### ISSUE TITLE
Google Contact app is missing android.permission.BACKUP from GMS

### ISSUE THREAD

**Issue by thelittlefireman** [GrapheneOS/os-issue-tracker#1018]
I try to restore my contacts on my Pixel 6 pro from an other phone, but when i hit the "restore" button on com.google.android.contacts app, GMS show me a toast with : "Impossible to recovered contacts to restore for now"
And in the logcat i've got this crash message : 

```
02-27 12:27:25.982  1450  1880 W InputManager-JNI: Input channel object '306858a Toast (client)' was disposed without first being removed with the input manager!
02-27 12:27:25.993  1450  1704 W NotificationService: Toast already killed. pkg=com.google.android.gms token=android.os.BinderProxy@7468b73
02-27 12:27:27.772  3424   455 E Backup  : [BackupManagerWrapper] Google Play Services doesn't have permission android.permission.BACKUP
02-27 12:27:27.772  3424   455 E Backup  : [RequestGmsModuleRestore] Couldn't start restore session.
02-27 12:27:27.772  3424   455 E Backup  : [RequestGmsModuleRestore] Failure, status=8 message=INTERNAL_ERROR
02-27 12:27:27.784 31588 31588 E CRSActivity: Getting contact counts failed [CONTEXT service_id=135 ]
02-27 12:27:27.784 31588 31588 E CRSActivity: ufg: 8: 
02-27 12:27:27.784 31588 31588 E CRSActivity:   at ukx.b(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:27:27.784 31588 31588 E CRSActivity:   at ukx.a(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:27:27.784 31588 31588 E CRSActivity:   at ptj.a(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:27:27.784 31588 31588 E CRSActivity:   at ujl.ej(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:27:27.784 31588 31588 E CRSActivity:   at edy.onTransact(:com.google.android.gms@220221044@22.02.21 (190400-428111784):8)
02-27 12:27:27.784 31588 31588 E CRSActivity:   at android.os.Binder.execTransactInternal(Binder.java:1205)
02-27 12:27:27.784 31588 31588 E CRSActivity:   at android.os.Binder.execTransact(Binder.java:1163)
02-27 12:27:27.982   989   989 D AOC     : A3:MSG: lsm6dsr_device.cc, 760: USF: Lsm6dsrDevice: Sensor 4: Enabled 0, odr_index 0.
02-27 12:27:27.983   989   989 D AOC     : A3:MSG: lsm6dsr_fifo.cc, 746: USF: Lsm6dsrFifo: ODR: XL/G/T/TS: 52/52/13/6 WM: 4 Intr: 31.
02-27 12:27:27.983   989   989 D AOC     : A3:MSG: lsm6dsr_device.cc, 667: USF: Lsm6dsrDevice: Fifo was disabled for 959961ns.
02-27 12:27:27.984   989   989 D AOC     : A3:MSG: usf_sensor.cc, 1303: USF: Received start sampling request for LSM6DSR Motion Detect.
02-27 12:27:27.985   989   989 D AOC     : A3:MSG: lsm6dsr_device.cc, 760: USF: Lsm6dsrDevice: Sensor 3: Enabled 1, odr_index 1.
02-27 12:27:27.985   989   989 D AOC     : A3:MSG: lsm6dsr_fifo.cc, 746: USF: Lsm6dsrFifo: ODR: XL/G/T/TS: 52/52/13/6 WM: 4 Intr: 31.
02-27 12:27:27.986   989   989 D AOC     : A3:MSG: lsm6dsr_device.cc, 667: USF: Lsm6dsrDevice: Fifo was disabled for 672608ns.
02-27 12:27:27.987   989   989 D AOC     : A3:MSG: usf_sensor.cc, 1310: USF: Received stop sampling request for LSM6DSR Accelerometer.
02-27 12:27:27.987   989   989 D AOC     : A3:MSG: usf_sensor.cc, 1310: USF: Received stop sampling request for LSM6DSR Stationary Detect.
02-27 12:27:27.988   989   989 D AOC     : A3:ERR: usf_sensor.cc, 1770: USF: Sampling configuration 154101 not found.
02-27 12:27:30.160   462   508 D display : setActiveConfigWithConstraints:: PrimaryDisplay config(35)
02-27 12:27:30.164  1450  1493 I DisplayDeviceRepository: Display device changed: DisplayDeviceInfo{"Écran intégré": uniqueId="local:XXXXXXXXXXXXXXXXX", 1440 x 3120, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1440, height=3120, fps=60.0, alternativeRefreshRates=[120.00001]}, {id=2, width=1440, height=3120, fps=120.00001, alternativeRefreshRates=[60.0]}], colorMode 0, suppor
```

I try to `adb shell pm grant com.google.android.gms android.permission.BACKUP`
but BACKUP permission is not a changeable permission type.

```
Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.BACKUP requested by com.google.android.gms is not a changeable permission type
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1508)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1436)
        at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:380)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2384)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:260)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:24743)
        at android.os.Binder.shellCommand(Binder.java:961)
        at android.os.Binder.onTransact(Binder.java:845)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8840)
        at android.os.Binder.execTransactInternal(Binder.java:1205)
        at android.os.Binder.execTransact(Binder.java:1163)
```

Same things on automatic contact synchronization

```
02-27 12:46:58.881 31109   932 W SQLiteLog: (28) double-quoted string literal: "com.google"
02-27 12:46:58.882 31109   932 W SQLiteLog: (28) double-quoted string literal: "com.google"
02-27 12:46:58.887 31109   937 W SQLiteLog: (28) double-quoted string literal: "com.google"
02-27 12:46:58.904 31109 31136 W SQLiteLog: (28) double-quoted string literal: "com.google"
02-27 12:46:58.907  3424   441 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-27 12:46:58.907  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:46:58.907  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:58.912 31109 31136 W SQLiteLog: (28) double-quoted string literal: "com.google"
02-27 12:46:58.932  3424   441 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-27 12:46:58.932  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:46:58.932  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:58.992 31109 31136 W SQLiteLog: (28) double-quoted string literal: "com.google"
02-27 12:46:59.015  3424   441 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-27 12:46:59.015  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:46:59.015  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:59.062  3424   441 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-27 12:46:59.063  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:46:59.063  3424   441 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:59.155 31588  1280 D OpenGLRenderer: endAllActiveAnimators on 0xb400dc51c2c84500 (RippleDrawable) with handle 0xb400dc400cd1fe10
02-27 12:46:59.169  3424  3662 I DeviceBackupsUtil: Filtered Footprints backup with SDK version: 29 [CONTEXT service_id=135 ]
02-27 12:46:59.169  3424  3662 I DeviceBackupsUtil: Filtered Footprints backup with SDK version: 29 [CONTEXT service_id=135 ]
02-27 12:46:59.184  3424  3670 E Backup  : [BackupManagerWrapper] Google Play Services doesn't have permission android.permission.BACKUP
02-27 12:46:59.188  3424  3670 E Backup  : [LegacyBackupAccountManager] Fail to get legacy transport context.
02-27 12:46:59.188  3424  3670 E Backup  : android.content.pm.PackageManager$NameNotFoundException: Application package com.google.android.backup not found
02-27 12:46:59.188  3424  3670 E Backup  :      at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2543)
02-27 12:46:59.188  3424  3670 E Backup  :      at android.app.ContextImpl.createPackageContext(ContextImpl.java:2508)
02-27 12:46:59.188  3424  3670 E Backup  :      at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:1000)
02-27 12:46:59.188  3424  3670 E Backup  :      at pun.<init>(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:46:59.188  3424  3670 E Backup  :      at puk.a(:com.google.android.gms@220221044@22.02.21 (190400-428111784):16)
02-27 12:46:59.188  3424  3670 E Backup  :      at prs.a(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:59.188  3424  3670 E Backup  :      at prv.d(:com.google.android.gms@220221044@22.02.21 (190400-428111784):4)
02-27 12:46:59.188  3424  3670 E Backup  :      at prv.a(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:59.188  3424  3670 E Backup  :      at azaw.call(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:59.188  3424  3670 E Backup  :      at bfcb.run(:com.google.android.gms@220221044@22.02.21 (190400-428111784):1)
02-27 12:46:59.188  3424  3670 E Backup  :      at vpo.c(:com.google.android.gms@220221044@22.02.21 (190400-428111784):6)
02-27 12:46:59.188  3424  3670 E Backup  :      at vpo.run(:com.google.android.gms@220221044@22.02.21 (190400-428111784):7)
02-27 12:46:59.188  3424  3670 E Backup  :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-27 12:46:59.188  3424  3670 E Backup  :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-27 12:46:59.188  3424  3670 E Backup  :      at vur.run(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:59.188  3424  3670 E Backup  :      at java.lang.Thread.run(Thread.java:920)
02-27 12:46:59.196  3424  3424 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.backup.GMS_MODULE_RESTORE cmp=com.google.android.gms/.chimera.GmsInternalBoundBrokerService }
02-27 12:46:59.196  3424  3424 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.backup.GMS_MODULE_RESTORE cmp=com.google.android.gms/.chimera.GmsInternalBoundBrokerService }
02-27 12:46:59.209  3424  3424 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
02-27 12:46:59.209  3424  3424 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
02-27 12:46:59.212  3424  3424 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
02-27 12:46:59.247  3424  1309 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-27 12:46:59.249  3424  1309 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:46:59.249  3424  1309 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)
02-27 12:46:59.275  3424  1309 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-27 12:46:59.276  3424  1309 W Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):2)
02-27 12:46:59.276  3424  1309 W Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@220221044@22.02.21 (190400-428111784):0)


``` 

Could it be possible to fix this ?
Thansk

**Comment by Zanthed** [comment]
It's possible this permission being granted would fix the issue that people have when trying to sync contacts from their Google account using Google Contacts, but this doesn't seem to be a runtime permission and is a privileged permission we don't want to give.

Might have to be looked into.

cc @muhomorr

**Comment by thestinger** [comment]
We definitely can't grant this kind of privileged permission.

**Comment by thelittlefireman** [comment]
and is there a way to bypass it ? it's seem to be looking for a legacy package com.google.android.backup, could it be possible to mock it ?

**Comment by thestinger** [comment]
Not planned/
