### ISSUE TITLE
Unable to use Woop app

### ISSUE THREAD

**Issue by odlg** [GrapheneOS/os-issue-tracker#1101]
A scouting app called Woop is not usable. I cannot see if it is caused by missing Android 12 compatibility or it is GrapheneOS specific. I sse this via adb logcat

```
04-02 11:09:17.800 31673 31816 W DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
04-02 11:09:17.805 31673 31816 I DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
04-02 11:09:17.805 31673 31816 I DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 6
04-02 11:09:17.807 31673 31816 W nodes.woopapp: Failed to determine odex file name: Dex location /proc/self/fd/177 has no extension.
04-02 11:09:17.802 31673 31673 W androidmapsapi-: type=1400 audit(0.0:371614): avc: denied { write } for name="fd" dev="proc" ino=3348065 scontext=u:r:untrusted_app:s0:c119,c256,c522,c768 tcontext=u:r:untrusted_app:s0:c119,c256,c522,c768 tclass=dir permissive=0
04-02 11:09:17.831 31673 31786 W ProtoDataStoreFlagStore: Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#nodes.woopapp, using defaults.
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: Unable to update local snapshot for com.google.android.libraries.consentverifier#nodes.woopapp, may result in stale flags.
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=nodes.woopapp, sha256=[0de99ce53079b5238ee2eb591ff70d759dacd9cd89e073df93a459e0089244ba], atk=false, ver=220618044.true (go/gsrlt)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at agj.s(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):3)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at agj.get(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):2)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at ain.a(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):1)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at aht.g(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):1)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at wn.d(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):1)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at xu.run(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):0)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at java.lang.Thread.run(Thread.java:920)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=nodes.woopapp, sha256=[0de99ce53079b5238ee2eb591ff70d759dacd9cd89e073df93a459e0089244ba], atk=false, ver=220618044.true (go/gsrlt)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.Parcel.createException(Parcel.java:2410)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.Parcel.readException(Parcel.java:2393)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.Parcel.readException(Parcel.java:2335)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at dy.aZ(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):2)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at qk.a(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):4)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at ic.e(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):2)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at jb.t(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):2)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at jb.u(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):3)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at jb.e(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):2)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at jf.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@220618097@22.06.18 (190400-0):69)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.Looper.loopOnce(Looper.java:201)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.Looper.loop(Looper.java:288)
04-02 11:09:17.835 31673 31788 W ProtoDataStoreFlagStore: 	at android.os.HandlerThread.run(HandlerThread.java:67)
04-02 11:09:18.019 31673 31716 D TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=FIREPERF for destination cct
```

**Comment by muhomorr** [comment]
Explain the issue in more detail. I don't see any issues with this app on my end.
Are you on the latest GrapheneOS version (2022033013)?

**Comment by odlg** [comment]
Yes, I am on 2022033013 on a Pixel 6. I am using the Woop app in a Work profile with Sandboxed Play services. 

To reproduce the issue (I think the app is only danish - sorry) 

1. Press 'Log på som gæst' - log on as guest
2. Enter some unique user Id in the field 'Vælg brugernavn' and press 'Log på som gæst' - log on as guest
3. Now press 'Find jagt' - search for a hunt. - after this a spinner starts trying to list hunts.This produces the error above on my phone.

Trying to make the recipe as simple as possible, behaviour has changed, and the app hangs at the splash screen logging this:
```
04-02 13:01:17.159  1603 10566 I ActivityManager: Done dumping
04-02 13:01:17.218  1603 10566 E ActivityManager: ANR in nodes.woopapp (nodes.woopapp/.feature.splash.SplashActivity)
04-02 13:01:17.218  1603 10566 E ActivityManager: PID: 10446
04-02 13:01:17.218  1603 10566 E ActivityManager: Reason: Input dispatching timed out (f5adcaf nodes.woopapp/nodes.woopapp.feature.splash.SplashActivity (server) is not responding. Waited 5005ms for FocusEvent(hasFocus=true))
04-02 13:01:17.218  1603 10566 E ActivityManager: Parent: nodes.woopapp/.feature.splash.SplashActivity
04-02 13:01:17.218  1603 10566 E ActivityManager: Frozen: false
04-02 13:01:17.218  1603 10566 E ActivityManager: Load: 2.99 / 2.92 / 2.74
04-02 13:01:17.218  1603 10566 E ActivityManager: ----- Output from /proc/pressure/memory -----
04-02 13:01:17.218  1603 10566 E ActivityManager: some avg10=0.02 avg60=0.20 avg300=0.14 total=106729885
04-02 13:01:17.218  1603 10566 E ActivityManager: full avg10=0.00 avg60=0.10 avg300=0.06 total=50102604
04-02 13:01:17.218  1603 10566 E ActivityManager: ----- End output from /proc/pressure/memory -----
04-02 13:01:17.218  1603 10566 E ActivityManager: 
04-02 13:01:17.218  1603 10566 E ActivityManager: CPU usage from 0ms to 8249ms later (2022-04-02 13:01:08.910 to 2022-04-02 13:01:17.159):
04-02 13:01:17.218  1603 10566 E ActivityManager:   100% 3322/app.grapheneos.gmscompat: 100% user + 0.4% kernel / faults: 806 minor 120 major
04-02 13:01:17.218  1603 10566 E ActivityManager:   22% 1603/system_server: 9.8% user + 12% kernel / faults: 22489 minor
04-02 13:01:17.218  1603 10566 E ActivityManager:   11% 8588/com.aurora.store: 7.3% user + 4.2% kernel / faults: 3729 minor
04-02 13:01:17.218  1603 10566 E ActivityManager:   11% 1996/com.android.systemui: 5.9% user + 5.2% kernel / faults: 20609 minor
04-02 13:01:17.218  1603 10566 E ActivityManager:   9.6% 4321/org.dslul.openboard.inputmethod.latin: 6.1% user + 3.5% kernel / faults: 5744 minor 33 major
04-02 13:01:17.218  1603 10566 E ActivityManager:   6.1% 31616/org.dslul.openboard.inputmethod.latin: 4.2% user + 1.9% kernel / faults: 3114 minor 11 major
04-02 13:01:17.218  1603 10566 E ActivityManager:   4.9% 572/surfaceflinger: 1.9% user + 3% kernel / faults: 586 minor
04-02 13:01:17.218  1603 10566 E ActivityManager:   0.6% 1108/media.swcodec: 0.2% user + 0.3% kernel / faults: 6590 minor 19 major
04-02 13:01:17.218  1603 10566 E ActivityManager:   2.6% 2422/com.android.phone: 1.8% user + 0.8% kernel / faults: 3056 minor 72 major
04-02 13:01:17.218  1603 10566 E ActivityManager:   2.4% 14/rcuog/0: 0% user + 2.4% kernel
04-02 13:01:17.218  1603 10566 E ActivityManager:   2.4% 1063/media.extractor: 1% user + 1.3% kernel / faults: 4133 minor
04-02 13:01:17.218  1603 10566 E ActivityManager:   2.1% 10446/nodes.woopapp: 1.4% user + 0.7% kernel / faults: 4432 minor
04-02 13:01:17.218  1603 10566 E ActivityManager:   1.9% 1154/adbd: 0.1% user + 1.8% kernel / faults: 170 minor
```
and a lot more lines.

**Comment by muhomorr** [comment]
Can you send me a full logcat? (`adb logcat -d -v uid > logcat.txt`)

**Comment by odlg** [comment]
I rebooted my phone and now it just works without troubles. I have so far been unable to reproduce it.

When having the troubles I did reinstall the app several times, also clearing the apps storage and cache - but the problems persisted. I do not like that a reboot fixes it like that :-(
