### ISSUE TITLE
Play Store crash when opening "Permissions for unused apps" in Play Protect Settings

### ISSUE THREAD

**Issue by ghost** [GrapheneOS/os-issue-tracker#1126]
Play Store -> go to your account icon in the top right -> Play Protect -> Settings icon in the top right -> click the "Permissions for unused apps" section

```
--------- beginning of crash
04-14 14:58:02.564 13179 13179 E AndroidRuntime: FATAL EXCEPTION: main
04-14 14:58:02.564 13179 13179 E AndroidRuntime: Process: com.android.vending, PID: 13179
04-14 14:58:02.564 13179 13179 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.ManagePermissionsActivity}; have you declared this activity in your AndroidManifest.xml?
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2119)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1766)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5413)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at fln.startActivityForResult(PG:2)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5371)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:5757)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:5710)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at nsc.ak(PG:16)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at nsc.I(PG:38)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at qgp.r(PG:11)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at androidx.preference.Preference.C(PG:3)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at androidx.preference.Preference.b(Unknown Source:0)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at ho.onClick(PG:55)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.view.View.performClick(View.java:7455)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7432)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.view.View.access$3700(View.java:835)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28810)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:48)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-14 14:58:02.564 13179 13179 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
04-14 14:58:02.564 13179 13179 W Finsky.CrashDetector: Crash at version: 29.8.23-21 [0] [PR] 438919558.
04-14 14:58:02.565 13179 13179 E AndroidRuntime: Error reporting crash
04-14 14:58:02.565 13179 13179 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:571)
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5351)
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at glv.uncaughtException(PG:6)
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-14 14:58:02.565 13179 13179 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
04-14 14:58:02.565 13179 13179 I Process : Sending signal. PID: 13179 SIG: 9
```

**Comment by flawedworld** [comment]
This is due to Google shipping a proprietary fork of PermissionController [com.google.android.permissioncontroller] and AOSP uses [com.android.permissioncontroller]
