### ISSUE TITLE
[GmsCompat] Issues with Google Apps

### ISSUE THREAD

**Issue by rand64** [GrapheneOS/os-issue-tracker#1179]
Hello,

This issue has started recently, and when using my phone (P6P), I am unable to launch any of these apps:

- Google Maps (Loads the UI sometimes, but crashes immediately)
- Google Voice (Loads the UI, but returns: Error loading conversations, please try again)
- Youtube loads the starting ui (Red Play Button) but goes no further
- Youtube Music loads the starting ui (Red Play Button) but goes no further

Build: SP2A.220505.002.2022050301
Profile: Secondary (Only used for Google Apps when needed)

If I uninstall all the compatibility apps, the apps then load fine (can see the menus and everything in the background) but unable to use them due to not having the framework installed.

**Comment by rand64** [comment]
Google Voice (LogCat)

```
05-08 03:18:00.678 20792 20825 E mqf     : java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{490d4b7 20792:com.google.android.apps.googlevoice/u10a145} (pid=20792, uid=1010145) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.createException(Parcel.java:2410)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.readException(Parcel.java:2393)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.readException(Parcel.java:2335)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5907)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7010)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3388)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2542)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1214)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1155)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1111)
05-08 03:18:00.678 20792 20825 E mqf     : 	at htk.e(PG:19)
05-08 03:18:00.678 20792 20825 E mqf     : 	at htk.d(PG:4)
05-08 03:18:00.678 20792 20825 E mqf     : 	at cxw.a(PG:154)
05-08 03:18:00.678 20792 20825 E mqf     : 	at luw.a(PG:2)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqb.d(PG:2)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqc.run(PG:9)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.o(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.b(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqc.f(PG:3)
05-08 03:18:00.678 20792 20825 E mqf     : 	at doc.b(PG:7)
05-08 03:18:00.678 20792 20825 E mqf     : 	at dep.apply(PG:45)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.m.accept(SourceFile:50)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.a.forEachRemaining(SourceFile:19)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.c.X(SourceFile:20)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.c.n0(SourceFile:10)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.u1.c(Unknown Source:4)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.c.q0(SourceFile:34)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.d2.collect(SourceFile:85)
05-08 03:18:00.678 20792 20825 E mqf     : 	at eov.b(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at djo.a(PG:37)
05-08 03:18:00.678 20792 20825 E mqf     : 	at eqk.a(PG:78)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqn.a(PG:11)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqa.d(PG:2)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqc.run(PG:9)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.o(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.j(PG:12)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpq.run(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrf.c(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrf.b(PG:3)
05-08 03:18:00.678 20792 20825 E mqf     : 	at msh.done(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.set(FutureTask.java:234)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mss.run(PG:4)
05-08 03:18:00.678 20792 20825 E mqf     : 	at huv.run(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-08 03:18:00.678 20792 20825 E mqf     : 	at hsy.run(PG:86)
05-08 03:18:00.678 20792 20825 E mqf     : 	at huh.run(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.lang.Thread.run(Thread.java:920)
05-08 03:18:00.678 20792 20825 E mqf     : Got more than one input Future failure. Logging failures after the first
05-08 03:18:00.678 20792 20825 E mqf     : java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{490d4b7 20792:com.google.android.apps.googlevoice/u10a145} (pid=20792, uid=1010145) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.createException(Parcel.java:2410)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.readException(Parcel.java:2393)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.os.Parcel.readException(Parcel.java:2335)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5907)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7010)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3388)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2542)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1214)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1155)
05-08 03:18:00.678 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1111)
05-08 03:18:00.678 20792 20825 E mqf     : 	at htk.e(PG:19)
05-08 03:18:00.678 20792 20825 E mqf     : 	at htk.d(PG:4)
05-08 03:18:00.678 20792 20825 E mqf     : 	at cxw.a(PG:154)
05-08 03:18:00.678 20792 20825 E mqf     : 	at luw.a(PG:2)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqb.d(PG:2)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqc.run(PG:9)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.o(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.b(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqc.f(PG:3)
05-08 03:18:00.678 20792 20825 E mqf     : 	at doc.b(PG:7)
05-08 03:18:00.678 20792 20825 E mqf     : 	at dep.apply(PG:45)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.m.accept(SourceFile:50)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.a.forEachRemaining(SourceFile:19)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.c.X(SourceFile:20)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.c.n0(SourceFile:10)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.u1.c(Unknown Source:4)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.c.q0(SourceFile:34)
05-08 03:18:00.678 20792 20825 E mqf     : 	at j$.util.stream.d2.collect(SourceFile:85)
05-08 03:18:00.678 20792 20825 E mqf     : 	at eov.b(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at djo.a(PG:37)
05-08 03:18:00.678 20792 20825 E mqf     : 	at eqk.a(PG:78)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqn.a(PG:11)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqa.d(PG:2)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mqc.run(PG:9)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.o(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpy.j(PG:12)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mpq.run(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrf.c(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mrf.b(PG:3)
05-08 03:18:00.678 20792 20825 E mqf     : 	at msh.done(PG:1)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.set(FutureTask.java:234)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
05-08 03:18:00.678 20792 20825 E mqf     : 	at mss.run(PG:4)
05-08 03:18:00.678 20792 20825 E mqf     : 	at huv.run(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-08 03:18:00.678 20792 20825 E mqf     : 	at hsy.run(PG:86)
05-08 03:18:00.678 20792 20825 E mqf     : 	at huh.run(PG:5)
05-08 03:18:00.678 20792 20825 E mqf     : 	at java.lang.Thread.run(Thread.java:920)
05-08 03:18:00.679 20792 20825 E mqf     : Got more than one input Future failure. Logging failures after the first
05-08 03:18:00.679 20792 20825 E mqf     : java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{490d4b7 20792:com.google.android.apps.googlevoice/u10a145} (pid=20792, uid=1010145) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.os.Parcel.createException(Parcel.java:2410)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.os.Parcel.readException(Parcel.java:2393)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.os.Parcel.readException(Parcel.java:2335)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5907)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7010)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3388)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2542)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1214)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1155)
05-08 03:18:00.679 20792 20825 E mqf     : 	at android.content.ContentResolver.query(ContentResolver.java:1111)
05-08 03:18:00.679 20792 20825 E mqf     : 	at htk.e(PG:19)
05-08 03:18:00.679 20792 20825 E mqf     : 	at htk.d(PG:4)
05-08 03:18:00.679 20792 20825 E mqf     : 	at cxw.a(PG:154)
05-08 03:18:00.679 20792 20825 E mqf     : 	at luw.a(PG:2)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mqb.d(PG:2)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mqc.run(PG:9)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mpy.o(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mpy.b(PG:5)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mqc.f(PG:3)
05-08 03:18:00.679 20792 20825 E mqf     : 	at doc.b(PG:7)
05-08 03:18:00.679 20792 20825 E mqf     : 	at dep.apply(PG:45)
05-08 03:18:00.679 20792 20825 E mqf     : 	at j$.util.stream.m.accept(SourceFile:50)
05-08 03:18:00.679 20792 20825 E mqf     : 	at j$.util.a.forEachRemaining(SourceFile:19)
05-08 03:18:00.679 20792 20825 E mqf     : 	at j$.util.stream.c.X(SourceFile:20)
05-08 03:18:00.679 20792 20825 E mqf     : 	at j$.util.stream.c.n0(SourceFile:10)
05-08 03:18:00.679 20792 20825 E mqf     : 	at j$.util.stream.u1.c(Unknown Source:4)
05-08 03:18:00.679 20792 20825 E mqf     : 	at j$.util.stream.c.q0(SourceFile:34)
05-08 03:18:00.679 20792 20825 E mqf     : 	at j$.util.stream.d2.collect(SourceFile:85)
05-08 03:18:00.679 20792 20825 E mqf     : 	at eov.b(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at djo.a(PG:37)
05-08 03:18:00.679 20792 20825 E mqf     : 	at eqk.a(PG:78)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mqn.a(PG:11)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mqa.d(PG:2)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mqc.run(PG:9)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mpy.o(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mpy.j(PG:12)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mpq.run(PG:5)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mrd.execute(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mrf.c(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mrf.b(PG:3)
05-08 03:18:00.679 20792 20825 E mqf     : 	at msh.done(PG:1)
05-08 03:18:00.679 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-08 03:18:00.679 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.set(FutureTask.java:234)
05-08 03:18:00.679 20792 20825 E mqf     : 	at java.util.concurrent.FutureTask.run(FutureTask.java:274)
05-08 03:18:00.679 20792 20825 E mqf     : 	at mss.run(PG:4)
05-08 03:18:00.679 20792 20825 E mqf     : 	at huv.run(PG:5)
05-08 03:18:00.679 20792 20825 E mqf     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-08 03:18:00.679 20792 20825 E mqf     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-08 03:18:00.679 20792 20825 E mqf     : 	at hsy.run(PG:86)
05-08 03:18:00.679 20792 20825 E mqf     : 	at huh.run(PG:5)
05-08 03:18:00.679 20792 20825 E mqf     : 	at java.lang.Thread.run(Thread.java:920)
05-08 03:18:00.679 20792 20825 E mqf     : Got more than one input Future failure. Logging failures after the first
05-08 03:18:00.679 20792 20825 E mqf     : java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{490d4b7 20792:com.google.android.apps.googlevoice/u10a145} (pid=20792, uid=1010145) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
```

**Comment by thestinger** [comment]
You must have uninstalled the Google Play apps and then reinstalled them. This means you broke all the apps depending on them, since they need to be installed afterwards. Google Maps not working with location rerouting in the current Stable channel release is a known issue resolved by the latest Beta channel release which will be in Stable soon.
