### ISSUE TITLE
Bluetooth communication requires giving 'phone' permission to Google Play Services

### ISSUE THREAD

**Issue by lbschenkel** [GrapheneOS/os-issue-tracker#1309]
I am not sure if this is a bug (most probably not), but yet I want to report it because it might be something that could be improved in GmsCompat in future versions.

I am running GrapheneOS version SQ3A.220705.003.A1.2022070600 with Play Services installed. I have installed the [GoPro app](https://play.google.com/store/apps/details?id=com.gopro.smarty) version 10.19.1 (12787) and tried to connect it to a GoPro camera via Bluetooth. It finds the camera, but when I press "Connect" the app crashes.

I took a look at logcat (dump is below) and given the stack trace I eventually found out that it was Google Play Services that was crashing — the reason for why it crashes is because I did not have granted 'phone' permission to it. Once I granted that permission, no more crashes and the Bluetooth communication worked. (I tried other permissions but they didn't make any difference, only 'phone' did.)

So far I never had to grant this permission to Play Services and all the apps I have work fine. I was hoping I could get by without it. I am not quite sure why granting 'phone' permission to Play Services is needed for Bluetooth communication.

Anyway, I understand that Google Play Services is what it is but I'm reporting this anyway in the hope that new shims could be added to GmsCompat in the future to make this code path in Play Services work without this permission being granted.

Excerpt from logcat:
```
07-12 11:41:17.768 28562 28562 E AndroidRuntime: FATAL EXCEPTION: main
07-12 11:41:17.768 28562 28562 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 28562
07-12 11:41:17.768 28562 28562 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.google.android.gms.nearby.discovery.service.DiscoveryService: java.lang.SecurityException: listen
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4573)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:257)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2111)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7876)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: Caused by: java.lang.SecurityException: listen
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2427)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2411)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2394)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2336)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.telephony.TelephonyRegistryManager.listenFromCallback(TelephonyRegistryManager.java:270)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.telephony.TelephonyRegistryManager.registerTelephonyCallback(TelephonyRegistryManager.java:1175)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.telephony.TelephonyManager.registerTelephonyCallback(TelephonyManager.java:15352)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at asoi.k(:com.google.android.gms@222413044@22.24.13 (190400-455379205):6)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at audx.e(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at audx.c(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at asgk.a(:com.google.android.gms@222413044@22.24.13 (190400-455379205):110)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at arnh.i(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at arnh.d(:com.google.android.gms@222413044@22.24.13 (190400-455379205):0)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at arnh.b(:com.google.android.gms@222413044@22.24.13 (190400-455379205):1)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at arnh.c(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.google.android.gms.nearby.discovery.service.DiscoveryChimeraService.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):16)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at fbp.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):1)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at uqn.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):4)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4560)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	... 11 more
07-12 11:41:17.768 28562 28562 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.telephony.TelephonyPermissions.enforceCarrierPrivilege(TelephonyPermissions.java:645)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.telephony.TelephonyPermissions.checkReadPhoneState(TelephonyPermissions.java:149)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadPhoneState(TelephonyPermissions.java:94)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.server.TelephonyRegistry.checkListenerPermission(TelephonyRegistry.java:3195)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 	at com.android.server.TelephonyRegistry.listen(TelephonyRegistry.java:1025)
07-12 11:41:17.768 28562 28562 E AndroidRuntime: 
07-12 11:41:19.497 28778 28778 E AndroidRuntime: FATAL EXCEPTION: main
07-12 11:41:19.497 28778 28778 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 28778
07-12 11:41:19.497 28778 28778 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.google.android.gms.nearby.discovery.service.DiscoveryService: java.lang.SecurityException: listen
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4573)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:257)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2111)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7876)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: Caused by: java.lang.SecurityException: listen
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2427)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2411)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2394)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2336)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.telephony.TelephonyRegistryManager.listenFromCallback(TelephonyRegistryManager.java:270)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.telephony.TelephonyRegistryManager.registerTelephonyCallback(TelephonyRegistryManager.java:1175)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.telephony.TelephonyManager.registerTelephonyCallback(TelephonyManager.java:15352)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at asoi.k(:com.google.android.gms@222413044@22.24.13 (190400-455379205):6)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at audx.e(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at audx.c(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at asgk.a(:com.google.android.gms@222413044@22.24.13 (190400-455379205):110)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at arnh.i(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at arnh.d(:com.google.android.gms@222413044@22.24.13 (190400-455379205):0)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at arnh.b(:com.google.android.gms@222413044@22.24.13 (190400-455379205):1)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at arnh.c(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at com.google.android.gms.nearby.discovery.service.DiscoveryChimeraService.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):16)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at fbp.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):1)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at uqn.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):4)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4560)
07-12 11:41:19.497 28778 28778 E AndroidRuntime: 	... 11 more
07-12 11:41:19.497 28778 28826 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
07-12 11:41:19.497 28778 28826 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 28778
07-12 11:41:19.497 28778 28826 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:571)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.INetworkManagementService$Stub$Proxy.setUidCleartextNetworkPolicy(INetworkManagementService.java:2274)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.StrictMode.setVmPolicy(StrictMode.java:2090)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at wuq.a(:com.google.android.gms@222413044@22.24.13 (190400-455379205):15)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at wup.e(:com.google.android.gms@222413044@22.24.13 (190400-455379205):4)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at wtq.r(:com.google.android.gms@222413044@22.24.13 (190400-455379205):16)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at wtq.x(:com.google.android.gms@222413044@22.24.13 (190400-455379205):2)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at bocc.x(:com.google.android.gms@222413044@22.24.13 (190400-455379205):4)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at wcz.b(:com.google.android.gms@222413044@22.24.13 (190400-455379205):16)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at wdd.m(:com.google.android.gms@222413044@22.24.13 (190400-455379205):5)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at wdd.handleMessage(:com.google.android.gms@222413044@22.24.13 (190400-455379205):57)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at anox.ks(:com.google.android.gms@222413044@22.24.13 (190400-455379205):0)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at anox.dispatchMessage(:com.google.android.gms@222413044@22.24.13 (190400-455379205):11)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 	Suppressed: cfhm: 
07-12 11:41:19.497 28778 28826 E AndroidRuntime: 		at tk_trace.nearby-DiscoveryChimeraService_onCreate(Unknown Source:0)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: FATAL EXCEPTION: main
07-12 11:41:20.450 28864 28864 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 28864
07-12 11:41:20.450 28864 28864 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.google.android.gms.nearby.discovery.service.DiscoveryService: java.lang.SecurityException: listen
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4573)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:257)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2111)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7876)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: Caused by: java.lang.SecurityException: listen
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2427)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2411)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2394)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2336)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.telephony.TelephonyRegistryManager.listenFromCallback(TelephonyRegistryManager.java:270)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.telephony.TelephonyRegistryManager.registerTelephonyCallback(TelephonyRegistryManager.java:1175)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.telephony.TelephonyManager.registerTelephonyCallback(TelephonyManager.java:15352)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at asoi.k(:com.google.android.gms@222413044@22.24.13 (190400-455379205):6)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at audx.e(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at audx.c(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at asgk.a(:com.google.android.gms@222413044@22.24.13 (190400-455379205):110)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at arnh.i(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at arnh.d(:com.google.android.gms@222413044@22.24.13 (190400-455379205):0)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at arnh.b(:com.google.android.gms@222413044@22.24.13 (190400-455379205):1)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at arnh.c(:com.google.android.gms@222413044@22.24.13 (190400-455379205):3)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.google.android.gms.nearby.discovery.service.DiscoveryChimeraService.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):16)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at fbp.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):1)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at uqn.onCreate(:com.google.android.gms@222413044@22.24.13 (190400-455379205):4)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4560)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	... 11 more
07-12 11:41:20.450 28864 28864 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.telephony.TelephonyPermissions.enforceCarrierPrivilege(TelephonyPermissions.java:645)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.telephony.TelephonyPermissions.checkReadPhoneState(TelephonyPermissions.java:149)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadPhoneState(TelephonyPermissions.java:94)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.server.TelephonyRegistry.checkListenerPermission(TelephonyRegistry.java:3195)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 	at com.android.server.TelephonyRegistry.listen(TelephonyRegistry.java:1025)
07-12 11:41:20.450 28864 28864 E AndroidRuntime: 
07-12 11:48:34.575 29241 29272 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
07-12 11:48:34.575 29241 29272 E AndroidRuntime: Process: com.android.statementservice, PID: 29241
07-12 11:48:34.575 29241 29272 E AndroidRuntime: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at androidx.work.Data.toByteArrayInternal(Data.java:417)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at androidx.work.Data$Builder.build(Data.java:846)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-12 11:48:34.575 29241 29272 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)

```

**Comment by Zanthed** [comment]
That's how GoPro wrote the app, using Play services APIs to discover nearby devices.

`com.google.android.gms.nearby.discovery.service.DiscoveryChimeraService.onCreate`

It is possible to route these things to OS APIs (like geolocation, and in the future sensors) but I'm not 100% sure on this.

**Comment by lbschenkel** [comment]
> That's how GoPro wrote the app, using Play services APIs to discover nearby devices.

Yes, I realized that when I saw the crash in logcat.

> It is possible to route these things to OS APIs (like geolocation, and in the future sensors) but I'm not 100% sure on this.

This is what I hope for and motivated the reporting of this issue.

**Comment by lbschenkel** [comment]
> @lbschenkel The crash will be fixed with [GrapheneOS/platform_frameworks_base#223](https://github.com/GrapheneOS/platform_frameworks_base/pull/223)

Amazing! Thank you so much!
