### ISSUE TITLE
(most) VR apps crash/hang on a blank screen

### ISSUE THREAD

**Issue by Zanthed** [GrapheneOS/os-issue-tracker#1321]
User reported two apps on Play Store (com.rabbitmountain.underwatervr and com.GizmoVR.Virtual.Reality.Videos) that they tried to use with sandboxed Google Play (full proper installation) but it hangs on a blank screen. It's possible all VR apps may be broken but it's unconfirmed right now.

Logcat shows the app crashed and appears to be a Unity app. Nothing appears to have triggered this, no Java exceptions were noted, no permission issues, etc.

Snippet of com.rabbitmountain.underwatervr:

```
07-15 01:40:53.982 21219 21266 E CRASH   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000000034ed
07-15 01:40:53.982 21219 21266 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-15 01:40:53.982 21219 21266 E CRASH   : Build fingerprint: 'google/redfin/redfin:12/SQ3A.220705.003.A1/2022071300:user/release-keys'
07-15 01:40:53.982 21219 21266 E CRASH   : Revision: 'MP1.0'
07-15 01:40:53.982  4309  4309 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3220
07-15 01:40:53.982 21219 21266 E CRASH   : pid: 21219, tid: 21266, name: UnityMain  >>> com.rabbitmountain.underwatervr <<<
07-15 01:40:53.982 21219 21266 E CRASH   :     x0   0000000000000000  x1   0000000100000078  x2   0000000000000000  x3   0000000000000001
07-15 01:40:53.982 21219 21266 E CRASH   :     x4   0000000000000000  x5   0000c8130f6c7cd8  x6   0000c812fad23989  x7   0000c812facf21f7
07-15 01:40:53.982 21219 21266 E CRASH   :     x8   0000000000000000  x9   00000000ffffffff  x10  0000000000000001  x11  0000000000000001
07-15 01:40:53.982 21219 21266 E CRASH   :     x12  0000000100000078  x13  0000000000000000  x14  ffffffffffffffff  x15  0000c844654cf9c0
07-15 01:40:53.982 21219 21266 E CRASH   :     x16  0000c812fafc3e60  x17  0000c845962c9afc  x18  0000c812f91dc000  x19  0000c812fb0164f0
07-15 01:40:53.982 21219 21266 E CRASH   :     x20  b400c8194cdbc550  x21  0000c812fb0164f0  x22  0000c812fb016520  x23  0000000000000026
07-15 01:40:53.982 21219 21266 E CRASH   :     x24  0000c812fb013c90  x25  00000000000033bd  x26  0000000000000044  x27  6b4da45f8839c200
07-15 01:40:53.982 21219 21266 E CRASH   :     x28  00000000706aec70  x29  0000c8130f6c7e80  x30  0000c812fa3758c4
07-15 01:40:53.982 21219 21266 E CRASH   :     sp   0000c8130f6c7e30  pc   0000c812fa37591c  pstate 0000000020000000
07-15 01:40:53.982 21219 21266 E CRASH   : backtrace:
07-15 01:40:53.986  4309  4309 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2116 checkRepeatedly = false, unlocked = true
07-15 01:40:53.986  4309  4309 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1923 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.rabbitmountain.underwatervr fieldId=-1 fieldName=null extras=null}, false)
07-15 01:40:53.987  4309  4309 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2116 checkRepeatedly = true, unlocked = true
07-15 01:40:53.999 21219 21270 W com.rabbitmountain.underwatervr: Failed to determine odex file name: Dex location /gmscompat_fd_76 has no extension.
07-15 01:40:54.005 21219 21266 E CRASH   :      #00  pc 000000000065ee30  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #01  pc 000000000013ddcc  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #02  pc 0000000000002248  /apex/com.android.art/lib64/libsigchain.so (art::SignalChain::Handler(int, siginfo*, void*)+444)
07-15 01:40:54.005 21219 21266 E CRASH   :      #03  pc 00000000000004e0  [vdso] (__kernel_rt_sigreturn)
07-15 01:40:54.005 21219 21266 E CRASH   :      #04  pc 000000000015f91c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #05  pc 000000000015f4bc  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #06  pc 000000000015f42c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #07  pc 000000000015c824  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #08  pc 00000000000a4a28  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #09  pc 00000000000a4bf0  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #10  pc 00000000003ec384  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #11  pc 00000000003eca7c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #12  pc 00000000003ec170  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #13  pc 000000000015f8c4  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #14  pc 000000000015f4bc  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #15  pc 000000000015f42c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #16  pc 000000000015c824  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #17  pc 00000000000a4a28  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #18  pc 00000000000a4bf0  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #19  pc 00000000003ec384  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #20  pc 00000000003eca7c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #21  pc 00000000003ec170  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #22  pc 000000000015f8c4  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #23  pc 000000000015f4bc  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #24  pc 000000000015f42c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #25  pc 000000000015c824  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.005 21219 21266 E CRASH   :      #26  pc 000000000058b308  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.006 21219 21266 E CRASH   :      #27  pc 000000000058b29c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.006 21219 21266 E CRASH   :      #28  pc 000000000058b188  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.006 21219 21266 E CRASH   :      #29  pc 0000000000587c9c  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.006 21219 21266 E CRASH   :      #30  pc 00000000005851fc  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.006 21219 21266 E CRASH   :      #31  pc 0000000000586048  /data/app/~~Y1Js8gJC7WDuJaHDhjI7qQ==/com.rabbitmountain.underwatervr-bOPqRZnxRnCkyMzeIJcpSA==/lib/arm64/libunity.so
07-15 01:40:54.011 21219 21266 E MessageQueue: IdleHandler threw exception
07-15 01:40:54.011 21219 21266 E MessageQueue: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000000034ed
07-15 01:40:54.011 21219 21266 E MessageQueue: Build fingerprint: 'google/redfin/redfin:12/SQ3A.220705.003.A1/2022071300:user/release-keys'
07-15 01:40:54.011 21219 21266 E MessageQueue: Revision: 'MP1.0'
07-15 01:40:54.011 21219 21266 E MessageQueue: pid: 21219, tid: 21266, name: UnityMain  >>> com.rabbitmountain.underwatervr <<<
07-15 01:40:54.011 21219 21266 E MessageQueue:     x0   0000000000000000  x1   0000000100000078  x2   0000000000000000  x3   0000000000000001
07-15 01:40:54.011 21219 21266 E MessageQueue:     x4   0000000000000000  x5   0000c8130f6c7cd8  x6   0000c812fad23989  x7   0000c812facf21f7
07-15 01:40:54.011 21219 21266 E MessageQueue:     x8   0000000000000000  x9   00000000ffffffff  x10  0000000000000001  x11  0000000000000001
07-15 01:40:54.011 21219 21266 E MessageQueue:     x12  0000000100000078  x13  0000000000000000  x14  ffffffffffffffff  x15  0000c844654cf9c0
07-15 01:40:54.011 21219 21266 E MessageQueue:     x16  0000c812fafc3e60  x17  0000c845962c9afc  x18  0000c812f91dc000  x19  0000c812fb0164f0
07-15 01:40:54.011 21219 21266 E MessageQueue:     x20  b400c8194cdbc550  x21  0000c812fb0164f0  x22  0000c812fb016520  x23  0000000000000026
07-15 01:40:54.011 21219 21266 E MessageQueue:     x24  0000c812fb013c90  x25  00000000000033bd  x26  0000000000000044  x27  6b4da45f8839c200
07-15 01:40:54.011 21219 21266 E MessageQueue:     x28  00000000706aec70  x29  0000c8130f6c7e80  x30  0000c812fa3758c4
07-15 01:40:54.011 21219 21266 E MessageQueue:     sp   0000c8130f6c7e30  pc   0000c812fa37591c  pstate 0000000020000000
07-15 01:40:54.011 21219 21266 E MessageQueue:
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0065ee30(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0013ddcc(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libsigchain.art::SignalChain::Handler(int, siginfo*, void*)(SignalChain:444)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at [vdso].__kernel_rt_sigreturn(__kernel_rt_sigreturn:0)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f91c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f4bc(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f42c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015c824(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.000a4a28(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.000a4bf0(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.003ec384(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.003eca7c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.003ec170(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f8c4(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f4bc(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f42c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015c824(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.000a4a28(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.000a4bf0(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.003ec384(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.003eca7c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.003ec170(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f8c4(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f4bc(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015f42c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0015c824(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0058b308(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0058b29c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.0058b188(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.00587c9c(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.005851fc(Native Method)
07-15 01:40:54.011 21219 21266 E MessageQueue:  at libunity.00586048(Native Method)

```

I have a full bug report I can share to @muhomorr but we should focus on Android 13 for now.

**Comment by flawedworld** [comment]
Unity bug
