### ISSUE TITLE
Google Services didn't work and how I fix it

### ISSUE THREAD

**Issue by lessneek** [GrapheneOS/os-issue-tracker#1372]
All google services were installed from the GOS's Apps app and all worked well. But after upgrading of Google Services from Aurora Store (I guess so) all apps  (Signal, Instagram, etc.) which leveraged gs stopped to receive push-notifications. And Google Camera started to crash on launch. Deletion and reinstalling of google services from the GOS Apps didn't fix the problem. Only reinstalling the apps which uses gservices helped to fix the problem. So the question is: what was that? Is it some known problem?

```
type: crash
osVersion: google/oriole/oriole:12/SQ3A.220705.004/2022080900:user/release-keys
package: com.google.android.GoogleCamera:65075803
process: com.google.android.GoogleCamera

java.lang.RuntimeException: Unable to get provider com.google.android.apps.camera.contentprovider.CameraContentProvider: java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{498c1d2 9049:com.google.android.GoogleCamera/u0a124} (pid=9049, uid=10124) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
	at android.app.ActivityThread.installProvider(ActivityThread.java:7470)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6982)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6753)
	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2092)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{498c1d2 9049:com.google.android.GoogleCamera/u0a124} (pid=9049, uid=10124) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2427)
	at android.os.Parcel.createException(Parcel.java:2411)
	at android.os.Parcel.readException(Parcel.java:2394)
	at android.os.Parcel.readException(Parcel.java:2336)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5912)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7016)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3413)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2550)
	at android.content.ContentResolver.query(ContentResolver.java:1214)
	at android.content.ContentResolver.query(ContentResolver.java:1155)
	at android.content.ContentResolver.query(ContentResolver.java:1111)
	at iib.d(PG:1)
	at cak.<init>(PG:14)
	at clo.a(PG:2)
	at clr.a(PG:1)
	at bhz.get(PG:29)
	at msu.get(PG:1)
	at bxo.get(PG:5)
	at msu.get(PG:1)
	at com.google.android.apps.camera.legacy.app.app.CameraApp.d(PG:14)
	at com.google.android.apps.camera.legacy.app.app.CameraApp.initAppComponent(PG:2)
	at com.google.android.apps.camera.contentprovider.CameraContentProvider.onCreate(PG:3)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
	at com.google.android.apps.camera.contentprovider.CameraContentProvider.attachInfo(PG:1)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7465)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:611)
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:235)
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:125)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6104)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2465)


```

**Comment by thestinger** [comment]
This is what happens if you remove GSF is one or more profiles.

**Comment by thestinger** [comment]
Not specific to sandboxed Google Play, it's the same as the stock OS.

**Comment by lessneek** [comment]
Can I fix it somehow without reinstalling apps? Or registration of an app happens only on installation?

**Comment by thestinger** [comment]
You need to install GSF and then the apps depending on it. If you remove GSF from any profile, it breaks this across all profiles due to an upstream Android bug revoking these install permissions defined by apps across all profiles when it's uninstalled from one. That will get fixed in the future, but removing GSF will still break apps depending on it within the same profile. The within profile part is how it's intended to work. The cross profile part is an upstream AOSP bug not within the scope of our tracker since it impacts stock OS.

It has nothing to do with registration.
