### ISSUE TITLE
Google app crashing caused by screen transitions in the app

### ISSUE THREAD

**Issue by daniel4ka** [GrapheneOS/os-issue-tracker#1427]
I've noticed inconsistent crashing of the Google app caused by various screen transitions in the app, on a secondary user profile running full Google Play (Pixel 6, GrapheneOS 2022082400, Google Services Framework 32, Google Play services 222413044, Google Play Store 83111410, Google app 301206137), and reported through the "Sandboxed Google Play crashed" notification.

Several screen transition flows cause crashes sometimes, especially if I perform the back gesture, and especially if the back gesture happens at critical screen loading moments:

1. Google app settings > Notifications > Notifications you opted into
2. Google app settings > Personal results
3. Google app settings > Channels & Interests
4. Say "What are my notes" to the Google Assistant > Open one of the notes that show up

The beginning of the crash report always says: `java.lang.SecurityException: getPackagesForUid: UID ` *number* ` requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS to access user 0.`

Here's the crash report for the 1st screen transition flow described above, with the crash triggered by performing the back gesture a moment after opening the "Notifications you opted into" screen:

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.220624.021/2022082400:user/release-keys
package: com.google.android.googlequicksearchbox:301206137
process: com.google.android.googlequicksearchbox:search

java.lang.SecurityException: getPackagesForUid: UID <number> requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS to access user 0.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3012)
	at android.os.Parcel.createException(Parcel.java:2996)
	at android.os.Parcel.readException(Parcel.java:2979)
	at android.os.Parcel.readException(Parcel.java:2921)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackagesForUid(IPackageManager.java:4769)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1133)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1127)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:931)
	at android.app.ApplicationPackageManager.getPackagesForUid(ApplicationPackageManager.java:1146)
	at com.android.internal.gmscompat.GmsHooks.addRecentlyBoundPids(GmsHooks.java:255)
	at android.app.ActivityManager.getRunningAppProcesses(ActivityManager.java:3634)
	at com.google.android.libraries.performance.primes.d.a.c(PG:10)
	at com.google.android.libraries.performance.primes.c.d.a(PG:1)
	at com.google.android.libraries.performance.primes.c.d.onActivityStarted(PG:3)
	at android.app.Application.dispatchActivityStarted(Application.java:401)
	at android.app.Activity.dispatchActivityStarted(Activity.java:1406)
	at android.app.Activity.onStart(Activity.java:1928)
	at com.google.android.apps.gsa.velvet.ui.settings.a.onStart(PG:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1515)
	at android.app.Activity.performStart(Activity.java:8326)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3702)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.ComputerEngine.enforceCrossUserOrProfilePermission(ComputerEngine.java:2960)
	at com.android.server.pm.IPackageManagerBase.getPackagesForUid(IPackageManagerBase.java:655)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2180)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:5942)
	at android.os.Binder.execTransactInternal(Binder.java:1302)
```

**Comment by daniel4ka** [comment]
Solved in GrapheneOS 2022083000
