### ISSUE TITLE
Background crashes of MBank - Polish banking app

### ISSUE THREAD

**Issue by PatrykMis** [GrapheneOS/os-issue-tracker#1455]
Not sure if it's app-specific crash or GrapheneOS, but I've seen it only on GOS.

App link: https://play.google.com/store/apps/details?id=pl.mbank

Native Code Debugging disabled, all hardening settings unchanged. App does not crash when forground, only while doing other things in other apps (browsing internet etc.). Hard to reproduce because it crashes randomly: sometimes even half a day without crash, sometimes once a half hour. Main profile without GApps.

```
type: crash
osVersion: google/flame/flame:13/TP1A.220624.014/2022083000:user/release-keys
package: pl.mbank:48813
process: pl.mbank:d89daa35549d4163befdf4458cf3bde7:r.w

kotlin.UninitializedPropertyAccessException: lateinit property featureManager has not been initialized
	at pl.mbank.app.NmBApplication.r(ProGuard:1)
	at pl.mbank.app.NmBApplication.onLowMemory(ProGuard:1)
	at android.app.ActivityThread.handleLowMemory(ActivityThread.java:6358)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2209)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by PatrykMis** [comment]
Crash also reported to app developer.

**Comment by thestinger** [comment]
> kotlin.UninitializedPropertyAccessException: lateinit property featureManager has not been initialized

This is definitely an app bug, if it's the source of the crashes.

**Comment by thestinger** [comment]
I think the crash would occur elsewhere too and isn't tied to any kind of hardening done by GrapheneOS.
