### ISSUE TITLE
GMS crash in secondary profile

### ISSUE THREAD

**Issue by PatrykMis** [GrapheneOS/os-issue-tracker#1466]
This profile was loaded yestarday but it was inactive. When I switched into it today I have been surprised by the following crash. Then Play Store updated Play Services to the same version.

```
type: crash
osVersion: google/flame/flame:13/TP1A.220905.004/2022090600:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms.persistent

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
at beyi.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):12)
at bevf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
at xot.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):6)
at xot.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at xty.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
at java.lang.Thread.run(Thread.java:1012)
Suppressed: cfvr:
at tk_trace.ScheduledTaskImpl(Unknown Source:0)
at tk_trace.stats-PlatformStatsCollectorChimeraService_onRunTaskAsync(Unknown Source:0)
at tk_trace.scheduler-ServiceConnection_com.google.android.gms.stats.PlatformStatsCollectorService_onServiceConnected(Unknown Source:0)
at tk_trace.checkQueueLazily(Unknown Source:0)
at tk_trace.NetworkScheduler_alarmUp(Unknown Source:0)
at tk_trace.gcm-SchedulerInternalChimeraReceiver_onReceive(Unknown Source:0)
at tk_trace.gcm-GcmChimeraService_onCreate(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'long[] android.os.IStatsManagerService.getRegisteredExperimentIds()' on a null object reference
at anyg.apply(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at clmg.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at clmh.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
... 6 more
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'long[] android.os.IStatsManagerService.getRegisteredExperimentIds()' on a null object reference
at android.app.StatsManager.getRegisteredExperimentIds(StatsManager.java:476)
at binf.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
at bine.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):62)
at bilm.e(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
at bine.j(:com.google.android.gms@222615044@22.26.15 (190400-461192076):8)
at bine.b(:com.google.android.gms@222615044@22.26.15 (190400-461192076):26)
at bine.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):6)
at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):27)
at anyd.call(:com.google.android.gms@222615044@22.26.15 (190400-461192076):4)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
... 6 more

```

**Comment by thestinger** [comment]
cc @muhomorr
