### ISSUE TITLE
GMS crash

### ISSUE THREAD

**Issue by BirdDev** [GrapheneOS/os-issue-tracker#1474]
I received the following stacktrace in pixel 5

```
type: crash
osVersion: google/redfin/redfin:13/TP1A.220905.004/2022090600:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms.persistent

android.net.ConnectivityManager$TooManyRequestsException
	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4017)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4206)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4213)
	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4595)
	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4565)
	at aqkl.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at aqma.<init>(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at aqmi.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at aqmi.i(:com.google.android.gms@222615044@22.26.15 (190400-461192076):16)
	at aqkt.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
	at aqll.f(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at antj.en(:com.google.android.gms@222615044@22.26.15 (190400-461192076):1)
	at ahjx.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):12)
	at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at xot.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):6)
	at xot.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at xty.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cfvr: 
		at tk_trace.168-startOrUpdateSearch(Unknown Source:0)
		at tk_trace.cast-DiscoveryManager$DiscoveryManagerReceiver_onReceive(Unknown Source:0)
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)

```
I have only one account on this device and am connected with a private VPN.
It does not need to be related but I'm having general trouble using the playstore app on my device. (Can't connect)

Please let me know if I can help you with any more information.

**Comment by thestinger** [comment]
cc @muhomorr

**Comment by muhomorr** [comment]
@BirdDev Have you revoked Network permission from Play services?

**Comment by BirdDev** [comment]
@muhomorr indeed! I gave permission and I am now able to use the Play services again.
Also, no further crash occurred. Thank you!
