### ISSUE TITLE
park4night app crash

### ISSUE THREAD

**Issue by soinu** [GrapheneOS/os-issue-tracker#1499]
App crashes on GrapheneOS, works on different device
```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.220905.004/2022091400:user/release-keys
package: fr.tramb.park4night:181
process: fr.tramb.park4night

java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3012)
	at android.os.Parcel.createException(Parcel.java:2996)
	at android.os.Parcel.readException(Parcel.java:2979)
	at android.os.Parcel.readException(Parcel.java:2921)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8593)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3037)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3001)
	at com.mapbox.mapboxsdk.telemetry.MapboxEventManager.getCellularNetworkType(MapboxEventManager.java:558)
	at com.mapbox.mapboxsdk.telemetry.MapboxEventManager.pushEvent(MapboxEventManager.java:397)
	at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:516)
	at com.bfichter.toolkit.map.implementation.BFMapBoxView.onCreateView(BFMapBoxView.java:95)
	at com.bfichter.toolkit.map.BFMapView.onCreateView(BFMapView.java:71)
	at fr.tramb.park4night.ihm.Dashboad.onCreateView(Dashboad.java:156)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1515)
	at android.app.Activity.performStart(Activity.java:8326)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3702)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by thestinger** [comment]
Not a GrapheneOS issue.

**Comment by soinu** [comment]
Apparently this app works just fine with sandboxed google play services installed
