### ISSUE TITLE
Gms crash

### ISSUE THREAD

**Issue by thelittlefireman** [GrapheneOS/os-issue-tracker#1503]
```
type: crash
osVersion: google/raven/raven:13/TP1A.220905.004.A1/2022092000:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms

java.lang.IllegalArgumentException: Unknown authority com.android.contacts
	at android.content.ContentResolver.call(ContentResolver.java:2469)
	at android.content.ContentResolver.call(ContentResolver.java:2452)
	at android.provider.ContactsContract$SimContacts.getSimAccounts(ContactsContract.java:8450)
	at bagg.b(:com.google.android.gms@222615044@22.26.15 (190400-461192076):1)
	at bagh.d(:com.google.android.gms@222615044@22.26.15 (190400-461192076):5)
	at bagh.b(:com.google.android.gms@222615044@22.26.15 (190400-461192076):1)
	at baga.f(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
	at antj.en(:com.google.android.gms@222615044@22.26.15 (190400-461192076):1)
	at ahjx.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):12)
	at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at xot.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):6)
	at xot.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at xty.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cfvr: 
		at tk_trace.5-ClassifyAccountTypes(Unknown Source:0)
		at tk_trace.people-PeopleChimeraService-IContactsSyncService_201201(Unknown Source:0)


```

**Comment by muhomorr** [comment]
Check version of "GmsCompat config" in Apps app. Are you on version 3?
