### ISSUE TITLE
Seedvault crash at startup

### ISSUE THREAD

**Issue by rightsaidfred99** [GrapheneOS/os-issue-tracker#1514]
Here's the log, its been happening for a few months

```
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.220905.004.A1/2022092300:user/release-keys
package: com.stevesoltys.seedvault:30000231
process: com.stevesoltys.seedvault
java.lang.AssertionError: Error reading metadata from cache
	at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:48)
	at com.stevesoltys.seedvault.metadata.MetadataManager.getBackupToken(MetadataManager.kt:209)
	at com.stevesoltys.seedvault.App.migrateTokenFromMetadataToSettingsManager(App.kt:109)
	at com.stevesoltys.seedvault.App.access$migrateTokenFromMetadataToSettingsManager(App.kt:40)
	at com.stevesoltys.seedvault.App$onCreate$1.invoke(App.kt:76)
	at com.stevesoltys.seedvault.App$onCreate$1.invoke(App.kt:75)
	at com.stevesoltys.seedvault.AppKt.permitDiskReads(App.kt:138)
	at com.stevesoltys.seedvault.App.onCreate(App.kt:75)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6791)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.io.IOException
	at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:45)
	... 20 more
```

**Comment by muhomorr** [comment]
Seems to be an internal Seedvault bug. Try clearing app data of Seedvault.
