### ISSUE TITLE
Google play sandbox crash at startup

### ISSUE THREAD

**Issue by rightsaidfred99** [GrapheneOS/os-issue-tracker#1515]
```
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.220905.004.A1/2022092300:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms
java.lang.NullPointerException: Attempt to invoke interface method 'void android.os.IStatsManagerService.addConfiguration(long, byte[], java.lang.String)' on a null object reference
	at android.app.StatsManager.addConfig(StatsManager.java:151)
	at bpmb.e(:com.google.android.gms@222615044@22.26.15 (190400-461192076):5)
	at bpmb.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):207)
	at com.google.android.gms.westworld.InitOperation.e(:com.google.android.gms@222615044@22.26.15 (190400-461192076):9)
	at uvi.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at uzr.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):4)
	at ffi.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
	at ffh.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
	at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by PatrykMis** [comment]
After upgrading to 5 this issue still exists.


```
type: crash
osVersion: google/flame/flame:13/TP1A.220905.004/2022092300:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms

java.lang.NullPointerException: Attempt to invoke interface method 'void android.os.IStatsManagerService.addConfiguration(long, byte[], java.lang.String)' on a null object reference
at android.app.StatsManager.addConfig(StatsManager.java:151)
at bpmb.e(:com.google.android.gms@222615044@22.26.15 (190400-461192076):5)
at bpmb.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):207)
at com.google.android.gms.westworld.InitOperation.e(:com.google.android.gms@222615044@22.26.15 (190400-461192076):9)
at uvi.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at uzr.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):4)
at ffi.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
at ffh.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
Try version 6.
