### ISSUE TITLE
Gms crash on Pixel 4a

### ISSUE THREAD

**Issue by lesposi** [GrapheneOS/os-issue-tracker#1527]
Greetings,
I'm running with this setup:
```
Pixel 4a
Version: TP1A.220905.004.2022092300

GmsCompat: version 13
GmsCompat config: version 7
```

After every reboot, I get multiple instances of the following crash dumps:

```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.220905.004/2022092300:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms

java.lang.IllegalStateException: Failed to find update_engine
at android.os.UpdateEngine.<init>(UpdateEngine.java:252)
at bmoz.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
at bmpe.<init>(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at bmpa.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
at bmte.b(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
at bmon.<init>(:com.google.android.gms@222615044@22.26.15 (190400-461192076):5)
at bmon.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
at bmmj.b(:com.google.android.gms@222615044@22.26.15 (190400-461192076):5)
at bmml.apply(:com.google.android.gms@222615044@22.26.15 (190400-461192076):8)
at com.google.android.gms.update.execution.InstallationEventIntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):8)
at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at uzr.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):4)
at ffi.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
at ffh.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)

```

```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.220905.004/2022092300:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms

java.lang.SecurityException: Only the system update service can broadcast update information
at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
at android.os.Parcel.createException(Parcel.java:3005)
at android.os.Parcel.readException(Parcel.java:2981)
at android.os.Parcel.readException(Parcel.java:2923)
at android.app.admin.IDevicePolicyManager$Stub$Proxy.notifyPendingSystemUpdate(IDevicePolicyManager.java:10041)
at android.app.admin.DevicePolicyManager.notifyPendingSystemUpdate(DevicePolicyManager.java:11986)
at bmlr.h(:com.google.android.gms@222615044@22.26.15 (190400-461192076):1)
at bmlm.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):50)
at com.google.android.gms.update.control.ReceiverIntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at uzr.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):4)
at ffi.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
at ffh.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)

```

```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.220905.004/2022092300:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms

java.lang.SecurityException: Only the system update service can broadcast update information
at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
at android.os.Parcel.createException(Parcel.java:3005)
at android.os.Parcel.readException(Parcel.java:2981)
at android.os.Parcel.readException(Parcel.java:2923)
at android.app.admin.IDevicePolicyManager$Stub$Proxy.notifyPendingSystemUpdate(IDevicePolicyManager.java:10041)
at android.app.admin.DevicePolicyManager.notifyPendingSystemUpdate(DevicePolicyManager.java:11986)
at bmlr.h(:com.google.android.gms@222615044@22.26.15 (190400-461192076):1)
at bmlm.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):50)
at com.google.android.gms.update.control.ReceiverIntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at uzr.onHandleIntent(:com.google.android.gms@222615044@22.26.15 (190400-461192076):4)
at ffi.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
at ffh.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.internal.util.Preconditions.checkCallAuthorization(Preconditions.java:261)
at com.android.server.devicepolicy.DevicePolicyManagerService.notifyPendingSystemUpdate(DevicePolicyManagerService.java:13755)
at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:4741)
at android.os.Binder.execTransactInternal(Binder.java:1302)
at android.os.Binder.execTransact(Binder.java:1265)
```

Also, (not sure if related) after some time, the notification **Sandboxed Google Play is running** disappears altogether.

**Comment by MTPeyton** [comment]
I'm also seeing similar issues on my Pixel 4a. It happened frequently after the latest GrapheneOS update. Now several days later it happens much less frequently, and hasn't happened for the last 24 hours. However, my GMS seemed to automatically restart itself each time.

**Comment by muhomorr** [comment]
@flawedworld This should be enough:
https://github.com/GrapheneOS/platform_packages_apps_GmsCompat/pull/35/commits/ef2b1b8b4c19a3414bddfda92da3738bdfb1df3c
