### ISSUE TITLE
Any version of G-Cam app crashes on startup - bug in GSF?

### ISSUE THREAD

**Issue by indiDing** [GrapheneOS/os-issue-tracker#1528]
Pixel 6a.
GSF (new version as of 2022-09-29) is installed / activated on both two profiles.
G-Cam app crashes on startup. Tried different versions from G-Cam. According to crash log some libs seem to be missing.

Crash log 1 (G-Cam V 8.6, latest version as of 2022-09-02)

`
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.220905.004.A2/2022092300:user/release-keys
package: com.google.android.GoogleCamera:65535120
process: com.google.android.GoogleCamera

java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastartup.so" not found
at jbl.run(PG:4)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
at jao.run(PG:2)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastartup.so" not found
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:191)
at mtn.get(PG:1)
at jbl.run(PG:3)
... 4 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastartup.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
at java.lang.Runtime.loadLibrary0(Runtime.java:998)
at java.lang.System.loadLibrary(System.java:1661)
at jha.b(PG:1)
at jhb.b(PG:8)
at jhb.a(PG:1)
at csp.<init>(PG:1)
at cog.get(PG:31)
at nju.get(PG:1)
at csu.get(PG:1)
at nju.get(PG:1)
at csr.run(PG:98)
at gtc.run(PG:2)
at czl.run(PG:5)
at asd.run(PG:57)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
at jbm.run(PG:1)
at jbl.run(PG:1)
... 4 more
`

Crash log 1 (G-Cam V 8.2)

`type: crash
osVersion: google/bluejay/bluejay:13/TP1A.220905.004.A2/2022092300:user/release-keys
package: com.google.android.GoogleCamera:64129804
process: com.google.android.GoogleCamera

java.lang.UnsatisfiedLinkError: dlopen failed: library "libCO2XupdSGA.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
at java.lang.Runtime.loadLibrary0(Runtime.java:998)
at java.lang.System.loadLibrary(System.java:1661)
at com.nativebindings.VMRunner.<clinit>(VMRunner.java:30)
at eor.initVM(Unknown Source:4)
at eor.<clinit>(Unknown Source:0)
at java.lang.Class.newInstance(Native Method)
at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
at android.app.Instrumentation.newApplication(Instrumentation.java:1236)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6752)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
`

**Comment by thestinger** [comment]
Is this the official Google Camera from the Play Store? It seems you must be using something else.

**Comment by r3g-5z** [comment]
It's not the official GCam. There are mods of GCam on various places that modify the library libgcastartup.so.
The latest GCam is also not "8.2", it's 8.6.263.471358013.15.

**Comment by thestinger** [comment]
Use the official app and it will work.

**Comment by indiDing** [comment]
@r3g-5z
I attached TWO crashlogs in one. Ok, not the best way. However, the first crash log comes from V 8.2 and the second from V 8.6.
The 8.2. package I took from a stock pixel 2 and play store, even more official is not possible I think ;-)
Indeed, the V 8.6 package comes from apkmirror.
Will continue trying ...

**Comment by indiDing** [comment]
@thestinger 
Didn´t know that. Thank you!
