### ISSUE TITLE
Error in (Google) Messages

### ISSUE THREAD

**Issue by thilakm-git** [GrapheneOS/os-issue-tracker#1536]
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221005.002/2022100300:user/release-keys
package: com.google.android.apps.messaging:148318063
process: com.google.android.apps.messaging

java.lang.RuntimeException: Unable to create service com.google.android.libraries.micore.superpacks.scheduling.DownloadJobService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.libraries.micore.superpacks.scheduling.DownloadJobService" on path: DexPathList[[zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/base.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.arm64_v8a.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.de.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.en.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/lib/arm64, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/base.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.de.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4534)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2163)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.libraries.micore.superpacks.scheduling.DownloadJobService" on path: DexPathList[[zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/base.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.arm64_v8a.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.de.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.en.apk", zip file "/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/lib/arm64, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/base.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.de.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.en.apk!/lib/arm64-v8a, /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4502)
	... 11 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.arm64_v8a.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6682)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
		... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.de.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6682)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
		... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.en.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6682)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
		... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~Lf-pK-SS9r02e4wka9hBzw==/com.google.android.apps.messaging-gZTgsgNVQ4JHz60g3-fzdg==/split_config.xxhdpi.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6682)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
		... 9 more

```

**Comment by muhomorr** [comment]
How to reproduce this?

**Comment by thilakm-git** [comment]
Sorry, I havent found a reliable way to reproduce this. It's been happening very infrequently - though over the past few weeks - with no apparent pattern. The only pattern I noticed was that this happens wenn I don't actually have the messages app open (in foreground). I'll keep this thread updated in case I find a way to reproduce this.

**Comment by r3g-5z** [comment]
Is this still an issue?

**Comment by r3g-5z** [comment]
Going to assume this has fixed itself overtime with sandboxed Google Play updates and improvements or this may have just been a Google Messages bug. If this is still an issue, let us know but we do need a clear method of reproduction otherwise this isn't actionable, especially if it doesn't impact normal functionality.
