### ISSUE TITLE
Google location manager crash while using Bluetooth earbuds 

### ISSUE THREAD

**Issue by desartij** [GrapheneOS/os-issue-tracker#1548]
I had multiple crashes of play services today while listening to Spotify with my Sony wf-1000xm4.

It seams to be related to the location service I use the Google location system instead of redirecting to the OS because of issue I have with Google map not tracking my movement while using it for navigation

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022100300:user/release-keys
package: com.google.android.gms:223316044
process: com.google.android.gms.persistent

java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10115 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.app.ContextImpl.enforce(ContextImpl.java:2285)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2313)
	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:948)
	at com.android.bluetooth.Utils.enforceBluetoothPrivilegedPermission(Utils.java:408)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setMetadata(AdapterService.java:3571)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setMetadata(AdapterService.java:3557)
	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:1227)
	at android.os.Binder.execTransactInternal(Binder.java:1307)
	at android.os.Binder.execTransact(Binder.java:1265)
	Suppressed: crrw: 
		at tk_trace.nearby-DiscoveryChimeraService_onCreate(Unknown Source:0)
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)
```

**Comment by r3g-5z** [comment]
Newest release will solve this.
