### ISSUE TITLE
Google sandbox keeps crashing

### ISSUE THREAD

**Issue by MrJay8592** [GrapheneOS/os-issue-tracker#1559]
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022100300:user/release-keys
package: com.google.android.gms:223914044
process: com.google.android.gms.persistent

java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10125 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.app.ContextImpl.enforce(ContextImpl.java:2285)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2313)
	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:948)
	at com.android.bluetooth.Utils.enforceBluetoothPrivilegedPermission(Utils.java:408)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setMetadata(AdapterService.java:3571)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setMetadata(AdapterService.java:3557)
	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:1227)
	at android.os.Binder.execTransactInternal(Binder.java:1307)
	at android.os.Binder.execTransact(Binder.java:1265)
	Suppressed: ctwt: 
		at tk_trace.nearby-DiscoveryChimeraService_onCreate(Unknown Source:0)
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)

```

**Comment by r3g-5z** [comment]
Update to the latest beta 2022101200.

**Comment by MrJay8592** [comment]
Where can I find that? Kinda new to this

**Comment by r3g-5z** [comment]
https://grapheneos.org/usage#updates-settings
