### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Mathew420w0** [GrapheneOS/os-issue-tracker#1560]
```
type: crash
osVersion: google/coral/coral:13/TP1A.221005.002/2022101200:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms.persistent

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at beyi.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):12)
	at bevf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at xot.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):6)
	at xot.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at xty.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cfvr: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.stats-PlatformStatsCollectorChimeraService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.scheduler-ServiceConnection_com.google.android.gms.stats.PlatformStatsCollectorService_onServiceConnected(Unknown Source:0)
		at tk_trace.checkQueueEagerly(Unknown Source:0)
		at tk_trace.trigger_EXECUTION_CALLBACK(Unknown Source:0)
		at tk_trace.scheduler-StandaloneSchedulingEngine_handleClientCallback(Unknown Source:0)
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.fitness-SyncGcmTaskChimeraService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.scheduler-ServiceConnection_com.google.android.gms.fitness.sync.SyncGcmTaskService_onServiceConnected(Unknown Source:0)
		at tk_trace.checkQueueEagerly(Unknown Source:0)
		at tk_trace.trigger_EXECUTION_CALLBACK(Unknown Source:0)
		at tk_trace.scheduler-StandaloneSchedulingEngine_handleClientCallback(Unknown Source:0)
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.clearcut-QosUploaderChimeraService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.scheduler-ServiceConnection_com.google.android.gms.clearcut.uploader.QosUploaderService_onServiceConnected(Unknown Source:0)
		at tk_trace.checkQueueEagerly(Unknown Source:0)
		at tk_trace.trigger_EXECUTION_CALLBACK(Unknown Source:0)
		at tk_trace.scheduler-StandaloneSchedulingEngine_handleClientCallback(Unknown Source:0)
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.tapandpay-TapAndPayGcmTaskChimeraService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.scheduler-ServiceConnection_com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService_onServiceConnected(Unknown Source:0)
		at tk_trace.checkQueueLazily(Unknown Source:0)
		at tk_trace.scheduler-StandaloneSchedulingEngine_trigger_EVENT_CODE_DOZE_LIGHT_MODE_CHANGED(Unknown Source:0)
		at tk_trace.scheduler-DeviceStateReceiver_onReceive(Unknown Source:0)
		at tk_trace.GmsCoreLogger.get(Unknown Source:0)
		at tk_trace.Missing root trace(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at anyg.apply(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at clmg.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at clmh.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):11)
	... 6 more
Caused by: java.lang.NullPointerException
	at chma.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at binf.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at bine.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):55)
	at bilm.e(:com.google.android.gms@222615044@22.26.15 (190400-461192076):7)
	at bine.j(:com.google.android.gms@222615044@22.26.15 (190400-461192076):8)
	at bine.b(:com.google.android.gms@222615044@22.26.15 (190400-461192076):26)
	at bine.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):6)
	at com.google.android.gms.stats.PlatformStatsCollectorChimeraService.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):27)
	at anyd.call(:com.google.android.gms@222615044@22.26.15 (190400-461192076):4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more

```

**Comment by PatrykMis** [comment]
I had this too.
