### ISSUE TITLE
Crash after (or while) updating GMS

### ISSUE THREAD

**Issue by PatrykMis** [GrapheneOS/os-issue-tracker#1561]
I had "Action required in Play Store" from GmsCompat. After launching it, package installer asked me to upgrade GMS. In a minute I had crash - stack trace below.

```
type: crash
osVersion: google/flame/flame:13/TP1A.221005.002/2022101200:user/release-keys
package: com.google.android.gms:223316044
process: com.google.android.gms.persistent

java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.libraries.geller.portable.Geller.nativeCreate(com.google.android.libraries.geller.portable.callbacks.GellerStorageOperationsCallback, com.google.android.libraries.geller.portable.GellerStorageChangeListenerHandler, com.google.android.libraries.geller.portable.callbacks.GellerLoggingCallback, byte[]) (tried Java_com_google_android_libraries_geller_portable_Geller_nativeCreate and Java_com_google_android_libraries_geller_portable_Geller_nativeCreate__Lcom_google_android_libraries_geller_portable_callbacks_GellerStorageOperationsCallback_2Lcom_google_android_libraries_geller_portable_GellerStorageChangeListenerHandler_2Lcom_google_android_libraries_geller_portable_callbacks_GellerLoggingCallback_2_3B)
at com.google.android.libraries.geller.portable.Geller.nativeCreate(Native Method)
at com.google.android.libraries.geller.portable.Geller.<init>(:com.google.android.gms@223316044@22.33.16 (190400-474895102):17)
at cbcc.a(:com.google.android.gms@223316044@22.33.16 (190400-474895102):2)
at denv.<init>(:com.google.android.gms@223316044@22.33.16 (190400-474895102):15)
at avaa.a(:com.google.android.gms@223316044@22.33.16 (190400-474895102):112)
at aujj.i(:com.google.android.gms@223316044@22.33.16 (190400-474895102):3)
at aujj.d(:com.google.android.gms@223316044@22.33.16 (190400-474895102):0)
at aujj.b(:com.google.android.gms@223316044@22.33.16 (190400-474895102):1)
at aujj.c(:com.google.android.gms@223316044@22.33.16 (190400-474895102):3)
at avaa.a(:com.google.android.gms@223316044@22.33.16 (190400-474895102):78)
at aujj.i(:com.google.android.gms@223316044@22.33.16 (190400-474895102):3)
at aujj.d(:com.google.android.gms@223316044@22.33.16 (190400-474895102):0)
at aujj.b(:com.google.android.gms@223316044@22.33.16 (190400-474895102):1)
at aujj.c(:com.google.android.gms@223316044@22.33.16 (190400-474895102):3)
at avwn.<init>(:com.google.android.gms@223316044@22.33.16 (190400-474895102):5)
at avaa.a(:com.google.android.gms@223316044@22.33.16 (190400-474895102):70)
at aujj.i(:com.google.android.gms@223316044@22.33.16 (190400-474895102):3)
at aujj.d(:com.google.android.gms@223316044@22.33.16 (190400-474895102):0)
at aujj.b(:com.google.android.gms@223316044@22.33.16 (190400-474895102):1)
at aujj.c(:com.google.android.gms@223316044@22.33.16 (190400-474895102):3)
at com.google.android.gms.nearby.discovery.service.DiscoveryChimeraService.onCreate(:com.google.android.gms@223316044@22.33.16 (190400-474895102):5)
at gie.onCreate(:com.google.android.gms@223316044@22.33.16 (190400-474895102):1)
at wfs.onCreate(:com.google.android.gms@223316044@22.33.16 (190400-474895102):4)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4521)
at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2163)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by muhomorr** [comment]
Is this a one-time crash?

**Comment by PatrykMis** [comment]
Yes.

**Comment by thestinger** [comment]
Doesn't seem actionable. Could be a Play services bug.
