### ISSUE TITLE
Google sandbox continues to crash

### ISSUE THREAD

**Issue by MrJay8592** [GrapheneOS/os-issue-tracker#1566]
Already updated to latest beta

type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022101200:user/release-keys
package: com.google.android.gms:223914044
process: com.google.android.gms.persistent

java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10125 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.app.ContextImpl.enforce(ContextImpl.java:2285)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2313)
	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:948)
	at com.android.bluetooth.Utils.enforceBluetoothPrivilegedPermission(Utils.java:408)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setSilenceMode(AdapterService.java:2876)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setSilenceMode(AdapterService.java:2862)
	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:960)
	at android.os.Binder.execTransactInternal(Binder.java:1307)
	at android.os.Binder.execTransact(Binder.java:1265)
	Suppressed: ctwt: 
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)

**Comment by thestinger** [comment]
You aren't on the latest Beta. Stop opening new issues repeatedly.
