### ISSUE TITLE
Sandbox crashed

### ISSUE THREAD

**Issue by Urx567** [GrapheneOS/os-issue-tracker#1567]
```
type: crash
osVersion: google/bramble/bramble:13/TP1A.221005.002/2022100300:user/release-keys
package: com.google.android.gms:222615044
process: com.google.android.gms.persistent

android.net.ConnectivityManager$TooManyRequestsException
	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4017)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4206)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4213)
	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4595)
	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4565)
	at aqkl.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at aqma.<init>(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at aqmi.a(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at aqmi.i(:com.google.android.gms@222615044@22.26.15 (190400-461192076):16)
	at aqkt.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):3)
	at aqll.f(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at antj.en(:com.google.android.gms@222615044@22.26.15 (190400-461192076):1)
	at ahjx.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):12)
	at cfvf.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):2)
	at xot.c(:com.google.android.gms@222615044@22.26.15 (190400-461192076):6)
	at xot.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at xty.run(:com.google.android.gms@222615044@22.26.15 (190400-461192076):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cfvr: 
		at tk_trace.168-startOrUpdateSearch(Unknown Source:0)
		at tk_trace.AsyncOpImpl(Unknown Source:0)
		at tk_trace.AsyncOpTask(Unknown Source:0)
		at tk_trace.51-CommitToConfigurationOperationCall(Unknown Source:0)
		at tk_trace.phenotype-ConfigurationChimeraProvider_query(Unknown Source:0)
		at tk_trace.phenotype-ConfigurationChimeraProvider_queryWithSignal(Unknown Source:0)

```

**Comment by muhomorr** [comment]
Should be fixed in release that is currently in beta.
