### ISSUE TITLE
App crash on 2022101500

### ISSUE THREAD

**Issue by root-io** [GrapheneOS/os-issue-tracker#1570]
GrapheneOS 2022101500 Pixel 6

App crash, was working before

```
android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
        at android.webkit.CookieManager.getInstance(CookieManager.java:50)
        at com.facebook.react.modules.network.c.i(ForwardingCookieHandler.java:3)
        at com.facebook.react.modules.network.c.get(ForwardingCookieHandler.java:1)
        at r5.y.d(JavaNetCookieJar.kt:1)
        at com.facebook.react.modules.network.l.d(ReactCookieJarContainer.java:2)
        at x5.a.a(BridgeInterceptor.kt:17)
        at x5.g.b(RealInterceptorChain.kt:12)
        at x5.j.a(RetryAndFollowUpInterceptor.kt:7)
        at x5.g.b(RealInterceptorChain.kt:12)
        at w5.e.s(RealCall.kt:16)
        at w5.e$a.run(RealCall.kt:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
        at android.webkit.CookieManager.getInstance(CookieManager.java:50)
        at com.facebook.react.modules.network.c.i(ForwardingCookieHandler.java:3)
        at com.facebook.react.modules.network.c.get(ForwardingCookieHandler.java:1)
        at r5.y.d(JavaNetCookieJar.kt:1)
        at com.facebook.react.modules.network.l.d(ReactCookieJarContainer.java:2)
        at x5.a.a(BridgeInterceptor.kt:17)
        at x5.g.b(RealInterceptorChain.kt:12)
        at x5.j.a(RetryAndFollowUpInterceptor.kt:7)
        at x5.g.b(RealInterceptorChain.kt:12)
        at w5.e.s(RealCall.kt:16)
        at w5.e$a.run(RealCall.kt:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

Caused by: TQ: errorCode=2
        at org.chromium.base.library_loader.b.g(chromium-TrichromeWebView64.apk-stable-524912635:870)
        at org.chromium.base.library_loader.b.i(chromium-TrichromeWebView64.apk-stable-524912635:697)
        at org.chromium.android_webview.AwBrowserProcess.i(chromium-TrichromeWebView64.apk-stable-524912635:681)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-TrichromeWebView64.apk-stable-524912635:445)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForT.<init>(chromium-TrichromeWebView64.apk-stable-524912635:13)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForT.create(chromium-TrichromeWebView64.apk-stable-524912635:9)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
        at android.webkit.CookieManager.getInstance(CookieManager.java:50)
        at com.facebook.react.modules.network.c.i(ForwardingCookieHandler.java:3)
        at com.facebook.react.modules.network.c.get(ForwardingCookieHandler.java:1)
        at r5.y.d(JavaNetCookieJar.kt:1)
        at com.facebook.react.modules.network.l.d(ReactCookieJarContainer.java:2)
        at x5.a.a(BridgeInterceptor.kt:17)
        at x5.g.b(RealInterceptorChain.kt:12)
        at x5.j.a(RetryAndFollowUpInterceptor.kt:7)
        at x5.g.b(RealInterceptorChain.kt:12)
        at w5.e.s(RealCall.kt:16)
        at w5.e$a.run(RealCall.kt:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmonochrome_64.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at org.chromium.base.library_loader.b.g(chromium-TrichromeWebView64.apk-stable-524912635:819)
        at org.chromium.base.library_loader.b.i(chromium-TrichromeWebView64.apk-stable-524912635:697)
        at org.chromium.android_webview.AwBrowserProcess.i(chromium-TrichromeWebView64.apk-stable-524912635:681)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-TrichromeWebView64.apk-stable-524912635:445)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForT.<init>(chromium-TrichromeWebView64.apk-stable-524912635:13)
        at com.android.webview.chromium.WebViewChromiumFactoryProviderForT.create(chromium-TrichromeWebView64.apk-stable-524912635:9)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:355)
        at android.webkit.CookieManager.getInstance(CookieManager.java:50)
        at com.facebook.react.modules.network.c.i(ForwardingCookieHandler.java:3)
        at com.facebook.react.modules.network.c.get(ForwardingCookieHandler.java:1)
        at r5.y.d(JavaNetCookieJar.kt:1)
        at com.facebook.react.modules.network.l.d(ReactCookieJarContainer.java:2)
        at x5.a.a(BridgeInterceptor.kt:17)
        at x5.g.b(RealInterceptorChain.kt:12)
        at x5.j.a(RetryAndFollowUpInterceptor.kt:7)
        at x5.g.b(RealInterceptorChain.kt:12)
        at w5.e.s(RealCall.kt:16)
        at w5.e$a.run(RealCall.kt:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by r3g-5z** [comment]
What app? If it's an app you obtained from F-Droid you should get it somewhere else to get a proper 64-bit build and reinstall the app.

**Comment by thestinger** [comment]
No details provided on which app this is and we know the cause: it's an unsupported 32-bit-only app. We may decide to revert this change temporarily due to the poor state of the app ecosystem outside the Play Store but this is intended.
