### ISSUE TITLE
Google Play not working in Work Profile

### ISSUE THREAD

**Issue by maxammann** [GrapheneOS/os-issue-tracker#1573]
I'm using Google Play within a work profile, instead of a user profile. The work profile was setup using (Shelter)[https://f-droid.org/en/packages/net.typeblog.shelter/]. Unforuntely, Google Play depenant apps are not working properly.

### Apps not working properly

- Google Maps says on the initial launch that Google Play is not installed. Works afterwards, and even allows to login.
- Youtube is not starting:
```
10-18 20:20:15.054  1844 16594 I ActivityTaskManager: START u13 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x4000000 cmp=com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity bnds=[436,751][644,1066] (has extras)} from uid 1310181
10-18 20:20:15.075  1844  3474 W ActivityTaskManager: Tried to set launchTime (0) mLastActivityLaunchTime (98629826)
10-18 20:20:15.086 11796 11796 W GooglePlayServicesUtil: com.google.android.youtube requires the Google Play Store, but it is missing.
10-18 20:20:15.087 11796 11796 E GoogleApiAvailability: Google Play services is invalid. Cannot recover.
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: Creating dialog for Google Play services availability issue. ConnectionResult=9
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: java.lang.IllegalArgumentException
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at mhr.b(PG:15)
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at mhr.a(PG:2)
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at esw.c(PG:7)
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at esw.onCreate(PG:7)
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at lcd.onCreate(PG:1)
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at android.app.Activity.performCreate(Activity.java:8341)
10-18 20:20:15.092 11796 11796 W GoogleApiAvailability: 	at android.app.Activity.performCreate(Activity.java:8320)
10-1
....
```

### Apps working

Google Camera is working because it only depends on GFS.

### Things tried

I already tried to remove all apps from the profile and reinstalling all.

**Comment by thestinger** [comment]
You haven't installed it correctly. Install the Play Store there.

**Comment by maxammann** [comment]
Uff, sorry! Yes that was it. I did not install the Store.
