### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Gospodininzenjer** [GrapheneOS/os-issue-tracker#1597]
```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221005.002/2022102300:user/release-keys
package: com.google.android.gsf:33
process: com.google.process.gservices

java.lang.RuntimeException: Unable to start receiver com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4346)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
	at android.content.ContentResolver.insert(ContentResolver.java:2216)
	at android.content.ContentResolver.insert(ContentResolver.java:2175)
	at com.google.android.gsf.gservices.GservicesProvider.syncSettingsFromGsfStorage(GservicesProvider.java:631)
	at com.google.android.gsf.gservices.GservicesProvider.syncAllSettingsFromGsfStorage(GservicesProvider.java:581)
	at com.google.android.gsf.gservices.GservicesProvider.updateGsfStorageOverridesTable(GservicesProvider.java:730)
	at com.google.android.gsf.gservices.GservicesProvider.updateOverride(GservicesProvider.java:425)
	at com.google.android.gsf.gservices.GservicesProvider.update(GservicesProvider.java:385)
	at android.content.ContentProvider.update(ContentProvider.java:1882)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:465)
	at android.content.ContentResolver.update(ContentResolver.java:2423)
	at android.content.ContentResolver.update(ContentResolver.java:2385)
	at com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver.onReceive(GservicesProvider.java:119)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4337)
	... 11 more

```

**Comment by muhomorr** [comment]
It seem that you've allowed the "Modify system settings" special access permission to Google Services Framework app. If so, why?
Revoking it should stop these crashes.

**Comment by Gospodininzenjer** [comment]
Allowed is :

-Network
-read instant messages
-write instant messages
 
If i revoke it all- will that impact on my messenger application's?

**Comment by thestinger** [comment]
Look at special access permissions. Don't revoke Network since you use the functionality.
