### ISSUE TITLE
Google Play Services 22.43.12 breaks apps relying on it.

### ISSUE THREAD

**Issue by tuxedojacob** [GrapheneOS/os-issue-tracker#1618]
After installing this update, Gboard will pop up and down randomly, making typing near impossible.  Confirmed in any app that uses it, it will crash with the following.  Several apps relying on these services are now going completely haywire, crashing as soon as they're opened.

type: crash
osVersion: google/cheetah/cheetah:13/TD1A.220804.031/2022102800:user/release-keys
package: com.google.android.gms:224312044
process: com.google.android.gms.persistentjava.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.os.IUserManager$Stub$Proxy.getUserName(IUserManager.java:3193)
	at android.os.UserManager.getUserName(UserManager.java:2180)
	at bcvx.j(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.ah(:com.google.android.gms@224312044@22.43.12 (190400-483592595):1)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.X(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at bbhz.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at avza.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):3)
	at zxw.c(:com.google.android.gms@224312044@22.43.12 (190400-483592595):6)
	at zxw.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadb.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cuwy:
		at tk_trace.nearby-NearbySharingChimeraService_onCreate(Unknown Source:0)
		at tk_trace.container-PersistentApiService$ChimeraService_onBind(Unknown Source:0)
		at tk_trace.gcm-GcmChimeraService_onCreate(Unknown Source:0)```

**Comment by tuxedojacob** [comment]
Uninstalled this version, installed "Apps" version, issue seems to be resolved.  Sorry, I don't think I realized GOS isn't using latest/greatest

**Comment by muhomorr** [comment]
@tuxedojacob How did you end up this version of Play services?
