### ISSUE TITLE
Sandboxed Google Play crashed

### ISSUE THREAD

**Issue by sethmich** [GrapheneOS/os-issue-tracker#1619]
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221005.002/2022102800:user/release-keys
package: com.google.android.gms:224312044
process: com.google.android.gms.persistent

java.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.os.IUserManager$Stub$Proxy.getUserName(IUserManager.java:3193)
	at android.os.UserManager.getUserName(UserManager.java:2180)
	at bcvx.j(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.ah(:com.google.android.gms@224312044@22.43.12 (190400-483592595):1)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.V(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at bbie.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at avza.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):3)
	at zxw.c(:com.google.android.gms@224312044@22.43.12 (190400-483592595):6)
	at zxw.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadb.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cuwy: 
		at tk_trace.nearby-NearbySharingChimeraService_onCreate(Unknown Source:0)
		at tk_trace.container-PersistentApiService$ChimeraService_onBind(Unknown Source:0)
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)

```

**Comment by sethmich** [comment]
This started happening just about every hour, lasts for about 5-10min, then starts working for a little while.

**Comment by muhomorr** [comment]
@sethmich How did you end up with this version of Play services?

**Comment by sethmich** [comment]
@muhomorr Pretty sure it was from updating Google Play Services via the Aurora store. I got it working now as I did a fresh install from "Apps" as mentioned in #1618
