### ISSUE TITLE
Google Play Services Crash

### ISSUE THREAD

**Issue by mpldr** [GrapheneOS/os-issue-tracker#1622]
```
type: crash
osVersion: google/redfin/redfin:13/TP1A.221005.002/2022102800:user/release-keys
package: com.google.android.gms:224312044
process: com.google.android.gms.persistent

java.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.os.IUserManager$Stub$Proxy.getUserName(IUserManager.java:3193)
	at android.os.UserManager.getUserName(UserManager.java:2180)
	at bcvx.j(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.ah(:com.google.android.gms@224312044@22.43.12 (190400-483592595):1)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.V(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at bbie.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at avza.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):3)
	at zxw.c(:com.google.android.gms@224312044@22.43.12 (190400-483592595):6)
	at zxw.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadb.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cuwy: 
		at tk_trace.nearby-NearbySharingChimeraService_onCreate(Unknown Source:0)
		at tk_trace.container-PersistentApiService$ChimeraService_onBind(Unknown Source:0)
		at tk_trace.gcm-GcmChimeraService_onCreate(Unknown Source:0)

```

**Comment by mpldr** [comment]
Thank you, seems I did that by accident. Worked after reinstalling

**Comment by chris42** [comment]
> You've updated Play services to an unsupported version using an unsupported update method such as Aurora Store.

Not sure about that. I get a request multiple times a day to update google services, by the play store. Denied it so far, but seems, that there is a newer version by google around.

**Comment by thestinger** [comment]
@chris42 You should be updating Play services and the Play Store only via our app repository client and the Play Store. Don't install it from Aurora Store or you'll get an unsupported version. It's not always going to be the latest version since they have to be tested and support added to the compatibility layer if needed.
