### ISSUE TITLE
Error Google Play services

### ISSUE THREAD

**Issue by Belier96** [GrapheneOS/os-issue-tracker#1623]
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221005.002/2022102800:user/release-keys
package: com.google.android.gms:224312044
process: com.google.android.gms.persistent

java.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.os.IUserManager$Stub$Proxy.getUserName(IUserManager.java:3193)
	at android.os.UserManager.getUserName(UserManager.java:2180)
	at bcvx.j(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.ah(:com.google.android.gms@224312044@22.43.12 (190400-483592595):1)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.X(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at bbhz.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at avza.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):3)
	at zxw.c(:com.google.android.gms@224312044@22.43.12 (190400-483592595):6)
	at zxw.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadb.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cuwy: 
		at tk_trace.nearby-NearbySharingChimeraService_onCreate(Unknown Source:0)
		at tk_trace.container-PersistentApiService$ChimeraService_onBind(Unknown Source:0)

```

**Comment by besendorf** [comment]
Same issue here

**Comment by blueandyellowtaco38** [comment]
```
type: crash
osVersion: google/barbet/barbet:13/TP1A.221005.002/2022102800:user/release-keys
package: com.google.android.gms:224312044
process: com.google.android.gms.persistent

java.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.os.IUserManager$Stub$Proxy.getUserName(IUserManager.java:3193)
	at android.os.UserManager.getUserName(UserManager.java:2180)
	at bcvx.j(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.ah(:com.google.android.gms@224312044@22.43.12 (190400-483592595):1)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.X(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at bbhz.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at avza.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):3)
	at zxw.c(:com.google.android.gms@224312044@22.43.12 (190400-483592595):6)
	at zxw.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadb.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cuwy: 
		at tk_trace.nearby-NearbySharingChimeraService_onCreate(Unknown Source:0)
		at tk_trace.container-PersistentApiService$ChimeraService_onBind(Unknown Source:0)
		at tk_trace.gcm-GcmChimeraService_onCreate(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.getUserName(UserManagerService.java:1648)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1652)
	at android.os.Binder.execTransactInternal(Binder.java:1302)
	at android.os.Binder.execTransact(Binder.java:1265)


```

**Comment by muhomorr** [comment]
Update "GmsCompat config" package in Apps app to version 14.

**Comment by thestinger** [comment]
Also, please always search for issues before opening new ones. Multiple people who updated Play services via Aurora Store have opened an issue about this already.
