### ISSUE TITLE
Sandboxed Google Play Crashed

### ISSUE THREAD

**Issue by reveldevel** [GrapheneOS/os-issue-tracker#1627]
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221005.002/2022102800:user/release-keys
package: com.google.android.gms:224312044
process: com.google.android.gms.persistent

java.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.os.IUserManager$Stub$Proxy.getUserName(IUserManager.java:3193)
	at android.os.UserManager.getUserName(UserManager.java:2180)
	at bcvx.j(:com.google.android.gms@224312044@22.43.12 (190400-483592595):2)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.ah(:com.google.android.gms@224312044@22.43.12 (190400-483592595):1)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.V(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at bbie.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at avza.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):3)
	at zxw.c(:com.google.android.gms@224312044@22.43.12 (190400-483592595):6)
	at zxw.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadb.run(:com.google.android.gms@224312044@22.43.12 (190400-483592595):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cuwy: 
		at tk_trace.nearby-NearbySharingChimeraService_onCreate(Unknown Source:0)
		at tk_trace.container-PersistentApiService$ChimeraService_onBind(Unknown Source:0)
		at tk_trace.AsyncOpImpl(Unknown Source:0)
		at tk_trace.AsyncOpTask(Unknown Source:0)
		at tk_trace.51-CommitToConfigurationOperationCall(Unknown Source:0)
		at tk_trace.phenotype-ConfigurationChimeraProvider_query(Unknown Source:0)
		at tk_trace.phenotype-ConfigurationChimeraProvider_queryWithSignal(Unknown Source:0)

```

**Comment by thestinger** [comment]
Please search before filing an issue. You used Aurora Store to update Play services to an unsupported version. You should only update Play services and the Play Store via our app repository client and the Play Store itself. If you update to the latest GmsCompat config you won't have this issue, but you shouldn't be on this version that's still being tested and isn't fully supported by the compatibility layer yet.

Duplicates:

https://github.com/GrapheneOS/os-issue-tracker/issues/1623
https://github.com/GrapheneOS/os-issue-tracker/issues/1622
https://github.com/GrapheneOS/os-issue-tracker/issues/1619
https://github.com/GrapheneOS/os-issue-tracker/issues/1618

If you update these apps with Aurora Store, you will have issues like this because you're using unsupported releases of Play services and the Play Store before they've been tested and the compatibility layer extended as needed.

**Comment by cohesive-flight** [comment]
Wouldn't the Aurora Store update apps to the same version the Play Store would update them to?

**Comment by thestinger** [comment]
No, we control what the Play Store does with the compatibility layer and stop it updating to an unsupported version.
