### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by h-2** [GrapheneOS/os-issue-tracker#1635]
```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221005.002/2022102800:user/release-keys
package: com.android.vending:83281810
process: com.android.vending

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
	at fyn.h(PG:2)
	at aaix.d(PG:30)
	at aaiw.c(PG:25)
	at aaiw.a(PG:3)
	at aaiq.acl(PG:17)
	at jgg.u(Unknown Source:21)
	at aaju.u(PG:2)
	at hpk.run(PG:17)
	at jgr.e(Unknown Source:0)
	at aaju.e(PG:27)
	at jgr.g(Unknown Source:7)
	at jgr.acl(Unknown Source:6)
	at jgg.u(Unknown Source:21)
	at zss.run(PG:15)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by thestinger** [comment]
Looks like an upstream Play Store bug. We just report the crashes prominently.

**Comment by h-2** [comment]
Ok, just wanted to post it, since it came up. Thanks!
