### ISSUE TITLE
Error on every reboot...

### ISSUE THREAD

**Issue by citynetcomputing** [GrapheneOS/os-issue-tracker#1654]
attached...

![IMG_20221109_104731](https://user-images.githubusercontent.com/23244845/200876510-bc73f667-4987-4442-8db0-00b01b0e6151.jpg)

**Comment by thestinger** [comment]
Not enough information provided. You need to provide logs for the crash.

**Comment by citynetcomputing** [comment]
Sure, whats the process to do so?



Cheers,
Jay.
________________________________

**Comment by bigswag420** [comment]
press show details

**Comment by citynetcomputing** [comment]
Thank you! Attached..


```
type: crash
osVersion: google/panther/panther:13/TD1A.221105.001/2022110800:user/release-keys
package: com.android.qns:33
process: com.android.qns
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gril/GRilConnectionListener;
at com.android.qns.GoogleQnsManager.<init>(GoogleQnsManager.java:93)
at com.android.qns.GoogleQnsManager.lambda$getInstance$0(GoogleQnsManager.java:129)
at com.android.qns.GoogleQnsManager.$r8$lambda$XT0whsub1y6WRTrD70V6wflOelg(Unknown Source:0)
at com.android.qns.GoogleQnsManager$$ExternalSyntheticLambda0.apply(Unknown Source:6)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710)
at com.android.qns.GoogleQnsManager.getInstance(GoogleQnsManager.java:128)
at com.android.qns.QualifiedNetworksServiceImpl$NetworkAvailabilityProviderImpl.onConfigurationLoaded(QualifiedNetworksServiceImpl.java:262)
at com.android.qns.QualifiedNetworksServiceImpl$NetworkAvailabilityProviderImpl$2.handleMessage(QualifiedNetworksServiceImpl.java:185)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.ClassNotFoundException: com.google.android.gril.GRilConnectionListener
... 12 more
```
Cheers,
Jay.




















Cheers,
Jay.

________________________________

**Comment by citynetcomputing** [comment]
This looks google related so if it helps im de-googled FYI...

**Comment by citynetcomputing** [comment]
Any eta on a fix for this? TY!

**Comment by thestinger** [comment]
It's fixed already and will be included in the next release.

**Comment by citynetcomputing** [comment]
Thank You Sir! Received an update today so wasn't sure if that was supposed to be it but the issue was still there so i asked. ;)

Thanks again!!
