### ISSUE TITLE
Google Play Service crash

### ISSUE THREAD

**Issue by Maximus1996** [GrapheneOS/os-issue-tracker#1661]
Hello,
I wasn´t doing anything special but today Google Play Service crashed with the following log:

ype: crash
osVersion: google/panther/panther:13/TD1A.221105.001/2022110800:user/release-keys
package: com.google.android.gms:224113044
process: com.google.android.gms

dajs: rethrowing exception from lowpool[16]
at zyb.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):4)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at arnp.lv(:com.google.android.gms@224113044@22.41.13 (190400-480714934):0)
at arnp.dispatchMessage(:com.google.android.gms@224113044@22.41.13 (190400-480714934):11)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Suppressed: cuij:
at tk_trace.ScheduledTaskImpl(Unknown Source:0)
at tk_trace.security__nonwearable-TelecomTaskService_onRunTaskAsync(Unknown Source:0)
at tk_trace.security__nonwearable-TelecomTaskService-IMessenger_0(Unknown Source:0)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
at android.telecom.TelecomManager.getAllPhoneAccountHandles(TelecomManager.java:1472)
at brui.a(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
at com.google.android.gms.security.snet.TelecomTaskService.a(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
at arpb.call(:com.google.android.gms@224113044@22.41.13 (190400-480714934):4)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at zyr.c(:com.google.android.gms@224113044@22.41.13 (190400-480714934):6)
at zyr.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):7)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at aadw.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):0)
at java.lang.Thread.run(Thread.java:1012)

**Comment by thestinger** [comment]
Update to GmsCompatConfig v15 in the Beta channel of the app repository. It will be in stable soon.
