### ISSUE TITLE
Sandboxed Google Play crashed

### ISSUE THREAD

**Issue by mahirtazwar** [GrapheneOS/os-issue-tracker#1671]
Getting this error multiple times after the recent update. Prior to updating, I had removed location permission of Google Play Services. However, granting the location permission did not seem to mitigate the "Google Play crased" notification.

The error message is pasted below:

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221105.002/2022110800:user/release-keys
package: com.google.android.gms:224212044
process: com.google.android.gms

daqa: rethrowing exception from lowpool[8]
	at zwy.run(:com.google.android.gms@224212044@22.42.12 (190400-481949630):4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at [arov.lv](http://arov.lv/)(:com.google.android.gms@224212044@22.42.12 (190400-481949630):0)
	at arov.dispatchMessage(:com.google.android.gms@224212044@22.42.12 (190400-481949630):11)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: cuok: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService-IMessenger_0(Unknown Source:0)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
	at android.telecom.TelecomManager.getAllPhoneAccountHandles(TelecomManager.java:1472)
	at brwm.a(:com.google.android.gms@224212044@22.42.12 (190400-481949630):2)
	at com.google.android.gms.security.snet.TelecomTaskService.a(:com.google.android.gms@224212044@22.42.12 (190400-481949630):2)
	at arqh.call(:com.google.android.gms@224212044@22.42.12 (190400-481949630):4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at zxo.c(:com.google.android.gms@224212044@22.42.12 (190400-481949630):6)
	at zxo.run(:com.google.android.gms@224212044@22.42.12 (190400-481949630):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aact.run(:com.google.android.gms@224212044@22.42.12 (190400-481949630):0)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by thestinger** [comment]
Please search before filing an issue. Many people have filed this duplicate issue already. It was already fixed yesterday shortly after the initial report and you haven't updated GmsCompatConfig to v15.
