### ISSUE TITLE
error in gmscompat

### ISSUE THREAD

**Issue by noone-one** [GrapheneOS/os-issue-tracker#1672]
type: crash
osVersion: google/oriole/oriole:13/TP1A.221105.002/2022110800:user/release-keys
package: com.google.android.gms:223316044
process: com.google.android.gms

cxpc: rethrowing exception from lowpool[0]
	at yzn.run(:com.google.android.gms@223316044@22.33.16 (190400-474895102):4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at aqdu.lh(:com.google.android.gms@223316044@22.33.16 (190400-474895102):0)
	at aqdu.dispatchMessage(:com.google.android.gms@223316044@22.33.16 (190400-474895102):11)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: crrw: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService-IMessenger_0(Unknown Source:0)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
	at android.telecom.TelecomManager.getAllPhoneAccountHandles(TelecomManager.java:1472)
	at bpsc.a(:com.google.android.gms@223316044@22.33.16 (190400-474895102):2)
	at com.google.android.gms.security.snet.TelecomTaskService.a(:com.google.android.gms@223316044@22.33.16 (190400-474895102):2)
	at aqfg.call(:com.google.android.gms@223316044@22.33.16 (190400-474895102):4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at zad.c(:com.google.android.gms@223316044@22.33.16 (190400-474895102):6)
	at zad.run(:com.google.android.gms@223316044@22.33.16 (190400-474895102):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at zfi.run(:com.google.android.gms@223316044@22.33.16 (190400-474895102):0)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by thestinger** [comment]
Please search before filing issues. Many people have reported this issue and it was already fixed yesterday shortly after the first report. You haven't updated to GmsCompatConfig v15 yet.
