### ISSUE TITLE
Google play services crash

### ISSUE THREAD

**Issue by 0n** [GrapheneOS/os-issue-tracker#1673]
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221105.002/2022110800:user/release-keys
package: com.google.android.gms:224113044
process: com.google.android.gms

dajs: rethrowing exception from lowpool[0]
	at zyb.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at arnp.lv(:com.google.android.gms@224113044@22.41.13 (190400-480714934):0)
	at arnp.dispatchMessage(:com.google.android.gms@224113044@22.41.13 (190400-480714934):11)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: cuij: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService-IMessenger_0(Unknown Source:0)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
	at android.telecom.TelecomManager.getAllPhoneAccountHandles(TelecomManager.java:1472)
	at brui.a(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
	at com.google.android.gms.security.snet.TelecomTaskService.a(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
	at arpb.call(:com.google.android.gms@224113044@22.41.13 (190400-480714934):4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at zyr.c(:com.google.android.gms@224113044@22.41.13 (190400-480714934):6)
	at zyr.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadw.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):0)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
Please search before filing an issue. Over a dozen duplicates have been filed about this compatibility issue which was fixed yesterday already. You simply need to update GmsCompatConfig to v15. It was fixed within hours of the first issue report.
