### ISSUE TITLE
Gmscompat repeated crashes

### ISSUE THREAD

**Issue by lake-effect** [GrapheneOS/os-issue-tracker#1674]
Potentially a duplicate of #1653:

```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221105.002/2022110800:user/release-keys
package: com.google.android.gms:224113044
process: com.google.android.gms

dajs: rethrowing exception from lowpool[0]
	at zyb.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at arnp.lv(:com.google.android.gms@224113044@22.41.13 (190400-480714934):0)
	at arnp.dispatchMessage(:com.google.android.gms@224113044@22.41.13 (190400-480714934):11)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: cuij: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService_onRunTaskAsync(Unknown Source:0)
		at tk_trace.security__nonwearable-TelecomTaskService-IMessenger_0(Unknown Source:0)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
	at android.telecom.TelecomManager.getAllPhoneAccountHandles(TelecomManager.java:1472)
	at brui.a(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
	at com.google.android.gms.security.snet.TelecomTaskService.a(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
	at arpb.call(:com.google.android.gms@224113044@22.41.13 (190400-480714934):4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at zyr.c(:com.google.android.gms@224113044@22.41.13 (190400-480714934):6)
	at zyr.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aadw.run(:com.google.android.gms@224113044@22.41.13 (190400-480714934):0)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
It's a duplicate and resolved already by GmsCompatConfig v15. You just need to update it.

**Comment by lake-effect** [comment]
Is the update already in the stable release channel? Because this is on the latest: 
![IMG_20221111_085150](https://user-images.githubusercontent.com/39317653/201389991-e630c7e8-3468-43e4-bdeb-d101b8f2038b.jpg)

**Comment by thestinger** [comment]
Yes, it's already released in stable. You might have had the crashes from before you updated.

**Comment by avemt1** [comment]
```
type: crash
osVersion: google/raven/raven:13/TP1A.221105.002/2022111000:user/release-keys
package: com.android.vending:83281810
process: com.android.vending

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.com.android.internal.gmscompat.PlayStoreHooks$PackageInstallerStatusForwarder.31 flg=0x10 (has extras) } in com.android.internal.gmscompat.PlayStoreHooks$PackageInstallerStatusForwarder@6a7977d
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.google.android.finsky.packagemanager.impl.PackageMonitorReceiverImpl$RegisteredReceiver
	at com.android.internal.gmscompat.PlayStoreHooks.lambda$uninstallListener$3(PlayStoreHooks.java:272)
	at com.android.internal.gmscompat.PlayStoreHooks$$ExternalSyntheticLambda4.accept(Unknown Source:8)
	at com.android.internal.gmscompat.PlayStoreHooks$PackageInstallerStatusForwarder.onReceive(PlayStoreHooks.java:228)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.google.android.finsky.packagemanager.impl.PackageMonitorReceiverImpl$RegisteredReceiver
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at com.android.internal.gmscompat.PlayStoreHooks.lambda$uninstallListener$3(PlayStoreHooks.java:264)
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.google.android.finsky.packagemanager.impl.PackageMonitorReceiverImpl$RegisteredReceiver
	... 17 more

```
