### ISSUE TITLE
Error in service google play

### ISSUE THREAD

**Issue by thelittlefireman** [GrapheneOS/os-issue-tracker#1679]
```
type: crash
osVersion: google/raven/raven:13/TP1A.221105.002/2022110800:user/release-keys
package: com.google.android.gms:224113044
process: com.google.android.gms.ui

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 611396 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:88)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.TransactionTooLargeException: data parcel size 611396 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1248)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:85)
	... 11 more

```

**Comment by thestinger** [comment]
This appears to be a Play services bug rather than a GrapheneOS specific issue.
