### ISSUE TITLE
Google Play Services Bluetooth crash

### ISSUE THREAD

**Issue by kyuweftea** [GrapheneOS/os-issue-tracker#1711]
This started appearing occasionally after accidentally updating Play Services via Play Store instead of Apps. It has not been granted the Nearby devices permission.

```
type: crash
osVersion: google/barbet/barbet:13/TP1A.221105.002/2022111000:user/release-keys
package: com.google.android.gms:224417044
process: com.google.android.gms.persistent

java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@47f36b3c: BluetoothAdapterService
	at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:482)
	at com.android.bluetooth.Utils.checkConnectPermissionForDataDelivery(Utils.java:514)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.unregisterBluetoothConnectionCallback(AdapterService.java:3182)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.unregisterBluetoothConnectionCallback(AdapterService.java:3172)
	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:1367)
	at android.os.Binder.execTransactInternal(Binder.java:1307)
	at android.os.Binder.execTransact(Binder.java:1265)
	Suppressed: cvhl: 
		at tk_trace.nearby-DiscoveryChimeraService_onDestroy(Unknown Source:0)

```

**Comment by thestinger** [comment]
Update to the latest GmsCompatCompat v17.
