### ISSUE TITLE
Issue nr4


### ISSUE THREAD

**Issue by Gospodininzenjer** [GrapheneOS/os-issue-tracker#1722]
```
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221105.002/2022111800:user/release-keys
package: com.google.android.gsf:33
process: com.google.process.gservices
processUptime: 11385623 + 1473 ms
GmsCompatConfig version: 17

java.lang.RuntimeException: Unable to start receiver com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver: java.lang.SecurityException: com.google.android.gsf was not granted  this permission: android.permission.WRITE_SETTINGS.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4346)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: com.google.android.gsf was not granted  this permission: android.permission.WRITE_SETTINGS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
	at android.content.ContentResolver.insert(ContentResolver.java:2216)
	at android.content.ContentResolver.insert(ContentResolver.java:2175)
	at com.google.android.gsf.gservices.GservicesProvider.syncSettingsFromGsfStorage(GservicesProvider.java:631)
	at com.google.android.gsf.gservices.GservicesProvider.syncAllSettingsFromGsfStorage(GservicesProvider.java:581)
	at com.google.android.gsf.gservices.GservicesProvider.updateGsfStorageOverridesTable(GservicesProvider.java:730)
	at com.google.android.gsf.gservices.GservicesProvider.updateOverride(GservicesProvider.java:425)
	at com.google.android.gsf.gservices.GservicesProvider.update(GservicesProvider.java:385)
	at android.content.ContentProvider.update(ContentProvider.java:1882)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:465)
	at android.content.ContentResolver.update(ContentResolver.java:2423)
	at android.content.ContentResolver.update(ContentResolver.java:2385)
	at com.google.android.gsf.gservices.GservicesProvider$OverrideReceiver.onReceive(GservicesProvider.java:119)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4337)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.provider.Settings.isCallingPackageAllowedToPerformAppOpsProtectedOperation(Settings.java:18589)
	at android.provider.Settings.checkAndNoteWriteSettingsOperation(Settings.java:18477)
	at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:1890)
	at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:1856)
	at com.android.providers.settings.SettingsProvider.insert(SettingsProvider.java:700)


```

**Comment by thestinger** [comment]
Looks like a duplicate report.

**Comment by thestinger** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/1653.

**Comment by muhomorr** [comment]
@Gospodininzenjer Did you grant the "Modify system settings" permission to Play services? If yes, revoke it.
https://github.com/GrapheneOS/os-issue-tracker/issues/1653#issuecomment-1309834803

**Comment by Gospodininzenjer** [comment]
No, it is not granted ....
