### ISSUE TITLE
U2F crash

### ISSUE THREAD

**Issue by mpldr** [GrapheneOS/os-issue-tracker#1760]
When attempting to use my USB-C security key, the following crash occurred:

```
type: crash
osVersion: google/redfin/redfin:13/TP1A.221105.002/2022112500:user/release-keys
package: com.google.android.gms:224417044
process: com.google.android.gms.ui
processUptime: 28209 + 452 ms
GmsCompatConfig version: 17

java.lang.IllegalStateException: Fragment already added: ahfv{fc14e6a} (22a26391-2c0c-46e8-bf8e-68ba133843b4 tag=fragment_fingerprint_or_lock_screen)
	at ev.h(:com.google.android.gms@224417044@22.44.17 (190400-488410709):1)
	at ek.k(:com.google.android.gms@224417044@22.44.17 (190400-488410709):2)
	at ek.aD(:com.google.android.gms@224417044@22.44.17 (190400-488410709):54)
	at ek.aF(:com.google.android.gms@224417044@22.44.17 (190400-488410709):8)
	at ek.ai(:com.google.android.gms@224417044@22.44.17 (190400-488410709):7)
	at dw.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at arwb.ly(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
	at arwb.dispatchMessage(:com.google.android.gms@224417044@22.44.17 (190400-488410709):11)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: cvhl: 

```

**Comment by thestinger** [comment]
Likely resolved by now.
