### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dementsweden** [GrapheneOS/os-issue-tracker#1761]
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221105.002/2022112500:user/release-keys
package: com.google.android.gms:224113044
process: com.google.android.gms.ui
processUptime: 5659 + 186 ms
GmsCompatConfig version: 17

java.lang.IllegalStateException: Fragment juo{cc275ea} (9f25bd73-7615-4910-be17-66a25a5e3daf) not attached to a context.
	at cu.requireContext(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
	at juo.A(:com.google.android.gms@224113044@22.41.13 (190400-480714934):3)
	at juo.z(:com.google.android.gms@224113044@22.41.13 (190400-480714934):0)
	at juo.x(:com.google.android.gms@224113044@22.41.13 (190400-480714934):2)
	at juy.onPostExecute(:com.google.android.gms@224113044@22.41.13 (190400-480714934):6)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by thestinger** [comment]
We need information on what you're doing when the crash occurs.
