### ISSUE TITLE
Error in google play service... and some apps stoped working

### ISSUE THREAD

**Issue by StefanHumg** [GrapheneOS/os-issue-tracker#1766]
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022102600:user/release-keys
package: com.google.android.gms:224417044
process: com.google.android.gms.persistent

java.lang.SecurityException: You need MANAGE_USERS, CREATE_USERS, QUERY_USERS, or GET_ACCOUNTS_PRIVILEGED permissions to: get user name
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.os.IUserManager$Stub$Proxy.getUserName(IUserManager.java:3193)
	at android.os.UserManager.getUserName(UserManager.java:2180)
	at bdbu.j(:com.google.android.gms@224417044@22.44.17 (190400-488410709):2)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.ah(:com.google.android.gms@224417044@22.44.17 (190400-488410709):1)
	at com.google.android.gms.nearby.sharing.NearbySharingChimeraService.X(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
	at bbnv.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
	at aweo.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):3)
	at aabe.c(:com.google.android.gms@224417044@22.44.17 (190400-488410709):6)
	at aabe.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aagj.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: cvhl: 
		at tk_trace.nearby-NearbySharingChimeraService_onCreate(Unknown Source:0)
		at tk_trace.container-PersistentApiService$ChimeraService_onBind(Unknown Source:0)

```

**Comment by muhomorr** [comment]
You're running an outdated version of GrapheneOS (released on October 26th). Current version does not have this issue.

**Comment by StefanHumg** [comment]
Hi,
How to update it?

Promień Iskier

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by muhomorr** [comment]
Settings -> System -> System update

**Comment by StefanHumg** [comment]
Thanks

Wysłano z aplikacji ProtonMail

-------- Oryginalna wiadomość --------
2 gru 2022, 17:12, muhomorr napisał(a):
