### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by Mathew420w0** [GrapheneOS/os-issue-tracker#1849]
```
type: crash
osVersion: google/coral/coral:13/TP1A.221005.002/2022122000:user/release-keys
package: com.android.vending:83321210
process: com.android.vending
processUptime: 13590583 + 3883 ms
GmsCompatConfig version: 18

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchCancelPendingInputEvents()' on a null object reference
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.View.cancelPendingInputEvents(View.java:21413)
	at android.app.Activity.cancelInputsAndStartExitTransition(Activity.java:5558)
	at android.app.Activity.startActivityForResult(Activity.java:5537)
	at zzzi.startActivityForResult(PG:2)
	at android.app.Activity.startActivityForResult(Activity.java:5437)
	at android.app.Activity.startActivity(Activity.java:5974)
	at android.app.Activity.startActivity(Activity.java:5941)
	at mzt.accept(PG:81)
	at kiq.b(Unknown Source:2)
	at ajqr.run(PG:6)
	at qq.execute(PG:11)
	at ajpk.m(PG:1)
	at ajpk.k(PG:11)
	at ajpk.abT(Unknown Source:14)
	at ajpy.m(PG:4)
	at ajpr.h(PG:5)
	at ajpp.run(PG:2)
	at ajqd.execute(Unknown Source:0)
	at ajpk.m(PG:1)
	at ajpk.k(PG:11)
	at ajpk.abT(Unknown Source:14)
	at ajpn.f(Unknown Source:0)
	at ajpo.run(PG:13)
	at qq.execute(PG:11)
	at ajri.execute(PG:4)
	at ajpk.m(PG:1)
	at ajpk.k(PG:11)
	at ajpk.q(PG:3)
	at ajpm.f(PG:2)
	at ajpo.run(PG:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at htu.run(PG:12)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
This is a duplicate and we have no reason to think it's caused by GrapheneOS.
