### ISSUE TITLE
GmsCompat: Implement more user-friendly notice for lack of camera permission (or others)

### ISSUE THREAD

**Issue by GlitchBuddy** [GrapheneOS/os-issue-tracker#1855]
I have encountered a crash in Google Play Services when attempting to take (not choose) a new profile photo from the Google Account settings. Looking through the crash logs, it was because I had not granted the Camera permission for Google Play Services. I believe that this type of crash could be recognized by GmsCompat, and the user could be presented with a more friendly notice explaining that the Camera permission (or any required permission) has not been granted, possibly with the option to grant the permission or dismiss the message.

STEPS TO REPRODUCE:
0. Google Play Services has not been granted the Camera permission
1. Go to Settings > Apps > Sandboxed Google Play > Google Settings > Manage your Google Account
2. Tap on your profile photo and choose 'Set profile photo'
3. Choose 'Take photo'

FULL CRASH LOG:
```
type: crash
osVersion: google/panther/panther:13/TQ1A.221205.011/2022122000:user/release-keys
package: com.google.android.gms:224617044
process: com.google.android.gms.ui
processUptime: 9010 + 396 ms
GmsCompatConfig version: 18

java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=app.grapheneos.camera/.ui.activities.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) } from ProcessRecord{6b31d43 6871:com.google.android.gms.ui/u0a124} (pid=6871, uid=10124) with revoked permission android.permission.CAMERA
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2054)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1840)
	at android.app.Activity.startActivityForResult(Activity.java:5518)
	at gzx.platform_startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):2)
	at gzw.startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):2)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):2)
	at hei.startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):2)
	at gzw.public_startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):2)
	at gzx.startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):3)
	at android.app.Activity.startActivityForResult(Activity.java:5437)
	at gzx.platform_startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):1)
	at gzw.startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):1)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):1)
	at hei.startActivityForResult(:com.google.android.gms@224617044@22.46.17 (190400-491726958):1)
	at com.google.android.gms.people.profile.AvatarChimeraActivity.f(:com.google.android.gms@224617044@22.46.17 (190400-491726958):4)
	at bojl.onClick(:com.google.android.gms@224617044@22.46.17 (190400-491726958):1)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1251)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3270)
	at android.widget.AbsListView$3.run(AbsListView.java:4236)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1110)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1031)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:713)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1292)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1233)


```

**Comment by r3g-5z** [comment]
Doesn't seem to be an issue anymore based on my testing.
