### ISSUE TITLE
Dynamite modules don't work from priv-app

### ISSUE THREAD

**Issue by dot-gov** [GrapheneOS/os-issue-tracker#1881]
To be clear, this isn't an issue on the official distribution because I don't think any of the priv-apps use dynamite modules, but I'm posting this to solicit ideas on how this might be fixed.

I'm trying to get google dialer to work on GrapheneOS. Because of the permissions required, it needs to be installed as a priv-app. However, because of selinux policies, it can't load certain libraries. For instance,
libconscrypt_gmscore_jni.so:
```
01-06 15:03:10.135  4728  4811 I DynamiteModule: Non-system-image GmsCore APK, forcing V1
01-06 15:03:10.164  2533  2692 W ProviderHelper: Unknown dynamite feature providerinstaller.dynamite
01-06 15:03:10.166  4728  4811 I DynamiteModule: Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
01-06 15:03:10.166  4728  4811 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader: Unable to locate conscrypt_gmscore_jni in dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/base.apk"],nativeLibraryDirectories=[/data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/lib/arm64, /data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/base.apk!/lib/arm64-v8a/libconscrypt_gmscore_jni.so" segment 1: Permission denied
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.lang.System.loadLibrary(System.java:1661)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at aaln.g(:com.google.android.gms@224814044@22.48.14 (190400-493411920):2)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at aaln.f(:com.google.android.gms@224814044@22.48.14 (190400-493411920):2)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at com.google.android.gms.providerinstaller.ProviderInstallerImpl.b(:com.google.android.gms@224814044@22.48.14 (190400-493411920):6)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at com.google.android.gms.providerinstaller.ProviderInstallerImpl.insertProvider(:com.google.android.gms@224814044@22.48.14 (190400-493411920):5)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.lang.reflect.Method.invoke(Native Method)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(:com.google.android.gms@224814044@22.48.14 (190400-493411920):2)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.lang.reflect.Method.invoke(Native Method)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at noi.c(PG:2)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at noi.a(PG:11)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at lvl.call(PG:7)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at sqn.a(Unknown Source:2)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at sps.run(PG:3)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at sqo.run(Unknown Source:4)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at nqu.run(PG:44)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at java.lang.Thread.run(Thread.java:1012)
01-06 15:03:10.170  4728  4811 E GmsNativeLibraryLoader:        at ntx.run(PG:6)
01-06 15:03:10.171  4728  4811 W FileUtils: Failed to chmod(/data/user_de/0/com.google.android.gms/app_extracted_libs): android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
01-06 15:03:10.171  4728  4811 W FileUtils: Failed to chmod(/data/user_de/0/com.google.android.gms/app_extracted_libs): android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
01-06 15:03:10.171  4728  4811 W FileUtils: Failed to chmod(/data/user_de/0/com.google.android.gms/app_extracted_libs): android.system.ErrnoException: chmod failed: ENOENT (No such file or directory)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader: Unable to locate conscrypt_gmscore_jni in dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/base.apk"],nativeLibraryDirectories=[/data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/lib/arm64, /data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/app/~~KkaDWLRS2KdLaHoUEKRGHA==/com.google.android.gms-SIfotNVYhZz6rCOWhPCuZg==/base.apk!/lib/arm64-v8a/libconscrypt_gmscore_jni.so" segment 1: Permission denied
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.lang.System.loadLibrary(System.java:1661)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at aaln.g(:com.google.android.gms@224814044@22.48.14 (190400-493411920):24)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at aaln.f(:com.google.android.gms@224814044@22.48.14 (190400-493411920):2)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at com.google.android.gms.providerinstaller.ProviderInstallerImpl.b(:com.google.android.gms@224814044@22.48.14 (190400-493411920):6)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at com.google.android.gms.providerinstaller.ProviderInstallerImpl.insertProvider(:com.google.android.gms@224814044@22.48.14 (190400-493411920):5)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.lang.reflect.Method.invoke(Native Method)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at com.google.android.gms.common.security.ProviderInstallerImpl.insertProvider(:com.google.android.gms@224814044@22.48.14 (190400-493411920):2)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.lang.reflect.Method.invoke(Native Method)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at noi.c(PG:2)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at noi.a(PG:11)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at lvl.call(PG:7)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at sqn.a(Unknown Source:2)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at sps.run(PG:3)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at sqo.run(Unknown Source:4)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at nqu.run(PG:44)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at java.lang.Thread.run(Thread.java:1012)
01-06 15:03:10.172  4728  4811 E GmsNativeLibraryLoader:        at ntx.run(PG:6)
01-06 15:03:10.172  4728  4811 E ProviderInstallerImpl: Failed to call insertProvider of ProviderInstallerImpl stub via reflection!
01-06 15:03:10.172  4728  4811 E ProviderInstaller: Failed to install provider: java.lang.reflect.InvocationTargetException
01-06 15:03:10.172  4728  4811 E GnpSdk  : [PeriodicSyncJob] Failed to install security provider, GrowthKit sync can't run.
01-06 15:03:10.172  4728  4811 E GnpSdk  : nbs
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at noi.c(PG:4)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at noi.a(PG:11)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at lvl.call(PG:7)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at sqn.a(Unknown Source:2)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at sps.run(PG:3)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at sqo.run(Unknown Source:4)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at nqu.run(PG:44)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at java.lang.Thread.run(Thread.java:1012)
01-06 15:03:10.172  4728  4811 E GnpSdk  :      at ntx.run(PG:6)
```
As well as CronetDynamite.apk:
```
01-06 12:46:25.521  5434  5464 I DynamiteModule: Considering local module com.google.android.gms.cronet_dynamite:0 and remote module com.google.android.gms.cronet_dynamite:1611
01-06 12:46:25.521  5434  5464 I DynamiteModule: Selected remote version of com.google.android.gms.cronet_dynamite, version >= 1611
01-06 12:46:25.538  5434  5464 W System  : ClassLoader referenced unknown path:
01-06 12:46:25.545  5434  5464 W com.google.android.dialer: Failed to determine odex file name: Dex location /gmscompat_fd_190 has no extension.
01-06 12:46:25.545  5434  5464 W ziparchive: Unable to open '/gmscompat_fd_190.dm': No such file or directory
01-06 12:46:25.560  5434  5464 W linker  : Warning: unable to resolve "/gmscompat_fd_190": No such file or directory (ignoring)
01-06 12:46:25.556  5434  5434 W com.google.android.dialer: type=1400 audit(0.0:1374): avc: denied { execute } for comm=424720546872656164202330 path="/data/user_de/0/com.google.android.gms/app_chimera/m/00000001/CronetDynamite.apk" dev="dm-50" ino=3374 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c131,c256,c512,c768 tclass=file permissive=0 app=com.google.android.dialer
```
Adding the following selinux policy fixes this:
```
allow priv_app app_data_file:file { execute };
allow priv_app apk_data_file:file { execute };
```
However, there is also a big scary warning against doing so in the default policy files
```
# Do not allow loading executable code from non-privileged
# application home directories. Code loading across a security boundary
# is dangerous and allows a full compromise of a privileged process
# by an unprivileged process. b/112357170
neverallow priv_app app_data_file:file no_x_file_perms;
```

Is there a better solution?

**Comment by thestinger** [comment]
You could move Play services into a dedicate domain and only allow executing from there but quite a lot of work would be involved. On you to do that if you want it. This is all working as intended.
