### ISSUE TITLE
crash- sand boxed google play services

### ISSUE THREAD

**Issue by Jvonline** [GrapheneOS/os-issue-tracker#1898]
```
type: crash
osVersion: google/coral/coral:13/TP1A.221005.002/2023011000:user/release-keys
package: com.google.android.gms:225014044
process: com.google.android.gms
processUptime: 39753021 + 436 ms
GmsCompatConfig version: 25

ddnd: rethrowing exception from lowpool[2]
	at aalb.run(:com.google.android.gms@225014044@22.50.14 (190400-499278674):4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at astc.lC(:com.google.android.gms@225014044@22.50.14 (190400-499278674):0)
	at astc.dispatchMessage(:com.google.android.gms@225014044@22.50.14 (190400-499278674):11)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: cxji: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.ocr-ModelCleanUpTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.IllegalArgumentException: ProtoDataStoreConfig<cilv> doesn't match previous call [uri=android://com.google.android.gms/files/mdd_pds_config/shared/DiagSharedFileswallet_ocr.pb] [migrations]
	at czbc.h(:com.google.android.gms@225014044@22.50.14 (190400-499278674):0)
	at coyx.a(:com.google.android.gms@225014044@22.50.14 (190400-499278674):23)
	at cjfl.get(:com.google.android.gms@225014044@22.50.14 (190400-499278674):7)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@225014044@22.50.14 (190400-499278674):1)
	at cjeu.get(:com.google.android.gms@225014044@22.50.14 (190400-499278674):0)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@225014044@22.50.14 (190400-499278674):1)
	at ciys.a(:com.google.android.gms@225014044@22.50.14 (190400-499278674):0)
	at cjfc.get(:com.google.android.gms@225014044@22.50.14 (190400-499278674):0)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@225014044@22.50.14 (190400-499278674):1)
	at cjef.b(:com.google.android.gms@225014044@22.50.14 (190400-499278674):1)
	at cily.a(:com.google.android.gms@225014044@22.50.14 (190400-499278674):29)
	at cvuy.c(:com.google.android.gms@225014044@22.50.14 (190400-499278674):4)
	at cvuo.e(:com.google.android.gms@225014044@22.50.14 (190400-499278674):1)
	at com.google.android.gms.ocr.service.ModelCleanUpTaskService.a(:com.google.android.gms@225014044@22.50.14 (190400-499278674):7)
	at asuo.call(:com.google.android.gms@225014044@22.50.14 (190400-499278674):4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at aalr.c(:com.google.android.gms@225014044@22.50.14 (190400-499278674):6)
	at aalr.run(:com.google.android.gms@225014044@22.50.14 (190400-499278674):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at aaqv.run(:com.google.android.gms@225014044@22.50.14 (190400-499278674):0)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
cc @muhomorr
