### ISSUE TITLE
Compatibility issues with shizuku

### ISSUE THREAD

**Issue by vvb2060** [GrapheneOS/os-issue-tracker#1900]
```
01-17 19:35:31.249 31990 31990 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
01-17 19:35:31.301 31990 31990 I AndroidRuntime: Using default boot image
01-17 19:35:31.301 31990 31990 I AndroidRuntime: Leaving lock profiling enabled
01-17 19:35:31.303 31990 31990 E cutils-trace: Error opening trace file: No such file or directory (2)
01-17 19:35:31.525 31990 31990 D shizuku_server: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
01-17 19:35:31.525 31990 31990 D shizuku_server: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
01-17 19:35:31.621 31990 31990 D AndroidRuntime: Calling main entry rikka.shizuku.server.ShizukuService
01-17 19:35:31.625 31990 31990 D AndroidRuntime: Shutting down VM
01-17 19:35:31.625 31990 31990 E AndroidRuntime: FATAL EXCEPTION: main
01-17 19:35:31.625 31990 31990 E AndroidRuntime: PID: 31990
01-17 19:35:31.625 31990 31990 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/app/~~sxxTavhYgX_kK_xXF-Ir8w==/moe.shizuku.privileged.api--DiXZIoTYGK-zEdzpY-zlg==/base.apk!/lib/arm64-v8a/librish.so" segment 0: Permission denied
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:929)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at java.lang.System.load(System.java:1625)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at rikka.rish.b.f(SourceFile:3)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at rikka.rish.b.e(SourceFile:4)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at rikka.shizuku.server.c.<init>(SourceFile:2)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at rikka.shizuku.server.ShizukuService.<init>(SourceFile:1)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at rikka.shizuku.server.ShizukuService.main(SourceFile:4)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
01-17 19:35:31.625 31990 31990 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
01-17 19:35:31.621 31990 31990 W main    : type=1400 audit(0.0:26763): avc: denied { execute } for path="/data/app/~~sxxTavhYgX_kK_xXF-Ir8w==/moe.shizuku.privileged.api--DiXZIoTYGK-zEdzpY-zlg==/base.apk" dev="dm-45" ino=209706 scontext=u:r:shell:s0 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0
01-17 19:35:31.626 31990 31990 E AndroidRuntime: Error reporting crash
01-17 19:35:31.626 31990 31990 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4702)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4699)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4690)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
01-17 19:35:31.626 31990 31990 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
01-17 19:35:31.626 31990 31990 I Process : Sending signal. PID: 31990 SIG: 9
```

avc: denied { execute } for path="/data/app/~~sxxTavhYgX_kK_xXF-Ir8w==/moe.shizuku.privileged.api--DiXZIoTYGK-zEdzpY-zlg==/base.apk" dev="dm-45" ino=209706 scontext=u:r: shell:s0 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0

shell should be trusted by user, I don't think this restriction is necessary, it breaks apps that work via adb like https://github.com/RikkaApps/Shizuku

**Comment by vvb2060** [comment]
cc @RikkaW

**Comment by thestinger** [comment]
Any form of network-based ADB should not be persistent because it opens up a verified boot security vulnerability.

**Comment by vvb2060** [comment]
Even with the old way of connecting, if you don't trust the other party's public key, the other party can't connect.  So I don't think there is a security issue.  Malicious connecters can at best gain the same privileges as legitimate users, which will not break verified boot.

**Comment by thestinger** [comment]
Being able to persist ADB access does greatly reduce the security of verified boot. Verified boot is only as useful as the lack of trust in persistent state. Persistent network ADB access is a major weakness in it.

**Comment by vvb2060** [comment]
When adbd dies, system kills the whole cgroup, so this is not persistent. Such as reboot device or switch WiFi networks.

**Comment by vvb2060** [comment]
Of course, I admit that apps like shizuku create a huge attack surface.

**Comment by RikkaW** [comment]
Processes started by adb are killed once adbd dies, such as reboot the device, disable developer options. Shizuku needs to be restarted by the user once adbd dies. I cannot understand why this is "persist ADB access" and why verified boot is related to it. Also, this can be simply bypassed by copying files to `/data/local/tmp`, I'm wondering if making such changes really make sense.

**Comment by qwq233** [comment]
> This was an intentional change. It could be added back but you should be aware that persistent network ADB is going to be removed since it's a major weakness in the verified boot security model.

why wireless adb will weaken verified boot

**Comment by TempUser13** [comment]
If using wireless adb is bad, can there at least be an option to use shizuku over regular adb? I know you don't recommend adb to be enabled but realistically some people are okay with having it enabled and you also have to intentionally enable it and download shizuku so the user is fully aware that this isn't completely safe. Isn't there a way to make shizuku an exception?

**Comment by TempUser13** [comment]
Thank you for making the change so shizuku works
