### ISSUE TITLE
System UI stops responding: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized

### ISSUE THREAD

**Issue by telans** [GrapheneOS/os-issue-tracker#1937]
A dialog opens prompting to either wait of kill the System UI process. If pressing "wait", the UI remains responsive yet the dialog box will continue to appear until the UI is restarted. If force killing the process, the device reverts to the lock screen with no other side effects.

Model: Pixel 6a
Android version: 13
Build number: TQ1A.230105.001.A2.2023012500

I haven't caught this crash live with logcat yet, so below is what I assume the crash is related to.

```
02-05 01:06:12.258  1389  6891 W JobScheduler: Job didn't exist in JobStore: a8ed1ac #u0a33/130 com.android.statementservice/androidx.work.impl.background.systemjob.SystemJobService
02-05 01:06:12.304 15516 15544 E AndroidRuntime: FATAL EXCEPTION: WM.task-1
02-05 01:06:12.304 15516 15544 E AndroidRuntime: Process: com.android.statementservice, PID: 15516
02-05 01:06:12.304 15516 15544 E AndroidRuntime: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at androidx.work.Data.toByteArrayInternal(Data.java:407)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at androidx.work.Data$Builder.build(Data.java:957)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:224)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:140)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
02-05 01:06:12.304 15516 15544 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
02-05 01:06:12.311  1389 15550 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
02-05 01:06:12.313 15516 15544 I Process : Sending signal. PID: 15516 SIG: 9
02-05 01:06:12.314  1389  1462 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{af69c97 2529:com.google.android.gms.persistent/u0a130} (pid=2529, uid=10130) requires android.permission.READ_LOGS due to sender android (uid 1000)
02-05 01:06:12.314  1389  1462 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02-05 01:06:12.314  1389  1462 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02-05 01:06:12.388  1389  9368 I ActivityManager: Process com.android.statementservice (pid 15516) has died: cch+5 CEM 
02-05 01:06:12.388  1389  1469 I libprocessgroup: Successfully killed process cgroup uid 10033 pid 15516 in 0ms
02-05 01:06:12.389   769   769 I Zygote  : Process 15516 exited due to signal 9 (Killed)
```

Feel free to request more logs etc.

**Comment by thestinger** [comment]
That log isn't related and is a known upstream Android issue. You'll need to find the logs for the issue you're encountering

**Comment by telans** [comment]
> That log isn't related and is a known upstream Android issue. You'll need to find the logs for the issue you're encountering

I'll have to get back to you then for when it happens again, as that is the *only* output to `adb logcat --buffer=crash`

**Comment by telans** [comment]
Here are the proper logs: https://dpaste.com/ALFBYNPXB.txt

**Comment by thestinger** [comment]
There's a more recent issue someone filed with instructions for reproducing an issue and for now we'll have to assume this is the same one.

https://github.com/GrapheneOS/os-issue-tracker/issues/1971

**Comment by telans** [comment]
Confirmed, these replication steps correspond exactly to changes I have made on my device.
