### ISSUE TITLE
Error in Android System Intelligence

### ISSUE THREAD

**Issue by n3rdcub** [GrapheneOS/os-issue-tracker#1984]
Notes worth mentioning; was experiencing lockups to the point of an unstable device. I saw a random mention of KDE Connect causing similar issues so I disabled the app to test, it wasn't connected... But it fixed my lockups. 
After a reboot, and running 617 dip in devops I get several of these every hour. Still trying to determine the trigger it seems random
```
type: crash
osVersion: google/panther/panther:13/TQ1A.230205.002/2023022300:user/release-keys
package: com.google.android.as:8715675
process: com.google.android.as
processUptime: 916221 + 400 ms

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 } in fpx@4f6c2ad
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
	at android.provider.DeviceConfig.enforceReadPermission(DeviceConfig.java:1240)
	at android.provider.Settings$NameValueCache.getStringsForPrefix(Settings.java:3327)
	at android.provider.Settings$Config.getStrings(Settings.java:17902)
	at android.provider.DeviceConfig.getProperties(DeviceConfig.java:818)
	at android.provider.DeviceConfig.getProperty(DeviceConfig.java:790)
	at android.provider.DeviceConfig.getInt(DeviceConfig.java:878)
	at jvu.a(Unknown Source:5)
	at etq.i(PG:9)
	at etq.c(PG:2)
	at dwx.e(PG:3)
	at dwx.d(Unknown Source:10)
	at dwp.d(Unknown Source:22)
	at doq.d(Unknown Source:9)
	at dnt.f(PG:2)
	at bva.aC(PG:24)
	at bvh.g(PG:70)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:72)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:73)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:75)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:76)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:79)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bvh.g(PG:80)
	at bvh.a(PG:311)
	at rkf.a(PG:1)
	at bva.aQ(Unknown Source:59)
	at bvh.b(PG:107)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at bva.aP(Unknown Source:2)
	at bvh.b(PG:109)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at bvh.b(PG:115)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at bvh.b(PG:116)
	at bvh.a(PG:313)
	at rkf.a(PG:1)
	at fpx.onReceive(PG:16)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
	... 11 more

```

**Comment by muhomorr** [comment]
Why did you install the Android System Intelligence package? It's not supported on GrapheneOS.

**Comment by n3rdcub** [comment]
Firstly it's not even available in the store, so you can't unless bundled.
Second, https://github.com/KieronQuinn/AmbientMusicMod I had this working  before I assume the recent update and now I get routine crashes for no reason

**Comment by n3rdcub** [comment]
I finally snagged a log hopefully this helps

````
type: crash
osVersion: google/panther/panther:13/TQ1A.230205.002/2023022300:user/release-keys
package: com.android.launcher3:33
process: com.android.launcher3
processUptime: 20916208 + 1104 ms

android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.app.ActivityClient.activityStopped(ActivityClient.java:89)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.DeadSystemException
	... 12 more

````

**Comment by r3g-5z** [comment]
This doesn't look like the same issue you originally posted. Are you reporting an Android System Intelligence crash (which is not supported on GrapheneOS because it requires privileged integration) or are you reporting a Launcher3 crash?

**Comment by n3rdcub** [comment]
Im reporting multiple crashes. As Im not a dev I can't interpret half of this. Cursory glance seems a permission issue but doesn't explain why now months after installing it throws errors?? Is launcher and AndySysIntel related? Don't see how they crash each other

________________________________

**Comment by thestinger** [comment]
Please report one issue per filed issue.

**Comment by n3rdcub** [comment]
So....if I got this correctly, because I don't understand what's being displayed all across my screen and I get big shiny buttons to report, I actually should NOT submit bug reports unless I can read them well enough to notice they're different??


________________________________

**Comment by n3rdcub** [comment]
Also Google services at a whole require privileges integration but team Graphene said nah we got this. 

Can no other dev manage such a feat to port features?

**Comment by thestinger** [comment]
Appears to be intended. This app hasn't been granted a permission it's trying to use.

**Comment by n3rdcub** [comment]
Is this a permission intentionally disallowed like Android auto or Google dialer features?
Or is this something I just need to set myself?
