### ISSUE TITLE
"Android S Easter Egg" crash

### ISSUE THREAD

**Issue by github3939** [GrapheneOS/os-issue-tracker#1996]
Steps to reproduce:

* [Enable the Android Easter Egg](https://www.androidauthority.com/android-13-easter-egg-3180887/) 
* Add "Cat Controls" via the "Device controls" quick settings tile
* Fill the Water bubbler to 200 mL and fill the Food bowl
* Wait for crash, It may take 5-20 minutes to produce the crash.

```
type: crash
osVersion: google/panther/panther:13/TQ1A.230205.002/2023030400:user/release-keys
package: com.android.egg:12
process: com.android.egg
processUptime: 50272 + 299 ms

java.lang.RuntimeException: java.lang.IllegalArgumentException: 0|com.android.egg|1|com.android.egg.neko:allcats|10050 Not posted. PendingIntents attached to bubbles must be mutable
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:109)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.IllegalArgumentException: 0|com.android.egg|1|com.android.egg.neko:allcats|10050 Not posted. PendingIntents attached to bubbles must be mutable
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3025)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:3032)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:678)
	at android.app.NotificationManager.notify(NotificationManager.java:628)
	at com.android.egg.neko.NekoService.notifyCat(NekoService.java:129)
	at com.android.egg.neko.NekoService.triggerFoodResponse(NekoService.java:121)
	at com.android.egg.neko.NekoService.onStartJob(NekoService.java:91)
	at android.app.job.JobService$1.onStartJob(JobService.java:68)
	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:105)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.NotificationManagerService.checkDisqualifyingFeatures(NotificationManagerService.java:6973)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:6640)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:6492)
	at com.android.server.notification.NotificationManagerService$11.enqueueNotificationWithTag(NotificationManagerService.java:3517)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1286)


```

**Comment by thestinger** [comment]
This is the old easter egg, not the current one, and either way we're not going to be changing it downstream.

**Comment by r3g-5z** [comment]
Probably should just disable it going forward if we break Android Easter Eggs consistently. 

https://github.com/GrapheneOS/os-issue-tracker/issues/856#issuecomment-1021686813

**Comment by thestinger** [comment]
I don't think we broke anything. It's part of the old Android 12 easter egg and even in 12 it was a port of an earlier one.
