### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by mateowoetam** [GrapheneOS/os-issue-tracker#2023]
```
type: crash
osVersion: google/coral/coral:13/TP1A.221005.002.B2/2023030400:user/release-keys
package: com.google.android.googlequicksearchbox:301230437
process: com.google.android.googlequicksearchbox:search
processUptime: 10870 + 1402 ms
GmsCompatConfig version: 37

java.lang.RuntimeException: Unable to instantiate receiver com.google.android.apps.search.assistant.verticals.automation.routines.receiver.GeofenceRecoveryReceiver_Receiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.search.assistant.verticals.automation.routines.receiver.GeofenceRecoveryReceiver_Receiver" on path: DexPathList[[zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/base.apk", zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_config.xxxhdpi.apk", zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_fedora_brella_feature_module.apk", zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_lens_ondevice_engine_feature_module.apk"],nativeLibraryDirectories=[/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/lib/arm64, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/base.apk!/lib/arm64-v8a, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_config.xxxhdpi.apk!/lib/arm64-v8a, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_fedora_brella_feature_module.apk!/lib/arm64-v8a, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_lens_ondevice_engine_feature_module.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4293)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2154)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.search.assistant.verticals.automation.routines.receiver.GeofenceRecoveryReceiver_Receiver" on path: DexPathList[[zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/base.apk", zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_config.xxxhdpi.apk", zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_fedora_brella_feature_module.apk", zip file "/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_lens_ondevice_engine_feature_module.apk"],nativeLibraryDirectories=[/data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/lib/arm64, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/base.apk!/lib/arm64-v8a, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_config.xxxhdpi.apk!/lib/arm64-v8a, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_fedora_brella_feature_module.apk!/lib/arm64-v8a, /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_lens_ondevice_engine_feature_module.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
	at androidx.core.app.CoreComponentFactory.instantiateReceiver(PG:1)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4286)
	... 11 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_config.xxxhdpi.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6657)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
		... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_fedora_brella_feature_module.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6657)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
		... 9 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~dryfV6bFRlA-EhboTyHvfw==/com.google.android.googlequicksearchbox-cBbkbjtrVBl_pB4jPmq3kA==/split_lens_ondevice_engine_feature_module.apk because: Entry not found
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3135)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3127)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6657)
		at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
		... 9 more

```

**Comment by thestinger** [comment]
Need more details on what's being reported. What is the problem and how did it happen?

**Comment by deralte99** [comment]
Same issue on my Pixel 6a. Woke up and report Google Sandboxed Play had crashed. Keeps happening on restart. Apps seem to work but no updating happening.  User account. Owner account fine but only one eSIM app on there.

**Comment by muhomorr** [comment]
@mateowoetam @deralte99 How did you install the Google app: from the Play Store or from elsewhere (eg Aurora Store)?
Do you have Play Store installed and enabled?

**Comment by deralte99** [comment]
On the User account Play store installed and enabled.  Mix of Play and
Aurora apps.

On Owner account, Play store installed to get the single app.  Did the
minimum to get the Nomad eSim installed.  Can't switch to eSim on a User
account it seems, only Owner.

Problem is on the User side only with full Play Store install.

**Comment by mateowoetam** [comment]
I have Google services enabled and don't use the aurora store; I use f-droid and PlayStore, Only one account. Not even sure what caused the crash; I wasn't inside any app when it showed up.

**Comment by muhomorr** [comment]
@deralte99 
> Apps seem to work but no updating happening

What do you mean by "no updating happening"?

**Comment by deralte99** [comment]
So usually when I pull down from the top to expand the notifications, at
the bottom is "All apps up to date". Graphene appears to run checks quite
regularly as a visible process as I've never seen that in regular Android.
At any rate, that's not running any more.  GMS Compat still is though so I
assume that's why the apps still work.

**Comment by thestinger** [comment]
The notifications for apps and the OS already being up-to-date is optional. You may have turned it off. We have that there so users can see that there are regular update checks and can easily check when it last happened by looking there. It's our choice to display those notifications by default.

**Comment by deralte99** [comment]
If I turned it off, I didn't do it intentionally and it would have been
coincidental with the crash reports. Its possible. Will have to try and
turn it on again.

**Comment by deralte99** [comment]
All apps up to date has reappeared. May have been a red herring.  Performed a restart. Still getting "Sandboxed Google Play crashed" a few minutes in after restart though.  Beyond the crash report can't really tell much different though.

Not sure if relayed. My widgets have disappeared.  This used to be an issue when changing screen orientation. Still is an issue where widgets don't behave. Could just be a coincident issues as I've had the widget issue for many months since switching over to Graphene.
