### ISSUE TITLE
Bluetooth crash

### ISSUE THREAD

**Issue by MrJay8592** [GrapheneOS/os-issue-tracker#2025]
```
type: crash
osVersion: google/bluejay/bluejay:13/T2B3.230109.009/2023031300:user/release-keys
package: com.android.bluetooth:33
process: com.android.bluetooth
processUptime: 9403 + 76 ms

java.lang.SecurityException: validateSignalStrengthUpdateRequest: Neither user 1002 nor current process has android.permission.LISTEN_ALWAYS_REPORTED_SIGNAL_STRENGTH.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.setSignalStrengthUpdateRequest(ITelephony.java:14498)
	at android.telephony.TelephonyManager.setSignalStrengthUpdateRequest(TelephonyManager.java:16614)
	at com.android.bluetooth.hfp.HeadsetPhoneState.startListenForPhoneState(HeadsetPhoneState.java:171)
	at com.android.bluetooth.hfp.HeadsetPhoneState.listenForPhoneState(HeadsetPhoneState.java:145)
	at com.android.bluetooth.hfp.HeadsetStateMachine.updateAgIndicatorEnableState(HeadsetStateMachine.java:2101)
	at com.android.bluetooth.hfp.HeadsetStateMachine.-$$Nest$mupdateAgIndicatorEnableState(Unknown Source:0)
	at com.android.bluetooth.hfp.HeadsetStateMachine$Connected.enter(HeadsetStateMachine.java:1047)
	at com.android.internal.util.StateMachine$SmHandler.invokeEnterMethods(StateMachine.java:1038)
	at com.android.internal.util.StateMachine$SmHandler.performTransitions(StateMachine.java:880)
	at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:820)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by r3g-5z** [comment]
Update to latest beta or wait for stable.
