### ISSUE TITLE
Cannot toggle bluetooth when in airplane mode; attempting to do so in settings crashes

### ISSUE THREAD

**Issue by Pi-Time** [GrapheneOS/os-issue-tracker#2038]
I frequently use my phone on airplane mode and on occasion use my bluetooth headphones. In the latest GrapheneOS update to my Pixel 4a, attempting to toggle bluetooth on the control center while airplane mode is enabled does not elicit a response and tapping it in rapid succession will cause the system to crash and return to the boot screen. When attempting to toggle bluetooth in the settings app, the app crashes. Resetting network settings does not appear to alleviate it and I am stuck with turning off airplane mode before changing bluetooth settings. Crash report is below:

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ2A.230305.008.C1/2023031500:user/release-keys
package: com.android.settings:33
process: com.android.settings
processUptime: 2624 + 396 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.bluetooth.BluetoothAirplaneModeListener.updateBluetoothToggledTime()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.bluetooth.IBluetoothManager$Stub$Proxy.enable(IBluetoothManager.java:412)
	at android.bluetooth.BluetoothAdapter.enable(BluetoothAdapter.java:1465)
	at com.android.settings.connecteddevice.PreviouslyConnectedDeviceDashboardFragment.enableBluetoothIfNecessary(PreviouslyConnectedDeviceDashboardFragment.java:84)
	at com.android.settings.connecteddevice.PreviouslyConnectedDeviceDashboardFragment.onStart(PreviouslyConnectedDeviceDashboardFragment.java:78)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3081)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1396)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2911)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2839)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:273)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:425)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
	at android.app.Activity.performStart(Activity.java:8413)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3667)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.bluetooth.BluetoothManagerService.enable(BluetoothManagerService.java:1381)
	at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:177)
	at android.os.Binder.execTransactInternal(Binder.java:1302)
	at android.os.Binder.execTransact(Binder.java:1265)


```

**Comment by r3g-5z** [comment]
Unable to reproduce. Been using Airplane mode + Bluetooth with no problems, tried spamming the Bluetooth quick tile and it works fine.

**Comment by BlauerHunger** [comment]
similar issue here with GrapheneOS on Pixel 6

When in Airplane Mode (with WiFi connected in my case) I tap the Bluetooth tile to enable BT it shows "activating" until some kind of timeout without actually activating it. Going into Bluetooth settings (long press quick tile) works, but when I press "Pairing" or "show all devices" (I'm not using the english version), the settings app crashes with the backtrace attached below. 

When I disable Airplane mode everything works as expected until I enable it again. Reboots don't change anything.

```
type: crash
osVersion: google/oriole/oriole:13/T2B3.230109.009/2023031500:user/release-keys
package: com.android.settings:33
process: com.android.settings
processUptime: 1107 + 224 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.bluetooth.BluetoothAirplaneModeListener.updateBluetoothToggledTime()' on a null object reference
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
 at android.os.Parcel.createException(Parcel.java:3005)
 at android.os.Parcel.readException(Parcel.java:2981)
 at android.os.Parcel.readException(Parcel.java:2923)
 at android.bluetooth.IBluetoothManager$Stub$Proxy.enable(IBluetoothManager.java:412)
 at android.bluetooth.BluetoothAdapter.enable(BluetoothAdapter.java:1465)
 at com.android.settings.connecteddevice.PreviouslyConnectedDeviceDashboardFragment.enableBluetoothIfNecessary(PreviouslyConnectedDeviceDashboardFragment.java:84)
 at com.android.settings.connecteddevice.PreviouslyConnectedDeviceDashboardFragment.onStart(PreviouslyConnectedDeviceDashboardFragment.java:78)
 at androidx.fragment.app.Fragment.performStart(Fragment.java:3081)
 at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
 at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
 at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1396)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2911)
 at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2839)
 at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:273)
 at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:425)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
 at android.app.Activity.performStart(Activity.java:8413)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3667)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7891)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.bluetooth.BluetoothManagerService.enable(BluetoothManagerService.java:1381)
 at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:177)
 at android.os.Binder.execTransactInternal(Binder.java:1302)
 at android.os.Binder.execTransact(Binder.java:1265)

```

**Comment by FusionDragon** [comment]
Also having this issue, Pixel 4A base.
```
```
type: crash
osVersion: google/sunfish/sunfish:13/TQ2A.230305.008.C1/2023031500:user/release-keys
package: com.android.settings:33
process: com.android.settings
processUptime: 6022 + 324 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.bluetooth.BluetoothAirplaneModeListener.updateBluetoothToggledTime()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.bluetooth.IBluetoothManager$Stub$Proxy.enable(IBluetoothManager.java:412)
	at android.bluetooth.BluetoothAdapter.enable(BluetoothAdapter.java:1465)
	at com.android.settings.bluetooth.BluetoothPairingDetail.updateBluetooth(BluetoothPairingDetail.java:95)
	at com.android.settings.bluetooth.BluetoothPairingDetail.onStart(BluetoothPairingDetail.java:79)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3081)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1396)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2911)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2839)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:273)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:425)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
	at android.app.Activity.performStart(Activity.java:8413)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3667)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.bluetooth.BluetoothManagerService.enable(BluetoothManagerService.java:1381)
	at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:177)
	at android.os.Binder.execTransactInternal(Binder.java:1302)
	at android.os.Binder.execTransact(Binder.java:1265)


```
```

**Comment by FusionDragon** [comment]
> Unable to reproduce. Been using Airplane mode + Bluetooth with no problems, tried spamming the Bluetooth quick tile and it works fine.

For me the quick tile gets stuck on "Turning on..." and it doesn't change until I turn it back off. Auto connect doesn't work because it's not turning on.

**Comment by BlauerHunger** [comment]
Just installed the update that came out recently (TQ2A.230305.008.E1.2023032000), the issue persists.

**Comment by Pi-Time** [comment]
To clarify, I had forgotten to mention the specific behavior when turning bluetooth on in airplane mode, but it is consistent with what everyone else has mentioned. The feature to shut off bluetooth after inactivity also seems to trigger this issue. I also experience this issue in the latest update.

**Comment by FusionDragon** [comment]
> Are you using secondary user profiles?

I am not using a secondary profile, this issue still persists.

**Comment by Pi-Time** [comment]
The issue is present in the update that I received today (TQ2A.230305.008.C1.2023040400) after turning off the multiple profile function.

**Comment by TempUser13** [comment]
This is still an issue on TQ2A.230305.008.E1.2023040400, Pixel 6. If airplane is off, I can turn Bluetooth on and connect a device then turn airplane mode on but if the Bluetooth device disconnects while airplane mode is enabled then the device will keep soft rebooting then eventually the device will enter recovery with the message that it thinks the os is corrupt. If the Bluetooth device disconnects with airplane disabled then everything works as intended. The device soft rebooting doesn't happen straight away so you can unlock the phone and then turn airplane off and then turn Bluetooth off but it will reboot if left alone.

**Comment by Mrnofish** [comment]
For those who are experiencing this issue can you please try the following and report back?

First you will need to have working ADB access of some kind. Make it to the shell, then go:

`settings put global apm_enhancement_enable 1`

Make sure there are no mistakes.

This should revert the toggle behavior to normal and resolve crashes.

**Comment by Mrnofish** [comment]
For those who are having the issue, please try the following:

First of all, you'll need ADB/shell access of some kind. What we're going to achieve, is reset all airplane mode settings to their stock values.

From the shell, issue the following. Make sure you type everything exactly:
```
settings put global bt_default_apm_state 0
settings put global airplane_mode_toggleable_radios bluetooth,wifi,nfc
settings put global airplane_mode_radios cell,bluetooth,wifi,nfc,wimax
settings put global apm_enhancement_enabled 0
```

Make sure Wi-Fi, Bluetooth and Airplane Mode are all disabled.
Reboot.
Enable Airplane Mode. Test the Bluetooth tile.

I am not sure whether some of the steps are optional, but having lost a considerable amount of time to find a solution, I went with the shotgun approach.

**Comment by FusionDragon** [comment]
> If you're experiencing the issue, please try the following:
> 
> First of all, you'll need ADB/shell access of some kind. What we're going to achieve, is reset all airplane mode settings to their stock values.
> 
> 1. From the shell, issue the following. Make sure you type everything exactly:
> 
> ```
> settings put global bt_default_apm_state 0
> settings put global airplane_mode_toggleable_radios bluetooth,wifi,nfc
> settings put global airplane_mode_radios cell,bluetooth,wifi,nfc,wimax
> settings put global apm_enhancement_enabled 0
> ```
> 
> 2. Check that Wi-Fi, Bluetooth and Airplane Mode are all disabled.
> 3. Reboot.
> 4. Enable Airplane Mode.
> 5. Test the Bluetooth tile.
> 
> I am not sure whether some of the steps are optional, but having lost a considerable amount of time to find a solution, I went with the shotgun approach.

Can confirm this workaround works. I may have also unintentionally found out how I caused this issue. I am using the System UI Tuner application by Zacharee1. I used the function which allows me to exempt radios from being affected by the airplane mode toggle. This was not an issue prior to the update which this was first reported, I was using Bluetooth just fine with WiFi, Bluetooth, and NFC exempt from the airplane mode toggle. Now however after setting those to exempt (after doing your workaround), it has again broken Bluetooth in airplane mode. Anyone who is using System UI Tuner should not touch the airplane mode tweaks function. Something in the recent update is preventing exemptions from working for Bluetooth.

**Comment by Pi-Time** [comment]
@Mrnofish: Thanks for the tip! The Airplane mode exemptions became second nature after I used system UI tuner, disabled it, and subsequently forgot about it. Bummer that the exemptions can't be used for now, but at least Bluetooth works fine again.

**Comment by thestinger** [comment]
@Pi-Time That's already a standard feature... so the issue is that you're setting broken internal settings. I suggest a factory reset.

**Comment by Pi-Time** [comment]
@thestinger Thanks for taking a look. If I understood you correctly, where might I find the Airplane Mode exemptions in the standard settings app? I recall finding it in the developer options on my old Pixel 2.

Fortunately in my case, the third command Mrnofish mentioned did get rid of the crashes without having to factory reset.

**Comment by thestinger** [comment]
It remembers which radios you had enabled last time and doesn't disable them when enabling it again.

**Comment by FusionDragon** [comment]
> @thestinger Thanks for taking a look. If I understood you correctly, where might I find the Airplane Mode exemptions in the standard settings app? I recall finding it in the developer options on my old Pixel 2.
> 
> Fortunately in my case, the third command Mrnofish mentioned did get rid of the crashes without having to factory reset.
> Edit: For anyone curious, the commands won't restore default GrapheneOS behavior, that does require the reset

Factory reset is not necessary. Follow my steps above and it'll fix the Bluetooth issue.

**Comment by FusionDragon** [comment]
> @thestinger Thanks for taking a look. If I understood you correctly, where might I find the Airplane Mode exemptions in the standard settings app? I recall finding it in the developer options on my old Pixel 2.
> 
> Fortunately in my case, the third command Mrnofish mentioned did get rid of the crashes without having to factory reset.
> Edit: For anyone curious, the commands won't restore default GrapheneOS behavior, that does require the reset

What do you mean it doesn't restore default GrapheneOS behavior?

**Comment by Pi-Time** [comment]
I'm not certain if I understand everything here. As far as I can tell from @thestinger , the default behavior would be that I can go into airplane mode for the first time, turn bluetooth or wifi back on, and when I exit and re-enter airplane mode, it won't touch whatever I turned on again.
When I ran the commands again and rebooted, I could not get airplane mode to remember what I toggled. Granted, it does not diminish the usefulness of your solution because I do not have the time to deal with a factory reset.

**Comment by thestinger** [comment]
You have changed the default way it works.

**Comment by FusionDragon** [comment]
> I'm not certain if I understand everything here. As far as I can tell from @thestinger , the default behavior would be that I can go into airplane mode for the first time, turn bluetooth or wifi back on, and when I exit and re-enter airplane mode, it won't touch whatever I turned on again. When I ran the commands again and rebooted, I could not get airplane mode to remember what I toggled; bluetooth shuts off when entering airplane mode regardless. Granted, it does not diminish the usefulness of your solution because I do not have the time to deal with a factory reset.

This wasn't the case for me when i first got graphene os, also it wasn't a major patch. The change was a patch that broke it i think. It wasn't a jump from 12-13 or anything like that. It was working perfectly fine before so it's hard not to see it as an update issue if you get what i mean.

**Comment by Mrnofish** [comment]
Not sure if graphene is different from Lineage which is what I use, FWIW I took the defaults from the Android source code repo and they do restore default behavior for me.

As for how Android manages airplane mode now, there are accounts of these changes on specialist news site.

I can attest the normal logic for Bluetooth requires certain conditions to be met.

For instance BT won't turn off on entering APM, as long as there is a device such as a headset with an active connection. I haven't paid particular attention to the one applied to WiFi, though.

I guess the most surefire way to ascertain the behaviors would be to look at source code.
