### ISSUE TITLE
App "ZITY" crash

### ISSUE THREAD

**Issue by skariko** [GrapheneOS/os-issue-tracker#2055]
Hello,
I am using GrapheneOS on a Pixel 6, with Google Play Services and logged in Play Store on the owner's profile.

The application called ZITY (is a car sharing) crash after a few seconds with this error:

```
type: crash
osVersion: google/oriole/oriole:13/TQ2A.230305.008.E1/2023032000:user/release-keys
package: es.zitycar.carsharing:30000046
process: es.zitycar.carsharing
processUptime: 5229 + 384 ms

java.lang.IllegalStateException: KAAS SDK is not running on a safe device!
	at com.continental.kaas.library.KAAS.initializeSafetyCheck(:754)
	at com.continental.kaas.library.KAAS.init(:160)
	at es.zitycar.carsharing.common.ota.KaasManager.initialize(KaasManager.kt:47)
	at es.zitycar.carsharing.common.ota.BleManager$Companion.initialize(BleManager.kt:38)
	at es.zitycar.carsharing.ZityApplication$onCreate$1.invokeSuspend(ZityApplication.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by thestinger** [comment]
Looks like the app is deliberately not supporting alternate operating systems. This could probably be worked around but it's an issue with the app and they should really just stop breaking it on purpose.
