### ISSUE TITLE
Wallpaper App Crash

### ISSUE THREAD

**Issue by Bugreporter48** [GrapheneOS/os-issue-tracker#2063]
The wallpaper app crashes when I try to change the wallpaper.

### Showcase
https://user-images.githubusercontent.com/127946441/228704390-a395e0a9-1378-4c27-b47c-144d5c541510.mp4

### Log
```
type: crash
osVersion: google/redfin/redfin:13/TQ2A.230305.008.C1/2023032600:user/release-keys
package: com.android.wallpaper:33
process: com.android.wallpaper
processUptime: 1068 + 284 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
at com.android.wallpaper.picker.PreviewFragment.onCreate(PreviewFragment.java:156)
at com.android.wallpaper.picker.LivePreviewFragment.onCreate(LivePreviewFragment.java:128)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:3009)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2832)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:417)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:247)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
at android.app.Activity.performStart(Activity.java:8413)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3667)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7891)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

```

**Comment by wwwcccc1** [comment]
This may be an upstream bug, I can reproduce it with both my Pixel 7 on latest GOS and another phone with Arrow OS 13 with geometric weather set as the wallpaper. Only happens with geometric weather live wallpaper

**Comment by thestinger** [comment]
Is this still an issue with the latest release?

**Comment by Bugreporter48** [comment]
Just tested and it works again.
