### ISSUE TITLE
Google play services crush in the background

### ISSUE THREAD

**Issue by manooll** [GrapheneOS/os-issue-tracker#2066]
I have play service with disabled access to the web. 
Did not do anything special to cause the crash, seem to have crushed in the background:

```
type: crash
osVersion: google/panther/panther:13/TQ2A.230305.008/2023032600:user/release-keys
package: com.google.android.gms:231015044
process: com.google.android.gms
processUptime: 85913480 + 305 ms
GmsCompatConfig version: 43

java.lang.RuntimeException: Unable to unbind to service com.google.android.gms.chimera.GmsBoundBrokerService@612338c with Intent { act=com.google.android.chimera.BoundService.START dat=chimera-action: cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }: hcx: android.os.DeadObjectException
	at android.app.ActivityThread.handleUnbindService(ActivityThread.java:4564)
	at android.app.ActivityThread.-$$Nest$mhandleUnbindService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2168)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: hcx: android.os.DeadObjectException
	at com.google.android.chimera.container.router.BoundServiceRouter.onUnbind(:com.google.android.gms@231015044@23.10.15 (190400-517566699):2)
	at gwc.onUnbind(:com.google.android.gms@231015044@23.10.15 (190400-517566699):0)
	at yhc.onUnbind(:com.google.android.gms@231015044@23.10.15 (190400-517566699):2)
	at gwf.onUnbind(:com.google.android.gms@231015044@23.10.15 (190400-517566699):2)
	at gwi.onUnbind(:com.google.android.gms@231015044@23.10.15 (190400-517566699):3)
	at ycs.onUnbind(:com.google.android.gms@231015044@23.10.15 (190400-517566699):3)
	at android.app.ActivityThread.handleUnbindService(ActivityThread.java:4548)
	... 11 more
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at gno.gt(:com.google.android.gms@231015044@23.10.15 (190400-517566699):2)
	at hcz.k(:com.google.android.gms@231015044@23.10.15 (190400-517566699):0)
	at com.google.android.chimera.container.router.BoundServiceRouter.onUnbind(:com.google.android.gms@231015044@23.10.15 (190400-517566699):1)
	... 17 more

```

**Comment by muhomorr** [comment]
This is a Play services bug.
