### ISSUE TITLE
Play Store Crash

### ISSUE THREAD

**Issue by Klejdi-Bozho** [GrapheneOS/os-issue-tracker#2078]
```
type: crash
osVersion: google/raven/raven:13/TQ2A.230305.008.E1/2023032600:user/release-keys
package: com.android.vending:83511110
process: com.android.vending
processUptime: 46841528 + 305 ms
GmsCompatConfig version: 44

java.lang.NullPointerException: Attempt to invoke virtual method 'void hwa.b(float, float, float, float)' on a null object reference
	at hcb.run(PG:60)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by thestinger** [comment]
Likely just a Play Store bug. Can you provide any more details?

**Comment by thestinger** [comment]
Are you doing anything specific that triggers a crash and is it noticeable to you other than the notification we create?
