### ISSUE TITLE
Crash when downloading eSIM subscription in MyKyivstar app

### ISSUE THREAD

**Issue by immunizedcarbon** [GrapheneOS/os-issue-tracker#2086]
Hello, 

I tried to activate eSIM through the official app of the operator Kyivstar. But the app crashes after I press the activation button.
Playstore, Play Services and Framework is installed and eSIM management is activated. 
Also tried to give the app every access it asks for and the compatibility mode.

Is this an App or GrapheneOS related error? The error log is below. Thank you!

type: crash
osVersion: google/bluejay/bluejay:13/TQ2A.230305.008.E1/2023040400:user/release-keys
package: com.kyivstar.mykyivstar:23560
process: com.kyivstar.mykyivstar
processUptime: 50078 + 440 ms

java.lang.RuntimeException: Error receiving broadcast Intent { act=download_subscription flg=0x10 } in com.truphone.android.esim.EsimOperationBroadcastReceiver@4d2304a
 at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1800)
 at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7891)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.IllegalArgumentException: Invalid result intent
 at android.telephony.euicc.EuiccManager.startResolutionActivity(EuiccManager.java:1006)
 at com.truphone.android.esim.EsimOperationBroadcastReceiver.resolveDownloadSubscriptionError(EsimOperationBroadcastReceiver.java:112)
 at com.truphone.android.esim.EsimOperationBroadcastReceiver.onReceive(EsimOperationBroadcastReceiver.java:85)
 at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1790)
 ... 11 more

**Comment by thestinger** [comment]
Have you tried using the Google eSIM activation app instead?

**Comment by maade69** [comment]
I have successfully installed eSIM using carrier app (not KyivStar). Might be an issue with the carrier app itself.
