### ISSUE TITLE
Crash on show or create contact

### ISSUE THREAD

**Issue by camporter** [GrapheneOS/os-issue-tracker#2094]
When using an app that sends the `com.android.contacts.action.SHOW_OR_CREATE_CONTACT` intent, such as k9 mail when pressing on an email sender, the contacts app crashes:

```
type: crash
osVersion: google/cheetah/cheetah:13/TQ2A.230305.008.C1/2023040400:user/release-keys
package: com.android.contacts:10734
process: com.android.contacts
processUptime: 87 + 218 ms

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:866)
at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:829)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:717)
at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
at android.app.Activity.createDialog(Activity.java:1872)
at android.app.Activity.showDialog(Activity.java:4980)
at android.app.Activity.showDialog(Activity.java:4939)
at com.android.contacts.activities.ShowOrCreateActivity.onQueryComplete(ShowOrCreateActivity.java:205)
at com.android.contacts.util.NotifyingAsyncQueryHandler.onQueryComplete(NotifyingAsyncQueryHandler.java:61)
at android.content.AsyncQueryHandler.handleMessage(AsyncQueryHandler.java:344)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7891)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

I think this might be related to the updates to use androidx for the `AlertDialog`s: https://github.com/GrapheneOS/platform_packages_apps_Contacts/commit/ca0f697dcf58350e1d09aa5ea24798e67dc94c60

**Comment by r3g-5z** [comment]
Fixed in next GrapheneOS release
