### ISSUE TITLE
Vendetta crashes on startup
Vendetta: https://github.com/vendetta-mod/VendettaManager
I am on the newest GOS version. 
If there was a template, I am sorry the mobile app didnt show it. I also couldnt a similar issue on the tracker

### ISSUE THREAD

**Issue by einekratzekatze** [GrapheneOS/os-issue-tracker#2096]
```
type: crash
osVersion: google/oriole/oriole:13/TQ2A.230305.008.E1/2023040400:user/release-keys
package: dev.beefers.vendetta:172024
process: dev.beefers.vendetta
processUptime: 651 + 38 ms

android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:211)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.Applicatio
[TRUNCATED 32249 CHARS]
cel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:206)
	at android.app.compat.gms.GmsCompat.isGmsApp(GmsCompat.java:186)
	at android.app.compat.gms.GmsCompat.isClientOfGmsCore(GmsCompat.java:243)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.maybeAdjustApplicationInfo(GmcPackageManager.java:70)
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:510)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:490)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:484)
	at org.lsposed.lspatch.loader.SigBypass.replaceSignature(SigBypass.java:44)
	at org.lsposed.lspatch.loader.SigBypass.-$$Nest$smreplaceSignature(Unknown Source:0)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:89)
	at org.lsposed.lspatch.loader.SigBypass$2.createFromParcel(SigBypass.java:85)
	at android.os.Parcel.readTypedObject(Parcel.java:4003)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:4506)
	at android.content.pm.PackageManager.getPackageInfoAsUserUncached(PackageManager.java:10496)
	at android.content.pm.PackageManager.-$$Nest$smgetPackageInfoAsUserUncached(Unknown Source:0)
	at android.content.pm.PackageManager$2.recompute(PackageManager.java:10509)
	at android.content.pm.PackageManager$2.recompute(PackageManager.java:10506)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.content.pm.PackageManager.getPackageInfoAsUserCached(PackageManager.java:10523)
	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:250)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:215)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:209)
	at t9.i.d(SourceFile:127)
	at t9.g.f(SourceFile:1)
	at t9.f.f(Unknown Source:0)
	at w9.h0.b(SourceFile:61)
	at com.google.android.gms.common.api.internal.t.E(SourceFile:42)
	at com.google.android.gms.common.api.internal.c.j(SourceFile:36)
	at com.google.android.gms.common.api.internal.c.handleMessage(SourceFile:403)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.DeadSystemException
	... 631 more

```

**Comment by r3g-5z** [comment]
LSPosed and other root-related system modifications to GrapheneOS are not supported, especially signature spoofing. You are not running GrapheneOS by making these modifications and we cannot solve these issues.

**Comment by einekratzekatze** [comment]
> LSPosed and other root-related system modifications to GrapheneOS are not supported, especially signature spoofing. You are not running GrapheneOS by making these modifications and we cannot solve these issues.

Just tried it without gms, and the app works normally. The crash isnt caused by GOS being incompatible with the way the app was patched
