### ISSUE TITLE
Google play sandbox crashed

### ISSUE THREAD

**Issue by robelene112** [GrapheneOS/os-issue-tracker#2152]
Dear devs,

Today i got a notification stating that google play sandbox crashed. I thought you should know so that's why i opened this issue. Here js the full crash report:
```
type: crash
osVersion: google/panther/panther:13/TQ2A.230405.003.E1/2023041100:user/release-keys
package: com.google.android.gms:231312044
process: com.google.android.gms.persistent
processUptime: 42437582 + 508 ms
GmsCompatConfig version: 49

java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.libraries.geller.portable.Geller.nativeCreate(com.google.android.libraries.geller.portable.callbacks.GellerStorageOperationsCallback, com.google.android.libraries.geller.portable.GellerStorageChangeListenerHandler, com.google.android.libraries.geller.portable.callbacks.GellerLoggingCallback, byte[]) (tried Java_com_google_android_libraries_geller_portable_Geller_nativeCreate and Java_com_google_android_libraries_geller_portable_Geller_nativeCreate__Lcom_google_android_libraries_geller_portable_callbacks_GellerStorageOperationsCallback_2Lcom_google_android_libraries_geller_portable_GellerStorageChangeListenerHandler_2Lcom_google_android_libraries_geller_portable_callbacks_GellerLoggingCallback_2_3B)
	at com.google.android.libraries.geller.portable.Geller.nativeCreate(Native Method)
	at com.google.android.libraries.geller.portable.Geller.<init>(:com.google.android.gms@231312044@23.13.12 (190400-519946965):7)
	at ckly.a(:com.google.android.gms@231312044@23.13.12 (190400-519946965):2)
	at dppf.<init>(:com.google.android.gms@231312044@23.13.12 (190400-519946965):15)
	at aznc.a(:com.google.android.gms@231312044@23.13.12 (190400-519946965):138)
	at ayva.i(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at ayva.d(:com.google.android.gms@231312044@23.13.12 (190400-519946965):0)
	at ayva.b(:com.google.android.gms@231312044@23.13.12 (190400-519946965):1)
	at ayva.c(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at aznc.a(:com.google.android.gms@231312044@23.13.12 (190400-519946965):89)
	at ayva.i(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at ayva.d(:com.google.android.gms@231312044@23.13.12 (190400-519946965):0)
	at ayva.b(:com.google.android.gms@231312044@23.13.12 (190400-519946965):1)
	at ayva.c(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at babb.<init>(:com.google.android.gms@231312044@23.13.12 (190400-519946965):5)
	at aznc.a(:com.google.android.gms@231312044@23.13.12 (190400-519946965):95)
	at ayva.i(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at ayva.d(:com.google.android.gms@231312044@23.13.12 (190400-519946965):0)
	at ayva.b(:com.google.android.gms@231312044@23.13.12 (190400-519946965):1)
	at ayva.c(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at bakx.<init>(:com.google.android.gms@231312044@23.13.12 (190400-519946965):0)
	at aznc.a(:com.google.android.gms@231312044@23.13.12 (190400-519946965):11)
	at ayva.i(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at ayva.d(:com.google.android.gms@231312044@23.13.12 (190400-519946965):0)
	at ayva.b(:com.google.android.gms@231312044@23.13.12 (190400-519946965):1)
	at ayva.c(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at aznk.<init>(:com.google.android.gms@231312044@23.13.12 (190400-519946965):2)
	at aznc.a(:com.google.android.gms@231312044@23.13.12 (190400-519946965):1)
	at ayva.i(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at ayva.d(:com.google.android.gms@231312044@23.13.12 (190400-519946965):0)
	at ayva.b(:com.google.android.gms@231312044@23.13.12 (190400-519946965):1)
	at ayva.c(:com.google.android.gms@231312044@23.13.12 (190400-519946965):3)
	at com.google.android.gms.nearby.discovery.service.DiscoveryChimeraService.onCreate(:com.google.android.gms@231312044@23.13.12 (190400-519946965):4)
	at haw.onCreate(:com.google.android.gms@231312044@23.13.12 (190400-519946965):1)
	at yjn.onCreate(:com.google.android.gms@231312044@23.13.12 (190400-519946965):4)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4489)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2158)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

On my end it appears google play works as intended so i have no unusual behaviour to report. I hope this helps.

**Comment by muhomorr** [comment]
Stack trace is almost identical to https://github.com/GrapheneOS/os-issue-tracker/issues/1561

This is likely an upstream AOSP bug in handling of package updates.
