### ISSUE TITLE
After some accidental presses, Play Store crashes when opening certain apps' pages

### ISSUE THREAD

**Issue by GlitchBuddy** [GrapheneOS/os-issue-tracker#2166]
While browsing Google Play Store, I accidentally made a couple of rapid presses when putting my phone down. Sandboxed Google Play then proceeded to crash. I rebooted my phone, but now Play Store crashes when opening the pages of _certain_ apps. For example, I can view these apps fine:

- Disney+
- PicsArt
- Duolingo

But these apps will crash Play Store:

- Prime Video
- Google Chat
- Peridot

There doesn't seem to be a pattern I can discern.

The full error is below:
```
type: crash
osVersion: google/panther/panther:13/TQ2A.230405.003.E1/2023042900:user/release-keys
package: com.android.vending:83551610
process: com.android.vending
processUptime: 1673 + 301 ms

java.lang.IllegalStateException: Already has a parent override
	at aorl.cp(Unknown Source:7)
	at ajjj.i(PG:3)
	at ajjj.c(PG:3)
	at aauo.a(PG:34)
	at agjh.e(PG:2)
	at ajgx.ado(PG:4)
	at czp.d(Unknown Source:4)
	at cyv.d(PG:8)
	at cyw.x(PG:13)
	at cyw.i(PG:1)
	at dcb.e(PG:30)
	at cxa.e(PG:3)
	at cxa.e(PG:3)
	at cxa.e(PG:3)
	at cyw.e(PG:1)
	at ede.e(PG:14)
	at ecx.a(PG:13)
	at bmc.a(PG:2)
	at bgu.a(PG:1)
	at bgn.a(PG:33)
	at blw.a(PG:3)
	at ecz.e(PG:7)
	at ehs.e(PG:6)
	at aln.a(PG:3)
	at ect.g(PG:3)
	at eie.e(PG:8)
	at all.a(PG:3)
	at ect.g(PG:3)
	at eie.e(PG:8)
	at drf.g(PG:3)
	at eie.e(PG:8)
	at bau.g(PG:6)
	at eie.e(PG:8)
	at ejh.a(Unknown Source:8)
	at dii.c(PG:7)
	at djp.b(PG:13)
	at elh.d(PG:3)
	at elh.c(PG:1)
	at ejf.A(PG:6)
	at ejf.e(PG:10)
	at azv.e(PG:8)
	at ehs.e(PG:6)
	at ejh.a(Unknown Source:8)
	at dii.c(PG:7)
	at djp.b(PG:13)
	at elh.d(PG:3)
	at elh.c(PG:1)
	at ejf.A(PG:6)
	at ejf.e(PG:10)
	at azv.e(PG:8)
	at baa.a(PG:4)
	at ecz.e(PG:7)
	at ehs.e(PG:6)
	at ejh.a(Unknown Source:8)
	at dii.c(PG:7)
	at djp.b(PG:13)
	at elh.d(PG:3)
	at elh.c(PG:1)
	at ejf.A(PG:6)
	at ejf.e(PG:10)
	at azv.e(PG:8)
	at ehs.e(PG:6)
	at bcr.g(PG:3)
	at eie.e(PG:8)
	at bau.g(PG:6)
	at eie.e(PG:8)
	at ejh.a(Unknown Source:8)
	at dii.c(PG:7)
	at djp.b(PG:13)
	at elh.d(PG:3)
	at elh.c(PG:1)
	at ejf.A(PG:6)
	at eiq.an(PG:3)
	at eiq.aq(PG:2)
	at ejp.f(PG:2)
	at ejp.o(PG:9)
	at ejp.g(PG:7)
	at androidx.compose.ui.platform.AndroidComposeView.e(PG:2)
	at ekw.a(Unknown Source:1)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(PG:4)
	at android.view.View.draw(View.java:23220)
	at android.view.View.updateDisplayListIfDirty(View.java:22084)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22040)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4764)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4475)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3662)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2346)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by thestinger** [comment]
Looks like an upstream bug. Suggest clearing the app's data.
