### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by phunman1** [GrapheneOS/os-issue-tracker#2189]
```
type: crash
osVersion: google/bluejay/bluejay:13/TQ2A.230505.002/2023050500:user/release-keys
package: com.android.vending:83571920
process: com.android.vending
processUptime: 13476555 + 2022 ms
GmsCompatConfig version: 52

java.lang.UnsupportedOperationException: getPageDelegate() cannot be called after the page has been destroyed
	at vlm.B(Unknown Source:11)
	at ucj.accept(PG:49)
	at ucl.r(PG:33)
	at ucl.p(PG:3)
	at ueq.s(PG:2)
	at aepw.e(PG:4)
	at com.google.android.finsky.uicomponentsmvc.buttongroup.view.ButtonGroupView.f(Unknown Source:8)
	at aenk.onClick(PG:7)
	at android.view.View.performClick(View.java:7506)
	at com.google.android.material.button.MaterialButton.performClick(PG:2)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29357)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by thestinger** [comment]
This sounds like a regular Play Store bug rather than something GrapheneOS specific.
