### ISSUE TITLE
Permission Controller crashes when trying to edit scoped permissions

### ISSUE THREAD

**Issue by M4tZeSS** [GrapheneOS/os-issue-tracker#2229]
Setup scoped permissions on app -> back out of the screen when setup -> try to edit it again -> permission controller crashes
```
type: crash
osVersion: google/oriole/oriole:13/TQ2A.230505.002/2023052900:user/release-keys
package: com.android.permissioncontroller:330000000
process: com.android.permissioncontroller
processUptime: 8101 + 332 ms

java.lang.IllegalArgumentException: s == null
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
 at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
 at android.content.ContentResolver.call(ContentResolver.java:2474)
 at com.android.permissioncontroller.cscopes.ContactScopesFragment.callScopedContactsProvider(ContactScopesFragment.kt:279)
 at com.android.permissioncontroller.cscopes.ContactScopesFragment.callScopedContactsProvider$default(ContactScopesFragment.kt:278)
 at com.android.permissioncontroller.cscopes.ContactScopesFragment.updateCategories(ContactScopesFragment.kt:144)
 at com.android.permissioncontroller.cscopes.ContactScopesFragment.update(ContactScopesFragment.kt:117)
 at com.android.permissioncontroller.ext.BaseSettingsWithLargeHeaderFragment.onResume(BaseSettingsWithLargeHeaderFragment.kt:32)
 at androidx.fragment.app.Fragment.performResume(Fragment.java:3099)
 at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:605)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
 at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
 at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1396)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2911)
 at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2846)
 at androidx.fragment.app.Fragment.performResume(Fragment.java:3108)
 at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:605)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
 at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:771)
 at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:690)
 at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:855)
 at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:154)
 at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:123)
 at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:306)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1875)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1786)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
 at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:510)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7903)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by muhomorr** [comment]
Unable to reproduce this crash. Need more detailed instructions on how to reproduce it.

**Comment by muhomorr** [comment]
Tried adding number from a contact with no label, still unable to reproduce. Check logcat after the crash, it might contain more info.

**Comment by muhomorr** [comment]
I see. I've found the issue now.
