### ISSUE TITLE
Sandboxed google play crashed

### ISSUE THREAD

**Issue by mhmatthewhugley** [GrapheneOS/os-issue-tracker#2234]
```
type: crash
osVersion: google/redfin/redfin:13/TQ2A.230505.002/2023052900:user/release-keys
package: com.android.vending:83601320
process: com.android.vending
processUptime: 3189472 + 3822 ms
GmsCompatConfig version: 56

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchCancelPendingInputEvents()' on a null object reference
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:4697)
	at android.view.View.cancelPendingInputEvents(View.java:21429)
	at android.app.Activity.cancelInputsAndStartExitTransition(Activity.java:5593)
	at android.app.Activity.startActivityForResult(Activity.java:5572)
	at zzzi.startActivityForResult(PG:2)
	at android.app.Activity.startActivityForResult(Activity.java:5472)
	at android.app.Activity.startActivity(Activity.java:6009)
	at android.app.Activity.startActivity(Activity.java:5976)
	at qms.accept(PG:82)
	at pph.b(PG:3)
	at aoqe.run(PG:6)
	at ph.execute(PG:17)
	at aooy.h(PG:1)
	at aooy.k(PG:11)
	at aooy.aeU(Unknown Source:14)
	at aopm.m(PG:4)
	at aopf.h(PG:5)
	at aopd.run(PG:5)
	at no.c(Unknown Source:0)
	at aopr.execute(Unknown Source:0)
	at aooy.h(PG:1)
	at aooy.k(PG:11)
	at aooy.aeU(Unknown Source:14)
	at aopb.f(Unknown Source:0)
	at aopc.run(PG:13)
	at ph.execute(PG:17)
	at aoqw.execute(PG:6)
	at aooy.h(PG:1)
	at aooy.k(PG:11)
	at aooy.q(PG:3)
	at aopa.f(PG:2)
	at aopc.run(PG:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at nhx.run(PG:27)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
Looks like an upstream bug. Sandboxed Google Play compatibility layer reports these kinds of crashes too.
