### ISSUE TITLE
Error in Google Play services

### ISSUE THREAD

**Issue by Gospodininzenjer** [GrapheneOS/os-issue-tracker#2243]
```
type: crash
osVersion: google/sunfish/sunfish:13/TQ1A.221205.011/2022122000:user/release-keys
package: com.google.android.gms:231819044
process: com.google.android.gms
processUptime: 20937 + 853 ms
GmsCompatConfig version: 57

java.lang.IllegalStateException: Failed to find update_engine
	at android.os.UpdateEngine.<init>(UpdateEngine.java:252)
	at cikk.a(:com.google.android.gms@231819044@23.18.19 (190400-536743017):0)
	at cikp.<init>(:com.google.android.gms@231819044@23.18.19 (190400-536743017):2)
	at cikl.a(:com.google.android.gms@231819044@23.18.19 (190400-536743017):0)
	at cioq.b(:com.google.android.gms@231819044@23.18.19 (190400-536743017):3)
	at cijy.<init>(:com.google.android.gms@231819044@23.18.19 (190400-536743017):5)
	at cijy.c(:com.google.android.gms@231819044@23.18.19 (190400-536743017):0)
	at cihu.b(:com.google.android.gms@231819044@23.18.19 (190400-536743017):14)
	at cihw.apply(:com.google.android.gms@231819044@23.18.19 (190400-536743017):10)
	at com.google.android.gms.update.execution.InstallationEventIntentOperation.onHandleIntent(:com.google.android.gms@231819044@23.18.19 (190400-536743017):8)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@231819044@23.18.19 (190400-536743017):2)
	at zhv.onHandleIntent(:com.google.android.gms@231819044@23.18.19 (190400-536743017):4)
	at hjm.run(:com.google.android.gms@231819044@23.18.19 (190400-536743017):3)
	at hjl.run(:com.google.android.gms@231819044@23.18.19 (190400-536743017):11)
	at dfhf.run(:com.google.android.gms@231819044@23.18.19 (190400-536743017):2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by muhomorr** [comment]
How to reproduce this crash?
