### ISSUE TITLE
No recents items when going to recents screen

### ISSUE THREAD

**Issue by soupslurpr** [GrapheneOS/os-issue-tracker#2257]
On updating to the latest release, sometimes I get an issue where the regents screen has no items and can't get any new items. It gets fixed temporarily from switching profiles and back, but it comes back. This might be an upstream QPR3 issue.

I think this might be related to using split screen but I could be wrong. I was using Vanadium in split screen with itself and this was happening a lot.

**Comment by soupslurpr** [comment]
I got logs it seems the launcher crashes when this happens. 

```
type: crash
osVersion: google/panther/panther:13/TQ3A.230605.012/2023061402:user/release-keys
package: com.android.launcher3:33
process: com.android.launcher3
processUptime: 2345 + 294 ms

java.lang.NullPointerException: Attempt to read from field 'com.android.internal.util.LatencyTracker com.android.systemui.shade.NotificationPanelViewController.mLatencyTracker' on a null object reference in method 'void com.android.systemui.recents.OverviewProxyService$1$$ExternalSyntheticLambda9.accept(java.lang.Object)'
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at com.android.systemui.shared.recents.ISystemUiProxy$Stub$Proxy.onStatusBarMotionEvent(ISystemUiProxy.java:360)
	at com.android.quickstep.SystemUiProxy.onStatusBarMotionEvent(SystemUiProxy.java:287)
	at com.android.launcher3.uioverrides.touchcontrollers.StatusBarTouchController.dispatchTouchEvent(StatusBarTouchController.java:79)
	at com.android.launcher3.uioverrides.touchcontrollers.StatusBarTouchController.onControllerInterceptTouchEvent(StatusBarTouchController.java:109)
	at com.android.launcher3.views.BaseDragLayer.findControllerToHandleTouch(BaseDragLayer.java:183)
	at com.android.launcher3.views.BaseDragLayer.findActiveController(BaseDragLayer.java:193)
	at com.android.launcher3.views.BaseDragLayer.onInterceptTouchEvent(BaseDragLayer.java:163)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2653)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:303)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:225)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4307)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:2111)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15309)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6774)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6574)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6030)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6218)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6275)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9202)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9153)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9122)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9325)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9282)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9416)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:824)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by ozoromo** [comment]
Am experiencing this aswell

**Comment by pedohorse** [comment]
having the same bug too. It happens after some time.

ending session and reentering is a workaround to make it work again

**Comment by soupslurpr** [comment]
You don't have to end session. Just switching to another profile and back fixes it temporarily for me.

**Comment by octocorvus** [comment]
Need more information on this. For starters.
Are you experiencing this issue in Owner profile or secondary profiles or both?
Were multiple profiles active at the time the issue started happening?

**Comment by soupslurpr** [comment]
Happens on both, and my I did have multiple profiles active at the same time, owner and another one. I didn't test if it happens in owner if I end session on my other profile.

**Comment by pedohorse** [comment]
> You don't have to end session. Just switching to another profile and back fixes it temporarily for me.

i have owner (not in use) and another profile (active) running.  
When this bug happens in the non-owner profile - just switching to owner and back doesn't help (looks like it happens at the same time in non-owner and owner profiles). But ending non-owner session fixes it for owner profile too.

**Comment by deadcombo** [comment]
Some apps reliably cause this on my P7P.
https://github.com/T8RIN/ImageResizer

After opening this one I always get this bug.

TQ3A.230605.012.2023062300

I've experienced this for the last 4 updates.

**Comment by deadcombo** [comment]
Tested with the GrapheneOS gallery app.
It also causes this.

I can always reproduce it like this:

Take screenshot -> tap edit -> save.

It's now impossible to use the recents menu until switching user profile / restarting.

Additionally, opening an app through the launcher will cause it to load but remain transparent (not drawn) until I tap the screen (doesn't make a difference how). This is also resolved when switching to Owner and back.

**Comment by octocorvus** [comment]
this bug is reproducible on stock OS, the easiest way to reproduce it is:
1. switch to a user profile, which is at rest
2. take screenshot and click the button to edit screenshot
3. go to recents screen (it will not show any items)

**Comment by Karter315** [comment]
Same issue

![IMG_20230728_071412](https://github.com/GrapheneOS/os-issue-tracker/assets/24773231/71f834aa-b1a6-4cf2-9e89-3f4a158cbf10)

**Comment by pxlkng** [comment]
> Need more information on this. For starters. Are you experiencing this issue in Owner profile or secondary profiles or both? Were multiple profiles active at the time the issue started happening?

> this bug is reproducible on stock OS, the easiest way to reproduce it is:
> 
>     1. switch to a user profile, which is at rest
> 
>     2. take screenshot and click the button to edit screenshot
> 
>     3. go to recents screen (it will not show any items)

For me this happens on a secondary as well as owner profile and all that is required for triggering this bug is just taking a screenshot, you don't have to edit it afterwards or do anything at all. Just take a screenshot and this will break the recents screen/app launcher.

Build: TQ3A.230705.001.2023072600

**Comment by pxlkng** [comment]
> @pxlkng are you also using work profile (in owner)?

No, I'm just using plain default android user profiles. Settings->System->Multiple users->Add user

**Comment by pxlkng** [comment]
> @pxlkng when this happens in owner profile, can you capture a bug report and send it to my matrix?
> 
> instructions for capturing bug report: https://developer.android.com/studio/debug/bug-report my matrix id: `@octocorvus:grapheneos.org`

As of right now, for whatever reason, I cannot reproduce this issue on owner profile anymore. I think I may have done the testing for that part wrong, so sorry for the confusion. I will update here if I should be able to reproduce it again.

But the issue with secondary normal user profiles (not work profiles) still persists for only taking a screenshot. I just tested it again.
