### ISSUE TITLE
Google play services crash

### ISSUE THREAD

**Issue by FrenchToast202** [GrapheneOS/os-issue-tracker#2267]
```
type: crash
osVersion: google/cheetah/cheetah:13/TQ1A.230105.002/2023011000:user/release-keys
package: com.google.android.gms:232316044
process: com.google.android.gms
processUptime: 2388384 + 270 ms
GmsCompatConfig version: 59

java.lang.NullPointerException: Attempt to invoke direct method 'boolean android.os.RecoverySystem.requestLskf(java.lang.String, android.content.IntentSender)' on a null object reference
	at android.os.RecoverySystem.prepareForUnattendedUpdate(RecoverySystem.java:746)
	at cjqq.g(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
	at cjqx.v(:com.google.android.gms@232316044@23.23.16 (190400-540660214):16)
	at cjqs.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):84)
	at com.google.android.gms.update.control.ReceiverIntentOperation.onHandleIntent(:com.google.android.gms@232316044@23.23.16 (190400-540660214):7)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@232316044@23.23.16 (190400-540660214):2)
	at znb.onHandleIntent(:com.google.android.gms@232316044@23.23.16 (190400-540660214):4)
	at hli.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
	at hlh.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):11)
	at dgui.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at 
java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
> osVersion: google/cheetah/cheetah:13/TQ1A.230105.002/2023011000:user/release-keys

Please update to a current GrapheneOS release. You're on a several month old release from January.

**Comment by FrenchToast202** [comment]
![Screenshot_20230624-145328](https://github.com/GrapheneOS/os-issue-tracker/assets/137411185/27f27259-5c50-4314-8d3f-f3dae238e6b7)

**Comment by FrenchToast202** [comment]
System update has given me an error.

**Comment by thestinger** [comment]
This is an issue with your network that you need to address. Our releases.grapheneos.org server and our DNS servers work fine. Something is wrong with your network. Which VPN service are you using? It's likely blocking updates...

**Comment by FrenchToast202** [comment]
I use Express VPN and MullVad DNS

**Comment by FrenchToast202** [comment]
This issue is still present even when I turn off the VPN and DNS.

**Comment by thestinger** [comment]
This is an issue with your network setup that you'll need to resolve. Reset network settings as a whole. Please get further support with this via https://discuss.grapheneos.org/ and/or our main Matrix chat room. You need to update your OS and the crash you encountered will be gone.
