### ISSUE TITLE
Error in Google Play Services 

### ISSUE THREAD

**Issue by FrenchToast202** [GrapheneOS/os-issue-tracker#2277]
```
type: crash
osVersion: google/cheetah/cheetah:13/TQ3A.230605.012/2023062300:user/release-keys
package: com.google.android.gms:232316044
process: com.google.android.gms
processUptime: 710205 + 247 ms
GmsCompatConfig version: 60

java.lang.NullPointerException: Attempt to invoke direct method 'boolean android.os.RecoverySystem.requestLskf(java.lang.String, android.content.IntentSender)' on a null object reference
	at android.os.RecoverySystem.prepareForUnattendedUpdate(RecoverySystem.java:746)
	at cjqq.g(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
	at cjqx.v(:com.google.android.gms@232316044@23.23.16 (190400-540660214):16)
	at cjqs.a(:com.google.android.gms@232316044@23.23.16 (190400-540660214):84)
	at com.google.android.gms.update.control.ReceiverIntentOperation.onHandleIntent(:com.google.android.gms@232316044@23.23.16 (190400-540660214):7)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@232316044@23.23.16 (190400-540660214):2)
	at znb.onHandleIntent(:com.google.android.gms@232316044@23.23.16 (190400-540660214):4)
	at hli.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):3)
	at hlh.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):11)
	at dgui.run(:com.google.android.gms@232316044@23.23.16 (190400-540660214):2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by muhomorr** [comment]
Is this a recurring crash?
