### ISSUE TITLE
App chrash relatet to libhermes.so

### ISSUE THREAD

**Issue by CuriousApe2020** [GrapheneOS/os-issue-tracker#2312]
Everytime I try to start the App "Fressnapf Tracker" (an App for use with an GPS Dog Tracker) it crashes with the below shown error message. I think it might be related to: [#903
](https://github.com/GrapheneOS/os-issue-tracker/issues/903)

My device: Google Pixel 6a running GrapheneOS

type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230705.001/2023070500:user/release-keys
package: com.iotventure.fressnapf:156
process: com.iotventure.fressnapf
processUptime: 95 + 234 ms

java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~082vb7voCiaWRJUe7PEVvA==/com.iotventure.fressnapf-wmdVK1XJz8qG1--JzzPMzw==/lib/arm64 flags = 0]
	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = ()]
	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
	Native lib dir: /data/app/~~082vb7voCiaWRJUe7PEVvA==/com.iotventure.fressnapf-wmdVK1XJz8qG1--JzzPMzw==/lib/arm64
 result: 0
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:369)
	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:316)
	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:94)
	at expo.modules.ReactNativeHostWrapperBase.createReactInstanceManager(ReactNativeHostWrapperBase.kt:32)
	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
	at com.iotventure.fressnapf.MainApplication.onCreate(MainApplication.java:67)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1282)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6824)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

**Comment by thestinger** [comment]
Appears to be a bug in the app rather than a GrapheneOS issue. The app isn't compatible with modern Android due to a bug that wasn't breaking it until a newer release. You can find many instances of the same error from this react native related bug.

**Comment by flawedworld** [comment]
This app needs to update their React dependencies. Only the developers can do that.

**Comment by muhomorr** [comment]
I've installed this app from Play Store and it launches fine.
This stack trace suggests that the app wasn't installed properly: it looks like it's missing a native library that is installed as a separate APK split (`split_config.arm64_v8a.apk`).

How did you install this app?

**Comment by CuriousApe2020** [comment]
@muhomorr Thank you for the Info I installed the App via the PlayStore and everything works. Seems like the Problem was with AuroraStore. Sorry for opening this false Issue.

**Comment by thestinger** [comment]
@CuriousApe2020 Native installer mode in Aurora Store is broken. You need to use the Session installer mode. It should always do that itself instead of providing a choice to use the legacy mode.
