### ISSUE TITLE
Google Services Framework Keeps Stopping

### ISSUE THREAD

**Issue by ghexplorerr** [GrapheneOS/os-issue-tracker#2321]
On a fresh install of GrapheneOS on a used Pixel 6a, Google Services Framework keeps crashing. 

The Android version before the install was April 2022. The installation instructions suggested that normally I would have needed to update to at least June 2022 in order to unlock the bootloader, but in this case the bootloader was already unlocked, so I installed GrapheneOS.

Initial setup went fine, but I cannot use Google Play because I get the notification "Google Services Framework keeps stopping."

Here's the crash report:

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230705.001/2023071100:user/release-keys
package: com.google.android.gsf:33
process: com.google.process.gservices
processUptime: 137 + 545 ms
GmsCompatConfig version: 62

java.lang.RuntimeException: Unable to get provider com.google.android.gsf.gservices.GservicesProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gsf.gservices.GservicesProvider" on path: DexPathList[[zip file "/data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/base.apk"],nativeLibraryDirectories=[/data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/lib/arm64, /data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.ActivityThread.installProvider(ActivityThread.java:7536)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7042)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6813)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gsf.gservices.GservicesProvider" on path: DexPathList[[zip file "/data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/base.apk"],nativeLibraryDirectories=[/data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/lib/arm64, /data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7520)
	... 13 more
	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/base.apk because: Failure to verify dex file '/data/app/~~l4BQNTczHSC_agRAznndiw==/com.google.android.gsf-oXwDD2OYqbytch2QMuur0w==/base.apk': Bad checksum (13c4ff75, expected df45ff77)
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:371)
		at dalvik.system.DexFile.<init>(DexFile.java:113)
		at dalvik.system.DexFile.<init>(DexFile.java:86)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
		at dalvik.system.DexPathList.<init>(DexPathList.java:166)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:130)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:146)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:93)
		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:134)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:126)
		at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:61)
		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1034)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:1126)
		at android.app.LoadedApk.getResources(LoadedApk.java:1374)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3128)
		at android.app.ContextImpl.createAppContext(ContextImpl.java:3120)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6714)
		... 11 more

```

**Comment by thestinger** [comment]
I don't think you installed it correctly. Remove it and reinstall it with our instructions.

**Comment by ghexplorerr** [comment]
Removing and reinstalling did work. I'm not sure why; I'm not sure I did anything differently the second time.

I uninstalled Google Services Framework and Google Play Store, and I also uninstalled the updates to GmsCompatConfig.

Then I reinstalled Google Play Store and let GrapheneOS take care of the dependencies automatically.

It seems to be working now. Thanks!
