### ISSUE TITLE
Unable to change output device when using bluetooth

### ISSUE THREAD

**Issue by jkos95** [GrapheneOS/os-issue-tracker#2359]
If I make a call while my phone is connected to a bluetooth device (speaker, earphones, etc), I am unable to change the output device ("sound" button)  while on the call. If I try to tap the sound button and switch to a bluetooth device or from a bluetooth device back to my phone speaker, the phone app will crash and the output will not change. 

I am able to change music output devices with no problem. This only occurs while using the phone app. Will update to add the error received.

**Comment by jkos95** [comment]
```
type: crash
osVersion: google/oriole/oriole:13/TQ3A.230705.001/2023072600:user/release-keys
package: com.android.dialer:2900000
process: com.android.dialer
processUptime: 1865 + 292 ms

java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@61cf3c09: AdapterService getRemoteName
	at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:486)
	at com.android.bluetooth.Utils.checkConnectPermissionForDataDelivery(Utils.java:518)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getRemoteName(AdapterService.java:2599)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getRemoteName(AdapterService.java:2590)
	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:761)
	at android.os.Binder.execTransactInternal(Binder.java:1314)
	at android.os.Binder.execTransact(Binder.java:1268)

```

**Comment by empratyush** [comment]
unable to reproduce this on pixel 4a.
