### ISSUE TITLE
Matter Device Commissioning Fails

### ISSUE THREAD

**Issue by ImranR98** [GrapheneOS/os-issue-tracker#2383]
On a Pixel 7 with GrapheneOS build `TQ3A.230805.001.2023080800` and the latest versions of sandboxed Play Services installed, I am not able to commission a Matter IoT device - neither with the Google Home app nor with Home Assistant. I get this "No Wi-Fi connection" error: 
![matter_bug](https://github.com/GrapheneOS/os-issue-tracker/assets/30463115/7e30b65f-85a6-4a7d-8e32-842bd914b694)

I confirmed that all 3 Play services apps - 'Google Play services', 'Google Services Framework', and 'Google Play Store' - have the network permission (along with the Nearby Devices permission where applicable). Same for the Google Home and Home Assistant apps.

Clicking "Try again" doesn't do anything, while clicking "Cancel" causes a crash with this error:
```
type: crash
osVersion: google/panther/panther:13/TQ3A.230805.001/2023080800:user/release-keys
package: com.google.android.gms:233013044
process: com.google.android.gms.ui
processUptime: 632486 + 282 ms
installer: com.android.vending
GmsCompatConfig version: 66

java.lang.IllegalArgumentException: No action determined for button common_exit in container commissioning_error_not_connected_to_wifi
	at m.gmb.a(:com.google.android.gms.optional_home@233013065@23.30.13 (100400-0):376)
	at m.god.a(:com.google.android.gms.optional_home@233013065@23.30.13 (100400-0):9)
	at m.goc.onClick(:com.google.android.gms.optional_home@233013065@23.30.13 (100400-0):14)
	at android.view.View.performClick(View.java:7542)
	at com.google.android.material.button.MaterialButton.performClick(:com.google.android.gms.optional_home@233013065@23.30.13 (100400-0):10)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

I have confirmed that commissioning the same device does work on a Pixel 3XL with the latest Google build of "stock" Android.

I'm not sure if the Matter-related code will eventually make its way into AOSP and make this issue irrelevant; have posted a question here: https://issuetracker.google.com/issues/295677330

**Comment by muhomorr** [comment]
Don't have any Matter devices to test. Can you post a full logcat?

Also, try granting Location permission to Play services, Wi-Fi scan results are filtered without it.

**Comment by ImranR98** [comment]
[logcat.log](https://github.com/GrapheneOS/os-issue-tracker/files/12413293/logcat.log)

Granting location to Play Services doesn't seem to change anything. Here's the logcat (tried to remove older irrelevant stuff).

**Comment by muhomorr** [comment]
As part of Matter device setup, Play services tries to get credentials of the current Wi-Fi network by calling `WifiManager.getPrivilegedConfiguredNetworks()`, which requires the privileged `READ_WIFI_CREDENTIAL` permission.

When GmsCompat is active, `getPrivilegedConfiguredNetworks()` returns an empty list, which is not enough in this particular case. There's no unprivileged variant of this API. A list with placeholder values can be returned instead, but it's unlikely to help.

**Comment by ImranR98** [comment]
Okay, that makes sense. Is adding an unprivileged version of that API on the table? Or some workaround like redirecting unprivileged calls to a manual-input SSID/password prompt?

**Comment by muhomorr** [comment]
Implementing support for this part of Play services is currently not planned.

**Comment by meramsey** [comment]
if someone were to donate money for devs to buy Matter devices would that be helpful @thestinger ?

**Comment by thestinger** [comment]
The functionality doesn't work because it's implemented as requiring a privileged permission, not because of anything that was missed. We don't plan to make a special case for this feature. It could be left open for someone to eventually address by somehow asking the user for Wi-Fi credentials, but we aren't going to be working on it with our own resources. You would need to provide devices to test and find a developer to work on it and maintain it, who would likely need to be paid.

**Comment by nettnikl** [comment]
Hi, as Matter is gaining more track - maybe we can revisit this issue, and provide a workable workaround?

> When GmsCompat is active, `getPrivilegedConfiguredNetworks()` returns an empty list, which is not enough in this particular case. There's no unprivileged variant of this API. A list with placeholder values can be returned instead, but it's unlikely to help.

This could help, couldnt it? We could set up a temporary wifi network with a one time password generated here for example? And/or
> somehow asking the user for Wi-Fi credentials
?

**Comment by KUKHUA** [comment]
It should ask the user for the password.

**Comment by nettnikl** [comment]
To get this discussion rolling again:
- Is there a consensus in deciding that we need to include a solution to allow the use of matter?
- Is the current state of the art of google home, sonos & co (asking the user for a wifi ssid and pw) a viable way with regards to security and privacy?
- What do we need to differently or additionally to accomodate for the different OS, infra and privacy+security thread model?

(All of the above written in the generous assumption we have unlimited developing and maintaining power, that is a second step in thia discussion from my pov)

**Comment by rockhoppr** [comment]
The message about 'no wifi connection' also appears when trying to commission a matter-over-thread device. Synchronising credentials of the thread network inside home-assistant companion APP seems to work. Next step, I assume, should be transmitting these credentials via bluetooth to the IoT device.

**Comment by RAYs3T** [comment]
Same issue when pairing "Matter over Thread" devices. But why would it need wifi credentials for that? In the case of Thread the credentials are generated seperatly and do not involve wifi?

(tried this from within the homeassistant app)

**Comment by kenshin33** [comment]
@rockhoppr it seems that it doesn't at least for me. Synced the credentials (under the troubleshooting sub menu in the app) still the process stops right after entering the paring code or scanning the QR Code.
As @RAYs3T something is not right here and I think it's on whatever library the home assistant  app uses. for matter over wifi perfectly understandable, but matter over thread I don't see why it's trying to access the wifi list  or whatever. 
The 2 processes should be separate of simply warn that there is no wifi list and ignore.

**Comment by snotrauk** [comment]
Anyone got any work arounds for this?

**Comment by TimB87** [comment]
> Anyone got any work arounds for this?

Not really very comfortable but I was able to do use `chip-tool` from [connectedhomeip](https://github.com/project-chip/connectedhomeip) repository.
I have my own [thread border router](https://hub.docker.com/r/openthread/otbr) connected to a SLZB-06M in Thread mode, and my own [matter server](https://github.com/matter-js/matterjs-server). I am not sure if this would work with alexa or google home or any other thread router that may exist in your home already.
I use home assistant but I guess other ecosystems will offer you the same actions where that matters.

Rough steps documented from my notebook:

## get `chip-tool`
```
git clone --depth=1 https://github.com/project-chip/connectedhomeip.git
cd connectedhomeip
./scripts/checkout_submodules.py --shallow --platform linux
source scripts/activate.sh
./scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool
```
This will take a longer time so the usual "go get a coffee" statement applies.

## Pair device

Unfortunately, we need to first pair the device to the thread network, then we need to connect it to the matter service.
Each step requires some information.

### Get your thread dataset id

You need to know the dataset id of your thread network.
Inside the otbr container execute:
```
docker exec -it otbr ot-ctl dataset active
```

Copy the long output to your password vault or whatever. Let's assume it's `mn9z9s3m195pndzkovnuy7dst8tlbrlzc5n4isyhmu4tbvmfmw1u8kxhb5scfi7k8vtoz32tbgdrj9is49t1xlz9gi3hmgjvczqqmlhvobrdw6y5zq9xalb3uvcy2tvaghpfy9et4ibf2j84ucozhblmer21xm7mjviltk1jve5qhzd7j4ifg2lkgk06z5o5g1pancc0muvs909ibya7awmxeogw`.

### Get your devices QR code value

Use a qr scanner to scan the value, let's assume it's `MT:DGH38YXC23G1J274190`

### pair to thread network with chip-tool

> ⚠️ Please note that this step requires bluetooth (and/or wifi?) I only tested IKEA devices so far, all they need is bluetooth 😁 

Each device you pair you will need to give an unique node id as a decimal or hex value. Let's assume its `1234`.

Execute the following commands:
```
./chip-tool pairing code-thread 1234 hex:mn9z9s3m195pndzkovnuy7dst8tlbrlzc5n4isyhmu4tbvmfmw1u8kxhb5scfi7k8vtoz32tbgdrj9is49t1xlz9gi3hmgjvczqqmlhvobrdw6y5zq9xalb3uvcy2tvaghpfy9et4ibf2j84ucozhblmer21xm7mjviltk1jve5qhzd7j4ifg2lkgk06z5o5g1pancc0muvs909ibya7awmxeogw MT:DGH38YXC23G1J274190 --paa-trust-store-path ./credentials/development/paa-root-certs/
```

The syntax is `chip-tool pairing code-thread <node-id> <operationalDataset> <payload>`.

### Pair to matter

From within home assistants matter options you can pair a device by code (Settings -> Matter -> Options -> Add manually).
To generate the code needed you can use chip-tool again:
```
./chip-tool pairing open-commissioning-window 1234 1 300 10000 3840
```

The node-id is the first option in this subcommand, so you will need to change that to whatever you really used.

In the commands output you will see a code that looks very similar to the QR code value. Copy paste that into the code dialog in home assistant.
Done

**Comment by snotrauk** [comment]
That's brilliant thank you!!!

**Comment by jextrevor** [comment]
Thank you @TimB87 !! Had problems building on Arch Linux with the newest versions of GCC and some of the other packages, but was able to get it working using Ubuntu 24.04 + VirtualBox + a cheap USB bluetooth adapter.

**Comment by umrath** [comment]
This is very unfortunate and quite a bummer for me.
The reliance of Home Assistant on Google is quite worrying and contradicts the whole idea of Home Assistant.

**Comment by bbigras** [comment]
@umrath It's not ideal, but I think we can onboard a matter device with an esphome Bluetooth proxy now.

https://github.com/home-assistant/core/pull/171384
https://community.home-assistant.io/t/bluetooth-proxy-to-connect-to-matterjs-server-ble-endpoint-configuration-problems/1011942
https://www.home-assistant.io/changelogs/core-2026.6/

EDIT: We can. In Home-assistant's settings -> apps -> Matter Server -> Configuration -> Enable BLE proxy. Then go back to the Matter Server's "Info" tab and click "Open Web UI", provision the device there.

To get the "thead dataset" hex number, In Home-assistant's settings -> Devices & services -> Thread -> click the "configure" gear icon for your Thread service ->click the "Thread network information" (i) icon -> the number is under "Active dataset TLVs"
