### ISSUE TITLE
Google play crash

### ISSUE THREAD

**Issue by mhmatthewhugley** [GrapheneOS/os-issue-tracker#2413]
```
type: crash
osVersion: google/redfin/redfin:13/TQ3A.230805.001/2023080800:user/release-keys
package: com.android.vending:83721820
process: com.android.vending
processUptime: 467859 + 502 ms
installer: com.android.vending
GmsCompatConfig version: 71

java.lang.NullPointerException: Attempt to read from field 'ggu android.support.v7.widget.RecyclerView.W' on a null object reference in method 'void lz.d(android.view.View, int, boolean)'
	at lz.d(PG:16)
	at lz.adS(PG:2)
	at lz.adR(PG:2)
	at shq.c(PG:39)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.at(PG:9)
	at android.support.v7.widget.LinearLayoutManagerWithProxies.C(PG:13)
	at android.support.v7.widget.LinearLayoutManager.M(PG:45)
	at android.support.v7.widget.LinearLayoutManager.o(PG:743)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.o(PG:110)
	at android.support.v7.widget.RecyclerView.aO(PG:65)
	at android.support.v7.widget.RecyclerView.F(PG:74)
	at android.support.v7.widget.RecyclerView.onLayout(PG:6)
	at com.google.android.finsky.recyclerview.PlayRecyclerView.onLayout(PG:9)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at hkr.onLayout(PG:256)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at alal.ahc(PG:140)
	at alan.j(PG:1)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.j(PG:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:41)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at com.google.android.finsky.drawer.FinskyDrawerLayout.onLayout(PG:48)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
	at android.view.View.layout(View.java:23798)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4114)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3455)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9293)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by flawedworld** [comment]
This is a bug in Google Play, not our bug.
