### ISSUE TITLE
Sandbox crashed

### ISSUE THREAD

**Issue by Tareq4322** [GrapheneOS/os-issue-tracker#2452]
```
type: crash
osVersion: Redmi/rosemary/rosemary:12/SP1A.210812.016/V13.0.5.0.SFFTWXM:user/release-keys
package: com.google.android.googlequicksearchbox:301267730
process: com.google.android.googlequicksearchbox:search
processUptime: 8297 + 237 ms
installer: com.android.vending
GmsCompatConfig version: 74

java.util.concurrent.CancellationException
	at jlbs.c(PG:1)
	at jlbs.get(PG:1)
	at hbno.b(PG:2)
	at dvsm$c.j(PG:22)
	at dvsm$c.h(PG:7)
	at dvsm$c.g(PG:10)
	at dvsm$c.b(PG:3)
	at hovb.h(PG:23)
	at hovb.a(PG:2)
	at hous.run(PG:20)
	at hoga.run(PG:6)
	at hqfa.run(PG:3)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at ihrv.a(PG:1)
	at ihqr.run(PG:4)
	at ihrw.run(PG:1)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: jkqe: jkqv was cancelled; job=jkqv{Cancelled}@5021e26

```

**Comment by thestinger** [comment]
This issue tracker is only for GrapheneOS.

**Comment by thestinger** [comment]
GrapheneOS is based on Android 13 and will be based on Android 14 once it comes out. There's no Android 12 GrapheneOS so not only is that a different OS with an unofficial port of the compatibility layer but it's also an ancient version of it without many improvements that were implemented. It's probably an app bug anyway.
