### ISSUE TITLE
Sandboxed Google Play crashed

### ISSUE THREAD

**Issue by someonewhowhisestobeanonymous** [GrapheneOS/os-issue-tracker#2460]
```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230901.001/2023091800:user/release-keys
package: com.google.android.gms:233515044
process: com.google.android.gms
processUptime: 239587 + 310 ms
installer: com.android.vending
GmsCompatConfig version: 75

java.lang.SecurityException: Attempt to change component state; pid=3101, uid=10128, component=ComponentInfo{com.google.android.gsf/com.google.android.gsf.settings.common.AutomotiveWebViewActivity}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:6023)
	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:3056)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.setComponentEnabledSetting(GmcPackageManager.java:530)
	at agzn.k(:com.google.android.gms@233515044@23.35.15 (190400-565551795):12)
	at agzn.j(:com.google.android.gms@233515044@23.35.15 (190400-565551795):2)
	at agzo.F(:com.google.android.gms@233515044@23.35.15 (190400-565551795):3)
	at com.google.android.gms.core.tos.TosInitIntentOperation.b(:com.google.android.gms@233515044@23.35.15 (190400-565551795):50)
	at adwa.onHandleIntent(:com.google.android.gms@233515044@23.35.15 (190400-565551795):131)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@233515044@23.35.15 (190400-565551795):2)
	at aeak.onHandleIntent(:com.google.android.gms@233515044@23.35.15 (190400-565551795):10)
	at lnb.run(:com.google.android.gms@233515044@23.35.15 (190400-565551795):70)
	at lna.run(:com.google.android.gms@233515044@23.35.15 (190400-565551795):152)
	at dpvy.run(:com.google.android.gms@233515044@23.35.15 (190400-565551795):13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
Were you trying to use Android Auto? It's not supported on GrapheneOS.

**Comment by someonewhowhisestobeanonymous** [comment]
No I wasn't. Every day or throughout the day I get this notification.
![Screenshot_20231002-075825](https://github.com/GrapheneOS/os-issue-tracker/assets/41984122/c8d0be85-19be-4291-9b92-037b498f3eb6)

**Comment by someonewhowhisestobeanonymous** [comment]
No. I don't know how that happened. It is my first time I post something on GitHub.

**Comment by someonewhowhisestobeanonymous** [comment]
Here it is, again:
![Screenshot_20231002-105612](https://github.com/GrapheneOS/os-issue-tracker/assets/41984122/fbc579ec-beff-4101-843a-6ab88cb19571)


```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230901.001/2023091800:user/release-keys
package: com.google.android.gms:233614044
process: com.google.android.gms
processUptime: 36102 + 303 ms
installer: com.android.vending
GmsCompatConfig version: 76

java.lang.SecurityException: Attempt to change component state; pid=3115, uid=10128, component=ComponentInfo{com.google.android.gsf/com.google.android.gsf.settings.common.AutomotiveWebViewActivity}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:6023)
	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:3056)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.setComponentEnabledSetting(GmcPackageManager.java:530)
	at ahrn.k(:com.google.android.gms@233614044@23.36.14 (190400-567131450):12)
	at ahrn.j(:com.google.android.gms@233614044@23.36.14 (190400-567131450):2)
	at ahro.F(:com.google.android.gms@233614044@23.36.14 (190400-567131450):3)
	at com.google.android.gms.core.tos.TosInitIntentOperation.b(:com.google.android.gms@233614044@23.36.14 (190400-567131450):50)
	at aenq.onHandleIntent(:com.google.android.gms@233614044@23.36.14 (190400-567131450):131)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@233614044@23.36.14 (190400-567131450):2)
	at aesa.onHandleIntent(:com.google.android.gms@233614044@23.36.14 (190400-567131450):10)
	at mdh.run(:com.google.android.gms@233614044@23.36.14 (190400-567131450):70)
	at mdg.run(:com.google.android.gms@233614044@23.36.14 (190400-567131450):152)
	at drmo.run(:com.google.android.gms@233614044@23.36.14 (190400-567131450):13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by muhomorr** [comment]
It looks like you've disabled the "Google Services Framework" app.

Check whether it's enabled.
