### ISSUE TITLE
Long Screenshot edit button broken (scrolling screenshot)

### ISSUE THREAD

**Issue by n3rdcub** [GrapheneOS/os-issue-tracker#2470]
So if you press power and vol- at same time you get an option to "capture more" in certain apps....
However the pencil edit button does not function correctly on the selected portions of the image. 

Please see image, the red circle indicates the normal edit button one thinks to press when ready to edit with cropping or drawing. It does nothing when used on a selected portion of screen. 

The green circles indicate buttons that DO work. The left is the usual save. The right is a share menu with another edit button. THAT ONE works as intended. 

Never tested on stock but pretty sure this isn't intended use function. ![Screenshot_20231003-162854_1.png](https://github.com/GrapheneOS/os-issue-tracker/assets/71808897/05629bef-1a1d-4fa9-91d0-a7af0c99d5d3)

**Comment by n3rdcub** [comment]
Nope it's still insurance and set as default, I have other apps I use at times but GoS AOSP gallery still enabled and default

**Comment by n3rdcub** [comment]
> Thank you for elaborating. I tested this and pressing that button with Image Toolbox brings that one up, if I disable Image Toolbox and enable AOSP Gallery, it brings up the gallery's editor instead.

I get Android system Crashing. Toolbox is installed with default gallery disabled. Even with enabled systems  crashes anyway

```
type: crash
osVersion: google/panther/panther:13/TQ3A.230901.001/2023100300:user/release-keys
package: android:33
process: system:ui
processUptime: 177 + 69 ms

java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:706)
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:139)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1604)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.widget.ImageView.onDraw(ImageView.java:1446)
	at android.view.View.draw(View.java:23266)
	at android.view.View.draw(View.java:23139)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.ViewOverlay$OverlayViewGroup.dispatchDraw(ViewOverlay.java:255)
	at android.view.View.draw(View.java:23275)
	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:4905)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4813)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3683)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9293)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

**Comment by n3rdcub** [comment]
Nope it's still installed and set as default, I have other apps I use at times but GoS AOSP gallery still enabled and default

**Comment by n3rdcub** [comment]
To reiterate, the only way to take a scrolling screenshot is via Vol- and Power. Using the screenshot button from the recent menu we'll take a screenshot and we'll hide the status bar, but it will not allow for scrolling screenshots or long screenshots. 

By holding volume down and power, it is there that you are able to take a long screenshot It will say something to the effect of capture more and allow you to set your boundaries. 

Once your boundaries are set in the very bottom right you will see a pencil icon. THIS IS BROKEN. WHY IM NOT SURE BUT STAY WITH ME IMMA BLOW YOUR MIND

So in the top right you'll see a share menu or button rather, when you click it you'll be met with a share sheet, but if you pay attention to the apps given it's a very hodgepodge mismatch of apps that don't make any sense of why you would share it to that. You're missing all of your gallery apps, maybe getting 20 or 30%.
At the very top of that share sheet you'll see an edit button, PRESS THAT. That is literally doing the same function as the pencil AND shows you every gallery picture editing app you have installed.

I don't know how this has gone unnoticed for so long but I feel like I deserve a cookie... can I have snickerdoodle please? 😁

Confirmation not required but welcomed to concur my findings
