### ISSUE TITLE
l10n format issue with location provider

### ISSUE THREAD

**Issue by ivan-avalos** [GrapheneOS/os-issue-tracker#2475]
Hey, everyone! I have a banking application installed, that requires my GPS location by law. It had always worked flawlessly with GrapheneOS, until yesterday, when I decided to switch my phone to French to learn the language. Soon thereafter, my banking app couldn't get past the GPS retrieval popup without crashing.

I was able to get a backtrace, and I found something interesting: the system GPS location provider appears to be handing the app a floating point longitude (partially concealed in the backtrace) formatted as a string, with a comma instead of a period, which I suppose is for localization; but the banking app, which uses the default Java parser, doesn't know how to handle it.

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230901.001/2023100300:user/release-keys
package: com.bancomer.mbanking:118202
process: com.bancomer.mbanking
processUptime: 47577 + 231 ms
installer: com.aurora.store

java.lang.NumberFormatException: For input string: "-XXX,8365536272895800"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:543)
	at com.bbva.bgm.accountsui.util.GeolocationConsentUtil.formatLocationValue(GeolocationConsentUtil.java:171)
	at com.bbva.bgm.accountsui.activity.DashboardActivity.sendLocation(DashboardActivity.java:4479)
	at com.bbva.bgm.accountsui.activity.DashboardActivity$2.onLocationUpdated(DashboardActivity.java:4444)
	at com.bbva.bgm.accountsui.util.GeolocationConsentUtil$1.onRequestedLocationAvailable(GeolocationConsentUtil.java:76)
	at com.bancomer.mbanking.mobileservices.gms.LocationHelperGms.onLocationRetrieved(LocationHelperGms.java:90)
	at com.bancomer.mbanking.mobileservices.gms.LocationHelperGms.lambda$requestLastKnownLocation$0$LocationHelperGms(LocationHelperGms.java:75)
	at com.bancomer.mbanking.mobileservices.gms.-$$Lambda$LocationHelperGms$qXb9UpDGLI_KRYDp8LadKTei1VQ.onComplete(Unknown Source:2)
	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

When I switch back to English, it works again.

**Comment by thestinger** [comment]
The app is likely formatting it this way, not the OS. This looks like an app bug.
