### ISSUE TITLE
Launcher stopped working after recent update.

### ISSUE THREAD

**Issue by SleepzCat** [GrapheneOS/os-issue-tracker#2480]
Today after updating my phone, that launcher has stopped working and I get this error.
 ```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023100900:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 225 + 262 ms

java.lang.IllegalArgumentException: shortLabel cannot be empty
	at com.android.internal.util.Preconditions.checkStringNotEmpty(Preconditions.java:109)
	at android.content.pm.ShortcutInfo$Builder.setShortLabel(ShortcutInfo.java:1237)
	at com.android.launcher3.provider.LauncherDbUtils.migrateLegacyShortcuts(LauncherDbUtils.java:131)
	at com.android.launcher3.model.DatabaseHelper.onUpgrade(DatabaseHelper.java:273)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:423)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:347)
	at com.android.launcher3.model.ModelDbController.createDatabaseHelper(ModelDbController.java:117)
	at com.android.launcher3.model.ModelDbController.createDbIfNotExists(ModelDbController.java:99)
	at com.android.launcher3.model.ModelDbController.migrateGridIfNeeded(ModelDbController.java:290)
	at com.android.launcher3.model.LoaderTask.loadWorkspaceImpl(LoaderTask.java:371)
	at com.android.launcher3.model.LoaderTask.loadWorkspace(LoaderTask.java:344)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:210)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

This update has made it impossible for me to use my phone currently. Why are we forced to install these updates like its windows?

**Comment by thestinger** [comment]
> Today after updating my phone, that launcher has stopped working and I get this error.

Looks like corrupt data was stored, perhaps caused by a bug in a previous release. You can use the notification drawer to access Settings and clear app data for the launcher.

> Why are we forced to install these updates like its windows?

You aren't forced to install updates. If you don't install updates you're not going to have privacy/security patches though...

**Comment by SleepzCat** [comment]
> You aren't forced to install updates. If you don't install updates you're not going to have privacy/security patches though...
Well I don't authorize them, they just show up in my notification bar and state that they're downloading. I don't have the choice to say no, I only have the option to not hit reboot to apply it after its already installed onto my phone. I shouldn't have to be forced to download an update the exact moment its available, and then only get given the option to not reboot.

**Comment by SleepzCat** [comment]
> Looks like corrupt data was stored, perhaps caused by a bug in a previous release. You can use the notification drawer to access Settings and clear app data for the launcher.

Okay, I fixed it by clearing the app data but now as a consequence my entire home screens have been reset, when I had spent quite a lot of time a few months ago arranging it in a way that would look nice and let me find everything easily. I guess I'm going to have to spend more hours trying to set it all up again. Real kick in the fucking nuts from an update that downloads itself and forces you to avoid rebooting your phone if you don't want it to apply. Good stuff, cheers.

**Comment by thestinger** [comment]
> Well I don't authorize them, they just show up in my notification bar and state that they're downloading. I don't have the choice to say no, I only have the option to not hit reboot to apply it after its already installed onto my phone. I shouldn't have to be forced to download an update the exact moment its available, and then only get given the option to not reboot.

The default is mostly automatic updates for security reasons.

**Comment by thestinger** [comment]
> Okay, I fixed it by clearing the app data but now as a consequence my entire home screens have been reset, when I had spent quite a lot of time a few months ago arranging it in a way that would look nice and let me find everything easily. I guess I'm going to have to spend more hours trying to set it all up again. Real kick in the fucking nuts from an update that downloads itself and forces you to avoid rebooting your phone if you don't want it to apply. Good stuff, cheers.

There was probably another way to deal with it but it didn't sound like you were going to be patient and help with debugging it.
