### ISSUE TITLE
Sandboxed Google Services Keep crashing in Grapheneos Alpha Channel with Android 14

### ISSUE THREAD

**Issue by icarious0** [GrapheneOS/os-issue-tracker#2483]
```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231005.007/2023100900:user/release-keys
package: com.google.android.gms:233717044
process: com.google.android.gms.persistent
processUptime: 24520 + 422 ms
installer: com.android.vending
GmsCompatConfig version: 77

java.lang.NullPointerException: packageName can't be null
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.requestCellInfoUpdate(ITelephony.java:9641)
	at android.telephony.TelephonyManager.requestCellInfoUpdate(TelephonyManager.java:6803)
	at android.telephony.TelephonyManager.requestCellInfoUpdate(TelephonyManager.java:6865)
	at dmtl.handleMessage(:com.google.android.gms@233717044@23.37.17 (190400-570218080):596)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at bdvb.lJ(:com.google.android.gms@233717044@23.37.17 (190400-570218080):1)
	at bdvb.dispatchMessage(:com.google.android.gms@233717044@23.37.17 (190400-570218080):143)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	Suppressed: dshg: 
		at tk_trace.location_base-GoogleLocationChimeraService_onCreate(Unknown Source:0)

```

**Comment by qoijjj** [comment]
I was seeing this and it seems to have gone away after updating Google Services Framework in the GOS Apps app.

**Comment by thestinger** [comment]
That makes sense. Please make sure GSF is updated to 14.

**Comment by icarious0** [comment]
> I was seeing this and it seems to have gone away after updating Google Services Framework in the GOS Apps app.

Oh really? I didn't do that. I hope they have updated the Google Services Framework in the GOS Apps app in the upcoming OS level updates. But thanks for mentioning it.

**Comment by thestinger** [comment]
@icarious0 Our app repository client has the GSF update and delivers it after people update to Android 14. Check if you have the update pending.

**Comment by icarious0** [comment]
```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231005.007/2023100900:user/release-keys
package: com.google.android.gms:233717044
process: com.google.android.gms.persistent
processUptime: 6287 + 939 ms
installer: com.android.vending
GmsCompatConfig version: 77

java.lang.NullPointerException: packageName can't be null
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.requestCellInfoUpdate(ITelephony.java:9641)
	at android.telephony.TelephonyManager.requestCellInfoUpdate(TelephonyManager.java:6803)
	at android.telephony.TelephonyManager.requestCellInfoUpdate(TelephonyManager.java:6865)
	at dmtl.handleMessage(:com.google.android.gms@233717044@23.37.17 (190400-570218080):596)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at bdvb.lJ(:com.google.android.gms@233717044@23.37.17 (190400-570218080):1)
	at bdvb.dispatchMessage(:com.google.android.gms@233717044@23.37.17 (190400-570218080):143)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	Suppressed: dshg: 
		at tk_trace.location_base-GoogleLocationChimeraService_onCreate(Unknown Source:0)

```

Ya no. I did update my gsf to the latest and still have the proprietary google dependent apps crashing on this

**Comment by thestinger** [comment]
Try a reboot. Maybe it got screwed up from having 13 before.

**Comment by icarious0** [comment]
> Try a reboot. Maybe it got screwed up from having 13 before.

I did that. It still persists. I guess, the only thing that remains cause of the modern weirdness of software development is to delete the profile and start fresh. I will do that tomorrow and post my result here. But thanks for the prompt answers though.

**Comment by thestinger** [comment]
@icarious0 Are you using the location re-routing feature or Play services location? Do you have re-routing disabled and the Play services network location accuracy option enabled?

**Comment by icarious0** [comment]
> @icarious0 Are you using the location re-routing feature or Play services location? Do you have re-routing disabled and the Play services network location accuracy option enabled?

Sorry. Where can I find that option? I guess I may be at defaults still.

**Comment by thestinger** [comment]
The default is location re-routing enabled, Location permission disabled by Play services (as with any other app) and network location accuracy toggle disabled. You should have working location with these default settings.

**Comment by thestinger** [comment]
This will be fixed by today's release.

**Comment by jibarofoss** [comment]
I'm having a similar issue:
```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.231205.015/2023121200:user/release-keys
package: com.popular.android.mibanco:176
process: com.popular.android.mibanco
processUptime: 7124 + 205 ms
installer: com.aurora.store

java.lang.NullPointerException: packageName can't be null
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getCellLocation(ITelephony.java:8696)
	at android.telephony.TelephonyManager.getCellLocation(TelephonyManager.java:2503)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.getCellTowerId(CollectDeviceData.java:835)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.collectDeviceLocationAndNetworkData(CollectDeviceData.java:337)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.collectDeviceData(CollectDeviceData.java:220)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.startCollection(CollectDeviceData.java:191)
	at com.rsa.mobilesdk.sdk.MobileAPI.initAndValidateProperties(MobileAPI.java:671)
	at com.rsa.mobilesdk.sdk.MobileAPI.initSDK(MobileAPI.java:459)
	at com.popular.android.mibanco.util.RSACollectUtils.collectDeviceInfo(RSACollectUtils.java:33)
	at com.popular.android.mibanco.task.AsyncTasks.login(AsyncTasks.java:1934)
	at com.popular.android.mibanco.activity.EnterUsername.login(EnterUsername.java:760)
	at com.popular.android.mibanco.activity.EnterUsername.savedData(EnterUsername.java:692)
	at com.popular.android.mibanco.task.AsyncTasks$StartTask.onPostExecute(AsyncTasks.java:1659)
	at com.popular.android.mibanco.task.AsyncTasks$StartTask.onPostExecute(AsyncTasks.java:1587)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```
GrapheneOS Apps says everything is up to date as of 9 minutes ago, and I'm on the latest stable version.

**Comment by thestinger** [comment]
@jibarofoss Does the app have the Location permission?

**Comment by jibarofoss** [comment]
Yes. I granted the permission both to the app itself and every permission google play services had. Same crash still happens.

**Comment by thestinger** [comment]
No permissions need to be granted to sandboxed Google Play. Location rerouting should be enabled.

What about the Phone permission?

**Comment by jibarofoss** [comment]
All permissions for the crashing app were granted.
![Screenshot_20231229-134951](https://github.com/GrapheneOS/os-issue-tracker/assets/5615573/94dac67a-77c7-49ac-b56b-3fa930c4639b)

**Comment by thestinger** [comment]
@jibarofoss Please file a new issue with all these details. It seems unrelated to this one.
