### ISSUE TITLE
Can't add many widgets after Android 14 update

### ISSUE THREAD

**Issue by flexagoon** [GrapheneOS/os-issue-tracker#2485]
Hello. After updating to Android 14, I can no longer add widgets from some (not all) apps to my home screen. Here is the output of `adb logcat "*:E"` when trying to add the widget from Simple Calendar:

<details>
<summary> Logcat output </summary>

```
10-11 01:34:07.180  1305  3811 E ActivityTaskManager: Without BAL hardening this activity start would be allowed! [callingPackage: android; callingUid: 1000; appSwitchState: 2; callingUidHasAnyVisibleWindow: false; callingUidProcState: PERSISTENT; isCallingUidPersistentSystemProcess: true; balAllowedByPiSender: BackgroundStartPrivileges[allowsBackgroundActivityStarts=false, allowsBackgroundForegroundServiceStarts=true, originatingToken=null]; realCallingPackage: com.android.launcher3; realCallingUid: 10101; realCallingUidHasAnyVisibleWindow: true; realCallingUidProcState: TOP; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: PendingIntentRecord{1acb00b android startActivity}; backgroundStartPrivileges: BackgroundStartPrivileges[allowsBackgroundActivityStarts=false, allowsBackgroundForegroundServiceStarts=false, originatingToken=null]; intent: Intent { act=android.appwidget.action.APPWIDGET_CONFIGURE cmp=com.simplemobiletools.calendar.pro/.activities.WidgetDateConfigureActivity (has extras) }; callerApp: null; inVisibleTask: false]
10-11 01:34:07.182  1305  3811 E ActivityTaskManager: Abort background activity starts from 1000
10-11 01:34:07.208  2514  2514 E StartActivityParams: Unable to send back result
10-11 01:34:07.208  2514  2514 E StartActivityParams: android.app.PendingIntent$CanceledException
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.PendingIntent.send(PendingIntent.java:1076)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.PendingIntent.send(PendingIntent.java:902)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at com.android.launcher3.proxy.StartActivityParams.deliverResult(StartActivityParams.java:96)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at com.android.launcher3.proxy.ProxyActivityStarter.onActivityResult(ProxyActivityStarter.java:73)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.Activity.dispatchActivityResult(Activity.java:8998)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5537)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5583)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.os.Looper.loopOnce(Looper.java:205)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.os.Looper.loop(Looper.java:294)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at android.app.ActivityThread.main(ActivityThread.java:8199)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at java.lang.reflect.Method.invoke(Native Method)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-11 01:34:07.208  2514  2514 E StartActivityParams: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
10-11 01:34:07.235  2514  2514 E Launcher: Error: appWidgetId (EXTRA_APPWIDGET_ID) was not returned from the widget configuration activity.
```

</details>

The output is the same for all other apps with this issue, the only difference is the package name.

**Comment by thestinger** [comment]
This looks like bugs in these apps. Can you check their trackers for Android 14 issues?

**Comment by flexagoon** [comment]
@thestinger the list of broken apps includes Google Clock and Google Photos, which are bundled by default on Pixel, so I doubt that they have broken A14 support. Bur no, I wasn't able to find any related bug reports for any of the affected apps.

**Comment by flexagoon** [comment]
All widgets seem to work fine in the Lawnchair third-party launcher

**Comment by flexagoon** [comment]
This issue was also reported on the forum:

https://discuss.grapheneos.org/d/7969-cant-add-certain-widgets

**Comment by thestinger** [comment]
Appears to be due to https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions.

**Comment by thestinger** [comment]
This will be fixed by the today's release.

**Comment by 8bitPit** [comment]
By the way, we had the same issue with Niagara Launcher with reconfigurable widgets when targeting Android 14. Creating a bundle and setting `setPendingIntentBackgroundActivityStartMode` to `ActivityOptions.MODE_BACKGROUND_ACTIVITY_START_ALLOWED` and passing it to startAppWidgetConfigureActivityForResult fixes the issue for us.

Example snippet:
```
 val bundle = ActivityOptions
  .makeBasic()
  .setPendingIntentBackgroundActivityStartMode(ActivityOptions.MODE_BACKGROUND_ACTIVITY_START_ALLOWED)
  .toBundle()
appWidgetHost.startAppWidgetConfigureActivityForResult(...,options=bundle)
```

**Comment by HaoyuCui** [comment]
That helps! Modify the `LauncherWidgetHolder.java` from `packages/apps/Launcher3/src/com/android/launcher3/widget`
**From**
```
mWidgetHost.startAppWidgetConfigureActivityForResult(activity, widgetId, 0, requestCode,
                   getConfigurationActivityOptions(activity, widgetId));
```
 **To**
```
ActivityOptions options = ActivityOptions.makeBasic()
        .setPendingIntentBackgroundActivityStartMode(
                ActivityOptions.MODE_BACKGROUND_ACTIVITY_START_ALLOWED);
Bundle bundle = options.toBundle();
mWidgetHost.startAppWidgetConfigureActivityForResult(activity, widgetId, 0, requestCode, bundle);
```
Will solve the problem that Android 14 devices' widget disappearing problem.
