### ISSUE TITLE
Google play sandbox crash

### ISSUE THREAD

**Issue by skyhiflyguy** [GrapheneOS/os-issue-tracker#2488]
```
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231005.007/2023100900:user/release-keys
package: com.google.android.gms:233717044
process: com.google.android.gms.persistent
processUptime: 242581 + 595 ms
installer: com.android.vending
GmsCompatConfig version: 77

java.lang.RuntimeException: Unable to start receiver com.google.android.gms.gservices.provider.GservicesOverrideReceiver: java.lang.IllegalArgumentException: Unknown URI content://com.google.android.gsf.gservices/override
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4469)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2263)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalArgumentException: Unknown URI content://com.google.android.gsf.gservices/override
	at android.content.ContentResolver.update(ContentResolver.java:2436)
	at android.content.ContentResolver.update(ContentResolver.java:2402)
	at com.google.android.gms.gservices.provider.GservicesChimeraProvider$OverrideReceiver.onReceive(:com.google.android.gms@233717044@23.37.17 (190400-570218080):54)
	at aevn.a(:com.google.android.gms@233717044@23.37.17 (190400-570218080):34)
	at mft.onReceive(:com.google.android.gms@233717044@23.37.17 (190400-570218080):17)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4460)
	... 11 more

```

**Comment by thestinger** [comment]
Have you updated GSF to 14 via the app repository client? PLease check if you still get the error after updating it.

**Comment by thestinger** [comment]
Likely going to be fixed by updating GSF to 14.
