### ISSUE TITLE
Launcher will not start in Owner profile

### ISSUE THREAD

**Issue by crocinsocks** [GrapheneOS/os-issue-tracker#2492]
Someone else in forum: https://discuss.grapheneos.org/d/7975-launcher-doesnt-start-after-recent-update

I've have also noticed the same on a pixel 6 pro. In my case this only seems to affect the 'Owner' profile; guest and other profiles are working fine.

```
type: crash
osVersion: google/raven/raven:14/UP1A.231005.007/2023100900:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 114346 + 345 ms

java.lang.IllegalArgumentException: shortLabel cannot be empty
at com.android.internal.util.Preconditions.checkStringNotEmpty(Preconditions.java:109)
at android.content.pm.ShortcutInfo$Builder.setShortLabel(ShortcutInfo.java:1237)
at com.android.launcher3.provider.LauncherDbUtils.migrateLegacyShortcuts(LauncherDbUtils.java:131)
at com.android.launcher3.model.DatabaseHelper.onUpgrade(DatabaseHelper.java:273)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:423)
at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:347)
at com.android.launcher3.model.ModelDbController.createDatabaseHelper(ModelDbController.java:117)
at com.android.launcher3.model.ModelDbController.createDbIfNotExists(ModelDbController.java:99)
at com.android.launcher3.model.ModelDbController.migrateGridIfNeeded(ModelDbController.java:290)
at com.android.launcher3.model.LoaderTask.loadWorkspaceImpl(LoaderTask.java:371)
at com.android.launcher3.model.LoaderTask.loadWorkspace(LoaderTask.java:344)
at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:210)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.os.HandlerThread.run(HandlerThread.java:67)

```

Thanks

**Comment by thestinger** [comment]
This may be fixed by the next release. You can work around it by clearing the app data for now if you don't mind losing your home screen setup.

**Comment by thestinger** [comment]
This is fixed by the latest release. It was an AOSP regression. Clearing launcher app data works as an alternative to updating.
