### ISSUE TITLE
Google Fi app keeps crashing, can't send SMS

### ISSUE THREAD

**Issue by frogmech** [GrapheneOS/os-issue-tracker#2525]
It started yesterday, the Google Fi app keeps crashing and I can receive SMS delayed by a few minutes but I can't send SMS. Calls work fine. I already tried the solution in #2517 with no luck.

```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231005.007/2023101100:user/release-keys
package: com.google.android.apps.tycho:2580779
process: com.google.android.apps.tycho:persistent
processUptime: 547 + 262 ms
installer: com.aurora.store

java.lang.RuntimeException: Unable to create service com.google.android.apps.tycho.services.NovaCarrierService: ftt: An error occurred while executing registry entry 24
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:4681)
    at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2271)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8199)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: ftt: An error occurred while executing registry entry 24
    at fts.a(PG:14)
    at ijn.a(PG:8)
    at com.google.android.apps.tycho.services.NovaCarrierService.onCreate(PG:38)
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:4668)
    ... 11 more
Caused by: java.lang.SecurityException: com.google.android.apps.tycho: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
    at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
    at android.os.Parcel.createException(Parcel.java:3050)
    at android.os.Parcel.readException(Parcel.java:3026)
    at android.os.Parcel.readException(Parcel.java:2968)
    at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5699)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1873)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1801)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
    at ftr.d(PG:1)
    at fts.a(PG:5)
    ... 14 more
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13988)
    at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2578)
    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2724)
    at android.os.Binder.execTransactInternal(Binder.java:1368)
    at android.os.Binder.execTransact(Binder.java:1299)
```

**Comment by frogmech** [comment]
Uninstalling Google Fi and reinstalling it through the Play Store instead of Aurora Store seems to have fixed it

**Comment by thestinger** [comment]
Aurora Store often installs wrong variant of apps in the default "anonymous mode" which mainly avoids sending device model leading to getting wrong app variants.
