### ISSUE TITLE
Sandboxed Google Play crashed after updated to android 14 and to the new update

### ISSUE THREAD

**Issue by khelochagabia** [GrapheneOS/os-issue-tracker#2533]
type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231005.007/2023101100:user/release-keys
package: com.google.android.gms:233514044
process: com.google.android.gms.persistent
processUptime: 940 + 41959 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 77

java.lang.NullPointerException: packageName can't be null
 at android.os.Parcel.createExceptionOrNull(parcel.java:3072)
 at android.os.Parcel.createException(parcel.java:3050)
 at android.os.Parcel.readException(parcel.java:3026)
 at android.os.Parcel.readException(parcel.java:2968)
 at com.android.internal.telephony.ITelephony$Stub$Proxy.requestCellInfoUpdate(itelephony.java:9641)
 at android.telephony.TelephonyManager.requestCellInfoUpdate(telephonymanager.java:6807)
 at android.telephony.TelephonyManager.requestCellInfoUpdate(telephonymanager.java:6869)
 at dkjq.handleMessage(:com.google.android.gms[@233514044](https://t.me/233514044)@23.35.14 (190400-561707045):596)
 at android.os.Handler.dispatchMessage(handler.java:106)
 at bbxa.lJ(:com.google.android.gms[@233514044](https://t.me/233514044)@23.35.14 (190400-561707045):1)
 at bbxa.dispatchMessage(:com.google.android.gms[@233514044](https://t.me/233514044)@23.35.14 (190400-561707045):143)
 at android.os.Looper.loopOnce(looper.java:205)
 at android.os.Looper.loop(looper.java:294)
 at [android.os.HandlerThread.run](https://android.os.handlerthread.run/)(handlerthread.java:67)
 Suppressed: dpws: 
  at tk_trace.location_base-GoogleLocationChimeraService_onStartCommand(Unknown Source:0)
  at tk_trace.location_base-GoogleLocationChimeraService_onStartCommand(Unknown Source:0)

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/2517 is filed about this already. Please disable the Location permission for Play services as a workaround. You don't need to grant it the Location permission to use location in apps using Google Play geolocation. There's an upstream Android 14 issue also impacting the stock OS which breaks using one of the APIs it calls in secondary users. The reason Play services doesn't crash in the stock OS is because it only runs this code in the main user so it doesn't hit the OS bug. We're working on fixing it as our highest priority.
