### ISSUE TITLE
Connected ethernet reverts back to wifi/cellphone network when going to sleep

### ISSUE THREAD

**Issue by karolyi** [GrapheneOS/os-issue-tracker#2535]
Hey,

I've got a pixel 7 pro with the latest GrapheneOS where Android 14 recently arrived. I've got two USB Type-C ethernet adapters, one is a simple "Amazon basics" adapter, the other one is a USB hub with an ethernet connector on it, both can be used with a phone.

With this latest update, my daytime USB connected ethernet disconnects when the phone is going into sleep mode. Just tested, no matter which adapter it is, both has the same phenomenon.

Just thought I'll report it here.

**Comment by karolyi** [comment]
Correction: the phone keeps periodically switching the Ethernet adapter on and off. When it goes to sleep, I see the green link LED turning off for various periods, until it turns on again for a certain amount of time. The duration of these cycles vary, as I've observed so far.

**Comment by sec-oops** [comment]
I've tried to replicate this issue using a P7P + generic amazon USB C > Ethernet on the latest build and not been able to reproduce, can you confirm if this is still occurring?

**Comment by karolyi** [comment]
Hey,

either I still don't have the latest update (I'm on the stable channel, build number UP1A.231005.007.2023101300, the updater says it's the latest), or I still can reproduce it.

I'm using trackercontrol but I've turned it off for the time of testing to make sure it doesn't interfere.

If you can point me into a direction as to where to start looking for details, I can try and do so. It still switches back and forth, while bringing the phone back from sleep mode sometimes doesn't happen instantly. Maybe it dozes itself way too much somehow?

**Comment by karolyi** [comment]
hey @matchboxbananasynergy,

not sure what QPR1 is, but I can confirm that the issue still persists on the build number UQ1A.231205.015.2023120800 (pixel 7 pro)

**Comment by kunzstef** [comment]
I cannot confirm this on stock OS, but with Graphane Ethernet tethering is only reliable with screensaver enabled during charging. In this case the displayed  Ethernet tethering toggle in the settings still gets deactivated and disabled (can be edited and activated again after reattaching the Ethernet adapter), but tethering continues. 
Rarely when the device is then unplugged from the Ethernet adapter while tethering, the OS crashes and reboots:
```
type: crash
Process: system_server
Build: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at android.net.connectivity.com.android.server.ethernet.EthernetNetworkFactory.getInterfaceState(EthernetNetworkFactory.java:170)
at android.net.connectivity.com.android.server.ethernet.EthernetTracker.unicastInterfaceStateChange(EthernetTracker.java:328)
at android.net.connectivity.com.android.server.ethernet.EthernetTracker.lambda$addListener$4(EthernetTracker.java:435)
at android.net.connectivity.com.android.server.ethernet.EthernetTracker.$r8$lambda$u74wXsW90rogcJx8NNlJoTHWh6U(EthernetTracker.java:0)
at android.net.connectivity.com.android.server.ethernet.EthernetTracker$$ExternalSyntheticLambda5.run(R8$$SyntheticClass:0)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by onlycparra** [comment]
I confirm the behavior: Shortly after going to sleep, the ethernet adapter powers off (not even lights in the ethernet port).

Android 14
Pixel 6 pro
Build number: 2024050700

**Comment by karolyi** [comment]
Today I discovered by sheer coincidence that this bug ceased to exist with the latest update from yesterday (Pixel 7 Pro), that is `2024053100`.

Could others here confirm please?

I wonder what changes entered into this update that fixed the bug, maybe something from upstream.

**Comment by karolyi** [comment]
I've originally added a comment that I accidentally discovered that this bug ceased to exist, however it wasn't the case. I still can reproduce it but it happens later with the latest update `2024053100` on my Pixel 7 pro.

It seems that the device keeps the Ethernet connection for much longer, then goes to sleep, and connects back again within 10 seconds. Then, after a 5-6 minutes of screen blanking now, it turns off the interface, then comes back again (LED on) but it doesn't ping anymore and the delayed screen-on effect is still there.

This wasn't the case before since it disconnected right after screen blanking. Upon disconnect, the link led also stops flashing.

Right now, the interface is up but it doesn't ping, and upon unlocking it restarts the interface (LED off/on) and starts pinging again.

**Comment by onlycparra** [comment]
A thought here... I haven't tried this yet: Settings/Security/USB-C Port. Has interesting options for enabling/disabling usb-c when the device is locked.

Right now my selected option is "charging-only when locked". 

That sounds a lot like it could be the root of the issue.

If anybody can test, that would be nice. I'll try once I get some free time.

**Comment by karolyi** [comment]
Last time I checked, yes.

**Comment by karolyi** [comment]
Would that be build number 2025030300?

**Comment by karolyi** [comment]
Okay, I'll wait for 2025030700 and see what gives. My phone is a 'production' device so I don't want to risk bricking it.

**Comment by karolyi** [comment]
20250305800 arrived today.

I put the phone on the dongle for about 2x10 minutes in standby (with a wakeup inbetween) and the ethernet link never disconnected. It also jumped back from standby instantly, which wasn't the case before.

The link loss happened before in about maximum 30 seconds, after putting the phone in standby mode. I think this might just have been fixed, but maybe others could test as well.
