### ISSUE TITLE
com.google.android.gms crash

### ISSUE THREAD

**Issue by thilakm-git** [GrapheneOS/os-issue-tracker#2552]
```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231005.007/2023101300:user/release-keys
package: com.google.android.gms:234014044
process: com.google.android.gms
processUptime: 5157844 + 63 ms
installer: com.android.vending
GmsCompatConfig version: 78

eahd: rethrowing error from lowpool[0]
	at aiha.run(:com.google.android.gms@234014044@23.40.14 (190400-572056781):27)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at benu.lJ(:com.google.android.gms@234014044@23.40.14 (190400-572056781):1)
	at benu.dispatchMessage(:com.google.android.gms@234014044@23.40.14 (190400-572056781):143)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
	Suppressed: dtsf: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.semanticlocationhistory-StoreVisitsProcessingService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~Z774CvyIKFrKPrrzIm8Vog==/com.google.android.gms-U8smA_BVBs4_FrVoub0-qw==/base.apk!/lib/arm64-v8a/libgeller_jni_lite_lib.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.google.android.gms.semanticlocationhistory.deidentifieddata.storevisits.StoreVisitsProcessingService.gW(:com.google.android.gms@234014044@23.40.14 (190400-572056781):115)
	at bepk.call(:com.google.android.gms@234014044@23.40.14 (190400-572056781):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at aihr.c(:com.google.android.gms@234014044@23.40.14 (190400-572056781):50)
	at aihr.run(:com.google.android.gms@234014044@23.40.14 (190400-572056781):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at aimw.run(:com.google.android.gms@234014044@23.40.14 (190400-572056781):8)
	at java.lang.Thread.run(Thread.java:1012)

```

Let me know if more info needed.

**Comment by thestinger** [comment]
Please update to the latest release and try again.

**Comment by thestinger** [comment]
@QuestioningEspecialy This is entirely unrelated and is because you're so far behind on updates but have a current version of sandboxed Google Play.

**Comment by thestinger** [comment]
@QuestioningEspecialy That's not related to this. You need to update to a current release of GrapheneOS. You're on a release from 2023-06-23. That's extremely far behind and being on such an old release with current GmsCompatConfig and Google Play versions is unsupported. Updating Play services even further would be the opposite of what is needed. The issue you're talking about was resolved around November 2023 before it reached users who weren't helping us beta / alpha test new Play services versions.

**Comment by thestinger** [comment]
Silencing notifications wouldn't have stopped you getting updates, it only would have stopped it telling you to reboot. I doubt that you've gone over half a year without a reboot. You likely disabled the update client or changed the configured in a way that stopped you getting updates. Seems most likely that you disabled it. You should read https://grapheneos.org/usage#updates. Being that far behind on OS updates is not good. You should be happy you ran into that problem caused by being too far out of date because it has uncovered a huge problem you need to solve.
