### ISSUE TITLE
Touchscreen responsiveness greatly reduced, UI stickiness on Android 14 

### ISSUE THREAD

**Issue by UmahhRoan** [GrapheneOS/os-issue-tracker#2559]
My Pixel 6a has suddenly become a sticky mess since upgrading to the latest Android 14 build UP1A.231005.007.2023101300
I was on 13 until now and loved it.

Issues are:
- Gesture swipe no longer works as intended, there is no "Release" after i remove my finger, it just stops instead of the animation rolling off when scrolling. this results in simple things like my notifications not being able to be dismissed individually, the swipe gesture navigation no longer works properly unless you overemphasize every swipe, so i have to use the 3 button navigation now to get around on the phone.
- buttons are just generally less responsive, sometimes i'm typing and i have to hit a letter 2 or 3 times before it registers. same with any other tap.
- Is there a way to downgrade until these issues are fixed?

Thank you!

here's the crash log of the default launcher as well since upgrading which has happened a couple of times:

type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231005.007/2023101300:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 17333 + 815 ms

java.lang.NullPointerException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2064)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1879)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1710)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1656)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1426)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1416)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1467)
	at com.android.launcher3.icons.ShortcutCachingLogic.getIcon(ShortcutCachingLogic.java:109)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:77)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:43)
	at com.android.launcher3.icons.cache.BaseIconCache.addIconToDBAndMemCache(BaseIconCache.java:324)
	at com.android.launcher3.icons.cache.IconCacheUpdateHandler$SerializedIconUpdateTask.run(IconCacheUpdateHandler.java:294)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by thestinger** [comment]
We're not able to reproduce any of this, and the vast majority of people aren't impacted. There's something about your configuration and/or apps which causes these issues.

> Is there a way to downgrade until these issues are fixed?

No, and it's not clear what there is to fix right now.

**Comment by thestinger** [comment]
You could try clearing the launcher's data.

**Comment by irelativism** [comment]
I experienced the some stickiness but only on what regards to the lockscreen, and might be a enterely separate issue regarding 2 conflicting UIs check #2553 
Cheers Irelativism

**Comment by UmahhRoan** [comment]
thank you for your help friends. I'm not sure what happened but the phone is fine now. i didn't change any other setting, perhaps it was still updating in the background and was lagging, i'm not too sure. apologies i couldnt narrow this down any further.

**Comment by irelativism** [comment]
Can you described better what you mean by stickiness?
