### ISSUE TITLE
Null pointer exception in settings app

### ISSUE THREAD

**Issue by Manodiestra** [GrapheneOS/os-issue-tracker#2584]
When the "Charging optimized to protect your battery" message appears in the battery page of the settings app on the Pixel Tablet while on the dock. There is a "Charge to full" and a "Learn more" button.

Tapping the "Learn more" button throws the following error:

```
type: crash
osVersion: google/tangorpro/tangorpro:14/UP1A.231005.007/2023101300:user/release-keys
package: com.android.settings:34
process: com.android.settings
processUptime: 23297 + 222 ms

java.lang.NullPointerException: activityIntentPair.second must not be null
	at androidx.window.embedding.EmbeddingAdapter.translateSplitPairRule$lambda$5(EmbeddingAdapter.kt:169)
	at androidx.window.embedding.EmbeddingAdapter.$r8$lambda$Je3SMWBCpjlXBH0MVRXrGCVbLSY(EmbeddingAdapter.kt:0)
	at androidx.window.embedding.EmbeddingAdapter$$ExternalSyntheticLambda1.test(R8$$SyntheticClass:0)
	at androidx.window.extensions.embedding.SplitPairRule.matchesActivityIntentPair(SplitPairRule.java:84)
	at androidx.window.extensions.embedding.SplitController.getSplitRule(SplitController.java:1900)
	at androidx.window.extensions.embedding.SplitController.getSecondaryContainerForSplitIfAny(SplitController.java:1289)
	at androidx.window.extensions.embedding.SplitController.resolveStartActivityIntent(SplitController.java:1207)
	at androidx.window.extensions.embedding.SplitController$ActivityStartMonitor.onStartActivity(SplitController.java:2235)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2013)
	at android.app.Activity.startActivityForResult(Activity.java:6477)
	at android.view.View.startActivityForResult(View.java:7882)
	at com.android.settings.fuelgauge.batterytip.tips.DockDefenderTip.lambda$updatePreference$1(DockDefenderTip.java:143)
	at com.android.settings.fuelgauge.batterytip.tips.DockDefenderTip.$r8$lambda$icbuJL5k0afmY4TUeprnx_8pQYE(DockDefenderTip.java:0)
	at com.android.settings.fuelgauge.batterytip.tips.DockDefenderTip$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by Manodiestra** [comment]
Yes. I Still see it with

```
osVersion: google/tangorpro/tangorpro:14/UP1A.231005.007/2023102300:user/release-keys
package: com.android.settings:34
process: com.android.settings
```

Optimised charging only happens when docked, though. You won't see it if charging via USB.

**Comment by Manodiestra** [comment]
Yes.

```
type: crash
osVersion: google/tangorpro/tangorpro:14/UQ1A.231205.015/2023121200:user/release-keys
package: com.android.settings:34
process: com.android.settings
processUptime: 5412 + 221 ms

java.lang.NullPointerException: activityIntentPair.second must not be null
	at androidx.window.embedding.EmbeddingAdapter.translateSplitPairRule$lambda$5(EmbeddingAdapter.kt:167)
	at androidx.window.embedding.EmbeddingAdapter.$r8$lambda$Je3SMWBCpjlXBH0MVRXrGCVbLSY(EmbeddingAdapter.kt:0)
	at androidx.window.embedding.EmbeddingAdapter$$ExternalSyntheticLambda1.test(R8$$SyntheticClass:0)
	at androidx.window.extensions.embedding.SplitPairRule.matchesActivityIntentPair(SplitPairRule.java:84)
	at androidx.window.extensions.embedding.SplitController.getSplitRule(SplitController.java:2035)
	at androidx.window.extensions.embedding.SplitController.getSecondaryContainerForSplitIfAny(SplitController.java:1404)
	at androidx.window.extensions.embedding.SplitController.resolveStartActivityIntent(SplitController.java:1320)
	at androidx.window.extensions.embedding.SplitController$ActivityStartMonitor.onStartActivity(SplitController.java:2372)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2013)
	at android.app.Activity.startActivityForResult(Activity.java:6503)
	at android.view.View.startActivityForResult(View.java:7881)
	at com.android.settings.fuelgauge.batterytip.tips.DockDefenderTip.lambda$updatePreference$1(DockDefenderTip.java:143)
	at com.android.settings.fuelgauge.batterytip.tips.DockDefenderTip.$r8$lambda$icbuJL5k0afmY4TUeprnx_8pQYE(DockDefenderTip.java:0)
	at com.android.settings.fuelgauge.batterytip.tips.DockDefenderTip$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7658)
	at android.view.View.performClickInternal(View.java:7635)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30167)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```
