### ISSUE TITLE
Crash while trying to split screen, points to Gos launcher. 

### ISSUE THREAD

**Issue by n3rdcub** [GrapheneOS/os-issue-tracker#2622]
However, if you then set the stock launcher as default all of a sudden you're able to split screen whatever problematic apps were causing the error. I am currently jumping between a couple launchers but this is detectable on lawnchair Nova and Niagara I think kvaetsitso too

I'll grab a log here shortly

```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023102300:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 12061 + 95 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.views.FloatingTaskView.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
	at com.android.quickstep.views.RecentsView.confirmSplitSelect(RecentsView.java:4696)
	at com.android.quickstep.views.TaskView.confirmSecondSplitSelectApp(TaskView.java:762)
	at com.android.quickstep.views.TaskView.lambda$setIcon$11(TaskView.java:1102)
	at com.android.quickstep.views.TaskView.$r8$lambda$KTUKGHkPjfRenOSUDES7zNiunRs(Unknown Source:0)
	at com.android.quickstep.views.TaskView$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

Tested with Niagara. Immediate crash. When using stock GoS AOSP launcher it works damn near every time. Any other launcher gives this result. Will test with lawnchair and post here

**Comment by n3rdcub** [comment]
Google Messages & Vanadium. The apps themselves are irrelevant it happens with any but reporting for brevity.

```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023102300:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 16249 + 102 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.views.FloatingTaskView.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
	at com.android.quickstep.views.RecentsView.confirmSplitSelect(RecentsView.java:4696)
	at com.android.quickstep.views.TaskView.confirmSecondSplitSelectApp(TaskView.java:762)
	at com.android.quickstep.views.TaskView.onClick(TaskView.java:746)
	at com.android.quickstep.views.TaskView.$r8$lambda$2dErZAYzRAWboZR0vn31kIz_HGY(Unknown Source:0)
	at com.android.quickstep.views.TaskView$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```
Again, if I set the stock gos launcher as default and try to open up those same two apps it will work every time flawlessly but as soon as I set another app is default I get these errors

**Comment by n3rdcub** [comment]
Google Messages & Vanadium. The apps themselves are irrelevant it happens with any but reporting for brevity.

```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023102300:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 16249 + 102 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.views.FloatingTaskView.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
	at com.android.quickstep.views.RecentsView.confirmSplitSelect(RecentsView.java:4696)
	at com.android.quickstep.views.TaskView.confirmSecondSplitSelectApp(TaskView.java:762)
	at com.android.quickstep.views.TaskView.onClick(TaskView.java:746)
	at com.android.quickstep.views.TaskView.$r8$lambda$2dErZAYzRAWboZR0vn31kIz_HGY(Unknown Source:0)
	at com.android.quickstep.views.TaskView$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```
Again, if I set the stock gos launcher as default and try to open up those same two apps it will work every time flawlessly but as soon as I set another app is default I get these errors

**Comment by n3rdcub** [comment]
Google Messages & Vanadium. The apps themselves are irrelevant it happens with any but reporting for brevity.

```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023102300:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 16249 + 102 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.views.FloatingTaskView.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
	at com.android.quickstep.views.RecentsView.confirmSplitSelect(RecentsView.java:4696)
	at com.android.quickstep.views.TaskView.confirmSecondSplitSelectApp(TaskView.java:762)
	at com.android.quickstep.views.TaskView.onClick(TaskView.java:746)
	at com.android.quickstep.views.TaskView.$r8$lambda$2dErZAYzRAWboZR0vn31kIz_HGY(Unknown Source:0)
	at com.android.quickstep.views.TaskView$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```
Again, if I set the stock gos launcher as default and try to open up those same two apps it will work every time flawlessly but as soon as I set another app is default I get these errors

```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023102300:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 62306 + 121 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.views.FloatingTaskView.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
	at com.android.quickstep.views.RecentsView.confirmSplitSelect(RecentsView.java:4696)
	at com.android.quickstep.views.TaskView.confirmSecondSplitSelectApp(TaskView.java:762)
	at com.android.quickstep.views.TaskView.onClick(TaskView.java:746)
	at com.android.quickstep.views.TaskView.$r8$lambda$2dErZAYzRAWboZR0vn31kIz_HGY(Unknown Source:0)
	at com.android.quickstep.views.TaskView$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7659)
	at android.view.View.performClickInternal(View.java:7636)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30156)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

Edit: unfortunately I don't have more time to test but with what I was able to quickly figure out this seems something related to battery saver. When it's on it causes this to happen almost every time as soon as I turn it off suddenly I can start splitting those apps any app that was giving me problem

**Comment by mrxx0** [comment]
Unable to reproduce on 6a running 2023103100
Tested with : 
- Lawnchair 12.1.0 Alpha 4
- Niagara Launcher 1.9.9
With and without battery saver

**Comment by bhanuagarwal73** [comment]
Hey guys,
I am also facing the same issue.

I tried clearing the storage, force stop & more but nothing worked.

When I am using Nova Launcher then getting error during switching the app as GoLauncher stopped working but if make GoLauncher as default then working great.

Any help here !!!
