### ISSUE TITLE
Sandboxed Google play crashed

### ISSUE THREAD

**Issue by serafinPlym** [GrapheneOS/os-issue-tracker#2643]

**Comment by mrxx0** [comment]
Hi there,
You will have to give more details on the issue : what device, what os release, what version of Sandboxed Play services are you using and the steps to reproduce the crash

**Comment by serafinPlym** [comment]
Yes. I was about to, but got distracted by phone call. When I got back to this, it was fixed and ok. 

Her is the log:  
```
type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231005.007/2023103100:user/release-keys
package: com.google.android.gms:234212044
process: com.google.android.gms
processUptime: 16997 + 280 ms
installer: com.android.vending
GmsCompatConfig version: 81

java.lang.SecurityException: Attempt to change component state; pid=27880, uid=1010129, package=com.google.android.gms.supervision
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.content.pm.IPackageManager$Stub$Proxy.setApplicationEnabledSetting(IPackageManager.java:6198)
	at android.app.ApplicationPackageManager.setApplicationEnabledSetting(ApplicationPackageManager.java:3118)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.setApplicationEnabledSetting(GmcPackageManager.java:138)
	at bfbc.a(:com.google.android.gms@234212044@23.42.12 (190400-574052649):12)
	at com.google.android.gms.kids.settings.KidsSettingsModuleInitIntentOperation.onHandleIntent(:com.google.android.gms@234212044@23.42.12 (190400-574052649):163)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234212044@23.42.12 (190400-574052649):2)
	at aghp.onHandleIntent(:com.google.android.gms@234212044@23.42.12 (190400-574052649):10)
	at nok.run(:com.google.android.gms@234212044@23.42.12 (190400-574052649):70)
	at noj.run(:com.google.android.gms@234212044@23.42.12 (190400-574052649):152)
	at dveh.run(:com.google.android.gms@234212044@23.42.12 (190400-574052649):13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by serafinPlym** [comment]
Pixel7pro
Os v. 21
Second/work profile w sandboxed google
Sandboxed play 23.42.12

Crashes just after changing to second profile

**Comment by antarctic3431** [comment]
Can confirm - Started receiving "**Sandboxed Google Play crashed**" notifications after updating to GmsCompatConfig version 81. Similar to what was mentioned earlier, this is occurring in a secondary profile, with the crash notification happening seconds after initial profile unlock.

Pixel 7 (2023103100)
GmsCompatConfig 81
Google Play Services 23.42.12

**Comment by Infermity** [comment]
I had a similar error but it seems to work now for some reason.

**Comment by thestinger** [comment]
Will be fixed by GmsCompatConfig 82 coming in a few minutes.
