### ISSUE TITLE
System UI has stopped - Error

### ISSUE THREAD

**Issue by tropicalMood** [GrapheneOS/os-issue-tracker#2646]
Since I use physical sim-card in my phone,
I see this ERROR message pretty frequently (pretty much every day). Error say "System UI has stopped"
Back than I didn't saw it ever to happend.
After error message will show up, screen work for say half second, another second is completely dark and its repeat until I restart phone -> Which I have to do it as display doesn't work properly.

Model: Pixel 6a
Android version 14
Android security update October 6 2023
Kernel version: 5.10.198-android13-4-g57616f1b5f6f

**Comment by akc3n** [comment]
May you please provide more details, such as are you multiple profiles, the default launcher or a third party one? Which build version is it? There are many duplicates of similar issues related to this. Have a look around using the search feature in this issue tracker. The crash log would help too.

**Comment by gsture** [comment]
I I have the same problem but with various apps and the launcher. I don't use multiple profiles, I do use work apps. Launcher is also stock launcher.

```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023103100:user/release-keys
package: nl.rabomobiel:73242690
process: nl.rabomobiel:iyeydyuyjyqyoyvyryaygycyhypyxylyzysykiyieijiqioizikeueqexezeywiwewdwjwqwow:yy.zr
processUptime: 635 + 1135 ms
installer: com.aurora.store

java.lang.RuntimeException: Unable to create application yy.YW: yy.isG: Could not create instance for '[Singleton:'yy.qj']'
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7025)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: yy.isG: Could not create instance for '[Singleton:'yy.qj']'
	at yy.cmG.GkG(yy.cmG:59)
	at yy.lnG.GkG(yy.lnG:46)
	at yy.uEG.EvV(yy.uEG:53)
	at yy.uEG.invoke(yy.uEG:51)
	at yy.qmG.ZBV(yy.qmG:20)
	at yy.lnG.VkG(yy.lnG:51)
	at yy.hmG.Xc(yy.hmG:96)
	at yy.hmG.hPG(yy.hmG:64)
	at yy.UsG.Qxc(yy.UsG:339)
	at yy.PsG.Coc(yy.PsG:74)
	at yy.DnG.GLV(yy.DnG:66)
	at yy.PX.Xc(Unknown Source:40)
	at yy.YW.onCreate(yy.YW:85)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1321)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7020)
	... 11 more
Caused by: yy.isG: Could not create instance for '[Factory:'android.net.ConnectivityManager']'
	at yy.cmG.GkG(yy.cmG:59)
	at yy.knG.VkG(yy.knG:38)
	at yy.hmG.lPG(yy.hmG:116)
	at yy.pmG.Xc(yy.pmG:246)
	at yy.pmG.kc(yy.pmG:231)
	at yy.pmG.kmV(yy.pmG:210)
	at yy.Ovc.JWG(yy.Ovc:128)
	at yy.Ovc.invoke(yy.Ovc:65)
	at yy.cmG.GkG(yy.cmG:52)
	... 25 more
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type android.net.ConnectivityManager
	at yy.VEG.IG(yy.VEG:31)
	at yy.xvc.okV(yy.xvc:11)
	at yy.xvc.invoke(yy.xvc:10)
	at yy.cmG.GkG(yy.cmG:52)
	... 33 more

```

**Comment by tropicalMood** [comment]
I use default profile. Just use [Insular](https://f-droid.org/en/packages/com.oasisfeng.island.fdroid/) which create Personal and Work "app profile" not sure how its relevant. I use default launcher.
Build number: UP1A.231005.007.2023103100

**Comment by joafri** [comment]
I have the same issue.
Model: Pixel 7 Pro
Android version 14
Build number: UP1A.231105.003.2023110700

I run two profiles, but one is more or less dormant. 
Only using main profile
no work profile
google play in sandbox
1 simcard in slot 1

Crashes seem to come at random, but a bit more often if I watch YouTube videos that have been pre-downloaded.

**Comment by thestinger** [comment]
Likely fixed by QPR1. Open a new issue if you experience a new crash because it's likely for a different reason.
