### ISSUE TITLE
Google play sandbox crashing

### ISSUE THREAD

**Issue by Infermity** [GrapheneOS/os-issue-tracker#2647]
Hello,

It seems after android 14 was updated my Google play app no longer works and straight crashes. I am on a pixel 7.

Here's the log:
```
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023103100:user/release-keys
package: com.google.android.gms:234313038
process: com.google.android.gms
processUptime: 259011 + 307 ms
installer: com.android.vending
GmsCompatConfig version: 81

java.lang.SecurityException: Attempt to change component state; pid=3249, uid=10127, package=com.google.android.gms.supervision
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.content.pm.IPackageManager$Stub$Proxy.setApplicationEnabledSetting(IPackageManager.java:6198)
	at android.app.ApplicationPackageManager.setApplicationEnabledSetting(ApplicationPackageManager.java:3118)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.setApplicationEnabledSetting(GmcPackageManager.java:138)
	at bfei.a(:com.google.android.gms@234313038@23.43.13 (190400-577232161):12)
	at com.google.android.gms.kids.settings.KidsSettingsModuleInitIntentOperation.onHandleIntent(:com.google.android.gms@234313038@23.43.13 (190400-577232161):163)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234313038@23.43.13 (190400-577232161):2)
	at agjc.onHandleIntent(:com.google.android.gms@234313038@23.43.13 (190400-577232161):10)
	at nnr.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):70)
	at nnq.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):152)
	at dvhx.run(:com.google.android.gms@234313038@23.43.13 (190400-577232161):13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by Infermity** [comment]
Oh it's working now that's weird.

**Comment by thestinger** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2643.
