### ISSUE TITLE
Various app crashes

### ISSUE THREAD

**Issue by gsture** [GrapheneOS/os-issue-tracker#2648]
I have problems with various apps and the launcher crashing after the latest update (2023103100). I randomly get a pop up that the app has stopped working also when not directly using the app. When using the app i get multiple crashes but i can still keep using the app. I never had this before the latest update.

- OS build: 2023103100
- I don't use multiple profiles. (I do use work apps).
- Launcher stock
- I have 2 pixel 5's and both have the same issue.
- I use always on VPN but If I disable it I still get a crash.

Here is crash report:

type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023103100:user/release-keys
package: nl.rabomobiel:73242690
process: nl.rabomobiel:iyeydyuyjyqyoyvyryaygycyhypyxylyzysykiyieijiqioizikeueqexezeywiwewdwjwqwow:yy.zr
processUptime: 635 + 1135 ms
installer: com.aurora.store

java.lang.RuntimeException: Unable to create application yy.YW: yy.isG: Could not create instance for '[Singleton:'yy.qj']'
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7025)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: yy.isG: Could not create instance for '[Singleton:'yy.qj']'
	at yy.cmG.GkG(yy.cmG:59)
	at yy.lnG.GkG(yy.lnG:46)
	at yy.uEG.EvV(yy.uEG:53)
	at yy.uEG.invoke(yy.uEG:51)
	at yy.qmG.ZBV(yy.qmG:20)
	at yy.lnG.VkG(yy.lnG:51)
	at yy.hmG.Xc(yy.hmG:96)
	at yy.hmG.hPG(yy.hmG:64)
	at yy.UsG.Qxc(yy.UsG:339)
	at yy.PsG.Coc(yy.PsG:74)
	at yy.DnG.GLV(yy.DnG:66)
	at yy.PX.Xc(Unknown Source:40)
	at yy.YW.onCreate(yy.YW:85)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1321)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7020)
	... 11 more
Caused by: yy.isG: Could not create instance for '[Factory:'android.net.ConnectivityManager']'
	at yy.cmG.GkG(yy.cmG:59)
	at yy.knG.VkG(yy.knG:38)
	at yy.hmG.lPG(yy.hmG:116)
	at yy.pmG.Xc(yy.pmG:246)
	at yy.pmG.kc(yy.pmG:231)
	at yy.pmG.kmV(yy.pmG:210)
	at yy.Ovc.JWG(yy.Ovc:128)
	at yy.Ovc.invoke(yy.Ovc:65)
	at yy.cmG.GkG(yy.cmG:52)
	... 25 more
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type android.net.ConnectivityManager
	at yy.VEG.IG(yy.VEG:31)
	at yy.xvc.okV(yy.xvc:11)
	at yy.xvc.invoke(yy.xvc:10)
	at yy.cmG.GkG(yy.cmG:52)
	... 33 more

**Comment by nicohansi** [comment]
I have similar issues.

Here are a few more crash reports.

`de.hafas.android.db`:

```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023103100:user/release-keys
package: de.hafas.android.db:240000009
process: de.hafas.android.db
processUptime: 4536974 + 435 ms
installer: com.android.packageinstaller

android.view.InflateException: Binary XML file line #104 in de.hafas.android.db:layout/fragment_home: Binary XML file line #2 in de.hafas.android.db:layout/view_blitzbox: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #2 in de.hafas.android.db:layout/view_blitzbox: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:866)
	at android.view.LayoutInflater.createView(LayoutInflater.java:788)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:942)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:962)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1245)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at zs.f0.onCreateView(Unknown Source:9)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:24)
	at androidx.fragment.app.n0.f(Unknown Source:208)
	at androidx.fragment.app.n0.m(Unknown Source:124)
	at androidx.fragment.app.o0.t(Unknown Source:30)
	at androidx.fragment.app.FragmentManager.g1(Unknown Source:27)
	at androidx.fragment.app.FragmentManager.W(Unknown Source:9)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:11)
	at androidx.fragment.app.v.c(Unknown Source:4)
	at androidx.fragment.app.s.onStart(Unknown Source:20)
	at androidx.appcompat.app.d.onStart(Unknown Source:0)
	at db.vendo.android.vendigator.view.main.MainActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1587)
	at android.app.Activity.performStart(Activity.java:8684)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3818)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7f080105
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f080105
	at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:273)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:850)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:681)
	at android.content.res.Resources.loadDrawable(Resources.java:1004)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1017)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:991)
	at android.view.View.<init>(View.java:5706)
	at android.view.ViewGroup.<init>(ViewGroup.java:704)
	at android.widget.FrameLayout.<init>(FrameLayout.java:99)
	at android.widget.FrameLayout.<init>(FrameLayout.java:94)
	at android.widget.FrameLayout.<init>(FrameLayout.java:89)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:866)
	at android.view.LayoutInflater.createView(LayoutInflater.java:788)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:942)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:962)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1245)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at zs.f0.onCreateView(Unknown Source:9)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:24)
	at androidx.fragment.app.n0.f(Unknown Source:208)
	at androidx.fragment.app.n0.m(Unknown Source:124)
	at androidx.fragment.app.o0.t(Unknown Source:30)
	at androidx.fragment.app.FragmentManager.g1(Unknown Source:27)
	at androidx.fragment.app.FragmentManager.W(Unknown Source:9)
	at androidx.fragment.app.FragmentManager.B(Unknown Source:11)
	at androidx.fragment.app.v.c(Unknown Source:4)
	at androidx.fragment.app.s.onStart(Unknown Source:20)
	at androidx.appcompat.app.d.onStart(Unknown Source:0)
	at db.vendo.android.vendigator.view.main.MainActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1587)
	at android.app.Activity.performStart(Activity.java:8684)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3818)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

 `com.privateinternetaccess.android`:

```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023103100:user/release-keys
package: com.privateinternetaccess.android:591
process: com.privateinternetaccess.android:openvpn
processUptime: 618 + 303 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libwg-go.so" not found
	at com.privateinternetaccess.android.wireguard.util.SharedLibraryLoader.loadSharedLibrary(SharedLibraryLoader.java:104)
	at com.privateinternetaccess.android.wireguard.backend.GoBackend.<init>(GoBackend.java:166)
	at com.privateinternetaccess.android.PIAApplication.getBackend(PIAApplication.java:124)
	at com.privateinternetaccess.android.PIAApplication.getWireguard(PIAApplication.java:102)
	at com.privateinternetaccess.android.pia.impl.VPNImpl.isWireguardActive(VPNImpl.java:225)
	at com.privateinternetaccess.android.pia.impl.VPNImpl.isVPNActive(VPNImpl.java:213)
	at com.privateinternetaccess.android.pia.providers.ModuleClientStateProvider.metaEndpoints(ModuleClientStateProvider.kt:181)
	at com.privateinternetaccess.android.pia.providers.ModuleClientStateProvider.regionEndpoints(ModuleClientStateProvider.kt:97)
	at com.privateinternetaccess.regions.internals.Regions$fetchRegions$1.invokeSuspend(Regions.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libwg-go.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.privateinternetaccess.android.wireguard.util.SharedLibraryLoader.loadSharedLibrary(SharedLibraryLoader.java:81)
	... 20 more

```

`com.vsct.vsc.mobile.horaireetresa.android`:

```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023103100:user/release-keys
package: com.vsct.vsc.mobile.horaireetresa.android:2023102400
process: com.vsct.vsc.mobile.horaireetresa.android
processUptime: 2744 + 620 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(SourceFile:434)
	at io.flutter.embedding.engine.FlutterEngineGroup.<init>(SourceFile:7)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(SourceFile:145)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(SourceFile:8)
	at io.flutter.embedding.android.FlutterFragment.onAttach(SourceFile:12)
	at androidx.fragment.app.Fragment.performAttach(SourceFile:48)
	at androidx.fragment.app.d1.b(SourceFile:157)
	at androidx.fragment.app.d1.j(SourceFile:210)
	at androidx.fragment.app.FragmentManager.y(SourceFile:1013)
	at androidx.fragment.app.FragmentManager.N(SourceFile:82)
	at androidx.fragment.app.FragmentManager.w(SourceFile:76)
	at androidx.fragment.app.FragmentManager.t(SourceFile:63)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(SourceFile:15)
	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:21)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1587)
	at android.app.Activity.performStart(Activity.java:8684)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3818)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(SourceFile:45)
	... 30 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(SourceFile:14)
	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(SourceFile:4)
	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(SourceFile:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by nicohansi** [comment]
Here are a few more crahes, that I think are related. Unfortunately those bugs severely limit the useabilty of my device, since a lot of apps I have to use (for public transport, health insurance) are affected.
Does the label upstream mean those apps would also crash on stock Android 14?
I am doubtful about this, since there are so many apps that suddenly crash now.

```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231105.001/2023111500:user/release-keys
package: de.tk.tkapp:255
process: de.tk.tkapp
processUptime: 70 + 307 ms
installer: com.android.packageinstaller

java.lang.UnsatisfiedLinkError: No implementation found for int com.kobil.androidloader.NativeInterface.init(java.lang.String, boolean) (tried Java_com_kobil_androidloader_NativeInterface_init and Java_com_kobil_androidloader_NativeInterface_init__Ljava_lang_String_2Z) - is the library loaded, e.g. System.loadLibrary?
	at com.kobil.androidloader.NativeInterface.init(Native Method)
	at com.kobil.androidloader.AndroidLibLoader.b(Unknown Source:17)
	at com.kobil.androidloader.StageOne.onCreate(SourceFile:171)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7787)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7298)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7005)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231105.001/2023111500:user/release-keys
package: com.rise_world.epa.hkk.qu:20500064
process: com.rise_world.epa.hkk.qu
processUptime: 129 + 281 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to create application com.rise_world.epa.ProtectedEpaApplication: com.rise_world.epa.MessageGuardException_RFA6IDc1OCAwNjc5IFsyMDIzMDYxMy0yMDIzMDkwNTE3MTUgYjc6YXJtNjQtdjhhIDM0IGdvb2dsZS9yZWRmaW4vcmVkZmluOjE0L1VQMUEuMjMxMTA1LjAwMS8yMDIzMTExNTAwOnVzZXIvcmVsZWFzZS1rZXlzIGJsb2NrZWRd: DP: 758 0679
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7025)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: com.rise_world.epa.MessageGuardException_RFA6IDc1OCAwNjc5IFsyMDIzMDYxMy0yMDIzMDkwNTE3MTUgYjc6YXJtNjQtdjhhIDM0IGdvb2dsZS9yZWRmaW4vcmVkZmluOjE0L1VQMUEuMjMxMTA1LjAwMS8yMDIzMTExNTAwOnVzZXIvcmVsZWFzZS1rZXlzIGJsb2NrZWRd: DP: 758 0679
	at com.rise_world.epa.ProtectedEpaApplication.FEvekrBk(Unknown Source:2)
	at com.rise_world.epa.ProtectedEpaApplication.onCreate(Unknown Source:51)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1321)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7020)
	... 11 more
Caused by: java.lang.RuntimeException: DP: 758 0679
	at com.rise_world.epa.ProtectedEpaApplication.G(Native Method)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.rise_world.epa.ProtectedEpaApplication$EpaAppConfig.dykgmfq(Unknown Source:31)
	at com.rise_world.epa.ProtectedEpaApplication$EpaAppConfig.cmJHIo(Unknown Source:472)
	at com.rise_world.epa.ProtectedEpaApplication.G(Native Method)
	at com.rise_world.epa.ProtectedEpaApplication.onCreate(Unknown Source:46)
	... 13 more

```

```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231105.001/2023111500:user/release-keys
package: de.hkk.hkkApp:30000617
process: de.hkk.hkkApp
processUptime: 274 + 294 ms
installer: com.android.packageinstaller

java.lang.UnsatisfiedLinkError: dlopen failed: library "libchilkat.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at iam.mobile.sdk.android.core.p.<clinit>(Unknown Source:2)
	at iam.mobile.sdk.android.IAMMobileSDK.lambda$configureIAMSDKWithClientID$0(Unknown Source:10)
	at iam.mobile.sdk.android.IAMMobileSDK.a(Unknown Source:0)
	at iam.mobile.sdk.android.a.run(Unknown Source:14)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
These apps are incorrectly installed. You partially installed them by installing only the main APK of several split APKs.

**Comment by gsture** [comment]
Sure, how is it that the app in my bug report is not incorrectly installed? For as far as I know apps from aurora come directly from playstore.

**Comment by gsture** [comment]
> > Sure, how is it that the app in my bug report is incorrectly installed? For as far as I know apps from aurora come directly from playstore.
> 
> Make sure you're using the "Session installer" in Aurora Store. If it still doesn't work, try using the Play Store. There are cases in which Aurora Store cannot download the app properly.

What are you talking about? The app works fine. Except for the random pop ups that the app stopped working related to android.net.ConnectivityManager. I can not see how this has anything to do with the app not being installed properly.

**Comment by thestinger** [comment]
The issue you filed appears to be an app bug.

I was referring to all the errors posted by @nicohansi as being the apps being incorrectly installed.

**Comment by nicohansi** [comment]
Thanks for clearing this up for me and sorry for cluttering this issue with an unrelated problem.

**Comment by mmarchi123** [comment]
@thestinger , should I create a new crash topic?

**Comment by mmarchi123** [comment]
@thestinger the app was working until last week, I believe it started crashing after an OS update

**Comment by mmarchi123** [comment]
Sounds good, thank you for the fast repply
