### ISSUE TITLE
Launcher Crashes Every Time on Boot After Last Update 

### ISSUE THREAD

**Issue by nimdajitam** [GrapheneOS/os-issue-tracker#2654]
I get crash report below every time I rebood my device. No further problems during usage.

Device Info (Pixel 6):

Stable, 
14, 
6. oktober 2023,
g5123b-120690-230802-B-10596884,
slider-1.3-10674934,
5.10.198-android13-4-g57616f1b5f6f
#1 Sat Oct 28 00:21:27 UTC 2023,
UP1A.231005.007.2023103100.

Crash Report:

```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231005.007/2023103100:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 221429 + 719 ms

java.lang.NullPointerException: Attempt to invoke interface method 'org.thoughtcrime.securesms.recipients.LiveRecipientCache org.thoughtcrime.securesms.dependencies.ApplicationDependencies$Provider.provideRecipientCache()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2064)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1879)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1710)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1656)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1426)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1416)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1467)
	at com.android.launcher3.icons.ShortcutCachingLogic.getIcon(ShortcutCachingLogic.java:109)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:77)
	at com.android.launcher3.icons.ShortcutCachingLogic.loadIcon(ShortcutCachingLogic.java:43)
	at com.android.launcher3.icons.cache.BaseIconCache.addIconToDBAndMemCache(BaseIconCache.java:324)
	at com.android.launcher3.icons.cache.IconCacheUpdateHandler$SerializedIconUpdateTask.run(IconCacheUpdateHandler.java:294)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by thestinger** [comment]
This issue caused by Signal has been resolved for the next GrapheneOS release already.
