### ISSUE TITLE
Repetitive crash notifications from Sandboxed Google Play

### ISSUE THREAD

**Issue by MattRC7** [GrapheneOS/os-issue-tracker#2686]
I'm seeing crash notifications from Sandboxed Google Play. Restarting my system does not remedy the issue. I do not appear to have any pending updates from the system, Graphene Apps, Google Play Apps, or F-Droid Apps. I have not figured out what actions I'm taking that cause the crash yet.

Here is the crash log:

```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231105.003/2023110700:user/release-keys
package: com.google.android.gms:234414038
process: com.google.android.gms.persistent
processUptime: 52294 + 314 ms
installer: com.android.vending
GmsCompatConfig version: 83

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a127; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at avyb.sendBroadcastAsUser(:com.google.android.gms@234414038@23.44.14 (190400-580326705):6)
	at cvxh.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):38)
	at cvxj.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):11)
	at ajls.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):50)
	at ajls.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajqx.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
```

**Comment by nimdajitam** [comment]
I'm experiencing crashes too. Since last update (I'm on stable, Pixel 6). On request I can provide more details.

```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231105.003/2023110700:user/release-keys
package: com.google.android.gms:234414038
process: com.google.android.gms.persistent
processUptime: 57449833 + 285 ms
installer: com.android.vending
GmsCompatConfig version: 83

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cnen.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):455)
	at cnbn.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):9)
	at ajls.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):50)
	at ajls.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajqx.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a111; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bfxo.apply(:com.google.android.gms@234414038@23.44.14 (190400-580326705):5)
	at ebya.d(:com.google.android.gms@234414038@23.44.14 (190400-580326705):3)
	at ebyb.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a111; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cvxh.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):38)
	at cvxl.g(:com.google.android.gms@234414038@23.44.14 (190400-580326705):723)
	at cvxi.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):7)
	at cvxi.d(:com.google.android.gms@234414038@23.44.14 (190400-580326705):10)
	at cvxi.e(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hc(:com.google.android.gms@234414038@23.44.14 (190400-580326705):206)
	at bfxp.call(:com.google.android.gms@234414038@23.44.14 (190400-580326705):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14540)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14450)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15416)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```
