### ISSUE TITLE
"Sandboxed Google Play crashed"

### ISSUE THREAD

**Issue by akramer-zibra** [GrapheneOS/os-issue-tracker#2688]
Hey, any ideas about the following error? Google Play services are installed and run in sandboxed mode, but crashes recently. I did several reboots, but without any change. Device is Google Pixel 6a. 

`````
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231105.003/2023110700:user/release-keys
package: com.google.android.gms:234414038
process: com.google.android.gms.persistent
processUptime: 1152653 + 264 ms
installer: com.android.vending
GmsCompatConfig version: 83

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a142; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at avyb.sendBroadcastAsUser(:com.google.android.gms@234414038@23.44.14 (190400-580326705):6)
	at cvxh.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):38)
	at cvxj.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):11)
	at ajls.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):50)
	at ajls.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajqx.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)

```

Any help is appreciated. Thanks in advance.

**Comment by thestinger** [comment]
This is resolved for the next release and is a minor issue in practice which is why we didn't put out a release ASAP.

**Comment by akramer-zibra** [comment]
Oh great. Looking forward. Thank you very much
