### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by gh0st76** [GrapheneOS/os-issue-tracker#2695]
```
type: crash
osVersion: google/bramble/bramble:13/TQ3A.230805.001/2023090600:user/release-keys
package: com.google.android.gms:234414038
process: com.google.android.gms.persistent
processUptime: 59597065 + 1154 ms
installer: com.android.vending
GmsCompatConfig version: 83

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cnen.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):455)
	at cnbn.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):9)
	at ajls.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):50)
	at ajls.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at ajqx.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a131; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bfxo.apply(:com.google.android.gms@234414038@23.44.14 (190400-580326705):5)
	at ebya.d(:com.google.android.gms@234414038@23.44.14 (190400-580326705):3)
	at ebyb.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a131; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at avyb.sendBroadcastAsUser(:com.google.android.gms@234414038@23.44.14 (190400-580326705):6)
	at cvxh.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):38)
	at cvxl.g(:com.google.android.gms@234414038@23.44.14 (190400-580326705):723)
	at cvxi.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):7)
	at cvxi.d(:com.google.android.gms@234414038@23.44.14 (190400-580326705):10)
	at cvxi.e(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hc(:com.google.android.gms@234414038@23.44.14 (190400-580326705):206)
	at bfxp.call(:com.google.android.gms@234414038@23.44.14 (190400-580326705):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more

```

**Comment by thestinger** [comment]
You need to update to a current release. You're very behind on updates.
