### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by gh0st76** [GrapheneOS/os-issue-tracker#2696]
```
type: crash
osVersion: google/bramble/bramble:13/TQ3A.230805.001/2023090600:user/release-keys
package: com.google.android.gms:234414038
process: com.google.android.gms.persistent
processUptime: 1474947 + 273 ms
installer: com.android.vending
GmsCompatConfig version: 83

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a131; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at avyb.sendBroadcastAsUser(:com.google.android.gms@234414038@23.44.14 (190400-580326705):6)
	at cvxh.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):38)
	at cvxj.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):11)
	at ajls.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):50)
	at ajls.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at ajqx.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2270)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13751)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13703)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14581)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2304)


```

**Comment by thestinger** [comment]
You're multiple months behind on updates. You need to update. You probably had it installed but never rebooted.

**Comment by gh0st76** [comment]
I rebooting my phone almost every day.

**Comment by thestinger** [comment]
Check why you aren't receiving updates. If you disabled them, turn them back on. Perhaps you disabled notifications from the app or set it to only use network types you haven't been on.

**Comment by gh0st76** [comment]
Thank you very much for your analysis. I've identified problem already. I
have multiple user accounts for security reasons. I've created admin
account and after that my users account. I thought it will install updates
automaticaly, but when I am rebooting, I am usualy switching quickly to my
users account so admin won't get enough time for update download. Thank you
for your good job and good luck.
