### ISSUE TITLE
System crash after opening 

### ISSUE THREAD

**Issue by blaugrau3001** [GrapheneOS/os-issue-tracker#2720]
Graphenebuild: UP1A.231105.003.2023112600
Signal PNP build: Version 6.42.0-nightlyPnp-2023-11-27-16-11-12

Signal is installed in work profile threw Shelter

When I tested the new Signal PNP version I got a system crash after opening a notification in a bubble. I looked in the logs and found a system ui crash so I report it here but also at Signal, if my interpretation is wrong.
```
FATAL EXCEPTION: AsyncTask #1
Process: com.android.systemui, PID: 29944
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Permission Denial: opening provider org.thoughtcrime.securesms.providers.AvatarProvider from ProcessRecord{e78c3 29944:com.android.systemui/u0a106} (pid=29944, uid=10106) that is not exported from UID 10193
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5921)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7332)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3732)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2568)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2048)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1879)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1710)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1656)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1426)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1416)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1467)
	at com.android.wm.shell.bubbles.BubbleViewInfoTask$BubbleViewInfo.populate(go/retraceme 6cd796b39b904f0dbeb4e2c9587b4b770a6377b3459c26933f9b02b0cef86e8b:144)
	at com.android.wm.shell.bubbles.BubbleViewInfoTask.doInBackground(go/retraceme 6cd796b39b904f0dbeb4e2c9587b4b770a6377b3459c26933f9b02b0cef86e8b:27)
	at com.android.wm.shell.bubbles.BubbleViewInfoTask.doInBackground(go/retraceme 6cd796b39b904f0dbeb4e2c9587b4b770a6377b3459c26933f9b02b0cef86e8b:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:691)
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:287)
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:144)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6789)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2769)
```

I can provide more Info if needed.

Reproduction:
- write yourself a message to the Signal PNP client or from someone else
- get the notification with the content displaying
- press the bubble button
- the crash should happen than

**Comment by muhomorr** [comment]
This is an upstream bug.

**Comment by blaugrau3001** [comment]
This bug seems to not be there anymore on build 14 (UQ1A.231205.015) and Signal build Version 6.43.0-nightly-2023-12-15-17-00-17
