### ISSUE TITLE
system_server crash: null pointer exception in com.android.wifi.x.android.hardware.wifi

### ISSUE THREAD

**Issue by jonhermansen** [GrapheneOS/os-issue-tracker#2735]
Upgraded to the latest alpha (2023112600) on my Pixel 6a yesterday, and today my phone rebooted and reported this crash:

```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UP1A.231105.003/2023112600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'com.android.wifi.x.android.hardware.wifi.StaBackgroundScanCapabilities com.android.wifi.x.android.hardware.wifi.IWifiStaIface.getBackgroundScanCapabilities()' on a null object reference
	at com.android.server.wifi.hal.WifiStaIfaceAidlImpl.getBackgroundScanCapabilities(WifiStaIfaceAidlImpl.java:243)
	at com.android.server.wifi.hal.WifiStaIface.lambda$getBackgroundScanCapabilities$6(WifiStaIface.java:202)
	at com.android.server.wifi.hal.WifiStaIface.$r8$lambda$_EbJ5ihVCnh9jcPe1DVklmaHw0c(WifiStaIface.java:0)
	at com.android.server.wifi.hal.WifiStaIface$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:0)
	at com.android.server.wifi.hal.WifiStaIface.validateAndCall(WifiStaIface.java:142)
	at com.android.server.wifi.hal.WifiStaIface.getBackgroundScanCapabilities(WifiStaIface.java:201)
	at com.android.server.wifi.WifiVendorHal.getBgScanCapabilities(WifiVendorHal.java:579)
	at com.android.server.wifi.WifiNative.getBgScanCapabilities(WifiNative.java:3174)
	at com.android.server.wifi.scanner.WifiScannerImpl$1.create(WifiScannerImpl.java:63)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.setupScannerImpls(WifiScanningServiceImpl.java:741)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.lambda$setScanningEnabled$1(WifiScanningServiceImpl.java:204)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.$r8$lambda$D_ymntbRb7H5O15mR0WYDlVLPp0(WifiScanningServiceImpl.java:0)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by jonhermansen** [comment]
I now see there is an update (2023112900), I will see if I can replicate it there as well.

Just before the crash occurred, I realized I was disconnected from my auto-connect wifi AP, and I clicked on the Wi-Fi quick tile...

**Comment by thestinger** [comment]
Not related to the update.

**Comment by jonhermansen** [comment]
> Not related to the update.

Thank you for all of your hard work, @thestinger.

I updated to 2023112900 and still see it. Before that, I was on 2023111500, and I did not see it there.

Also, I looked on the Google issue tracker for bugs that might be related. I wasn't able to find anything public. If I can find more details or replicate the issue reliably, I will report back here.

**Comment by jonhermansen** [comment]
> > > Not related to the update.
> > 
> > 
> > Thank you for all of your hard work, @thestinger.
> > I updated to 2023112900 and still see it. Before that, I was on 2023111500, and I did not see it there.
> > Also, I looked on the Google issue tracker for bugs that might be related. I wasn't able to find anything public. If I can find more details or replicate the issue reliably, I will report back here.
> 
> Reason you didn't see these crashes before is because it's the latest two releases that introduced these crash reports in the first place. This was likely happening before, but you just didn't get the crash. On the latest release, I believe you have to opt into seeing these crashes via a toggle in Settings > Security. In most cases, the bugs uncovered by this will be upstream bugs.

@matchboxbananasynergy Thank you. Yes, I have enabled secure app spawning, disabled native code execution for third-party apps, and  some additional debug flags enabled in developer settings.

**Comment by thestinger** [comment]
Please reopen if this still happens with the 2023120701 release.

**Comment by jonhermansen** [comment]
> Please reopen if this still happens with the 2023120701 release.

@thestinger It just happened to me again on 2023120701.

```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.231205.015/2023120701:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'com.android.wifi.x.android.hardware.wifi.StaBackgroundScanCapabilities com.android.wifi.x.android.hardware.wifi.IWifiStaIface.getBackgroundScanCapabilities()' on a null object reference
	at com.android.server.wifi.hal.WifiStaIfaceAidlImpl.getBackgroundScanCapabilities(WifiStaIfaceAidlImpl.java:243)
	at com.android.server.wifi.hal.WifiStaIface.lambda$getBackgroundScanCapabilities$6(WifiStaIface.java:202)
	at com.android.server.wifi.hal.WifiStaIface.$r8$lambda$_EbJ5ihVCnh9jcPe1DVklmaHw0c(WifiStaIface.java:0)
	at com.android.server.wifi.hal.WifiStaIface$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:0)
	at com.android.server.wifi.hal.WifiStaIface.validateAndCall(WifiStaIface.java:142)
	at com.android.server.wifi.hal.WifiStaIface.getBackgroundScanCapabilities(WifiStaIface.java:201)
	at com.android.server.wifi.WifiVendorHal.getBgScanCapabilities(WifiVendorHal.java:579)
	at com.android.server.wifi.WifiNative.getBgScanCapabilities(WifiNative.java:3174)
	at com.android.server.wifi.scanner.WifiScannerImpl$1.create(WifiScannerImpl.java:63)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.setupScannerImpls(WifiScanningServiceImpl.java:741)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.lambda$setScanningEnabled$1(WifiScanningServiceImpl.java:204)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.$r8$lambda$D_ymntbRb7H5O15mR0WYDlVLPp0(WifiScanningServiceImpl.java:0)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

Still not sure exactly how to reproduce it, but here's a rough idea of what I did...

1. Boot the phone, connect to wifi, wait 12+ hours
2. Go out of range from the wifi network for an hour
3. Come back in range, click on Wi-Fi quick tile

Immediately after clicking on the tile, the crash occurs and the phone reboots. I guess that must be normal for a system_server crash?

**Comment by jonhermansen** [comment]
In case it is helpful, I also have these developer settings enabled:

- Enable Wi-Fi Verbose Logging
- Wi-Fi scan throttling
- Wi-Fi non-persistent MAC randomization

**Comment by thestinger** [comment]
> Wi-Fi non-persistent MAC randomization

It doesn't make sense to use this on GrapheneOS which has per-connection MAC randomization and DHCP state by default. That only makes the per-network persistent random MAC addresses expire eventually (on DHCP lease expiry and reboot).

**Comment by jonhermansen** [comment]
I believe these issues are duplicates: #2779, #2853, #2888

**Comment by phoropter** [comment]
I am also encountering this on 2023121200 on husky. It occurs occasionally when I either try to toggle airplane mode or wifi while in airplane mode. Appears to be the same error as in the initial post:

```
type: crash
Process: system_server
Build: google/husky/husky:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'com.android.wifi.x.android.hardware.wifi.StaBackgroundScanCapabilities com.android.wifi.x.android.hardware.wifi.IWifiStaIface.getBackgroundScanCapabilities()' on a null object reference
	at com.android.server.wifi.hal.WifiStaIfaceAidlImpl.getBackgroundScanCapabilities(WifiStaIfaceAidlImpl.java:243)
	at com.android.server.wifi.hal.WifiStaIface.lambda$getBackgroundScanCapabilities$6(WifiStaIface.java:202)
	at com.android.server.wifi.hal.WifiStaIface.$r8$lambda$_EbJ5ihVCnh9jcPe1DVklmaHw0c(WifiStaIface.java:0)
	at com.android.server.wifi.hal.WifiStaIface$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:0)
	at com.android.server.wifi.hal.WifiStaIface.validateAndCall(WifiStaIface.java:142)
	at com.android.server.wifi.hal.WifiStaIface.getBackgroundScanCapabilities(WifiStaIface.java:201)
	at com.android.server.wifi.WifiVendorHal.getBgScanCapabilities(WifiVendorHal.java:579)
	at com.android.server.wifi.WifiNative.getBgScanCapabilities(WifiNative.java:3174)
	at com.android.server.wifi.scanner.WifiScannerImpl$1.create(WifiScannerImpl.java:63)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.setupScannerImpls(WifiScanningServiceImpl.java:741)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.lambda$setScanningEnabled$1(WifiScanningServiceImpl.java:204)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.$r8$lambda$D_ymntbRb7H5O15mR0WYDlVLPp0(WifiScanningServiceImpl.java:0)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by jonhermansen** [comment]
@phoropter You're not alone, it still happens to me on 2023121200 too.

**Comment by joshiegy** [comment]
@jonhermansen same here. Close to every day.

**Comment by thestinger** [comment]
It will likely be fixed in a monthly Android release soon, perhaps January.

**Comment by jriberg** [comment]
```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240105.004/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Lost network stack. This is not the root cause of any issue, it is a side effect of a crash that happened earlier. Earlier logs should point to the actual issue.
	at android.net.ConnectivityModuleConnector.maybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:335)
	at android.net.ConnectivityModuleConnector.-$$Nest$mmaybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:0)
	at android.net.ConnectivityModuleConnector$ModuleServiceConnection.onServiceDisconnected(ConnectivityModuleConnector.java:278)
	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2227)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2242)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:981)
	at com.android.server.SystemServer.main(SystemServer.java:667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

Happened again :/

**Comment by thestinger** [comment]
@jriberg That's an entirely different issue and not related.
