### ISSUE TITLE
Repeated system_server crashes while plugged into desktop PC via USB.

### ISSUE THREAD

**Issue by slap-tree-butts** [GrapheneOS/os-issue-tracker#2749]
I noticed my Pixel 7 Pro crashing multiple times over a few hours of PC usage due to the USB connect/disconnect sound while having the phone plugged in to slow charge. I would estimate crashes occurred at 40 to 60 minute intervals, and I was not interacting with the phone at all during this time.

Each time the crash had the same exception message (Cannot change userId) but I didn't look too closely at the full trace.

After the first few soft restart events I manually restarted the phone to apply the pending update. The update worked normally but did not prevent or modify further crashes.

This crashing did not occur previously on the same PC just over one week ago and nothing on the PC side should have changed. Same USB-A to USB-C cable, same USB-A port. Motherboard is MSI PRO Z790-P WIFI for reference.

As far as I can tell the phone does not crash while unplugged from the PC and does not crash while charging from a "dumb" USB-C power supply.

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UP1A.231105.003/2023112900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalArgumentException: Cannot change userId for '/data/user/10/com.google.android.gms/app_dg_cache/E196E411A243C94E9BD7A6FD257F29BF601B64FA/the.apk' from 0 to 10
	at com.android.server.pm.dex.PackageDynamicCodeLoading$PackageDynamicCode.add(PackageDynamicCodeLoading.java:542)
	at com.android.server.pm.dex.PackageDynamicCodeLoading$PackageDynamicCode.-$$Nest$madd(PackageDynamicCodeLoading.java:0)
	at com.android.server.pm.dex.PackageDynamicCodeLoading.record(PackageDynamicCodeLoading.java:122)
	at com.android.server.pm.dex.DynamicCodeLogger.recordDex(DynamicCodeLogger.java:232)
	at com.android.server.pm.DynamicCodeLoggingService.syncDataFromArtService(DynamicCodeLoggingService.java:158)
	at com.android.server.pm.DynamicCodeLoggingService.-$$Nest$smsyncDataFromArtService(DynamicCodeLoggingService.java:0)
	at com.android.server.pm.DynamicCodeLoggingService$IdleLoggingThread.run(DynamicCodeLoggingService.java:181)
```

**Comment by thestinger** [comment]
@slap-tree-butts Do you still have an issue with the [2023120701](https://grapheneos.org/releases#2023120701) release?
