### ISSUE TITLE
Repeated kernel crashes and restarts

### ISSUE THREAD

**Issue by johannes-qvarford** [GrapheneOS/os-issue-tracker#2751]
Kernel has crashed 2 times with a crash report the last couple of days. The device has restarted multiple times a day, but no explicit crash reports were created those times.

Here is the latest crash report (too big to paste inline): https://pastebin.com/tkkU9Pvp

Thank you for all your hard work.

**Comment by thestinger** [comment]
Do you know what triggers it?

**Comment by thestinger** [comment]
Please reopen if it still happens on the 2023120701 release.

**Comment by L11R** [comment]
It still happens to me.

It's usually crashes without an option to send logs, but here is the one I can:

```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: Unable to create process group for app.vanadium.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:1 (2678)
	at com.android.server.am.ProcessList.startProcess(ProcessList.java:2486)
	at com.android.server.am.ProcessList.lambda$handleProcessStart$1(ProcessList.java:2115)
	at com.android.server.am.ProcessList.$r8$lambda$x51oUQi6HPNnzxQPaHbqHBYY3LQ(ProcessList.java:0)
	at com.android.server.am.ProcessList$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:0)
	at com.android.server.am.ProcessList.handleProcessStart(ProcessList.java:2141)
	at com.android.server.am.ProcessList.lambda$startProcessLocked$0(ProcessList.java:2081)
	at com.android.server.am.ProcessList.$r8$lambda$rd0BXPgECSWG21Kr8GWdMphFRuo(ProcessList.java:0)
	at com.android.server.am.ProcessList$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

**Comment by L11R** [comment]
Also I want to address that everytime graphic shell crashes, Auditor app fails to audit, until I reboot the phone completely.

**Comment by thestinger** [comment]
@L11R The crash report you attached isn't a kernel crash.

**Comment by L11R** [comment]
@thestinger yes, sorry, I didn't wanted to spam new issues, because as far as I understand it's a common issue after the December Update. Also it's hard to distinguish kernel and shell crashes: in the fist case it just take longer to reboot.

Happened again after night, btw.

I would create a general one: kernel and shell _(I don't know how in Android an alternative for Linux DE calls)_ crashes.

**Comment by thestinger** [comment]
It's only because we recently adding logging for kernel and system_server crashes where people would previously just call it a random reboot.

**Comment by L11R** [comment]
@thestinger well, maybe I had crashes before this logging has been added. But I don't remember that my phone randomly showed up GrapheneOS logo multiple times during day. Also it reboots (kernel or shell) just in my hands, while I casually using phone. It's definitely something that I didn't meet.

**Comment by thestinger** [comment]
If you have a crash, please file an issue about it. The crash above is not a kernel crash. Separate issues for separate crashes please.
