### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by hheitgre** [GrapheneOS/os-issue-tracker#2764]
```
type: crash
Process: unknown
Build: google/oriole/oriole:14/UP1A.231105.003/2023112900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: java.lang.IllegalStateException: User 11 must be unlocked for widgets to be available
	at com.android.launcher3.widget.LauncherWidgetHolder.startListening(LauncherWidgetHolder.java:109)
	at com.android.launcher3.widget.LauncherWidgetHolder.setShouldListenFlag(LauncherWidgetHolder.java:478)
	at com.android.launcher3.widget.LauncherWidgetHolder.setActivityStarted(LauncherWidgetHolder.java:151)
	at com.android.launcher3.Launcher.onStart(Launcher.java:1091)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1587)
	at android.app.Activity.performStart(Activity.java:8684)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3818)
	at android.app.servertransaction.StartActivityItem.execute(StartActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: User 11 must be unlocked for widgets to be available
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.startListening(IAppWidgetService.java:693)
	at android.appwidget.AppWidgetHost.startListening(AppWidgetHost.java:231)
	at com.android.launcher3.widget.LauncherWidgetHolder.startListening(LauncherWidgetHolder.java:106)
	... 20 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl.ensureGroupStateLoadedLocked(AppWidgetServiceImpl.java:650)
	at com.android.server.appwidget.AppWidgetServiceImpl.ensureGroupStateLoadedLocked(AppWidgetServiceImpl.java:644)
	at com.android.server.appwidget.AppWidgetServiceImpl.startListening(AppWidgetServiceImpl.java:780)
	at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:310)
	at android.os.Binder.execTransactInternal(Binder.java:1368)


```

**Comment by dev0T** [comment]
Just had the same thing happen while attempting to unlock my Pixel 8 Pro with fingerprint.

````
type: crash
Process: system_server
Build: google/husky/husky:14/UD1A.231105.004/2023112900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

android.view.Surface$OutOfResourcesException: NO_MEMORY
	at android.view.SurfaceControl.nativeCreate(Native Method)
	at android.view.SurfaceControl.<init>(SurfaceControl.java:1235)
	at android.view.SurfaceControl.<init>(Unknown Source:0)
	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:908)
	at com.android.server.wm.Transition.calculateTransitionRoots(Transition.java:2323)
	at com.android.server.wm.Transition.calculateTransitionInfo(Transition.java:2343)
	at com.android.server.wm.Transition.onTransactionReady(Transition.java:1457)
	at com.android.server.wm.BLASTSyncEngine$SyncGroup.finishNow(BLASTSyncEngine.java:263)
	at com.android.server.wm.BLASTSyncEngine$SyncGroup.onTimeout(BLASTSyncEngine.java:389)
	at com.android.server.wm.BLASTSyncEngine$SyncGroup.lambda$new$0(BLASTSyncEngine.java:144)
	at com.android.server.wm.BLASTSyncEngine$SyncGroup.$r8$lambda$eTAyejDPssWpGCiN-35gZ_pXMoI(BLASTSyncEngine.java:0)
	at com.android.server.wm.BLASTSyncEngine$SyncGroup$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

````

**Comment by h2dden** [comment]
same here on 8pro

```
type: crash
Process: system_server
Build: google/husky/husky:14/UD1A.[231105.004](tel:231105.004)/[2023120400](tel:2023120400):user/release-keys
Crash-Handler: [com.android.internal.os.RuntimeInit](http://com.android.internal.os.runtimeinit/)$KillApplicationHandler
Loading-Progress: [1.0](tel:1.0)
Dropped-Count: 0

[java.util.concurrent.RejectedExecutionException](http://java.util.concurrent.rejectedexecutionexception/): Task [java.util.concurrent.ScheduledThreadPoolExecutor](http://java.util.concurrent.scheduledthreadpoolexecutor/)$ScheduledFutureTask@78ca3d4[Not completed] rejected from [java.util.concurrent.ScheduledThreadPoolExecutor](http://java.util.concurrent.scheduledthreadpoolexecutor/)@ac[4897](tel:4897)d[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = [202](tel:202)]
at [java.util.concurrent.ThreadPoolExecutor](http://java.util.concurrent.threadpoolexecutor/)$[AbortPolicy.rejectedExecution](http://abortpolicy.rejectedexecution/)([ThreadPoolExecutor.java:2082](http://threadpoolexecutor.java:2082/))
at [java.util.concurrent.ThreadPoolExecutor.reject](http://java.util.concurrent.threadpoolexecutor.reject/)([ThreadPoolExecutor.java:842](http://threadpoolexecutor.java:842/))
at [java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute](http://java.util.concurrent.scheduledthreadpoolexecutor.delayedexecute/)([ScheduledThreadPoolExecutor.java:345](http://scheduledthreadpoolexecutor.java:345/))
at [java.util.concurrent.ScheduledThreadPoolExecutor.schedule](http://java.util.concurrent.scheduledthreadpoolexecutor.schedule/)([ScheduledThreadPoolExecutor.java:569](http://scheduledthreadpoolexecutor.java:569/))
at [java.util.concurrent.Executors](http://java.util.concurrent.executors/)$[DelegatedScheduledExecutorService.schedule](http://delegatedscheduledexecutorservice.schedule/)([Executors.java:770](http://executors.java:770/))
at [com.android.server.power.stats.BatteryExternalStatsWorker.scheduleCleanupDueToRemovedUser](http://com.android.server.power.stats.batteryexternalstatsworker.schedulecleanupduetoremoveduser/)([BatteryExternalStatsWorker.java:345](http://batteryexternalstatsworker.java:345/))
at [com.android.server.power.stats.BatteryStatsImpl.onUserRemovedLocked](http://com.android.server.power.stats.batterystatsimpl.onuserremovedlocked/)([BatteryStatsImpl.java:15040](http://batterystatsimpl.java:15040/))
at [com.android.server.am.BatteryStatsService.lambda](http://com.android.server.am.batterystatsservice.lambda/)$onUserRemoved$6([BatteryStatsService.java:715](http://batterystatsservice.java:715/))
at [com.android.server.am.BatteryStatsService](http://com.android.server.am.batterystatsservice/).$r8$lambda$7VDvHexgqszdbOz_VQFie1GweuQ([BatteryStatsService.java:0](http://batterystatsservice.java:0/))
at [com.android.server.am.BatteryStatsService](http://com.android.server.am.batterystatsservice/)$$[ExternalSyntheticLambda90.run](http://externalsyntheticlambda90.run/)(R8$$SyntheticClass:0)
at [android.os.Handler.handleCallback](http://android.os.handler.handlecallback/)([Handler.java:958](http://handler.java:958/))
at [android.os.Handler.dispatchMessage](http://android.os.handler.dispatchmessage/)([Handler.java:99](http://handler.java:99/))
at [android.os.Looper.loopOnce](http://android.os.looper.looponce/)([Looper.java:205](http://looper.java:205/))
at [android.os.Looper.loop](http://android.os.looper.loop/)([Looper.java:294](http://looper.java:294/))
at [android.os.HandlerThread.run](http://android.os.handlerthread.run/)([HandlerThread.java:67](http://handlerthread.java:67/))

```

**Comment by h2dden** [comment]
just rebooted after the latest update:


```
type: crash
osVersion: google/husky/husky:14/UQ1A.[231205.015](tel:231205.015)/[2023120701](tel:2023120701):user/release-keys
uid: [1000](tel:1000) (u:r:surfaceflinger:s0)
cmdline: /system/bin/surfaceflinger
processUptime: [134](tel:134)s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr [200](tel:200)c8b[985](tel:985)c38f49
threadName: surfaceflinger
MTE: enabled

backtrace:
    /system/bin/surfaceflinger (android::SurfaceFlinger::commit(android::PhysicalDisplayId, android::ftl::SmallMap<android::PhysicalDisplayId, android::scheduler::FrameTarget const*, 3ul, std::__1::equal_to<android::PhysicalDisplayId> > const&)+[800](tel:800), pc 20ef60)
    /system/bin/surfaceflinger (android::scheduler::Scheduler::onFrameSignal(android::ICompositor&, android::VsyncId, android::TimePoint)+[364](tel:364), pc 1ee39c)
    /system/lib64/[libutils.so](http://libutils.so/) (android::Looper::pollInner(int)+[376](tel:376), pc 18b08)
    /system/lib64/[libutils.so](http://libutils.so/) (android::Looper::pollOnce(int, int*, int*, void**)+[124](tel:124), pc [1892](tel:1892)c)
    /system/bin/surfaceflinger (android::impl::MessageQueue::waitMessage()+92, pc 1deefc)
    /system/bin/surfaceflinger (android::scheduler::Scheduler::run()+28, pc 1ee21c)
    /system/bin/surfaceflinger (main[+1792](tel:+1792), pc 25b[920](tel:920))
    /apex/[com.android.runtime/lib64/bionic/libc.so](http://com.android.runtime/lib64/bionic/libc.so) (__libc_init+[104](tel:104), pc 5ad08)
```

**Comment by thestinger** [comment]
@h2dden That's not the same thing, please open a new issue about it.
