### ISSUE TITLE
Contact Scopes does not work as expected

### ISSUE THREAD

**Issue by PatrykMis** [GrapheneOS/os-issue-tracker#2766]
**To reproduce:**

1. Choose an app capable of obtaining Contacts permission. Open the app info.
2. Tap Permissions and then Contacts.
3. Tap Contact Scopes and try to enable.
4. The following crash occurs (not reproducible on Android versions prior to 14):

```
type: crash
osVersion: google/shiba/shiba:14/UD1A.231105.004/2023112600:user/release-keys
package: com.android.permissioncontroller:330000000
process: com.android.permissioncontroller
processUptime: 36492 + 296 ms

java.lang.IllegalArgumentException: Unknown authority com.android.contacts.scoped
	at android.content.ContentResolver.call(ContentResolver.java:2487)
	at com.android.permissioncontroller.cscopes.ContactScopesFragment.callScopedContactsProvider(ContactScopesFragment.kt:279)
	at com.android.permissioncontroller.cscopes.ContactScopesFragment.callScopedContactsProvider$default(ContactScopesFragment.kt:278)
	at com.android.permissioncontroller.cscopes.ContactScopesFragment.updateCategories(ContactScopesFragment.kt:144)
	at com.android.permissioncontroller.cscopes.ContactScopesFragment.update(ContactScopesFragment.kt:117)
	at com.android.permissioncontroller.ext.BaseSettingsWithLargeHeaderFragment.onResume(BaseSettingsWithLargeHeaderFragment.kt:33)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:3191)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:643)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:296)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1451)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3029)
	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2961)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:3200)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:643)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:296)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:664)
	at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.kt:587)
	at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.kt:774)
	at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.kt:150)
	at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.kt:101)
	at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.kt:234)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1951)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1841)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1778)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:564)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

After opening the app, I can choose any contact.

**Comment by muhomorr** [comment]
It looks like the "Contacts Storage" system package is disabled (`com.android.providers.contacts`).

I'm unable to reproduce this issue unless this package is disabled.

**Comment by PatrykMis** [comment]
Can't reproduce on latest OS too, but I am sure `com.android.providers.contacts` had not been disabled.
