### ISSUE TITLE
Sandbox google play crashed 

### ISSUE THREAD

**Issue by Timchaos** [GrapheneOS/os-issue-tracker#2773]
Hello
My Problem at the last time 

```
type: crash
osVersion: google/raven/raven:14/UP1A.231105.003/2023120400:user/release-keys
package: com.google.android.gms:234522038
process: com.google.android.gms.persistent
processUptime: 1968 + 862 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 85

java.lang.SecurityException: AlarmManager.setPrioritized: uid 1010132 does not have android.permission.SCHEDULE_PRIORITIZED_ALARM.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:311)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1093)
	at android.app.AlarmManager.setPrioritized(AlarmManager.java:754)
	at awzr.c(:com.google.android.gms@234522038@23.45.22 (190400-586842901):22)
	at awzl.h(:com.google.android.gms@234522038@23.45.22 (190400-586842901):62)
	at awze.b(:com.google.android.gms@234522038@23.45.22 (190400-586842901):65)
	at awsz.run(:com.google.android.gms@234522038@23.45.22 (190400-586842901):120)
	at ajng.c(:com.google.android.gms@234522038@23.45.22 (190400-586842901):50)
	at ajng.run(:com.google.android.gms@234522038@23.45.22 (190400-586842901):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234522038@23.45.22 (190400-586842901):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.gcm-GcmChimeraService_onStartCommand(Unknown Source:0)

```

I can't open the play store and other apps 
How can it fix it?

**Comment by thestinger** [comment]
@Timchaos Did you trigger this a specific way?

**Comment by Timchaos** [comment]
No..last week the Problem was there and i dont do anything

**Comment by thestinger** [comment]
I mean is anything specific happening when this triggers. When does it happen? Does it just happen in the background, when you do something specific or is it constantly chain crashing to the point it's unusable? Do you notice that it happens?

**Comment by Timchaos** [comment]
When I want to open an app, for example the play store, I see it open briefly and then the app closes again and I can no longer open it.
Sometimes I get a message saying "Sandbox Google play crashed" 
And this happens most often when I want to open apps that "need" Google

**Comment by thestinger** [comment]
@Timchaos Have you granted Unrestricted battery mode to Play services?

**Comment by Timchaos** [comment]
No..all play services are in the optimised mode

**Comment by Timchaos** [comment]
That works great, but why is it like that now? I have had graphene for almost a year and this has never been a problem

Thanks for the help

**Comment by thestinger** [comment]
@Timchaos They must have added a new dependency on it and we'll have to work around it.

**Comment by thestinger** [comment]
I think it can be left open since we could avoid the crash when it's not granted.

**Comment by thestinger** [comment]
@Timchaos This should be resolved by GmsCompatConfig v86 which is currently in the Alpha and Beta channels of the app repository. It will be in the Stable channel very soon. We also have a more complete approach to prevent future issues like this one included in today's release of the OS.

**Comment by Timchaos** [comment]
Thank you for the quick help and for quickly resolving the problem
