### ISSUE TITLE
Gms crash

### ISSUE THREAD

**Issue by cybern0id** [GrapheneOS/os-issue-tracker#2778]
Appreciate my pixel 3 no longer supported so please close this ticket if deemed of no interest.

I am using 'Shelter' to implement a work profile; not sure if that is pertinent.

Crash report as follows:
```
type: crash
osVersion: google/blueline/blueline:12/SP1A.210812.016.C2/2023020600:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 1406 ms
GmsCompatConfig version: 86

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a103; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
	at android.os.Parcel.createException(Parcel.java:2420)
	at android.os.Parcel.readException(Parcel.java:2396)
	at android.os.Parcel.readException(Parcel.java:2338)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5727)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1456)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1423)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:578)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:578)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhg.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):29)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.NotifyInitializationPossible(Unknown Source:0)
		at tk_trace.time-TimeModuleInitIntentOperation_onHandleIntentWithRedelivery(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2136)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12930)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12882)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:13720)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2351)


```

**Comment by cybern0id** [comment]
Of course and completely understood. Hoping Father Christmas might be nice and bring me a second hand 6 or 7..... 🎅 
Love GrapheneOS and all that you all do to keep it alive.
