### ISSUE TITLE
Random restarts of the system ui

### ISSUE THREAD

**Issue by joshiegy** [GrapheneOS/os-issue-tracker#2779]
The display goes to the lockscreen, turns screen off, then on, then off a few times followed by me needing to login again.
I didn't do anything special this time, just unlocked the phone.

Here's the crashlog.

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UP1A.231105.003/2023120400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'com.android.wifi.x.android.hardware.wifi.StaBackgroundScanCapabilities com.android.wifi.x.android.hardware.wifi.IWifiStaIface.getBackgroundScanCapabilities()' on a null object reference
	at com.android.server.wifi.hal.WifiStaIfaceAidlImpl.getBackgroundScanCapabilities(WifiStaIfaceAidlImpl.java:243)
	at com.android.server.wifi.hal.WifiStaIface.lambda$getBackgroundScanCapabilities$6(WifiStaIface.java:202)
	at com.android.server.wifi.hal.WifiStaIface.$r8$lambda$_EbJ5ihVCnh9jcPe1DVklmaHw0c(WifiStaIface.java:0)
	at com.android.server.wifi.hal.WifiStaIface$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:0)
	at com.android.server.wifi.hal.WifiStaIface.validateAndCall(WifiStaIface.java:142)
	at com.android.server.wifi.hal.WifiStaIface.getBackgroundScanCapabilities(WifiStaIface.java:201)
	at com.android.server.wifi.WifiVendorHal.getBgScanCapabilities(WifiVendorHal.java:579)
	at com.android.server.wifi.WifiNative.getBgScanCapabilities(WifiNative.java:3174)
	at com.android.server.wifi.scanner.WifiScannerImpl$1.create(WifiScannerImpl.java:63)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.setupScannerImpls(WifiScanningServiceImpl.java:741)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.lambda$setScanningEnabled$1(WifiScanningServiceImpl.java:204)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.$r8$lambda$D_ymntbRb7H5O15mR0WYDlVLPp0(WifiScanningServiceImpl.java:0)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by thestinger** [comment]
Please reopen if it still happens on the 2023120701 release.

**Comment by thestinger** [comment]
Closing as duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2735.
