### ISSUE TITLE
System periodically starts to glitch then proceeds to crash and reboot

### ISSUE THREAD

**Issue by vanindm** [GrapheneOS/os-issue-tracker#2781]
```
type: crash
Process: system_server
Build: google/raven/raven:14/UP1A.231105.003/2023112900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 4811712 free bytes and 4698KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at android.content.ComponentName.readFromParcel(ComponentName.java:382)
	at android.content.Intent.readFromParcel(Intent.java:11849)
	at android.content.Intent.<init>(Intent.java:11839)
	at android.content.Intent$1.createFromParcel(Intent.java:11827)
	at android.content.Intent$1.createFromParcel(Intent.java:11825)
	at android.os.Parcel.readTypedObject(Parcel.java:4045)
	at android.os.Parcel.createTypedArray(Parcel.java:4006)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3249)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2724)
	at android.os.Binder.execTransactInternal(Binder.java:1368)
	at android.os.Binder.execTransact(Binder.java:1299)

```

**Comment by thestinger** [comment]
Please reopen if it still happens on the 2023120701 release.
