### ISSUE TITLE
system_server crash - NullPointerException on BiometricService

### ISSUE THREAD

**Issue by RxnNode** [GrapheneOS/os-issue-tracker#2783]
The exception happened when attempting to unlock Pixel 8 Pro with fingerprint. 
I'm unable to reproduce this issue, but it happened several times after the latest update.

```
type: crash
Process: system_server
Build: google/husky/husky:14/UD1A.231105.004/2023120400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.biometrics.BiometricService$EnabledOnKeyguardCallback.notify(boolean, int)' on a null object reference
	at com.android.server.biometrics.BiometricService$SettingObserver.notifyEnabledOnKeyguardCallbacks(BiometricService.java:390)
	at com.android.server.biometrics.BiometricService$3.onUserSwitchComplete(BiometricService.java:1060)
	at com.android.server.am.UserController.dispatchUserSwitchComplete(UserController.java:2009)
	at com.android.server.am.UserController.handleMessage(UserController.java:3172)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

**Comment by thestinger** [comment]
Please reopen if it still happens on the 2023120701 release.
