### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by c-key** [GrapheneOS/os-issue-tracker#2784]
Got this error after unlock.
```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UP1A.231105.003/2023120400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: User 10 is locked or not running
	at com.android.server.pm.ShortcutService.throwIfUserLockedL(ShortcutService.java:1326)
	at com.android.server.pm.ShortcutService$LocalService.getShortcuts(ShortcutService.java:2971)
	at com.android.server.people.data.DataManager.getShortcuts(DataManager.java:758)
	at com.android.server.people.data.DataManager.getShortcut(DataManager.java:220)
	at com.android.server.people.data.DataManager.getConversationChannel(DataManager.java:272)
	at com.android.server.people.data.DataManager.updateConversationStoreThenNotifyListeners(DataManager.java:1352)
	at com.android.server.people.data.DataManager.lambda$pruneExpiredConversationStatuses$7(DataManager.java:388)
	at com.android.server.people.data.DataManager.$r8$lambda$9QtnLJolnfZOyDCArzVmsAk6eIU(DataManager.java:0)
	at com.android.server.people.data.DataManager$$ExternalSyntheticLambda15.accept(R8$$SyntheticClass:0)
	at com.android.server.people.data.ConversationStore.forAllConversations(ConversationStore.java:172)
	at com.android.server.people.data.PackageData.forAllConversations(PackageData.java:125)
	at com.android.server.people.data.DataManager.lambda$pruneExpiredConversationStatuses$8(DataManager.java:378)
	at com.android.server.people.data.DataManager.$r8$lambda$Ke8LiaCTHULoKeL-JCkONVxdtXU(DataManager.java:0)
	at com.android.server.people.data.DataManager$$ExternalSyntheticLambda11.accept(R8$$SyntheticClass:0)
	at com.android.server.people.data.UserData.forAllPackages(UserData.java:73)
	at com.android.server.people.data.DataManager.forPackagesInProfile(DataManager.java:204)
	at com.android.server.people.data.DataManager.pruneExpiredConversationStatuses(DataManager.java:376)
	at com.android.server.people.data.DataManager.lambda$pruneDataForUser$9(DataManager.java:576)
	at com.android.server.people.data.DataManager.$r8$lambda$9iSSrF9eBT0tc3XJR9x9H17w2CM(DataManager.java:0)
	at com.android.server.people.data.DataManager$$ExternalSyntheticLambda8.accept(R8$$SyntheticClass:0)
	at com.android.server.people.data.UserData.forAllPackages(UserData.java:73)
	at com.android.server.people.data.DataManager.pruneDataForUser(DataManager.java:564)
	at com.android.server.people.PeopleService$LocalService.pruneDataForUser(PeopleService.java:451)
	at com.android.server.people.data.DataMaintenanceService.lambda$onStartJob$0(DataMaintenanceService.java:71)
	at com.android.server.people.data.DataMaintenanceService.$r8$lambda$jb3IGZMYfGb0tzDMSzNHcsd1StE(DataMaintenanceService.java:0)
	at com.android.server.people.data.DataMaintenanceService$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
Please reopen if it still happens on the 2023120701 release.
