### ISSUE TITLE
system_server Bluetooth state changed crash

### ISSUE THREAD

**Issue by BradNut** [GrapheneOS/os-issue-tracker#2785]
Everything is fine on the phone but this did show up after installing and restarting the latest release.

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.231205.015/2023120701:user/release-keys
Process: system_server
Build: google/cheetah/cheetah:14/UP1A.231105.003/2023120400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x4000010 (has extras) } in com.android.server.ext.BluetoothAutoOff$1@2e125ce
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.bluetooth.gatt.GattNativeInterface.gattClientGetDeviceType(java.lang.String)' on a null object reference
	at com.android.bluetooth.gatt.GattService.getDeviceType(GattService.java:4770)
	at com.android.bluetooth.gatt.GattService.getDevicesMatchingConnectionStates(GattService.java:3086)
	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.getDevicesMatchingConnectionStates(GattService.java:626)
	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.getDevicesMatchingConnectionStates(GattService.java:615)
	at android.bluetooth.IBluetoothGatt$Stub.onTransact(IBluetoothGatt.java:521)
	at android.os.Binder.execTransactInternal(Binder.java:1373)
	at android.os.Binder.execTransact(Binder.java:1299)
```

**Comment by thestinger** [comment]
@haval0 That's a completely different issue.

**Comment by BradNut** [comment]
It did not happen in the latest release. Thank you!

**Comment by thestinger** [comment]
Resolved for next release.
