### ISSUE TITLE
Pixel Camera Services crashes on every boot

### ISSUE THREAD

**Issue by heckarman** [GrapheneOS/os-issue-tracker#2800]
To my knowledge, `pixel camera services` is supported by GrapheneOS unlike Android System Intelligence and Pixel Launcher
```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
package: com.google.android.apps.camera.services:331118
process: com.google.android.apps.camera.services
processUptime: 496 + 599 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start receiver com.google.android.apps.camera.services.lyric.service.LyricConfigReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.pixel.camera.services.lyricconfigprovider.ILyricConfigProvider.updateConfig(java.util.List)' on a null object reference
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4489)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2268)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.pixel.camera.services.lyricconfigprovider.ILyricConfigProvider.updateConfig(java.util.List)' on a null object reference
	at com.google.pixel.camera.services.lyricconfigprovider.LyricConfigProviderManager.updateConfig(LyricConfigProviderManager.java:103)
	at com.google.android.apps.camera.services.lyric.service.LyricConfigReceiver.onReceive(PG:10)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4480)
	... 11 more

```

**Comment by thestinger** [comment]
Pixel Camera Services isn't supported yet.

**Comment by thestinger** [comment]
It's a priv-app in the stock OS. It won't work user installed anymore.

**Comment by heckarman** [comment]
IT IS indeed supported and I remember seeing that added somewhere in the repo.
It was added by @muhomorr AFAIK and they might have better context on it.

**Comment by thestinger** [comment]
No, it's not supported yet.

**Comment by heckarman** [comment]
It exists and is supported as far as I remember but I'm unable to determine in repo / commit it was added but I'm pretty it was added in the month of October - November

**Comment by thestinger** [comment]
It was previously possible to install it without crashes, but it wasn't something supported and it wasn't possible to use the CameraX extensions. Including support for it is planned, but hasn't been done yet.
