### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by limbusdev** [GrapheneOS/os-issue-tracker#2804]
```
type: crash
Process: system_server
Build: google/oriole/oriole:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Adding window failed
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1506)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:411)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:150)
	at android.app.Dialog.show(Dialog.java:352)
	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
	at com.android.server.am.ErrorDialogController.forAllDialogs(ErrorDialogController.java:164)
	at com.android.server.am.ErrorDialogController.lambda$showCrashDialogs$1(ErrorDialogController.java:182)
	at com.android.server.am.ErrorDialogController.$r8$lambda$RbiusjkAePXWGrMazzX5fIVcwYY(ErrorDialogController.java:0)
	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)
Caused by: java.lang.RuntimeException: Failed to open input channel pair with name 58935b9 Application Error: net.osmand.plus: Unknown error -24 Status=-24
	at com.android.server.input.NativeInputManagerService$NativeImpl.createInputChannel(Native Method)
	at com.android.server.input.InputManagerService.createInputChannel(InputManagerService.java:794)
	at com.android.server.wm.WindowState.openInputChannel(WindowState.java:2647)
	at com.android.server.wm.WindowManagerService.addWindow(WindowManagerService.java:1644)
	at com.android.server.wm.Session.addToDisplayAsUser(Session.java:219)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1484)
	... 15 more

```

**Comment by Juliaria08** [comment]
Same on `google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys`, my log:

```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A=2E231205=2E015/2023120800:user/relea=
se-keys
Crash-Handler: com=2Eandroid=2Einternal=2Eos=2ERuntimeInit$KillApplication=
Handler
Loading-Progress: 1=2E0
Dropped-Count: 0

java=2Elang=2ERuntimeException: Adding window failed
	at android=2Eview=2EViewRootImpl=2EsetView(ViewRootImpl=2Ejava:1506)
	at android=2Eview=2EWindowManagerGlobal=2EaddView(WindowManagerGlobal=2Ej=
ava:411)
	at android=2Eview=2EWindowManagerImpl=2EaddView(WindowManagerImpl=2Ejava:=
150)
	at android=2Eapp=2EDialog=2Eshow(Dialog=2Ejava:352)
	at com=2Eandroid=2Eserver=2Eam=2EErrorDialogController$$ExternalSynthetic=
Lambda3=2Eaccept(R8$$SyntheticClass:0)
	at com=2Eandroid=2Eserver=2Eam=2EErrorDialogController=2EforAllDialogs(Er=
rorDialogController=2Ejava:164)
	at com=2Eandroid=2Eserver=2Eam=2EErrorDialogController=2Elambda$showCrash=
Dialogs$1(ErrorDialogController=2Ejava:182)
	at com=2Eandroid=2Eserver=2Eam=2EErrorDialogController=2E$r8$lambda$Rbius=
jkAePXWGrMazzX5fIVcwYY(ErrorDialogController=2Ejava:0)
	at com=2Eandroid=2Eserver=2Eam=2EErrorDialogController$$ExternalSynthetic=
Lambda4=2Erun(R8$$SyntheticClass:0)
	at android=2Eos=2EHandler=2EhandleCallback(Handler=2Ejava:958)
	at android=2Eos=2EHandler=2EdispatchMessage(Handler=2Ejava:99)
	at android=2Eos=2ELooper=2EloopOnce(Looper=2Ejava:205)
	at android=2Eos=2ELooper=2Eloop(Looper=2Ejava:294)
	at android=2Eos=2EHandlerThread=2Erun(HandlerThread=2Ejava:67)
	at com=2Eandroid=2Eserver=2EServiceThread=2Erun(ServiceThread=2Ejava:46)
	at com=2Eandroid=2Eserver=2EUiThread=2Erun(UiThread=2Ejava:45)
Caused by: java=2Elang=2ERuntimeException: Failed to open input channel pa=
ir with name 811ef45 Application Error: com=2Eandroid=2Elauncher3: Unknown =
error -24 Status=3D-24
	at com=2Eandroid=2Eserver=2Einput=2ENativeInputManagerService$NativeImpl=
=2EcreateInputChannel(Native Method)
	at com=2Eandroid=2Eserver=2Einput=2EInputManagerService=2EcreateInputChan=
nel(InputManagerService=2Ejava:794)
	at com=2Eandroid=2Eserver=2Ewm=2EWindowState=2EopenInputChannel(WindowSta=
te=2Ejava:2647)
	at com=2Eandroid=2Eserver=2Ewm=2EWindowManagerService=2EaddWindow(WindowM=
anagerService=2Ejava:1644)
	at com=2Eandroid=2Eserver=2Ewm=2ESession=2EaddToDisplayAsUser(Session=2Ej=
ava:219)
	at android=2Eview=2EViewRootImpl=2EsetView(ViewRootImpl=2Ejava:1484)
	=2E=2E=2E 15 more

```

**Comment by Juliaria08** [comment]
Don't know if this is related, but on the same phone I later saw this:
```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
uid: 1000 (u:r:system_server:s0
cmdline: system_server
processUptime: 17563s

abortMessage: Too many open files, could not duplicate input channel 5f26c24 com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher (client)

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: binder:2922_1A

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libinput.so (android::InputChannel::dupFd() const+532, pc b5314)
    /system/lib64/libinput.so (android::InputChannel::dup() const+52, pc b4f44)
    /system/lib64/libandroid_runtime.so (android::android_view_InputChannel_nativeDup(_JNIEnv*, _jobject*, long)+80, pc 149530)
    /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116, pc 1e9094)
    /apex/com.android.art/lib64/libart.so (nterp_helper+5648, pc 20a990)
    /system/framework/framework.jar (android.view.InputChannel.copyTo+24, pc 1b2cb0)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowState.openInputChannel+328, pc 974098)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.WindowManagerService.addWindow+7340, pc 93563c)
    /apex/com.android.art/lib64/libart.so (nterp_helper+5848, pc 20aa58)
    /system/framework/services.jar (com.android.server.wm.Session.addToDisplayAsUser+46, pc eda16)
    /apex/com.android.art/lib64/libart.so (nterp_helper+5720, pc 20a9d8)
    /system/framework/framework.jar (android.view.IWindowSession$Stub.onTransact+3532, pc 1b1b0c)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.Session.onTransact+72, pc 90a738)
    /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransactInternal+752, pc 6247a0)
    /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransact+564, pc 624304)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+460, pc 64417c)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92, pc 64440c)
    /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+660, pc 47aa84)
    /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+120, pc deae8)
    /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+164, pc 195d24)
    /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+304, pc 74b00)
    /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1016, pc 5ed78)
    /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+160, pc 5e8c0)
    /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+112, pc 5f210)
    /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24, pc 69078)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140, pc e719c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

Something very wrong seems to have happened in the update. I also saw a error about the last update for some reason.
Is it possible for me to downgrade without losing user data?

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/os-issue-tracker/issues/2790

**Comment by thestinger** [comment]
https://grapheneos.org/releases#2023121200 raises the file descriptor limit and should resolve this Android 14 QPR1 issue unless it's caused by a file descriptor leak rather than higher file descriptor usage.
