### ISSUE TITLE
crash: system_server on bluejay:14/UQ1A.231205.015/2023120800

### ISSUE THREAD

**Issue by hoffie** [GrapheneOS/os-issue-tracker#2813]
```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: failed to set system property (check logcat for reason)
	at android.os.SystemProperties.native_set(Native Method)
	at android.os.SystemProperties.set(SystemProperties.java:235)
	at android.app.PropertyInvalidatedCache.setNonce(PropertyInvalidatedCache.java:711)
	at android.app.PropertyInvalidatedCache.invalidateCacheLocked(PropertyInvalidatedCache.java:1127)
	at android.app.PropertyInvalidatedCache.invalidateCache(PropertyInvalidatedCache.java:1100)
	at android.hardware.display.DisplayManagerGlobal.invalidateLocalDisplayInfoCaches(DisplayManagerGlobal.java:1247)
	at com.android.server.display.DisplayInfoProxy.set(DisplayInfoProxy.java:42)
	at com.android.server.display.LogicalDisplay.updateLocked(LogicalDisplay.java:526)
	at com.android.server.display.LogicalDisplayMapper.updateLogicalDisplaysLocked(LogicalDisplayMapper.java:698)
	at com.android.server.display.LogicalDisplayMapper.onDisplayDeviceChangedLocked(LogicalDisplayMapper.java:249)
	at com.android.server.display.DisplayDeviceRepository.sendChangedEventLocked(DisplayDeviceRepository.java:222)
	at com.android.server.display.DisplayDeviceRepository.handleDisplayDeviceChanged(DisplayDeviceRepository.java:190)
	at com.android.server.display.DisplayDeviceRepository.onDisplayDeviceEvent(DisplayDeviceRepository.java:90)
	at com.android.server.display.DisplayAdapter.lambda$sendDisplayDeviceEventLocked$0(DisplayAdapter.java:112)
	at com.android.server.display.DisplayAdapter.$r8$lambda$gm45_jC2LhoVo8UVaUhDk7CBBT8(DisplayAdapter.java:0)
	at com.android.server.display.DisplayAdapter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**logcat excerpt from right before the crash until next boot message:**
```
12-10 22:30:26.204     0     0 I trusty  : [GF_TA][I][gf_algo_customized][fill_auth_big_data] continuous_update_fl
ag:0x0f
12-10 23:16:53.903 31860 31945 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.display
12-10 23:16:53.903 31860 31945 E AndroidRuntime: java.lang.RuntimeException: failed to set system property (check 
logcat for reason)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.os.SystemProperties.native_set(Native Method)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.os.SystemProperties.set(SystemProperties.java:2
35)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.app.PropertyInvalidatedCache.setNonce(PropertyI
nvalidatedCache.java:711)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.app.PropertyInvalidatedCache.invalidateCacheLoc
ked(PropertyInvalidatedCache.java:1127)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.app.PropertyInvalidatedCache.invalidateCache(Pr
opertyInvalidatedCache.java:1100)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.hardware.display.DisplayManagerGlobal.invalidat
eLocalDisplayInfoCaches(DisplayManagerGlobal.java:1247)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.DisplayInfoProxy.set(Display
InfoProxy.java:42)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.LogicalDisplay.updateLocked(
LogicalDisplay.java:526)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.LogicalDisplayMapper.updateL
ogicalDisplaysLocked(LogicalDisplayMapper.java:698)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.LogicalDisplayMapper.onDispl
ayDeviceChangedLocked(LogicalDisplayMapper.java:249)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.DisplayDeviceRepository.sendChangedEventLocked(DisplayDeviceRepository.java:222)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.DisplayDeviceRepository.handleDisplayDeviceChanged(DisplayDeviceRepository.java:190)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.DisplayDeviceRepository.onDisplayDeviceEvent(DisplayDeviceRepository.java:90)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.DisplayAdapter.lambda$sendDisplayDeviceEventLocked$0(DisplayAdapter.java:112)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.DisplayAdapter.$r8$lambda$gm45_jC2LhoVo8UVaUhDk7CBBT8(DisplayAdapter.java:0)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.display.DisplayAdapter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:958)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
12-10 23:16:53.903 31860 31945 E AndroidRuntime:        at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-10 23:16:54.612 32171 32171 E AndroidRuntime: FATAL EXCEPTION: main
12-10 23:16:54.612 32171 32171 E AndroidRuntime: Process: com.android.systemui, PID: 32171
12-10 23:16:54.612 32171 32171 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
12-10 23:16:54.613 32171 32456 E AndroidRuntime: FATAL EXCEPTION: BroadcastRunning
12-10 23:16:54.613 32171 32456 E AndroidRuntime: Process: com.android.systemui, PID: 32171
12-10 23:16:54.613 32171 32456 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
--------- beginning of system
12-10 23:17:01.507 18764 18764 D SystemServerTiming: OnBootPhase_500_com.android.server.telecom.TelecomLoaderService
```

This happened while being on the lock screen.

I've been seeing multiple system_server crashes/unexpected "reboots" (boot logo, asked for PIN) since 2023120700 (or maybe 2023120400). Sometimes with no crash report, sometimes after interactions (mostly on the lock or home screen).

I've at least once observed this stack trace: https://github.com/GrapheneOS/os-issue-tracker/issues/2804#issuecomment-1849089557 and #2790

This Pixel 6a had been really stable in the past on GrapheneOS (thanks for all the hard work for making this happen!), so I suspect that this is not a hardware-related issue.

**Comment by thestinger** [comment]
Likely a rare upstream bug, and not much we can do about this one if it's not happening regularly. We're going to focus on resolving #2790.

**Comment by thestinger** [comment]
Likely a rare upstream bug, and not much we can do about this one if it's not happening regularly.
