### ISSUE TITLE
Sandboxed GooglePlay crashed

### ISSUE THREAD

**Issue by h-2** [GrapheneOS/os-issue-tracker#2816]
I don't know when this happened exactly, because I had notifications turned off and saw it much later.

```
type: crash
osVersion: google/oriole/oriole:14/UP1A.231005.007/2023100900:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 2031808 + 302 ms
installer: com.android.vending
GmsCompatConfig version: 87

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cnpu.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):455)
	at cnmu.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):9)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a115; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bgds.apply(:com.google.android.gms@234523038@23.45.23 (190400-587848529):5)
	at ecjp.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):3)
	at ecjq.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a115; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.ha(:com.google.android.gms@234523038@23.45.23 (190400-587848529):186)
	at bgdt.call(:com.google.android.gms@234523038@23.45.23 (190400-587848529):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14521)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14431)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by thestinger** [comment]
You need to update to a current release. You're on 2023100900.

**Comment by thestinger** [comment]
You're still only on 2023101100 and need to update to a current release. You had an update pending for months and you're still not updated beyond that one.

**Comment by h-2** [comment]
> You're still only on 2023101100 and need to update to a current release. You had an update pending for months and you're still not updated beyond that one.

Thanks for the quick reply! For some reason, it took two more reboots for the next update to be installed, but now everything is fine.
