### ISSUE TITLE
Error in Google Play Store

### ISSUE THREAD

**Issue by attisimon** [GrapheneOS/os-issue-tracker#2821]
Hello!

Today Google Play Store crashed on my secondary profile. I wasn't signed in, I opened the app and then I accessed the Updates section from the menu. The crash happened while checking for updates.

Here is the output:

```
type: crash
osVersion: google/lynx/lynx:14/UQ1A.231205.015/2023120800:user/release-keys
package: com.android.vending:83861020
process: com.android.vending
processUptime: 6700288 + 386 ms
installer: com.android.vending
GmsCompatConfig version: 87

java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.set(ArrayList.java:448)
	at abzw.T(PG:30)
	at abzw.S(PG:19)
	at abzw.p(PG:3)
	at lb.w(PG:1)
	at lr.r(PG:1103)
	at lr.c(PG:6)
	at kj.a(PG:54)
	at ur.h(PG:9)
	at tlr.c(PG:5)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.at(PG:9)
	at android.support.v7.widget.LinearLayoutManagerWithProxies.B(PG:13)
	at android.support.v7.widget.LinearLayoutManager.M(PG:45)
	at android.support.v7.widget.LinearLayoutManager.n(PG:743)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.n(PG:110)
	at android.support.v7.widget.RecyclerView.aO(PG:65)
	at android.support.v7.widget.RecyclerView.F(PG:74)
	at android.support.v7.widget.RecyclerView.onLayout(PG:6)
	at com.google.android.finsky.recyclerview.PlayRecyclerView.onLayout(PG:9)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at iau.onLayout(PG:256)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at aocv.onLayout(PG:1)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4455)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3767)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by attisimon** [comment]
I am using Aurora Store most of the time to install and update apps. I just wanted to report the crash, perhaps it helps.

**Comment by thestinger** [comment]
It's likely just a Play Store UI bug. Does it happen again?
