### ISSUE TITLE
System Server Crash

### ISSUE THREAD

**Issue by GrapheneEnjoyer** [GrapheneOS/os-issue-tracker#2837]
Guys Out of nowhere, i got crash while i was away from my device, anything i should be concerned about?

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

android.view.Surface$OutOfResourcesException: DEAD_OBJECT
	at android.view.SurfaceControl.nativeCreate(Native Method)
	at android.view.SurfaceControl.<init>(SurfaceControl.java:1237)
	at android.view.SurfaceControl.<init>(Unknown Source:0)
	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:910)
	at com.android.server.wm.WindowContainer.setInitialSurfaceControlProperties(WindowContainer.java:682)
	at com.android.server.wm.WindowContainer.createSurfaceControl(WindowContainer.java:678)
	at com.android.server.wm.WindowToken.createSurfaceControl(WindowToken.java:337)
	at com.android.server.wm.WindowContainer.onParentChanged(WindowContainer.java:664)
	at com.android.server.wm.WindowContainer.setParent(WindowContainer.java:646)
	at com.android.server.wm.WindowContainer.addChild(WindowContainer.java:777)
	at com.android.server.wm.DisplayArea$Tokens.addChild(DisplayArea.java:729)
	at com.android.server.wm.DisplayContent.addWindowToken(DisplayContent.java:1434)
	at com.android.server.wm.WindowToken.<init>(WindowToken.java:240)
	at com.android.server.wm.WallpaperWindowToken.<init>(WallpaperWindowToken.java:53)
	at com.android.server.wm.WindowManagerService.addWindowToken(WindowManagerService.java:2722)
	at com.android.server.wm.WindowManagerService$LocalService.addWindowToken(WindowManagerService.java:7856)
	at com.android.server.wallpaper.WallpaperManagerService$DisplayConnector.connectLocked(WallpaperManagerService.java:937)
	at com.android.server.wallpaper.WallpaperManagerService.lambda$attachServiceLocked$21(WallpaperManagerService.java:3735)
	at com.android.server.wallpaper.WallpaperManagerService.$r8$lambda$uZi5_bwd07bsmBx9bUAW0RE40MU(WallpaperManagerService.java:0)
	at com.android.server.wallpaper.WallpaperManagerService$$ExternalSyntheticLambda23.accept(R8$$SyntheticClass:0)
	at com.android.server.wallpaper.WallpaperManagerService$WallpaperConnection.forEachDisplayConnector(WallpaperManagerService.java:1052)
	at com.android.server.wallpaper.WallpaperManagerService.attachServiceLocked(WallpaperManagerService.java:3735)
	at com.android.server.wallpaper.WallpaperManagerService.-$$Nest$mattachServiceLocked(WallpaperManagerService.java:0)
	at com.android.server.wallpaper.WallpaperManagerService$WallpaperConnection.onServiceConnected(WallpaperManagerService.java:1094)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2198)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2231)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:972)
	at com.android.server.SystemServer.main(SystemServer.java:666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

**Comment by GrapheneEnjoyer** [comment]
Closing And reposting on ongoing thread

**Comment by thestinger** [comment]
It's unrelated to the issue in that thread but the issue here should be resolved in the next release.

**Comment by thestinger** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/2787.

**Comment by thestinger** [comment]
https://grapheneos.org/releases#2023121200 raises the file descriptor limit and should resolve this Android 14 QPR1 issue unless it's caused by a file descriptor leak rather than higher file descriptor usage.
