### ISSUE TITLE
Crash after trying to enable ethernet tethering

### ISSUE THREAD

**Issue by GOSOShero** [GrapheneOS/os-issue-tracker#2840]
Ethernet tethering works well, but sometimes when I turn off the device I tether to, Ethernet tether turns off on my phone too, but the option is not greyed out. Now when I connect my phone to the device again and try to turn on Ethernet tethering, it doesn't turn on and make my system_server crash. After the crash it works again. 

Here is the crash report

```
type: crash
Process: system_server
Build: google/oriole/oriole:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at android.net.connectivity.com.android.server.ethernet.EthernetNetworkFactory.getInterfaceState(EthernetNetworkFactory.java:170)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker.unicastInterfaceStateChange(EthernetTracker.java:328)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker.lambda$addListener$4(EthernetTracker.java:435)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker.$r8$lambda$u74wXsW90rogcJx8NNlJoTHWh6U(EthernetTracker.java:0)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker$$ExternalSyntheticLambda5.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by thestinger** [comment]
Please update to the latest release and see if it happens again.
