### ISSUE TITLE
Random crash when turning Bluetooth on

### ISSUE THREAD

**Issue by danielmehring** [GrapheneOS/os-issue-tracker#2842]
I tried turning Bluetooth on and I think I tapped quickly a couple of times on the tile.

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Service is unavailable: null
	at com.android.bluetooth.le_audio.LeAudioService$BluetoothLeAudioBinder.registerCallback(LeAudioService.java:3497)
	at android.bluetooth.IBluetoothLeAudio$Stub.onTransact(IBluetoothLeAudio.java:469)
	at android.os.Binder.execTransactInternal(Binder.java:1366)
	at android.os.Binder.execTransact(Binder.java:1302)

```

**Comment by danielmehring** [comment]
I didn't manage to reproduce it. So maybe just close this issue. It's probably a very unlikely edge case.
