### ISSUE TITLE
Google play service crash INTERACT_ACROSS_USERS_FULL

### ISSUE THREAD

**Issue by churchthecat** [GrapheneOS/os-issue-tracker#2845]
After latest update. Additional profile , main has no google.

```
type: crash
osVersion: google/bonito/bonito:12/SP2A.220505.008/2023020600:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 3447 ms
GmsCompatConfig version: 87

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u12a335; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
	at android.os.Parcel.createException(Parcel.java:2420)
	at android.os.Parcel.readException(Parcel.java:2396)
	at android.os.Parcel.readException(Parcel.java:2338)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5727)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1456)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1423)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:578)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:578)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhi.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:920)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)

```

**Comment by churchthecat** [comment]
> You're using an end-of-life device that no longer receives any updates, including to the compatibility layer. This issue is fixed on current GrapheneOS.
> 
> Please consider moving to a supported device. Your device is not receiving security updates. The recommended devices can be found here: https://grapheneos.org/faq#recommended-devices

Yes I  aware , due to reasons I am not able to move yet. Is there a way to downgrade? I see others opening issues regarding this on different devices.

**Comment by thestinger** [comment]
> Yes I aware , due to reasons I am not able to move yet. Is there a way to downgrade? I see others opening issues regarding this on different devices.

It was fixed in the [2023111500](https://grapheneos.org/releases#2023111500) release and backported to 4th generation Pixels.

**Comment by thestinger** [comment]
We can likely release an update to GmsCompatConfig working around it for 3rd generation Pixels soon. We aren't going to release any further extended support OS releases for them especially since they're on Android 12.1 but we can do that to quiet down the issues getting filed.

**Comment by thestinger** [comment]
@churchthecat Please update GmsCompatConfig to 88 via the app repository and you shouldn't have the crashes anymore.

**Comment by churchthecat** [comment]
Sweet , thanks :)
