### ISSUE TITLE
Crashing every 10-15min

### ISSUE THREAD

**Issue by TryingHaaard** [GrapheneOS/os-issue-tracker#2851]
This is the log, what function is it that messing with the system? Can i turn something off? Its the Pixel 4A, i got info that last update was the last for 4A and then the update surprisingly messed up the system for me as a last farwell.

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001/2023100300:user/release-keys
package: com.google.android.gms:234414038
process: com.google.android.gms.persistent
processUptime: 5596 + 309 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cnen.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):455)
	at cnbn.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):9)
	at ajls.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):50)
	at ajls.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at ajqx.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvmi: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a126; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bfxo.apply(:com.google.android.gms@234414038@23.44.14 (190400-580326705):5)
	at ebya.d(:com.google.android.gms@234414038@23.44.14 (190400-580326705):3)
	at ebyb.run(:com.google.android.gms@234414038@23.44.14 (190400-580326705):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a126; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at avyb.sendBroadcastAsUser(:com.google.android.gms@234414038@23.44.14 (190400-580326705):6)
	at cvxh.a(:com.google.android.gms@234414038@23.44.14 (190400-580326705):38)
	at cvxl.g(:com.google.android.gms@234414038@23.44.14 (190400-580326705):723)
	at cvxi.c(:com.google.android.gms@234414038@23.44.14 (190400-580326705):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hc(:com.google.android.gms@234414038@23.44.14 (190400-580326705):186)
	at bfxp.call(:com.google.android.gms@234414038@23.44.14 (190400-580326705):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2270)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13751)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13703)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14581)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2304)


```

**Comment by thestinger** [comment]
The latest stable release for the Pixel 4a is [2023110900](https://grapheneos.org/releases#2023110900). You need to update.

**Comment by thestinger** [comment]
Your issue is because you aren't updated, not because of an update. It was caused by a Play services update and we dealt with it before the problem could reach users.

**Comment by thestinger** [comment]
Also, the Pixel 4a is end-of-life but still receives extended support releases from GrapheneOS. It should receive one this month, soon, but we were focused on extended support for the Pixel 4a (5G) and Pixel 5 first.

**Comment by TryingHaaard** [comment]
Thanks for the answer, this is where it gets frustrating, i have pushed the "check fof updates" several times but it doesnt give any confirmation that it checked and i never received a update after i did that. Any solutions? Would be great with some kind of feedback when it last sucessfully checked for an update because now im in the dark.

**Comment by TryingHaaard** [comment]
![Screenshot_20231213-210505](https://github.com/GrapheneOS/os-issue-tracker/assets/153770041/60b5b797-1088-4f39-ba66-2e987c47f32c)
![Screenshot_20231213-210452](https://github.com/GrapheneOS/os-issue-tracker/assets/153770041/62eaed93-b01c-4ac7-8f3a-f7563c85f607)

Doesnt seem to be te problem either :O 

Thanks for helping me figuring this out

**Comment by TryingHaaard** [comment]
Did that several times in the past and just did it again to no avail. Is there any way to check the call to the update server and what error it trows?

**Comment by TryingHaaard** [comment]
Permittednetworkswasthe dowpit, it was set to unmetered only, i changed to "any" and it started to downloada update directly.

Sorry guys
