### ISSUE TITLE
Crash after disabling airplane mode

### ISSUE THREAD

**Issue by AlexanderHott** [GrapheneOS/os-issue-tracker#2853]
```
type: crash
Process: system_server
Build: google/panther/panther:14/UQ1A.231205.015/2023120800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'com.android.wifi.x.android.hardware.wifi.StaBackgroundScanCapabilities com.android.wifi.x.android.hardware.wifi.IWifiStaIface.getBackgroundScanCapabilities()' on a null object reference
	at com.android.server.wifi.hal.WifiStaIfaceAidlImpl.getBackgroundScanCapabilities(WifiStaIfaceAidlImpl.java:243)
	at com.android.server.wifi.hal.WifiStaIface.lambda$getBackgroundScanCapabilities$6(WifiStaIface.java:202)
	at com.android.server.wifi.hal.WifiStaIface.$r8$lambda$_EbJ5ihVCnh9jcPe1DVklmaHw0c(WifiStaIface.java:0)
	at com.android.server.wifi.hal.WifiStaIface$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:0)
	at com.android.server.wifi.hal.WifiStaIface.validateAndCall(WifiStaIface.java:142)
	at com.android.server.wifi.hal.WifiStaIface.getBackgroundScanCapabilities(WifiStaIface.java:201)
	at com.android.server.wifi.WifiVendorHal.getBgScanCapabilities(WifiVendorHal.java:579)
	at com.android.server.wifi.WifiNative.getBgScanCapabilities(WifiNative.java:3174)
	at com.android.server.wifi.scanner.WifiScannerImpl$1.create(WifiScannerImpl.java:63)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.setupScannerImpls(WifiScanningServiceImpl.java:741)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.lambda$setScanningEnabled$1(WifiScanningServiceImpl.java:204)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.$r8$lambda$D_ymntbRb7H5O15mR0WYDlVLPp0(WifiScanningServiceImpl.java:0)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by AlexanderHott** [comment]
> Please update to the latest release. Always the first thing to try before filing an issue.

Sorry, my phone had been in airplane mode for a while, I didn't see there was a new update.

**Comment by thestinger** [comment]
There was a file descriptor exhaustion issue caused by Android 14 QPR1 which we've addressed, which caused all kinds of issues and may have caused what you experienced.
