### ISSUE TITLE
Every 5 minutes getting 'Sandboxed Google Play crashed'

### ISSUE THREAD

**Issue by cherez0ff** [GrapheneOS/os-issue-tracker#2855]
```
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231005.007/2023101300:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 84838 + 559 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a150; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
 at android.os.Parcel.createException(Parcel.java:3050)
 at android.os.Parcel.readException(Parcel.java:3026)
 at android.os.Parcel.readException(Parcel.java:2968)
 at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
 at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
 at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
 at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
 at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
 at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
 at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
 at cwgx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):11)
 at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
 at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
 at java.lang.Thread.run(Thread.java:1012)
 Suppressed: dvxr: 
  at tk_trace.ScheduledTaskImpl(Unknown Source:0)
  at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
  ```
  
  Also, some apps like taxi stopped working.

**Comment by LukasMerz** [comment]
It's almost every app that crashes (Spotify, Audible, Reddit, Idagio)
Not crashing are (WhatsApp, Telegram, Teams)

**Comment by muhomorr** [comment]
@cherez0ff You're running an outdated version of GrapheneOS. This issue is resolved in the current version.

@LukasMerz Which version of GrapheneOS are you on?

**Comment by cherez0ff** [comment]
Confirmed - fixed after update

**Comment by LukasMerz** [comment]
@muhomorr I am on UP1A.231005.007.2023102300 which is outdated, but I am wondering why it does not show me the option to udpate. I'll investigate further
