### ISSUE TITLE
Google Play Services crashing after reboot

### ISSUE THREAD

**Issue by bitsn1per** [GrapheneOS/os-issue-tracker#2856]
Google Pixel 6

```
type: crash
osVersion: google/oriole/oriole:13/TQ2A.230305.008.E1/2023040400:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 273807 + 445 ms
GmsCompatConfig version: 88

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a142; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5096)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):11)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2270)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13698)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13650)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14528)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2296)


```

**Comment by bitsn1per** [comment]
> You're running an outdated version of GrapheneOS. It's over 8 months old at this point. This issue is resolved in the current version.

Thank you for your attention for my report! I have fixed this issue with cleaning all Google Services cache.

I've used to automatic updates with my previous phones. So, now I'm downloading updates manually. Is there any way to set up autoupdates?

**Comment by muhomorr** [comment]
OS updates are automatic by default. See https://grapheneos.org/usage#updates
