### ISSUE TITLE
Google Play Services crash every 10-15 Minutes

### ISSUE THREAD

**Issue by osedoxin** [GrapheneOS/os-issue-tracker#2859]
Google Play Services crash every 10-15 Minutes. Apart from the constant crash notifications this force closes apps, e.g. Google Maps and delays push notifications significantly. 

````
type: crash
osVersion: google/panther/panther:14/UP1A.231005.007/2023101300:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 557 + 343 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a134; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhi.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)

````

**Comment by thestinger** [comment]
You need to update, this was resolved a while ago before the Play services update reached users.

**Comment by osedoxin** [comment]
Which update am I missing? I don't see any missing updates in "Apps" or system update

**Comment by thestinger** [comment]
You're on a 2 month old version of the OS.

**Comment by thestinger** [comment]
You're on 2023101300 and you should be on 2023121200. You might have dismissed the successful update notification and haven't rebooted since then.
