### ISSUE TITLE
Sandboxed googleplay crashed

### ISSUE THREAD

**Issue by 13p13** [GrapheneOS/os-issue-tracker#2863]
Started happening after recent updates.
Seems to be in the user profile not main profile.
Noticed via opening apps on user, such as venmo , cashapp etc, that they close immediately.

Gplay and services installed completely in user profile. NOT on main profile.

Apps up to date, everything updated. Restart helps but for a short period. 

Seems to be a permission issue between users, looking at the log.

Log from crash report below:
```
type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231005.007/2023101300:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 617 + 363 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u14a131; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhi.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)

```

**Comment by thestinger** [comment]
You're very far behind on updates (2023101300 is from October) and are missing the fix we did for this in November before this Play update shipped to users. GmsCompatConfig has been updated to permit the new Google Play versions with the assumption that people update their OS within a couple weeks.

**Comment by thestinger** [comment]
Did you disallow it from using the network type you have available in the settings?

**Comment by thestinger** [comment]
It was possible to dismiss notifications which should have been sticky until we fixed it since Android disabled sticky notifications overall, even for system apps, other than a few specific components. Perhaps you did already install the update, dismissed the notification before we prevented that again and you haven't rebooted for 2 months.

**Comment by 13p13** [comment]
have rebooted multiple times, but this issue now bothers me.
I have network allowed for all system apps.
Notifications for System Updater all on....
error reporting, update progress already updated , all of them
some were on silent notification, returned them to alert status.

restarted several times, can't revive the automatic updates
