### ISSUE TITLE
frequent google play crashes 

### ISSUE THREAD

**Issue by buckclub** [GrapheneOS/os-issue-tracker#2868]
Was getting this whenever I tried to open iFunny or X 

```
type: crash
osVersion: google/husky/husky:14/UD1A.230803.041/2023103100:user/release-keys
package: com.google.android.gms:234816039
process: com.google.android.gms.persistent
processUptime: 197179 + 521 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a139; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at awtb.sendBroadcastAsUser(:com.google.android.gms@234816039@23.48.16 (190408-590025996):6)
	at cyua.a(:com.google.android.gms@234816039@23.48.16 (190408-590025996):43)
	at cyuc.run(:com.google.android.gms@234816039@23.48.16 (190408-590025996):11)
	at akan.c(:com.google.android.gms@234816039@23.48.16 (190408-590025996):50)
	at akan.run(:com.google.android.gms@234816039@23.48.16 (190408-590025996):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akge.run(:com.google.android.gms@234816039@23.48.16 (190408-590025996):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyvb: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14521)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14431)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by thestinger** [comment]
You need to update the OS.
