### ISSUE TITLE
Pixel 7 Pro system_server crash

### ISSUE THREAD

**Issue by zifxify** [GrapheneOS/os-issue-tracker#2870]
Switching user profiles caused this crash

```
type: crash
Process: unknown
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 12) is unlocked
	at android.app.ActivityThread.installProvider(ActivityThread.java:7809)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7315)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7022)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2248)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: androidx.startup.StartupException: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 12) is unlocked
	at b6.a.b(AppInitializer.java:99)
	at b6.a.a(AppInitializer.java:82)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7804)
	... 13 more
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 12) is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:609)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:592)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:221)
	at com.reblaze.sdk.ReblazeInstance.<init>(SourceFile:24)
	at com.reblaze.sdk.a.<init>(SourceFile:7)
	at com.reblaze.sdk.Loader.b(SourceFile:61)
	at b6.a.b(AppInitializer.java:86)
	... 18 more

```

**Comment by zifxify** [comment]
New one today,

```
type: crash
Process: unknown
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ExceptionInInitializerError
	at app.grapheneos.apps.ApplicationImpl.attachBaseContext(Unknown Source:14)
	at android.app.Application.attach(Application.java:352)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1287)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2248)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 12) is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:609)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:592)
	at app.grapheneos.apps.PackageStates.<clinit>(Unknown Source:282)
	... 17 more

```

**Comment by muhomorr** [comment]
This is not a system_server crash, it was reported as one due to an upstream bug that has since been resolved.
