### ISSUE TITLE
Error in Google Play Store

### ISSUE THREAD

**Issue by Oktobear** [GrapheneOS/os-issue-tracker#2873]
```
type: crash
osVersion: google/husky/husky:14/UQ1A.231205.015/2023121200:user/release-keys
package: com.android.vending:83873220
process: com.android.vending
processUptime: 1569887 + 389 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.NullPointerException: Attempt to read from field 'hoz android.support.v7.widget.RecyclerView.W' on a null object reference in method 'void lj.k(android.view.View, int, boolean)'
	at lj.k(PG:16)
	at lj.adt(PG:2)
	at lj.ads(PG:2)
	at tte.c(PG:39)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.at(PG:9)
	at android.support.v7.widget.LinearLayoutManagerWithProxies.B(PG:13)
	at android.support.v7.widget.LinearLayoutManager.M(PG:45)
	at android.support.v7.widget.LinearLayoutManager.n(PG:743)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.n(PG:110)
	at android.support.v7.widget.RecyclerView.aO(PG:65)
	at android.support.v7.widget.RecyclerView.F(PG:74)
	at android.support.v7.widget.RecyclerView.onLayout(PG:6)
	at com.google.android.finsky.recyclerview.PlayRecyclerView.onLayout(PG:9)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at ial.onLayout(PG:256)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at aoia.agF(PG:142)
	at aoic.j(PG:1)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.j(PG:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:41)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at com.google.android.finsky.drawer.FinskyDrawerLayout.onLayout(PG:48)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4455)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3767)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by thestinger** [comment]
Appears to be a Play Store bug.
