### ISSUE TITLE
Pixek 8 Pro : Sandboxed Google Play crash

### ISSUE THREAD

**Issue by blabaere** [GrapheneOS/os-issue-tracker#2875]
Sorry, I don't have more context than the stacktrace.

```
type: crash
osVersion: google/husky/husky:14/UQ1A.231205.015/2023121200:user/release-keys
package: com.google.android.gms:234523039
process: com.google.android.gms
processUptime: 76221 + 248 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 88

java.lang.SecurityException: You either need MANAGE_USERS or QUERY_USERS permission to: call getUserRestrictionSources.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.os.IUserManager$Stub$Proxy.getUserRestrictionSources(IUserManager.java:2692)
	at android.os.UserManager.getUserRestrictionSources(UserManager.java:3568)
	at com.google.android.gms.auth.managed.intentoperations.AuthManagedModuleInitIntentOperation.d(:com.google.android.gms@234523039@23.45.23 (190408-587848529):61)
	at com.google.android.gms.auth.managed.intentoperations.AuthManagedModuleInitIntentOperation.b(:com.google.android.gms@234523039@23.45.23 (190408-587848529):108)
	at aggl.onHandleIntent(:com.google.android.gms@234523039@23.45.23 (190408-587848529):131)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234523039@23.45.23 (190408-587848529):2)
	at agla.onHandleIntent(:com.google.android.gms@234523039@23.45.23 (190408-587848529):10)
	at nqe.run(:com.google.android.gms@234523039@23.45.23 (190408-587848529):70)
	at nqd.run(:com.google.android.gms@234523039@23.45.23 (190408-587848529):152)
	at dvwy.run(:com.google.android.gms@234523039@23.45.23 (190408-587848529):13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
@blabaere What were you doing when this happened?

**Comment by actick** [comment]
@thestinger same just happen to me as well on Pixel 6a.. I got this error while normal use.. Now every time I reboot or shutdown &start comes up every time right after boot. I see exactly same stacktrace as the reported one

**Comment by slavicd** [comment]
Pixel 6. Happens upon opening any Google play app.

**Comment by slavicd** [comment]
> @slavicd This is a different thing. Your issue is that your OS is not up to date. Please update and the issue will go away. You're on a release from October.

This has started happening after my phone updated this morning. There are no more available updates according to the system.

**Comment by slavicd** [comment]
![photo_2023-12-16_15-08-21](https://github.com/GrapheneOS/os-issue-tracker/assets/1071705/5c1ec0e9-1d56-4d5e-a01a-71fc2134b006)

I think I have a theory of what's happening: when the Sandboxed Google Play crash happens the updater fails.

**Comment by thestinger** [comment]
@slavicd That doesn't make sense, and it's unrelated to this issue. Please use one of the support platforms for support. The issue you're having is because you haven't kept updated.

**Comment by slavicd** [comment]
> @slavicd That doesn't make sense, and it's unrelated to this issue. Please use one of the support platforms for support. The issue you're having is because you haven't kept updated.

My "Sandboxed Google Play crash" report is unrelated to "Sandboxed Google Play crash"? Your cat stepped on the delete button, careful. You just deleted the only useful comment here, where someone who had a better morning than you indicated that there is ANOTHER update, which, my theory (poorly founded, yes) was that it gets interrupted because of the said crash.

**Comment by thestinger** [comment]
@slavicd Yes, it's entirely unrelated to this thread. You have an issue caused by not updating the OS. The issue you have was resolved in November, significantly before you received the Play services change requiring it. If you had kept updated, you would not have experienced any issue. Nothing you've posted here is relevant or useful. The issue you have is not causing your problems with updates. You have a network issue that's causing that problem, and it's likely why you fell out-of-date, which is why you have the Play services crash from having a recent Google Play on an outdated OS release without support for it.

**Comment by thestinger** [comment]
The issue you have was fixed in [2023111500](https://grapheneos.org/releases#2023111500). It has nothing to do with this issue. Not every crash which occurs in the same app (in this case Play services) is caused by the same issue. We can clearly see that the crash you're having is caused by not having GrapheneOS 2023111500 or later. Our November 15th release onwards fixed the issue before it was impacting any significant number of users. We also provided it for end-of-life 4th generation Pixels via the extended support we provide, and we provided it a workaround via GmsCompatConfig for 3rd generation Pixel users. Users are expected to update the OS within at least a couple weeks of a release. We don't plan on providing a workaround for users who aren't updating. This issue thread should be about discussing the issue filed by @blabaere, which appears to be a real problem that's not fixed yet and is going to be prioritized above everything else. This thread shouldn't be used to discuss an issue fixed in our November 15th release. It seems you've had an issue with your network blocking you from updating for a long time and that led to you missing the fix and then having the issue you do now a month later since the fix is now required. We fixed it before it impacted you, but you didn't update.

**Comment by thestinger** [comment]
[2023111500](https://grapheneos.org/releases#2023111500) release notes:

> Sandboxed Google Play compatibility layer: replace cross-user intent broadcasts with user-local ones to avoid occasional background service crashes

That's the issue you have, because you aren't updated. The issue you have is not the reason you aren't updated, because it wasn't causing issues for you last month.

**Comment by actick** [comment]
@thestinger in airport at the moment and have issues with GPS .. Location is ON but can't connect to any GPS servers anymore . Do you think  it can be related with above issue or might be due to environment I'm in now ?

**Comment by thestinger** [comment]
@actick Doesn't sound related. Are you indoors? GNSS doesn't usually work inside large concrete buildings unless you're right next to a window with clear view of the sky. Try GPSTest.

**Comment by thestinger** [comment]
@actick It's possible to use Google's network location on GrapheneOS. See https://grapheneos.org/usage#sandboxed-google-play-configuration. It requires using apps which use the Google Play geolocation such as Organic Maps from the Play Store configured to use it, disabling our rerouting of location requests to the OS in Sandboxed Google Play settings, enabling background Location permission for Play services, enabling Nearby Devices permission for Play services and enabling their network location accuracy toggle. There will be more network location options in the future. By default, GrapheneOS implements **emulated** network location via GNSS location which is unique to GrapheneOS.

**Comment by actick** [comment]
Yes I'm indoors .. Thanks for the hints.. Will try them out.

**Comment by actick** [comment]
Thanks @thestinger ... I can confirm GPS issue resolved when I got outside so seems  like you said, not related with the stacktrace

**Comment by Koru25** [comment]
I have the same issue that has been coming up for a couple of days:

```
type: crash
osVersion: google/barbet/barbet:14/UP1A.231005.007/2023102300:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 620 + 359 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a169; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhi.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14521)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14431)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by ccoroiu-boku** [comment]
I can confirm issues is resolved now. Thanks a lot @matchboxbananasynergy !! You guys rocks !

**Comment by actick** [comment]
Issues seems fixed now on my phone. Thanks a lot !
