### ISSUE TITLE
Sandboxed google play crashed

### ISSUE THREAD

**Issue by CharlieSmith** [GrapheneOS/os-issue-tracker#2876]
I am experiencing this frequently, my phone was idle on charge and playing a podcast on Podcast Addict at the time. 

`
type: crash
osVersion: google/oriole/oriole:14/UP1A.231105.003/2023110700:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 1193 + 382 ms
installer: com.android.vending
GmsCompatConfig version: 88

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a128; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhi.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-FlagsChangedIntentOperation_onHandleIntentWithRedelivery(Unknown Source:0)

`

**Comment by thestinger** [comment]
You need to keep your device updated. You have an outdated OS but a recent Play services and GmsCompatConfig. This issue was fixed in the OS around a month ago before users got the Google Play update.

**Comment by thestinger** [comment]
You're on 2023110700, a release from early November. Perhaps you dismissed the update notification and forgot about it. It was temporarily possible to dismiss after the initial update to Android 14 since Android stopped respecting sticky notifications even for system apps.
