### ISSUE TITLE
Everything is crashing whats going on?! 

### ISSUE THREAD

**Issue by Koru25** [GrapheneOS/os-issue-tracker#2881]
I keep rebooting phone hoping it will make a difference but no..

```
type: crash
osVersion: google/barbet/barbet:14/UP1A.231005.007/2023102300:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 745 + 309 ms
installer: com.android.vending
GmsCompatConfig version: 89

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a169; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at cwgw.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):10)
	at cwhi.f(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at bfsm.ff(:com.google.android.gms@234523038@23.45.23 (190400-587848529):1)
	at bfsx.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):100)
	at dvwy.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):13)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)

```

**Comment by thestinger** [comment]
You filed this already: https://github.com/GrapheneOS/os-issue-tracker/issues/2880.

The [2023111500](https://grapheneos.org/releases#2023111500) release resolved this issue on November 15th before it was an issue for you. You're on a 2 month old OS release (2023102300). You need to update.
