### ISSUE TITLE
Fix this pleeeeeaaaaase!!!

### ISSUE THREAD

**Issue by Koru25** [GrapheneOS/os-issue-tracker#2884]
```
type: crash
osVersion: google/barbet/barbet:14/UP1A.231005.007/2023102300:user/release-keys
package: com.google.android.gms:234523038
process: com.google.android.gms.persistent
processUptime: 341505 + 287 ms
installer: com.android.vending
GmsCompatConfig version: 89

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cnpu.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):455)
	at cnmu.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):9)
	at ajng.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):50)
	at ajng.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ajsl.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dvxr: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a169; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bgds.apply(:com.google.android.gms@234523038@23.45.23 (190400-587848529):5)
	at ecjp.d(:com.google.android.gms@234523038@23.45.23 (190400-587848529):3)
	at ecjq.run(:com.google.android.gms@234523038@23.45.23 (190400-587848529):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a169; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at awci.sendBroadcastAsUser(:com.google.android.gms@234523038@23.45.23 (190400-587848529):6)
	at cwgv.a(:com.google.android.gms@234523038@23.45.23 (190400-587848529):38)
	at cwgz.g(:com.google.android.gms@234523038@23.45.23 (190400-587848529):723)
	at cwgw.c(:com.google.android.gms@234523038@23.45.23 (190400-587848529):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.ha(:com.google.android.gms@234523038@23.45.23 (190400-587848529):186)
	at bgdt.call(:com.google.android.gms@234523038@23.45.23 (190400-587848529):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14521)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14431)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by Koru25** [comment]
Apologies for the multiple posts... I was getting very frustrated and it was getting late. I looked in the Apps area but there was nowhere to choose to update. I have turned phone off and on multiple times and it hasn't come up with error today so perhaps has updated in the reboot, does that sound right? Would it automatically update on reboot? Apologies again and thanks for your help

**Comment by thestinger** [comment]
@Koru25 Check Settings -> System -> System update to make sure the update client is enabled. Go to notification settings from there and make sure they're enabled. At the very least, error notifications and the reboot notification should be enabled. You can turn off the Already Updated notification channel if you don't want to be able to check that via the notification drawer collapsed at the bottom (it doesn't appear in status bar or lock screen).
