### ISSUE TITLE
Sandboxed Google Play crash

### ISSUE THREAD

**Issue by rmcgme** [GrapheneOS/os-issue-tracker#2890]
```
type: crash
osVersion: Redmi/begonia/begonia:11/RP1A.200720.011/V12.5.8.0.RGGMIXM:user/release-keys
package: com.google.android.gms:234816038
process: com.google.android.gms.persistent
processUptime: 650 + 61 ms
installer: com.android.vending
GmsCompatConfig version: 89

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a188; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3070)
	at android.os.Parcel.createException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:3030)
	at android.os.Parcel.readException(Parcel.java:2972)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5779)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cyua.a(:com.google.android.gms@234816038@23.48.16 (190400-590025996):43)
	at cyue.g(:com.google.android.gms@234816038@23.48.16 (190400-590025996):723)
	at cyub.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):7)
	at cyub.d(:com.google.android.gms@234816038@23.48.16 (190400-590025996):10)
	at cyun.f(:com.google.android.gms@234816038@23.48.16 (190400-590025996):38)
	at bgqq.fj(:com.google.android.gms@234816038@23.48.16 (190400-590025996):1)
	at bgrb.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):100)
	at dyui.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):13)
	at akan.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):50)
	at akan.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akge.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyvb: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14484)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14394)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15360)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2662)
```

**Comment by rmcgme** [comment]
```
type: crash
osVersion: Redmi/begonia/begonia:11/RP1A.200720.011/V12.5.8.0.RGGMIXM:user/release-keys
package: com.google.android.gms:234816038
process: com.google.android.gms.persistent
processUptime: 612 + 25 ms
installer: com.android.vending
GmsCompatConfig version: 89

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a188; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3070)
	at android.os.Parcel.createException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:3030)
	at android.os.Parcel.readException(Parcel.java:2972)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5779)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cyua.a(:com.google.android.gms@234816038@23.48.16 (190400-590025996):43)
	at cyue.g(:com.google.android.gms@234816038@23.48.16 (190400-590025996):723)
	at cyub.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):7)
	at cyub.d(:com.google.android.gms@234816038@23.48.16 (190400-590025996):10)
	at cyun.f(:com.google.android.gms@234816038@23.48.16 (190400-590025996):38)
	at bgqq.fj(:com.google.android.gms@234816038@23.48.16 (190400-590025996):1)
	at bgrb.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):100)
	at dyui.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):13)
	at akan.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):50)
	at akan.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akge.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyvb: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14484)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14394)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15360)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2662)


```

**Comment by thestinger** [comment]
@rmcgme You're not using GrapheneOS. This is happening due to an incomplete/outdated port of our sandboxed Google Play compatibility layer.

**Comment by thestinger** [comment]
GrapheneOS is based on Android 14 and you're on Android 11. Maintaining the compatibility layer for Android 11 isn't something we do. We're temporarily maintaining it a bit longer with reduced support for Android 13 for the extended support GrapheneOS devices.
