### ISSUE TITLE
Crash with turning Ethernet Tethering on

### ISSUE THREAD

**Issue by GOSOShero** [GrapheneOS/os-issue-tracker#2898]
Crash after enabling Ethernet tethering still exists after updating. It's annoying that I have to make my OS crash to be able to tether again. Luckily I found exactly how to reproduce it.

1. Connect your phone to another device with a LAN cable
2. Turn on Ethernet Tethering on GrapheneOS
3. Lock phone
4. Disconnect cable from phone
5. Turn on phone and try to Ethernet Tether again. You'll see Ethernet Tether is not greyed out.
6. If you click on the switch it won't turn on
7. Click on the arrow to go back to the connection menu
8. system_server crash

```
type: crash
Process: system_server
Build: google/oriole/oriole:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at android.net.connectivity.com.android.server.ethernet.EthernetNetworkFactory.getInterfaceState(EthernetNetworkFactory.java:170)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker.unicastInterfaceStateChange(EthernetTracker.java:328)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker.lambda$addListener$4(EthernetTracker.java:435)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker.$r8$lambda$u74wXsW90rogcJx8NNlJoTHWh6U(EthernetTracker.java:0)
	at android.net.connectivity.com.android.server.ethernet.EthernetTracker$$ExternalSyntheticLambda5.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by kasia-de** [comment]
> Does this still happen?

I attempted to reproduce this, following their steps (from tangorpro instead):
- Followed 1-6
- Observed that tether was disabled yet not grayed out
- I'm not sure what the "connection menu" is, but I clicked the arrow to go back
- observed no crash or unexpected behaviour.

Given that it occurred across lynx and oriole, I would presume that it should happen on tangorpro too
