### ISSUE TITLE
Sandboxed Google Play crashed

### ISSUE THREAD

**Issue by pswies** [GrapheneOS/os-issue-tracker#2904]
For a few days I have been getting random crashes of various applocations. The crash report says:

```
type: crash
osVersion: google/panther/panther:13/TQ3A.230901.001/2023100300:user/release-keys
package: com.google.android.gms:234816038
process: com.google.android.gms.persistent
processUptime: 735 + 298 ms
installer: com.android.vending
GmsCompatConfig version: 89

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a128; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at awtb.sendBroadcastAsUser(:com.google.android.gms@234816038@23.48.16 (190400-590025996):6)
	at cyua.a(:com.google.android.gms@234816038@23.48.16 (190400-590025996):43)
	at cyue.g(:com.google.android.gms@234816038@23.48.16 (190400-590025996):723)
	at cyub.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):7)
	at cyub.d(:com.google.android.gms@234816038@23.48.16 (190400-590025996):10)
	at cyun.f(:com.google.android.gms@234816038@23.48.16 (190400-590025996):38)
	at bgqq.fj(:com.google.android.gms@234816038@23.48.16 (190400-590025996):1)
	at bgrb.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):100)
	at dyui.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):13)
	at akan.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):50)
	at akan.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at akge.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyvb: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)

```

**Comment by thestinger** [comment]
The OS version you're on is very out-of-date and missing the fix for this from November:

> 2023100300

It was fixed before it was an issue for you and other users.

**Comment by thestinger** [comment]
You're on the last release not based on Android 13:

https://grapheneos.org/releases#2023100300

You're missing most of the October security patches, all of November and all of December along with all other improvements from the past several months including this fix.

**Comment by pswies** [comment]
Ahh, indeed! Thank you for the super fast and precise response, @thestinger .
