### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by Martos89** [GrapheneOS/os-issue-tracker#2912]
```
type: crash
Process: system_server
Build: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalArgumentException: Cannot change userId for '/data/user_de/12/com.google.android.gms/app_chimera/m/0000000e/CronetDynamite.apk' from 11 to 12
	at com.android.server.pm.dex.PackageDynamicCodeLoading$PackageDynamicCode.add(PackageDynamicCodeLoading.java:542)
	at com.android.server.pm.dex.PackageDynamicCodeLoading$PackageDynamicCode.-$$Nest$madd(PackageDynamicCodeLoading.java:0)
	at com.android.server.pm.dex.PackageDynamicCodeLoading.record(PackageDynamicCodeLoading.java:122)
	at com.android.server.pm.dex.DynamicCodeLogger.recordDex(DynamicCodeLogger.java:232)
	at com.android.server.pm.DynamicCodeLoggingService.syncDataFromArtService(DynamicCodeLoggingService.java:158)
	at com.android.server.pm.DynamicCodeLoggingService.-$$Nest$smsyncDataFromArtService(DynamicCodeLoggingService.java:0)
	at com.android.server.pm.DynamicCodeLoggingService$IdleLoggingThread.run(DynamicCodeLoggingService.java:181)

```

**Comment by thestinger** [comment]
Looks like a known upstream bug. We'd need more information on how you triggered it to do anything.

**Comment by Martos89** [comment]
I just put it on charge during the night

Marcello Torre
***@***.***

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Martos89** [comment]
Hi,

This keeps happening overnight while i charge my phone. I have been using a double charger which I use for me and my partner since we are abroad, which also means that I am currently roaming. Could this be related. I also noticed that the battery is draining rapidly.

Thank you.

Marcello Torre
***@***.***

Sent from Proton Mail mobile

-------- Original Message --------
