### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by crptkng** [GrapheneOS/os-issue-tracker#2918]
```
type: crash
Process: unknown
Build: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ExceptionInInitializerError
	at app.grapheneos.apps.ApplicationImpl.attachBaseContext(Unknown Source:14)
	at android.app.Application.attach(Application.java:352)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1287)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2248)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 10) is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:609)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:592)
	at app.grapheneos.apps.PackageStates.<clinit>(Unknown Source:282)
	... 17 more

```

**Comment by thestinger** [comment]
When did this happen?

**Comment by thestinger** [comment]
Looks like a weird upstream bug we've seen a few times.

**Comment by crptkng** [comment]
> When did this happen?

This happened the day of reporting to issue tracker. I have my phone set to reboot periodically. Appears to have happened while the phone was dormant.

**Comment by crptkng** [comment]
Developer option is/was closed at time of crash

**Comment by thestinger** [comment]
Closing in favor of https://github.com/GrapheneOS/os-issue-tracker/issues/2870.
