### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Je1312** [GrapheneOS/os-issue-tracker#2920]
```
type: crash
Process: unknown
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:572)
	at android.app.PendingIntent.getActivity(PendingIntent.java:559)
	at android.app.PendingIntent.getActivity(PendingIntent.java:523)
	at org.torproject.android.service.OrbotService.showToolbarNotification(OrbotService.java:178)
	at org.torproject.android.service.OrbotService.showBandwidthNotification(OrbotService.java:1104)
	at org.torproject.android.service.OrbotRawEventListener.handleBandwidth(OrbotRawEventListener.java:83)
	at org.torproject.android.service.OrbotRawEventListener.onEvent(OrbotRawEventListener.java:43)
	at net.freehaven.tor.control.TorControlConnection.handleEvent(TorControlConnection.java:240)
	at net.freehaven.tor.control.TorControlConnection.react(TorControlConnection.java:382)
	at net.freehaven.tor.control.TorControlConnection$ControlParseThread.run(TorControlConnection.java:352)

```

**Comment by thestinger** [comment]
More details needed.
