### ISSUE TITLE
Server_system has crashed reported

### ISSUE THREAD

**Issue by sbarnard86** [GrapheneOS/os-issue-tracker#2922]
Received a notification that server_system has crashed. Never seen this before and thought it might be important to report. 

```
type: crash
Process: unknown
Build: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.calendar/androidx.startup.InitializationProvider}
	at android.app.ActivityThread.installProvider(ActivityThread.java:7809)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7315)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7022)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2248)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: androidx.startup.StartupException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.calendar/androidx.startup.InitializationProvider}
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:209)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:49)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7804)
	... 13 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.calendar/androidx.startup.InitializationProvider}
	at android.app.ApplicationPackageManager.getProviderInfo(ApplicationPackageManager.java:645)
	at android.app.ApplicationPackageManager.getProviderInfo(ApplicationPackageManager.java:628)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:205)
	... 17 more

```

**Comment by crptkng** [comment]
this is the same report as #2918

**Comment by thestinger** [comment]
It's not the same.

**Comment by joshiegy** [comment]
Same here... Again...
```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'com.android.wifi.x.android.hardware.wifi.StaBackgroundScanCapabilities com.android.wifi.x.android.hardware.wifi.IWifiStaIface.getBackgroundScanCapabilities()' on a null object reference
	at com.android.server.wifi.hal.WifiStaIfaceAidlImpl.getBackgroundScanCapabilities(WifiStaIfaceAidlImpl.java:243)
	at com.android.server.wifi.hal.WifiStaIface.lambda$getBackgroundScanCapabilities$6(WifiStaIface.java:202)
	at com.android.server.wifi.hal.WifiStaIface.$r8$lambda$_EbJ5ihVCnh9jcPe1DVklmaHw0c(WifiStaIface.java:0)
	at com.android.server.wifi.hal.WifiStaIface$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:0)
	at com.android.server.wifi.hal.WifiStaIface.validateAndCall(WifiStaIface.java:142)
	at com.android.server.wifi.hal.WifiStaIface.getBackgroundScanCapabilities(WifiStaIface.java:201)
	at com.android.server.wifi.WifiVendorHal.getBgScanCapabilities(WifiVendorHal.java:579)
	at com.android.server.wifi.WifiNative.getBgScanCapabilities(WifiNative.java:3174)
	at com.android.server.wifi.scanner.WifiScannerImpl$1.create(WifiScannerImpl.java:63)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.setupScannerImpls(WifiScanningServiceImpl.java:741)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.lambda$setScanningEnabled$1(WifiScanningServiceImpl.java:204)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.$r8$lambda$D_ymntbRb7H5O15mR0WYDlVLPp0(WifiScanningServiceImpl.java:0)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by joshiegy** [comment]
This time I used fb messenger and was swiping to go back to the homescreen

**Comment by AlexanderHott** [comment]
```
type: crash
Process: system_server
Build: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'com.android.wifi.x.android.hardware.wifi.StaBackgroundScanCapabilities com.android.wifi.x.android.hardware.wifi.IWifiStaIface.getBackgroundScanCapabilities()' on a null object reference
	at com.android.server.wifi.hal.WifiStaIfaceAidlImpl.getBackgroundScanCapabilities(WifiStaIfaceAidlImpl.java:243)
	at com.android.server.wifi.hal.WifiStaIface.lambda$getBackgroundScanCapabilities$6(WifiStaIface.java:202)
	at com.android.server.wifi.hal.WifiStaIface.$r8$lambda$_EbJ5ihVCnh9jcPe1DVklmaHw0c(WifiStaIface.java:0)
	at com.android.server.wifi.hal.WifiStaIface$$ExternalSyntheticLambda1.get(R8$$SyntheticClass:0)
	at com.android.server.wifi.hal.WifiStaIface.validateAndCall(WifiStaIface.java:142)
	at com.android.server.wifi.hal.WifiStaIface.getBackgroundScanCapabilities(WifiStaIface.java:201)
	at com.android.server.wifi.WifiVendorHal.getBgScanCapabilities(WifiVendorHal.java:579)
	at com.android.server.wifi.WifiNative.getBgScanCapabilities(WifiNative.java:3174)
	at com.android.server.wifi.scanner.WifiScannerImpl$1.create(WifiScannerImpl.java:63)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.setupScannerImpls(WifiScanningServiceImpl.java:741)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.lambda$setScanningEnabled$1(WifiScanningServiceImpl.java:204)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl.$r8$lambda$D_ymntbRb7H5O15mR0WYDlVLPp0(WifiScanningServiceImpl.java:0)
	at com.android.server.wifi.scanner.WifiScanningServiceImpl$$ExternalSyntheticLambda9.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```

I toggled wifi off and on while not having mobile data.

**Comment by thestinger** [comment]
Neither of these is the same as the initial issue.

**Comment by AlexanderHott** [comment]
> Neither of these is the same as the initial issue.

Should I open a new one? It's hard to tell for a non-os developer and I usually try not to create duplicate issues

**Comment by thestinger** [comment]
No, it's at https://github.com/GrapheneOS/os-issue-tracker/issues/2735.

**Comment by thestinger** [comment]
@sbarnard86 Has it happened again?

**Comment by muhomorr** [comment]
This is not a system_server crash. It's being reported that way due to an upstream crash handling bug.
