### ISSUE TITLE
gms crash report

### ISSUE THREAD

**Issue by BlaineRas** [GrapheneOS/os-issue-tracker#2930]
```
type: crash
osVersion: google/husky/husky:14/UQ1A.231205.015/2023121200:user/release-keys
package: com.google.android.gms:234816039
process: com.google.android.gms
processUptime: 21799726 + 309 ms
installer: com.android.vending
GmsCompatConfig version: 89

eflz: rethrowing error from lowpool[26]
	at ajzw.run(:com.google.android.gms@234816039@23.48.16 (190408-590025996):27)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at bhch.lL(:com.google.android.gms@234816039@23.48.16 (190408-590025996):1)
	at bhch.dispatchMessage(:com.google.android.gms@234816039@23.48.16 (190408-590025996):143)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: dyvb: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.semanticlocationhistory-StoreVisitsProcessingService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~aWv0Za6xZmi_D2DX_hZIzw==/com.google.android.gms-MZQ6dwcVxzOEZyzYDpB4jw==/base.apk!/lib/arm64-v8a/libgeller_jni_lite_lib.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.google.android.gms.semanticlocationhistory.deidentifieddata.storevisits.StoreVisitsProcessingService.hc(:com.google.android.gms@234816039@23.48.16 (190408-590025996):118)
	at bhdx.call(:com.google.android.gms@234816039@23.48.16 (190408-590025996):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at akan.c(:com.google.android.gms@234816039@23.48.16 (190408-590025996):50)
	at akan.run(:com.google.android.gms@234816039@23.48.16 (190408-590025996):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akge.run(:com.google.android.gms@234816039@23.48.16 (190408-590025996):8)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
Appears to be installed incorrectly. More information required on whether it's still occurring.
