### ISSUE TITLE
System Crash on Pixel 6a

### ISSUE THREAD

**Issue by JackMadeley** [GrapheneOS/os-issue-tracker#2947]
Hi all,

I am running the latest version of Graphene OS on a Pixel 6a and last night my phone crashed out of nowhere, here is the logs

```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x4000010 (has extras) } in com.android.server.ext.BluetoothAutoOff$1@48440b9
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.bluetooth.gatt.GattNativeInterface.gattClientGetDeviceType(java.lang.String)' on a null object reference
	at com.android.bluetooth.gatt.GattService.getDeviceType(GattService.java:4770)
	at com.android.bluetooth.gatt.GattService.getDevicesMatchingConnectionStates(GattService.java:3086)
	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.getDevicesMatchingConnectionStates(GattService.java:626)
	at com.android.bluetooth.gatt.GattService$BluetoothGattBinder.getDevicesMatchingConnectionStates(GattService.java:615)
	at android.bluetooth.IBluetoothGatt$Stub.onTransact(IBluetoothGatt.java:521)
	at android.os.Binder.execTransactInternal(Binder.java:1366)
	at android.os.Binder.execTransact(Binder.java:1302)

```

There is no problem with my phone now after a reboot, but just reporting here in case anyone else experienced the same.

**Comment by muhomorr** [comment]
This crash is due to a race condition in the Bluetooth auto-off code.

**Comment by rsssxd** [comment]
```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys
uid: 10107 (u:r:platform_app:s0:c512,c768)
cmdline: com.android.systemui
processUptime: 61537s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62e64)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664, pc 292d48)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324, pc 2952ac)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840d0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a67f4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf9ec)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64730)
```

**Comment by thestinger** [comment]
@rsssxd That's not the same issue, that's this upstream one: https://github.com/GrapheneOS/os-issue-tracker/issues/2700
