### ISSUE TITLE
GFS dependent app crashes

### ISSUE THREAD

**Issue by jibarofoss** [GrapheneOS/os-issue-tracker#2969]
App crashes when trying to log in, yielding the following stack trace. All permissions the app asks for were granted. App is https://play.google.com/store/apps/details?id=com.popular.android.mibanco&hl=en&gl=US.
```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.231205.015/2023121200:user/release-keys
package: com.popular.android.mibanco:176
process: com.popular.android.mibanco
processUptime: 7124 + 205 ms
installer: com.aurora.store

java.lang.NullPointerException: packageName can't be null
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getCellLocation(ITelephony.java:8696)
	at android.telephony.TelephonyManager.getCellLocation(TelephonyManager.java:2503)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.getCellTowerId(CollectDeviceData.java:835)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.collectDeviceLocationAndNetworkData(CollectDeviceData.java:337)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.collectDeviceData(CollectDeviceData.java:220)
	at com.rsa.mobilesdk.sdk.CollectDeviceData.startCollection(CollectDeviceData.java:191)
	at com.rsa.mobilesdk.sdk.MobileAPI.initAndValidateProperties(MobileAPI.java:671)
	at com.rsa.mobilesdk.sdk.MobileAPI.initSDK(MobileAPI.java:459)
	at com.popular.android.mibanco.util.RSACollectUtils.collectDeviceInfo(RSACollectUtils.java:33)
	at com.popular.android.mibanco.task.AsyncTasks.login(AsyncTasks.java:1934)
	at com.popular.android.mibanco.activity.EnterUsername.login(EnterUsername.java:760)
	at com.popular.android.mibanco.activity.EnterUsername.savedData(EnterUsername.java:692)
	at com.popular.android.mibanco.task.AsyncTasks$StartTask.onPostExecute(AsyncTasks.java:1659)
	at com.popular.android.mibanco.task.AsyncTasks$StartTask.onPostExecute(AsyncTasks.java:1587)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by thestinger** [comment]
@jibarofoss Is this in the main profile or a secondary user / work profile?

**Comment by jibarofoss** [comment]
Secondary profile.

**Comment by thestinger** [comment]
@jibarofoss It's worth trying to see if it happens in the main user. This looks like an upstream Android 14 bug. We worked around it for system components.

**Comment by thestinger** [comment]
@jibarofoss It's worth trying to see if it happens in the main user. This looks like it could be an upstream Android 14 bug with user profiles.
