### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by olsonperrensen** [GrapheneOS/os-issue-tracker#2973]
```
type: crash
Process: system_server
Build: google/panther/panther:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Service is unavailable: null
	at com.android.bluetooth.le_audio.LeAudioService$BluetoothLeAudioBinder.registerCallback(LeAudioService.java:3497)
	at android.bluetooth.IBluetoothLeAudio$Stub.onTransact(IBluetoothLeAudio.java:469)
	at android.os.Binder.execTransactInternal(Binder.java:1366)
	at android.os.Binder.execTransact(Binder.java:1302)

```

**Comment by thestinger** [comment]
May already be resolved by the upcoming release.
