### ISSUE TITLE
Keyboard crash 

### ISSUE THREAD

**Issue by heckarman** [GrapheneOS/os-issue-tracker#2978]
Keyboard being used is Open board by Helium314 with default keyboard's spell check resulting in this. Unless I change the spell check to Openboard spell check, it keeps on crashing every time keyboard dpops up for typing.

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023123000:user/release-keys
package: com.android.inputmethod.latin:30
process: com.android.inputmethod.latin
processUptime: 143 + 402 ms

java.lang.RuntimeException: Unable to create service com.android.inputmethod.latin.spellcheck.AndroidSpellCheckerService: java.lang.RuntimeException: RichInputMethodManager is used before initialization
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4701)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2276)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.RuntimeException: RichInputMethodManager is used before initialization
	at com.android.inputmethod.latin.RichInputMethodManager.checkInitialized(RichInputMethodManager.java:90)
	at com.android.inputmethod.latin.RichInputMethodManager.getInstance(RichInputMethodManager.java:76)
	at com.android.inputmethod.latin.spellcheck.AndroidSpellCheckerService.fetchEnabledLocales(AndroidSpellCheckerService.java:125)
	at com.android.inputmethod.latin.spellcheck.AndroidSpellCheckerService.onCreate(AndroidSpellCheckerService.java:111)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4688)
	... 11 more

```

**Comment by thestinger** [comment]
Should be fixed by https://github.com/GrapheneOS/platform_packages_inputmethods_LatinIME/pull/22 for today's release.

**Comment by heckarman** [comment]
Can I get singer context on this as to why it was crashing?

**Comment by thestinger** [comment]
We've been trying to fix upstream bugs in the spell checking implementation which has caused new bugs. Yesterday's alpha channel release fixed most of the issues but introduced a crash after the OS kills the spell checking service.

**Comment by heckarman** [comment]
Why stork check service is being killed by the OS? Trying to not keep it rubbing even after the keyboard goes away?

**Comment by thestinger** [comment]
It's killing it to save resources. It's standard for non-foreground services to get quickly killed off. Apps can't just run stuff continuously without a foreground service. It's not normally actually killing the app as a whole, just reducing the resources it uses.
