### ISSUE TITLE
Everything is crashing

### ISSUE THREAD

**Issue by Bowc99** [GrapheneOS/os-issue-tracker#2982]
Everything is crashing. I've turned phone off a few times but no updates install. Can anyone advise?

```
type: crash
osVersion: google/barbet/barbet:14/UP1A.231005.007/2023102300:user/release-keys
package: com.google.android.gms:234816038
process: com.google.android.gms.persistent
processUptime: 940 + 283 ms
installer: com.android.vending
GmsCompatConfig version: 90

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a169; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cyua.a(:com.google.android.gms@234816038@23.48.16 (190400-590025996):43)
	at cyue.g(:com.google.android.gms@234816038@23.48.16 (190400-590025996):723)
	at cyub.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):7)
	at cyub.d(:com.google.android.gms@234816038@23.48.16 (190400-590025996):10)
	at cyun.f(:com.google.android.gms@234816038@23.48.16 (190400-590025996):38)
	at bgqq.fj(:com.google.android.gms@234816038@23.48.16 (190400-590025996):1)
	at bgrb.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):100)
	at dyui.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):13)
	at akan.c(:com.google.android.gms@234816038@23.48.16 (190400-590025996):50)
	at akan.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akge.run(:com.google.android.gms@234816038@23.48.16 (190400-590025996):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyvb: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)

```

**Comment by thestinger** [comment]
@Bowc99 You're on the 2023102300 release. The current version is 2023123100. You fell too far behind but have GmsCompatConfig and sandboxed Google Play updates beyond what was supported by 2023102300. You're going to need to update. You likely disabled the update client or changed the settings in a way that you don't get updates. There is a problem with people disabling updates but not remembering they did it.

**Comment by Bowc99** [comment]
How do I fix this? Do I need to do it from the Owner profile or can I do it in the sandboxes profile? If you could explain what to do that would be great thanks ;)

**Comment by thestinger** [comment]
The update client only runs in the Owner user and can't be configured from other users. You need to update GrapheneOS. You're on a release from October 23rd and it's currently January 1st. You're missing the November and December security patches, along with a lot of other changes including support for running the Play services version you have installed as part of sandboxed Google Play. You're going to need to determine why you've fallen so far behind on updates, likely because you either disabled the OS update client or disabled the Network permission for it, which is highly recommended against but we don't stop you doing it. You may have also changed it to only using Unmetered networks while only being connected to metered networks (mobile data). We don't have your device and don't know what you've changed. By default, users get automatic updates on all available networks and the update client shows notifications about all update checks including error messages as low importance (visible on status bar / lockscreen and not collapsed) notifications and minimum importance (not visible on status bar / lockscreen and collapsed at the bottom) notifications about the device already being up-to-date. If you don't have those notifications in the Owner user, you must have disabled updates.

**Comment by thestinger** [comment]
> or can I do it in the sandboxes profile

You don't need to use a dedicated user or work profile for sandboxed Google Play to be sandboxed. They're regular sandboxed apps. It has no special interaction with profiles. Profiles work the same way for it as other apps with the same benefits of acting as separate workspaces with separate apps/data where apps can't see each other or communicate across them.

**Comment by Bowc99** [comment]
Thanks for your responses. I have checked all settings and nothing was switched off, everything is set to update. I have checked for updates and nothing been found so now I am stuck with not knowing what to do next. I havent meddled with settings to turn off updates as I know how important they are. If you have any suggestions for how to rectify that would be really helpful. I am at a loss as.to how to fix this. Thanks

**Comment by Bowc99** [comment]
It is not on metered only access either. I havent changed anything like that, just been using my phone since I got it, tbh I'm not that tech savvy with modern tech lol so wouldnt have known to check this. My phone has bene updating when ive turned on and off ok and grapheme is has recently updated

**Comment by Bowc99** [comment]
*wouldnt have known to change this not check

**Comment by thestinger** [comment]
You're on 2023102300 so it hasn't recently updated the OS, only apps.

**Comment by thestinger** [comment]
@Bowc99 You should be getting notifications for the update client saying what's happening. If you turned off the notifications, turn them back on.
