### ISSUE TITLE
Android Auto crashes when I turn off my car.

### ISSUE THREAD

**Issue by zachvlat** [GrapheneOS/os-issue-tracker#2988]
```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.231205.015/2023123100:user/release-keys
package: com.google.android.projection.gearhead:110635014
process: com.google.android.projection.gearhead:projection
processUptime: 6402685 + 363 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 90

java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/0000002b/CronetDynamite.apk!/lib/arm64-v8a/libcronet.119.0.6045.31.so" segment 1: Permission denied
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at org.chromium.net.impl.CronetLibraryLoader.a(:com.google.android.gms.dynamite_cronetdynamite@234816038@23.48.16 (190400-0):51)
	at org.chromium.net.impl.CronetUrlRequestContext.<init>(:com.google.android.gms.dynamite_cronetdynamite@234816038@23.48.16 (190400-0):10)
	at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(:com.google.android.gms.dynamite_cronetdynamite@234816038@23.48.16 (190400-0):14)
	at aers.build(SourceFile:7)
	at org.chromium.net.ExperimentalCronetEngine$Builder.build(SourceFile:2)
	at vis.a(SourceFile:39)
	at yae.a(SourceFile:1)
	at rlo.a(SourceFile:81)
	at yae.a(SourceFile:1)
	at rxz.b(SourceFile:1)
	at myt.a(SourceFile:10)
	at yae.a(SourceFile:1)
	at yaj.a(SourceFile:1)
	at yae.a(SourceFile:1)
	at vye.a(SourceFile:55)
	at uam.a(SourceFile:1)
	at mso.b(SourceFile:4)
	at mso.a(SourceFile:4)
	at mso.f(SourceFile:16)
	at muq.a(SourceFile:4)
	at rnb.d(SourceFile:24)
	at rlh.b(SourceFile:8)
	at rlk.r(SourceFile:7)
	at rlk.l(SourceFile:15)
	at qxk.p(SourceFile:4)
	at qxk.l(SourceFile:1)
	at rlk.g(SourceFile:19)
	at rlk.c(SourceFile:5)
	at qxk.<init>(SourceFile:31)
	at qxo.j(SourceFile:50)
	at qxo.a(SourceFile:2)
	at qxo.h(SourceFile:1)
	at qxo.c(SourceFile:2)
	at qns.j(SourceFile:3)
	at qns.e(SourceFile:1)
	at vvr.at(SourceFile:72)
	at ruu.onCreate(SourceFile:4)
	at pkg.b(SourceFile:1)
	at poj.c(SourceFile:2)
	at ruv.m(SourceFile:4)
	at pkk.o(SourceFile:6)
	at pkk.b(SourceFile:1)
	at com.google.android.libraries.maps.MapView.onCreate(SourceFile:4)
	at com.google.android.apps.auto.components.apphost.view.widgets.maps.MapViewContainerImpl.cI(SourceFile:1)
	at ecz.bR(SourceFile:8)
	at eea.a(SourceFile:3)
	at eeb.j(SourceFile:23)
	at eeb.g(SourceFile:2)
	at eeb.e(SourceFile:3)
	at com.google.android.apps.auto.components.apphost.view.widgets.maps.MapViewContainerImpl.g(SourceFile:1)
	at hrj.b(SourceFile:2)
	at hgs.run(SourceFile:36)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by zachvlat** [comment]
> What version is your AppCompatConfig in the OS? This has already been resolved in the most recent AppCompatConfig update, as seen in the following changelog: https://github.com/GrapheneOS/platform_packages_apps_AppCompatConfig/releases/tag/3

I m on version 21.

**Comment by zachvlat** [comment]
> > > What version is your AppCompatConfig in the OS? This has already been resolved in the most recent AppCompatConfig update, as seen in the following changelog: https://github.com/GrapheneOS/platform_packages_apps_AppCompatConfig/releases/tag/3
> > 
> > 
> > I m on version 21.
> 
> That would be the version of "Apps", not AppCompatConfig. Please open your app drawer, and then click on the "Apps" app. Then, press on the three dots on the top right corner, and tap "All packages". You will find AppCompatConfig there. Tap on that, and make sure you're up to date and have version 3 of that. If not, update.

It's version 3

**Comment by thestinger** [comment]
@zachvlat The crash would have been from before you were on version 3.
