### ISSUE TITLE
GrapheneOS - Android Auto Crash

### ISSUE THREAD

**Issue by corvusfan23** [GrapheneOS/os-issue-tracker#2996]
```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.231205.015/2023123100:user/release-keys
package: com.google.android.projection.gearhead:110635014
process: com.google.android.projection.gearhead:car
processUptime: 4015900 + 327 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 90

java.lang.IllegalStateException: Failed to register vehicle with CDM
	at hfs.m(SourceFile:13)
	at hfs.c(SourceFile:7)
	at ncr.run(SourceFile:8)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Application must hold android.permission.REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION to associate with a device with android.app.role.SYSTEM_AUTOMOTIVE_PROJECTION profile.
	at dim.k(SourceFile:4)
	at dim.get(SourceFile:16)
	at dir.get(SourceFile:2)
	at hfs.m(SourceFile:5)
	... 7 more
Caused by: java.lang.SecurityException: Application must hold android.permission.REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION to associate with a device with android.app.role.SYSTEM_AUTOMOTIVE_PROJECTION profile.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.companion.ICompanionDeviceManager$Stub$Proxy.associate(ICompanionDeviceManager.java:741)
	at android.companion.CompanionDeviceManager.associate(CompanionDeviceManager.java:394)
	at hdm.a(SourceFile:12)
	at hfl.a(SourceFile:7)
	at cxu.b(SourceFile:3)
	at hfs.m(SourceFile:4)
	... 7 more

```

------------------------------------------

Forgive me if there is more that you may need. I am happy to help get to the bottom of this! Thank you

**Comment by muhomorr** [comment]
Have you granted permission for wired or wireless Android Auto in Settings -> Apps -> Sandboxed Google Play -> Android Auto?

**Comment by corvusfan23** [comment]
I was dumb, and looked under Settings -> Apps -> Google Play Services rather than under Sandboxed Google Play -> Android Auto.

I have not been able to go back to my car to test since seeing your response, but thank you so much for such a quick response. I feel dumb for not seeing those options.

Thank you so much.
