### ISSUE TITLE
Android Auto keeps crashing

### ISSUE THREAD

**Issue by macsternz** [GrapheneOS/os-issue-tracker#3000]
Installed AA via GOS AppStore after the last update. When I connect to the car a message pops up, saying that AA has crashed. After reattaching the cable AA doesn't open at all. It never comes back to live. Only a new install of AA brings it back, but the same result - "Android Auto has crashed"

**Comment by thestinger** [comment]
Did you permit the access it requires with the toggles?

**Comment by macsternz** [comment]
```
type: crash
osVersion: google/panther/panther:14/UQ1A.231205.015/2023123100:user/release-keys
package: com.google.android.projection.gearhead:110635014
process: com.google.android.projection.gearhead:car
processUptime: 189698 + 442 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 90

java.lang.IllegalStateException: Failed to register vehicle with CDM
	at hfs.m(SourceFile:13)
	at hfs.c(SourceFile:7)
	at ncr.run(SourceFile:8)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Application must hold android.permission.REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION to associate with a device with android.app.role.SYSTEM_AUTOMOTIVE_PROJECTION profile.
	at dim.k(SourceFile:4)
	at dim.get(SourceFile:16)
	at dir.get(SourceFile:2)
	at hfs.m(SourceFile:5)
	... 7 more
Caused by: java.lang.SecurityException: Application must hold android.permission.REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION to associate with a device with android.app.role.SYSTEM_AUTOMOTIVE_PROJECTION profile.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.companion.ICompanionDeviceManager$Stub$Proxy.associate(ICompanionDeviceManager.java:741)
	at android.companion.CompanionDeviceManager.associate(CompanionDeviceManager.java:394)
	at hdm.a(SourceFile:12)
	at hfl.a(SourceFile:7)
	at cxu.b(SourceFile:3)
	at hfs.m(SourceFile:4)
	... 7 more

```

**Comment by thestinger** [comment]
It doesn't sound like you've enabled support for Android Auto. You can't simply install it and used it. It requires special privileges.

**Comment by thestinger** [comment]
There are settings in the Sandboxed Google Play settings in Settings -> Apps.

**Comment by macsternz** [comment]
I only have Google Play Services in Apps under settings not "Sandboxed Google Play"

**Comment by thestinger** [comment]
No, Settings -> Apps has settings for it. Not talking about an app.

Please look at https://grapheneos.org/usage#sandboxed-google-play-configuration. It doesn't specifically cover Android Auto yet but it shows where the configuration is.

**Comment by macsternz** [comment]
Sorry guys. I've found it. I honestly have never seen this entry in Apps. Now I have found it and switched all the toggles. 
Sorry again. Can we delete the post?

**Comment by thestinger** [comment]
Yes, it can be deleted if you want.
