### ISSUE TITLE
System crashed after click on bluetooth button in quick controls panel

### ISSUE THREAD

**Issue by nmzein** [GrapheneOS/os-issue-tracker#3005]
type: crash
Process: system_server
Build: google/shiba/shiba:14/UQ1A.231205.015/2023123100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Service is unavailable: null
	at com.android.bluetooth.le_audio.LeAudioService$BluetoothLeAudioBinder.registerCallback(LeAudioService.java:3497)
	at android.bluetooth.IBluetoothLeAudio$Stub.onTransact(IBluetoothLeAudio.java:469)
	at android.os.Binder.execTransactInternal(Binder.java:1366)
	at android.os.Binder.execTransact(Binder.java:1302)

**Comment by h2dden** [comment]
phone restarted out of the blue:
```
type: crash
Process: system_server
Build: google/husky/husky:14/UQ1A.[231205.015](tel:231205.015)/[2023123100](tel:2023123100):user/release-keys
Crash-Handler: [com.android.internal.os.RuntimeInit](http://com.android.internal.os.runtimeinit/)$KillApplicationHandler
Loading-Progress: [1.0](tel:1.0)
Dropped-Count: 0

[java.lang.IllegalArgumentException](http://java.lang.illegalargumentexception/): Cannot change userId for '/data/user/10/[com.google.android.gms/app_dg_cache/1FF1CAAF27B5C2D89CCDAAC2580B20511F43612A/the.apk](http://com.google.android.gms/app_dg_cache/1FF1CAAF27B5C2D89CCDAAC2580B20511F43612A/the.apk)' from 11 to 10
at [com.android.server.pm.dex.PackageDynamicCodeLoading](http://com.android.server.pm.dex.packagedynamiccodeloading/)$[PackageDynamicCode.add](http://packagedynamiccode.add/)([PackageDynamicCodeLoading.java:542](http://packagedynamiccodeloading.java:542/))
at [com.android.server.pm.dex.PackageDynamicCodeLoading](http://com.android.server.pm.dex.packagedynamiccodeloading/)$PackageDynamicCode.-$$Nest$madd([PackageDynamicCodeLoading.java:0](http://packagedynamiccodeloading.java:0/))
at [com.android.server.pm.dex.PackageDynamicCodeLoading.record](http://com.android.server.pm.dex.packagedynamiccodeloading.record/)([PackageDynamicCodeLoading.java:122](http://packagedynamiccodeloading.java:122/))
at [com.android.server.pm.dex.DynamicCodeLogger.recordDex](http://com.android.server.pm.dex.dynamiccodelogger.recorddex/)([DynamicCodeLogger.java:232](http://dynamiccodelogger.java:232/))
at [com.android.server.pm.DynamicCodeLoggingService.syncDataFromArtService](http://com.android.server.pm.dynamiccodeloggingservice.syncdatafromartservice/)([DynamicCodeLoggingService.java:158](http://dynamiccodeloggingservice.java:158/))
at [com.android.server.pm.DynamicCodeLoggingService](http://com.android.server.pm.dynamiccodeloggingservice/).-$$Nest$smsyncDataFromArtService([DynamicCodeLoggingService.java:0](http://dynamiccodeloggingservice.java:0/))
at [com.android.server.pm.DynamicCodeLoggingService](http://com.android.server.pm.dynamiccodeloggingservice/)$[IdleLoggingThread.run](http://idleloggingthread.run/)([DynamicCodeLoggingService.java:181](http://dynamiccodeloggingservice.java:181/))

```

**Comment by thestinger** [comment]
@h2dden  Not related

**Comment by h2dden** [comment]
opened a new ticket. kudos
