### ISSUE TITLE
perpetual sandbox google play crashing

### ISSUE THREAD

**Issue by jacurutu-antoineb** [GrapheneOS/os-issue-tracker#3016]
Running a pixel 4a
android version 13

Installed Graphene several months ago - things have been working terrific up until about 3 weeks ago. Sandboxed Google Play crashes then perpetually crashes. The impact is that many apps no longer load (X, meater, ..). The google keyboard (for swipe) is one of those apps so my keyboard comes up, disappears, etc. If I uninstall Google Play Services apps start working again without a reboot. 
When this crash does occurs (it perpetually reboots and kills my apps), I have to reboot the phone for apps to start working. they work until google play starts crashing again. (I need google play services for speech services for duolingo)

type: crash
osVersion: google/sunfish/sunfish:13/TQ2A.230505.002/2023050500:user/release-keys
package: com.google.android.gms:234914038
process: com.google.android.gms.persistent
processUptime: 145663 + 610 ms
GmsCompatConfig version: 90
java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a144; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at cysl.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):43)
	at cysn.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):11)
	at akas.c(:com.google.android.gms@234914038@23.49.14 (190400-590296185):50)
	at akas.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at akgh.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyxu:
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2270)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13703)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13655)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14533)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2304)

**Comment by thestinger** [comment]
Your install is incredibly out-of-date. You need to update. This issue was fixed in November before users were experiencing it due to having a new Play services version.

**Comment by thestinger** [comment]
This is the version you have:

> 2023050500

You're on a release from May 2023. Pixel 4a went end-of-life after August 2023, so you're missing months of regular updates, then extended support and legacy extended support releases. One of those legacy extended support releases in November backported a fix for this issue with new Play services versions long before you were experiencing it.

This is the current version for Pixel 4a (sunfish):

> 2023122200

Like the other 4th generation Pixels, the Pixel 4a is end-of-life and lacks firmware and driver security patches. We provide legacy extended support releases with the Android 13 security backports and other patches.

You should replace the device with one that has full security updates available, but you should still be installing the updates that are available in the meantime.
