### ISSUE TITLE
WPA2-Enterprise Trust Certificate on First use crashes system_server

### ISSUE THREAD

**Issue by ORIOLESFan02** [GrapheneOS/os-issue-tracker#3040]
```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240105.004/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.server.wifi.ClientModeImpl.ACTION_CERT_NOTIF_TAP flg=0x10 pkg=android (has extras) } in com.android.server.wifi.InsecureEapNetworkHandler$1@eed591c
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1819)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.server.wifi.util.CertificateSubjectInfo.commonName' on a null object reference in method 'void com.android.server.wifi.InsecureEapNetworkHandler.askForUserApprovalForCaCertificate()'
	at com.android.server.wifi.InsecureEapNetworkHandler.askForUserApprovalForCaCertificate(InsecureEapNetworkHandler.java:662)
	at com.android.server.wifi.InsecureEapNetworkHandler.-$$Nest$maskForUserApprovalForCaCertificate(InsecureEapNetworkHandler.java:0)
	at com.android.server.wifi.InsecureEapNetworkHandler$1.onReceive(InsecureEapNetworkHandler.java:136)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1811)
	... 7 more

```

**Comment by thestinger** [comment]
Looks like a bug in how it handles an invalid certificate, but the issue is that the certificate is invalid.

**Comment by iMonZ** [comment]
> Looks like a bug in how it handles an invalid certificate, but the issue is that the certificate is invalid.

Same issue. With WPA3 Enterprise and a valid certificate. I can't connect to the WiFi Network
