### ISSUE TITLE
Google Play  keeps crashing

### ISSUE THREAD

**Issue by martinlk27** [GrapheneOS/os-issue-tracker#3045]
```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023102300:user/release-keys
package: com.google.android.gms:234914038
process: com.google.android.gms.persistent
processUptime: 76069 + 507 ms
installer: com.android.vending
GmsCompatConfig version: 90

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a130; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cysl.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):43)
	at cysn.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):11)
	at akas.c(:com.google.android.gms@234914038@23.49.14 (190400-590296185):50)
	at akas.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akgh.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyxu: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)

```

**Comment by thestinger** [comment]
You're on a release from October and need to update. This was resolved in November long before it was an issue for you.
