### ISSUE TITLE
Android Auto crashed when turning off car. Pixel7 with Carlinkit 4.0 attached to vehicle.

### ISSUE THREAD

**Issue by nlroth** [GrapheneOS/os-issue-tracker#3050]
Here is the crash report....

```
type: crash
osVersion: google/panther/panther:14/UQ1A.240105.004/2024010400:user/release-keys
package: com.google.android.projection.gearhead:110635014
process: com.google.android.projection.gearhead:car
processUptime: 514 + 393 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 90

java.lang.RuntimeException: Unable to start service com.google.android.apps.auto.wireless.setup.service.impl.WirelessSetupSharedService@58767a4 with Intent { act=android.bluetooth.device.action.ACL_CONNECTED cmp=com.google.android.projection.gearhead/com.google.android.apps.auto.wireless.setup.service.impl.WirelessSetupSharedService (has extras) }: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.google.android.projection.gearhead/com.google.android.apps.auto.wireless.setup.service.impl.WirelessSetupSharedService
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4906)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.google.android.projection.gearhead/com.google.android.apps.auto.wireless.setup.service.impl.WirelessSetupSharedService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
	at android.os.Parcel.readParcelable(Parcel.java:4872)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6805)
	at android.app.Service.startForeground(Service.java:878)
	at com.google.android.apps.auto.wireless.setup.service.impl.WirelessSetupSharedService.f(SourceFile:12)
	at com.google.android.apps.auto.wireless.setup.service.impl.WirelessSetupSharedService.n(SourceFile:14)
	at com.google.android.apps.auto.wireless.setup.service.impl.WirelessSetupSharedService.onStartCommand(SourceFile:15)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4888)
	... 11 more

```

**Comment by steve-zero** [comment]
Sorry to bother here, but as I was so rudely dismissed by simply closing down the issue, I had to find another way to give some _final_ feedback on the issue that GrapheneOS requires the mandatory use of an Google Account when using Android Auto.

@thestinger 
> You are using a Google account with Aurora Store.

Factually: **no**.
**They** use **a** Google Account but not me and not mine.
The account used by Aurora is not traceble to me, besides a temporary IP address. A personal throwaway account would give them still my IMEI, my validated phone number, and all usage data and telemetry.
That is a huge difference in privacy.

So I note down that the problem won't be fixed. _That's okay._
I was honestly only asking and was seeking for a comprehensible explanation.

**So the full GrapheneOS product is meant to be used by Google customers only.**
(That must be part of your deal with Google, I guess.)

**Comment by nlroth** [comment]
This happened over 1yr ago.
Since then, the AA app has been updated several times.
This can be closed now.

Cheers.
