### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by olsonperrensen** [GrapheneOS/os-issue-tracker#3051]
```
type: crash
Process: unknown
Build: google/panther/panther:14/UQ1A.240105.004/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.deskclock/androidx.startup.InitializationProvider}
	at android.app.ActivityThread.installProvider(ActivityThread.java:7872)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7378)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7073)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2268)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: androidx.startup.StartupException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.deskclock/androidx.startup.InitializationProvider}
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:209)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:49)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2619)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2589)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7867)
	... 13 more
Caused by: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{com.android.deskclock/androidx.startup.InitializationProvider}
	at android.app.ApplicationPackageManager.getProviderInfo(ApplicationPackageManager.java:645)
	at android.app.ApplicationPackageManager.getProviderInfo(ApplicationPackageManager.java:628)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:205)
	... 17 more

```

**Comment by MichaelDevon** [comment]
i was just about to open an issue. heres mine


```
type: crash
Process: unknown
Build: google/shiba/shiba:14/UQ1A.240105.004/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 12) is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:610)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:593)
	at dc.f2.a(SourceFile:4)
	at dc.j2.e(SourceFile:84)
	at dc.k2.zza(Unknown Source:8)
	at dc.n2.a(SourceFile:25)
	at dc.l2.b(Unknown Source:5)
	at dc.g5.run(SourceFile:5)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by thestinger** [comment]
@MichaelDevon That's not related.

**Comment by vBardys** [comment]
In case another log on related issue is helpful. Otherwise please delete. Happened while I was watching video using 'InfinityLoop1309.NewPipeEnhanced' about 15min ago

```
type: crash
Process: system_server
Build: google/shiba/shiba:14/UQ1A.240105.004/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at com.android.internal.util.ArtFastDataOutput.writeUTF(ArtFastDataOutput.java:79)
	at com.android.modules.utils.BinaryXmlSerializer.attribute(BinaryXmlSerializer.java:207)
	at com.android.server.appop.AppOpsCheckingServiceImpl.writeState(AppOpsCheckingServiceImpl.java:794)
	at com.android.server.appop.AppOpsCheckingServiceImpl$1$1.doInBackground(AppOpsCheckingServiceImpl.java:146)
	at com.android.server.appop.AppOpsCheckingServiceImpl$1$1.doInBackground(AppOpsCheckingServiceImpl.java:143)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```

**Comment by muhomorr** [comment]
This is not a system_server crash, it was reported as one due to an upstream bug that has since been resolved.
