### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by ishanarora** [GrapheneOS/os-issue-tracker#3052]
```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.231205.015/2023121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: failed to set system property (check logcat for reason)
	at android.os.SystemProperties.native_set(Native Method)
	at android.os.SystemProperties.set(SystemProperties.java:235)
	at android.app.PropertyInvalidatedCache.setNonce(PropertyInvalidatedCache.java:711)
	at android.app.PropertyInvalidatedCache.invalidateCacheLocked(PropertyInvalidatedCache.java:1127)
	at android.app.PropertyInvalidatedCache.uncorkInvalidations(PropertyInvalidatedCache.java:1214)
	at android.app.PropertyInvalidatedCache$AutoCorker.handleMessage(PropertyInvalidatedCache.java:1318)
	at android.app.PropertyInvalidatedCache$AutoCorker.-$$Nest$mhandleMessage(Unknown Source:0)
	at android.app.PropertyInvalidatedCache$AutoCorker$1.handleMessage(PropertyInvalidatedCache.java:1328)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:972)
	at com.android.server.SystemServer.main(SystemServer.java:666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

**Comment by ishanarora** [comment]
It crashed while using Mull browser with approx 100 tabs open.

**Comment by thestinger** [comment]
Looks like an upstream bug we're likely not going to be able to resolve. It should get fixed in an AOSP update.
