### ISSUE TITLE
Settings crash when adding a second os language (raven)

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#3065]
With installed and activated simple keyboard 5.16 (fork) i tried to add a second OS language in settings.
The first try no reaction (language was not added), on the 2nd i got a crash of settings.

```
type: crash
osVersion: google/raven/raven:14/UQ1A.240105.002/2024010400:user/release-keys
package: com.android.settings:34
process: com.android.settings
processUptime: 23935 + 242 ms

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=32425267, result=-1, data=Intent { (has extras) }} to activity {com.android.settings/com.android.settings.SubSettings}: java.lang.SecurityException: Permission Denial: updatePersistentConfiguration() from pid=11933, uid=1000 requires android.permission.WRITE_SETTINGS
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5594)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5633)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: Permission Denial: updatePersistentConfiguration() from pid=11933, uid=1000 requires android.permission.WRITE_SETTINGS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.updatePersistentConfigurationWithAttribution(IActivityManager.java:7693)
	at com.android.internal.app.LocalePicker.updateLocales(LocalePicker.java:321)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter$3.onAnimationsFinished(LocaleDragAndDropAdapter.java:328)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.isRunning(RecyclerView.java:14398)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.updateLocalesWhenAnimationStops(LocaleDragAndDropAdapter.java:320)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.doTheUpdate(LocaleDragAndDropAdapter.java:303)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.addLocale(LocaleDragAndDropAdapter.java:290)
	at com.android.settings.localepicker.LocaleListEditor.onActivityResult(LocaleListEditor.java:203)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2750)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2730)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:818)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at com.android.settings.SettingsActivity.onActivityResult(SettingsActivity.java:562)
	at android.app.Activity.dispatchActivityResult(Activity.java:9022)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5587)
	... 15 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforceWriteSettingsPermission(ActivityManagerService.java:16136)
	at com.android.server.am.ActivityManagerService.updatePersistentConfigurationWithAttribution(ActivityManagerService.java:16108)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3985)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2767)
	at android.os.Binder.execTransactInternal(Binder.java:1387)


```

I had the github version installed from here:

https://github.com/rkkr/simple-keyboard/releases/download/102/app-release.apk

English(us) was used and trying to add german language in os settings.

Google Pixel 6 pro raven
UQ1A.240105.002.2024010400

**Comment by robovoice1** [comment]
Keeps crashing with deinstalled 3rd party keyboard and rebooted device
```
type: crash
osVersion: google/raven/raven:14/UQ1A.240105.002/2024010400:user/release-keys
package: com.android.settings:34
process: com.android.settings
processUptime: 9347 + 239 ms

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=924971216, result=-1, data=Intent { (has extras) }} to activity {com.android.settings/com.android.settings.SubSettings}: java.lang.SecurityException: Permission Denial: updatePersistentConfiguration() from pid=6818, uid=1000 requires android.permission.WRITE_SETTINGS
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5594)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5633)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: Permission Denial: updatePersistentConfiguration() from pid=6818, uid=1000 requires android.permission.WRITE_SETTINGS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.updatePersistentConfigurationWithAttribution(IActivityManager.java:7693)
	at com.android.internal.app.LocalePicker.updateLocales(LocalePicker.java:321)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter$3.onAnimationsFinished(LocaleDragAndDropAdapter.java:328)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.isRunning(RecyclerView.java:14398)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.updateLocalesWhenAnimationStops(LocaleDragAndDropAdapter.java:320)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.doTheUpdate(LocaleDragAndDropAdapter.java:303)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.addLocale(LocaleDragAndDropAdapter.java:290)
	at com.android.settings.localepicker.LocaleListEditor.onActivityResult(LocaleListEditor.java:203)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2750)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2730)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:818)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at com.android.settings.SettingsActivity.onActivityResult(SettingsActivity.java:562)
	at android.app.Activity.dispatchActivityResult(Activity.java:9022)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5587)
	... 15 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforceWriteSettingsPermission(ActivityManagerService.java:16136)
	at com.android.server.am.ActivityManagerService.updatePersistentConfigurationWithAttribution(ActivityManagerService.java:16108)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3985)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2767)
	at android.os.Binder.execTransactInternal(Binder.java:1387)


```
![Screenshot_20240113-120931](https://github.com/GrapheneOS/os-issue-tracker/assets/92784377/29ef6431-ce5a-4ca1-ac7d-3ec5384a41ec)

**Comment by robovoice1** [comment]
This appears to be a regression to me, 3-4 updates before UQ1A.240105.002.2024010400
this was functioning flawless.

**Comment by thestinger** [comment]
Please reset app permissions. There's a reset option to do this for all apps (reset app preferences). It looks like you denied system app permissions.

**Comment by robovoice1** [comment]
```
type: crash
osVersion: google/raven/raven:14/UQ1A.240105.002/2024010400:user/release-keys
package: com.android.settings:34
process: com.android.settings
processUptime: 25512 + 323 ms

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=390984890, result=-1, data=Intent { (has extras) }} to activity {com.android.settings/com.android.settings.SubSettings}: java.lang.SecurityException: Permission Denial: updatePersistentConfiguration() from pid=6522, uid=1000 requires android.permission.WRITE_SETTINGS
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5594)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5633)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: Permission Denial: updatePersistentConfiguration() from pid=6522, uid=1000 requires android.permission.WRITE_SETTINGS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.updatePersistentConfigurationWithAttribution(IActivityManager.java:7693)
	at com.android.internal.app.LocalePicker.updateLocales(LocalePicker.java:321)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter$3.onAnimationsFinished(LocaleDragAndDropAdapter.java:328)
	at androidx.recyclerview.widget.RecyclerView$ItemAnimator.isRunning(RecyclerView.java:14398)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.updateLocalesWhenAnimationStops(LocaleDragAndDropAdapter.java:320)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.doTheUpdate(LocaleDragAndDropAdapter.java:303)
	at com.android.settings.localepicker.LocaleDragAndDropAdapter.addLocale(LocaleDragAndDropAdapter.java:290)
	at com.android.settings.localepicker.LocaleListEditor.onActivityResult(LocaleListEditor.java:203)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2750)
	at androidx.fragment.app.FragmentManager$8.onActivityResult(FragmentManager.java:2730)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:818)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at com.android.settings.SettingsActivity.onActivityResult(SettingsActivity.java:562)
	at android.app.Activity.dispatchActivityResult(Activity.java:9022)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5587)
	... 15 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforceWriteSettingsPermission(ActivityManagerService.java:16136)
	at com.android.server.am.ActivityManagerService.updatePersistentConfigurationWithAttribution(ActivityManagerService.java:16108)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3985)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2767)
	at android.os.Binder.execTransactInternal(Binder.java:1387)


```

Still crashing.
Plus an additional system server crash notification after tapping on reset app permissions...

**Comment by robovoice1** [comment]
```
type: crash
Process: system_server
Build: google/raven/raven:14/UQ1A.240105.002/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Lost network stack. This is not the root cause of any issue, it is a side effect of a crash that happened earlier. Earlier logs should point to the actual issue.
	at android.net.ConnectivityModuleConnector.maybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:335)
	at android.net.ConnectivityModuleConnector.-$$Nest$mmaybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:0)
	at android.net.ConnectivityModuleConnector$ModuleServiceConnection.onServiceDisconnected(ConnectivityModuleConnector.java:278)
	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2227)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2242)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:981)
	at com.android.server.SystemServer.main(SystemServer.java:667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

**Comment by thestinger** [comment]
The main issue you're having appears to be that you disabled system app permissions. Check the special access permissions. You seem to have revoked write settings for the Settings app.

**Comment by robovoice1** [comment]
Yes, you are absolutely right (as always). Too much "trying out" on my side. Works now as expected.

Thanks for the response 😎
