### ISSUE TITLE
Network stack cause system_server crash

### ISSUE THREAD

**Issue by Skealz** [GrapheneOS/os-issue-tracker#3067]
I was using vanadium, connected on wifi, using permanent VPN and airplane mode enabled, ans suddenly :

```
type: crash
Process: system_server
Build: google/shiba/shiba:14/UQ1A.240105.004/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Lost network stack. This is not the root cause of any issue, it is a side effect of a crash that happened earlier. Earlier logs should point to the actual issue.
	at android.net.ConnectivityModuleConnector.maybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:335)
	at android.net.ConnectivityModuleConnector.-$$Nest$mmaybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:0)
	at android.net.ConnectivityModuleConnector$ModuleServiceConnection.onServiceDisconnected(ConnectivityModuleConnector.java:278)
	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2227)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2242)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:981)
	at com.android.server.SystemServer.main(SystemServer.java:667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

**Comment by Skealz** [comment]
Some seconds after recovering from the crash, I got also those 2 reports :
```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.240105.004/2024010400:user/release-keys
uid: 1000 (u:r:system_app:s0)
cmdline: com.android.settings
processUptime: 93s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr 800c327d2e84024
threadName: DefaultDispatch
MTE: enabled

backtrace:
    /system/framework/arm64/boot.oat (art_jni_trampoline+212, pc 9b564)
    /system/framework/arm64/boot.oat (java.util.concurrent.locks.LockSupport.parkNanos+72, pc f5308)
    /system_ext/priv-app/Settings/oat/arm64/Settings.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park+124, pc 1c68c5c)
    /system_ext/priv-app/Settings/oat/arm64/Settings.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark+372, pc 1c6a1d4)
    /system_ext/priv-app/Settings/oat/arm64/Settings.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker+900, pc 1c69964)
    /system_ext/priv-app/Settings/oat/arm64/Settings.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run+36, pc 1c6ae04)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc d006c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64db0)
```


```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.240105.004/2024010400:user/release-keys
uid: 10033 (u:r:platform_app:s0:c512,c768)
cmdline: com.android.statementservice
processUptime: 82s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr 800dd0c98ca9518
threadName: DefaultDispatch
MTE: enabled

backtrace:
    /system/framework/arm64/boot.oat (art_jni_trampoline+152, pc 9b528)
    /system/framework/arm64/boot.oat (java.util.concurrent.locks.LockSupport.parkNanos+72, pc f5308)
    /system/priv-app/StatementService/oat/arm64/StatementService.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park+124, pc 1a878c)
    /system/priv-app/StatementService/oat/arm64/StatementService.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark+372, pc 1a9d04)
    /system/priv-app/StatementService/oat/arm64/StatementService.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker+900, pc 1a9494)
    /system/priv-app/StatementService/oat/arm64/StatementService.odex (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run+36, pc 1aa964)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 2109a4)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+172, pc 253b3c)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1416, pc 69abc8)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc d006c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64db0)
```

**Comment by Skealz** [comment]
Another system_crash linked to network stack. 
I dont know if I should open another issue.

Sometimes the network ils buggy, here is what happened :
The permanent VPN is disconnected and it can't reconnect although I'm connected to wifi. So I turn off and on the wifi, and the crash happen.
After the crash, the VPN connects fine.


```
type: crash
Process: system_server
Build: google/shiba/shiba:14/UQ1A.240105.004/2024010400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Could not create IpClient
	at com.android.wifi.x.android.net.networkstack.NetworkStackClientBase.lambda$makeIpClient$1(NetworkStackClientBase.java:74)
	at com.android.wifi.x.android.net.networkstack.NetworkStackClientBase.$r8$lambda$O7FAXGqSPcEp2-TkZpWx3Oz56KM(NetworkStackClientBase.java:0)
	at com.android.wifi.x.android.net.networkstack.NetworkStackClientBase$$ExternalSyntheticLambda1.accept(R8$$SyntheticClass:0)
	at com.android.wifi.x.android.net.networkstack.NetworkStackClientBase.requestConnector(NetworkStackClientBase.java:119)
	at com.android.wifi.x.android.net.networkstack.NetworkStackClientBase.makeIpClient(NetworkStackClientBase.java:70)
	at com.android.wifi.x.android.net.ip.IpClientUtil.makeIpClient(IpClientUtil.java:81)
	at com.android.server.wifi.FrameworkFacade.makeIpClient(FrameworkFacade.java:257)
	at com.android.server.wifi.ClientModeImpl.makeIpClient(ClientModeImpl.java:4357)
	at com.android.server.wifi.ClientModeImpl.-$$Nest$mmakeIpClient(ClientModeImpl.java:0)
	at com.android.server.wifi.ClientModeImpl$ConnectableState.enterImpl(ClientModeImpl.java:4411)
	at com.android.server.wifi.RunnerState.enter(RunnerState.java:75)
	at com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler.invokeEnterMethods(StateMachine.java:1038)
	at com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at com.android.wifi.x.android.net.INetworkStackConnector$Stub$Proxy.makeIpClient(INetworkStackConnector.java:214)
	at com.android.wifi.x.android.net.networkstack.NetworkStackClientBase.lambda$makeIpClient$1(NetworkStackClientBase.java:72)
	... 16 more

```

**Comment by thestinger** [comment]
@Skealz confirmed they're getting crashes in the stock OS too and other evidence showing it's a hardware failure such as faulty memory corrupting data. It's highly likely that all of these problems are tied to the same hardware fault(s).
