### ISSUE TITLE
Launcher Crash when enabling split screen

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#3108]
This may be upstream

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.240105.002/2024011300:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 6668 + 391 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.views.FloatingTaskView.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
	at com.android.quickstep.views.RecentsView.confirmSplitSelect(RecentsView.java:4772)
	at com.android.quickstep.views.TaskView.confirmSecondSplitSelectApp(TaskView.java:816)
	at com.android.quickstep.views.TaskView.onClick(TaskView.java:800)
	at com.android.quickstep.views.TaskView.$r8$lambda$2dErZAYzRAWboZR0vn31kIz_HGY(Unknown Source:0)
	at com.android.quickstep.views.TaskView$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7658)
	at android.view.View.performClickInternal(View.java:7635)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30167)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

Reproduce: 
- swipe up for task overview
- long bress the app icon, enable split view
- click on the app next to it

**Comment by empratyush** [comment]
unable to reproduce.

**Comment by thestinger** [comment]
@firefoxlover Are you using the default launcher?

**Comment by firefoxlover** [comment]
True. I thought that was not part of the Launcher because the recent apps view does not change. It does not happen on the AOSP launcher.

**Comment by thestinger** [comment]
The crash is happening in AOSP launcher which still provides this when using an alternate launcher. It seems to be a bug in the alternate launcher that's triggering a bug in the AOSP launcher. AOSP launcher should handle this bug in the alternate launcher without crashing but we're probably not going to change anything.
