### ISSUE TITLE
Google Play service crashed when trying to enable NFC for security key

### ISSUE THREAD

**Issue by minhng99** [GrapheneOS/os-issue-tracker#3114]
The NFC is off and an app requested for a security key verification, I selected the NFC method, turn on NFC and this happened.

```
type: crash
osVersion: google/husky/husky:14/UQ1A.240105.004/2024011600:user/release-keys
package: com.google.android.gms:235014039
process: com.google.android.gms.ui
processUptime: 9166 + 194 ms
installer: com.android.vending
GmsCompatConfig version: 91

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@224bcc1
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1819)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fd.aE(:com.google.android.gms@235014039@23.50.14 (190408-592568214):12)
	at fd.N(:com.google.android.gms@235014039@23.50.14 (190408-592568214):27)
	at bs.c(:com.google.android.gms@235014039@23.50.14 (190408-592568214):66)
	at bs.a(:com.google.android.gms@235014039@23.50.14 (190408-592568214):2)
	at cx.hI(:com.google.android.gms@235014039@23.50.14 (190408-592568214):109)
	at cx.dismiss(:com.google.android.gms@235014039@23.50.14 (190408-592568214):2)
	at dvio.dismiss(:com.google.android.gms@235014039@23.50.14 (190408-592568214):8)
	at asao.s(:com.google.android.gms@235014039@23.50.14 (190408-592568214):52)
	at asao.k(:com.google.android.gms@235014039@23.50.14 (190408-592568214):84)
	at atkr.b(:com.google.android.gms@235014039@23.50.14 (190408-592568214):501)
	at asao.q(:com.google.android.gms@235014039@23.50.14 (190408-592568214):10)
	at assw.f(:com.google.android.gms@235014039@23.50.14 (190408-592568214):5)
	at asia.b(:com.google.android.gms@235014039@23.50.14 (190408-592568214):9)
	at atiy.c(:com.google.android.gms@235014039@23.50.14 (190408-592568214):64)
	at atiy.b(:com.google.android.gms@235014039@23.50.14 (190408-592568214):116)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.a(:com.google.android.gms@235014039@23.50.14 (190408-592568214):109)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@235014039@23.50.14 (190408-592568214):18)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1811)
	... 12 more
```

**Comment by cameronaaron** [comment]
```
type: crash
osVersion: google/husky/husky:15/BP1A.250305.019/2025030800:user/release-keys
package: com.google.android.gms:250832035, targetSdk 35
process: com.google.android.gms.ui
processUptime: 4444522 + 379 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 154

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@c958932
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1838)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8973)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at ft.aE(:com.google.android.gms@250832035@25.08.32 (260400-731361394):12)
	at ft.N(:com.google.android.gms@250832035@25.08.32 (260400-731361394):27)
	at ch.c(:com.google.android.gms@250832035@25.08.32 (260400-731361394):58)
	at ch.a(:com.google.android.gms@250832035@25.08.32 (260400-731361394):3)
	at dl.ig(:com.google.android.gms@250832035@25.08.32 (260400-731361394):110)
	at dl.dismiss(:com.google.android.gms@250832035@25.08.32 (260400-731361394):2)
	at fbjx.dismiss(:com.google.android.gms@250832035@25.08.32 (260400-731361394):8)
	at bcne.s(:com.google.android.gms@250832035@25.08.32 (260400-731361394):51)
	at bcne.k(:com.google.android.gms@250832035@25.08.32 (260400-731361394):81)
	at bdwz.b(:com.google.android.gms@250832035@25.08.32 (260400-731361394):433)
	at bcne.r(:com.google.android.gms@250832035@25.08.32 (260400-731361394):10)
	at bdex.f(:com.google.android.gms@250832035@25.08.32 (260400-731361394):5)
	at bcub.b(:com.google.android.gms@250832035@25.08.32 (260400-731361394):9)
	at bdvg.c(:com.google.android.gms@250832035@25.08.32 (260400-731361394):29)
	at bdvg.b(:com.google.android.gms@250832035@25.08.32 (260400-731361394):104)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.kz(:com.google.android.gms@250832035@25.08.32 (260400-731361394):105)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@250832035@25.08.32 (260400-731361394):17)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1830)
	... 12 more
```

**Comment by cameronaaron** [comment]
NFC KEYS always fail even when enabled manually

**Comment by muhomorr** [comment]
This crash is suppressed since 2025031400 release. It happens if NFC is enabled while FIDO prompt activity is in background. That activity restart automatically when user returns to it. This crash is reproducible on stock Pixel OS, it's just not reported there.
