### ISSUE TITLE
Sandboxes Google Playstore crash

### ISSUE THREAD

**Issue by BlackBird9067** [GrapheneOS/os-issue-tracker#3120]
```
type: crash
osVersion: google/panther/panther:14/UQ1A.240105.004/2024011600:user/release-keys
package: com.android.vending:83811820
process: com.android.vending
processUptime: 3078078 + 315 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 92

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.android.gms.accountsettings.action.VIEW_SETTINGS pkg=com.google.android.gms (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2250)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1884)
	at android.app.Activity.startActivityForResult(Activity.java:5661)
	at zzzi.startActivityForResult(PG:50)
	at android.app.Activity.startActivityForResult(Activity.java:5581)
	at aldq.b(PG:33)
	at alev.a(PG:55)
	at vvk.a(PG:60)
	at alin.onClick(PG:228)
	at uwn.b(PG:51)
	at apzi.run(PG:30)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by ScienceBeyondTime** [comment]
```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.240105.004/2024011600:user/release-keys
package: com.google.android.gms:234914038
process: com.google.android.gms.ui
processUptime: 7909 + 251 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 92

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@44d470c
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1819)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fd.aE(:com.google.android.gms@234914038@23.49.14 (190400-590296185):12)
	at fd.N(:com.google.android.gms@234914038@23.49.14 (190400-590296185):27)
	at bs.c(:com.google.android.gms@234914038@23.49.14 (190400-590296185):66)
	at bs.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
	at cx.hI(:com.google.android.gms@234914038@23.49.14 (190400-590296185):109)
	at cx.dismiss(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
	at duku.dismiss(:com.google.android.gms@234914038@23.49.14 (190400-590296185):8)
	at arpz.s(:com.google.android.gms@234914038@23.49.14 (190400-590296185):52)
	at arpz.k(:com.google.android.gms@234914038@23.49.14 (190400-590296185):84)
	at atae.b(:com.google.android.gms@234914038@23.49.14 (190400-590296185):501)
	at arpz.q(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
	at asij.f(:com.google.android.gms@234914038@23.49.14 (190400-590296185):5)
	at arxl.b(:com.google.android.gms@234914038@23.49.14 (190400-590296185):9)
	at asyl.c(:com.google.android.gms@234914038@23.49.14 (190400-590296185):64)
	at asyl.b(:com.google.android.gms@234914038@23.49.14 (190400-590296185):116)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):109)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@234914038@23.49.14 (190400-590296185):18)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1811)
	... 12 more
```
