### ISSUE TITLE
Error in google play store

### ISSUE THREAD

**Issue by zafabbas** [GrapheneOS/os-issue-tracker#3130]
```
type: crash
osVersion: google/raven/raven:14/UQ1A.240105.002/2024011600:user/release-keys
package: com.android.vending:83923720
process: com.android.vending
processUptime: 129012360 + 401 ms
installer: com.android.vending
GmsCompatConfig version: 92

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
	at android.util.ArrayMap.allocArrays(ArrayMap.java:279)
	at android.util.ArrayMap.put(ArrayMap.java:604)
	at android.os.BaseBundle.putInt(BaseBundle.java:873)
	at llt.l(PG:3)
	at llt.g(PG:222)
	at llw.m(PG:169)
	at ipr.dispatchTransaction(PG:533)
	at izs.onTransact(PG:13)
	at android.os.Binder.execTransactInternal(Binder.java:1387)
	at android.os.Binder.execTransact(Binder.java:1328)
```

**Comment by thestinger** [comment]
Looks like a Play Store bug.
