### ISSUE TITLE
System server crash - pixel 6 pro

### ISSUE THREAD

**Issue by Axgbk17** [GrapheneOS/os-issue-tracker#3131]
Could someone please help me understand why my phone keeps crashing with this error message? Thank you.
 
```
type: crash
Process: system_server
Build: google/raven/raven:14/UQ1A.240105.002/2024011600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 4293360 free bytes and 4192KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3553)
	at java.util.Arrays.copyOf(Arrays.java:3522)
	at java.util.ArrayList.toArray(ArrayList.java:376)
	at java.util.ArrayList.<init>(ArrayList.java:188)
	at com.android.server.notification.ManagedServices.getServices(ManagedServices.java:211)
	at com.android.server.notification.NotificationManagerService$NotificationListeners.isListenerPackage(NotificationManagerService.java:12160)
	at com.android.server.notification.NotificationManagerService.checkDisqualifyingFeatures(NotificationManagerService.java:7279)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:6852)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:6672)
	at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:6662)
	at com.android.server.notification.NotificationManagerService$14.enqueueNotification(NotificationManagerService.java:6482)
	at com.android.server.am.ServiceRecord$2.run(ServiceRecord.java:1440)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by thestinger** [comment]
It's likely a bug triggered by an application. We're not going to be able to resolve it without a lot more information and probably a way to reproduce it. It's very likely an upstream Android bug particularly since it's a Java out-of-memory error instead of a native one.
