### ISSUE TITLE
system_server crashes with OOM

### ISSUE THREAD

**Issue by uttarayan21** [GrapheneOS/os-issue-tracker#3132]
```
type: crash
Process: system_server
Build: google/shiba/shiba:14/UQ1A.240105.004/2024011600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 420546432 byte allocation with 100646912 free bytes and 213MB until OOM, target footprint 414010344, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3553)
	at java.util.Arrays.copyOf(Arrays.java:3522)
	at java.util.ArrayList.grow(ArrayList.java:244)
	at java.util.ArrayList.grow(ArrayList.java:251)
	at java.util.ArrayList.add(ArrayList.java:461)
	at java.util.ArrayList.add(ArrayList.java:474)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacketReader.readLabels(MdnsPacketReader.java:170)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecord(MdnsPacket.java:128)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecords(MdnsPacket.java:115)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecordsSection(MdnsPacket.java:99)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parse(MdnsPacket.java:82)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsInterfaceAdvertiser.handlePacket(MdnsInterfaceAdvertiser.java:318)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:101)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:34)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.handleInput(FdEventsReader.java:261)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.lambda$createAndRegisterFd$0(FdEventsReader.java:217)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.$r8$lambda$xh0yZpbdLvlMgmz3uMcpPMcWNvc(FdEventsReader.java:0)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader$$ExternalSyntheticLambda0.onFileDescriptorEvents(R8$$SyntheticClass:0)
	at android.os.MessageQueue.dispatchEvents(MessageQueue.java:293)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

Keeps happening spontaneously 
Build is from 2024 01 16.

Not sure if related to #3115 

Happened 5 times within the span of 3 hours.
![Screenshot_20240123-180213](https://github.com/GrapheneOS/os-issue-tracker/assets/18732700/873fd60a-3fd9-4e29-a3b8-0f7fa2358d84)

**Comment by thestinger** [comment]
Not enough info to act on this. We'll bear in mind that a few users have had these occur.
