### ISSUE TITLE
system_server crash - healthconnect? 

### ISSUE THREAD

**Issue by jriberg** [GrapheneOS/os-issue-tracker#3135]
```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240105.004/2024011600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PACKAGE_CHANGED dat=package: flg=0x45000010 (has extras) } in com.android.server.healthconnect.migration.MigratorPackageChangesReceiver@ad13517
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1819)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at com.android.server.healthconnect.migration.MigratorPackageChangesReceiver.onReceive(MigratorPackageChangesReceiver.java:61)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1811)
	... 7 more
```

**Comment by addy419** [comment]
Same here:

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.240105.002/2024011600:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 60s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62ea4)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664, pc 292d48)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324, pc 2952ac)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840d0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a67f4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

**Comment by thestinger** [comment]
@addy419 Not the same, that's a known upstream issue and not the same as this.

**Comment by addy419** [comment]
@thestinger Ah I see, sorry about that.

**Comment by karolyi** [comment]
Is this related here, I wonder?

```java
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240105.004/2024011600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Error flushing proto to stream
    at android.util.proto.ProtoOutputStream.flush(ProtoOutputStream.java:2518)
    at com.android.server.BootReceiver.addTombstoneToDropBox(BootReceiver.java:377)
    at com.android.server.os.NativeTombstoneManager.handleTombstone(NativeTombstoneManager.java:144)
    at com.android.server.os.NativeTombstoneManager.-$$Nest$mhandleTombstone(NativeTombstoneManager.java:0)
    at com.android.server.os.NativeTombstoneManager$TombstoneWatcher.lambda$onEvent$0(NativeTombstoneManager.java:589)
    at com.android.server.os.NativeTombstoneManager$TombstoneWatcher.$r8$lambda$tfJ_q07NaI9c6UYttszi4EdMJ7Y(NativeTombstoneManager.java:0)
    at com.android.server.os.NativeTombstoneManager$TombstoneWatcher$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.os.HandlerThread.run(HandlerThread.java:67)
    at com.android.server.ServiceThread.run(ServiceThread.java:46)
Caused by: java.io.IOException: write failed: EBADF (Bad file descriptor)
    at libcore.io.IoBridge.write(IoBridge.java:651)
    at java.io.FileOutputStream.write(FileOutputStream.java:406)
    at java.io.FileOutputStream.write(FileOutputStream.java:384)
    at android.util.proto.ProtoOutputStream.flush(ProtoOutputStream.java:2515)
    ... 12 more
Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
    at libcore.io.Linux.writeBytes(Native Method)
    at libcore.io.Linux.write(Linux.java:296)
    at libcore.io.ForwardingOs.write(ForwardingOs.java:943)
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:448)
    at libcore.io.IoBridge.write(IoBridge.java:646)
    ... 15 more
```
