### ISSUE TITLE
Error in Google play services

### ISSUE THREAD

**Issue by oilman1986** [GrapheneOS/os-issue-tracker#3142]
```
type: crash
osVersion: 
google/bluejay/bluejay:14/UP1A.231005.007/2023101100:user/release-keys
package: com.google.android.gms:234914038
process: com.google.android.gms.persistent
processUptime: 6347205 + 305 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 93

java.lang.RuntimeException: Rethrown by StandaloneSchedulingEngine
	at cpya.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):455)
	at cpud.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):9)
	at akas.c(:com.google.android.gms@234914038@23.49.14 (190400-590296185):50)
	at akas.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akgh.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: dyxu: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.time-TrustedTimeMaintenanceTaskService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a125; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at bhiz.apply(:com.google.android.gms@234914038@23.49.14 (190400-590296185):5)
	at efnj.d(:com.google.android.gms@234914038@23.49.14 (190400-590296185):3)
	at efnk.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):139)
	... 6 more
Caused by: java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a125; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5778)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1513)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1480)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:607)
	at cysl.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):43)
	at cysp.g(:com.google.android.gms@234914038@23.49.14 (190400-590296185):723)
	at cysm.c(:com.google.android.gms@234914038@23.49.14 (190400-590296185):7)
	at com.google.android.gms.time.singleuserapi.service.TrustedTimeMaintenanceTaskService.hc(:com.google.android.gms@234914038@23.49.14 (190400-590296185):186)
	at bhja.call(:com.google.android.gms@234914038@23.49.14 (190400-590296185):32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 6 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2457)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:14521)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14431)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2661)


```

**Comment by oilman1986** [comment]
I really appreciate the help on this front.



Alex J. Ramirez, P.E.
***@***.***
713-819-2110
