### ISSUE TITLE
Android Auto Crash

### ISSUE THREAD

**Issue by srdempster** [GrapheneOS/os-issue-tracker#3151]
```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.240105.004/2024012600:user/release-keys
package: com.google.android.projection.gearhead:110635054
process: com.google.android.projection.gearhead:projection
processUptime: 712 + 1171 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 93

hwf: not able to initialize DisplayLayout
	at hvv.g(SourceFile:8)
	at hvv.c(SourceFile:1)
	at com.google.android.projection.gearhead.system.GhLifecycleService.f(SourceFile:4)
	at oaa.handleMessage(SourceFile:37)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: ohj: java.lang.IllegalStateException: OutOfCarLifecycle
	at pnb.cg(SourceFile:8)
	at pnb.cf(SourceFile:1)
	at ogl.h(SourceFile:4)
	at ogl.g(SourceFile:2)
	at jtx.a(SourceFile:57)
	at hwl.a(SourceFile:29)
	at hvv.g(SourceFile:1)
	... 12 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at get.ef(SourceFile:3)
	at nuj.L(SourceFile:2)
	at phn.d(SourceFile:5)
	at obg.a(SourceFile:5)
	at nrl.d(SourceFile:1)
	at obl.a(SourceFile:4)
	at ogl.g(SourceFile:1)
	... 15 more
```

**Comment by muhomorr** [comment]
Need to see a full log right after the crash. It can be accessed by tapping the "Show log" button at the bottom of the crash report screen.

**Comment by srdempster** [comment]
It hasn't come up since the last flurry of app updates within grapheneos "Apps". I run alpha versions do perhaps will wait in future to see if it corrects on further releases.

Sent from ProtonMail, Swiss-based encrypted email.

-------- Original Message --------

**Comment by muhomorr** [comment]
I've seen several similar Android Auto crashes after USB or Wi-FI connection failure. This crash was likely caused by a connection failure too.
