### ISSUE TITLE
Work profiles crash after failing to unpause work apps

### ISSUE THREAD

**Issue by AntsyBoi** [GrapheneOS/os-issue-tracker#3152]
```
type: crash
Process: system_server
Build: google/panther/panther:14/UQ1A.240105.004/2024012600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: No TargetUser for 11
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at com.android.server.SystemServiceManager.onUser(SystemServiceManager.java:468)
	at com.android.server.SystemServiceManager.onUserStopping(SystemServiceManager.java:424)
	at com.android.server.am.UserController.finishUserStopping(UserController.java:1101)
	at com.android.server.am.UserController.lambda$stopSingleUserLU$6(UserController.java:1039)
	at com.android.server.am.UserController.$r8$lambda$sK6Ham53MGc-JuZG7yv1Pz75Drs(UserController.java:0)
	at com.android.server.am.UserController$$ExternalSyntheticLambda15.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by AntsyBoi** [comment]
> Were you able to get it to work or is this still happening?

This was just a one time issue, did not happen again and I am able to continue using work profile apps. It required a full restart of my phone to resolve, as even the automatic system server restart after the crash didn't solve it.
