### ISSUE TITLE
Play Services crash after installation

### ISSUE THREAD

**Issue by cebzab** [GrapheneOS/os-issue-tracker#3171]
Play services crash after installation, the notification shows that it's running but for an example Signal doesn't see it at all and after installation it switches to being always on in the background.
I've reinstalled os multiple times via web installer, every time I get the same result.

If there's anything I could do more, let me know.

The error code:

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S1/2024010700:user/release-keys
package: com.google.android.gms:234914038
process: com.google.android.gms
processUptime: 4780 + 1178 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 93

java.lang.SecurityException: Attempt to change component state; pid=6534, uid=10148, package=com.google.android.gms.supervision
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.content.pm.IPackageManager$Stub$Proxy.setApplicationEnabledSetting(IPackageManager.java:6080)
	at android.app.ApplicationPackageManager.setApplicationEnabledSetting(ApplicationPackageManager.java:3084)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.setApplicationEnabledSetting(GmcPackageManager.java:138)
	at bgqv.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):12)
	at com.google.android.gms.kids.settings.KidsSettingsModuleInitIntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):163)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageManagerService.setEnabledSettings(PackageManagerService.java:3743)
	at com.android.server.pm.PackageManagerService.-$$Nest$msetEnabledSettings(Unknown Source:0)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.setApplicationEnabledSetting(PackageManagerService.java:5493)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3025)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:5994)


```

**Comment by dot-gov** [comment]
Same issue here on pixel 6a, fresh install.
