### ISSUE TITLE
google play services  is crashing. then auto restarts. started in January 2024. was working for the past year no problems

### ISSUE THREAD

**Issue by travelyoga** [GrapheneOS/os-issue-tracker#3172]
here is the error log. 
I deinstalled all apps and only installed one. it still crashes
I deleted the user profile and made a new one. still crashes
crashes 20-30 times during the day
then all the apps running at that time crash too.
to get things going again, I restart the phone. then it is stable for about a hour, then crashes again. 

type: crash
osVersion: google/bluejay/bluejay:13/TQ2A.230405.003.E1/2023041100:user/release-keys
package: com.google.android.gms:240213038
process: com.google.android.gms.persistent
processUptime: 666 + 5602 ms
GmsCompatConfig version: 93

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u10a162; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at axgc.sendBroadcastAsUser(:com.google.android.gms@240213038@24.02.13 (190400-599553831):6)
	at daia.a(:com.google.android.gms@240213038@24.02.13 (190400-599553831):43)
	at daie.g(:com.google.android.gms@240213038@24.02.13 (190400-599553831):723)
	at daib.c(:com.google.android.gms@240213038@24.02.13 (190400-599553831):7)
	at daib.d(:com.google.android.gms@240213038@24.02.13 (190400-599553831):10)
	at dail.f(:com.google.android.gms@240213038@24.02.13 (190400-599553831):48)
	at bhxh.fh(:com.google.android.gms@240213038@24.02.13 (190400-599553831):1)
	at bhxq.run(:com.google.android.gms@240213038@24.02.13 (190400-599553831):100)
	at ebdb.run(:com.google.android.gms@240213038@24.02.13 (190400-599553831):21)
	at akki.c(:com.google.android.gms@240213038@24.02.13 (190400-599553831):50)
	at akki.run(:com.google.android.gms@240213038@24.02.13 (190400-599553831):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at akpt.run(:com.google.android.gms@240213038@24.02.13 (190400-599553831):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: ebdl: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.AsyncOpImpl(Unknown Source:0)
		at tk_trace.AsyncOpTask(Unknown Source:0)
		at tk_trace.326-alluserapi.RetrieveGlobalStateOperation(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2270)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13698)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13650)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14528)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2304)

**Comment by travelyoga** [comment]
where can I find the updater app on grapheneos. I searched for it and cannot find it. can you send me more info.  send me a link on how to access and use this app for updating.

**Comment by travelyoga** [comment]
found it. it is enabled and has network permissions.
says: no permissions denied

**Comment by travelyoga** [comment]
I can  see:
Settings > System > System Update
I have not messed with any system apps
I rebooted an hour ago.

**Comment by travelyoga** [comment]
grapheneos. I installed it over a year ago.  from https://grapheneos.org/install/web and I used google chrome installer

**Comment by travelyoga** [comment]
can you send me the name of the lastest release name. the note above lists

raven-ota_update-2021122018.zip

where do I find a listing of all the versions to side load?

**Comment by travelyoga** [comment]
thank you for your support. I will side load in two week from now. meanwhile I am using the main profile with no google play services.

**Comment by travelyoga** [comment]
thanks I will check these out too. I am traveling now and I don't want to break my phone. I will probably do a fresh reload when I got back home from traveling.  thanks for your help.

**Comment by travelyoga** [comment]
got it to update today without side loading. I had to turn on notifications.  now it is downloading the system updates.
Also yesterday, I updated the google play from the play store, and the crashes went away. thanks for your support.
