### ISSUE TITLE
Android Auto could not be started

### ISSUE THREAD

**Issue by liminalstate** [GrapheneOS/os-issue-tracker#3173]
Intermittent crashes experienced.

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.240105.004/2024012600:user/release-keys
package: com.google.android.projection.gearhead:110635054
process: com.google.android.projection.gearhead:projection
processUptime: 558136 + 416 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 93

hwf: Unable to access car
	at hvv.g(SourceFile:8)
	at hvv.b(SourceFile:1)
	at ikh.dF(SourceFile:2)
	at itu.b(SourceFile:5)
	at tdk.c(SourceFile:17)
	at itv.k(SourceFile:4)
	at its.a(SourceFile:4)
	at hwc.v(SourceFile:16)
	at ibh.a(SourceFile:117)
	at ntf.f(SourceFile:4)
	at nsr.run(SourceFile:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: ohj: java.lang.IllegalStateException: OutOfCarLifecycle
	at pnb.cg(SourceFile:8)
	at pnb.cf(SourceFile:1)
	at ogl.h(SourceFile:4)
	at ogl.b(SourceFile:2)
	at obx.u(SourceFile:1)
	at nrx.y(SourceFile:1)
	at nep.g(SourceFile:1)
	at ijx.a(SourceFile:100)
	at hwl.a(SourceFile:28)
	at hvv.g(SourceFile:1)
	... 20 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at get.ef(SourceFile:3)
	at nuj.A(SourceFile:2)
	at obk.a(SourceFile:10)
	at ogh.a(SourceFile:2)
	at obh.call(SourceFile:11)
	at ogl.b(SourceFile:1)
	... 26 more
```

**Comment by liminalstate** [comment]
I think this may be a loose cable but I'm not 100% sure on that.  I swapped out my cable and the crashes seem to be less frequent.  Please keep that in mind as you review these.

```
type: logcat
osVersion: google/cheetah/cheetah:14/UQ1A.240105.004/2024012600:user/release-keys
packageName: com.google.android.projection.gearhead:110635054
buffers: main,system,crash,events
level: verbose

--------- beginning of crash
1706922089.675 31180 31180 E AndroidRuntime: FATAL EXCEPTION: main
1706922089.675 31180 31180 E AndroidRuntime: Process: com.google.android.projection.gearhead:projection, PID: 31180
1706922089.675 31180 31180 E AndroidRuntime: hwf: Unable to access car
1706922089.675 31180 31180 E AndroidRuntime: 	at hvv.g(SourceFile:8)
1706922089.675 31180 31180 E AndroidRuntime: 	at hvv.b(SourceFile:1)
1706922089.675 31180 31180 E AndroidRuntime: 	at ikh.dF(SourceFile:2)
1706922089.675 31180 31180 E AndroidRuntime: 	at itu.b(SourceFile:5)
1706922089.675 31180 31180 E AndroidRuntime: 	at tdk.c(SourceFile:17)
1706922089.675 31180 31180 E AndroidRuntime: 	at itv.k(SourceFile:4)
1706922089.675 31180 31180 E AndroidRuntime: 	at its.a(SourceFile:4)
1706922089.675 31180 31180 E AndroidRuntime: 	at hwc.v(SourceFile:16)
1706922089.675 31180 31180 E AndroidRuntime: 	at ibh.a(SourceFile:117)
1706922089.675 31180 31180 E AndroidRuntime: 	at ntf.f(SourceFile:4)
1706922089.675 31180 31180 E AndroidRuntime: 	at nsr.run(SourceFile:2)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8279)
1706922089.675 31180 31180 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
1706922089.675 31180 31180 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
1706922089.675 31180 31180 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
1706922089.675 31180 31180 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
1706922089.675 31180 31180 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
1706922089.675 31180 31180 E AndroidRuntime: Caused by: ohj: java.lang.IllegalStateException: OutOfCarLifecycle
1706922089.675 31180 31180 E AndroidRuntime: 	at pnb.cg(SourceFile:8)
1706922089.675 31180 31180 E AndroidRuntime: 	at pnb.cf(SourceFile:1)
1706922089.675 31180 31180 E AndroidRuntime: 	at ogl.h(SourceFile:4)
1706922089.675 31180 31180 E AndroidRuntime: 	at ogl.b(SourceFile:2)
1706922089.675 31180 31180 E AndroidRuntime: 	at obx.u(SourceFile:1)
1706922089.675 31180 31180 E AndroidRuntime: 	at nrx.y(SourceFile:1)
1706922089.675 31180 31180 E AndroidRuntime: 	at nep.g(SourceFile:1)
1706922089.675 31180 31180 E AndroidRuntime: 	at ijx.a(SourceFile:100)
1706922089.675 31180 31180 E AndroidRuntime: 	at hwl.a(SourceFile:28)
1706922089.675 31180 31180 E AndroidRuntime: 	at hvv.g(SourceFile:1)
1706922089.675 31180 31180 E AndroidRuntime: 	... 20 more
1706922089.675 31180 31180 E AndroidRuntime: Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3050)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3026)
1706922089.675 31180 31180 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2968)
1706922089.675 31180 31180 E AndroidRuntime: 	at get.ef(SourceFile:3)
1706922089.675 31180 31180 E AndroidRuntime: 	at nuj.A(SourceFile:2)
1706922089.675 31180 31180 E AndroidRuntime: 	at obk.a(SourceFile:10)
1706922089.675 31180 31180 E AndroidRuntime: 	at ogh.a(SourceFile:2)
1706922089.675 31180 31180 E AndroidRuntime: 	at obh.call(SourceFile:11)
1706922089.675 31180 31180 E AndroidRuntime: 	at ogl.b(SourceFile:1)
1706922089.675 31180 31180 E AndroidRuntime: 	... 26 more
1706990831.010 21094 21094 E AndroidRuntime: FATAL EXCEPTION: main
1706990831.010 21094 21094 E AndroidRuntime: Process: com.google.android.projection.gearhead:projection, PID: 21094
1706990831.010 21094 21094 E AndroidRuntime: hwf: not able to initialize DisplayLayout
1706990831.010 21094 21094 E AndroidRuntime: 	at hvv.g(SourceFile:8)
1706990831.010 21094 21094 E AndroidRuntime: 	at hvv.c(SourceFile:1)
1706990831.010 21094 21094 E AndroidRuntime: 	at com.google.android.projection.gearhead.system.GhLifecycleService.f(SourceFile:4)
1706990831.010 21094 21094 E AndroidRuntime: 	at oaa.handleMessage(SourceFile:37)
1706990831.010 21094 21094 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
1706990831.010 21094 21094 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
1706990831.010 21094 21094 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
1706990831.010 21094 21094 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8279)
1706990831.010 21094 21094 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
1706990831.010 21094 21094 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
1706990831.010 21094 21094 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
1706990831.010 21094 21094 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
1706990831.010 21094 21094 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
1706990831.010 21094 21094 E AndroidRuntime: Caused by: ohj: java.lang.IllegalStateException: OutOfCarLifecycle
1706990831.010 21094 21094 E AndroidRuntime: 	at pnb.cg(SourceFile:8)
1706990831.010 21094 21094 E AndroidRuntime: 	at pnb.cf(SourceFile:1)
1706990831.010 21094 21094 E AndroidRuntime: 	at ogl.h(SourceFile:4)
1706990831.010 21094 21094 E AndroidRuntime: 	at ogl.g(SourceFile:2)
1706990831.010 21094 21094 E AndroidRuntime: 	at jtx.a(SourceFile:57)
1706990831.010 21094 21094 E AndroidRuntime: 	at hwl.a(SourceFile:29)
1706990831.010 21094 21094 E AndroidRuntime: 	at hvv.g(SourceFile:1)
1706990831.010 21094 21094 E AndroidRuntime: 	... 12 more
1706990831.010 21094 21094 E AndroidRuntime: Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
1706990831.010 21094 21094 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
1706990831.010 21094 21094 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3050)
1706990831.010 21094 21094 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3026)
1706990831.010 21094 21094 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2968)
1706990831.010 21094 21094 E AndroidRuntime: 	at get.ef(SourceFile:3)
1706990831.010 21094 21094 E AndroidRuntime: 	at nuj.L(SourceFile:2)
1706990831.010 21094 21094 E AndroidRuntime: 	at phn.d(SourceFile:5)
1706990831.010 21094 21094 E AndroidRuntime: 	at obg.a(SourceFile:5)
1706990831.010 21094 21094 E AndroidRuntime: 	at nrl.d(SourceFile:1)
1706990831.010 21094 21094 E AndroidRuntime: 	at obl.a(SourceFile:4)
1706990831.010 21094 21094 E AndroidRuntime: 	at ogl.g(SourceFile:1)
1706990831.010 21094 21094 E AndroidRuntime: 	... 15 more
--------- beginning of system
1707148639.873  7380  7380 E ActivityThread: Service com.google.android.apps.auto.carservice.service.impl.GearheadCarStartupService has leaked ServiceConnection heu@8cd8bc9 that was originally bound here
1707148639.873  7380  7380 E ActivityThread: android.app.ServiceConnectionLeaked: Service com.google.android.apps.auto.carservice.service.impl.GearheadCarStartupService has leaked ServiceConnection heu@8cd8bc9 that was originally bound here
1707148639.873  7380  7380 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:2064)
1707148639.873  7380  7380 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1936)
1707148639.873  7380  7380 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1915)
1707148639.873  7380  7380 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2145)
1707148639.873  7380  7380 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:2021)
1707148639.873  7380  7380 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:861)
1707148639.873  7380  7380 E ActivityThread: 	at hev.run(SourceFile:1)
1707148639.873  7380  7380 E ActivityThread: 	at android.os.Handler.handleCallback(Handler.java:958)
1707148639.873  7380  7380 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:99)
1707148639.873  7380  7380 E ActivityThread: 	at android.os.Looper.loopOnce(Looper.java:205)
1707148639.873  7380  7380 E ActivityThread: 	at android.os.Looper.loop(Looper.java:294)
1707148639.873  7380  7380 E ActivityThread: 	at android.os.HandlerThread.run(HandlerThread.java:67)
--------- beginning of main
1707150513.786 25270  6351 D TrafficStats: tagSocket(134) with statsTag=0xffffffff, statsUid=-1
1707150516.903 25270  6351 D TrafficStats: tagSocket(134) with statsTag=0xffffffff, statsUid=-1
1707150541.638 25270  6351 D TrafficStats: tagSocket(134) with statsTag=0xffffffff, statsUid=-1
1707150544.726 25270  6351 D TrafficStats: tagSocket(134) with statsTag=0xffffffff, statsUid=-1
1707150565.499 27003 27003 I GH.CAR  : onDestroy
1707150565.499 27003 27003 I GH.CAR  : tearDown()
1707150565.499 27003 27003 I GH.CarService: tearDown()
1707150565.499 27003 27003 I GH.DelegateMngCarSvc: tearDown()
```
