### ISSUE TITLE
Launcher doesn't add website shortcut as app icon

### ISSUE THREAD

**Issue by mrxx0** [GrapheneOS/os-issue-tracker#3175]
Device : Pixel 8 Pro
Release : 2024012600

**Steps to reproduce :**

-In Vanadium (or any other browser), add a website to the home screen using the three-dot menu in the top right corner.

**Actual Behavior:**

No icon is added to the home screen.

**Expected Behavior:**

The website icon shortcut should be added to the home screen.

Rebooting the phone or force-closing the launcher fixes the issue, and the icon is now present on the home screen.

Log (grabbed from system logs in Settings) : 

```
--------- switch to events
         1706970592.900  1000  1339  1902 I input_interaction: Interaction with: 859e4df com.android.launcher3/com.android.launcher3.dragndrop.AddItemActivity (server), [Gesture Monitor] swipe-up (server), [Gesture Monitor] edge-swipe (server), PointerEventDispatcher0 (server), 
--------- switch to main
         1706970592.970  9999  2119  2147 I deeptouch: I0000 00:00:1706970592.970467    2147 tf_lite_classifier.cc:409] Event stream classified as kNone
         1706970592.974 10106 10642 10642 D StatsLog: LAUNCHER_ADD_EXTERNAL_ITEM_PLACED_AUTOMATICALLY
         1706970592.983 10106 10642 10673 D ItemInstallQueue: Adding PendingInstallShortcutInfo to queue. Attached info: WorkspaceItemInfo(id=-1 type=DEEPSHORTCUT container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@7bc6f targetComponent=ComponentInfo{app.vanadium.browser/com.google.android.apps.chrome.Main} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=GrapheneOS Discussion Forum)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: java.lang.Exception
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at com.android.launcher3.model.ItemInstallQueue.queuePendingShortcutInfo(ItemInstallQueue.java:189)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at com.android.launcher3.model.ItemInstallQueue.queueItem(ItemInstallQueue.java:160)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at com.android.launcher3.dragndrop.AddItemActivity.onPlaceAutomaticallyClick(AddItemActivity.java:340)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at java.lang.reflect.Method.invoke(Native Method)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.view.View$DeclaredOnClickListener.onClick(View.java:6468)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.view.View.performClick(View.java:7658)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.view.View.performClickInternal(View.java:7635)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.view.View$PerformClick.run(View.java:30167)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.os.Handler.handleCallback(Handler.java:958)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.os.Handler.dispatchMessage(Handler.java:99)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.os.Looper.loopOnce(Looper.java:205)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.os.Looper.loop(Looper.java:294)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at android.app.ActivityThread.main(ActivityThread.java:8279)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at java.lang.reflect.Method.invoke(Native Method)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
         1706970592.983 10106 10642 10673 D ItemInstallQueue: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
         1706970592.997  1000  1339  4018 W AppSearchIcing: icing-search-engine.cc:283: Error: 5, Message: Failed to delete Document. namespace: android$app.vanadium.browser/app.vanadium.browser, uri: d1a93218-f630-40c0-9e68-fb51ece928a6;Failed to find DocumentId by key: android$app.vanadium.browser/app.vanadium.browser, d1a93218-f630-40c0-9e68-fb51ece928a6;Key not found 17964712865159225500 in DynamicTrieKeyMapper /data/system_ce/0/appsearch/icing/document_dir/key_mapper_dir/key_mapper.
--------- switch to system
         1706970592.999  1000  1339  1561 E ShortcutService: Failed deleting d1a93218-f630-40c0-9e68-fb51ece928a6, error message:Failed to delete Document. namespace: android$app.vanadium.browser/app.vanadium.browser, uri: d1a93218-f630-40c0-9e68-fb51ece928a6;Failed to find DocumentId by key: android$app.vanadium.browser/app.vanadium.browser, d1a93218-f630-40c0-9e68-fb51ece928a6;Key not found 17964712865159225500 in DynamicTrieKeyMapper /data/system_ce/0/appsearch/icing/document_dir/key_mapper_dir/key_mapper.
--------- switch to events
         1706970593.298  1000  1339  2239 I wm_finish_activity: [User=0,Token=130882098,Task ID=170,Component Name=com.android.launcher3/.dragndrop.AddItemActivity,Reason=app-request]
         1706970593.298  1000  1339  2239 I wm_task_moved: [TaskId=166,Root Task ID=166,Display Id=0,ToTop=1,Index=5]
         1706970593.298  1000  1339  2239 I wm_task_to_front: [User=0,Task=166,Display Id=0]
         1706970593.300  1000  1339  2239 I wm_focused_root_task: [User=0,Display Id=0,Focused Root Task Id=166,Last Focused Root Task Id=170,Reason=finish-top adjustFocusToNextFocusableTask]
         1706970593.302  1000  1339  2239 I wm_pause_activity: [User=0,Token=130882098,Component Name=com.android.launcher3/.dragndrop.AddItemActivity,User Leaving=userLeaving=false,Reason=finish]
```

**Comment by mikila85** [comment]
same here

**Comment by MichaelDevon** [comment]
probably upstream, as this happened in lineageOS to me as well

**Comment by mrxx0** [comment]
I'm not sure in which Vanadium update the upstream fix was added, but this problem no longer exists.
