### ISSUE TITLE
Camera causes system to crash randomly

### ISSUE THREAD

**Issue by Neu-Maximilian** [GrapheneOS/os-issue-tracker#3179]
```
type: crash
Process: system_server
Build: google/shiba/shiba:14/UQ1A.240105.004/2024012600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalArgumentException: setTorchMode:2626: Camera ID "0" is a not valid camera ID
	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1625)
	at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:2288)
	at android.hardware.camera2.CameraManager.setTorchMode(CameraManager.java:1152)
	at com.android.server.accessibility.FlashNotificationsController.doCameraFlashNotification(FlashNotificationsController.java:658)
	at com.android.server.accessibility.FlashNotificationsController.doCameraFlashNotificationOn(FlashNotificationsController.java:611)
	at com.android.server.accessibility.FlashNotificationsController.-$$Nest$mdoCameraFlashNotificationOn(FlashNotificationsController.java:0)
	at com.android.server.accessibility.FlashNotificationsController$FlashNotificationThread.startFlashNotification(FlashNotificationsController.java:808)
	at com.android.server.accessibility.FlashNotificationsController$FlashNotificationThread.run(FlashNotificationsController.java:767)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.ServiceSpecificException: setTorchMode:2626: Camera ID "0" is a not valid camera ID (code 3)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3080)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.hardware.ICameraService$Stub$Proxy.setTorchMode(ICameraService.java:1008)
	at android.hardware.camera2.CameraManager$CameraManagerGlobal.setTorchMode(CameraManager.java:2286)
	... 11 more
```

**Comment by Neu-Maximilian** [comment]
> This looks like a hardware failure.

The camera app was showing a blank (black) feed before and after the crash. After restarting again though, it returned. I think the issue lies with the camera server, not the hardware as it is brand new. However I doubt it would be easy to duplicate.
