### ISSUE TITLE
GmsCompat crash

### ISSUE THREAD

**Issue by cyphar** [GrapheneOS/os-issue-tracker#3195]
```
type: crash
osVersion: google/shiba/shiba:14/UQ1A.240105.004/2024012600:user/release-keys
package: com.google.android.gms:240213038
process: com.google.android.gms.persistent
processUptime: 77255142 + 237 ms
installer: com.android.vending
GmsCompatConfig version: 93

java.lang.SecurityException: registerVibratorStateListener: Neither user 10141 nor current process has android.permission.ACCESS_VIBRATOR_STATE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.os.IVibratorManagerService$Stub$Proxy.registerVibratorStateListener(IVibratorManagerService.java:323)
	at android.os.SystemVibratorManager$SingleVibrator.addVibratorStateListener(SystemVibratorManager.java:286)
	at android.os.SystemVibratorManager$SingleVibrator.addVibratorStateListener(SystemVibratorManager.java:262)
	at dvwp.b(:com.google.android.gms@240213038@24.02.13 (190400-599553831):50)
	at dwbl.a(:com.google.android.gms@240213038@24.02.13 (190400-599553831):3)
	at dwby.r(:com.google.android.gms@240213038@24.02.13 (190400-599553831):20)
	at dwbo.i(:com.google.android.gms@240213038@24.02.13 (190400-599553831):3)
	at dwbl.d(:com.google.android.gms@240213038@24.02.13 (190400-599553831):26)
	at dwby.d(:com.google.android.gms@240213038@24.02.13 (190400-599553831):8)
	at dwbr.run(:com.google.android.gms@240213038@24.02.13 (190400-599553831):10)
	at akki.c(:com.google.android.gms@240213038@24.02.13 (190400-599553831):50)
	at akki.run(:com.google.android.gms@240213038@24.02.13 (190400-599553831):97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at akpt.run(:com.google.android.gms@240213038@24.02.13 (190400-599553831):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: ebdl: 
		at tk_trace.location-_onReceive_scheduled_t(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2395)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2423)
	at com.android.server.vibrator.VibratorManagerService.registerVibratorStateListener(VibratorManagerService.java:312)
	at android.os.IVibratorManagerService$Stub.onTransact(IVibratorManagerService.java:171)
	at android.os.Binder.execTransactInternal(Binder.java:1387)
```

**Comment by cyphar** [comment]
It happened a few more times today, while doing random tasks (watching videos in NewPipe, etc). The crash seems to coincide with when the location service is trying to get location data (the green bubble notification for location data access pops up right as the crash occurs).

(I'm using Google's accurate location service rather than the system location service.)
