### ISSUE TITLE
Constant repeated system_server crashes

### ISSUE THREAD

**Issue by Solhex** [GrapheneOS/os-issue-tracker#3200]
Since I think last month I've been getting system_server crashes every so often, but ignored it waiting for the next update, but since the latest update, 14 (UQ1A.240205.002), whenever it crashes it tends to crash non stop with around a minute or two between each crash (see below).

![Screenshot_20240208-000550.png](https://github.com/GrapheneOS/os-issue-tracker/assets/66540788/42dda1f5-a01f-483e-8cd3-05441e0b16bc)

Nothing that I could note of has happened before each crash, but below I've pasted a few crash logs of the issue.

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240205.002/2024020500:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 420546432 byte allocation with 100663296 free bytes and 200MB until OOM, target footprint 426912048, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3553)
	at java.util.Arrays.copyOf(Arrays.java:3522)
	at java.util.ArrayList.grow(ArrayList.java:244)
	at java.util.ArrayList.grow(ArrayList.java:251)
	at java.util.ArrayList.add(ArrayList.java:461)
	at java.util.ArrayList.add(ArrayList.java:474)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacketReader.readLabels(MdnsPacketReader.java:170)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPointerRecord.readData(MdnsPointerRecord.java:54)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsRecord.<init>(MdnsRecord.java:88)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPointerRecord.<init>(MdnsPointerRecord.java:37)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecord(MdnsPacket.java:164)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecords(MdnsPacket.java:115)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecordsSection(MdnsPacket.java:99)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsResponseDecoder.parseResponse(MdnsResponseDecoder.java:102)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsMultinetworkSocketClient.processResponsePacket(MdnsMultinetworkSocketClient.java:243)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsMultinetworkSocketClient.-$$Nest$mprocessResponsePacket(MdnsMultinetworkSocketClient.java:0)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsMultinetworkSocketClient$ReadPacketHandler.handlePacket(MdnsMultinetworkSocketClient.java:159)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:101)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:34)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.handleInput(FdEventsReader.java:261)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.lambda$createAndRegisterFd$0(FdEventsReader.java:217)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.$r8$lambda$xh0yZpbdLvlMgmz3uMcpPMcWNvc(FdEventsReader.java:0)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader$$ExternalSyntheticLambda0.onFileDescriptorEvents(R8$$SyntheticClass:0)
	at android.os.MessageQueue.dispatchEvents(MessageQueue.java:293)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240205.002/2024020500:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 420546432 byte allocation with 100646912 free bytes and 195MB until OOM, target footprint 432977264, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3553)
	at java.util.Arrays.copyOf(Arrays.java:3522)
	at java.util.ArrayList.grow(ArrayList.java:244)
	at java.util.ArrayList.grow(ArrayList.java:251)
	at java.util.ArrayList.add(ArrayList.java:461)
	at java.util.ArrayList.add(ArrayList.java:474)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacketReader.readLabels(MdnsPacketReader.java:170)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPointerRecord.readData(MdnsPointerRecord.java:54)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsRecord.<init>(MdnsRecord.java:88)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPointerRecord.<init>(MdnsPointerRecord.java:37)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecord(MdnsPacket.java:164)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecords(MdnsPacket.java:115)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecordsSection(MdnsPacket.java:99)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parse(MdnsPacket.java:82)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsInterfaceAdvertiser.handlePacket(MdnsInterfaceAdvertiser.java:318)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:101)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:34)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.handleInput(FdEventsReader.java:261)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.lambda$createAndRegisterFd$0(FdEventsReader.java:217)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.$r8$lambda$xh0yZpbdLvlMgmz3uMcpPMcWNvc(FdEventsReader.java:0)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader$$ExternalSyntheticLambda0.onFileDescriptorEvents(R8$$SyntheticClass:0)
	at android.os.MessageQueue.dispatchEvents(MessageQueue.java:293)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240205.002/2024020500:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 420546432 byte allocation with 100663296 free bytes and 203MB until OOM, target footprint 424147984, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3553)
	at java.util.Arrays.copyOf(Arrays.java:3522)
	at java.util.ArrayList.grow(ArrayList.java:244)
	at java.util.ArrayList.grow(ArrayList.java:251)
	at java.util.ArrayList.add(ArrayList.java:461)
	at java.util.ArrayList.add(ArrayList.java:474)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacketReader.readLabels(MdnsPacketReader.java:170)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPointerRecord.readData(MdnsPointerRecord.java:54)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsRecord.<init>(MdnsRecord.java:88)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPointerRecord.<init>(MdnsPointerRecord.java:37)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecord(MdnsPacket.java:164)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecords(MdnsPacket.java:115)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsPacket.parseRecordsSection(MdnsPacket.java:99)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsResponseDecoder.parseResponse(MdnsResponseDecoder.java:102)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsMultinetworkSocketClient.processResponsePacket(MdnsMultinetworkSocketClient.java:243)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsMultinetworkSocketClient.-$$Nest$mprocessResponsePacket(MdnsMultinetworkSocketClient.java:0)
	at android.net.connectivity.com.android.server.connectivity.mdns.MdnsMultinetworkSocketClient$ReadPacketHandler.handlePacket(MdnsMultinetworkSocketClient.java:159)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:101)
	at android.net.connectivity.com.android.server.connectivity.mdns.MulticastPacketReader.handlePacket(MulticastPacketReader.java:34)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.handleInput(FdEventsReader.java:261)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.lambda$createAndRegisterFd$0(FdEventsReader.java:217)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader.$r8$lambda$xh0yZpbdLvlMgmz3uMcpPMcWNvc(FdEventsReader.java:0)
	at android.net.connectivity.com.android.net.module.util.FdEventsReader$$ExternalSyntheticLambda0.onFileDescriptorEvents(R8$$SyntheticClass:0)
	at android.os.MessageQueue.dispatchEvents(MessageQueue.java:293)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Solhex** [comment]
> @Solhex This is a bug seemingly being triggered by mDNS. It only happens when you're connected to your home Wi-Fi network, right? There must be a device on the network triggering this OS bug. It looks like a serious bug in Android.

Mmm I suppose I have been constantly using my own WireGuard VPN (with either a full or split tunnel config), with pihole and unbound one of which could be the issue, but another factor may also be my accommodation's Wi-Fi (Glide) which doesn't seem to properly segment off other users devices from mine which also could be the issue.

I'll try running a few days without one or the other and see what might be causing it on my end, thanks for the heads up. 👍
