### ISSUE TITLE
System crash when switching users whilst media playing

### ISSUE THREAD

**Issue by derei** [GrapheneOS/os-issue-tracker#3208]
Secondary user configured to keep keep running in background. Switched to Owner whilst Prime Video was playing under secondary user. System Crashed during switching.

```
type: crash
Process: system_server
Build: google/cheetah/cheetah:14/UQ1A.240205.002/2024020500:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3707)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1713)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1563)
	at com.android.server.am.UserController.startUser(UserController.java:1517)
	at com.android.server.am.UserController.startUser(UserController.java:1476)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1822)
	at com.android.server.am.UserController.handleMessage(UserController.java:3090)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by derei** [comment]
> @derei Did you switch or use end session? Is the issue still happening?

Yes, issue is still happening and it appears to have a deeper cause. I started collecting logs, because GOSdfreezes and crashes in most random situations. So far it appears to be a drivers or power management issues and it may be linked to display initialisation, but I'm in no position to make any claims. I'm a mere pleb with minimal knowledge. However, I'd be happy to hand over crash logs to some of the GOS devs, and even to follow instructions for more detailed logging or debugging. 

Let me know if there is anything I can do.

**Comment by sparagi** [comment]
I got the following stack trace, which is nearly identical to the one in #3381, after:
- I was using my main secondary account.
- I switched into the owner account by swiping down, selecting my avatar, then selecting the owner account.  The owner account only accepts my PIN, no fingerprint.
- I updated apps from F-Droid, perhaps impatiently pressing some Update buttons twice.
- It kept popping up a dialog about how the Process something (manager?) was frozen and did I want to kill it or wait (will update with exact phrasing next time I see this dialog); I said wait each time.
- I eventually used the power button to try to Restart, Power Off, and I don't remember if I tried Lockdown, but everything I tried (several times each, with and without pauses between) did nothing.
- Found another pop-up as above; this time, I said to kill it.
- Still Restart did nothing.  I may have tried Power Off again as well.
- I tried to switch users back to my main secondary account following the same procedure as above.  At the moment, this secondary account accepts PIN or fingerprint.
- It paused with the avatar for my main secondary account on the screen, with a progress bar circling it, for maybe 15 seconds.  I don't think I had authenticated yet but am not sure.
- The phone finally restarted.
- After the restart, I could still see my background and desktop (I think for the main secondary user but am not sure) for a good second but when I touched the screen, it gave me the usual prompt (for PIN entry for the owner account) after a restart. 

I include all this in case it sheds light on the trigger for this issue, or someone else can see what is in common with what they were doing.  These are most definitely *not* repro steps.

Let me know if I should open other bugs about things that were going wrong earlier in the steps above; I wasn't planning to since the steps are so vague I can't see what anyone could do about it.  Next time, I'll start documenting earlier in the process of something going strangely so I have more specific and useful data.

```
type: crash
SystemUptimeMs: 141767618
Process: system_server
Build: google/oriole/oriole:14/AP1A.240405.002/2024040900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3860)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1812)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1663)
	at com.android.server.am.UserController.startUser(UserController.java:1617)
	at com.android.server.am.UserController.startUser(UserController.java:1576)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1921)
	at com.android.server.am.UserController.handleMessage(UserController.java:3220)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by bugQ** [comment]
same exception on `shiba` immediately upon switching to admin. admin had several bg tasks but all the secondary user had open was Telegram X. it is possible that an mp4 somebody had sent was playing silently at the time

**Comment by AkechiShiro** [comment]
Any idea in order to move forward to fix this issue ? @thestinger I see it is tagged as upstream, is this a bug in AOSP ?

**Comment by AkechiShiro** [comment]
Has this been reported upstream ?
