### ISSUE TITLE
Multiple app crashes when trying to access map component

### ISSUE THREAD

**Issue by Geojohnnxy** [GrapheneOS/os-issue-tracker#3223]
Hi everyone 

I have noticed after latest update that applications (i.e. Uber, Wolt, Bolt food, Google Photos... ) installed on my Pixel 7 that are in any way using google maps component are crashing whenever they try to render it. Applications are installed either on main or secondery user profiles. Sandboxed google services are updated to latest version and have been completely removed and reinstalled after crashes started to happen.
Applications like Here maps or StreetComplete that are having their own maping components are working as intended. 

I have a log from Photos app that crashes repeadetly after trying to see where photo was taken (by swiping up) but it is similar for other applications 
```
type: crash
osVersion: google/panther/panther:14/UQ1A.240205.002/2024020500:user/release-keys
package: com.google.android.apps.photos:48792611
process: com.google.android.apps.photos
processUptime: 3217 + 216 ms
installer: com.aurora.store

android.content.res.Resources$NotFoundException: Resource ID #0x7b08005f
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:243)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:998)
	at android.content.res.Resources.getDrawable(Resources.java:938)
	at android.content.res.Resources.getDrawable(Resources.java:913)
	at com.google.maps.api.android.lib6.impl.ay.n(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):41)
	at com.google.maps.api.android.lib6.impl.fc.<init>(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):46)
	at com.google.maps.api.android.lib6.impl.bk.aD(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):25)
	at com.google.maps.api.android.lib6.impl.cu.d(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):11)
	at com.google.android.gms.maps.internal.q.bb(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):159)
	at m.ef.onTransact(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):21)
	at android.os.Binder.transact(Binder.java:1224)
	at gxa.hP(PG:8)
	at akbk.b(PG:19)
	at ajut.b(PG:7)
	at aztc.z(PG:25)
	at akbl.f(PG:86)
	at ajux.d(PG:45)
	at ajux.a(PG:6)
	at com.google.android.gms.maps.MapView.c(PG:24)
	at thj.<init>(PG:21)
	at thk.c(PG:19)
	at acft.b(PG:16)
	at md.b(PG:19)
	at ov.q(PG:881)
	at ov.b(PG:6)
	at nl.a(PG:54)
	at android.support.v7.widget.LinearLayoutManager.k(PG:1)
	at android.support.v7.widget.LinearLayoutManager.J(PG:45)
	at android.support.v7.widget.LinearLayoutManager.o(PG:743)
	at android.support.v7.widget.RecyclerView.aS(PG:65)
	at android.support.v7.widget.RecyclerView.L(PG:62)
	at android.support.v7.widget.RecyclerView.onLayout(PG:8)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at com.google.android.apps.photos.mediadetails.MediaDetailsBehavior.s(PG:16)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:41)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at androidx.viewpager.widget.ViewPager.onLayout(PG:254)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.j(PG:365)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:47)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1880)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1640)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4455)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3767)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by Geojohnnxy** [comment]
Currently Play store is enabled without network access but I only enabled it yesterday while troubleshooting. Same problem occurs with play store enabled and disabled.   

Play services version:

```
version 23.49.14 (190400-590296185)

com.google.android.gms
versionCode 234914038

targetSdk 34
minSdk 31
```

**Comment by Geojohnnxy** [comment]
I did. I have one profile with a full google account support that has access to network (that I dont use often), and have managed to recapture error there as well. 

```

type: crash
osVersion: google/panther/panther:14/UQ1A.240205.002/2024020500:user/release-keys
package: com.google.android.apps.photos:48792611
process: com.google.android.apps.photos
processUptime: 8350 + 270 ms
installer: com.android.vending

android.content.res.Resources$NotFoundException: Resource ID #0x7b08005f
	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:243)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:998)
	at android.content.res.Resources.getDrawable(Resources.java:938)
	at android.content.res.Resources.getDrawable(Resources.java:913)
	at com.google.maps.api.android.lib6.impl.ay.n(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):41)
	at com.google.maps.api.android.lib6.impl.fc.<init>(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):46)
	at com.google.maps.api.android.lib6.impl.bk.aD(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):25)
	at com.google.maps.api.android.lib6.impl.cu.d(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):11)
	at com.google.android.gms.maps.internal.q.bb(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):159)
	at m.ef.onTransact(:com.google.android.gms.dynamite_mapsdynamite@234914038@23.49.14 (190400-0):21)
	at android.os.Binder.transact(Binder.java:1224)
	at gxa.hP(PG:8)
	at akbk.b(PG:19)
	at ajut.b(PG:7)
	at aztc.z(PG:25)
	at akbl.f(PG:86)
	at ajux.d(PG:45)
	at ajux.a(PG:6)
	at com.google.android.gms.maps.MapView.c(PG:24)
	at thj.<init>(PG:21)
	at thk.c(PG:19)
	at acft.b(PG:16)
	at md.b(PG:19)
	at ov.q(PG:881)
	at ov.b(PG:6)
	at nl.a(PG:54)
	at android.support.v7.widget.LinearLayoutManager.k(PG:1)
	at android.support.v7.widget.LinearLayoutManager.J(PG:45)
	at android.support.v7.widget.LinearLayoutManager.o(PG:743)
	at android.support.v7.widget.RecyclerView.aS(PG:65)
	at android.support.v7.widget.RecyclerView.L(PG:62)
	at android.support.v7.widget.RecyclerView.onLayout(PG:8)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at com.google.android.apps.photos.mediadetails.MediaDetailsBehavior.s(PG:16)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:41)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at androidx.viewpager.widget.ViewPager.onLayout(PG:254)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.j(PG:365)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(PG:47)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1880)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1640)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4455)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3767)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by muhomorr** [comment]
What's the version of "Apps" app?

**Comment by muhomorr** [comment]
It looks like you've installed Play services using a version of Apps that had a bug which led to incomplete installs of Play services.

That bug had been fixed few months ago. Have you been updating the OS regularly? Is auto-update enabled in Apps?

**Comment by Geojohnnxy** [comment]
> What's the version of "Apps" app?

I am on version 21


> It looks like you've installed Play services using a version of Apps that had a bug which led to incomplete installs of Play services.
> 
> That bug had been fixed few months ago. Have you been updating the OS regularly? Is auto-update enabled in Apps?

I don't have auto-updates on both "Apps" and on "OS" but I do a manual updates once in a while (every few weeks). 

What would you @muhomorr suggest to try next?

**Comment by muhomorr** [comment]
@Geojohnnxy Update Play services to the latest version via Play Store. Can do that even if you're not logged in to a Google account.

**Comment by muhomorr** [comment]
Alternatively, update Play services to the version that is currently in alpha in Apps (23.05.13).
