### ISSUE TITLE
system_server crashes shortly after any interaction

### ISSUE THREAD

**Issue by GambolingPangolin** [GrapheneOS/os-issue-tracker#3251]
My GrapheneOS install has become totally unstable.  In both normal and safe mode the `system_server` crashes within about 1 minute of any user interaction.

This seems to be related to #3200 but I encounter the bug on Wi-Fi, cellular only, and on airplane mode.

## Device and OS details

Phone: Pixel 7a
Android version: 14
Build number: `UQ1A.240205.002.2024020500`

### Example 1

```
type: crash
Process: system_server
Build: google/lynx/lynx:14/UQ1A.240205.002/2024020500:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1977256 free bytes and 1930KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.server.alarm.AlarmManagerService$AlarmHandler.handleMessage(AlarmManagerService.java:5142)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.android.server.SystemServer.run(SystemServer.java:981)
	at com.android.server.SystemServer.main(SystemServer.java:667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

### Example 2

```
type: crash
Process: system_server
Build: google/lynx/lynx:14/UQ1A.240205.002/2024020500:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 104 byte allocation with 3495336 free bytes and 3413KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.server.usage.UsageStatsProtoV2.parseEvent(UsageStatsProtoV2.java:237)
	at com.android.server.usage.UsageStatsProtoV2.read(UsageStatsProtoV2.java:498)
	at com.android.server.usage.UsageStatsDatabase.readLocked(UsageStatsDatabase.java:1154)
	at com.android.server.usage.UsageStatsDatabase.readLocked(UsageStatsDatabase.java:1108)
	at com.android.server.usage.UsageStatsDatabase.readLocked(UsageStatsDatabase.java:1091)
	at com.android.server.usage.UsageStatsDatabase.getLatestUsageStats(UsageStatsDatabase.java:753)
	at com.android.server.usage.UserUsageStatsService.loadActiveStats(UserUsageStatsService.java:899)
	at com.android.server.usage.UserUsageStatsService.rolloverStats(UserUsageStatsService.java:850)
	at com.android.server.usage.UserUsageStatsService.reportEvent(UserUsageStatsService.java:317)
	at com.android.server.usage.UsageStatsService.reportEvent(UsageStatsService.java:1173)
	at com.android.server.usage.UsageStatsService.onUserUnlocked(UsageStatsService.java:472)
	at com.android.server.usage.UsageStatsService.-$$Nest$monUserUnlocked(UsageStatsService.java:0)
	at com.android.server.usage.UsageStatsService$H.handleMessage(UsageStatsService.java:1949)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by GambolingPangolin** [comment]
> Try disabling (not uninstalling, so data will be kept) all of your user installed apps and see if it still happens.

Does running under safe mode not accomplish this?

**Comment by GambolingPangolin** [comment]
I tried going one-by-one to disable my user-installed apps but am unable to go to `Settings > Apps` on long-press an app and open its settings page via the context menu.

Opening up `Settings > Apps` generates the following error log:

[Error in Settings 1324b4cbdd39.txt](https://github.com/GrapheneOS/os-issue-tracker/files/14378241/Error.in.Settings.1324b4cbdd39.txt)

Also here is a system log, generated in between crashes:

[System log b6ba0d204b66.txt](https://github.com/GrapheneOS/os-issue-tracker/files/14378278/System.log.b6ba0d204b66.txt)

Are there any other logs etc. I can collect to help determine the cause of the problem?

**Comment by TheRedTopHat** [comment]
I'm also having what appears to be the same problem (correct me if I am wrong and I can create a new issue).

`system_server` consistently crashes at random, sometimes overnight when I am not interacting with the device.  I have uninstalled almost all of my user installed apps.  

Here is the most recent crash log which I woke up to today:
```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.240205.002/2024022800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 8 byte allocation with 5067648 free bytes and 4948KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
 at android.net.connectivity.com.android.server.connectivity.NetworkRanker.getBestNetworkByPolicy(NetworkRanker.java:256)
 at android.net.connectivity.com.android.server.connectivity.NetworkRanker.mightBeat(NetworkRanker.java:389)
 at android.net.connectivity.com.android.server.ConnectivityService.isNetworkPotentialSatisfier(ConnectivityService.java:4999)
 at android.net.connectivity.com.android.server.ConnectivityService.unneeded(ConnectivityService.java:4956)
 at android.net.connectivity.com.android.server.ConnectivityService.updateInactivityState(ConnectivityService.java:4515)
 at android.net.connectivity.com.android.server.ConnectivityService.applyNetworkReassignment(ConnectivityService.java:9561)
 at android.net.connectivity.com.android.server.ConnectivityService.rematchNetworksAndRequests(ConnectivityService.java:9498)
 at android.net.connectivity.com.android.server.ConnectivityService.rematchAllNetworksAndRequests(ConnectivityService.java:9484)
 at android.net.connectivity.com.android.server.ConnectivityService.handleRegisterNetworkRequests(ConnectivityService.java:4891)
 at android.net.connectivity.com.android.server.ConnectivityService.handleRegisterNetworkRequest(ConnectivityService.java:4858)
 at android.net.connectivity.com.android.server.ConnectivityService.-$$Nest$mhandleRegisterNetworkRequest(ConnectivityService.java:0)
 at android.net.connectivity.com.android.server.ConnectivityService$InternalHandler.handleMessage(ConnectivityService.java:5761)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.os.HandlerThread.run(HandlerThread.java:67)
```

Let me know if there is any other information I can provide.

**Comment by GambolingPangolin** [comment]
I ended up reinstalling GrapheneOS and have not had any problems since.

**Comment by havit1** [comment]
@thestinger sorry to reopen the issue, but i've just got this error on my phone. If it helps in any way, seems that it happened right after i connected the phone to the charger and it should have checked for os updates. Phone is in constant turn on -> freeze after about 8-10 sec -> reboot cycle
