### ISSUE TITLE
Google Play services crashing after 24.05 update

### ISSUE THREAD

**Issue by Tachi107** [GrapheneOS/os-issue-tracker#3259]
Hi all, after updating the Google Play services to version 24.05 from the Apps app, I keep getting crash reports from GmsCompat, and I'm unable to use some apps (e.g. Snapchat).

I'm running GrapheneOS on Android 13, on an old Pixel 4.

Here's one of the crash logs:

```
type: crash
osVersion: google/flame/flame:13/TP1A.221005.002.B2/2023100300:user/release-keys
package: com.google.android.gms:240513038
process: com.google.android.gms.persistent
processUptime: 923 + 74 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 96

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a156; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5111)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1473)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1440)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at dblf.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):43)
	at dbll.g(:com.google.android.gms@240513038@24.05.13 (190400-602827846):737)
	at dblh.a(:com.google.android.gms@240513038@24.05.13 (190400-602827846):7)
	at dblh.c(:com.google.android.gms@240513038@24.05.13 (190400-602827846):13)
	at dbls.f(:com.google.android.gms@240513038@24.05.13 (190400-602827846):50)
	at bixd.fj(:com.google.android.gms@240513038@24.05.13 (190400-602827846):1)
	at bixm.run(:com.google.android.gms@240513038@24.05.13 (190400-602827846):100)
	at echc.run(:com.google.android.gms@240513038@24.05.13 (190400-602827846):21)
	at aktm.c(:com.google.android.gms@240513038@24.05.13 (190400-602827846):50)
	at aktm.run(:com.google.android.gms@240513038@24.05.13 (190400-602827846):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at akza.run(:com.google.android.gms@240513038@24.05.13 (190400-602827846):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: echm: 
		at tk_trace.326-singleuserapi.RetrieveGlobalState(Unknown Source:0)
		at tk_trace.time-TrustedTimeAllUserChimeraService-IGmsServiceBroker_45(Unknown Source:0)
		at tk_trace.thunderbird-EmergencyPersistentChimeraService_onCreate(Unknown Source:0)
```

I know the Pixel 4 is now out of date and unsupported, but I believe this might be a legit bug in the Gms compatibility layer.

Thanks :)

**Comment by Tachi107** [comment]
Hi Daniel, thanks for your reply. Indeed, updating the OS fixes the issue. I had disabled the System Updates app for some reason, and forgot about it. Thanks again and sorry for the useless report!
