### ISSUE TITLE
System server crash after reboot installing latest version

### ISSUE THREAD

**Issue by Lonami** [GrapheneOS/os-issue-tracker#3279]
I haven't actually noticed anything fail, but since I can't find a report with this, I figured I would open the issue anyway.

```
type: crash
Process: system_server
Build: google/bluejay/bluejay:14/UQ1A.240205.002/2024022800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
	at com.android.server.biometrics.sensors.MultiBiometricLockoutState.clearPermanentLockOut(MultiBiometricLockoutState.java:89)
	at com.android.server.biometrics.sensors.AuthSessionCoordinator.resetLockoutFor(AuthSessionCoordinator.java:190)
	at com.android.server.biometrics.BiometricService$BiometricServiceWrapper.resetLockout(BiometricService.java:801)
	at com.android.server.biometrics.AuthService$AuthServiceImpl.resetLockout(AuthService.java:422)
	at android.hardware.biometrics.BiometricManager.resetLockout(BiometricManager.java:633)
	at com.android.server.locksettings.BiometricDeferredQueue.processPendingLockoutsGeneric(BiometricDeferredQueue.java:284)
	at com.android.server.locksettings.BiometricDeferredQueue.lambda$processPendingLockoutResets$2(BiometricDeferredQueue.java:200)
	at com.android.server.locksettings.BiometricDeferredQueue.$r8$lambda$eWjWUQoyro5PCAdi89XiYP-Cm1Q(BiometricDeferredQueue.java:0)
	at com.android.server.locksettings.BiometricDeferredQueue$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by aljvdevel** [comment]
Similar thing here here, however system became unresponsive and i forced a shutdown



```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.240205.002/2024022800:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 1125s

abortMessage: GrContext is abandoned/device lost at start of CanvasContext::draw

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 62ea4)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1456, pc 64be80)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 38730)
    /system/lib64/liblog.so (__android_log_assert+308, pc 6fd4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+2664, pc 292d48)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+1324, pc 2952ac)
    /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+624, pc 2840d0)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+404, pc 2a67f4)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+284, pc 1430c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cfa2c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 64770)
```

**Comment by mrgnex** [comment]
Same thing here. Happened after switching between users:

````
type: crash
Process: system_server
Build: google/raven/raven:14/UQ1A.240205.002/2024022800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3707)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1713)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1563)
	at com.android.server.am.UserController.startUser(UserController.java:1517)
	at com.android.server.am.UserController.startUser(UserController.java:1476)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1822)
	at com.android.server.am.UserController.handleMessage(UserController.java:3090)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
`

**Comment by lu-ckystars** [comment]
same here

```
type: crash
Process: system_server
Build: google/panther/panther:14/UQ1A.240205.002/2024022800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.autofill.ui.FillUi$AnchoredWindow.show(android.view.WindowManager$LayoutParams)' on a null object reference
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.lambda$show$0(FillUi.java:674)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.$r8$lambda$CEe5P1gLU-tWCH12AKgRPwErweQ(FillUi.java:0)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)
```

**Comment by Lonami** [comment]
Sorry I tried to come up with a better title which would've hopefully prevented some of these duplicate posts, but felt like it would've gotten too long 😅

Let me try something better.
