### ISSUE TITLE
Google Play Services has crashed

### ISSUE THREAD

**Issue by olsonperrensen** [GrapheneOS/os-issue-tracker#3288]
```
type: crash
osVersion: google/panther/panther:14/UQ1A.240205.002/2024030300:user/release-keys
package: com.google.android.gms:240513038
process: com.google.android.gms
processUptime: 245677 + 308 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 97

java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{9038b2a 2279:com.google.android.gms/u16a134} (pid=2279, uid=1610134) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5950)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7412)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3734)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2572)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1167)
	at android.content.ContentResolver.query(ContentResolver.java:1123)
	at com.google.android.gms.people.sync.focus.ContactsSyncIntentOperation.onHandleIntent(:com.google.android.gms@240513038@24.05.13 (190400-602827846):164)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@240513038@24.05.13 (190400-602827846):2)
	at ahpx.onHandleIntent(:com.google.android.gms@240513038@24.05.13 (190400-602827846):10)
	at omm.run(:com.google.android.gms@240513038@24.05.13 (190400-602827846):70)
	at oml.run(:com.google.android.gms@240513038@24.05.13 (190400-602827846):152)
	at echc.run(:com.google.android.gms@240513038@24.05.13 (190400-602827846):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:691)
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:287)
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:144)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6858)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2784)
```

**Comment by olsonperrensen** [comment]
I had GPS fully installed up until one hour ago. Got rid of Play Store and then re-installed it when the crash happened. I had the full log as well but it seems lost at the moment. Is there a way I can send it to you privately?

**Comment by FID02** [comment]
Can't repro with the steps provided. Tried in a fresh user profile. Although a bit unclear what I'm actually supposed to do...
