### ISSUE TITLE
crash in dialer when attempting to view RTT logs

### ISSUE THREAD

**Issue by easrng** [GrapheneOS/os-issue-tracker#3305]
Rlevant logs:
```
type: logcat
osVersion: google/bluejay/bluejay:14/UQ1A.240205.002/2024030300:user/release-keys
packageName: com.android.dialer:2900000
buffers: main,system,crash,events
level: verbose

--------- beginning of crash
1709942028.572 28569 28569 E AndroidRuntime: FATAL EXCEPTION: main
1709942028.572 28569 28569 E AndroidRuntime: Process: com.android.dialer, PID: 28569
1709942028.572 28569 28569 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.dialer/com.android.dialer.rtt.RttTranscriptActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3833)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3974)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8279)
1709942028.572 28569 28569 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
1709942028.572 28569 28569 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
1709942028.572 28569 28569 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
1709942028.572 28569 28569 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
1709942028.572 28569 28569 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
1709942028.572 28569 28569 E AndroidRuntime: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
1709942028.572 28569 28569 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:664)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:6)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
1709942028.572 28569 28569 E AndroidRuntime: 	at com.android.dialer.rtt.RttTranscriptActivity.onCreate(RttTranscriptActivity.java:7)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8674)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8652)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
1709942028.572 28569 28569 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
1709942028.572 28569 28569 E AndroidRuntime: 	... 14 more
```

**Comment by empratyush** [comment]
has been fixed.
