### ISSUE TITLE
Getting GmsCompat crash after trying to authorize with FIDO2 security key using NFC

### ISSUE THREAD

**Issue by L11R** [GrapheneOS/os-issue-tracker#3314]
I have this problem only with Solo 2 keys, Yubikey works correctly. Maybe something wrong with they key, but it works on some sites.

```
type: crash
osVersion: google/bluejay/bluejay:14/AP1A.240305.019.A1/2024030900:user/release-keys
package: com.google.android.gms:240812038
process: com.google.android.gms.ui
processUptime: 35578 + 61 ms
installer: com.android.vending
GmsCompatConfig version: 98

java.lang.IllegalArgumentException: Short encoding mandated, but APDU has more than 255 bytes of data
	at athc.a(:com.google.android.gms@240812038@24.08.12 (190400-608507424):62)
	at atha.d(:com.google.android.gms@240812038@24.08.12 (190400-608507424):1)
	at atdu.i(:com.google.android.gms@240812038@24.08.12 (190400-608507424):239)
	at atdu.h(:com.google.android.gms@240812038@24.08.12 (190400-608507424):1)
	at atdu.j(:com.google.android.gms@240812038@24.08.12 (190400-608507424):11)
	at atdu.g(:com.google.android.gms@240812038@24.08.12 (190400-608507424):12)
	at aump.run(:com.google.android.gms@240812038@24.08.12 (190400-608507424):124)
	at alab.c(:com.google.android.gms@240812038@24.08.12 (190400-608507424):50)
	at alab.run(:com.google.android.gms@240812038@24.08.12 (190400-608507424):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at alfp.run(:com.google.android.gms@240812038@24.08.12 (190400-608507424):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: edpc: 
```

**Comment by L11R** [comment]
I just got it after few tries also with Yubikey, but it's not consistent (with Solo 2 I get uit everytime) Maybe it relates to stability of NFC connection?

**Comment by L11R** [comment]
With USB both keys works perfectly, yeah, I get it only with NFC. Sure could be in upstream, but I don't have another Pixel to test...

**Comment by FID02** [comment]
I registered an account at miniflux.app in order to test this on GrapheneOS. I then registered a Yubikey 5 as a passkey, using NFC, which was successful. Notably the site doesn't offer the option of using FIDO2 as MFA.

Attempting to sign in to miniflux.app with the Yubikey makes the site show an error, but I'm not getting a crash. Tried with NFC and USB.

I did the same on stock PixelOS (QPR2): same error. Unable to sign in with the Yubikey.

I checked the resident keys on the Yubikey using Yubico Authenticator: there is no passkey from miniflux.app stored on the Yubikey.

I'm not self-hosting miniflux.app.

Error displayed on the site:

`Unable to login with passkey (NotAllowedError: The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.)`

L11R: Does this only occur on miniflux.app or can you reproduce this on other sites as well?

**Comment by L11R** [comment]
Miniflux has weird UX decision: in order to login with Passkey you need to type login, leave empty password field and finally click Login with Passkey.

**Comment by FID02** [comment]
> Miniflux has weird UX decision: in order to login with Passkey you need to type login, leave empty password field and finally click Login with Passkey.

Ah, I see. I now successfully signed in to minireader.app with a Yubikey 5 using NFC. Tried 4 times, always succeeded. On GrapheneOS.

I don't have a Solo 2 key available to try with.

**Comment by L11R** [comment]
Thanks for testing, probably it's something with my Solo 2. But it shouldn't crash anyway in my opinion.

**Comment by MSnaker** [comment]
> This looks like it might occur on stock OS too.

It does. I had this problem and I think I reported it already, and you or some other developer gave me the same answer.
Then I was on stock for like a week, during which I tried to use Solo Key2 (NFC) and the same happened in that instance.
It's not like I cannot use it at all, but the crash has a high occurrence.

**Comment by cameronaaron** [comment]
same
