### ISSUE TITLE
Crash and reboot after latest Vanadium update (p6pro)

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/os-issue-tracker#3324]
```
type: crash
SystemUptimeMs: 10249749
Process: system_server
Build: google/raven/raven:14/AP1A.240305.019.A1/2024031100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.pm.PackageSetting.getTargetSdkVersion()' on a null object reference
	at com.android.server.pm.InstallPackageHelper.preparePackageLI(InstallPackageHelper.java:1291)
	at com.android.server.pm.InstallPackageHelper.installPackagesLI(InstallPackageHelper.java:968)
	at com.android.server.pm.InstallPackageHelper.installPackagesTraced(InstallPackageHelper.java:930)
	at com.android.server.pm.PackageManagerService.installPackagesTraced(PackageManagerService.java:8165)
	at com.android.server.pm.InstallingSession.processApkInstallRequests(InstallingSession.java:537)
	at com.android.server.pm.InstallingSession.processInstallRequests(InstallingSession.java:526)
	at com.android.server.pm.InstallingSession.-$$Nest$mprocessInstallRequests(InstallingSession.java:0)
	at com.android.server.pm.InstallingSession$MultiPackageInstallingSession.lambda$tryProcessInstallRequest$0(InstallingSession.java:702)
	at com.android.server.pm.InstallingSession$MultiPackageInstallingSession.$r8$lambda$FG4z4NCeCPsiEmF_i1M46hmAqCo(InstallingSession.java:0)
	at com.android.server.pm.InstallingSession$MultiPackageInstallingSession$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by robovoice1** [comment]
Keeps crashing after all files are downloaded and installing.

@thestinger

**Comment by shift18** [comment]
As my system has newer crash before i thought it prudent to post the log file.

**How it happened**
Vanadium half loaded an image, then i tried to change tab, vanadium froze then i got logged out and after logging in the system crashed and the GOS logo appeared.

```
type: crash
osVersion: google/bluejay/bluejay:14/AP1A.240305.019.A1/2024031400:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 59134s

abortMessage: Lost GPU device unexpectedly

signal: 6 (SIGABRT), code -1 (SI_QUEUE)
threadName: RenderThread

backtrace:
    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164, pc 64ec4)
    /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+632, pc 938568)
    /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80, pc 19ad0)
    /system/lib64/liblog.so (__android_log_assert+292, pc 70e4)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw(bool)+4440, pc 34d378)
    /system/lib64/libhwui.so (std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c303f2d2360db58ed70a2d0ac7ed911b)+944, pc 398710)
    /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+760, pc 4b84c8)
    /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+368, pc 14280)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf97c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 66770)
```

**Comment by shift18** [comment]
> @shift18 That's a known issue and is a different one from the one above.

Ok, good to know.
