### ISSUE TITLE
Android Auto Crash

### ISSUE THREAD

**Issue by gaderic** [GrapheneOS/os-issue-tracker#3336]
Phone was connected via usb to a Jenson CAR8000 radio system.

```
type: crash
osVersion: google/oriole/oriole:14/AP1A.240305.019.A1/2024031100:user/release-keys
package: com.google.android.projection.gearhead:114640814
process: com.google.android.projection.gearhead:projection
processUptime: 3668973 + 542 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 98

igk: Error registering car activity start processor.
	at ieu.n(SourceFile:8)
	at ieu.e(SourceFile:1)
	at kki.dF(SourceFile:2)
	at trj.c(SourceFile:44)
	at jeg.k(SourceFile:4)
	at jed.a(SourceFile:4)
	at igh.v(SourceFile:16)
	at ilr.a(SourceFile:116)
	at ohw.f(SourceFile:4)
	at ohk.run(SourceFile:11)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: owa: java.lang.IllegalStateException: OutOfCarLifecycle
	at ogo.cu(SourceFile:8)
	at ogo.ct(SourceFile:1)
	at ovc.h(SourceFile:4)
	at ovc.g(SourceFile:2)
	at iue.a(SourceFile:52)
	at igq.a(SourceFile:29)
	at ieu.n(SourceFile:1)
	... 19 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3199)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at gml.ef(SourceFile:3)
	at oja.aw(SourceFile:3)
	at ojk.b(SourceFile:5)
	at oqg.a(SourceFile:24)
	at ogc.d(SourceFile:2)
	at oqc.a(SourceFile:11)
	at ovc.g(SourceFile:1)
	... 22 more
```

**Comment by muhomorr** [comment]
Crash log indicates that this is a USB connectivity issue. Does it happen regularly?

**Comment by gaderic** [comment]
Fat fingered the close button on mobile.

**Comment by muhomorr** [comment]
No need for extra logs for this issue unless new cable doesn't help.

Bluetooth disconnects are a separate issue.

**Comment by gaderic** [comment]
Understood. I should have the new cable soon. I'll probably be able to update this ticket if the issue continues later next week. I don't drive every day for work so I'll try to reproduce it on Sunday if possible.

**Comment by gaderic** [comment]
I've been driving for a few days now making sure to use Android Auto the whole time. I haven't had any problems since so I think it's safe to assume the old USB cable had gone bad.
