### ISSUE TITLE
system_server crash @profile switch on 20240309

### ISSUE THREAD

**Issue by goshuberto** [GrapheneOS/os-issue-tracker#3340]
happened repeatedly - taking much mor time since this update and leads to rebbot  in one out of three switch-attempts

```
type: crash
SystemUptimeMs: 26888294
Process: system_server
Build: google/panther/panther:14/AP1A.240305.019.A1/2024031100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3860)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1812)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1663)
	at com.android.server.am.UserController.startUser(UserController.java:1617)
	at com.android.server.am.UserController.startUser(UserController.java:1576)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1921)
	at com.android.server.am.UserController.handleMessage(UserController.java:3220)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by goshuberto** [comment]
Thanks and sorry for the overhead... maybe not closing, but setting on-hold, was a better method to let bug submitter find duplicates beforehand...

I understand that GrapheneOS is not the author of the code leading to this bug, hence it's not their ultimate responsibility to fix of course.
But GrapheneOS currently distributes regressive releases.  Closing such a bug might mislead people, who are crawling through the issue-tracker _before_ installing updates.  They would think everthing's fine with latest releases, no relevant open issues...
Or explicitly mark the repo/issue-tracker as "AOSP-addon part of GrapheneOS" - I'm running GrapheneOS not on top of AOSP but as monolithical distributed device firmware.  And this firmware shows a severe regression, hence I expect such bugs to be kept open/unresolved/on-hold - whataver, but _not_ closesd... IMHO.

Thanks!

**Comment by goshuberto** [comment]
Thanks for letting me know - I feared there's no way back...
Please, let me assure absolutely _nothing_ was changed on the phone, besides upgrading GrapheneOS - no setting was changed and not a single App was removed/installed/updated when I first noticed...
Meanwhile I started a 2nd attempt to find the corresponding upstream issue, using 'Keyguard is not shown in 20 seconds' .
The only issues I could find are from GrapheneOS issue-tracker and show a different stack trace.
And of course services/core/java/com/android/server/am/UserController.java

Currently I'm not convinced that this issue is beeing tracked upstream nor that it originates in a bug upstream.  Curious to see what happens on my non-GrapheneOS devices after receiving a  QPR2 update...  since it's not happening only after 'end session'-induced (forced) switch, but also during hot-switch, I guess I can expect them to crash too :-(

Is there a specific upstream version suspect to introduced the bug?  Meaning, how long is the 
'Keyguard is not shown in 20 seconds' crash known?

P.S.: This raises the backup problem:  Secondary profiles can't be restored currently - so my cold-standby device is pretty useless. I could install 2024030900 - hence there was a way back, but I can't copy my profiles :-(

**Comment by goshuberto** [comment]
2024032100 solved the issue for me - at least back to the same severity it was before 2024030[[:digit:]]{3,3}
Somtimes there's still a soft-reboot occurring, but 1 out of 100 instead of 2 out of 3 switches (switching with screen locked led to fewer crashes than switching from active hoescreen/app; just in case somebody stumbles across this post while tracking the issue...)
