### ISSUE TITLE
system server crash

### ISSUE THREAD

**Issue by firefoxlover** [GrapheneOS/os-issue-tracker#3366]
```
type: crash
SystemUptimeMs: 50468703
Process: system_server
Build: google/bluejay/bluejay:14/AP1A.240305.019.A1/2024032100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.autofill.ui.FillUi$AnchoredWindow.show(android.view.WindowManager$LayoutParams)' on a null object reference
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.lambda$show$0(FillUi.java:685)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.$r8$lambda$rayRxR7zWVCJ_EZ9KlZ9jO79cqM(FillUi.java:0)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)
```

Opening Vanadium, suddenly threw me to the boot screen.

**Comment by firefoxlover** [comment]
exact infos:

I tried to open a website in latest mull and google recaptcha blocked some stuff. I had KeepassXC open which works as password manager app so probably uses autofill.

I opened the website with the link added to the KeepassXC entry, so that it may fill out that field.

I opened vanadium, opened that website and it threw me to the GrapheneOS boot screen and afterwards I got the "system server crashed" message where I got this log.

So this is likely a Vanadium bug
