### ISSUE TITLE
Play services crash trying to use ac NFC security key

### ISSUE THREAD

**Issue by idk-r-n** [GrapheneOS/os-issue-tracker#3400]
```
type: crash
osVersion: google/oriole/oriole:14/AP1A.240405.002/2024040300:user/release-keys
package: com.google.android.gms:240812038
process: com.google.android.gms.ui
processUptime: 7534 + 206 ms
installer: com.android.vending
GmsCompatConfig version: 101

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@6d63206
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1818)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fd.aE(:com.google.android.gms@240812038@24.08.12 (190400-608507424):12)
	at fd.N(:com.google.android.gms@240812038@24.08.12 (190400-608507424):27)
	at bs.c(:com.google.android.gms@240812038@24.08.12 (190400-608507424):66)
	at bs.a(:com.google.android.gms@240812038@24.08.12 (190400-608507424):2)
	at cx.ik(:com.google.android.gms@240812038@24.08.12 (190400-608507424):109)
	at cx.dismiss(:com.google.android.gms@240812038@24.08.12 (190400-608507424):2)
	at dzae.dismiss(:com.google.android.gms@240812038@24.08.12 (190400-608507424):8)
	at atet.r(:com.google.android.gms@240812038@24.08.12 (190400-608507424):52)
	at atet.k(:com.google.android.gms@240812038@24.08.12 (190400-608507424):86)
	at aupg.b(:com.google.android.gms@240812038@24.08.12 (190400-608507424):504)
	at atet.q(:com.google.android.gms@240812038@24.08.12 (190400-608507424):10)
	at atxf.f(:com.google.android.gms@240812038@24.08.12 (190400-608507424):5)
	at atmf.b(:com.google.android.gms@240812038@24.08.12 (190400-608507424):9)
	at aunn.c(:com.google.android.gms@240812038@24.08.12 (190400-608507424):64)
	at aunn.b(:com.google.android.gms@240812038@24.08.12 (190400-608507424):105)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.a(:com.google.android.gms@240812038@24.08.12 (190400-608507424):113)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@240812038@24.08.12 (190400-608507424):18)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	... 12 more
```

**Comment by muhomorr** [comment]
Duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3114
