### ISSUE TITLE
Using the TV notification crashes Google Play services 

### ISSUE THREAD

**Issue by imapancake22** [GrapheneOS/os-issue-tracker#3402]
I don't know too much about tvs and coding but I figured this might be helpful

```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240405.002/2024040300:user/release-keys
package: com.google.android.gms:241017038
process: com.google.android.gms.persistent
processUptime: 57404683 + 364 ms
installer: com.android.vending
GmsCompatConfig version: 101

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.cast.rcn.VIRTUAL_REMOTE flg=0x10000010 (has extras) } in com.google.android.gms.cast.rcn.RemoteControlNotificationMediaIntentReceiver@7704112
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1818)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.google.android.gms (pid=2952, uid=10141) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5878)
	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1231)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:505)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:505)
	at com.google.android.chimera.ModuleContext.sendBroadcast(:com.google.android.gms@241017038@24.10.17 (190400-617915183):3)
	at azfp.sendBroadcast(:com.google.android.gms@241017038@24.10.17 (190400-617915183):3)
	at com.google.android.gms.cast.rcn.RemoteControlNotificationMediaIntentReceiver.a(:com.google.android.gms@241017038@24.10.17 (190400-617915183):362)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@241017038@24.10.17 (190400-617915183):18)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1810)
	... 12 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:3224)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:6018)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:15381)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14868)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15844)
```

**Comment by allmazz** [comment]
Still actual.
To reproduce: enable Cast notifications in Google settings, play something on TV, expand the notification and press on remote icon.
```
type: crash
osVersion: google/shiba/shiba:16/BP2A.250805.005/2025110801:user/release-keys
package: com.google.android.gms:254031035, targetSdk 36
process: com.google.android.gms.persistent
processUptime: 56614296 + 732 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 165

java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.cast.rcn.VIRTUAL_REMOTE flg=0x10000010 xflg=0x4 pkg=com.google.android.gms (has extras) } in com.google.android.gms.cast.rcn.RemoteControlNotificationMediaIntentReceiver@471d657
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1852)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9111)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Caused by: java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.google.android.gms (pid=10407, uid=10178) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3348)
	at android.os.Parcel.createException(Parcel.java:3332)
	at android.os.Parcel.readException(Parcel.java:3308)
	at android.os.Parcel.readException(Parcel.java:3250)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:6292)
	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1418)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:547)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:547)
	at btbb.sendBroadcast(:com.google.android.gms@254031035@25.40.31 (260400-816341114):4)
	at com.google.android.gms.cast.rcn.RemoteControlNotificationMediaIntentReceiver.kz(:com.google.android.gms@254031035@25.40.31 (260400-816341114):252)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@254031035@25.40.31 (260400-816341114):17)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1844)
	... 12 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:3330)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:6239)
	at com.android.server.am.BroadcastController.broadcastIntentLockedTraced(BroadcastController.java:1392)
	at com.android.server.am.BroadcastController.broadcastIntentLocked(BroadcastController.java:807)
	at com.android.server.am.BroadcastController.broadcastIntentWithFeature(BroadcastController.java:740)
```
