### ISSUE TITLE
Android auto random crash

### ISSUE THREAD

**Issue by jriberg** [GrapheneOS/os-issue-tracker#3414]
Unsure what caused it, but it happened a couple of times over my 1h trip.
Nissan leaf 2018 if it matters
```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240405.002/2024040300:user/release-keys
package: com.google.android.projection.gearhead:114640814
process: com.google.android.projection.gearhead:projection
processUptime: 1017 + 330 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 101

android.os.BadParcelableException: Failure retrieving array; only received 1 of 45
	at android.content.pm.BaseParceledListSlice.<init>(BaseParceledListSlice.java:104)
	at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:42)
	at android.content.pm.ParceledListSlice.<init>(Unknown Source:0)
	at android.content.pm.ParceledListSlice$1.createFromParcel(ParceledListSlice.java:80)
	at android.content.pm.ParceledListSlice$1.createFromParcel(ParceledListSlice.java:78)
	at android.os.Parcel.readTypedObject(Parcel.java:4178)
	at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:4425)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:1057)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:1034)
	at jwc.f(SourceFile:2)
	at jwk.a(SourceFile:3)
	at jwm.a(SourceFile:1)
	at nyb.onListenerConnected(SourceFile:13)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2417)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffer space
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at android.content.pm.BaseParceledListSlice.<init>(BaseParceledListSlice.java:95)
	... 22 more
```

**Comment by everonline** [comment]
Same here:

[```
type: crash
osVersion: google/panther/panther:14/AP1A.240405.002/2024040300:user/release-keys
package: com.google.android.projection.gearhead:114640814
process: com.google.android.projection.gearhead:projection
processUptime: 23927 + 314 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 102

java.lang.IllegalArgumentException: No matching component for intent: Intent { cmp=com.google.android.projection.gearhead/com.google.android.apps.auto.components.preflight.PreflightCarActivityService (has extras) }
	at oqe.a(SourceFile:6)
	at ovc.g(SourceFile:1)
	at oqo.x(SourceFile:9)
	at ogo.G(SourceFile:1)
	at kbo.a(SourceFile:9)
	at igq.a(SourceFile:30)
	at ieu.n(SourceFile:1)
	at ieu.f(SourceFile:1)
	at kbq.d(SourceFile:75)
	at com.google.android.projection.gearhead.system.GhLifecycleService.h(SourceFile:12)
	at oor.handleMessage(SourceFile:22)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```
](url)
