### ISSUE TITLE
System Server crash mostly after charging overnight

### ISSUE THREAD

**Issue by T2brozz** [GrapheneOS/os-issue-tracker#3423]
Phone: Pixel 7A
Version: lynx-14.4-11458464

After charging it overnight, so for a long time, where it sits at 100%, it crashes in the morning when I start using it.
Sometimes just random, while using Spotify or watching YouTube.

Just before it is crashing, user Input is delayed. Touch input ~ couple seconds later and all Input is applied at once. Hardware Buttons are also delayed.  The phone also starts getting warm 

I hope someone can help me solve this because it bothers me to restart my phone randomly.

I currently do not have all the logs, just one. Furthermore, I will post any new logs I get 
 Current Log:
```type: crash
SystemUptimeMs: 105006618
Process: system_server
Build: google/lynx/lynx:14/AP1A.240305.019.A1/2024032100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 687216 free bytes and 671KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at libcore.io.IoUtils$FileReader.<init>(IoUtils.java:398)
	at libcore.io.IoUtils.readFileAsString(IoUtils.java:291)
	at com.android.server.ResourcePressureUtil.readResourcePsiState(ResourcePressureUtil.java:48)
	at com.android.server.ResourcePressureUtil.$r8$lambda$YqRwUJ2GaBiqQtdp5zJtNgfVUt0(ResourcePressureUtil.java:0)
	at com.android.server.ResourcePressureUtil$$ExternalSyntheticLambda0.apply(R8$$SyntheticClass:0)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:209)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:503)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:132)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:619)
	at com.android.server.ResourcePressureUtil.currentPsiState(ResourcePressureUtil.java:67)
	at com.android.server.am.ProcessErrorStateRecord.appNotResponding(ProcessErrorStateRecord.java:462)
	at com.android.server.am.AnrHelper$AnrRecord.appNotResponding(AnrHelper.java:302)
	at com.android.server.am.AnrHelper$AnrConsumerThread.run(AnrHelper.java:235)```

**Comment by T2brozz** [comment]
Here is also another log from a crash. It happend while watching a youtube with mobile internet.
```
type: ANR
osVersion: google/lynx/lynx:14/AP1A.240405.002/2024040900:user/release-keys
package: android:34
process: system

activity: null
cause: ANR Input dispatching timed out (PointerEventDispatcher0 (server) is not responding. Waited 5002ms for MotionEvent).
info: ANR in system
PID: 1304
Reason: Input dispatching timed out (PointerEventDispatcher0 (server) is not responding. Waited 5002ms for MotionEvent).
ErrorId: eb2bff59-82d9-46f8-b13d-230836a32f04
Frozen: false
Load: 4.17 / 5.57 / 5.03
----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.00 avg300=0.00 total=31746233
full avg10=0.00 avg60=0.00 avg300=0.00 total=15228047
----- End output from /proc/pressure/memory -----
----- Output from /proc/pressure/cpu -----
some avg10=3.30 avg60=12.86 avg300=19.52 total=1617810325
----- End output from /proc/pressure/cpu -----
----- Output from /proc/pressure/io -----
some avg10=0.00 avg60=0.00 avg300=0.00 total=54087498
full avg10=0.00 avg60=0.00 avg300=0.00 total=36942517
----- End output from /proc/pressure/io -----

CPU usage from 5ms to 5340ms later (2024-04-15 15:57:22.307 to 2024-04-15 15:57:27.643) with 99% awake:
  141% 1304/system_server: 111% user + 30% kernel / faults: 33468 minor 5493 major
  32% 14007/app.revanced.android.youtube: 21% user + 11% kernel / faults: 58709 minor 957 major
  28% 4732/org.thosp.yourlocalweather: 18% user + 9.9% kernel / faults: 16829 minor 4864 major
  24% 2072/com.android.systemui: 19% user + 5.2% kernel / faults: 18625 minor 1207 major
  22% 14551/com.android.launcher3: 17% user + 5.2% kernel / faults: 7696 minor 1903 major
  8% 540/surfaceflinger: 4.8% user + 3.1% kernel / faults: 1653 minor 10 major
  0% 1058/media.swcodec: 0% user + 0% kernel / faults: 8626 minor 137 major
  4.6% 3877/com.google.android.inputmethod.latin: 2.2% user + 2.4% kernel / faults: 10738 minor 1315 major
  3.9% 520/android.system.suspend-service: 0.5% user + 3.3% kernel
  3.5% 24494/app.vanadium.browser: 1.4% user + 2% kernel / faults: 5930 minor 99 major
45% TOTAL: 27% user + 16% kernel + 0.4% iowait + 0.8% irq + 0.4% softirq
CPU usage from 175ms to 635ms later (2024-04-15 15:57:22.478 to 2024-04-15 15:57:22.937):
  148% 1304/system_server: 115% user + 33% kernel / faults: 832 minor
    41% 1704/android.ui: 41% user + 0% kernel
    38% 24532/AnrAuxiliaryTas: 12% user + 25% kernel
    25% 8674/binder:1304_15: 25% user + 0% kernel
    20% 8607/binder:1304_13: 17% user + 2.5% kernel
    5.1% 6875/binder:1304_12: 2.5% user + 2.5% kernel
    2.5% 1707/android.anim: 0% user + 2.5% kernel
    2.5% 1972/tworkPolicy.uid: 2.5% user + 0% kernel
    2.5% 3640/binder:1304_E: 2.5% user + 0% kernel
    2.5% 24511/AnrConsumer: 0% user + 2.5% kernel
  48% 2072/com.android.systemui: 45% user + 2.6% kernel / faults: 582 minor
    34% 2271/SysUiBg: 34% user + 0% kernel
    5.3% 2251/RenderThread: 5.3% user + 0% kernel
    2.6% 2072/ndroid.systemui: 2.6% user + 0% kernel
    2.6% 2422/pool-3-thread-1: 2.6% user + 0% kernel
    2.6% 2517/mali-event-hand: 0% user + 2.6% kernel
    2.6% 3609/binder:2072_9: 2.6% user + 0% kernel
  51% 14007/app.revanced.android.youtube: 48% user + 3% kernel / faults: 620 minor
    18% 22806/RenderThread: 18% user + 0% kernel
    9.1% 14087/ChromiumNet: 9.1% user + 0% kernel
    6.1% 14007/android.youtube: 6.1% user + 0% kernel
    3% 16264/binder:14007_E: 3% user + 0% kernel
    3% 22867/glide-source-th: 3% user + 0% kernel
    3% 22869/ComponentLayout: 3% user + 0% kernel
  33% 14551/com.android.launcher3: 27% user + 6% kernel / faults: 98 minor 62 major
    21% 14585/RenderThread: 18% user + 3% kernel
    6% 14551/droid.launcher3: 6% user + 0% kernel
    6% 15959/mali-event-hand: 3% user + 3% kernel
    3% 21745/binder:14551_E: 3% user + 0% kernel
  23% 540/surfaceflinger: 13% user + 9.3% kernel / faults: 2 minor
    9.3% 540/surfaceflinger: 6.9% user + 2.3% kernel
    4.6% 587/RenderEngine: 2.3% user + 2.3% kernel
    2.3% 763/mali-event-hand: 2.3% user + 0% kernel
    2.3% 765/mali-cpu-comman: 0% user + 2.3% kernel
    2.3% 783/TimerDispatch: 0% user + 2.3% kernel
    2.3% 787/app: 0% user + 2.3% kernel
    2.3% 800/surfaceflinger: 0% user + 2.3% kernel
  28% 3683/com.android.nfc: 11% user + 17% kernel / faults: 1924 minor 2985 major
    28% 3845/Signal Catcher: 11% user + 17% kernel
  21% 2312/com.android.phone: 13% user + 8.2% kernel / faults: 1433 minor 1191 major
    19% 2601/Signal Catcher: 13% user + 5.4% kernel
    2.7% 2680/binder:2312_6: 2.7% user + 0% kernel
    2.7% 2682/SMSVC: 2.7% user + 0% kernel
  17% 3877/com.google.android.inputmethod.latin: 8.7% user + 8.7% kernel / faults: 1998 minor 872 major
    14% 3965/Signal Catcher: 8.7% user + 5.8% kernel
  10% 2218/com.samsung.slsi.telephony.oem.oemrilhookservice: 8% user + 2.6% kernel / faults: 1916 minor 1228 major
    8% 2553/Signal Catcher: 5.3% user + 2.6% kernel
  7% 542/android.hardware.composer.hwc3-service.pixel: 2.3% user + 4.6% kernel
    4.6% 796/binder:542_6: 0% user + 4.6% kernel
  5.8% 4732/org.thosp.yourlocalweather: 5.8% user + 0% kernel / faults: 183 minor 64 major
    2.9% 4836/pool-1-thread-1: 2.9% user + 0% kernel
  2.2% 57/rcuop/5: 0% user + 2.2% kernel
  2.2% 231/decon0_kthread: 0% user + 2.2% kernel
  2.3% 472/servicemanager: 2.3% user + 0% kernel / faults: 2 minor 2 major
  2.3% 602/tombstoned: 0% user + 2.3% kernel / faults: 20 minor 12 major
  3.4% 22491/kworker/u16:0-gpu-dvfs-control: 0% user + 3.4% kernel
  3.5% 22811/csf_sync_update: 0% user + 3.5% kernel
  3.5% 24494/app.vanadium.browser: 0% user + 3.5% kernel / faults: 118 minor 1 major
    3.5% 24494/anadium.browser: 0% user + 3.5% kernel
   +0% 24546/fonts-androidx: 0% user + 0% kernel
 +0% 24538/kworker/7:1H-fsverity_read_queue: 0% user + 0% kernel
 +0% 24539/kworker/7:3H: 0% user + 0% kernel
63% TOTAL: 42% user + 18% kernel + 0.5% iowait + 1.3% irq + 0.5% softirq
```
