### ISSUE TITLE
Bug always show time pixel freezing and false battery info

### ISSUE THREAD

**Issue by kullanici32** [GrapheneOS/os-issue-tracker#3428]
Hello, I installed this version (flame-factory-2024040100) yesterday with a clean installation.

And if I turn on the always show time option, it freezes as in the video. I tried it on the main profile, I tried creating a second profile and it freezes in the same way, it is not related to the full screen information in the video, I pressed OK on that warning in the first profile and it freezes there in the same way. And if I repeat this too many times, it goes into recovery mode, and the message "Your data may be corrupted" appears. It says "Reset factory data and try again" and I open the Android system again by selecting "Try again". How can we solve this problem?

https://github.com/GrapheneOS/os-issue-tracker/assets/109388218/ce25d2d7-1653-4e6d-b2d1-67e84e77e4a4

![WhatsApp Image 2024-04-11 at 14 04 56](https://github.com/GrapheneOS/os-issue-tracker/assets/109388218/4fab088f-db50-4bba-9ddf-8d5f15fc6964)

**Comment by kullanici32** [comment]
Is there any roadmap for the future? I know the developers are very busy and this is an old device, but I still use it daily and don't want to switch to another rom.

**Comment by kullanici32** [comment]
@thestinger I request you to open this comment as an issue again.

**Comment by kullanici32** [comment]
@thestinger Ok I understand, you don't want to try to fix it even if it is a bug that affects the usage because it is old,
I understand you because there are not many people using P4 and its security is old.

I want to switch to the updated device, but it is not officially sold in my country and the cost of unlocking the IMEI to use the phone I bought abroad as a "phone" in my country is more than 1000 dollars.
Now even if I explain this problem in more detail, it will not be solved.

Finally, I was not aware of the attack on you, I will not make such a promotion again, but know that the always showtime feature always works perfectly in the original OS

Maybe if it is officially sold in the future, see you on new devices, thank you for your work..

**Comment by kullanici32** [comment]
@thestinger I don't want to waste your time, but it's strange to hear that you don't understand the problem I'm talking about. Let me explain for the last time: you can look at the video in my first post to understand the problem (don't pay attention to the picture), the summary of the problem is if when I turn on the always show time feature and press the power button when the time is shown, the screen freezes and the screen turns on but it turns off immediately, I cannot turn on and use the phone with the power button in any way ( It is clearly shown in the video) else If I try to open it by touching the screen, it opens normally. and this problem only appears in grapheneOS versions. I didn't want to bother you unnecessarily, but since you said you didn't understand the problem, I wanted to explain again.

quote:
> 
>  VID-20240411-WA0003.mp4

**Comment by kullanici32** [comment]
@thestinger Thank you very much for your efforts. After all, it is still much more secure than many devices on the market, and it would be great to use a problem-free version for those like me who do not have access to the latest model.

I'm looking forward to the next update...

**Comment by kullanici32** [comment]
@thestinger 
I was looking forward to the next version, and I downloaded flame-ota_update-2024080800.zip, turned on the always-on display feature, turned off the display, and pressed the power button, and the same problem still persists. I wonder if the fix has been applied in this new version? Can you check? thank you very much


` E AndroidRuntime: FATAL EXCEPTION: main
08-09 13:11:02.300  6483  6483 E AndroidRuntime: Process: com.android.systemui, PID: 6483
08-09 13:11:02.300  6483  6483 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isPowerbuttonFps()' on a null object reference
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.wm.shell.TaskView$$ExternalSyntheticLambda5.run(R8$$SyntheticClass:166)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.systemui.shade.NotificationShadeWindowControllerImpl.batchApplyWindowLayoutParams(NotificationShadeWindowControllerImpl.java:6)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.CentralSurfacesImpl$12.onStartedWakingUp(CentralSurfacesImpl.java:15)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.systemui.keyguard.WakefulnessLifecycle$$ExternalSyntheticLambda4.accept(Unknown Source:8)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.systemui.keyguard.Lifecycle.dispatch(Lifecycle.java:15)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.systemui.keyguard.KeyguardLifecyclesDispatcher$1.handleMessage(KeyguardLifecyclesDispatcher.java:259)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7940)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-09 13:11:02.300  6483  6483 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
08-09 13:11:02.344  1565  1565 E NearbyManager: Cannot stop scan with this callback because it is never registered.
08-09 13:11:02.382  1565  5842 E LockoutResetTracker: Callback binder died: android.os.BinderProxy@8646f71
08-09 13:11:02.382  1565  5842 E LockoutResetTracker: Removing dead callback for: com.android.systemui
08-09 13:11:02.383  1565  1593 E BiometricService: Enabled callback binder died
08-09 13:11:02.384  1565  4806 E BiometricService: Enabled callback binder died
`

**Comment by kullanici32** [comment]
@thestinger I'm sorry about this situation. I know it's in the old supported version and I know that you focus more on current devices. Can you make us one last gesture and solve this problem before the device is completely disconnected from support? I can help you with testing etc. I don't want to bother you too much but your help to those who still use Pixel 4 will be greatly appreciated :)
