### ISSUE TITLE
system_server: crash when tapping on keyboard

### ISSUE THREAD

**Issue by xandris** [GrapheneOS/os-issue-tracker#3434]
```
type: crash
SystemUptimeMs: 162984799
Process: system_server
Build: google/redfin/redfin:14/UP1A.231105.001.B2/2024040900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.autofill.ui.FillUi$AnchoredWindow.show(android.view.WindowManager$LayoutParams)' on a null object reference
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.lambda$show$0(FillUi.java:685)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.$r8$lambda$rayRxR7zWVCJ_EZ9KlZ9jO79cqM(FillUi.java:0)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)
```

**Comment by lbschenkel** [comment]
Same with me. I was going to report it but found this one. Same stack trace.

**Comment by xandris** [comment]
@thestinger I think it was Vanadium and I have KeePassDX for password filling
