### ISSUE TITLE
Unable to access car while driving with Android Auto opened

### ISSUE THREAD

**Issue by jslyonnais** [GrapheneOS/os-issue-tracker#3435]
Happen so many times. Android Auto crash randomly. Sometimes while I drive with GPS (I use Waze, but happened with Maps) or if I listen to music.

Cannot find something relevant but maybe it could help understand the situation.

```
type: crash
osVersion: google/panther/panther:14/AP1A.240405.002/2024040900:user/release-keys
package: com.google.android.projection.gearhead:114640814
process: com.google.android.projection.gearhead:projection
processUptime: 3176817 + 519 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 102

igk: Unable to access car
	at ieu.n(SourceFile:8)
	at ieu.e(SourceFile:1)
	at iuo.dF(SourceFile:2)
	at jef.b(SourceFile:5)
	at trj.c(SourceFile:17)
	at jeg.k(SourceFile:4)
	at jed.a(SourceFile:4)
	at igh.v(SourceFile:16)
	at ilr.a(SourceFile:116)
	at ohw.f(SourceFile:4)
	at ohk.run(SourceFile:11)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: owa: java.lang.IllegalStateException: OutOfCarLifecycle
	at ogo.cu(SourceFile:8)
	at ogo.ct(SourceFile:1)
	at ovc.h(SourceFile:4)
	at ovc.b(SourceFile:2)
	at oqo.u(SourceFile:1)
	at ogo.y(SourceFile:1)
	at nth.g(SourceFile:1)
	at iue.a(SourceFile:104)
	at igq.a(SourceFile:29)
	at ieu.n(SourceFile:1)
	... 20 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3199)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at gml.ee(SourceFile:3)
	at oja.A(SourceFile:2)
	at oqb.a(SourceFile:10)
	at ouy.a(SourceFile:2)
	at opy.call(SourceFile:11)
	at ovc.b(SourceFile:1)
	... 26 more
```

**Comment by jslyonnais** [comment]
> @jslyonnais You should replace the USB cable and make sure both ports are clean. This is usually caused by a bad USB connection. It's not a GrapheneOS issue.

Done this a few times. Wonder if it's the car the problem to be honest...!
