### ISSUE TITLE
Google play service crash

### ISSUE THREAD

**Issue by anakins-arm** [GrapheneOS/os-issue-tracker#3439]
```
type: crash
osVersion: google/oriole/oriole:14/AP1A.240405.002/2024040900:user/release-keys
package: com.google.android.gms:241017038
process: com.google.android.gms.ui
processUptime: 56485 + 229 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 103

java.lang.IllegalStateException: Must not be called on the main application thread
	at alac.k(:com.google.android.gms@241017038@24.10.17 (190400-617915183):10)
	at alac.j(:com.google.android.gms@241017038@24.10.17 (190400-617915183):3)
	at aukn.c(:com.google.android.gms@241017038@24.10.17 (190400-617915183):1)
	at avif.e(:com.google.android.gms@241017038@24.10.17 (190400-617915183):16)
	at aukn.h(:com.google.android.gms@241017038@24.10.17 (190400-617915183):83)
	at aukn.f(:com.google.android.gms@241017038@24.10.17 (190400-617915183):32)
	at auwb.gr(:com.google.android.gms@241017038@24.10.17 (190400-617915183):59)
	at iik.kO(:com.google.android.gms@241017038@24.10.17 (190400-617915183):29)
	at iik.f(:com.google.android.gms@241017038@24.10.17 (190400-617915183):42)
	at iik.l(:com.google.android.gms@241017038@24.10.17 (190400-617915183):15)
	at iig.run(:com.google.android.gms@241017038@24.10.17 (190400-617915183):19)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by muhomorr** [comment]
How to reproduce it?
