### ISSUE TITLE
markup app no access to content + conflict

### ISSUE THREAD

**Issue by io43** [GrapheneOS/os-issue-tracker#3448]
If you set the Markup app as default app for the Screenshot feature, it also set it as editor for all png files and it causes a problem when trying to edit a png from another app because Markup do not and can't not have enough permissions to read the files or something like that. 

it is possible to set it as default editor only for the screenshot feature? not all PNG images

```
type: crash
osVersion: google/shiba/shiba:14/AP1A.240405.002/2024040300:user/release-keys
package: com.google.android.markup:184
process: com.google.android.markup
processUptime: 132 + 181 ms
installer: app.grapheneos.apps

java.lang.SecurityException: com.google.android.markup has no access to content://media/external/images/media/1000000498
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:202)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:165)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2068)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1883)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1553)
	at aql.b(PG:8)
	at u.run(PG:13)
	at java.lang.Thread.run(Thread.java:1012)
```

https://github.com/GrapheneOS/os-issue-tracker/assets/125970146/1652e19c-da9d-4b18-abb4-10fc95c2dd37

**Comment by muhomorr** [comment]
Which Gallery app is shown in the screen recording? It's supposed to be granting read access to file that it asks to edit.

**Comment by io43** [comment]
oh that's a issue from gallery app? i can be closed so.

It is Simple Gallery with Pro editor 6.28.1 (gallery-396-proprietary-release from [github](https://github.com/SimpleMobileTools/Simple-Gallery/releases))

I known it is not longer updated and have been sold but the forked version do not include the Pro editor which can edit and trim videos.
