### ISSUE TITLE
system-server: crash when running YT Revanced video and opening Discord

### ISSUE THREAD

**Issue by NoobKozlegeny** [GrapheneOS/os-issue-tracker#3449]
Steps to reproduce (if it's even possible):
0. Be deep underground in a metro system, where getting access to decent internet is more challenging
1. Have YT Revanced and official Discord downloaded
2. Discord is already open in storage
3. Open this video from Discord (https://youtu.be/2ld5gQ88J-I?si=6BQ05vWhdE8Ip3hZ)
4. It redirects to YT and stop it
5. Open Discord from storage

Log:
```
type: crash
SystemUptimeMs: 48398911
Process: system_server
Build: google/oriole/oriole:14/AP1A.240405.002/2024040300:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Lost network stack. This is not the root cause of any issue, it is a side effect of a crash that happened earlier. Earlier logs should point to the actual issue.
	at android.net.ConnectivityModuleConnector.maybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:335)
	at android.net.ConnectivityModuleConnector.-$$Nest$mmaybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:0)
	at android.net.ConnectivityModuleConnector$ModuleServiceConnection.onServiceDisconnected(ConnectivityModuleConnector.java:278)
	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2226)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2241)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:1001)
	at com.android.server.SystemServer.main(SystemServer.java:685)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
```

**Comment by NoobKozlegeny** [comment]
Yes, there was a soft reboot afterwards. Sorry I've forgot to mention that. Is there any more info I could provide?
