### ISSUE TITLE
Random crash of system_server

### ISSUE THREAD

**Issue by jriberg** [GrapheneOS/os-issue-tracker#3454]
Opened an app to pay for parking. When it loaded maps and reached GPS, system rebooted with grapheneos logo

```
type: crash
SystemUptimeMs: 217267834
Process: system_server
Build: google/cheetah/cheetah:14/AP1A.240405.002/2024040900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Lost network stack. This is not the root cause of any issue, it is a side effect of a crash that happened earlier. Earlier logs should point to the actual issue.
	at android.net.ConnectivityModuleConnector.maybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:335)
	at android.net.ConnectivityModuleConnector.-$$Nest$mmaybeCrashWithTerribleFailure(ConnectivityModuleConnector.java:0)
	at android.net.ConnectivityModuleConnector$ModuleServiceConnection.onServiceDisconnected(ConnectivityModuleConnector.java:278)
	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2226)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2241)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:1001)
	at com.android.server.SystemServer.main(SystemServer.java:685)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
```

**Comment by ANDROID2468** [comment]
I had a similar issue. I was trying to use keepassDx   and it crash the system-server

````
type: crash
SystemUptimeMs: 3690758
Process: system_server
Build: google/shiba/shiba:14/AP1A.240405.002.B1/2024042200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.autofill.ui.FillUi$AnchoredWindow.show(android.view.WindowManager$LayoutParams)' on a null object reference
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.lambda$show$0(FillUi.java:685)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.$r8$lambda$rayRxR7zWVCJ_EZ9KlZ9jO79cqM(FillUi.java:0)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)
```
`
