### ISSUE TITLE
google play dervices and other google apps crashing after update (Version 2024042100)

### ISSUE THREAD

**Issue by magelpen** [GrapheneOS/os-issue-tracker#3461]
After updating to the new stable version 2024042100, Google Play Services crashes frequently. Additionally, Google Keep, Gboard, and other Google apps are also crashing.

```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240405.002.B1/2024042100:user/release-keys
package: com.google.android.gms:241517038
process: com.google.android.gms.persistent
processUptime: 384 + 307 ms
installer: com.android.vending
GmsCompatConfig version: 104

java.lang.SecurityException: Permission Denial: getPackageProcessState from pid=22553, uid=10129 requires android.permission.PACKAGE_USAGE_STATS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at android.app.IActivityManager$Stub$Proxy.getPackageProcessState(IActivityManager.java:8899)
	at android.app.ActivityManager.getPackageImportance(ActivityManager.java:4275)
	at com.google.android.gms.common.util.AppImportanceHelperV26.f(:com.google.android.gms@241517038@24.15.17 (190400-626366329):18)
	at ecje.m(:com.google.android.gms@241517038@24.15.17 (190400-626366329):13)
	at com.google.android.location.internal.server.GoogleLocationChimeraService.a(:com.google.android.gms@241517038@24.15.17 (190400-626366329):172)
	at echf.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):7)
	at amhb.c(:com.google.android.gms@241517038@24.15.17 (190400-626366329):50)
	at amhb.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ammr.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: eiaf: 
		at tk_trace.location_base-GoogleLocationChimeraService_onStartCommand(Unknown Source:0)
		at tk_trace.location_base-GoogleLocationChimeraService_onStartCommand(Unknown Source:0)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforceCallingPermission(ActivityManagerService.java:6167)
	at com.android.server.am.ActivityManagerService.getPackageProcessState(ActivityManagerService.java:3208)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4694)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2802)
	at android.os.Binder.execTransactInternal(Binder.java:1530)
```

**Comment by magelpen** [comment]
Cool, thanks.

**Comment by magelpen** [comment]
I updated GmsCompatConfig to alpha channel (version 105) and  closed rerouter location. But google apps crash immediately.
```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240405.002.B1/2024042100:user/release-keys
package: com.google.android.gms:241517038
process: com.google.android.gms.persistent
processUptime: 2885 + 544 ms
installer: com.android.vending
GmsCompatConfig version: 105

java.lang.SecurityException: Permission Denial: getPackageProcessState from pid=23337, uid=10129 requires android.permission.PACKAGE_USAGE_STATS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at android.app.IActivityManager$Stub$Proxy.getPackageProcessState(IActivityManager.java:8899)
	at android.app.ActivityManager.getPackageImportance(ActivityManager.java:4275)
	at com.google.android.gms.common.util.AppImportanceHelperV26.f(:com.google.android.gms@241517038@24.15.17 (190400-626366329):18)
	at ecje.m(:com.google.android.gms@241517038@24.15.17 (190400-626366329):13)
	at com.google.android.location.internal.server.GoogleLocationChimeraService.a(:com.google.android.gms@241517038@24.15.17 (190400-626366329):172)
	at echf.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):7)
	at amhb.c(:com.google.android.gms@241517038@24.15.17 (190400-626366329):50)
	at amhb.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ammr.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: eiaf: 
		at tk_trace.location_base-GoogleLocationChimeraService_onStartCommand(Unknown Source:0)
		at tk_trace.location_base-GoogleLocationChimeraService_onStartCommand(Unknown Source:0)
```

**Comment by magelpen** [comment]
@thestinger Wow, I've been testing it for 10 minutes and it's working fine. Thank you so much!
