### ISSUE TITLE
Google crash

### ISSUE THREAD

**Issue by AngelMarca** [GrapheneOS/os-issue-tracker#3467]
```
type: crash
osVersion: Redmi/begonia/begonia:11/RP1A.200720.011/V12.5.8.0.RGGMIXM:user/release-keys
package: com.google.android.googlequicksearchbox:301333629
process: com.google.android.googlequicksearchbox:search
processUptime: 607223 + 60 ms
installer: com.google.android.googlequicksearchbox
GmsCompatConfig version: 106

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.googlequicksearchbox/com.google.android.apps.search.googleapp.accounts.ui.myaccount.MyAccountActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.android.gms.accountsettings.action.VIEW_SETTINGS pkg=com.google.android.gms (has extras) }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3833)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3974)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8275)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.android.gms.accountsettings.action.VIEW_SETTINGS pkg=com.google.android.gms (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2260)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1894)
	at android.app.Activity.startActivityForResult(Activity.java:5682)
	at androidx.activity.v.startActivityForResult(PG:4)
	at com.google.android.libraries.av.c.a.a.startActivityForResult(PG:5)
	at androidx.activity.result.j.f(PG:159)
	at androidx.activity.result.h.b(PG:32)
	at com.google.android.apps.search.googleapp.accounts.ui.myaccount.MyAccountActivity.onCreate(PG:91)
	at android.app.Activity.performCreate(Activity.java:8701)
	at android.app.Activity.performCreate(Activity.java:8679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1471)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	... 12 more
```

**Comment by flawedworld** [comment]
We don't support your device.

**Comment by AngelMarca** [comment]
My apologizes, I'm on Voltage OS, when the app crashed the report system send me to your github profile, then I posted the log info.
I'm sorry for the mistakes

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
