### ISSUE TITLE
system crash

### ISSUE THREAD

**Issue by jogurcik13** [GrapheneOS/os-issue-tracker#3473]
```
type: crash
osVersion: google/raven/raven:14/AP1A.240405.002/2024042100:user/release-keys
uid: 1000 (u:r:system_server:s0)
cmdline: system_server
processUptime: 37323s

signal: 11 (SIGSEGV), code 2 (SEGV_ACCERR), faultAddr b400d9bab4b83000
threadName: android.ui

backtrace:
    /system/lib64/libhwui.so (SkRegion::contains(int, int) const+92, pc 4bd26c)
    /system/lib64/libhwui.so (android::Region_contains(_JNIEnv*, _jobject*, int, int) (.__uniq.223021506454627850717093723162255380028)+48, pc 4bd1f0)
    /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116, pc 1f2e84)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.TaskTapPointerEventListener.onPointerEvent+516, pc 5e93b4)
    /system/framework/oat/arm64/services.odex (com.android.server.wm.PointerEventDispatcher.onInputEvent+368, pc 5d5ea0)
    /system/framework/arm64/boot-framework.oat (android.view.InputEventReceiver.dispatchInputEvent+112, pc 690f20)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 3e1d74)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+836, pc 3e0714)
    /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+188, pc 69c4fc)
    /system/lib64/libandroid_runtime.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+120, pc d6438)
    /system/lib64/libandroid_runtime.so (android::NativeInputEventReceiver::consumeEvents(_JNIEnv*, bool, long, bool*)+296, pc 148ba8)
    /system/lib64/libandroid_runtime.so (android::nativeConsumeBatchedInputEvents(_JNIEnv*, _jclass*, long, long)+96, pc 14a200)
    /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116, pc 1f3414)
    /system/framework/arm64/boot-framework.oat (android.view.InputEventReceiver.onBatchedInputEventPending+112, pc 6915b0)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 3e1d74)
    /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+836, pc 3e0714)
    /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+188, pc 69c4fc)
    /system/lib64/libandroid_runtime.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+120, pc d6438)
    /system/lib64/libandroid_runtime.so (android::NativeInputEventReceiver::consumeEvents(_JNIEnv*, bool, long, bool*)+856, pc 148dd8)
    /system/lib64/libandroid_runtime.so (android::NativeInputEventReceiver::handleEvent(int, int, void*)+164, pc 1489b4)
    /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+856, pc f648)
    /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44, pc 17de9c)
    /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116, pc 1eef34)
    /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+280, pc 53b1f8)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+88, pc 538c68)
    /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+244, pc 538b94)
    /system/framework/arm64/boot-framework.oat (android.os.HandlerThread.run+548, pc 537f44)
    /system/framework/oat/arm64/services.odex (com.android.server.UiThread.run+164, pc 79ec14)
    /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612, pc 3e1d74)
    /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+220, pc 3c60ec)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1656, pc 4d2cb8)
    /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8, pc 4d2628)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc cf93c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64, pc 66730)
```

**Comment by MKBontwikkeling** [comment]
Seem to have the same issue. My GOS installation bootloops and crashes about 30 seconds into the boot sequence.

**Comment by nickcipriani** [comment]
I believe I experienced the same issue:
```
type: crash
SystemUptimeMs: 112842200
Process: system_server
Build: google/husky/husky:14/AP1A.240505.005/2024053100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3860)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1812)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1663)
	at com.android.server.am.UserController.startUser(UserController.java:1617)
	at com.android.server.am.UserController.startUser(UserController.java:1576)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1921)
	at com.android.server.am.UserController.handleMessage(UserController.java:3220)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
