### ISSUE TITLE
Android Auto Crash

### ISSUE THREAD

**Issue by tuxpizza** [GrapheneOS/os-issue-tracker#3485]
Running into an Android Auto crash with Play Services 24.16.15, Services Framework 14, Play store 40.6.31-31, and Android Auto 11.6.641234

Pixel 8 Pro Husky, GrapheneOS 2024042200

This crash occurs when I tap on an application to launch it on my car's infotainment inside Android auto.

```
type: crash
osVersion: google/husky/husky:14/AP1A.240405.002.B1/2024042200:user/release-keys
package: com.google.android.projection.gearhead:116641234
process: com.google.android.projection.gearhead:projection
processUptime: 1473596 + 328 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 108

java.lang.IllegalArgumentException: No matching component for intent: Intent { cmp=com.google.android.projection.gearhead/.media.MediaService (has extras) }
	at otx.a(SourceFile:54)
	at oyq.g(SourceFile:1)
	at ouh.x(SourceFile:92)
	at oko.aR(SourceFile:5)
	at knl.a(SourceFile:224)
	at iiv.a(SourceFile:248)
	at iif.k(SourceFile:1)
	at iif.b(SourceFile:13)
	at knm.i(SourceFile:201)
	at knm.h(SourceFile:5)
	at lmt.onClick(SourceFile:30)
	at android.view.View.performClick(View.java:7729)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30484)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by McClunatic** [comment]
Perhaps similar:

```
type: crash
osVersion: google/bluejay/bluejay:14/AP2A.240605.024/2024062000:user/release-keys
package: com.google.android.projection.gearhead:120642034
process: com.google.android.projection.gearhead:projection
processUptime: 62573 + 517 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 120

ips: Unable to get CarInfo
	at ioc.j(SourceFile:56)
	at ioc.d(SourceFile:8)
	at iqb.a(SourceFile:22)
	at mhb.invoke(SourceFile:28)
	at abxe.a(SourceFile:23)
	at mgm.invoke(SourceFile:68)
	at abxe.a(SourceFile:23)
	at com.google.android.apps.auto.components.system.statusbar.RailStatusBarFragment.e(SourceFile:3)
	at luz.onPreDraw(SourceFile:284)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1176)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4029)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: pjm: java.lang.IllegalStateException: OutOfCarLifecycle
	at pmn.e(SourceFile:115)
	at pmn.d(SourceFile:1)
	at pik.h(SourceFile:19)
	at pik.b(SourceFile:9)
	at pec.c(SourceFile:10)
	at ouc.S(SourceFile:5)
	at mgx.invoke(SourceFile:17)
	at ipy.a(SourceFile:241)
	at ioc.j(SourceFile:1)
	... 27 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3200)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at gtw.dT(SourceFile:11)
	at own.o(SourceFile:6)
	at pdm.call(SourceFile:78)
	at pik.b(SourceFile:1)
	... 32 more
```

**Comment by McClunatic** [comment]
Thanks @thestinger I'm confident you're right, I do have issues with this cable. Please disregard and I appreciate the quick reply.

**Comment by tuxpizza** [comment]
@thestinger I have not ran into this issue recently
