### ISSUE TITLE
System_server crashed

### ISSUE THREAD

**Issue by EBK187** [GrapheneOS/os-issue-tracker#3493]
System_server crashed 
```
type: crash
SystemUptimeMs: 44230477
Process: system_server
Build: google/oriole/oriole:14/AP1A.240405.002/2024042100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Can't change activity type once set: { mBounds=Rect(0, 0 - 2400, 1080) mAppBounds=Rect(0, 0 - 2272, 1017) mMaxBounds=Rect(0, 0 - 2400, 1080) mDisplayRotation=ROTATION_270 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0} activityType=home
	at android.app.WindowConfiguration.setActivityType(WindowConfiguration.java:436)
	at android.app.WindowConfiguration.setTo(WindowConfiguration.java:452)
	at android.content.res.Configuration.setTo(Configuration.java:1103)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:130)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.TaskFragment.onConfigurationChanged(TaskFragment.java:2446)
	at com.android.server.wm.Task.onConfigurationChangedInner(Task.java:1952)
	at com.android.server.wm.Task.onConfigurationChanged(Task.java:2022)
	at com.android.server.wm.ConfigurationContainer.dispatchConfigurationToChild(ConfigurationContainer.java:163)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.TaskFragment.onConfigurationChanged(TaskFragment.java:2446)
	at com.android.server.wm.Task.onConfigurationChangedInner(Task.java:1952)
	at com.android.server.wm.Task.onConfigurationChanged(Task.java:2034)
	at com.android.server.wm.ConfigurationContainer.dispatchConfigurationToChild(ConfigurationContainer.java:163)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.DisplayArea.onConfigurationChanged(DisplayArea.java:654)
	at com.android.server.wm.ConfigurationContainer.dispatchConfigurationToChild(ConfigurationContainer.java:163)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.DisplayArea.onConfigurationChanged(DisplayArea.java:654)
	at com.android.server.wm.ConfigurationContainer.dispatchConfigurationToChild(ConfigurationContainer.java:163)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.DisplayArea.onConfigurationChanged(DisplayArea.java:654)
	at com.android.server.wm.ConfigurationContainer.dispatchConfigurationToChild(ConfigurationContainer.java:163)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.DisplayArea.onConfigurationChanged(DisplayArea.java:654)
	at com.android.server.wm.ConfigurationContainer.dispatchConfigurationToChild(ConfigurationContainer.java:163)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.DisplayArea.onConfigurationChanged(DisplayArea.java:654)
	at com.android.server.wm.ConfigurationContainer.dispatchConfigurationToChild(ConfigurationContainer.java:163)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.DisplayArea.onConfigurationChanged(DisplayArea.java:654)
	at com.android.server.wm.DisplayContent.onConfigurationChanged(DisplayContent.java:2775)
	at com.android.server.wm.ConfigurationContainer.onRequestedOverrideConfigurationChanged(ConfigurationContainer.java:202)
	at com.android.server.wm.WindowContainer.onRequestedOverrideConfigurationChanged(WindowContainer.java:1036)
	at com.android.server.wm.DisplayArea.onRequestedOverrideConfigurationChanged(DisplayArea.java:72)
	at com.android.server.wm.DisplayContent.onRequestedOverrideConfigurationChanged(DisplayContent.java:6414)
	at com.android.server.wm.DisplayContent.performDisplayOverrideConfigUpdate(DisplayContent.java:6384)
	at com.android.server.wm.RootWindowContainer.dispatchConfigurationToChild(RootWindowContainer.java:621)
	at com.android.server.wm.RootWindowContainer.dispatchConfigurationToChild(RootWindowContainer.java:170)
	at com.android.server.wm.ConfigurationContainer.onConfigurationChanged(ConfigurationContainer.java:154)
	at com.android.server.wm.WindowContainer.onConfigurationChanged(WindowContainer.java:582)
	at com.android.server.wm.ActivityTaskManagerService.updateGlobalConfigurationLocked(ActivityTaskManagerService.java:4633)
	at com.android.server.wm.DisplayContent.updateDisplayOverrideConfigurationLocked(DisplayContent.java:6353)
	at com.android.server.wm.DisplayContent.updateDisplayOverrideConfigurationLocked(DisplayContent.java:6330)
	at com.android.server.wm.DisplayContent.sendNewConfiguration(DisplayContent.java:1668)
	at com.android.server.wm.Transition.applyDisplayChangeIfNeeded(Transition.java:2871)
	at com.android.server.wm.WindowOrganizerController.applyTransaction(WindowOrganizerController.java:575)
	at com.android.server.wm.WindowOrganizerController.applyTransaction(WindowOrganizerController.java:539)
	at com.android.server.wm.WindowOrganizerController.lambda$startTransition$4(WindowOrganizerController.java:368)
	at com.android.server.wm.WindowOrganizerController.$r8$lambda$OxMmVYZeM4xJh7uJ-Y5zE6BDr8Y(WindowOrganizerController.java:0)
	at com.android.server.wm.WindowOrganizerController$$ExternalSyntheticLambda6.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
[system_server crash 591d70f03952.txt](https://github.com/GrapheneOS/os-issue-tracker/files/15205961/system_server.crash.591d70f03952.txt)

**Comment by EBK187** [comment]
Help

**Comment by EBK187** [comment]
Help me

**Comment by EBK187** [comment]
[system_server crash 591d70f03952.txt](https://github.com/GrapheneOS/os-issue-tracker/files/15205964/system_server.crash.591d70f03952.txt)
