### ISSUE TITLE
Consistent Crash around 8:30AM EST on Pixel Fold

### ISSUE THREAD

**Issue by compacted-mug-dropper** [GrapheneOS/os-issue-tracker#3496]
Hey! I've lived being able to use my Pixel Fold with GrapheneOS, but consistently every morning from around 7:30am-9am I get a crash where the phone suddenly goes to the GrapheneOS logo with title (the boot screen) and then less than ten seconds later plops me back into the lock screen with all my software closed. Why could be causing it??? Here's my crash log from the latest one in case it helps, it doesn't always seem to give me one.

```
type: crash
SystemUptimeMs: 234454827
Process: system_server
Build: google/felix/felix:14/AP1A.240405.002.A2/2024042100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:976)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:954)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371)
	at com.android.server.pm.ShortcutBitmapSaver.waitForAllSavesLocked(ShortcutBitmapSaver.java:120)
	at com.android.server.pm.ShortcutPackageItem.waitForBitmapSaves(ShortcutPackageItem.java:233)
	at com.android.server.pm.ShortcutPackageItem.saveShortcutPackageItem(ShortcutPackageItem.java:216)
	at com.android.server.pm.ShortcutPackageItem$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
```

**Comment by compacted-mug-dropper** [comment]
Hm.. would there be a way to find what app that is or would this be a trial and error type beat?
