### ISSUE TITLE
Play Services crashes when adding a payment card to the Revolut app

### ISSUE THREAD

**Issue by FID02** [GrapheneOS/os-issue-tracker#3521]
EDIT: Updated version information.
In the Revolut app, Play Services crashes during the UI flow of adding a payment card to a Revolut account. 

https://play.google.com/store/apps/details?id=com.revolut.revolut

Please note, the actual adding of the card works fine regardless of the crash.

Please also note, I am on the Beta channel of Play Services in the Play Store, and opted in to update to unknown versions of Play Services and Play Store in Settings > Apps > Sandboxed Google Play.

Version information:
- Play Services 24.22.13
- GmsCompatConfig 115
- GrapheneOS 2024052100
- Revolut app 10.32

This is in a secondary profile.

Steps to reproduce:
1. Open the Revolut app, select 'Add money'
2. Make sure 'Debit or credit card' is selected
If a card is already added to the account, select 'Change' instead
4. Select 'Add money/card securely'

The app dialog that appears during the crash has an NFC feature for recognizing a payment card placed at the back of the device (not sure this is relevant; you don't have to tap the card to trigger the crash).

```
type: crash
osVersion: google/shiba/shiba:14/AP1A.240505.005/2024050900:user/release-keys
package: com.google.android.gms:241717038
process: com.google.android.gms
processUptime: 120970 + 446 ms
installer: com.android.vending
GmsCompatConfig version: 110

java.lang.IllegalArgumentException: Account cannot be null
	at tpl.b(:com.google.android.gms@241717038@24.17.17 (190400-631235745):51)
	at tpl.i(:com.google.android.gms@241717038@24.17.17 (190400-631235745):1)
	at tpl.g(:com.google.android.gms@241717038@24.17.17 (190400-631235745):6)
	at dlzu.a(:com.google.android.gms@241717038@24.17.17 (190400-631235745):195)
	at dmgd.M(:com.google.android.gms@241717038@24.17.17 (190400-631235745):10)
	at dmeb.M(:com.google.android.gms@241717038@24.17.17 (190400-631235745):3)
	at dmha.f(:com.google.android.gms@241717038@24.17.17 (190400-631235745):182)
	at bmst.hh(:com.google.android.gms@241717038@24.17.17 (190400-631235745):1)
	at bmtc.run(:com.google.android.gms@241717038@24.17.17 (190400-631235745):97)
	at ejjp.run(:com.google.android.gms@241717038@24.17.17 (190400-631235745):21)
	at amlz.c(:com.google.android.gms@241717038@24.17.17 (190400-631235745):50)
	at amlz.run(:com.google.android.gms@241717038@24.17.17 (190400-631235745):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at amrp.run(:com.google.android.gms@241717038@24.17.17 (190400-631235745):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: ejjz: 
		at tk_trace.4-getPaymentCardRecognitionIntent(Unknown Source:0)
		at tk_trace.wallet-PaymentChimeraService-IOwService_23(Unknown Source:0)


```

**Comment by FID02** [comment]
This never had any impact on the user beyond showing a notification about a crash. The app's NFC feature worked fine. Not an issue.
