### ISSUE TITLE
system_server crash when switching profiles

### ISSUE THREAD

**Issue by sanjacob** [GrapheneOS/os-issue-tracker#3527]
Just experienced this bug while switching back to the owner profile from another. I was using both wifi and bluetooth.

```
type: crash
SystemUptimeMs: 77812903
Process: system_server
Build: google/lynx/lynx:14/AP1A.240505.005/2024050700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3860)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1812)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1663)
	at com.android.server.am.UserController.startUser(UserController.java:1617)
	at com.android.server.am.UserController.startUser(UserController.java:1576)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1921)
	at com.android.server.am.UserController.handleMessage(UserController.java:3220)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by sauravpradhan** [comment]
I can help fix this as I have fixed these kinds of issues previously. How do i build the source code ? How do I get started ?

**Comment by rajatgupta1998** [comment]
> I can help fix this as I have fixed these kinds of issues previously. How do i build the source code ? How do I get started ?

@sauravpradhan , this is like AOSP environment, and GrapheneOS has their own manifest here:

[https://github.com/GrapheneOS/platform_manifest](https://github.com/GrapheneOS/platform_manifest)

Build instructions are present here as well: [https://grapheneos.org/build](https://grapheneos.org/build)

**Comment by sauravpradhan** [comment]
@rajatgupta1998 Completely get it. But is the build server hosted somewhere so that members can access ? If not its really difficult to get this baseline started in local machine ? Are you also contributing ?

**Comment by rajatgupta1998** [comment]
> @rajatgupta1998 Completely get it. But is the build server hosted somewhere so that members can access ? If not its really difficult to get this baseline started in local machine ? Are you also contributing ?

I think they have their private infra - as opposed to a community accessible server. I compile AOSP on my local machine only.  Let us move the discussion to the forum, it might be off-topic. [https://discuss.grapheneos.org/](https://discuss.grapheneos.org/)
