### ISSUE TITLE
reporting random crash log

### ISSUE THREAD

**Issue by cake2** [GrapheneOS/os-issue-tracker#3536]
```
type: crash
SystemUptimeMs: 92542136
Process: system_server
Build: google/shiba/shiba:14/AP1A.240505.005/2024050700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.media.MediaPlayer.finalize() timed out after 10 seconds
	at android.media.MediaPlayer.native_finalize(Native Method)
	at android.media.MediaPlayer.finalize(MediaPlayer.java:3444)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:362)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:342)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:314)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by muhomorr** [comment]
How to reproduce it?
