### ISSUE TITLE
im new to Graphene and my google services keep crashing.

### ISSUE THREAD

**Issue by AllKittyy** [GrapheneOS/os-issue-tracker#3554]
```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240505.005/2024051500:user/release-keys
package: com.google.android.gms:241718038
process: com.google.android.gms.persistent
processUptime: 3816582 + 377 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 111

java.lang.SecurityException: Neither user 1110145 nor current process has android.permission.ACCESS_FINE_LOCATION.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at android.location.ILocationManager$Stub$Proxy.addGnssMeasurementsListener(ILocationManager.java:1656)
	at android.location.LocationManager$GnssMeasurementsTransportManager.registerTransport(LocationManager.java:3156)
	at android.location.LocationManager$GnssMeasurementsTransportManager.registerTransport(LocationManager.java:3146)
	at com.android.internal.listeners.ListenerTransportManager.addListener(ListenerTransportManager.java:70)
	at android.location.LocationManager.registerGnssMeasurementsCallback(LocationManager.java:2793)
	at ecul.e(:com.google.android.gms@241718038@24.17.18 (190400-633711484):28)
	at ecpk.b(:com.google.android.gms@241718038@24.17.18 (190400-633711484):86)
	at ecqd.m(:com.google.android.gms@241718038@24.17.18 (190400-633711484):25)
	at ecqd.l(:com.google.android.gms@241718038@24.17.18 (190400-633711484):3)
	at ecoi.b(:com.google.android.gms@241718038@24.17.18 (190400-633711484):20)
	at ecqd.m(:com.google.android.gms@241718038@24.17.18 (190400-633711484):25)
	at ecqn.a(:com.google.android.gms@241718038@24.17.18 (190400-633711484):1156)
	at ecqn.run(:com.google.android.gms@241718038@24.17.18 (190400-633711484):11)
```

**Comment by AllKittyy** [comment]
I am indeed. I have been playing YouTube or YouTube music. Nothing else.
Even rebooted and just opened YouTube music again with all other apps
closed, and it still crashes.
Thank you for your quick response!

**Comment by AllKittyy** [comment]
Currently, it has full permission to location and sensors besides health
related ones. Anything here that would cause the issue?

**Comment by AllKittyy** [comment]
Ok, thanks for the clarification. I went ahead and gave it access to
precise location data. I don't see it having issues, but I'll play some
youtube to make sure!

Question for you, while I have your attention:
I installed Graphene the other day. I have it setup with multiple users so
that I can have my google sandboxed a bit better. I ran into an issue
immediately with RCS. It seems as though everyone who has an android that
supports RCS is able to get my texts, but cannot send me any. I don't know
for sure if my texts have come in through RCS or SMS, but I would assume
SMS, as I uninstalled google messenger for the graphene variant after
issues with this. I have been able to call and receive calls without issue,
and my sms to apple devices works fine. I'm not sure what else I can do to
make it work at this point.

Thank you again for your help!
~ CyborgRider.
