### ISSUE TITLE
Apps Closing and Sandbox Crashing Constantly

### ISSUE THREAD

**Issue by jtsteg** [GrapheneOS/os-issue-tracker#3557]
Phone: Pixel 6a

Every 2-5 minutes I get dozens of these errors from the sandboxed play services. It makes the device unusable. Other apps such as NordVPN and OpenWeather won't run more than a few seconds before they close. I may have to uninstall graphene if this isn't quickly resolvable because my phone is now unusable.

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.220905.004.A2/2022092300:user/release-keys
package: com.google.android.gms:241616038
process: com.google.android.gms.persistent

java.lang.SecurityException: Permission Denial: registerUidObserver from pid=24789, uid=10124 requires android.permission.PACKAGE_USAGE_STATS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.IActivityManager$Stub$Proxy.registerUidObserver(IActivityManager.java:4787)
	at android.app.ActivityManager.addOnUidImportanceListener(ActivityManager.java:3847)
	at com.google.android.gms.common.util.AppImportanceHelperV26.c(:com.google.android.gms@241616038@24.16.16 (190400-629452829):7)
	at com.google.android.gms.common.util.AppImportanceHelper.b(:com.google.android.gms@241616038@24.16.16 (190400-629452829):19)
	at eczs.z(:com.google.android.gms@241616038@24.16.16 (190400-629452829):9)
	at eczs.s(:com.google.android.gms@241616038@24.16.16 (190400-629452829):23)
	at eczs.handleMessage(:com.google.android.gms@241616038@24.16.16 (190400-629452829):31)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at bnlg.ny(:com.google.android.gms@241616038@24.16.16 (190400-629452829):1)
	at bnlg.dispatchMessage(:com.google.android.gms@241616038@24.16.16 (190400-629452829):138)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	Suppressed: eiri: 
		at tk_trace.location_base-GoogleLocationChimeraService_onCreate(Unknown Source:0)

```

and

```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.220905.004.A2/2022092300:user/release-keys
package: com.google.android.gms:241616038
process: com.google.android.gms.persistent

java.lang.SecurityException: Permission Denial: broadcast from com.google.android.gms asks to run as user -1 but is calling from uid u0a124; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3021)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5096)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1474)
	at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1441)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:599)
	at baiv.sendBroadcastAsUser(:com.google.android.gms@241616038@24.16.16 (190400-629452829):9)
	at dhkp.a(:com.google.android.gms@241616038@24.16.16 (190400-629452829):43)
	at dhkv.h(:com.google.android.gms@241616038@24.16.16 (190400-629452829):759)
	at dhkr.a(:com.google.android.gms@241616038@24.16.16 (190400-629452829):7)
	at dhkr.c(:com.google.android.gms@241616038@24.16.16 (190400-629452829):13)
	at com.google.android.gms.time.trustedtime.intentops.PersistentSingleUserModuleInitIntentOperation.b(:com.google.android.gms@241616038@24.16.16 (190400-629452829):131)
	at aipc.onHandleIntent(:com.google.android.gms@241616038@24.16.16 (190400-629452829):129)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@241616038@24.16.16 (190400-629452829):2)
	at aiug.onHandleIntent(:com.google.android.gms@241616038@24.16.16 (190400-629452829):8)
	at owa.run(:com.google.android.gms@241616038@24.16.16 (190400-629452829):70)
	at ovz.run(:com.google.android.gms@241616038@24.16.16 (190400-629452829):152)
	at eiqy.run(:com.google.android.gms@241616038@24.16.16 (190400-629452829):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by muhomorr** [comment]
You are running an outdated GrapheneOS version from September 2022. These issues are fixed in the current GrapheneOS version.
