### ISSUE TITLE
Pixel 6a crashing during sim unlock

### ISSUE THREAD

**Issue by Dariqq** [GrapheneOS/os-issue-tracker#3558]
Hi,

My Pixel6a is sometimes crashing during the unlock screen causing the device to reboot.

This has been going on for a couple of weeks but until today I got to a screen telling me android awas unable to start with the option to retry or wipe the device. Selecting retry everything started with no visible error. With todays update (2024-05-23) the device just instantly reboots and crashes again.

Removing the sim card during boot got me out of the loop. 

I skimmed the logs and found multiple crashes in `com.shannon.imsservice`

```
--------- beginning of crash
05-23 10093  2110  3097 E AndroidRuntime: FATAL EXCEPTION: Thread-10
05-23 10093  2110  3097 E AndroidRuntime: Process: com.shannon.imsservice, PID: 2110
05-23 10093  2110  3097 E AndroidRuntime: java.lang.SecurityException: Not allowed to access cell info
05-23 10093  2110  3097 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
05-23 10093  2110  3097 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3175)
05-23 10093  2110  3097 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3151)
05-23 10093  2110  3097 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3093)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getAllCellInfo(ITelephony.java:9826)
05-23 10093  2110  3097 E AndroidRuntime: 	at android.telephony.TelephonyManager.getAllCellInfo(TelephonyManager.java:6764)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.shannon.imsservice.util.DeviceInfoUtil.getCellPlmn(DeviceInfoUtil.java:208)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.shannon.imsservice.config.OperatorConfig.getNetworkNameFromSlotId(OperatorConfig.java:236)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.shannon.imsservice.config.OperatorConfig.getBooleanValue(OperatorConfig.java:114)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.shannon.imsservice.config.OperatorConfig.getBooleanValue(OperatorConfig.java:110)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.shannon.imsservice.config.OperatorConfig.isSmsFormat3GPP2(OperatorConfig.java:82)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.shannon.imsservice.sms.ImsSms.updateSmsFormat(ImsSms.java:434)
05-23 10093  2110  3097 E AndroidRuntime: 	at com.shannon.imsservice.sms.ImsSms$3.run(ImsSms.java:701)
```

Interestingly this does not seem to occur everytime as when I rebooted the device again with sim already inserted it did not reboot though still logged the same crash occuring, so i am not sure what is going on here and if the above crash is even the cause of the problem.

If you need more info let me know.

**Comment by muhomorr** [comment]
Log shows that a system app that is part of the telephony stack (ImsService, `com.shannon.imsservice`) doesn't have the Location permission, which it needs to function. You've probably revoked it manually.
