### ISSUE TITLE
system crash logging out from user

### ISSUE THREAD

**Issue by FraYoshi** [GrapheneOS/os-issue-tracker#3581]
Pixel 8 Pro

- I created a new user
- initialized it
- set pin and 1 fingerprint
- switched to owner
- switched back to user
- tried activating dev options
- entered the minigame of android 14, where the ship taked off
- played less than a minute
- received a telegram call on another phone (telegram was on owner, but was not ringing)
- got distracted less than a minute
- exited the mini-game
- logged-off the user
- waited for the owner pin to appear (did not)
- got rebooted and notified of the crash.

```
type: crash
SystemUptimeMs: 15359369
Process: system_server
Build: google/husky/husky:14/AP1A.240505.005/2024052100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3860)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1812)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1663)
	at com.android.server.am.UserController.startUser(UserController.java:1617)
	at com.android.server.am.UserController.startUser(UserController.java:1576)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1921)
	at com.android.server.am.UserController.handleMessage(UserController.java:3220)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by FraYoshi** [comment]
same happened again after the reboot, this time when switching to the profile, not yet unlocked.

- selected a couple dozens apps to install to tho now user from the owner
- waited a couple minute
- logged-in to the user profile
- crash and reboot before getting asked for the pin.

```
type: crash
SystemUptimeMs: 18407819
Process: system_server
Build: google/husky/husky:14/AP1A.240505.005/2024052100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3860)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1812)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1663)
	at com.android.server.am.UserController.startUser(UserController.java:1617)
	at com.android.server.am.UserController.startUser(UserController.java:1576)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1921)
	at com.android.server.am.UserController.handleMessage(UserController.java:3220)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
