### ISSUE TITLE
Android Auto crashed after unplugging and replugging Pixel 8

### ISSUE THREAD

**Issue by algues111** [GrapheneOS/os-issue-tracker#3591]
Hello !

I encountered a crash when I unplugged and replugged my Pixel 8 to my Nissan Car. 

Additional data :
> I only allowed Android Auto to use USB and not Wi-Fi nor Bluetooth

Here is the report :

```
type: crash
osVersion: google/shiba/shiba:14/AP1A.240505.005/2024052100:user/release-keys
package: com.google.android.projection.gearhead:118641624
process: com.google.android.projection.gearhead:car
processUptime: 1221951 + 314 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 114

java.lang.IllegalStateException: Unable to find touch IME
	at szr.aa(SourceFile:10)
	at guo.<init>(SourceFile:24)
	at hse.run(SourceFile:515)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

Thank you in advance for your work and have a nice end of week !

**Comment by algues111** [comment]
> @algues111 Which keyboard are you using?

AOSP Android Keyboard (French Switzerland).

Why ?
