### ISSUE TITLE
Pixel 7a system freeze, crash and reboot during user profile switch.

### ISSUE THREAD

**Issue by cybern0id** [GrapheneOS/os-issue-tracker#3601]
Pixel 7a
GOS: Most recent stable version 2024053100

Freeze, crash and automatic reboot when attempting user profile switch from 'Work' to 'Owner'. Preceding interaction was tapping 'Switch profile' button on Fairemail  notification.

```
type: crash
SystemUptimeMs: 16906746
Process: system_server
Build: google/lynx/lynx:14/AP1A.240505.005/2024053100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3860)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1812)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1663)
	at com.android.server.am.UserController.startUser(UserController.java:1617)
	at com.android.server.am.UserController.startUser(UserController.java:1576)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1921)
	at com.android.server.am.UserController.handleMessage(UserController.java:3220)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

**Comment by cybern0id** [comment]
Ah, this appears to be a duplicate of #3208 (though I had no media playing). Closing this one.
