### ISSUE TITLE
Google Play Services has Crashed

### ISSUE THREAD

**Issue by davidwilliams238** [GrapheneOS/os-issue-tracker#3610]
Google play services crashing after latest update when the Nearby Share pulldown menu tile is clicked. The crash log is:

```
type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240505.005/2024053100:user/release-keys
package: com.google.android.gms:242213038
process: com.google.android.gms.ui
processUptime: 451 + 224 ms
installer: com.android.vending
GmsCompatConfig version: 115

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.android.gms/com.google.android.gms.nearby.sharing.SetupActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2371)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1955)
	at android.app.Activity.startActivityForResult(Activity.java:5789)
	at pqa.platform_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ajgt.platform_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):4)
	at ppz.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ptz.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ppz.public_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at pqa.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):3)
	at ptr.a(:com.google.android.gms@242213038@24.22.13 (190400-638740827):172)
	at adl.a(:com.google.android.gms@242213038@24.22.13 (190400-638740827):32)
	at com.google.android.gms.nearby.sharing.QuickSettingsChimeraActivity.T(:com.google.android.gms@242213038@24.22.13 (190400-638740827):31)
	at cckw.a(:com.google.android.gms@242213038@24.22.13 (190400-638740827):23)
	at com.google.android.gms.nearby.sharing.BaseCardActivity.A(:com.google.android.gms@242213038@24.22.13 (190400-638740827):29)
	at cbwn.id(:com.google.android.gms@242213038@24.22.13 (190400-638740827):26)
	at djvc.run(:com.google.android.gms@242213038@24.22.13 (190400-638740827):18)
	at anck.c(:com.google.android.gms@242213038@24.22.13 (190400-638740827):12)
	at bbnf.run(:com.google.android.gms@242213038@24.22.13 (190400-638740827):5)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at bpat.nM(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at bpat.dispatchMessage(:com.google.android.gms@242213038@24.22.13 (190400-638740827):138)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: emes: 
		at tk_trace.nearby-IBooleanResultListener_0(Unknown Source:0)
```

**Comment by hokutoryuken** [comment]
Same error encountered:
```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S1/2024052300:user/release-keys
package: com.android.vending:84122130
process: com.android.vending
processUptime: 824328 + 348 ms
installer: com.android.vending
GmsCompatConfig version: 116

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 561528 bytes
Bundle stats:
  AcquireClientConfigModel.clientConfig [size=9644]
    protoparsers [size=9596]
  ComponentMapModel [size=144284]
    ComponentMapModel.contentComponents_values [size=142732]
      protoparsers [size=142684]
  ActionMapModel [size=10796]
    ActionMapModel.action_values [size=10588]
      protoparsers [size=10540]
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=201704]
    androidx.lifecycle.internal.SavedStateHandlesProvider [size=193360]
      androidx.lifecycle.ViewModelProvider.DefaultKey:aidm [size=193232]
        values [size=192536]
    android:support:activity-result [size=1176]
    android:support:fragments [size=6800]
      fragment_da13c20f-e535-4b88-9286-90205c657958 [size=6460]
        viewState [size=5200]
  DialogScreenMapModel [size=173024]
    im5-paysafecard [size=31560]
      protoparsers [size=31512]
    a [size=2520]
      protoparsers [size=2472]
    c [size=3368]
      protoparsers [size=3320]
    bp [size=15256]
      protoparsers [size=15208]
    ri [size=1236]
      protoparsers [size=1188]
    im1 [size=38624]
      protoparsers [size=38576]
    im_767051 [size=1148]
      protoparsers [size=1100]
    im_767052 [size=1144]
      protoparsers [size=1096]
    im_767053 [size=1140]
      protoparsers [size=1092]
    im_786012 [size=24260]
      protoparsers [size=24212]
    im_786013 [size=25132]
      protoparsers [size=25084]
    im_786014 [size=25052]
      protoparsers [size=25004]
  AcquireDroidGuardModel.droidGuardPayload [size=16312]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:165)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.TransactionTooLargeException: data parcel size 561528 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1316)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:95)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:154)
	... 10 more

```
Oops i missed thé additional lines at thé bottom

**Comment by muhomorr** [comment]
@hokutoryuken That's an unrelated upstream Play Store issue. It's not caused by GrapheneOS.

**Comment by hokutoryuken** [comment]
sorry, i thought it could help. should i delete my message?

**Comment by muhomorr** [comment]
No, it's still useful to have this crash here in case it has to be searched for.

**Comment by NewGate69** [comment]
I had same sort of crash, when enabling and disabling the play services. 

Error txt

```
type: crash
osVersion: google/husky/husky:14/AP1A.240505.005/2024060500:user/release-keys
package: com.google.android.gms:241517038
process: com.google.android.gms.persistent
processUptime: 1340813 + 383 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 117

java.lang.RuntimeException: Unable to start receiver com.google.android.gms.gservices.provider.GservicesOverrideReceiver: java.lang.IllegalArgumentException: Unknown URI content://com.google.android.gsf.gservices/override
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4683)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2364)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalArgumentException: Unknown URI content://com.google.android.gsf.gservices/override
	at android.content.ContentResolver.update(ContentResolver.java:2440)
	at android.content.ContentResolver.update(ContentResolver.java:2406)
	at com.google.android.gms.gservices.provider.GservicesChimeraProvider$OverrideReceiver.onReceive(:com.google.android.gms@241517038@24.15.17 (190400-626366329):54)
	at ainc.a(:com.google.android.gms@241517038@24.15.17 (190400-626366329):34)
	at orh.onReceive(:com.google.android.gms@241517038@24.15.17 (190400-626366329):32)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4674)
	... 11 more
```

**Comment by NewGate69** [comment]
Enabled it again. My bad. :(

**Comment by muhomorr** [comment]
@davidwilliams238 I've reproduced this issue yesterday, but it's no longer reproducible today. There must have been a server-side change. Check whether it's still reproducible on your device.

**Comment by NewGate69** [comment]
Hi.
It seems it was a one off. Error is not seen enabling disabling GP services

Thanks for fast update.

**Comment by TheRealBellzy** [comment]
I had a crash as well. Looks to be a little different. 

```
type: crash
osVersion: google/shiba/shiba:14/AP1A.240505.005/2024060500:user/release-keys
package: com.google.android.gms:241517038
process: com.google.android.gms
processUptime: 9221798 + 306 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 117

epcb: rethrowing exception from lowpool[38]
	at amgk.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):43)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at bnbb.nx(:com.google.android.gms@241517038@24.15.17 (190400-626366329):1)
	at bnbb.dispatchMessage(:com.google.android.gms@241517038@24.15.17 (190400-626366329):138)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: eiaf: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.semanticlocationhistory-OdlhDatabaseCleanupJob_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.IllegalStateException: Couldn't read row 2885, col 2 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetBlob(Native Method)
	at android.database.CursorWindow.getBlob(CursorWindow.java:430)
	at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:48)
	at czlr.s(:com.google.android.gms@241517038@24.15.17 (190400-626366329):17)
	at czlr.k(:com.google.android.gms@241517038@24.15.17 (190400-626366329):34)
	at czlr.p(:com.google.android.gms@241517038@24.15.17 (190400-626366329):10)
	at com.google.android.gms.semanticlocationhistory.db.OdlhDatabaseCleanupJob.kc(:com.google.android.gms@241517038@24.15.17 (190400-626366329):1408)
	at bncy.a(:com.google.android.gms@241517038@24.15.17 (190400-626366329):9)
	at epby.a(:com.google.android.gms@241517038@24.15.17 (190400-626366329):3)
	at epay.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):21)
	at epca.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):5)
	at amhb.c(:com.google.android.gms@241517038@24.15.17 (190400-626366329):50)
	at amhb.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ammr.run(:com.google.android.gms@241517038@24.15.17 (190400-626366329):8)
	at java.lang.Thread.run(Thread.java:1012)
```
