### ISSUE TITLE
Android Auto crashed - OutOfCarLifecycle

### ISSUE THREAD

**Issue by jabjoe** [GrapheneOS/os-issue-tracker#3626]
I'm getting it crash quite a lot on every car I've used it with. This popped up. Not sure if this is same crash, but here it is.

```
type: crash
osVersion: google/raven/raven:14/AP1A.240505.004/2024060500:user/release-keys
package: com.google.android.projection.gearhead:118641624
process: com.google.android.projection.gearhead:projection
processUptime: 48355853 + 337 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 117

imx: Non-recoverable error during initialization. Bailing.
	at ilh.l(SourceFile:56)
	at ilh.e(SourceFile:13)
	at ucl.c(SourceFile:292)
	at jkr.k(SourceFile:19)
	at jko.a(SourceFile:20)
	at imu.v(SourceFile:177)
	at isk.a(SourceFile:1040)
	at ord.f(SourceFile:19)
	at pae.run(SourceFile:730)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: pfg: java.lang.IllegalStateException: OutOfCarLifecycle
[log.log](https://github.com/user-attachments/files/15795706/log.log)

	at oqe.H(SourceFile:115)
	at oqe.G(SourceFile:1)
	at pei.h(SourceFile:19)
	at pei.b(SourceFile:9)
	at ozw.c(SourceFile:10)
	at opw.aj(SourceFile:5)
	at ucj.a(SourceFile:13)
	at ind.a(SourceFile:248)
	at ilh.l(SourceFile:1)
	... 18 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3199)
	at android.os.Parcel.createException(Parcel.java:3175)
	at android.os.Parcel.readException(Parcel.java:3151)
	at android.os.Parcel.readException(Parcel.java:3093)
	at gre.dU(SourceFile:11)
	at osh.p(SourceFile:6)
	at ozg.call(SourceFile:78)
	at pei.b(SourceFile:1)
	... 23 more
```

**Comment by jabjoe** [comment]
It's 3 different cables in 3 different cars. Each cable and car combo doesn't have this with my wife's stock Android.

But I'll make sure the USB port is clear/clean.
