### ISSUE TITLE
Crash when connecting Anker USB-C hub

### ISSUE THREAD

**Issue by rei-zero246** [GrapheneOS/os-issue-tracker#3689]
```
type: crash
SystemUptimeMs: 153967101
Process: system_server
Build: google/husky/husky:14/AP2A.240605.024/2024062000:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to read from field 'int android.view.SurfaceControl$DesiredDisplayModeSpecs.defaultMode' on a null object reference in method 'boolean com.android.server.display.LocalDisplayAdapter$LocalDisplayDevice.updateDisplayModesLocked(android.view.SurfaceControl$DisplayMode[], int, int, float, android.view.SurfaceControl$DesiredDisplayModeSpecs)'
	at com.android.server.display.LocalDisplayAdapter$LocalDisplayDevice.updateDisplayModesLocked(LocalDisplayAdapter.java:418)
	at com.android.server.display.LocalDisplayAdapter$LocalDisplayDevice.updateDisplayPropertiesLocked(LocalDisplayAdapter.java:290)
	at com.android.server.display.LocalDisplayAdapter$LocalDisplayDevice.<init>(LocalDisplayAdapter.java:263)
	at com.android.server.display.LocalDisplayAdapter.tryConnectDisplayLocked(LocalDisplayAdapter.java:166)
	at com.android.server.display.LocalDisplayAdapter.-$$Nest$mtryConnectDisplayLocked(LocalDisplayAdapter.java:0)
	at com.android.server.display.LocalDisplayAdapter$LocalDisplayEventListener.onHotplug(LocalDisplayAdapter.java:1466)
	at com.android.server.display.LocalDisplayAdapter$ProxyDisplayEventReceiver.onHotplug(LocalDisplayAdapter.java:1435)
	at android.view.DisplayEventReceiver.dispatchHotplug(DisplayEventReceiver.java:365)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by rei-zero246** [comment]
[
[Kernel crash 70467942d58e.txt](https://github.com/user-attachments/files/15991944/Kernel.crash.70467942d58e.txt)

**Comment by rei-zero246** [comment]
```
type: crash
osVersion: google/husky/husky:14/AP2A.240605.024/2024062000:user/release-keys
uid: 1000 (u:r:surfaceflinger:s0)
cmdline: /system/bin/surfaceflinger
processUptime: 54s

signal: 11 (SIGSEGV), code 1 (SEGV_MAPERR), faultAddr 0
cause: null pointer dereference
threadName: surfaceflinger
MTE: not enabled

backtrace:
    /system/bin/surfaceflinger (android::SurfaceFlinger::loadDisplayModes(android::PhysicalDisplayId) const+624, pc 3f0500)
    /system/bin/surfaceflinger (android::SurfaceFlinger::processHotplug(android::PhysicalDisplayId, unsigned long, bool, android::DisplayIdentificationInfo&&)+140, pc 3f100c)
    /system/bin/surfaceflinger (android::SurfaceFlinger::configureLocked()+220, pc 3ea78c)
    /system/bin/surfaceflinger (android::SurfaceFlinger::configure()+56, pc 3eeb78)
    /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+1000, pc 10fb8)
    /system/bin/surfaceflinger (android::impl::MessageQueue::waitMessage()+76, pc 3d31fc)
    /system/bin/surfaceflinger (main+748, pc 42388c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+120, pc 5f0a8)
```

**Comment by rei-zero246** [comment]
```
type: crash
osVersion: google/husky/husky:14/AP2A.240605.024/2024062000:user/release-keys
uid: 1000 (u:r:surfaceflinger:s0)
cmdline: /system/bin/surfaceflinger
processUptime: 3s

signal: 11 (SIGSEGV), code 1 (SEGV_MAPERR), faultAddr 0
cause: null pointer dereference
threadName: surfaceflinger
MTE: not enabled

backtrace:
    /system/bin/surfaceflinger (android::SurfaceFlinger::loadDisplayModes(android::PhysicalDisplayId) const+624, pc 3f0500)
    /system/bin/surfaceflinger (android::SurfaceFlinger::processHotplug(android::PhysicalDisplayId, unsigned long, bool, android::DisplayIdentificationInfo&&)+140, pc 3f100c)
    /system/bin/surfaceflinger (android::SurfaceFlinger::configureLocked()+220, pc 3ea78c)
    /system/bin/surfaceflinger (android::SurfaceFlinger::configure()+56, pc 3eeb78)
    /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+1000, pc 10fb8)
    /system/bin/surfaceflinger (android::impl::MessageQueue::waitMessage()+76, pc 3d31fc)
    /system/bin/surfaceflinger (main+748, pc 42388c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+120, pc 5f0a8)
```

**Comment by rei-zero246** [comment]
The device caused the phone to restart to the point I thought that it wasn't going to turn back on.

**Comment by rei-zero246** [comment]
Build number 2024062000.

**Comment by rei-zero246** [comment]
This has not happened again.
