### ISSUE TITLE
GrapheneOS lagging then crashing

### ISSUE THREAD

**Issue by Streammet** [GrapheneOS/os-issue-tracker#3696]
```
type: crash
SystemUptimeMs: 89599855
Process: system_server
Build: google/oriole/oriole:14/AP2A.240605.024/2024062000:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 5116320 free bytes and 4996KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at android.net.connectivity.com.android.server.connectivity.NetworkRanker.mightBeat(NetworkRanker.java:386)
	at android.net.connectivity.com.android.server.ConnectivityService.informOffer(ConnectivityService.java:10647)
	at android.net.connectivity.com.android.server.ConnectivityService.issueNetworkNeeds(ConnectivityService.java:10582)
	at android.net.connectivity.com.android.server.ConnectivityService.issueNetworkNeeds(ConnectivityService.java:10575)
	at android.net.connectivity.com.android.server.ConnectivityService.rematchNetworksAndRequests(ConnectivityService.java:10335)
	at android.net.connectivity.com.android.server.ConnectivityService.rematchAllNetworksAndRequests(ConnectivityService.java:10319)
	at android.net.connectivity.com.android.server.ConnectivityService.handleRegisterNetworkRequests(ConnectivityService.java:5456)
	at android.net.connectivity.com.android.server.ConnectivityService.handleRegisterNetworkRequest(ConnectivityService.java:5421)
	at android.net.connectivity.com.android.server.ConnectivityService.-$$Nest$mhandleRegisterNetworkRequest(ConnectivityService.java:0)
	at android.net.connectivity.com.android.server.ConnectivityService$InternalHandler.handleMessage(ConnectivityService.java:6339)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

This happens like once every second day.

**Comment by mar0ni** [comment]
```
type: crash
SystemUptimeMs: 534026
Process: system_server
Build: google/akita/akita:14/AP2A.240605.024/2024062700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at android.location.provider.LocationProviderBase$Service.lambda$flush$1(LocationProviderBase.java:349)
	at android.location.provider.LocationProviderBase$Service$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:1024)
	at com.android.server.SystemServer.main(SystemServer.java:702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
Caused by: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:60)
	at android.location.LocationManager.requestFlush(LocationManager.java:1718)
	at com.android.location.gnss.GnssOverlayLocationProvider.onFlush(GnssOverlayLocationProvider.java:112)
	at android.location.provider.LocationProviderBase$Service.flush(LocationProviderBase.java:344)
	at com.android.server.location.provider.proxy.ProxyLocationProvider$2.run(ProxyLocationProvider.java:207)
	at com.android.server.servicewatcher.ServiceWatcherImpl$MyServiceConnection.runOnBinder(ServiceWatcherImpl.java:257)
	at com.android.server.servicewatcher.ServiceWatcherImpl.lambda$runOnBinder$0(ServiceWatcherImpl.java:126)
	at com.android.server.servicewatcher.ServiceWatcherImpl.$r8$lambda$GCGDYqQZRK7jCQUNZnY8QjXgR2Y(ServiceWatcherImpl.java:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

I just switched to a secondary profile with Google Play Services installed and after some time doing nothing, System Server crashes.

**Comment by Streammet** [comment]
mar0ni create a new issue. Dont comment on mine.

**Comment by Streammet** [comment]
Thestinger what can I provide, that would help you?
