### ISSUE TITLE
Crash when switching between profiles

### ISSUE THREAD

**Issue by Mollydog123** [GrapheneOS/os-issue-tracker#3704]
Hello, I am experiencing a common crash when switching between profiles. I have a pixel 8 pro, running build 2024062700.

Here is the crash dump:

```
type: crash
SystemUptimeMs: 196199
Process: system_server
Build: google/husky/husky:14/AP2A.240605.024/2024062700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3885)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1832)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1683)
	at com.android.server.am.UserController.startUser(UserController.java:1637)
	at com.android.server.am.UserController.startUser(UserController.java:1596)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1944)
	at com.android.server.am.UserController.handleMessage(UserController.java:3240)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

Possibly duplicate of https://github.com/GrapheneOS/os-issue-tracker/issues/3644

**Comment by Mollydog123** [comment]
I can confirm I performed a similar series of steps to what is described by this comment:
https://github.com/GrapheneOS/os-issue-tracker/issues/3644#issuecomment-2181649387
