### ISSUE TITLE
Settings app crashes when optimized charging on P8p

### ISSUE THREAD

**Issue by dill-shower** [GrapheneOS/os-issue-tracker#3734]
If I try to touch "Learn more"  button on settings app crashes. 

![Grp](https://github.com/GrapheneOS/os-issue-tracker/assets/114938733/94a13443-c887-4b48-a4bf-a7eb0d274bdc)
````
type: crash
osVersion: google/husky/husky:14/AP2A.240705.005/2024070201:user/release-keys
package: com.android.settings:34
process: com.android.settings
processUptime: 2577 + 421 ms

java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.ComponentActivity.startActivityForResult, parameter intent
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:2)
	at com.android.settings.core.SettingsBaseActivity.startActivityForResult(SettingsBaseActivity.java:165)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:244)
	at com.android.settings.fuelgauge.batterytip.tips.BatteryDefenderTip.lambda$updatePreference$0(BatteryDefenderTip.java:99)
	at com.android.settings.fuelgauge.batterytip.tips.BatteryDefenderTip.$r8$lambda$nkfimum8X6g1NthvgvUZY2Ggu2A(BatteryDefenderTip.java:0)
	at com.android.settings.fuelgauge.batterytip.tips.BatteryDefenderTip$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:0)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke-k-4lQ0M(Clickable.kt:644)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:638)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:680)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:559)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:581)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:1041)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:316)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:302)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:302)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:185)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:104)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:113)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1751)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1702)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1641)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:496)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4518)
	at android.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:53)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:454)
	at android.view.View.dispatchPointerEvent(View.java:16548)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7559)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7326)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6723)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6912)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6969)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6780)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6746)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6754)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6727)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9827)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9778)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9747)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9969)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@9a156b0, androidx.compose.runtime.BroadcastFrameClock@e3bb929, StandaloneCoroutine{Cancelling}@8e84ae, AndroidUiDispatcher@5afb24f]
```
`

**Comment by dill-shower** [comment]
It's crashes every time
