### ISSUE TITLE
Crash on Pixel 6 Pro

### ISSUE THREAD

**Issue by rawpie2** [GrapheneOS/os-issue-tracker#3739]
```
type: crash
osVersion: google/raven/raven:14/AP2A.240605.024/2024062700:user/release-keys
package: com.google.android.gms:242632038
process: com.google.android.gms
processUptime: 2687277 + 2527 ms
installer: com.android.vending
GmsCompatConfig version: 122

eppz: gerk: Timed out waiting for 10000 ms
	at dpzk.c(:com.google.android.gms@242632038@24.26.32 (190400-650348549):98)
	at dqfy.f(:com.google.android.gms@242632038@24.26.32 (190400-650348549):610)
	at bous.ft(:com.google.android.gms@242632038@24.26.32 (190400-650348549):1)
	at bovb.run(:com.google.android.gms@242632038@24.26.32 (190400-650348549):86)
	at enqq.run(:com.google.android.gms@242632038@24.26.32 (190400-650348549):21)
	at anzz.c(:com.google.android.gms@242632038@24.26.32 (190400-650348549):50)
	at anzz.run(:com.google.android.gms@242632038@24.26.32 (190400-650348549):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at aofk.run(:com.google.android.gms@242632038@24.26.32 (190400-650348549):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: enrb: 
		at tk_trace.4-getClientToken(Unknown Source:0)
		at tk_trace.wallet-PaymentChimeraService-IOwService_14(Unknown Source:0)
Caused by: gerk: Timed out waiting for 10000 ms
	at gerl.run(:com.google.android.gms@242632038@24.26.32 (190400-650348549):42)
	at gepm.run(:com.google.android.gms@242632038@24.26.32 (190400-650348549):3)
	at gepp.l(:com.google.android.gms@242632038@24.26.32 (190400-650348549):205)
	at geot.run(:com.google.android.gms@242632038@24.26.32 (190400-650348549):25)
	... 1 more
```

**Comment by rawpie2** [comment]
> Did this happen more than once, or only once and not again?

Happens a lot actually.
Every few hours or so
