### ISSUE TITLE
Google  crashes when switching on bluetootg- uknown bluetooth in my car (multiple devicea)

### ISSUE THREAD

**Issue by Mohdghnaim** [GrapheneOS/os-issue-tracker#3751]
Bluetooth is already on
Unknown Trackers is tellibg me switch on bluetooth
When i click on turn on bluetooth, it crashes

I have three unknown trackers in my car wuth strange names that make no sense 

type: crash
osVersion: google/cheetah/cheetah:14/AP2A.240705.004/2024070900:user/release-keys
package: com.google.android.gms:242213038
process: com.google.android.gms.ui
processUptime: 30514 + 248 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 122

java.lang.SecurityException: Permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity } from ProcessRecord{ec94555 9666:com.google.android.gms.ui/u0a150} (pid=9666, uid=10150) requires android.permission.BLUETOOTH_CONNECT
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2087)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2006)
	at android.app.Activity.startActivityForResult(Activity.java:5886)
	at pqa.platform_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ajgt.platform_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):4)
	at ppz.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ptz.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ppz.public_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at pqa.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):3)
	at android.app.Activity.startActivityForResult(Activity.java:5806)
	at pqa.platform_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at ajgt.platform_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ppz.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at ptz.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at ppz.public_startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at pqa.startActivityForResult(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at android.app.Activity.startActivity(Activity.java:6348)
	at pqa.platform_startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ajgt.platform_startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):4)
	at ppz.startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at com.google.android.chimera.android.Activity.startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ppz.public_startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at pqa.startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):3)
	at android.app.Activity.startActivity(Activity.java:6315)
	at pqa.platform_startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at ajgt.platform_startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):2)
	at ppz.startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at com.google.android.chimera.android.Activity.startActivity(:com.google.android.gms@242213038@24.22.13 (190400-638740827):1)
	at eioe.onClick(:com.google.android.gms@242213038@24.22.13 (190400-638740827):18)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1155)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1128)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:780)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1306)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1251)
```

**Comment by empratyush** [comment]
should be fixed [see](https://github.com/GrapheneOS/os-issue-tracker/issues/3621) .
