### ISSUE TITLE
Pixel 8a crasches constantly when switching to secondary user with Google Playstore inatalled

### ISSUE THREAD

**Issue by mar0ni** [GrapheneOS/os-issue-tracker#3754]
```
type: crash
SystemUptimeMs: 143696
Process: system_server
Build: google/akita/akita:14/AP2A.240705.005/2024071200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at android.location.provider.LocationProviderBase$Service.lambda$flush$1(LocationProviderBase.java:349)
	at android.location.provider.LocationProviderBase$Service$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:1024)
	at com.android.server.SystemServer.main(SystemServer.java:702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
Caused by: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:60)
	at android.location.LocationManager.requestFlush(LocationManager.java:1718)
	at com.android.location.gnss.GnssOverlayLocationProvider.onFlush(GnssOverlayLocationProvider.java:112)
	at android.location.provider.LocationProviderBase$Service.flush(LocationProviderBase.java:344)
	at com.android.server.location.provider.proxy.ProxyLocationProvider$2.run(ProxyLocationProvider.java:207)
	at com.android.server.servicewatcher.ServiceWatcherImpl$MyServiceConnection.runOnBinder(ServiceWatcherImpl.java:257)
	at com.android.server.servicewatcher.ServiceWatcherImpl.lambda$runOnBinder$0(ServiceWatcherImpl.java:126)
	at com.android.server.servicewatcher.ServiceWatcherImpl.$r8$lambda$GCGDYqQZRK7jCQUNZnY8QjXgR2Y(ServiceWatcherImpl.java:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by mar0ni** [comment]
Hi Daniel, sure, whatever info is helpful. Just let me know, what to do.

For me, this happens nearly instantly when I switch to my secondary user on the phone who has the sandboxed Play Store and dependencies installed. Switching to this user which is protected by PIN crashes the phone some seconds later. This user existed before (the OS update) and there are some Play Store Apps installed. 

I uninstalled the Play Services and dependencies. W/o them, the phone does not crash but re-installing them again crashes the phone when switching to this user.

**Comment by mar0ni** [comment]
The updated configuration did not fix the problem.
