### ISSUE TITLE
system_server crash when switching from second profile back to the owner

### ISSUE THREAD

**Issue by Git08hb** [GrapheneOS/os-issue-tracker#3758]
I can use the owner profile without any problems and can switch to the second profile. However when I'm in the second profile and want to switch back to the Owner profile the screen freezes or the OS stopped working? After a few seconds GrapheneOS logo shows up and the phone reboots itself. Then I can use the owner profile. Happens every time.

Here is the crash report:

```
type: crash
SystemUptimeMs: 21257169
Process: system_server
Build: google/oriole/oriole:14/AP2A.240705.004/2024071200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3885)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1832)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1683)
	at com.android.server.am.UserController.startUser(UserController.java:1637)
	at com.android.server.am.UserController.startUser(UserController.java:1596)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1944)
	at com.android.server.am.UserController.handleMessage(UserController.java:3240)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by esatravi** [comment]
I have exactly the same problem. GrapheneOS got automatically upgraded and now I can't switch to any profile. The OS crushes causing phone to restart. 

type: crash
SystemUptimeMs: 127426
Process: system_server
Build: google/redfin/redfin:14/UP1A.231105.001.B2/2024071200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:3885)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1832)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1683)
	at com.android.server.am.UserController.startUser(UserController.java:1637)
	at com.android.server.am.UserController.startUser(UserController.java:1596)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:1944)
	at com.android.server.am.UserController.handleMessage(UserController.java:3240)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by esatravi** [comment]
I am now unable to access any data stored on that profile. The main/'owner; profile loads upon the phone restart, and that's where the system_server error notification is displayed. 

Please advise how can I access my data stored in other profile.
