### ISSUE TITLE
Android Auto Crashing

### ISSUE THREAD

**Issue by danshick** [GrapheneOS/os-issue-tracker#3772]
```
type: crash
osVersion: google/husky/husky:14/AP2A.240705.005/2024071600:user/release-keys
package: com.google.android.projection.gearhead:122642414
process: com.google.android.projection.gearhead:projection
processUptime: 3192662 + 349 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 123

ixg: Unable to access car
	at iww.e(SourceFile:56)
	at iww.b(SourceFile:13)
	at jne.dz(SourceFile:33)
	at jwi.b(SourceFile:57)
	at usp.c(SourceFile:160)
	at jwj.k(SourceFile:19)
	at jwg.a(SourceFile:20)
	at ixd.v(SourceFile:177)
	at jdj.a(SourceFile:1073)
	at pgy.f(SourceFile:19)
	at ppz.run(SourceFile:730)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: pvb: java.lang.IllegalStateException: OutOfCarLifecycle
	at pyd.b(SourceFile:115)
	at pyd.a(SourceFile:1)
	at ptz.h(SourceFile:19)
	at ptz.b(SourceFile:9)
	at ppr.v(SourceFile:10)
	at pfr.A(SourceFile:5)
	at osi.g(SourceFile:1)
	at jmv.a(SourceFile:1024)
	at ixm.a(SourceFile:248)
	at iww.e(SourceFile:1)
	... 20 more
Caused by: java.lang.IllegalStateException: OutOfCarLifecycle
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3200)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at gzh.dY(SourceFile:11)
	at pic.A(SourceFile:7)
	at ppc.a(SourceFile:14)
	at ptz.n(SourceFile:14)
	at ppb.call(SourceFile:217)
	at ptz.b(SourceFile:1)
	... 26 more
```

**Comment by danshick** [comment]
I suppose it might be, but as of a recent update it went from never crashing to crashing multiple times during a short drive.

I believe before this crashing behavior, small connection hiccups would resolve themselves quietly, maybe causing a slight slowness in the screen updating or audio pauses. Now it crashes all the way back to the vehicle "please connect" screen and takes ten or so seconds to reconnect as the app restarts.

Prior to recent updates, even running Android Auto wired and yanking the cable out would not cause the app to crash.
