### ISSUE TITLE
System crash on autofill invocation

### ISSUE THREAD

**Issue by rnwst** [GrapheneOS/os-issue-tracker#3790]
```
type: crash
SystemUptimeMs: 252922364
Process: system_server
Build: google/lynx/lynx:14/AP2A.240705.004/2024071600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.autofill.ui.FillUi$AnchoredWindow.show(android.view.WindowManager$LayoutParams)' on a null object reference
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.lambda$show$0(FillUi.java:692)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.$r8$lambda$rayRxR7zWVCJ_EZ9KlZ9jO79cqM(FillUi.java:0)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)
```

**Comment by mccarthyp64** [comment]
Also just got this crash, it seems like the phone was performing worse and worse each time I'd fill in more fields in the form and it finally crashed on a credit card field (I use KeePassXC for password management and autofill).

````
type: crash
SystemUptimeMs: 59548359
Process: system_server
Build: google/shiba/shiba:14/AP2A.240905.003/2024091900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.autofill.ui.FillUi$AnchoredWindow.show(android.view.WindowManager$LayoutParams)' on a null object reference
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.lambda$show$0(FillUi.java:692)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter.$r8$lambda$rayRxR7zWVCJ_EZ9KlZ9jO79cqM(FillUi.java:0)
	at com.android.server.autofill.ui.FillUi$AutofillWindowPresenter$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
	at com.android.server.UiThread.run(UiThread.java:45)
```
`
