### ISSUE TITLE
system_server has crashed 

### ISSUE THREAD

**Issue by mar0ni** [GrapheneOS/os-issue-tracker#3791]
```
type: crash
SystemUptimeMs: 23434899
Process: system_server
Build: google/akita/akita:14/AP2A.240705.005/2024071600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.AssertionError: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at android.location.provider.LocationProviderBase$Service.lambda$flush$1(LocationProviderBase.java:349)
	at android.location.provider.LocationProviderBase$Service$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:1024)
	at com.android.server.SystemServer.main(SystemServer.java:702)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
Caused by: java.lang.IllegalArgumentException: unregistered listener cannot be flushed
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:60)
	at android.location.LocationManager.requestFlush(LocationManager.java:1718)
	at com.android.location.gnss.GnssOverlayLocationProvider.onFlush(GnssOverlayLocationProvider.java:112)
	at android.location.provider.LocationProviderBase$Service.flush(LocationProviderBase.java:344)
	at com.android.server.location.provider.proxy.ProxyLocationProvider$2.run(ProxyLocationProvider.java:207)
	at com.android.server.servicewatcher.ServiceWatcherImpl$MyServiceConnection.runOnBinder(ServiceWatcherImpl.java:257)
	at com.android.server.servicewatcher.ServiceWatcherImpl.lambda$runOnBinder$0(ServiceWatcherImpl.java:126)
	at com.android.server.servicewatcher.ServiceWatcherImpl.$r8$lambda$GCGDYqQZRK7jCQUNZnY8QjXgR2Y(ServiceWatcherImpl.java:0)
	at com.android.server.servicewatcher.ServiceWatcherImpl$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by mar0ni** [comment]
This still happens when switching to another profile with Google Play Services installed. 

I completely deleted my previous profile where this happened and set-up a new one. The same problem occurs and the crash happens immediately after unlocking the secondary profile with a pin (fingerprint also setup). This is with an Pixel 8a.
