### ISSUE TITLE
settings app crash on pixle 7 when trying to set up sim

### ISSUE THREAD

**Issue by wobby-droid** [GrapheneOS/os-issue-tracker#3800]
So for a long time something has been off with my graphene OS install. WiFi would abrubtly stop and so would some other apps but I had data so it wasn't that big of a deal, usually a reset would fix things for awile so I brushed it off. Until recently when my data stopped working today so I couldn't get texts & calls. I tried to turn the sim services on off and on again but when I tried to click on use this sim in settings, settings crashes. I tried resetting the phone & resetting mobile network settings & I tried shutting off the phone removing the sim and putting it back in. I have a physical sim card & boost infinite is my provider. I also use user profiles Trying to enter any carrier settings causes the same issue.
Here's the error message:

type: crash
osVersion: google/panther/panther:14/AP2A.240705.004/2024071600:user/release-keys
package: com.android.settings:34
process: com.android.settings
processUptime: 210 + 259 ms

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.IllegalStateException: Property subId should be initialized before get.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Property subId should be initialized before get.
	at kotlin.properties.NotNullVar.getValue(Delegates.kt:62)
	at com.android.settings.network.telephony.gsm.AutoSelectPreferenceController.getSubId(AutoSelectPreferenceController.kt:83)
	at com.android.settings.network.telephony.gsm.AutoSelectPreferenceController.getAvailabilityStatus(AutoSelectPreferenceController.kt:97)
	at com.android.settings.core.BasePreferenceController.isAvailable(BasePreferenceController.java:260)
	at com.android.settingslib.core.AbstractPreferenceController.displayPreference(AbstractPreferenceController.java:59)
	at com.android.settings.core.BasePreferenceController.displayPreference(BasePreferenceController.java:282)
	at com.android.settings.spa.preference.ComposePreferenceController.displayPreference(ComposePreferenceController.kt:30)
	at com.android.settings.dashboard.DashboardFragment.lambda$displayResourceTilesToScreen$8(DashboardFragment.java:378)
	at com.android.settings.dashboard.DashboardFragment.$r8$lambda$dJyii1AB-wnnohgJau5iUqpyrf0(DashboardFragment.java:0)
	at com.android.settings.dashboard.DashboardFragment$$ExternalSyntheticLambda6.accept(R8$$SyntheticClass:0)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1725)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:792)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:291)
	at java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:503)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:132)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:619)
	at com.android.settings.dashboard.DashboardFragment.displayResourceTilesToScreen(DashboardFragment.java:377)
	at com.android.settings.dashboard.DashboardFragment.displayResourceTiles(DashboardFragment.java:369)
	at com.android.settings.dashboard.DashboardFragment.refreshAllPreferences(DashboardFragment.java:432)
	at com.android.settings.dashboard.DashboardFragment.onCreatePreferences(DashboardFragment.java:205)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:162)
	at com.android.settingslib.core.lifecycle.ObservablePreferenceFragment.onCreate(ObservablePreferenceFragment.java:61)
	at com.android.settings.SettingsPreferenceFragment.onCreate(SettingsPreferenceFragment.java:138)
	at com.android.settings.dashboard.DashboardFragment.onCreate(DashboardFragment.java:164)
	at com.android.settings.dashboard.RestrictedDashboardFragment.onCreate(RestrictedDashboardFragment.java:104)
	at com.android.settings.network.telephony.MobileNetworkSettings.onCreate(MobileNetworkSettings.java:332)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3095)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:516)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:274)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2102)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1997)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1940)
	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:736)
	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:723)
	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:515)
	at com.android.settings.SettingsActivity.createUiFromIntent(SettingsActivity.java:324)
	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:283)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	... 15 more

**Comment by Tjson28** [comment]
My settings app crashes in my owner profile only when trying to use the search bar. So its not just when setting up a SIM. No one has commented a fix yet. Hopefully an update will solve it?

**Comment by Tjson28** [comment]
I tried both of these things and neither fixed it. Reset app settings and cellular settings
