### ISSUE TITLE
I got a notification and it said report and brought me to this site

### ISSUE THREAD

**Issue by divi0001** [GrapheneOS/os-issue-tracker#3847]
What it put into my copy/paste

```
type: crash
osVersion: google/oriole/oriole:14/AP2A.240805.005.F1/2024080600:user/release-keys
package: com.android.vending:84212730
process: com.android.vending
processUptime: 208087445 + 394 ms
installer: com.android.vending
GmsCompatConfig version: 127

java.lang.IllegalStateException: Too many active sessions for UID 10303
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3200)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:626)
	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:812)
	at adyx.a(PG:78)
	at alsx.run(PG:277)
	at amht.ai(PG:7)
	at adyl.o(PG:1247)
	at adyl.o(PG:1383)
	at adyl.o(PG:1772)
	at adyl.o(PG:1772)
	at rwo.b(PG:105)
	at auuj.run(PG:30)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:969)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:656)
	at android.content.pm.IPackageInstaller$Stub.onTransact(IPackageInstaller.java:282)
	at android.os.Binder.execTransactInternal(Binder.java:1529)
	at android.os.Binder.execTransact(Binder.java:1468)
```

**Comment by paul-rodriguez** [comment]
Same here: 

```
type: crash
osVersion: google/cheetah/cheetah:14/AP2A.240805.005/2024080600:user/release-keys
package: com.google.android.gms:243137038
process: com.google.android.gms
processUptime: 6040 + 379 ms
installer: com.android.vending
GmsCompatConfig version: 128

java.lang.IllegalStateException: Failed to find update_engine
	at android.os.UpdateEngine.<init>(UpdateEngine.java:256)
	at dpld.<init>(:com.google.android.gms@243137038@24.31.37 (190400-662270918):16)
	at dpkz.a(:com.google.android.gms@243137038@24.31.37 (190400-662270918):3)
	at dpqv.b(:com.google.android.gms@243137038@24.31.37 (190400-662270918):29)
	at dpkn.<init>(:com.google.android.gms@243137038@24.31.37 (190400-662270918):50)
	at dpii.b(:com.google.android.gms@243137038@24.31.37 (190400-662270918):184)
	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@243137038@24.31.37 (190400-662270918):314)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243137038@24.31.37 (190400-662270918):2)
	at aisb.onHandleIntent(:com.google.android.gms@243137038@24.31.37 (190400-662270918):8)
	at ock.run(:com.google.android.gms@243137038@24.31.37 (190400-662270918):70)
	at ocj.run(:com.google.android.gms@243137038@24.31.37 (190400-662270918):152)
	at eoqc.run(:com.google.android.gms@243137038@24.31.37 (190400-662270918):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```
