### ISSUE TITLE
google app crash

### ISSUE THREAD

**Issue by msrdbbs** [GrapheneOS/os-issue-tracker#3863]
```
type: crash
osVersion: google/cheetah/cheetah:14/AP2A.240805.005/2024080600:user/release-keys
package: com.google.android.gms:242864038
process: com.google.android.gms.ui
processUptime: 91096 + 248 ms
installer: com.android.vending
GmsCompatConfig version: 128

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=intent: }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2441)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2011)
	at android.app.Activity.startActivityForResult(Activity.java:5886)
	at qhz.platform_startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at akjk.platform_startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):4)
	at qhy.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at qlz.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at qhy.public_startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at qhz.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):3)
	at android.app.Activity.startActivityForResult(Activity.java:5806)
	at qhz.platform_startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at akjk.platform_startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at qhy.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at com.google.android.chimera.android.Activity.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at qlz.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at qhy.public_startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at qhz.startActivityForResult(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at android.app.Activity.startActivity(Activity.java:6348)
	at qhz.platform_startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at akjk.platform_startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):4)
	at qhy.startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at com.google.android.chimera.android.Activity.startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at qhy.public_startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at qhz.startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):3)
	at android.app.Activity.startActivity(Activity.java:6315)
	at qhz.platform_startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at akjk.platform_startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):2)
	at qhy.startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at com.google.android.chimera.android.Activity.startActivity(:com.google.android.gms@242864038@24.28.64 (190400-657846892):1)
	at com.google.android.gms.notifications.GunsBrowserChimeraActivity.f(:com.google.android.gms@242864038@24.28.64 (190400-657846892):22)
	at cjib.shouldOverrideUrlLoading(:com.google.android.gms@242864038@24.28.64 (190400-657846892):20)
	at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:91)
	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebView6432.apk-stable-653310533:126)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by msrdbbs** [comment]
Crash on google setting account

**Comment by iotku** [comment]
Been getting an increasing amount of gms crashes as well 

```
type: crash
osVersion: google/husky/husky:14/AP2A.240805.005/2024080600:user/release-keys
package: com.google.android.gms:243137039
process: com.google.android.gms.persistent
processUptime: 11915303 + 482 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 128

java.lang.SecurityException: getPackagesForUid: UID 1010139 requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS to access user 0.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackagesForUid(IPackageManager.java:5173)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1138)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1132)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.app.ApplicationPackageManager.getPackagesForUid(ApplicationPackageManager.java:1151)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.getPackagesForUid(GmcPackageManager.java:347)
	at bzre.f(:com.google.android.gms@243137039@24.31.37 (190408-662270918):42)
	at bykv.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):258)
	at bykr.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):64)
	at amsr.c(:com.google.android.gms@243137039@24.31.37 (190408-662270918):50)
	at amsr.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at amyd.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: eoqn: 
```

**Comment by iotku** [comment]
> @iotku Please try reinstalling sandboxed Google Play.

Still noticing some periodic crashes, seems to be at the same time Duolingo is crashing (when trying to playaudio clips the app restarts), but that could be unrelated

```
type: crash
osVersion: google/husky/husky:14/AP2A.240805.005/2024080600:user/release-keys
package: com.google.android.gms:243137039
process: com.google.android.gms.persistent
processUptime: 842925 + 329 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 129

java.lang.SecurityException: getPackagesForUid: UID 1010139 requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS to access user 0.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackagesForUid(IPackageManager.java:5173)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1138)
	at android.app.ApplicationPackageManager$3.recompute(ApplicationPackageManager.java:1132)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.app.ApplicationPackageManager.getPackagesForUid(ApplicationPackageManager.java:1151)
	at com.android.internal.gmscompat.sysservice.GmcPackageManager.getPackagesForUid(GmcPackageManager.java:347)
	at bzre.f(:com.google.android.gms@243137039@24.31.37 (190408-662270918):42)
	at bzre.e(:com.google.android.gms@243137039@24.31.37 (190408-662270918):5)
	at bykv.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):997)
	at bykr.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):64)
	at amsr.c(:com.google.android.gms@243137039@24.31.37 (190408-662270918):50)
	at amsr.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at amyd.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: eoqn: 
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.ComputerEngine.enforceCrossUserOrProfilePermission(ComputerEngine.java:2826)
	at com.android.server.pm.IPackageManagerBase.getPackagesForUid(IPackageManagerBase.java:648)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2324)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6554)
	at android.os.Binder.execTransactInternal(Binder.java:1534)
```

**Comment by muhomorr** [comment]
@iotku Are you running an official unmodified GrapheneOS build?

**Comment by iotku** [comment]
> @iotku Are you running an official unmodified GrapheneOS build?

Yes for Pixel 8 pro 2024080600, seems that something is fairly broken on my end somehow given that other apps are crashing in a similar fashion.

For Duolingo if I try to start an activity and play an audio clip and the app restarts.

For X (formally twitter) just trying to launch it crashes (but doesn't restart)

Eventually after enough app crashes I get the notification about Google Play services crashing above in my notification area.

"Disabling" (via App Info) Google Play services stops the crashes (but of course brings up various complaints about it not running)

I'm using it in a secondary android profile.

I uninstalled and reinstalled play services and it works for a bit then the behavior returned
