### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SleekBeat** [GrapheneOS/os-issue-tracker#3865]
```
type: crash
osVersion: google/bluejay/bluejay:14/AP2A.240805.005.F1/2024080600:user/release-keys
package: com.google.android.gms:242835038
process: com.google.android.gms.ui
processUptime: 67880 + 492 ms
installer: com.android.vending
GmsCompatConfig version: 128

java.lang.SecurityException: Application must hold android.permission.REQUEST_COMPANION_PROFILE_COMPUTER to associate with a device with android.app.role.COMPANION_DEVICE_COMPUTER profile.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.companion.ICompanionDeviceManager$Stub$Proxy.associate(ICompanionDeviceManager.java:878)
	at android.companion.CompanionDeviceManager.associate(CompanionDeviceManager.java:501)
	at aaz$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:72)
	at com.google.android.gms.auth.proximity.phonehub.CdmAssociationChimeraActivity.onWindowFocusChanged(:com.google.android.gms@242835038@24.28.35 (190400-657754416):153)
	at qhy.public_onWindowFocusChanged(:com.google.android.gms@242835038@24.28.35 (190400-657754416):1)
	at qhz.onWindowFocusChanged(:com.google.android.gms@242835038@24.28.35 (190400-657754416):5)
	at akjk.onWindowFocusChanged(:com.google.android.gms@242835038@24.28.35 (190400-657754416):9)
	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1810)
	at android.view.View.dispatchWindowFocusChanged(View.java:16562)
	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1511)
	at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:4360)
	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:4264)
	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6406)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6305)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.companion.PermissionsUtils.enforceRequestDeviceProfilePermissions(PermissionsUtils.java:99)
	at com.android.server.companion.PermissionsUtils.enforcePermissionsForAssociation(PermissionsUtils.java:80)
	at com.android.server.companion.AssociationRequestsProcessor.processNewAssociationRequest(AssociationRequestsProcessor.java:171)
	at com.android.server.companion.CompanionDeviceManagerService$CompanionDeviceManagerImpl.associate(CompanionDeviceManagerService.java:740)
	at android.companion.ICompanionDeviceManager$Stub.onTransact(ICompanionDeviceManager.java:392)
```

**Comment by thestinger** [comment]
Associating with a companion device using Play services isn't supported.
