### ISSUE TITLE
Fido2 registration IllegalStateException

### ISSUE THREAD

**Issue by alexsapps** [GrapheneOS/os-issue-tracker#3867]
Tried registering my Identiv uTrust Fido2 usb/nfc security key via USB on Proton Mail account and got this Google Play Services crash

```
type: crash
osVersion: google/cheetah/cheetah:14/AP2A.240805.005/2024080600:user/release-keys
package: com.google.android.gms:242213038
process: com.google.android.gms.ui
processUptime: 34326 + 341 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 129

java.lang.IllegalStateException
	at eobp.q(:com.google.android.gms@242213038@24.22.13 (190400-638740827):6)
	at axiu.e(:com.google.android.gms@242213038@24.22.13 (190400-638740827):14)
	at awka.g(:com.google.android.gms@242213038@24.22.13 (190400-638740827):21)
	at com.google.android.gms.fido.fido2.ui.AuthenticateChimeraActivity.r(:com.google.android.gms@242213038@24.22.13 (190400-638740827):3)
	at axnk.onClick(:com.google.android.gms@242213038@24.22.13 (190400-638740827):23)
	at android.view.View.performClick(View.java:7931)
	at com.google.android.material.button.MaterialButton.performClick(:com.google.android.gms@242213038@24.22.13 (190400-638740827):10)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by alexsapps** [comment]
I tried again a few more times and I just got "something went wrong" from Proton Mail's UI.

I got it working with my key's NFC functionality though.

I have lots of problems with this Identiv key tbh.
