### ISSUE TITLE
GMS Compat Sandbox Google Play crashing

### ISSUE THREAD

**Issue by Boelaap74** [GrapheneOS/os-issue-tracker#3876]
I get the following error for a while now, multiple times per day. I copied the following error code:

```
type: crash
osVersion: google/sargo/sargo:12/SP2A.220505.008/2023020600:user/release-keys
package: com.google.android.gms:243137038
process: com.google.android.gms
processUptime: 20846 ms
GmsCompatConfig version: 129

java.lang.SecurityException: You need MANAGE_USERS permission to: check user type
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
	at android.os.Parcel.createException(Parcel.java:2420)
	at android.os.Parcel.readException(Parcel.java:2396)
	at android.os.Parcel.readException(Parcel.java:2338)
	at android.os.IUserManager$Stub$Proxy.isUserOfType(IUserManager.java:2295)
	at android.os.UserManager.isUserOfType(UserManager.java:2016)
	at ailg.get(:com.google.android.gms@243137038@24.31.37 (190400-662270918):27)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243137038@24.31.37 (190400-662270918):16)
	at dagger.internal.Providers$1.get(:com.google.android.gms@243137038@24.31.37 (190400-662270918):3)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243137038@24.31.37 (190400-662270918):16)
	at ailt.<init>(:com.google.android.gms@243137038@24.31.37 (190400-662270918):84)
	at ailv.get(:com.google.android.gms@243137038@24.31.37 (190400-662270918):164)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243137038@24.31.37 (190400-662270918):16)
	at aiki.a(:com.google.android.gms@243137038@24.31.37 (190400-662270918):3)
	at aiet.a(:com.google.android.gms@243137038@24.31.37 (190400-662270918):80)
	at aigd.a(:com.google.android.gms@243137038@24.31.37 (190400-662270918):189)
	at com.google.android.gms.checkin.CheckinIntentOperation.onHandleIntent(:com.google.android.gms@243137038@24.31.37 (190400-662270918):33)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243137038@24.31.37 (190400-662270918):2)
	at aisb.onHandleIntent(:com.google.android.gms@243137038@24.31.37 (190400-662270918):8)
	at ock.run(:com.google.android.gms@243137038@24.31.37 (190400-662270918):70)
	at ocj.run(:com.google.android.gms@243137038@24.31.37 (190400-662270918):152)
	at eoqc.run(:com.google.android.gms@243137038@24.31.37 (190400-662270918):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.checkManageUsersPermission(UserManagerService.java:2510)
	at com.android.server.pm.UserManagerService.isUserOfType(UserManagerService.java:1365)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1019)
	at android.os.Binder.execTransactInternal(Binder.java:1206)
	at android.os.Binder.execTransact(Binder.java:1164)


```

**Comment by AtmosphericIgnition** [comment]
Lately, I have noticed that GmsCompat, which is usually shown inside the notification shade under "1 app is active" at the bottom, has been disappearing from there every few hours. Restarting the device seems to fix the issue.

Not sure if this is related to this issue, but it sounded similar enough that I thought to leave this here.

I will post my logs for GMS when this occurs again.

**Comment by Boelaap74** [comment]
Hi, thanks for your comment. Rebooting or restarting does not seem to work to fix the issue. My phone is a Pixel 3a, and due to that it won't update Graphene unfortunately. They don't support that model anymore. Maybe that is part of the problem?
Strange thing is that while GMs Compat Sandbox Google Play crashes (as seen in screenshot) Sandbox Google Play is running without an error message. I will try to include my start screen screenshot. 
![Screenshot_20240819-162130](https://github.com/user-attachments/assets/986a3b2b-5ea0-4756-9418-81ddd7e22382)

**Comment by Boelaap74** [comment]
Thanks. If there won't be some kind of support, that's unfortunate. Device still works so that's a plus.
I will see what happens.

**Comment by Boelaap74** [comment]
Thanks for the quick reply. Much appreciated. On the lookout for a new model then.

**Comment by Boelaap74** [comment]
Thanks for your reply. You’re right in that I didn’t notice anything broke accept for the notice of the crash. I have updated my device to a Pixel 8 pro since two days ago, and have installed Graphene via the website and installed the insular app via F-droid and divide my work and private profile. Busy installing Apps again. I should be good for a few years to come. I understand that after some time old devices won’t be supported anymore, and this was somewhat sad since my old Pixel 3a was still a good working device. But since having a 8 pro it’s like comparing a bicycle to a Superbike. They all do what they suppose to do, but the latter is a nice upgrade. Thanks again for your answer, it all makes sense when explained.  Verstuurd vanaf mijn iPhoneOp 25 aug. 2024 om 04:30 heeft Daniel Micay ***@***.***> het volgende geschreven:﻿
You've been getting Play services versions beyond what's supported on a GrapheneOS release from February 2023 for a while now and just hadn't noticed that anything broke. We can consider releasing a GmsCompatConfig update for 3rd gen devices to at least silence this crash but it's far from the only issue you're going to be having. Using an old Play services version would temporarily be an option but they expect people to update it and an old version won't keep working with their services and new apps indefinitely.
