### ISSUE TITLE
GmsCompat stops showing in the running apps section

### ISSUE THREAD

**Issue by AtmosphericIgnition** [GrapheneOS/os-issue-tracker#3878]
I have sandboxed Google Play installed on my owner profile. For a while now, after roughly 4-14 hours of uptime, GmsCompat stops showing in the "Currently running apps" section of the notification shade.

I'm not sure if this is a visual bug, or if GMS is crashing, or doing something else weird in the background, but I have attached logs and screenshots. Using the latest stable GmsCompatConfig, and latest stable GrapheneOS on P8P.

Before disappearing:
![signal-2024-08-19-220705_002](https://github.com/user-attachments/assets/35fe72a5-7261-429f-b9ba-7dedceb58230)
![signal-2024-08-19-220705_003](https://github.com/user-attachments/assets/09049da6-2061-4716-9980-a4189932cd66)

After disappearing:
![signal-2024-08-19-220705_004](https://github.com/user-attachments/assets/4453f077-42d9-49a2-a8c0-8195b0a19027)

**Logs:**

GMS:

````
type: logcat
osVersion: google/husky/husky:14/AP2A.240805.005/2024080600:user/release-keys
packageName: com.google.android.gms:243137039
buffers: main,system,crash,events,kernel
level: verbose

--------- beginning of events
08-19 19:33:01.428  9279 16610 I c2dm    : [packet_type=-1,,stream_id=3,last_stream_id=2]
08-19 19:38:51.447  9279 16671 I c2dm    : [packet_type=0,,stream_id=3,last_stream_id=3]
08-19 19:41:56.499  9279 17435 I c2dm    : [packet_type=-7,,stream_id=5,last_stream_id=4]
--------- beginning of main
08-19 19:48:34.461  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.dck.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:48:34.463  9279  9279 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.cast.firstparty.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:48:34.477  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:48:34.526  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
08-19 19:48:39.488  9279  9279 I NearbyDiscovery: (REDACTED) FastPairDisplayObserver: %s -> %s
08-19 19:48:39.489  9279 17990 I NearbySharing: (REDACTED) Screen is %s
08-19 19:48:39.489  9279 17990 I NearbySharing: Stopping scanning because the screen is locked. [CONTEXT service_id=194 ]
08-19 19:48:39.490  9279 17990 I NearbySharing: Stopping Fast Init advertisement because Bluetooth is off. [CONTEXT service_id=194 ]
08-19 19:48:39.490  9279 17990 I NearbySharing: Stopping advertising because Bluetooth is disabled. [CONTEXT service_id=194 ]
08-19 19:48:39.490  9279 17990 I NearbySharing: Stopping FastInitiation scanning because the screen is locked. [CONTEXT service_id=194 ]
08-19 19:48:39.491  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:48:39.491  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:48:39.491  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:48:39.492  9279 17990 I NearbySharing: Fast Initiation Scanning has stopped [CONTEXT service_id=194 ]
08-19 19:48:39.493  9279 17990 I NearbySharing: Dismissing HUN as there's no device nearby. [CONTEXT service_id=194 ]
08-19 19:48:39.687  9279 19127 I DiscoveryManager: Filter criteria(null) scannerFlags(0)
08-19 19:48:39.699  9279  4458 I NearbyDiscovery: (REDACTED) FastPairHandler: Received action %s
08-19 19:48:39.700  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:48:39.700  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:48:39.701  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:48:39.701  9279  4458 I NearbyDiscovery: FastPairController: onSystemStateChanged: skip due to flag disabled [CONTEXT service_id=265 ]
08-19 19:48:40.402  9279 19127 I DiscoveryManager: Filter criteria(8A86881D) scannerFlags(2)
08-19 19:48:40.405  9279 19127 W DatabaseProcessor: processLocalDevices: failed to get the network info with non-null networkId.
08-19 19:48:40.405  9279  9279 I CastMediaRouteProvider: Published 0 routes
08-19 19:48:40.408  9279 19127 D TrafficStats: tagSocket(107) with statsTag=0x20000900, statsUid=-1
08-19 19:48:40.414  9279  4458 I NearbyDiscovery: (REDACTED) FastPairHandler: Received action %s
08-19 19:48:40.414  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:48:40.414  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:48:40.414  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:48:40.414  9279  4458 I NearbyDiscovery: FastPairController: onSystemStateChanged: skip due to flag disabled [CONTEXT service_id=265 ]
08-19 19:48:40.415  9279 16671 W DatabaseProcessor: processLocalDevices: failed to get the network info with non-null networkId.
08-19 19:48:40.506  9279  9279 I CastMediaRouteProvider: Published 0 routes
08-19 19:48:40.562  9279  9279 I NearbyDiscovery: (REDACTED) FastPairDisplayObserver: %s -> %s
08-19 19:48:40.564  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:48:40.564  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:48:40.565  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:48:42.170  9279  4458 I NearbyDiscovery: (REDACTED) FastPairHandler: Received action %s
08-19 19:48:42.171  9279  4458 I NearbyDiscovery: FastPairController: onSystemStateChanged: skip due to flag disabled [CONTEXT service_id=265 ]
08-19 19:48:42.171  9279  9422 I NearbySharing: (REDACTED) Screen is %s
08-19 19:48:42.173  9279  9422 I NearbySharing: Uwb feature is off. [CONTEXT service_id=194 ]
08-19 19:48:42.173  9279  9422 I NearbySharing: Uwb feature is off. [CONTEXT service_id=194 ]
08-19 19:48:42.173  9279  9422 I NearbySharing: Stopping scanning because Bluetooth is disabled. [CONTEXT service_id=194 ]
08-19 19:48:42.174  9279  9422 I NearbySharing: Stopping Fast Init advertisement because Bluetooth is off. [CONTEXT service_id=194 ]
08-19 19:48:42.174  9279  9422 I NearbySharing: Stopping advertising because Bluetooth is disabled. [CONTEXT service_id=194 ]
08-19 19:48:42.179  9279  9422 I NearbySharing: Stopping FastInitiation scanning because visibility is hidden. [CONTEXT service_id=194 ]
08-19 19:48:42.180  9279  9422 I NearbySharing: Fast Initiation Scanning has stopped [CONTEXT service_id=194 ]
08-19 19:48:42.181  9279  9422 I NearbySharing: Dismissing HUN as there's no device nearby. [CONTEXT service_id=194 ]
08-19 19:48:42.220  9279  9422 I Nearby  : (REDACTED) Beginning attempt #%d for %s...
08-19 19:48:42.222  9279  9422 I NearbyMediums: BluetoothAdapter's name was not set by Nearby Connections, ignoring call to restore default scan mode.
08-19 19:48:42.223  9279  9422 I NearbyMediums: BluetoothAdapter's name was not set by Nearby Connections, ignoring call to restore device name
08-19 19:48:42.227  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
08-19 19:48:42.227  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
08-19 19:48:42.230  3274 19413 I Dck     : (REDACTED) disableDckSupport: %s
08-19 19:48:42.230  3274 19413 I Dck     : (REDACTED) doesDeviceHaveSupportedWirelessCapabilities: wccSysProp:%d, wccMendel:%d, deviceWccOverride:%s
08-19 19:48:42.230  3274 19413 I Dck     : Dck module condition - isDckModuleEligible: true [CONTEXT service_id=289 ]
08-19 19:48:42.235  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.dck.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:48:42.235  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.dck.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:48:42.238  9279  9279 I RCNIntentOperation: RCN is disabled on this network.
08-19 19:48:42.241  3274  3320 I Dck     : (REDACTED) disableDckSupport: %s
08-19 19:48:42.241  3274  3320 I Dck     : (REDACTED) doesDeviceHaveSupportedWirelessCapabilities: wccSysProp:%d, wccMendel:%d, deviceWccOverride:%s
08-19 19:48:42.241  3274  3320 I Dck     : Dck module condition - isDckModuleEligible: true [CONTEXT service_id=289 ]
08-19 19:48:42.256  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:48:42.256  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:48:43.416  9279 16671 W AdaptiveDiscoveryWorker: Exiting Adaptive Discovery. Current NetworkInfo is NULL.
08-19 19:48:44.733  9279  9279 I NearbyDiscovery: (REDACTED) FastPairDisplayObserver: %s -> %s
08-19 19:48:44.735  9279  9422 I NearbySharing: (REDACTED) Screen is %s
08-19 19:48:44.737  9279  9422 I NearbySharing: Stopping scanning because the screen is locked. [CONTEXT service_id=194 ]
08-19 19:48:44.738  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:48:44.738  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:48:44.738  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:48:44.738  9279  9422 I NearbySharing: Stopping Fast Init advertisement because Bluetooth is off. [CONTEXT service_id=194 ]
08-19 19:48:44.739  9279  9422 I NearbySharing: Stopping advertising because Bluetooth is disabled. [CONTEXT service_id=194 ]
08-19 19:48:44.739  9279  9422 I NearbySharing: Stopping FastInitiation scanning because the screen is locked. [CONTEXT service_id=194 ]
08-19 19:48:44.742  9279  9422 I NearbySharing: Fast Initiation Scanning has stopped [CONTEXT service_id=194 ]
08-19 19:48:44.743  9279  9422 I NearbySharing: Dismissing HUN as there's no device nearby. [CONTEXT service_id=194 ]
08-19 19:48:44.972  9279 19127 I DiscoveryManager: Filter criteria(null) scannerFlags(0)
08-19 19:48:44.980  9279  4458 I NearbyDiscovery: (REDACTED) FastPairHandler: Received action %s
08-19 19:48:44.980  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:48:44.980  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:48:44.980  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:48:44.980  9279  4458 I NearbyDiscovery: FastPairController: onSystemStateChanged: skip due to flag disabled [CONTEXT service_id=265 ]
08-19 19:48:46.273  9279  9279 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.phenotype.service.START pkg=com.google.android.gms }
08-19 19:49:36.588  9279 19128 I AlarmManager: setExactAndAllowWhileIdle [name: GCM_HB_ALARM type: 2 triggerAtMillis: 45653036]
--------- switch to events
08-19 19:49:36.592  9279 19128 I c2dm    : [packet_type=0,,stream_id=6,last_stream_id=6]
--------- switch to main
08-19 19:49:36.592  9279 19128 E WakeLock: GCM_HB_ALARM release without a matched acquire!
08-19 19:49:36.608  3274 19523 I Authzen : [DeviceStateSyncManager] The server is in sync with current state. Nothing to do
08-19 19:49:36.642  9279 19127 I AlarmManager: setExactAndAllowWhileIdle [name: GCM_HB_ALARM type: 2 triggerAtMillis: 45943090]
08-19 19:50:56.123  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.dck.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:50:56.128  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:50:56.151  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
08-19 19:51:17.952  9279  9279 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.mdns.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:54:00.583  9279 19128 I AlarmManager: setExactAndAllowWhileIdle [name: GCM_HB_ALARM type: 2 triggerAtMillis: 46207031]
08-19 19:54:00.627  9279 19128 I AlarmManager: setExactAndAllowWhileIdle [name: GCM_HB_ALARM type: 2 triggerAtMillis: 46207075]
--------- switch to events
08-19 19:54:00.629  9279 19128 I c2dm    : [packet_type=-7,,stream_id=8,last_stream_id=7]
--------- switch to main
08-19 19:57:28.983  9279  9279 I NearbyDiscovery: (REDACTED) FastPairDisplayObserver: %s -> %s
08-19 19:57:28.984  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:57:28.984  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:57:28.984  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:57:28.986  9279 19672 I DiscoveryManager: Filter criteria(8A86881D) scannerFlags(2)
08-19 19:57:28.987  9279 19672 W DatabaseProcessor: processLocalDevices: failed to get the network info with non-null networkId.
08-19 19:57:28.989  9279  9279 I CastMediaRouteProvider: Published 0 routes
08-19 19:57:29.016  9279  9279 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.mdns.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:57:29.016  9279  9279 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.mdns.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:57:29.033  9279 19672 D TrafficStats: tagSocket(250) with statsTag=0x20000900, statsUid=-1
08-19 19:57:29.034  9279  4458 I NearbyDiscovery: (REDACTED) FastPairHandler: Received action %s
08-19 19:57:29.034  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
08-19 19:57:29.034  9279  4458 D BluetoothAdapter: isLeEnabled(): OFF
08-19 19:57:29.034  9279  4458 I NearbyDiscovery: (REDACTED) FastPairScanner: eventType=%s, intReq=%s, scanning=%s, scanAllowed=%s, bleEnabled=%s, lockScanRate=%s, startScanningByLowPowerMode=%s
08-19 19:57:29.034  9279  4458 I NearbyDiscovery: FastPairController: onSystemStateChanged: skip due to flag disabled [CONTEXT service_id=265 ]
08-19 19:57:29.036  9279 19673 W DatabaseProcessor: processLocalDevices: failed to get the network info with non-null networkId.
08-19 19:57:29.088  9279  9279 I CastMediaRouteProvider: Published 0 routes
08-19 19:57:31.800  9279  4458 I NearbyDiscovery: (REDACTED) FastPairHandler: Received action %s
08-19 19:57:31.801  9279  4458 I NearbyDiscovery: FastPairController: onSystemStateChanged: skip due to flag disabled [CONTEXT service_id=265 ]
08-19 19:57:31.801  9279  9422 I NearbySharing: (REDACTED) Screen is %s
08-19 19:57:31.803  9279  9422 I NearbySharing: Uwb feature is off. [CONTEXT service_id=194 ]
08-19 19:57:31.803  9279  9422 I NearbySharing: Uwb feature is off. [CONTEXT service_id=194 ]
08-19 19:57:31.803  9279  9422 I NearbySharing: Stopping scanning because Bluetooth is disabled. [CONTEXT service_id=194 ]
08-19 19:57:31.808  9279  9422 I NearbySharing: Stopping Fast Init advertisement because Bluetooth is off. [CONTEXT service_id=194 ]
08-19 19:57:31.808  9279  9422 I NearbySharing: Stopping advertising because Bluetooth is disabled. [CONTEXT service_id=194 ]
08-19 19:57:31.810  9279 19673 I AlarmManager: setExactAndAllowWhileIdle [name: FcmRetry type: 2 triggerAtMillis: 46188251]
08-19 19:57:31.812  9279  9422 I NearbySharing: Stopping FastInitiation scanning because visibility is hidden. [CONTEXT service_id=194 ]
08-19 19:57:31.814  9279  9422 I NearbySharing: Fast Initiation Scanning has stopped [CONTEXT service_id=194 ]
08-19 19:57:31.815  9279  9422 I NearbySharing: Dismissing HUN as there's no device nearby. [CONTEXT service_id=194 ]
08-19 19:57:31.858  9279  9279 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.cast.firstparty.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:57:31.858  9279  9279 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.cast.firstparty.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:57:31.867  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.dck.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:31.867  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.dck.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:31.875  3274 19788 I Dck     : (REDACTED) disableDckSupport: %s
08-19 19:57:31.875  3274 19788 I Dck     : (REDACTED) doesDeviceHaveSupportedWirelessCapabilities: wccSysProp:%d, wccMendel:%d, deviceWccOverride:%s
08-19 19:57:31.875  3274 19788 I Dck     : Dck module condition - isDckModuleEligible: true [CONTEXT service_id=289 ]
08-19 19:57:31.861  9279  9422 I Nearby  : (REDACTED) Beginning attempt #%d for %s...
08-19 19:57:31.876  9279  9279 I RCNIntentOperation: RCN is disabled on this network.
--------- switch to events
08-19 19:57:31.877  3274 19785 I service_manager_stats: [call_count=200,total_time=250ms,duration=24617.81s]
--------- switch to main
08-19 19:57:31.878  9279  9422 I NearbyMediums: BluetoothAdapter's name was not set by Nearby Connections, ignoring call to restore default scan mode.
08-19 19:57:31.881  3274  9047 I Dck     : (REDACTED) disableDckSupport: %s
08-19 19:57:31.881  3274  9047 I Dck     : (REDACTED) doesDeviceHaveSupportedWirelessCapabilities: wccSysProp:%d, wccMendel:%d, deviceWccOverride:%s
08-19 19:57:31.881  3274  9047 I Dck     : Dck module condition - isDckModuleEligible: true [CONTEXT service_id=289 ]
08-19 19:57:31.884  9279  9422 I NearbyMediums: BluetoothAdapter's name was not set by Nearby Connections, ignoring call to restore device name
08-19 19:57:31.900  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
08-19 19:57:31.900  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
08-19 19:57:31.916  9279 19673 I NetworkScheduler.Stats: (REDACTED) Task %s/%s started execution. cause:%s exec_start_elapsed_seconds: %s
08-19 19:57:31.920  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:31.920  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:31.946  9279 17989 W Sensors : Cannot get virtualdevice_native service
08-19 19:57:32.041  9279 19673 W AdaptiveDiscoveryWorker: Exiting Adaptive Discovery. Current NetworkInfo is NULL.
08-19 19:57:32.148  3274 19802 D TrafficStats: tagSocket(108) with statsTag=0x20003300, statsUid=-1
08-19 19:57:32.786  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
08-19 19:57:32.786  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
08-19 19:57:33.822  9279  9279 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.auth.account.workaccount.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:57:33.822  9279  9279 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.auth.account.workaccount.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:57:34.502  9279 19672 W NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=1809s,end=3620s,earliest=-2022s,latest=-211s} requirements=[NET_CONNECTED,PREFERRED_NET_UNMETERED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-3831s last_run=-2s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-243137000} :1 [CONTEXT service_id=218 ]
08-19 19:57:38.075  3274  3274 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.appset.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:38.075  3274  3274 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.appset.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:42.198  9279 19672 W NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=1809s,end=3620s,earliest=-2030s,latest=-219s} requirements=[NET_CONNECTED,PREFERRED_NET_UNMETERED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-3839s last_run=-10s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-243137000} :1 [CONTEXT service_id=218 ]
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: UID for network attribution might be misset for tag 536883968 [CONTEXT service_id=39 ]
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: erld: FULL
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: 	at a.T(:com.google.android.gms@243137039@24.31.37 (190408-662270918):9)
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: 	at bawl.a(:com.google.android.gms@243137039@24.31.37 (190408-662270918):150)
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: 	at buvt.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):29)
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: 	at eoqc.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):21)
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-19 19:57:42.249  3274 19802 E GmsConnectionFactory: 	at buww.run(:com.google.android.gms@243137039@24.31.37 (190408-662270918):48)
08-19 19:57:42.269  3274 19802 D TrafficStats: tagSocket(108) with statsTag=0x20003300, statsUid=-1
08-19 19:57:42.361  9279 19673 W NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=1809s,end=3620s,earliest=-2030s,latest=-219s} requirements=[NET_CONNECTED,PREFERRED_NET_UNMETERED,PREFERRED_CHARGING] attributes=[PERSISTED] scheduled=-3839s last_run=-10s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-243137000} :1 [CONTEXT service_id=218 ]
08-19 19:57:46.901  9279  9279 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.cast.firstparty.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.PersistentApiService }
08-19 19:57:46.918  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.dck.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:46.936  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
08-19 19:57:46.997  3274  3274 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
````

GmsCompat:

```
type: logcat
osVersion: google/husky/husky:14/AP2A.240805.005/2024080600:user/release-keys
packageName: app.grapheneos.gmscompat:1008
buffers: main,system,crash,events,kernel
level: verbose

--------- beginning of system
08-19 20:02:51.063  3195  3195 E ActivityThread: Package [com.google.android.apps.photos] reported as REPLACED, but missing application info. Assuming REMOVED.
08-19 20:02:51.106  3195  3195 E ActivityThread: Package [com.google.android.apps.photos] reported as REPLACED, but missing application info. Assuming REMOVED.
```

**Comment by AtmosphericIgnition** [comment]
I have developer options enabled, so I can disable Wi-Fi scan throttling. I did not change any other developer options.
