### ISSUE TITLE
system_server crash when switching from Owner to other profiles

### ISSUE THREAD

**Issue by Kinderok1** [GrapheneOS/os-issue-tracker#3888]
```
type: crash
SystemUptimeMs: 33869053
Process: system_server
Build: google/cheetah/cheetah:14/AP2A.240805.005/2024080600:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20000 ms.
 at com.android.server.am.UserController.lambda$showKeyguard$19(UserController.java:2361)
 at com.android.server.am.UserController.$r8$lambda$wT8N0XZjIuEx-KppGzSNgZ41LjE(UserController.java:0)
 at com.android.server.am.UserController$$ExternalSyntheticLambda16.run(R8$$SyntheticClass:0)
 at com.android.server.am.UserController.lambda$runWithTimeout$20(UserController.java:2381)
 at com.android.server.am.UserController.$r8$lambda$3Otwh3XBWjxmOUSz6G331crra7Q(UserController.java:0)
 at com.android.server.am.UserController$$ExternalSyntheticLambda20.run(R8$$SyntheticClass:0)
 at android.os.Handler.handleCallback(Handler.java:959)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.os.HandlerThread.run(HandlerThread.java:85)
 at com.android.server.ServiceThread.run(ServiceThread.java:46)

``
```
Hello guys, after updating to a new version of GrapheneOS (bp: 2024080600), i cant use my other profiles. Every time when i switch to other profile i have this error (system_server has crashed).

If i create a new profile then switching from Owner to this newly created profile then it works fine. This error only appears when I try to switch to old profiles that were created before the new update. The error pops up every time, it is impossible to switch to the old profiles.

I looked at old similar posts about this, but nothing helps.

Any advice? 

thanks ✌️

**Comment by Kinderok1** [comment]
updates to 2024082200, still the same issue

What if I make a backup and factory reset, and then restore from this backup. Will my accounts be saved in the applications that were logged in. For example, gmail, telegram, whatsapp or will I need to log in to all accounts again?

**Comment by Kinderok1** [comment]
**Update on my problem**

Like i said before, if i create a new user profile, then switching from Owner to this newly created profile it works fine. But if i add unlock password to this new profile, then i have the same error (impossible to switch from Owner to this new user with password)

This error is somehow related to the unlock method…

**Comment by mjholub** [comment]
It also crashes while entering and leaving lockdown mode
```
type: crash
SystemUptimeMs: 34224409
Process: system_server
Build: google/oriole/oriole:14/AP2A.240805.005.F1/2024082200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20000 ms.
	at com.android.server.am.UserController.lambda$showKeyguard$19(UserController.java:2361)
	at com.android.server.am.UserController.$r8$lambda$wT8N0XZjIuEx-KppGzSNgZ41LjE(UserController.java:0)
	at com.android.server.am.UserController$$ExternalSyntheticLambda16.run(R8$$SyntheticClass:0)
	at com.android.server.am.UserController.lambda$runWithTimeout$20(UserController.java:2381)
	at com.android.server.am.UserController.$r8$lambda$3Otwh3XBWjxmOUSz6G331crra7Q(UserController.java:0)
	at com.android.server.am.UserController$$ExternalSyntheticLambda20.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
