### ISSUE TITLE
Play store crash when pairing pixel watch.

### ISSUE THREAD

**Issue by Dafydd62** [GrapheneOS/os-issue-tracker#3890]
```
type: crash
osVersion: google/raven/raven:14/AP2A.240805.005.F1/2024080600:user/release-keys
package: com.google.android.gms:243233038
process: com.google.android.gms.ui
processUptime: 7992 + 219 ms
installer: com.android.vending
GmsCompatConfig version: 130

java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10147 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.app.ContextImpl.enforce(ContextImpl.java:2396)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2424)
	at android.content.ContextWrapper.enforceCallingOrSelfPermission(ContextWrapper.java:984)
	at com.android.bluetooth.Utils.enforceBluetoothPrivilegedPermission(Utils.java:493)
	at com.android.bluetooth.Utils.enforceBluetoothPrivilegedPermissionOrAndroidAuto(Utils.java:500)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setPairingConfirmation(AdapterService.java:3684)
	at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.setPairingConfirmation(AdapterService.java:3663)
	at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:1387)
	at android.os.Binder.execTransactInternal(Binder.java:1534)
	at android.os.Binder.execTransact(Binder.java:1468)
	Suppressed: eoye: 
```

**Comment by Dafydd62** [comment]
I was just pairing my watch to the Pixel 6 Pro and my phone repeatedly
stated Play Services crashed.
I was nit doing anything else!

**Comment by oliver-rawden** [comment]
Same, I have this exact issue on the pixel watch when pairing with my pixel 7a. I have installed wear is app, google app, play services and the watch app with full permissions and I still get this error. Is there any fix for it?

**Comment by muhomorr** [comment]
Check whether this issue still occurs with GmsCompatConfig 136.
