### ISSUE TITLE
crash after updating to play services

### ISSUE THREAD

**Issue by lefuglyduck** [GrapheneOS/os-issue-tracker#3900]
```
type: crash
osVersion: google/panther/panther:14/UQ1A.240105.004/2024011600:user/release-keys
package: com.google.android.gms:243161038
process: com.google.android.gms
processUptime: 13268 + 196 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 130

java.lang.IllegalStateException: Failed to find update_engine
	at android.os.UpdateEngine.<init>(UpdateEngine.java:252)
	at dplc.<init>(:com.google.android.gms@243161038@24.31.61 (190400-661400885):16)
	at dpky.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):3)
	at dpqu.b(:com.google.android.gms@243161038@24.31.61 (190400-661400885):29)
	at dpkm.<init>(:com.google.android.gms@243161038@24.31.61 (190400-661400885):50)
	at dpih.b(:com.google.android.gms@243161038@24.31.61 (190400-661400885):184)
	at dpij.apply(:com.google.android.gms@243161038@24.31.61 (190400-661400885):102)
	at com.google.android.gms.update.execution.InstallationEventIntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):111)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):2)
	at aisb.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):8)
	at ock.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):70)
	at ocj.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):152)
	at eoqb.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by muhomorr** [comment]
Is this a recurring crash?
