### ISSUE TITLE
Sandboxed Google Play crashed notifications after upgrade

### ISSUE THREAD

**Issue by kuchtamartin** [GrapheneOS/os-issue-tracker#3902]
After yesterday's upgrade to Google Play Services 21.41.61 (190400-661400885) I am constantly getting Sandboxed Google Play crashed notifications. Everything seems to be working fine. Tried re-installing both Google Play Services and Google Play Store but the issue persists.

I am on unsupported device so if that is the cause, is there any way to roll back to previous version please?

```
type: crash
osVersion: google/sargo/sargo:12/SP2A.220505.008/2023020600:user/release-keys
package: com.google.android.gms:243161038
process: com.google.android.gms
processUptime: 101949 ms
GmsCompatConfig version: 130

java.lang.SecurityException: You need MANAGE_USERS permission to: check user type
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
	at android.os.Parcel.createException(Parcel.java:2420)
	at android.os.Parcel.readException(Parcel.java:2396)
	at android.os.Parcel.readException(Parcel.java:2338)
	at android.os.IUserManager$Stub$Proxy.isUserOfType(IUserManager.java:2295)
	at android.os.UserManager.isUserOfType(UserManager.java:2016)
	at ailg.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):27)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):16)
	at dagger.internal.Providers$1.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):3)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):16)
	at ailt.<init>(:com.google.android.gms@243161038@24.31.61 (190400-661400885):84)
	at ailv.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):164)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):16)
	at aiki.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):3)
	at aiet.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):80)
	at aigd.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):189)
	at com.google.android.gms.checkin.CheckinIntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):33)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):2)
	at aisb.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):8)
	at ock.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):70)
	at ocj.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):152)
	at eoqb.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.checkManageUsersPermission(UserManagerService.java:2510)
	at com.android.server.pm.UserManagerService.isUserOfType(UserManagerService.java:1365)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1019)
	at android.os.Binder.execTransactInternal(Binder.java:1206)
	at android.os.Binder.execTransact(Binder.java:1164)


```

**Comment by kuchtamartin** [comment]
Thank you very much. I would appreciate removing the warning. This is a daily driver in the family and it will get replaced with a newer Pixel as soon as possible.
