### ISSUE TITLE
Sandboxed Google Play Crashed Pixel 3 XL Multiple times an hour since update.

### ISSUE THREAD

**Issue by dmarsh2998** [GrapheneOS/os-issue-tracker#3906]
```
type: crash
osVersion: google/crosshatch/crosshatch:12/SP1A.210812.016.C2/2023020600:user/release-keys
package: com.google.android.gms:243161038
process: com.google.android.gms
processUptime: 1548786 ms
GmsCompatConfig version: 131

java.lang.SecurityException: You need MANAGE_USERS permission to: check user type
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
	at android.os.Parcel.createException(Parcel.java:2420)
	at android.os.Parcel.readException(Parcel.java:2396)
	at android.os.Parcel.readException(Parcel.java:2338)
	at android.os.IUserManager$Stub$Proxy.isUserOfType(IUserManager.java:2295)
	at android.os.UserManager.isUserOfType(UserManager.java:2016)
	at ailg.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):27)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):16)
	at dagger.internal.Providers$1.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):3)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):16)
	at ailt.<init>(:com.google.android.gms@243161038@24.31.61 (190400-661400885):84)
	at ailv.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):164)
	at dagger.internal.DoubleCheck.get(:com.google.android.gms@243161038@24.31.61 (190400-661400885):16)
	at aiki.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):3)
	at aiet.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):80)
	at aigd.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):189)
	at com.google.android.gms.checkin.CheckinIntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):33)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):2)
	at aisb.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):8)
	at ock.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):70)
	at ocj.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):152)
	at eoqb.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.checkManageUsersPermission(UserManagerService.java:2510)
	at com.android.server.pm.UserManagerService.isUserOfType(UserManagerService.java:1365)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1019)
	at android.os.Binder.execTransactInternal(Binder.java:1201)
	at android.os.Binder.execTransact(Binder.java:1164)


```

**Comment by dmarsh2998** [comment]
How do I revert back to a working system, or turn off/disable the notifications. Can not upgrade device, financial.

**Comment by dmarsh2998** [comment]
Can you point me to a old version with a link and some instruction please. I really need a temp workaround. Also please consider releasing a GmsCompatConfig update for 3rd gen devices.

Thank you for your help!

**Comment by dmarsh2998** [comment]
Thank you very much for your help.  Do you think Calyx would be a better option on this device? It seems to be still supported.

**Comment by dmarsh2998** [comment]
One of my banking apps quit working. Are there any work around's? Thank you for your help. Here is a copy of play store issues.


```
type: ANR
osVersion: google/crosshatch/crosshatch:12/SP1A.210812.016.C2/2023020600:user/release-keys
package: com.android.vending:84333230
process: com.android.vending

activity: null
cause: ANR Broadcast of Intent { act=com.android.vending.DOWNLOAD_SERVICE_LOGGING flg=0x10 cmp=com.android.vending/com.google.android.finsky.notification.impl.NotificationReceiver (has extras) }
info: ANR in com.android.vending
PID: 3527
Reason: Broadcast of Intent { act=com.android.vending.DOWNLOAD_SERVICE_LOGGING flg=0x10 cmp=com.android.vending/com.google.android.finsky.notification.impl.NotificationReceiver (has extras) }
Frozen: false
Load: 1.37 / 1.23 / 0.81
----- Output from /proc/pressure/memory -----
some avg10=0.44 avg60=1.53 avg300=0.78 total=56083929
full avg10=0.22 avg60=1.00 avg300=0.50 total=37877415
----- End output from /proc/pressure/memory -----

CPU usage from 0ms to 7246ms later (2024-11-05 18:25:01.876 to 2024-11-05 18:25:09.123):
  39% 3373/com.google.android.inputmethod.latin: 25% user + 13% kernel / faults: 32278 minor 1495 major
  34% 1500/system_server: 19% user + 15% kernel / faults: 37226 minor 2112 major
  13% 143/kswapd0: 0% user + 13% kernel
  9% 2082/com.android.systemui: 5.4% user + 3.5% kernel / faults: 8139 minor 1372 major
  6.1% 12516/org.futo.voiceinput: 3.5% user + 2.6% kernel / faults: 6334 minor 1648 major
  4.5% 6240/im.molly.app.unifiedpush: 2.1% user + 2.3% kernel / faults: 165 minor 113 major
  2.4% 14405/kworker/u16:13: 0% user + 2.4% kernel
  2% 6649/org.thoughtcrime.securesms: 0.9% user + 1% kernel / faults: 44 minor 33 major
  2% 14235/kworker/u16:15: 0% user + 2% kernel
  1.9% 743/surfaceflinger: 0.6% user + 1.2% kernel / faults: 238 minor 9 major
  1.7% 14796/kworker/u16:19: 0% user + 1.7% kernel
  0% 1162/media.extractor: 0% user + 0% kernel / faults: 3248 minor 53 major
  1.5% 3231/com.google.android.gms: 0.8% user + 0.6% kernel / faults: 689 minor 498 major
  1.3% 2389/com.android.phone: 0.6% user + 0.6% kernel / faults: 3110 minor 1732 major
  1% 14016/kworker/u16:3: 0% user + 1% kernel
  0.9% 869/netd: 0.5% user + 0.4% kernel / faults: 230 minor 99 major
  0% 1190/media.swcodec: 0% user + 0% kernel / faults: 2369 minor 32 major
  0.9% 2361/com.android.networkstack.process: 0.4% user + 0.5% kernel / faults: 2710 minor 1364 major
  0.8% 694/lmkd: 0.4% user + 0.4% kernel
  0% 2254/.dataservices: 0% user + 0% kernel / faults: 2914 minor 1964 major
  0% 2340/com.qualcomm.qti.telephonyservice: 0% user + 0% kernel / faults: 2743 minor 2203 major
  0% 2376/com.android.se: 0% user + 0% kernel / faults: 2786 minor 2296 major
  0% 3421/com.android.nfc: 0% user + 0% kernel / faults: 2593 minor 1816 major
  0% 3455/com.android.ims.rcsservice: 0% user + 0% kernel / faults: 2703 minor 2059 major
  0.5% 693/logd: 0.4% user + 0.1% kernel / faults: 195 minor 74 major
  0% 1178/media.codec: 0% user + 0% kernel / faults: 1908 minor 44 major
  0.5% 2544/com.android.launcher3: 0.2% user + 0.2% kernel / faults: 528 minor 196 major
  0.5% 14803/app.vanadium.browser: 0.1% user + 0.4% kernel / faults: 111 minor 85 major
  0.4% 14005/kworker/u16:0: 0% user + 0.4% kernel
  0.2% 7/rcu_preempt: 0% user + 0.2% kernel
  0.2% 21/rcuop/1: 0% user + 0.2% kernel
  0.2% 61/rcuop/6: 0% user + 0.2% kernel
  0.2% ***@***.***: 0% user + 0.2% kernel / faults: 16 minor 15 major
  0% 808/tombstoned: 0% user + 0% kernel / faults: 185 minor 68 major
  0.2% 906/statsd: 0% user + 0.2% kernel / faults: 75 minor 38 major
  0.2% ***@***.***: 0.1% user + 0.1% kernel / faults: 62 minor 66 major
  0.2% 10757/com.skemailmobileapp: 0% user + 0.2% kernel / faults: 294 minor 203 major
  0.2% 13704/us.spotco.fennec_dos: 0% user + 0.2% kernel / faults: 193 minor 108 major
  0% 13867/us.spotco.fennec_dos:gpu: 0% user + 0% kernel / faults: 28 minor 52 major
  0.2% 14394/kworker/u16:12: 0% user + 0.2% kernel
  0.2% 15258/app.grapheneos.apps: 0% user + 0.2% kernel / faults: 165 minor 39 major
  0.1% 6/ksoftirqd/0: 0% user + 0.1% kernel
  0% 8/rcu_sched: 0% user + 0% kernel
  0.1% 10/rcuop/0: 0% user + 0.1% kernel
  0% 13/migration/0: 0% user + 0% kernel
  0% 25/migration/2: 0% user + 0% kernel
  0.1% 29/rcuop/2: 0% user + 0.1% kernel
  0.1% 45/rcuop/4: 0% user + 0.1% kernel
  0% 50/ksoftirqd/5: 0% user + 0% kernel
  0.1% 69/rcuop/7: 0% user + 0.1% kernel
  0% 70/rcuos/7: 0% user + 0% kernel
  0.1% 104/system: 0% user + 0.1% kernel
  0% 207/IPCRTR_mpss_sme: 0% user + 0% kernel
  0% 642/kworker/1:1H: 0% user + 0% kernel
  0% 669/kworker/5:1H: 0% user + 0% kernel
  0.1% 672/ueventd: 0.1% user + 0% kernel / faults: 74 minor 66 major
  0.1% 695/servicemanager: 0.1% user + 0% kernel / faults: 8 minor 8 major
  0.1% 709/sugov:0: 0% user + 0.1% kernel
  0.1% 710/sugov:4: 0% user + 0.1% kernel
  0% 725/vold: 0% user + 0% kernel / faults: 174 minor 99 major
  0.1% 735/keystore2: 0% user + 0.1% kernel / faults: 22 minor 31 major
  0.1% ***@***.***: 0% user + 0.1% kernel / faults: 14 minor 15 major
  0% ***@***.***: 0% user + 0% kernel / faults: 281 minor 271 major
  0% 977/pixelstats-vendor: 0% user + 0% kernel / faults: 117 minor 98 major
  0% ***@***.***: 0% user + 0% kernel / faults: 40 minor 33 major
  0.1% 1023/msm_irqbalance: 0% user + 0.1% kernel / faults: 1 minor 1 major
  0.1% 1031/audioserver: 0% user + 0.1% kernel / faults: 50 minor 27 major
  0.1% 1106/cnd: 0% user + 0.1% kernel / faults: 39 minor 18 major
  0.1% 1117/netmgrd: 0% user + 0.1% kernel / faults: 2 major
  0% 1127/port-bridge: 0% user + 0% kernel / faults: 1 major
  0% 1146/cameraserver: 0% user + 0% kernel / faults: 39 minor 27 major
  0% 1158/installd: 0% user + 0% kernel / faults: 312 minor 138 major
  0% 1164/media.metrics: 0% user + 0% kernel / faults: 162 minor 62 major
  0% 1174/mediaserver: 0% user + 0% kernel / faults: 162 minor 72 major
  0.1% 2714/com.google.android.gms.persistent: 0% user + 0.1% kernel / faults: 69 minor 25 major
  0.1% 3510/com.windscribe.vpn: 0% user + 0.1% kernel / faults: 30 minor 34 major
  0.1% 14389/kworker/1:2: 0% user + 0.1% kernel
  0.1% 14905/app.vanadium.browser:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0: 0.1% user + 0% kernel / faults: 45 minor 3 major
  0.1% 14969/kworker/0:0: 0% user + 0.1% kernel
  0.1% 15324/com.android.permissioncontroller: 0% user + 0.1% kernel / faults: 161 minor 434 major
 +0% 15472/dex2oat32: 0% user + 0% kernel
 +0% 15532/kworker/3:3: 0% user + 0% kernel
70% TOTAL: 52% user + 12% kernel + 4.2% iowait + 1.3% irq + 0.5% softirq
CPU usage from 50ms to 403ms later (2024-11-05 18:25:01.926 to 2024-11-05 18:25:02.279) with 99% awake:
  130% 3527/com.android.vending: 55% user + 75% kernel / faults: 2315 minor 371 major
    63% 3827/bgExecutor #1: 27% user + 35% kernel
    23% 3527/android.vending: 7.9% user + 15% kernel
    11% 3840/bgExecutor #3: 7.9% user + 3.9% kernel
    7.9% 3833/bgExecutor #2: 3.9% user + 3.9% kernel
    3.9% 3817/bgExecutor #0: 3.9% user + 0% kernel
   +0% 15454/BlockingExecuto: 0% user + 0% kernel
   +0% 15455/BlockingExecuto: 0% user + 0% kernel
   +0% 15456/Db-frosting.db: 0% user + 0% kernel
   +0% 15457/AssetModuleBack: 0% user + 0% kernel
   +0% 15458/InstallQueueDat: 0% user + 0% kernel
   +0% 15459/InstallQueueUsi: 0% user + 0% kernel
   +0% 15460/Db-scheduler_ma: 0% user + 0% kernel
   +0% 15461/VerifyAppsDataS: 0% user + 0% kernel
   +0% 15462/-verify_apps.db: 0% user + 0% kernel
   +0% 15463/Db-notification: 0% user + 0% kernel
  88% 1500/system_server: 42% user + 46% kernel / faults: 627 minor 15 major
    32% 15452/Thread-96: 14% user + 17% kernel
    24% 15451/AnrConsumer: 7.1% user + 17% kernel
    7.1% 6496/Binder:1500_11: 3.5% user + 3.5% kernel
    7.1% 10067/Binder:1500_17: 7.1% user + 0% kernel
    3.5% 1837/Binder:1500_3: 3.5% user + 0% kernel
    3.5% 2282/Binder:1500_8: 0% user + 3.5% kernel
  46% 143/kswapd0: 0% user + 46% kernel
  19% 3231/com.google.android.gms: 11% user + 7.6% kernel / faults: 455 minor 282 major
    15% 3276/highpool[2]: 11% user + 3.8% kernel
    3.8% 5689/lowpool[5]: 3.8% user + 0% kernel
  2.8% 21/rcuop/1: 0% user + 2.8% kernel
  2.8% 61/rcuop/6: 0% user + 2.8% kernel
  3.2% 694/lmkd: 3.2% user + 0% kernel
  3.2% 710/sugov:4: 0% user + 3.2% kernel
  3.9% 6240/im.molly.app.unifiedpush: 3.9% user + 0% kernel / faults: 1 minor
    3.9% 6240/app.unifiedpush: 3.9% user + 0% kernel
  4.1% 14005/kworker/u16:0: 0% user + 4.1% kernel
  4.3% 15110/com.android.vending:background: 4.3% user + 0% kernel / faults: 1 minor
53% TOTAL: 14% user + 22% kernel + 13% iowait + 1.8% irq + 1% softirq

```

**Comment by dmarsh2998** [comment]
I'm not able to get a supported device at this time. Could you please recomended another option of OS until I can replace my device.

Thank You

**Comment by dmarsh2998** [comment]
```
type: crash
osVersion: google/crosshatch/crosshatch:12/SP1A.210812.016.C2/2023020600:user/release-keys
package: com.google.android.gms:244034029
process: com.google.android.gms.ui
processUptime: 1666 ms
GmsCompatConfig version: 150

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at ***@***.***@24.40.34 (190400-682300402):34)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.SecurityException: You need MANAGE_USERS permission to: Cannot get seed account information
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2436)
	at android.os.Parcel.createException(Parcel.java:2420)
	at android.os.Parcel.readException(Parcel.java:2396)
	at android.os.Parcel.readException(Parcel.java:2338)
	at android.os.IUserManager$Stub$Proxy.getSeedAccountOptions(IUserManager.java:3033)
	at android.os.UserManager.getSeedAccountOptions(UserManager.java:3292)
	at ***@***.***@24.40.34 (190400-682300402):16)
	at ***@***.***@24.40.34 (190400-682300402):3)
	at ***@***.***@24.40.34 (190400-682300402):1)
	at ***@***.***@24.40.34 (190400-682300402):3)
	at ***@***.***@24.40.34 (190400-682300402):16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

```
