### ISSUE TITLE
Unable to save the image, error occurred during: FILE_CREATION

### ISSUE THREAD

**Issue by scottdevin** [GrapheneOS/os-issue-tracker#3936]
Sadly, I can’t save screenshots or save files or photos on a new user. I get this error when attempting to save a photo. Unable to save the image, error occurred during: FILE_CREATION

**Comment by scottdevin** [comment]
Hey, thanks for the fast reply!

I created a new user profile. When I use it I am unable to save photos or files. If I take a photo from the stock camera app this is what appears on the screen!![image](https://github.com/user-attachments/assets/c6a29c40-cf40-45b8-b69a-1cd440949232)

**Comment by scottdevin** [comment]
Google Pixel 6A 
Build number: 202408220![image](https://github.com/user-attachments/assets/4b242a08-863f-4140-89f5-83e885ed4dca)

**Comment by scottdevin** [comment]
![image](https://github.com/user-attachments/assets/d9525b83-076b-4e33-afd5-8939b96061ca)

**Comment by aexyzk** [comment]
I was able to replicate this error, it seems to only happens to a 25th user. (not including the admin user) I suspect each user has a pre-allocated amount of storage (so one user can't use up all the actual storage)
both me and op have 128GiB

(I don't know if this is helpful info or not, but here it is non the less)

Pixel 6
Android 14
2024082200

**Comment by hungrymike** [comment]
My bad, deleting users AND rebooting the device seems to fix it.

**Comment by scottdevin** [comment]
Reboot my just restarting the device or factory reset?

**Comment by hungrymike** [comment]
To clarify - I also had the issue mentioned above with around 20+ users, couldn't save any files on new users. Previous users worked just fine. Deleting old users didn't help, however - after a restart and adding new users, they could then save files.

**Comment by melih12345** [comment]
I am experiencing the same issue. Have you found a solution? Photos don't appear in the gallery, and I can't take pictures.

**Comment by kokoskiwi** [comment]
i have the same problem
pixel 7 graphene os

**Comment by kokoskiwi** [comment]
i also cant save pics from telegram whatsapp camera

i have this problem on multiple user profiles. and i can’t erase these profiles cuz i have lots of accounts on them i can’t move

![Image](https://github.com/user-attachments/assets/200a4e3c-b504-44bf-bb98-fb77d0395f6c)
![Image](https://github.com/user-attachments/assets/08dafb90-9076-4eea-88da-c372d276fff8)
![Image](https://github.com/user-attachments/assets/a73dceb6-74a4-4e49-9995-96e45464165b)

**Comment by micson83** [comment]
Pretty sure it's still related to disk space, perhaps each profile too up too much space.

**Comment by dixommm** [comment]
I'm also having this issue, it started at 20+ profiles
Deleting and creating new users is not helping.
Device restart also doesn't help.
Can't do factory reset because of other profiles
I tried creating 20+ profiles and same issue on all 20+, there is 80GBs of free space and I'm using Pixel 7

This isn't photos issue only, seems that storage is messed up because I can't download anything from Vanadium.
New user acts like storage space doesn't exist and there's more than enough free space

**Comment by hungrymike** [comment]
As described, the limit would still be around 20 profile. So again, by removing unused profiles AND REBOOTING, you can make new ones without the disk issues.

I'm still guessing certain disk space is allocated per profile, hence you can't go above the 20-23 profiles.

**Comment by kokoskiwi** [comment]
> More logs from the other type of broken user that strncat believes is related to this:
> 
> [Launcher logs.txt](https://github.com/user-attachments/files/20745474/Launcher.logs.txt)
> 
> Clearing the launcher storage fixed it, but it is probably somehow connected to this.

Hi @kasia125 How can i fix this problem? i still have it. Where can i clear the launcher storage?
https://discuss.grapheneos.org/d/20813-unable-to-save-the-image-error-occurred-during-file-creation/10

**Comment by kokoskiwi** [comment]
i resetted my entire pixel phone
started from scratch again

now i have this error again 😭

**Comment by JavierMartinz** [comment]
I cannot take screenshots in profiles starting from 24th. I mean the first 23 profiles created can take screenshots, but any profile I create onwards... it doesn't work. I'm using latest build. I cannot download any image using Vanadium either

<img width="701" height="1561" alt="Image" src="https://github.com/user-attachments/assets/bb88cd53-31ef-427f-abd8-2540bc4f1773" />

**Comment by JavierMartinz** [comment]
Still happening with last release 

<img width="701" height="1563" alt="Image" src="https://github.com/user-attachments/assets/0ff35144-490e-41d7-9a40-7df925578c02" />

**Comment by inthewaves** [comment]
If you're encountering this issue, please go to Settings > Apps > All apps. In the top-right, tap on Show system, and then search for Media picker and open it. It should look like this:

<img src="https://github.com/user-attachments/assets/1778cf22-583a-4384-a661-7aa898eff277" width=40%/>

Try to take a screenshot on this page, then after the failure notification pops up, go to View logs and let me know if there are any errors there, particularly any errors that involve `getxattr` or `ENODATA`

**Comment by kasia-de** [comment]
> If you're encountering this issue, please go to Settings > Apps > All apps. In the top-right, tap on Show system, and then search for Media picker and open it. It should look like this:
> [...]
> 
> Try to take a screenshot on this page, then after the failure notification pops up, go to View logs and let me know if there are any errors there, particularly any errors that involve `getxattr` or `ENODATA`

Based on your request, I went ahead and did the following:
1) Went to settings > media picker
2) Captured the existing logs
3) Returned
4) Plugged in a USB drive
5) Captured logs
6) Took the screenshot
7) waited for a failure
8) Captured logs
9) Returned to the primary profile
10) captured system logs

The logs from before and after these operations all had getxattr ENODATA logs.

The initial logs had 223 logs of this.
```
$ grep -iF -- ENODATA 'Media picker log (1).txt' | wc -l
223
```

However, there was only one additional log about these after the operations:

```
$ diff <(grep -iF -- getxattr 'Media picker log (1).txt') <(grep -iF -- getxattr 'Media picker log (3).txt')
223a224
> 12-20 10:24:11.442 10066 10172 E MediaProvider: Xattr:user.extdbnextrowid20 not found on external storage: android.system.ErrnoException: getxattr failed: ENODATA (No data available)
```

Please give me a while to upload logs

**Comment by kasia-de** [comment]
Ah! The logs from media picker appear tiny in an unaffected profile vs. an affected profile.

The issue is clearly present long before the screenshot

**Comment by kasia-de** [comment]
There were xattr errors besides the `ENODATA`:

Maybe this is the whole issue?

Sliced out:
```
12-20 10:23:08.977 10066 10217 D DatabaseBackupAndRecovery: xattr set to 937ae487-9084-4829-92e6-af5507d14796 for key:user.extdbsessionid20 on path: /data/user/20/com.android.providers.media.module/databases/external.db.
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: Failed to set xattr:user.extdbsessionid20 to 937ae487-9084-4829-92e6-af5507d14796 for path: /data/media/0.
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: android.system.ErrnoException: setxattr failed: E2BIG (Argument list too long)
```

Full error:
```
12-20 10:23:08.971 10066 10217 W DatabaseBackupAndRecovery: Exception encountered while reading xattr:user.extdbsessionid20 from path:/data/media/0.
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: Failed to set xattr:user.extdbnextrowid20 to 1000001000 for path: /data/media/0.
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: android.system.ErrnoException: setxattr failed: E2BIG (Argument list too long)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.Linux.setxattr(Native Method)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.ForwardingOs.setxattr(ForwardingOs.java:822)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.BlockGuardOs.setxattr(BlockGuardOs.java:493)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.ForwardingOs.setxattr(ForwardingOs.java:822)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.system.Os.setxattr(Os.java:838)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseBackupAndRecovery.setXattr(DatabaseBackupAndRecovery.java:993)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.backupNextRowId(DatabaseHelper.java:2549)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.tryRecoverDatabase(DatabaseHelper.java:626)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.onOpen(DatabaseHelper.java:580)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:451)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:339)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.setFilterVolumeNames(DatabaseHelper.java:342)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.MediaProvider.lambda$updateVolumes$0(MediaProvider.java:606)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.MediaProvider.$r8$lambda$FfC0eTN4zVrvwLZaOM_Ga9D5kJw(MediaProvider.java:0)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.MediaProvider$$ExternalSyntheticLambda11.run(R8$$SyntheticClass:0)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Handler.handleCallback(Handler.java:1070)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Handler.dispatchMessage(Handler.java:125)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Looper.dispatchMessage(Looper.java:333)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Looper.loopOnce(Looper.java:263)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Looper.loop(Looper.java:367)
12-20 10:23:08.975 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.HandlerThread.run(HandlerThread.java:139)
12-20 10:23:08.977 10066 10217 D DatabaseBackupAndRecovery: xattr set to 937ae487-9084-4829-92e6-af5507d14796 for key:user.extdbsessionid20 on path: /data/user/20/com.android.providers.media.module/databases/external.db.
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: Failed to set xattr:user.extdbsessionid20 to 937ae487-9084-4829-92e6-af5507d14796 for path: /data/media/0.
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: android.system.ErrnoException: setxattr failed: E2BIG (Argument list too long)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.Linux.setxattr(Native Method)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.ForwardingOs.setxattr(ForwardingOs.java:822)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.BlockGuardOs.setxattr(BlockGuardOs.java:493)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at libcore.io.ForwardingOs.setxattr(ForwardingOs.java:822)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.system.Os.setxattr(Os.java:838)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseBackupAndRecovery.setXattr(DatabaseBackupAndRecovery.java:993)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.updateSessionIdInDatabaseAndExternalStorage(DatabaseHelper.java:740)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.tryRecoverDatabase(DatabaseHelper.java:627)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.onOpen(DatabaseHelper.java:580)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:451)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:339)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.DatabaseHelper.setFilterVolumeNames(DatabaseHelper.java:342)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.MediaProvider.lambda$updateVolumes$0(MediaProvider.java:606)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.MediaProvider.$r8$lambda$FfC0eTN4zVrvwLZaOM_Ga9D5kJw(MediaProvider.java:0)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at com.android.providers.media.MediaProvider$$ExternalSyntheticLambda11.run(R8$$SyntheticClass:0)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Handler.handleCallback(Handler.java:1070)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Handler.dispatchMessage(Handler.java:125)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Looper.dispatchMessage(Looper.java:333)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Looper.loopOnce(Looper.java:263)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.Looper.loop(Looper.java:367)
12-20 10:23:08.978 10066 10217 E DatabaseBackupAndRecovery: 	at android.os.HandlerThread.run(HandlerThread.java:139)
12-20 10:23:08.978 10066 10217 V MediaProvider: onOpen() finished for external.db
```

**Comment by kasia-de** [comment]
Logs:

[Media picker log (1).txt](https://github.com/user-attachments/files/24271533/Media.picker.log.1.txt)
[Media picker log (2).txt](https://github.com/user-attachments/files/24271534/Media.picker.log.2.txt)
[Media picker log (3).txt](https://github.com/user-attachments/files/24271535/Media.picker.log.3.txt)

**Comment by kokoskiwi** [comment]
i have the same bug too on over 20 pixel 7 with grapheneos

yes i have twenty of these phones

**Comment by olejenek500-web** [comment]
Have same bug on every profile i create after 20 on pixel 6 . Can u fix that , we reealy need to have 31 profiles.

**Comment by olejenek500-web** [comment]
googile pixel 9a have the same bug?

**Comment by olejenek500-web** [comment]
is it fixed?

**Comment by JavierMartinz** [comment]
still happening

**Comment by rsmanning** [comment]
Same issue, only three profiles and it's not the primary. I'd give you a screenshot of the error occurring but...

**Comment by inthewaves** [comment]
I reported this issue to Google because it can also occur on stock Pixel OS, and Google responded that they've fixed it for a future Android release. It's not clear what Android version the fix will be in, especially since AOSP only releases source code twice a year now in Q2 and Q4.
