### ISSUE TITLE
Sandboxed Google Play crashed

### ISSUE THREAD

**Issue by mberloww** [GrapheneOS/os-issue-tracker#3940]
As described in the title. 
"Report to developers" brought me here. Any assistance appreciated.

**Background:**
One day a couple of weeks ago this error appeared for the first time out of nowhere. I don't think I installed anything recently.

Initially everything except one app worked anyway so I ignored the error message.

Then to get that one app working again I uninstalled Google Play Services, and reinstalled from GrapheneOS app store.

The same error appeared, so I cleared the Google Play App Store cache, restarted, but no change. 

Then I uninstalled and reinstalled the Play Store. No change. 

**Current situation:**
Currently every Google app I open says "won't run without Google Play services, which are not supported by your device". 
The play services crash notification comes up very frequently now whereas before it was just once on restart. Seems to have "fully" crashed now while before it was "partial"?

`````

**Comment by mberloww** [comment]
`````
type: crash
osVersion: google/raven/raven:14/UP1A.231105.003/2023111500:user/release-keys
package: com.google.android.gms:243161038
process: com.google.android.gms
processUptime: 1556 + 287 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 133

java.lang.NullPointerException: Attempt to invoke direct method 'boolean android.os.RecoverySystem.requestLskf(java.lang.String, android.content.IntentSender)' on a null object reference
	at android.os.RecoverySystem.prepareForUnattendedUpdate(RecoverySystem.java:746)
	at com.google.android.gms.update.control.DeviceControl.g(:com.google.android.gms@243161038@24.31.61 (190400-661400885):34)
	at com.google.android.gms.update.control.InstallationControl.v(:com.google.android.gms@243161038@24.31.61 (190400-661400885):48)
	at dphk.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):913)
	at com.google.android.gms.update.control.ReceiverIntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):91)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):2)
	at aisb.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):8)
	at ock.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):70)
	at ocj.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):152)
	at eoqb.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
````

**Comment by mberloww** [comment]
![Screenshot_20240831-202128](https://github.com/user-attachments/assets/1ae35dca-79d6-49c0-a2f5-84082bfa43c1)

**Comment by mberloww** [comment]
Reinstalling Play Store from the GrapheneOS app store ("all packages" menu) worked. 
The issues seem fully resolved now.

**Comment by kmeaw** [comment]
I can reproduce this issue on a recent (I did a repo sync yesterday) build:
```
type: crash
osVersion: google/bluejay/bluejay:14/AP2A.240805.005.F1/2024083101:user/release-keys
package: com.google.android.gms:243161038
process: com.google.android.gms
processUptime: 18289 + 421 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 133

java.lang.NullPointerException: Attempt to invoke direct method 'boolean android.os.RecoverySystem.requestLskf(java.lang.String, android.content.IntentSender)' on a null object reference
        at android.os.RecoverySystem.prepareForUnattendedUpdate(RecoverySystem.java:714)
        at com.google.android.gms.update.control.DeviceControl.g(:com.google.android.gms@243161038@24.31.61 (190400-661400885):34)
        at com.google.android.gms.update.control.InstallationControl.v(:com.google.android.gms@243161038@24.31.61 (190400-661400885):48)
        at dphk.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):913)
        at com.google.android.gms.update.control.ReceiverIntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):91)
        at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):2)
        at aisb.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):8)
        at ock.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):70)
        at ocj.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):152)
        at eoqb.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
```
Did a clean release build with `out/` directory wiped out.

I had the same issue on a 6 month old build so I tried to update to see if there was some compatibility issue that got fixed. Unfortunately, nothing has changed.

This error message pops out sometimes but doesn't seem to have any effect on availability of apps that depend on Google Play Services.

Should I try adding a requestLskf stub to gmscompat_config file?

**Comment by mberloww** [comment]
> You're on a nearly 1 year old release from 2023:
> 
> > 2023111500
> 
> You need to update to a current release or you're going to have major compatibility issues.

Thanks for the reminder.
Just FYI I have now installed the update and upon rebooting I got the same error as before, but in any case all apps seem to be working fine. 

```
type: crash
osVersion: google/raven/raven:14/AP2A.240805.005.F1/2024082200:user/release-keys
package: com.google.android.gms:243161038
process: com.google.android.gms
processUptime: 132842 + 787 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 133

java.lang.NullPointerException: Attempt to invoke direct method 'boolean android.os.RecoverySystem.requestLskf(java.lang.String, android.content.IntentSender)' on a null object reference
	at android.os.RecoverySystem.prepareForUnattendedUpdate(RecoverySystem.java:714)
	at com.google.android.gms.update.control.DeviceControl.g(:com.google.android.gms@243161038@24.31.61 (190400-661400885):34)
	at com.google.android.gms.update.control.InstallationControl.v(:com.google.android.gms@243161038@24.31.61 (190400-661400885):48)
	at dphk.a(:com.google.android.gms@243161038@24.31.61 (190400-661400885):913)
	at com.google.android.gms.update.control.ReceiverIntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):91)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):2)
	at aisb.onHandleIntent(:com.google.android.gms@243161038@24.31.61 (190400-661400885):8)
	at ock.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):70)
	at ocj.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):152)
	at eoqb.run(:com.google.android.gms@243161038@24.31.61 (190400-661400885):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```
