### ISSUE TITLE
Google Play Services has crashed

### ISSUE THREAD

**Issue by basilmuc2024** [GrapheneOS/os-issue-tracker#3942]
Error message on Pixel 7, Android 14
[Error in Google Play-Dienste da4ec1e18f0e.txt](https://github.com/user-attachments/files/16825801/Error.in.Google.Play-Dienste.da4ec1e18f0e.txt)

**Comment by cuzimhappyy** [comment]
I'm having a similar issue when attempting to use a FIDO2 key via NFC
[Error in Google Play services f28df3d2ddf7.txt](https://github.com/user-attachments/files/16841521/Error.in.Google.Play.services.f28df3d2ddf7.txt)

**Comment by kydauran** [comment]
I seem to have encountered the same problem with caiman yesterday.
I only triggered it once with Yubikey Security Key A (got another pair with C port), next tries had no crashes.

[Error in Google Play services 50013a22c390.txt](https://github.com/user-attachments/files/17028945/Error.in.Google.Play.services.50013a22c390.txt)

**Comment by ShadowSlayer1441** [comment]
Seems to be the same issue caused by enabling NFC in the passkeys menu to use a NFC fido2 hardware key. The actual process worked seemlessley except for the crash notif.

```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241005.015/2024102400:user/release-keys
package: com.google.android.gms:244233036
process: com.google.android.gms.ui
processUptime: 7153 + 271 ms
installer: com.android.vending
GmsCompatConfig version: 145

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.nfc.action.ADAPTER_STATE_CHANGED flg=0x4000010 (has extras) } in com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver@c96cf8f
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1822)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at fl.aE(:com.google.android.gms@244233036@24.42.33 (260408-689790151):12)
	at fl.N(:com.google.android.gms@244233036@24.42.33 (260408-689790151):27)
	at ca.c(:com.google.android.gms@244233036@24.42.33 (260408-689790151):58)
	at ca.a(:com.google.android.gms@244233036@24.42.33 (260408-689790151):3)
	at de.hT(:com.google.android.gms@244233036@24.42.33 (260408-689790151):110)
	at de.dismiss(:com.google.android.gms@244233036@24.42.33 (260408-689790151):2)
	at ephh.dismiss(:com.google.android.gms@244233036@24.42.33 (260408-689790151):8)
	at away.r(:com.google.android.gms@244233036@24.42.33 (260408-689790151):51)
	at away.k(:com.google.android.gms@244233036@24.42.33 (260408-689790151):81)
	at axlb.b(:com.google.android.gms@244233036@24.42.33 (260408-689790151):499)
	at away.q(:com.google.android.gms@244233036@24.42.33 (260408-689790151):10)
	at awsu.f(:com.google.android.gms@244233036@24.42.33 (260408-689790151):5)
	at awie.b(:com.google.android.gms@244233036@24.42.33 (260408-689790151):9)
	at axji.c(:com.google.android.gms@244233036@24.42.33 (260408-689790151):72)
	at axji.b(:com.google.android.gms@244233036@24.42.33 (260408-689790151):104)
	at com.google.android.gms.fido.u2f.api.controller.NfcBroadcastReceiver.ko(:com.google.android.gms@244233036@24.42.33 (260408-689790151):105)
	at com.google.android.gms.libs.punchclock.tracing.TracingBroadcastReceiver.onReceive(:com.google.android.gms@244233036@24.42.33 (260408-689790151):17)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1814)
	... 12 more
```

**Comment by dscotese** [comment]
I also got this error after scanning and attempting to open a passkey QR code from the Gemini crypto exchange. It asked to connect via bluetooth, which I approved, and that's when it crashed.
