### ISSUE TITLE
P9PXL stuck between users 

### ISSUE THREAD

**Issue by DifferentWaste** [GrapheneOS/os-issue-tracker#3946]
Build 2024083100

[system_server crash 33da111738d7.txt](https://github.com/user-attachments/files/16834428/system_server.crash.33da111738d7.txt)

```
type: crash
SystemUptimeMs: 2010704
Process: system_server
Build: google/komodo/komodo:14/AD1A.240530.047/2024083100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:2929)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:362)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:342)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:314)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by DifferentWaste** [comment]
Will do.

**Comment by DifferentWaste** [comment]
Added screen lock and successfully switched profiles with no issues so far.

**Comment by Xaddek** [comment]
With "lock methode" you mean the setting that requires a pin before accessing the profile? 
Because my crash happend with a profile that has a pin.

**Comment by controlrepo** [comment]
Hello, also have this issue every time since the upgrade to the 2024102400 (Pixel 6).
Apart from the owner profile in have three other profiles.
I could switch between them no problem before the upgrade.
Only owner profile has the fingerprint login enabled - every other one has the PIN only.

Currently one of the profiles is completely inaccessible: phone always reliably crashes when I try to switch to it (in the identical way like in the OP and #4199 ).
The main difference between them is that this is the only profile with Android Auto installed. It was the first user profile created many releases ago.

The locking method between user profiles 1, 2, 3 is identical (pin only). Crash also happens when I switch between one of them into the cursed one.
Two of user profiles also have sandboxed google play installed.

Attaching one of the system_server traces. Please let me know if I can do something more to debug it better.


```
type: crash

SystemUptimeMs: 101149
Process: system_server
Timestamp: 2024-10-27 13:10:13.531+0000
Build: google/oriole/oriole:15/AP3A.241005.015/2024102400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:3068)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by controlrepo** [comment]
Hello, thanks for the response.

I had the developer options always disabled, only enabled it today for a while.
In disabled it again, rebooted the phone, unlocked the owner profile and tried to switch - exact same behaviour.

```
type: crash

SystemUptimeMs: 77031
Process: system_server
Timestamp: 2024-10-27 16:45:45.902+0000
Build: google/oriole/oriole:15/AP3A.241005.015/2024102400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:3068)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by SentientCoffee** [comment]
Don't remember where I found this workaround, but: Switching users from the lock screen (i.e. lock phone, wake, swipe down notifications and switch users from there) works fine. Switching users after the phone is unlocked causes the system_server crash.

**Comment by toroaren** [comment]
Hello, I am re-opening this because it might be that I am  suffering of this or a closely related problem. I am on the latest A16 070800 Beta and the system_server crash was there even in A15 latest stable. I have a P7 and 3 profiles. system_server crashes reproduceable on any of the builds i tried. Method: from the owner to another profile via double swipe and click on user icon. Logging in there, ending the session by either double swipe and click on another users icon. NOT providing this users lock pin or password but swiping down to dismiss the prompt and to instead choose another user. That users profile picture loads, then nothing for 10-20 seconds, than crash and I am back in the grapheneos boot animation and the owners lockscreen. This crash does not occur when pressing power button to turn off the screen instead of dismissing the passcode /pin prompt via swipe. When pressing power again, profile switch can be done without crash.

I saved the latest crashreport.  I add it as a file since I am on mobile only and totally unfamiliar with github. I created this account for reporting this. 

[system_server crash 05e6974071a3.txt](https://github.com/user-attachments/files/21145868/system_server.crash.05e6974071a3.txt)
