### ISSUE TITLE
System Crashing/Restarting After Charging

### ISSUE THREAD

**Issue by Niner-Ploon** [GrapheneOS/os-issue-tracker#3967]
Every time I take my phone off the charger the system crashes and reboots the phone. I don't know why this is happening and thought an update would fix the issue. The error message that pops up says "system server crash". 

I've attached the report below.

```
type: crash
SystemUptimeMs: 77540325
Process: system_server
Build: google/raven/raven:14/AP2A.240905.003.F1/2024090400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.nio.channels.FileLock.close()' on a null object reference
	at com.android.server.power.stats.PowerStatsStore.unlockStoreDirectory(PowerStatsStore.java:261)
	at com.android.server.power.stats.PowerStatsStore.storePowerStatsSpan(PowerStatsStore.java:157)
	at com.android.server.power.stats.PowerStatsStore.storeBatteryUsageStats(PowerStatsStore.java:227)
	at com.android.server.power.stats.BatteryStatsImpl.lambda$saveBatteryUsageStatsOnReset$3(BatteryStatsImpl.java:11844)
	at com.android.server.power.stats.BatteryStatsImpl.$r8$lambda$W0vtzSJt4a6o7uGulUQxNJn_ho4(BatteryStatsImpl.java:0)
	at com.android.server.power.stats.BatteryStatsImpl$$ExternalSyntheticLambda5.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

**Comment by Niner-Ploon** [comment]
Someone help please

**Comment by muhomorr** [comment]
@Niner-Ploon Reproduce this crash one more time, then immediately capture full system log from Settings > System > View logs. Send the log file to one of the following places:

Matrix: @muhomorr:grapheneos.org
Discord: muhomorr_ (with underscore at the end)
Email: [muhomorr@grapheneos.org](mailto:muhomorr@grapheneos.org)
