### ISSUE TITLE
When switching from user to admin profile, the system is crashed 

### ISSUE THREAD

**Issue by Edanomi7** [GrapheneOS/os-issue-tracker#3975]
```
type: crash
SystemUptimeMs: 34019126
Process: system_server
Build: google/caiman/caiman:14/AD1A.240905.004/2024090400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:2929)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:362)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:342)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:314)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Edanomi7** [comment]
I selected pin input and fingerprint as the lock.
The first start worked perfectly. But switching back then caused the crash. Switching to the user again ends in a system restart.
Creating a new user fails with a (the app takes too long) screen. In the (system is restarting screen) .
After selecting the ( wait for APP ) button, the installation ends in the ( select pin ) screen with a long wait and no keyboard.
Device gets quite warm.
Plugging in the charging cable has no function. ( no charging, no power flow).
Pixel 9 pro Grapheneos installation via website. Worked fine.
