### ISSUE TITLE
Launcher Crash - quickstep.RecentsActivity Java NPE

### ISSUE THREAD

**Issue by newb23** [GrapheneOS/os-issue-tracker#3996]
Issue occurs several times a day, will continue to track logs on it from here out.
Issue occurs when attempting to change apps, or on return to the home screen.
I use KISS launcher as my default, and HAD a Live Wallpaper, which I have now disabled.
I have not futzed with any notification settings, but the root error seems different from those reports.

Excited for Android 15!

```
type: crash
osVersion: google/akita/akita:14/AP2A.240905.003.A1/2024090400:user/release-keys
package: com.android.launcher3:34
process: com.android.launcher3
processUptime: 5475075 + 384 ms

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.launcher3/com.android.quickstep.RecentsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.util.SplitSelectStateController.registerSplitListener(com.android.quickstep.SplitSelectionListener)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6268)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6159)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:80)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:70)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6225)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2612)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.quickstep.util.SplitSelectStateController.registerSplitListener(com.android.quickstep.SplitSelectionListener)' on a null object reference
	at com.android.quickstep.views.RecentsView.onAttachedToWindow(RecentsView.java:1104)
	at android.view.View.dispatchAttachedToWindow(View.java:22663)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3495)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3502)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5338)
	at android.view.ViewGroup.addView(ViewGroup.java:5124)
	at android.view.ViewGroup.addView(ViewGroup.java:5096)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:554)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:535)
	at android.app.Activity.setContentView(Activity.java:3826)
	at com.android.quickstep.RecentsActivity.setupViews(RecentsActivity.java:134)
	at com.android.quickstep.RecentsActivity.onCreate(RecentsActivity.java:366)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	... 20 more
```

**Comment by newb23** [comment]
[Error in Launcher 1e8eda30affe.txt](https://github.com/user-attachments/files/17004865/Error.in.Launcher.1e8eda30affe.txt)

Full log for the report directly above.

**Comment by newb23** [comment]
I have not had this crash since removing Live Wallpaper, even after the Android 15 update.
