### ISSUE TITLE
Google crashed when opening from app list

### ISSUE THREAD

**Issue by MSnaker** [GrapheneOS/os-issue-tracker#4012]
Disclaimer: I have installed on my system Transcribro from the Accrescent store. While opening, it tried to show me the icon of a mic, then it closed.
It's not something I use often, but I understand how this might be a functionality people want working, so I'm reporting it.

Here's the crash log:

```
type: crash
osVersion: google/lynx/lynx:14/AP2A.240905.003/2024090400:user/release-keys
package: com.google.android.googlequicksearchbox:301397754
process: com.google.android.googlequicksearchbox:search
processUptime: 953 + 259 ms
installer: com.android.vending
GmsCompatConfig version: 137

java.lang.ClassCastException: com.google.android.libraries.web.base.i cannot be cast to com.google.android.apps.search.googleapp.search.voicesearch.at
	at com.google.android.apps.search.googleapp.search.o.o(PG:58)
	at com.google.android.apps.search.googleapp.search.o.z(PG:1)
	at com.google.android.apps.search.googleapp.search.SearchFragment.onStart(PG:70)
	at android.support.v4.app.au.performStart(PG:18)
	at android.support.v4.app.cw.e(PG:519)
	at android.support.v4.app.cn.I(PG:55)
	at android.support.v4.app.cn.B(PG:34)
	at android.support.v4.app.cn.A(PG:11)
	at android.support.v4.app.au.performStart(PG:47)
	at android.support.v4.app.cw.e(PG:519)
	at android.support.v4.app.cn.I(PG:55)
	at android.support.v4.app.cn.B(PG:34)
	at android.support.v4.app.cn.A(PG:11)
	at android.support.v4.app.au.performStart(PG:47)
	at android.support.v4.app.cw.e(PG:519)
	at android.support.v4.app.cn.I(PG:55)
	at android.support.v4.app.cn.B(PG:34)
	at android.support.v4.app.cn.A(PG:11)
	at android.support.v4.app.bf.g(PG:5)
	at android.support.v4.app.ba.onStart(PG:38)
	at android.support.v7.app.p.onStart(PG:1)
	at com.google.android.libraries.aw.c.a.a.onStart(PG:13)
	at com.google.android.apps.search.googleapp.activity.GoogleAppActivity.onStart(PG:24)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1706)
	at android.app.Activity.performStart(Activity.java:9056)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4029)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by soupslurpr** [comment]
Hi, could you provide steps to reproduce this issue? Thanks.

**Comment by MSnaker** [comment]
Ok there might have been something weird with my phone at the time, because I have not been able to reproduce the issue since then.
