### ISSUE TITLE
Device boot loops, strange behaviour

### ISSUE THREAD

**Issue by MorekConsultancy** [GrapheneOS/os-issue-tracker#4088]
When I run out of battery, I plug in to charge, the device turns on then it shows the power off screen, then it loops constantly on/off and gets very hot. To break the cycle I can pause the boot using the power button at the boot loader screen. This gives the phone enough time to get some charge and then when I resume it will power up and boot the OS.

This is odd behavior, as it only seems to happen now and then. After I have connected it to my win laptop...

```
type: crash
SystemUptimeMs: 31514
Process: system_server
Build: google/lynx/lynx:14/AP2A.240905.003/2024091900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.UnsupportedOperationException: android.os.DeadObjectException
	at com.android.server.usb.hal.port.UsbPortAidl.setPortSecurityState(UsbPortAidl.java:471)
	at com.android.server.usb.UsbPortManager.setPortSecurityState(UsbPortManager.java:453)
	at com.android.server.usb.UsbService.setPortSecurityState(UsbService.java:1010)
	at android.hardware.usb.UsbManager.setPortSecurityState(UsbManager.java:1627)
	at com.android.server.policy.keyguard.UsbPortSecurityHooks.setSecurityStateForAllPorts(UsbPortSecurityHooks.java:188)
	at com.android.server.policy.keyguard.UsbPortSecurityHooks.lambda$onKeyguardShowingStateChangedInner$2(UsbPortSecurityHooks.java:161)
	at com.android.server.policy.keyguard.UsbPortSecurityHooks.$r8$lambda$Mxx7lQQe9n7xZyKCwN54ad3XSkA(UsbPortSecurityHooks.java:0)
	at com.android.server.policy.keyguard.UsbPortSecurityHooks$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.getExtension(Native Method)
	at com.android.server.usb.hal.port.UsbPortAidl.setPortSecurityState(UsbPortAidl.java:468)
	... 12 more
```

Any  help appreciated

**Comment by MorekConsultancy** [comment]
Pixel 7a - grapheme OS latest build. Regular USB C cable used.

**Comment by MorekConsultancy** [comment]
Sorted? would ovbe to know about it if you have time to elaborate? xx
