### ISSUE TITLE
Google play services crash when turning remote locking

### ISSUE THREAD

**Issue by mrxx0** [GrapheneOS/os-issue-tracker#4144]
A feature of Google service allows to lock a device remotely.
By trying to activate it Google play services crashed.

Steps to reproduce : 
Settings -> Apps -> Sandboxed Google Play -> Google Settings -> Locate my device -> Remote locking -> activate

Tried to reproduce it again but I can't enter into the remote locking settings it crashed at that step on the 2nd time and now I have a empty screen on that step.

Crash : 

```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024101600:user/release-keys
package: com.google.android.gms:244034029
process: com.google.android.gms.ui
processUptime: 130694 + 196 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 142

java.lang.SecurityException: Need READ_PHONE_STATE, READ_PRIVILEGED_PHONE_STATE, or carrier privilege
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at com.android.internal.telephony.ISub$Stub$Proxy.getActiveSubInfoCount(ISub.java:1659)
	at android.telephony.SubscriptionManager.getActiveSubscriptionInfoCount(SubscriptionManager.java:2259)
	at bwar.W(:com.google.android.gms@244034029@24.40.34 (190400-682300402):9)
	at bwar.N(:com.google.android.gms@244034029@24.40.34 (190400-682300402):36)
	at bvzy.a(:com.google.android.gms@244034029@24.40.34 (190400-682300402):31)
	at ddvt.b(:com.google.android.gms@244034029@24.40.34 (190400-682300402):45)
	at androidx.preference.Preference.W(:com.google.android.gms@244034029@24.40.34 (190400-682300402):5)
	at kdk.onClick(:com.google.android.gms@244034029@24.40.34 (190400-682300402):9)
	at android.view.View.performClick(View.java:8028)
	at com.android.settingslib.widget.MainSwitchBar.performClick(:com.google.android.gms@244034029@24.40.34 (190400-682300402):6)
	at android.view.View.performClickInternal(View.java:8005)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31229)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by kelseying** [comment]
I am having what  seems to be the same issue.

```
type: crash
osVersion: google/panther/panther:15/AP3A.241005.015/2024102100:user/release-keys
package: com.google.android.gms:244134035
process: com.google.android.gms.ui
processUptime: 6554 + 742 ms
installer: com.android.vending
GmsCompatConfig version: 144

java.lang.RuntimeException: Unable to resume activity {com.google.android.gms/com.google.android.gms.mdm.settings.QrlSettingsActivity}: java.lang.SecurityException: Need READ_PHONE_STATE, READ_PRIVILEGED_PHONE_STATE, or carrier privilege
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5335)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5368)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.SecurityException: Need READ_PHONE_STATE, READ_PRIVILEGED_PHONE_STATE, or carrier privilege
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at com.android.internal.telephony.ISub$Stub$Proxy.getActiveSubInfoCount(ISub.java:1659)
	at android.telephony.SubscriptionManager.getActiveSubscriptionInfoCount(SubscriptionManager.java:2259)
	at bvxv.W(:com.google.android.gms@244134035@24.41.34 (260400-685836814):9)
	at bvxv.O(:com.google.android.gms@244134035@24.41.34 (260400-685836814):36)
	at bvxv.onResume(:com.google.android.gms@244134035@24.41.34 (260400-685836814):35)
	at fu.e(:com.google.android.gms@244134035@24.41.34 (260400-685836814):389)
	at fl.Q(:com.google.android.gms@244134035@24.41.34 (260400-685836814):55)
	at fl.J(:com.google.android.gms@244134035@24.41.34 (260400-685836814):34)
	at fl.H(:com.google.android.gms@244134035@24.41.34 (260400-685836814):11)
	at ee.g(:com.google.android.gms@244134035@24.41.34 (260400-685836814):5)
	at osp.onResumeFragments(:com.google.android.gms@244134035@24.41.34 (260400-685836814):10)
	at osp.onPostResume(:com.google.android.gms@244134035@24.41.34 (260400-685836814):4)
	at onf.public_onPostResume(:com.google.android.gms@244134035@24.41.34 (260400-685836814):1)
	at ong.onPostResume(:com.google.android.gms@244134035@24.41.34 (260400-685836814):5)
	at ajav.onPostResume(:com.google.android.gms@244134035@24.41.34 (260400-685836814):9)
	at android.app.Activity.performResume(Activity.java:9240)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5325)
	... 16 more
```
