### ISSUE TITLE
Signal App crashes when starting audio or video Call - Android 15

### ISSUE THREAD

**Issue by jaedog** [GrapheneOS/os-issue-tracker#4152]
Steps to reproduce: Start a audio or video call with Signal

Crash:
```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241005.015/2024101700:user/release-keys
flags: dev options enabled
package: org.thoughtcrime.securesms:147100
process: org.thoughtcrime.securesms
processUptime: 4955 + 371 ms
installer: com.android.vending

java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~HRhhFYrSk6KqgJ8Eq83m7w==/org.thoughtcrime.securesms-Oxd2BTdV2j_OVID01_y8Gw==/base.apk!classes6.dex)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~HRhhFYrSk6KqgJ8Eq83m7w==/org.thoughtcrime.securesms-Oxd2BTdV2j_OVID01_y8Gw==/base.apk!classes6.dex).(:0)
```

**Comment by jaedog** [comment]
It might just be a Signal bug on Android: https://github.com/signalapp/Signal-Android/issues/13737. I realized I'm on the beta channel for Signal.

**Comment by neunzehnachtneun** [comment]
I'm using Molly 7.18 and can't confirm.
