### ISSUE TITLE
Strange crash report 

### ISSUE THREAD

**Issue by Compr0mzd** [GrapheneOS/os-issue-tracker#4158]
It's the second time I get this crash report.  
Could it be related to the constant WiFi disconnection I have ?
```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241005.015/2024101700:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244134036
process: com.google.android.gms.persistent
processUptime: 1891 + 309 ms
installer: com.android.vending
GmsCompatConfig version: 143

android.net.ConnectivityManager$TooManyRequestsException
	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4435)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4636)
	at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:5203)
	at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:5170)
	at endz.x(:com.google.android.gms@244134036@24.41.34 (260408-685836814):201)
	at endz.handleMessage(:com.google.android.gms@244134036@24.41.34 (260408-685836814):50)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at brkn.mz(:com.google.android.gms@244134036@24.41.34 (260408-685836814):1)
	at brkn.dispatchMessage(:com.google.android.gms@244134036@24.41.34 (260408-685836814):138)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	Suppressed: ethu: 
		at tk_trace.location_base-GoogleLocationChimeraService_onCreate(Unknown Source:0)
```

If you need more context I'll give it promptly

**Comment by Compr0mzd** [comment]
```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241005.015/2024101701:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244134036
process: com.google.android.gms.persistent
processUptime: 3709971 + 379 ms
installer: com.android.vending
GmsCompatConfig version: 143

java.lang.RuntimeException: Unable to bind to service com.google.android.gms.chimera.PersistentApiService@d3e0a1f with Intent { act=com.google.android.chimera.BoundService.START dat=chimera-action: cmp=com.google.android.gms/.chimera.PersistentApiService }: android.net.ConnectivityManager$TooManyRequestsException
	at android.app.ActivityThread.handleBindService(ActivityThread.java:5039)
	at android.app.ActivityThread.-$$Nest$mhandleBindService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2459)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.net.ConnectivityManager$TooManyRequestsException
	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4435)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4636)
	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4657)
	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:5051)
	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:5017)
	at com.google.android.gms.mdns.MdnsChimeraService.onCreate(:com.google.android.gms@244134036@24.41.34 (260408-685836814):102)
	at ofw.onCreate(:com.google.android.gms@244134036@24.41.34 (260408-685836814):8)
	at ajft.onCreate(:com.google.android.gms@244134036@24.41.34 (260408-685836814):27)
	at ofh.onBind(:com.google.android.gms@244134036@24.41.34 (260408-685836814):115)
	at ofk.onBind(:com.google.android.gms@244134036@24.41.34 (260408-685836814):10)
	at com.google.android.gms.chimera.container.boundservice.GmsApiChimeraService.g(:com.google.android.gms@244134036@24.41.34 (260408-685836814):7)
	at com.google.android.gms.chimera.container.boundservice.GmsApiChimeraService.onBind(:com.google.android.gms@244134036@24.41.34 (260408-685836814):1)
	at ajaz.onBind(:com.google.android.gms@244134036@24.41.34 (260408-685836814):30)
	at android.app.ActivityThread.handleBindService(ActivityThread.java:5024)
	... 11 more
```
During the night without even using my phone I got 2 crashes.
- 1 with the same crash report as mentioned on the initial crash 
- 1 with the crash pasted on this comment
![IMG_20241019_091907](https://github.com/user-attachments/assets/cc5a7ef0-ec03-46e1-817b-0700a923a00c)

**Comment by Compr0mzd** [comment]
With latest Alpha Update the crash happened again

**Comment by muhomorr** [comment]
@Compr0mzd Capture a full system log from Settings > System > View logs right after this crash happens again. Send the log file to one of the following places:

Matrix: @muhomorr:grapheneos.org
Discord: muhomorr_ (with underscore at the end)
Email: [muhomorr@grapheneos.org](mailto:muhomorr@grapheneos.org)

**Comment by Compr0mzd** [comment]
> @Compr0mzd Capture a full system log from Settings > System > View logs right after this crash happens again. Send the log file to one of the following places:
> 
> Matrix: @muhomorr:grapheneos.org Discord: muhomorr_ (with underscore at the end) Email: [muhomorr@grapheneos.org](mailto:muhomorr@grapheneos.org)

I'll do it if can becausse it happens when I'm sleeping. It never happened during the day. It's weird.
