### ISSUE TITLE
2024101801 Bluetooth Privilaged Play Services Crashing

### ISSUE THREAD

**Issue by trixter13** [GrapheneOS/os-issue-tracker#4161]
```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024101801:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244134036
process: com.google.android.gms.persistent
processUptime: 454288 + 603 ms
installer: com.android.vending
GmsCompatConfig version: 143

java.lang.RuntimeException: Unable to start service com.google.android.gms.findmydevice.spot.bleadvertising.OfflineBeaconService_Persistent@638a37e with Intent { cmp=com.google.android.gms/.findmydevice.spot.bleadvertising.OfflineBeaconService_Persistent (has extras) }: java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10221 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5191)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2476)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10221 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.nearby.INearbyManager$Stub$Proxy.getPoweredOffModeEnabled(INearbyManager.java:374)
	at android.nearby.NearbyManager.getPoweredOffFindingMode(NearbyManager.java:612)
	at axqb.c(:com.google.android.gms@244134036@24.41.34 (260408-685836814):19)
	at axqq.d(:com.google.android.gms@244134036@24.41.34 (260408-685836814):3)
	at com.google.android.gms.findmydevice.spot.bleadvertising.OfflineBeaconChimeraService.onStartCommand(:com.google.android.gms@244134036@24.41.34 (260408-685836814):190)
	at oew.onStartCommand(:com.google.android.gms@244134036@24.41.34 (260408-685836814):8)
	at ajaz.onStartCommand(:com.google.android.gms@244134036@24.41.34 (260408-685836814):16)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5173)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2451)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2479)
	at com.android.server.nearby.NearbyService.enforceBluetoothPrivilegedPermission(NearbyService.java:221)
	at com.android.server.nearby.NearbyService.getPoweredOffModeEnabled(NearbyService.java:176)
	at android.nearby.INearbyManager$Stub.onTransact(INearbyManager.java:221)
```

**Comment by trixter13** [comment]
I'm still getting this error on the new build:
```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024101900:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244134036
process: com.google.android.gms.persistent
processUptime: 47407 + 1759 ms
installer: com.android.vending
GmsCompatConfig version: 143

java.lang.RuntimeException: Unable to start service com.google.android.gms.findmydevice.spot.bleadvertising.OfflineBeaconService_Persistent@83fc73 with Intent { cmp=com.google.android.gms/.findmydevice.spot.bleadvertising.OfflineBeaconService_Persistent (has extras) }: java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10221 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5191)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2476)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.SecurityException: Need BLUETOOTH PRIVILEGED permission: Neither user 10221 nor current process has android.permission.BLUETOOTH_PRIVILEGED.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.nearby.INearbyManager$Stub$Proxy.getPoweredOffModeEnabled(INearbyManager.java:374)
	at android.nearby.NearbyManager.getPoweredOffFindingMode(NearbyManager.java:622)
	at axqb.c(:com.google.android.gms@244134036@24.41.34 (260408-685836814):19)
	at axqq.d(:com.google.android.gms@244134036@24.41.34 (260408-685836814):3)
	at com.google.android.gms.findmydevice.spot.bleadvertising.OfflineBeaconChimeraService.onStartCommand(:com.google.android.gms@244134036@24.41.34 (260408-685836814):190)
	at oew.onStartCommand(:com.google.android.gms@244134036@24.41.34 (260408-685836814):8)
	at ajaz.onStartCommand(:com.google.android.gms@244134036@24.41.34 (260408-685836814):16)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5173)
	... 11 more
```
