### ISSUE TITLE
GmsCompat crash after scanning QR code

### ISSUE THREAD

**Issue by audreytoskin** [GrapheneOS/os-issue-tracker#4173]
```
type: crash
osVersion: google/comet/comet:14/AD1A.240905.004/2024101200:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244134029
process: com.google.android.gms
processUptime: 62559367 + 375 ms
installer: com.android.vending
GmsCompatConfig version: 143

java.lang.SecurityException: getAvailableSubscriptionInfoList. Does not have any of the following permissions. [android.permission.READ_PRIVILEGED_PHONE_STATE]
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at com.android.internal.telephony.ISub$Stub$Proxy.getAvailableSubscriptionInfoList(ISub.java:1669)
	at android.telephony.SubscriptionManager.getAvailableSubscriptionInfoList(SubscriptionManager.java:2152)
	at com.google.android.gms.esim.transferengine.EsimTransferEngine.f(:com.google.android.gms@244134029@24.41.34 (190400-685836814):5)
	at com.google.android.gms.esim.transferengine.EsimTransferEngine.k(:com.google.android.gms@244134029@24.41.34 (190400-685836814):31)
	at com.google.android.gms.esim.init.EsimModuleInitIntentOperation.onHandleIntent(:com.google.android.gms@244134029@24.41.34 (190400-685836814):101)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@244134029@24.41.34 (190400-685836814):2)
	at ajpl.onHandleIntent(:com.google.android.gms@244134029@24.41.34 (190400-685836814):8)
	at ojx.run(:com.google.android.gms@244134029@24.41.34 (190400-685836814):70)
	at ojw.run(:com.google.android.gms@244134029@24.41.34 (190400-685836814):152)
	at ettw.run(:com.google.android.gms@244134029@24.41.34 (190400-685836814):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

description: Crash error while trying to run a QR-code-based setup of a Chromebook from my phone.

- Begin setup of Galaxy Chromebook 2 > choose option to set up from my phone instead of manually typing my login and 2fa
- on Pixel 9 Pro Fold, launched `com.example.barcodescanner` version 1.10 (versionCode 13) from F-Droid, scanned QR code on Chromebook screen > GmsCompat crash notification.

**Comment by audreytoskin** [comment]
I don't have the Chromebook to test anymore, so I guess we can close this. Everyone else, you can start a new thread if you're able to duplicate the issue.
