### ISSUE TITLE
Google play services crashing since last update

### ISSUE THREAD

**Issue by Alundert** [GrapheneOS/os-issue-tracker#4196]
Since it crashes randomly here's the log:

```
type: crash
osVersion: google/raven/raven:15/AP3A.241005.015/2024102100:user/release-keys
flags: dev options enabled
package: com.google.android.gms:243530044
process: com.google.android.gms
processUptime: 39940 + 348 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 144

java.lang.IllegalStateException: Failed to find update_engine
	at android.os.UpdateEngine.<init>(UpdateEngine.java:256)
	at dqsi.<init>(:com.google.android.gms@243530044@24.35.30 (260400-668017056):16)
	at dqse.a(:com.google.android.gms@243530044@24.35.30 (260400-668017056):3)
	at dqxy.b(:com.google.android.gms@243530044@24.35.30 (260400-668017056):29)
	at dqrs.<init>(:com.google.android.gms@243530044@24.35.30 (260400-668017056):50)
	at dqpn.b(:com.google.android.gms@243530044@24.35.30 (260400-668017056):184)
	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@243530044@24.35.30 (260400-668017056):314)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@243530044@24.35.30 (260400-668017056):2)
	at aiuv.onHandleIntent(:com.google.android.gms@243530044@24.35.30 (260400-668017056):8)
	at ocr.run(:com.google.android.gms@243530044@24.35.30 (260400-668017056):70)
	at ocq.run(:com.google.android.gms@243530044@24.35.30 (260400-668017056):152)
	at eqdo.run(:com.google.android.gms@243530044@24.35.30 (260400-668017056):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by muhomorr** [comment]
Resolved since 2024102400 release.
