### ISSUE TITLE
Android Auto Crash - Google maps also crashes

### ISSUE THREAD

**Issue by opokadot** [GrapheneOS/os-issue-tracker#4215]
```
type: crash
osVersion: google/bluejay/bluejay:15/AP3A.241005.015/2024102100:user/release-keys
flags: dev options enabled
package: com.google.android.projection.gearhead:127643424
process: com.google.android.projection.gearhead:projection
processUptime: 564096 + 437 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 145

java.lang.IllegalArgumentException: Not a valid ID of the default device or any virtual device: 7
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3255)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.bluetooth.IBluetooth$Stub$Proxy.getRemoteClass(IBluetooth.java:2873)
	at android.bluetooth.BluetoothDevice.getBluetoothClass(BluetoothDevice.java:2385)
	at mnh.Y(SourceFile:1)
	at mnh.e(SourceFile:88)
	at mnr.onServiceConnected(SourceFile:321)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2210)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2243)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by muhomorr** [comment]
Is this a reproducible crash?
