### ISSUE TITLE
Crash of Playstore

### ISSUE THREAD

**Issue by sock3t** [GrapheneOS/os-issue-tracker#4217]
Playstore crashed after confirmation of app installation for child's device in Google Family Link App.

````
type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241005.015/2024102100:user/release-keys
flags: dev options enabled
package: com.android.vending:84321630
process: com.android.vending
processUptime: 2852114 + 10466 ms
installer: com.android.vending
GmsCompatConfig version: 145

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at aghz.C(PG:3)
	at qcx.apply(PG:120)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.bF(PG:7)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.bD(PG:21)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.bK(PG:3)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.at(PG:5)
	at android.support.v7.widget.LinearLayoutManagerWithProxies.k(PG:13)
	at android.support.v7.widget.LinearLayoutManager.M(PG:45)
	at android.support.v7.widget.LinearLayoutManager.o(PG:744)
	at com.google.android.finsky.layoutmanager.HybridLayoutManager.o(PG:110)
	at android.support.v7.widget.RecyclerView.aO(PG:65)
	at android.support.v7.widget.RecyclerView.F(PG:74)
	at android.support.v7.widget.RecyclerView.onLayout(PG:6)
	at com.google.android.finsky.recyclerview.PlayRecyclerView.onLayout(PG:9)
	at android.view.View.layout(View.java:25374)
	at android.view.ViewGroup.layout(ViewGroup.java:6421)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25374)
	at android.view.ViewGroup.layout(ViewGroup.java:6421)
	at jlt.onLayout(PG:254)
	at android.view.View.layout(View.java:25374)
	at android.view.ViewGroup.layout(ViewGroup.java:6421)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at aufk.onLayout(PG:1)
	at android.view.View.layout(View.java:25374)
	at android.view.ViewGroup.layout(ViewGroup.java:6421)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25374)
	at android.view.ViewGroup.layout(ViewGroup.java:6421)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25374)
	at android.view.ViewGroup.layout(ViewGroup.java:6421)
	at hnm.onLayout(PG:6)
	at android.view.View.layout(View.java:25374)
	at android.view.ViewGroup.layout(ViewGroup.java:6421)
	at hno.d(PG:47)
	at hnb.kq(PG:7)
	at ghw.n(PG:7)
	at ghm.a(PG:71)
	at fdd.d(PG:45)
	at fek.c(PG:176)
	at gjv.d(PG:3)
	at gjv.b(PG:15)
	at ghp.k(PG:116)
	at ghp.s(PG:132)
	at ggb.F(PG:12)
	at ggb.gI(PG:4)
	at gcu.g(PG:22)
	at gcu.r(PG:13)
	at foe.kq(PG:13)
	at ghw.n(PG:7)
	at ggo.aw(PG:88)
	at ggo.gI(PG:4)
	at gcu.e(PG:23)
	at gcu.k(PG:2)
	at blf.kq(PG:9)
	at ghw.n(PG:7)
	at ggo.aw(PG:88)
	at ggo.gI(PG:4)
	at gcu.m(PG:73)
	at bjz.kq(PG:6)
	at ghw.n(PG:7)
	at ggo.aw(PG:88)
	at ggo.gI(PG:4)
	at gcu.f(PG:11)
	at ghn.a(PG:64)
	at fdd.d(PG:95)
	at fek.c(PG:176)
	at gjv.d(PG:3)
	at gjv.a(PG:15)
	at ghp.t(PG:109)
	at gha.aa(PG:38)
	at gia.r(PG:207)
	at gia.i(PG:83)
	at gmb.p(PG:36)
	at gjj.b(PG:2)
	at gmb.dispatchDraw(PG:12)
	at android.view.View.draw(View.java:24845)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5659)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5312)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```
`

**Comment by sock3t** [comment]
This is the first ever crash with any app I witnessed since I switched to Graphene OS 1+ year ago.

It did not reproduce yet. But I also did not go through the exact same steps yet.

I am not 100% sure what exactly caused the crash. It might be a complex sequence based on my last few actions before the crash:

- while I was browsing the Playstore
- a notification from Google Family Link was shown
  - this was a confirmation for an app install request from my child's device
- I tapped that notification which opened the confirmation dialog which is provided by the Google Family Link app
- I then confirmed the install of the app for my child's device
  - this action was successful as the app was installed on my child's device after this confirmation
- at that moment the system crash dialog popped up

As far as I understand Family Link and Play store have some level of integration with each other. 

I went through that workflow to allow an app install on my child's device many times in the past. But I guess this was the first time I confirmed an app install while the Play store was in foreground.
