### ISSUE TITLE
System crash switching from profile to owner.

### ISSUE THREAD

**Issue by cybern0id** [GrapheneOS/os-issue-tracker#4226]
```
type: crash

SystemUptimeMs: 224466212
Process: system_server
Timestamp: 2024-10-27 17:49:28.585+0000
Build: google/lynx/lynx:15/AP3A.241005.015/2024102400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:3068)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

This is actually the second time this has happened on Android 15 on my Pixel 7a. Had been running alpha channel until about a week ago when I switched to beta.

I say 'crash' because that is what the system reports however the problem manifests as a frozen screen just after switching from a user profile to owner, at the circular 'loading' profile progress indicator and the only resolution is to hold down the power button until it restarts.

**Comment by cybern0id** [comment]
Ah, apologies, this might be a duplicate of #3841? Please close if so.
