### ISSUE TITLE
android auto crashes on pixel 6 with graphene os

### ISSUE THREAD

**Issue by piforce** [GrapheneOS/os-issue-tracker#4240]
In vacation I had a rent car with android auto. This worked with my phone. Back from vacation a bought a thrid party screen with android auto. 

When connecting android auto crashes. A few moment with connecting for the first time I got a screen after that is turns black en get the error android aut crashes. 

Tried removing and reinstalling android auto no luck. But when I am in my second (work) profile android auto connects and won't crash with the same settings as far as I know. 
Anyone any idea what is wrong in the main profile?

see log:
type: crash
osVersion: google/oriole/oriole:15/AP3A.241005.015/2024102400:user/release-keys
flags: dev options enabled
package: com.google.android.projection.gearhead:127643424
process: com.google.android.projection.gearhead:projection
processUptime: 159977 + 465 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 145

qwq: java.lang.SecurityException: uid 10286 does not have any of [android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION].
	at qwv.d(SourceFile:25)
	at jlk.a(SourceFile:196)
	at qwl.run(SourceFile:712)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.SecurityException: uid 10286 does not have any of [android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION].
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at gkh.ea(SourceFile:11)
	at ovl.a(SourceFile:155)
	at qnl.f(SourceFile:11)
	at qoa.u(SourceFile:10)
	at qoa.v(SourceFile:23)
	at qoa.g(SourceFile:30)
	at qoa.h(SourceFile:91)
	at qoa.b(SourceFile:15)
	at qpj.c(SourceFile:97)
	at qpd.d(SourceFile:7)
	at qpe.handleMessage(SourceFile:280)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)

**Comment by de0u** [comment]
This part seems like it might be the key:
> java.lang.SecurityException: uid 10286 does not have any of [android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION]

Is there some part of Android Auto and/or Google Play that you can grant location access to?

**Comment by piforce** [comment]
It is the wireless connection

**Comment by piforce** [comment]
yes al toggles are enabled

**Comment by piforce** [comment]
it works now.
gave play services right for location
gave play store right for location.
tnx
