### ISSUE TITLE
Wont open

### ISSUE THREAD

**Issue by Wickeddragon42070** [GrapheneOS/os-issue-tracker#4260]
```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024102400:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244233036
process: com.google.android.gms.ui
processUptime: 2008631 + 181 ms
installer: com.android.vending
GmsCompatConfig version: 145

java.lang.SecurityException: Need READ_PHONE_STATE, READ_PRIVILEGED_PHONE_STATE, or carrier privilege
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at com.android.internal.telephony.ISub$Stub$Proxy.getActiveSubInfoCount(ISub.java:1659)
	at android.telephony.SubscriptionManager.getActiveSubscriptionInfoCount(SubscriptionManager.java:2259)
	at bwhg.W(:com.google.android.gms@244233036@24.42.33 (260408-689790151):9)
	at bwhg.O(:com.google.android.gms@244233036@24.42.33 (260408-689790151):36)
	at bwgq.a(:com.google.android.gms@244233036@24.42.33 (260408-689790151):31)
	at deja.b(:com.google.android.gms@244233036@24.42.33 (260408-689790151):45)
	at androidx.preference.Preference.W(:com.google.android.gms@244233036@24.42.33 (260408-689790151):5)
	at kdb.onClick(:com.google.android.gms@244233036@24.42.33 (260408-689790151):9)
	at android.view.View.performClick(View.java:8028)
	at com.android.settingslib.widget.MainSwitchBar.performClick(:com.google.android.gms@244233036@24.42.33 (260408-689790151):6)
	at android.view.View.performClickInternal(View.java:8005)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31229)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by empratyush** [comment]
This is not enough information, please provide more info.

**Comment by Wickeddragon42070** [comment]
Sorry I don't remember what it was I downloaded the crash file on github.
If it happens again I'll try to give more information. Thanks anyway...
