### ISSUE TITLE
System server crash

### ISSUE THREAD

**Issue by Gezellig0** [GrapheneOS/os-issue-tracker#4274]
```
type: crash

SystemUptimeMs: 14486321
Process: system_server
Timestamp: 2024-11-03 12:28:13.671+0100
Build: google/akita/akita:15/AP3A.241005.015/2024103100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.util.SparseArray.valueAt(SparseArray.java:346)
	at com.android.server.power.stats.PowerComponentAggregatedPowerStats.addPowerStats(PowerComponentAggregatedPowerStats.java:204)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.flushPowerStats(BinaryStatePowerStatsProcessor.java:158)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.start(BinaryStatePowerStatsProcessor.java:93)
	at com.android.server.power.stats.PowerStatsAggregator.start(PowerStatsAggregator.java:167)
	at com.android.server.power.stats.PowerStatsAggregator.aggregatePowerStats(PowerStatsAggregator.java:74)
	at com.android.server.power.stats.PowerStatsScheduler.aggregateAndStorePowerStats(PowerStatsScheduler.java:126)
	at com.android.server.power.stats.PowerStatsScheduler.$r8$lambda$GEaV9AQjfxC9uJ1Tfs7f2eF4_H0(PowerStatsScheduler.java:0)
	at com.android.server.power.stats.PowerStatsScheduler$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

**Comment by McMarius11** [comment]
Mine Lyo crashed, here is the log

```
type: crash
flags: dev options enabled

SystemUptimeMs: 49188201
Process: system_server
Timestamp: 2024-11-04 08:00:31.527+0100
Build: google/panther/panther:15/AP3A.241005.015/2024103100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.util.SparseArray.valueAt(SparseArray.java:346)
	at com.android.server.power.stats.PowerComponentAggregatedPowerStats.addPowerStats(PowerComponentAggregatedPowerStats.java:204)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.flushPowerStats(BinaryStatePowerStatsProcessor.java:158)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.start(BinaryStatePowerStatsProcessor.java:93)
	at com.android.server.power.stats.PowerStatsAggregator.start(PowerStatsAggregator.java:167)
	at com.android.server.power.stats.PowerStatsAggregator.aggregatePowerStats(PowerStatsAggregator.java:74)
	at com.android.server.power.stats.PowerStatsScheduler.aggregateAndStorePowerStats(PowerStatsScheduler.java:126)
	at com.android.server.power.stats.PowerStatsScheduler.$r8$lambda$GEaV9AQjfxC9uJ1Tfs7f2eF4_H0(PowerStatsScheduler.java:0)
	at com.android.server.power.stats.PowerStatsScheduler$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```
