### ISSUE TITLE
launcher crashes after switching profile

### ISSUE THREAD

**Issue by graphenecrash** [GrapheneOS/os-issue-tracker#4279]
log
https://0bin.net/paste/r7hbt4KT#Z3Fb84Nvl61lj6kXoeCMRsVC0wtfkk1LOMASFcLU7tl

**Comment by whanake-music** [comment]
Same issue here
```
type: crash

SystemUptimeMs: 45535
Process: system_server
Timestamp: 2024-11-06 16:52:23.318+1300
Build: google/lynx/lynx:15/AP3A.241005.015/2024110400:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:3068)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```
My device: Pixel 7A

**Comment by SentientCoffee** [comment]
Same here. After trying to switch profiles, screen gets stuck on the "Switching to [Profile]..." screen, and then eventually reboots to the main profile.

Device is a Pixel 6.

```
type: crash
flags: dev options enabled

SystemUptimeMs: 2899917
Process: system_server
Timestamp: 2024-11-08 20:59:14.751-0500
Build: google/oriole/oriole:15/AP3A.241105.007/2024110700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:3068)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```
