### ISSUE TITLE
Reliably crashing on 2ndary switch

### ISSUE THREAD

**Issue by goshuberto** [GrapheneOS/os-issue-tracker#4299]
```
type: crash
flags: dev options enabled

SystemUptimeMs: 628852
Process: system_server
Timestamp: 2024-11-07 20:11:10.589+0100
Build: google/panther/panther:15/AP3A.241105.007/2024110700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at com.android.server.wm.WindowManagerService.detachWindowContext(WindowManagerService.java:3068)
	at android.window.WindowTokenClientController.detachIfNeeded(WindowTokenClientController.java:178)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:153)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
	at java.lang.Daemons$Daemon.run(Daemons.java:131)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ihatetheprivacystatement** [comment]
Not getting it every time but since android 15 I've had 30 system server crashes yes I counted

Most recent log I've got is here, but I saved several more if anyone needs to see em

type: crash

SystemUptimeMs: 32259565
Process: system_server
Timestamp: 2024-11-07 20:41:42.492-0800
Build: google/lynx/lynx:15/AP3A.241105.007/2024110700:user/release-keys
Crash-Handler: [com.android](http://com.android/).internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 10 seconds
	at [com.android](http://com.android/).server.wm.WindowManagerService.detachWindowContext([WindowManagerService.java:3068](http://windowmanagerservice.java:3068/))
	at android.window.WindowTokenClientController.detachIfNeeded([WindowTokenClientController.java:178](http://windowtokenclientcontroller.java:178/))
	at android.window.WindowContextController.detachIfNeeded([WindowContextController.java:153](http://windowcontextcontroller.java:153/))
	at android.window.WindowContext.release([WindowContext.java:114](http://windowcontext.java:114/))
	at android.window.WindowContext.finalize([WindowContext.java:107](http://windowcontext.java:107/))
	at java.lang.Daemons$FinalizerDaemon.doFinalize([Daemons.java:370](http://daemons.java:370/))
	at java.lang.Daemons$FinalizerDaemon.processReference([Daemons.java:350](http://daemons.java:350/))
	at java.lang.Daemons$FinalizerDaemon.runInternal([Daemons.java:322](http://daemons.java:322/))
	at java.lang.Daemons$[Daemon.run](http://daemon.run/)([Daemons.java:131](http://daemons.java:131/))
	at [java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:1012](http://thread.java:1012/))
```

Two slightly different kinds I've had.
Type one - switch profile via profile switcher or end session. Screen shows "switching to [profile name] screen and freezes there and becomes unresponsive. After a while the grapheneos splash screen shows and the phone ends up on the owner profile lock screen in afu

Type 2 - switch to owner profile via end session button. Gets to owner profile lock screen just fine before screen becomes black and unresponsive. After a while, gos splash screen shows, rest is the same
