### ISSUE TITLE
System server crashed - Phone in idle

### ISSUE THREAD

**Issue by mrxx0** [GrapheneOS/os-issue-tracker#4304]
Environment 

Pixel 8 pro - Husky 
2024110700

Context 

My pixel 8 pro was in airplane mode, not charging, in idle. I picked it up and find the notification about system server crash.

Logs

```
type: crash

SystemUptimeMs: 45874308
Process: system_server
Timestamp: 2024-11-08 23:17:55.331+0100
Build: google/husky/husky:15/AP3A.241105.007/2024110700:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.util.SparseArray.valueAt(SparseArray.java:346)
	at com.android.server.power.stats.PowerComponentAggregatedPowerStats.addPowerStats(PowerComponentAggregatedPowerStats.java:204)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.flushPowerStats(BinaryStatePowerStatsProcessor.java:158)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.start(BinaryStatePowerStatsProcessor.java:93)
	at com.android.server.power.stats.PowerStatsAggregator.start(PowerStatsAggregator.java:167)
	at com.android.server.power.stats.PowerStatsAggregator.aggregatePowerStats(PowerStatsAggregator.java:74)
	at com.android.server.power.stats.PowerStatsScheduler.aggregateAndStorePowerStats(PowerStatsScheduler.java:126)
	at com.android.server.power.stats.PowerStatsScheduler.$r8$lambda$GEaV9AQjfxC9uJ1Tfs7f2eF4_H0(PowerStatsScheduler.java:0)
	at com.android.server.power.stats.PowerStatsScheduler$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

**Comment by mrxx0** [comment]
Duplicate of #4274
