### ISSUE TITLE
Play store crash - 6a

### ISSUE THREAD

**Issue by DifferentWaste** [GrapheneOS/os-issue-tracker#4314]
```
type: crash
osVersion: google/bluejay/bluejay:15/AP3A.241105.007/2024110700:user/release-keys
userType: full.secondary
package: com.google.android.gms:244337035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms
processUptime: 117265 + 383 ms
installer: com.android.vending
GmsCompatConfig version: 147

fcuv: rethrowing exception from lowpool[11]
	at anne.run(:com.google.android.gms@244337035@24.43.37 (260400-693941914):43)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at bskq.mC(:com.google.android.gms@244337035@24.43.37 (260400-693941914):1)
	at bskq.dispatchMessage(:com.google.android.gms@244337035@24.43.37 (260400-693941914):138)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: eveo: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.networktransparency-NetworkDataUpdateTaskBoundService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.SecurityException: Caller uid 1210132 cannot set freezer state 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.enableAppFreezer(IActivityManager.java:10224)
	at android.os.BinderProxy$ProxyMap.getSortedInterfaceCounts(BinderProxy.java:275)
	at android.os.BinderProxy$ProxyMap.dumpProxyInterfaceCounts(BinderProxy.java:345)
	at android.os.BinderProxy$ProxyMap.set(BinderProxy.java:239)
	at android.os.BinderProxy.getInstance(BinderProxy.java:465)
	at android.os.Parcel.nativeReadStrongBinder(Native Method)
	at android.os.Parcel.readStrongBinder(Parcel.java:3364)
	at android.net.INetworkStatsService$Stub$Proxy.openSessionForUsageStats(INetworkStatsService.java:482)
	at android.app.usage.NetworkStats.<init>(NetworkStats.java:111)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTagState(NetworkStatsManager.java:686)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTagState(NetworkStatsManager.java:648)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTag(NetworkStatsManager.java:596)
	at clhp.a(:com.google.android.gms@244337035@24.43.37 (260400-693941914):28)
	at clgz.b(:com.google.android.gms@244337035@24.43.37 (260400-693941914):90)
	at gnhn.v(:com.google.android.gms@244337035@24.43.37 (260400-693941914):11)
	at gnqu.run(:com.google.android.gms@244337035@24.43.37 (260400-693941914):112)
	at gocv.run(:com.google.android.gms@244337035@24.43.37 (260400-693941914):4)
	at annu.c(:com.google.android.gms@244337035@24.43.37 (260400-693941914):50)
	at annu.run(:com.google.android.gms@244337035@24.43.37 (260400-693941914):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at ante.run(:com.google.android.gms@244337035@24.43.37 (260400-693941914):8)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enableAppFreezer(ActivityManagerService.java:21154)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5353)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2818)
	at android.os.Binder.execTransactInternal(Binder.java:1529)
	at android.os.Binder.execTransact(Binder.java:1468)
```

**Comment by muhomorr** [comment]
This crash seems to be caused by a resource leak in Play services. It indicates that Play services has hit a limit of 25000 BinderProxy objects, which is way higher than what it needs.

**Comment by muhomorr** [comment]
@DifferentWaste Is this crash reproducible?

**Comment by vivident4004** [comment]
I nave experienced a similar crash today, but on a Pixel 8. This is the first time this bug appeared. I just opened the profile where the Play services are installed, and I saw this notification. I don't know how to reproduce the bug, since I didn't do anything apart from opening Proton VPN.

```
type: crash
osVersion: google/shiba/shiba:15/AP4A.250205.002/2025030300:user/release-keys
userType: full.secondary
flags: dev options enabled
package: com.google.android.gms:250632035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms
processUptime: 92113 + 373 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 154

fnle: rethrowing exception from lowpool[2]
	at astj.run(:com.google.android.gms@250632035@25.06.32 (260400-724425688):43)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at bzbw.mz(:com.google.android.gms@250632035@25.06.32 (260400-724425688):1)
	at bzbw.dispatchMessage(:com.google.android.gms@250632035@25.06.32 (260400-724425688):138)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: ffpg: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.networktransparency-NetworkDataUpdateTaskBoundService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.SecurityException: Caller uid 1010182 cannot set freezer state 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3240)
	at android.os.Parcel.createException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3200)
	at android.os.Parcel.readException(Parcel.java:3142)
	at android.app.IActivityManager$Stub$Proxy.enableAppFreezer(IActivityManager.java:10224)
	at android.os.BinderProxy$ProxyMap.getSortedInterfaceCounts(BinderProxy.java:275)
	at android.os.BinderProxy$ProxyMap.dumpProxyInterfaceCounts(BinderProxy.java:345)
	at android.os.BinderProxy$ProxyMap.set(BinderProxy.java:239)
	at android.os.BinderProxy.getInstance(BinderProxy.java:465)
	at android.os.Parcel.nativeReadStrongBinder(Native Method)
	at android.os.Parcel.readStrongBinder(Parcel.java:3353)
	at android.net.INetworkStatsService$Stub$Proxy.openSessionForUsageStats(INetworkStatsService.java:496)
	at android.app.usage.NetworkStats.<init>(NetworkStats.java:111)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTagState(NetworkStatsManager.java:686)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTagState(NetworkStatsManager.java:648)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTag(NetworkStatsManager.java:596)
	at csvn.a(:com.google.android.gms@250632035@25.06.32 (260400-724425688):35)
	at csux.jL(:com.google.android.gms@250632035@25.06.32 (260400-724425688):90)
	at gzpp.v(:com.google.android.gms@250632035@25.06.32 (260400-724425688):11)
	at gzzb.run(:com.google.android.gms@250632035@25.06.32 (260400-724425688):112)
	at hamd.run(:com.google.android.gms@250632035@25.06.32 (260400-724425688):4)
	at astz.c(:com.google.android.gms@250632035@25.06.32 (260400-724425688):50)
	at astz.run(:com.google.android.gms@250632035@25.06.32 (260400-724425688):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at aszk.run(:com.google.android.gms@250632035@25.06.32 (260400-724425688):8)
	at java.lang.Thread.run(Thread.java:1117)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enableAppFreezer(ActivityManagerService.java:19083)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5353)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2679)
	at android.os.Binder.execTransactInternal(Binder.java:1436)
	at android.os.Binder.execTransact(Binder.java:1375)
```

[Error in Google Play Services c148658aa3aa.txt](https://github.com/user-attachments/files/19089945/Error.in.Google.Play.Services.c148658aa3aa.txt)
