### ISSUE TITLE
Google Play is crashing

### ISSUE THREAD

**Issue by egomaniac9023** [GrapheneOS/os-issue-tracker#4343]
```
type: crash
osVersion: google/bluejay/bluejay:15/AP3A.241105.007/2024110700:user/release-keys
package: com.android.vending:84352630, targetSdk 35
process: com.android.vending
processUptime: 473411 + 343 ms
installer: com.android.vending
GmsCompatConfig version: 149

java.lang.RuntimeException: Unable to destroy activity {com.android.vending/com.android.vending.AssetBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.LinearLayoutManager.O()' on a null object reference
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5997)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6029)
at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:46)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:225)
at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:107)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2645)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8744)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ExecInit.main(ExecInit.java:50)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.LinearLayoutManager.O()' on a null object reference
at aadr.e(PG:5)
at agod.U(PG:54)
at agod.T(PG:3)
at qwp.i(PG:8)
at qxz.i(PG:1)
at qwq.g(PG:10)
at jpi.j(PG:39)
at qws.i(PG:33)
at aaki.kQ(PG:3)
at aplr.f(PG:1588)
at cq.a(PG:11)
at cr.e(PG:20)
at cs.f(PG:110)
at bu.D(PG:59)
at bu.t(PG:88)
at bb.onDestroy(PG:12)
at eq.onDestroy(PG:1)
at zzzi.onDestroy(PG:1)
at xmo.onDestroy(PG:22)
at kyc.onDestroy(PG:1)
at android.app.Activity.performDestroy(Activity.java:9346)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1566)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5984)
... 16 more
```

**Comment by le-peachfiend** [comment]
Foolishly scanned QR code on new Pixel 8a for "Set up using another device. 

```
type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241105.007/2024111800:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms
processUptime: 2047087 + 337 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.SecurityException: getAvailableSubscriptionInfoList. Does not have any of the following permissions. [android.permission.READ_PRIVILEGED_PHONE_STATE]
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at com.android.internal.telephony.ISub$Stub$Proxy.getAvailableSubscriptionInfoList(ISub.java:1697)
	at android.telephony.SubscriptionManager.getAvailableSubscriptionInfoList(SubscriptionManager.java:2131)
	at com.google.android.gms.esim.transferengine.EsimTransferEngine.f(:com.google.android.gms@244433035@24.44.33 (260400-694629214):5)
	at com.google.android.gms.esim.transferengine.EsimTransferEngine.k(:com.google.android.gms@244433035@24.44.33 (260400-694629214):31)
	at com.google.android.gms.esim.init.EsimModuleInitIntentOperation.onHandleIntent(:com.google.android.gms@244433035@24.44.33 (260400-694629214):101)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@244433035@24.44.33 (260400-694629214):2)
	at ajkn.onHandleIntent(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at ojx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):70)
	at ojw.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):152)
	at evzh.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by GOS6** [comment]
type: crash
osVersion: google/bluejay/bluejay:15/AP3A.241105.007/2024111800:user/release-keys
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 38609310 + 568 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 2962, callerPackage: com.google.android.gms
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1947)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1894)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at frw.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):45)
	at frw.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):7)
	at com.google.android.location.geofencer.service.GeofencerStateMachine.g(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at epmf.accept(:com.google.android.gms@244433035@24.44.33 (260400-694629214):245)
	at buyx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):11)
	at anqt.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):50)
	at anqt.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at anwd.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: evzs: 
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)
