### ISSUE TITLE
Google play crash

### ISSUE THREAD

**Issue by kolshy420** [GrapheneOS/os-issue-tracker#4345]
```
type: crash
osVersion: google/akita/akita:15/AP3A.241105.007/2024110700:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244433035, targetSdk 35
process: com.google.android.gms.ui
processUptime: 488694 + 283 ms
installer: com.android.vending
GmsCompatConfig version: 147

java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.type' on a null object reference in method 'int com.android.server.content.SyncManager.computeSyncable(android.accounts.Account, int, java.lang.String, boolean, boolean)'
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3257)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.content.IContentService$Stub$Proxy.getIsSyncable(IContentService.java:1353)
	at android.content.ContentResolver.getIsSyncable(ContentResolver.java:3546)
	at deoq.p(:com.google.android.gms@244433035@24.44.33 (260400-694629214):3)
	at deoj.r(:com.google.android.gms@244433035@24.44.33 (260400-694629214):9)
	at deoj.p(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at deoj.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):5)
	at gtl.d(:com.google.android.gms@244433035@24.44.33 (260400-694629214):53)
	at gtm.im(:com.google.android.gms@244433035@24.44.33 (260400-694629214):27)
	at gtp.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):3)
	at gtq.o(:com.google.android.gms@244433035@24.44.33 (260400-694629214):40)
	at gvj.a(:com.google.android.gms@244433035@24.44.33 (260400-694629214):46)
	at gvh.eR(:com.google.android.gms@244433035@24.44.33 (260400-694629214):3)
	at gtp.eR(:com.google.android.gms@244433035@24.44.33 (260400-694629214):13)
	at gtm.ki(:com.google.android.gms@244433035@24.44.33 (260400-694629214):29)
	at gtm.f(:com.google.android.gms@244433035@24.44.33 (260400-694629214):42)
	at gtm.l(:com.google.android.gms@244433035@24.44.33 (260400-694629214):15)
	at gti.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):19)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by Timel737** [comment]
[Error in Google Play services a056b7590c57.txt](https://github.com/user-attachments/files/17787861/Error.in.Google.Play.services.a056b7590c57.txt)

**Comment by Timel737** [comment]
Same crash since recent update

**Comment by Timel737** [comment]
It only started after the recent GPlay update on 14 Nov. 

The crash notification pops up at rather random times. I will pay close attention to when it next happens and try and make a correlation. I will respond to this email thread with my findings. 

Thanks for reaching out. 

Tim

**Comment by muhomorr** [comment]
@Timel737 The crash that you've posted is not the same as the original. The next OS release should include a fix for it.

**Comment by muhomorr** [comment]
@kolshy420 Is this crash reproducible? It looks like a bug in Play services UI.

**Comment by Timel737** [comment]
Thanks

I'm didn't read all the way through the crash log.

The crash isn't super consistent and has only happened a couple of times since the 14th. I haven't determined what set it off (not sure if I can do anything to reproduce it).  It doesn't seem to interface with the OS or the phones functioning.

Thanks for following up.

Tim
