### ISSUE TITLE
Android Auto Crash

### ISSUE THREAD

**Issue by routersecskisthedude** [GrapheneOS/os-issue-tracker#4365]
```
type: crash
osVersion: google/husky/husky:15/AP3A.241105.007/2024111800:user/release-keys
package: com.google.android.projection.gearhead:129643854, targetSdk 35
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:car
processUptime: 8658 + 258 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 150

java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@1518543f: AdapterService getBondState
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3251)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.bluetooth.IBluetooth$Stub$Proxy.getBondState(IBluetooth.java:2701)
	at android.bluetooth.BluetoothDevice$2.apply(BluetoothDevice.java:2066)
	at android.bluetooth.BluetoothDevice$2.apply(BluetoothDevice.java:2051)
	at android.app.PropertyInvalidatedCache.recompute(PropertyInvalidatedCache.java:775)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.os.IpcDataCache.query(IpcDataCache.java:360)
	at android.bluetooth.BluetoothDevice.getBondState(BluetoothDevice.java:2108)
	at pqg.a(SourceFile:3)
	at pqy.h(SourceFile:44)
	at pqm.d(SourceFile:162)
	at pqm.c(SourceFile:315)
	at rdh.m(SourceFile:35)
	at pse.run(SourceFile:1002)
	at pqq.onServiceConnected(SourceFile:122)
	at android.bluetooth.BluetoothAdapter$ProfileConnection.connect(BluetoothAdapter.java:906)
	at android.bluetooth.BluetoothAdapter.lambda$getProfileProxy$0(BluetoothAdapter.java:3593)
	at android.bluetooth.BluetoothAdapter.$r8$lambda$hVDf6ETlKaEPiQ6OcMRJtNWsJSg(Unknown Source:0)
	at android.bluetooth.BluetoothAdapter$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by routersecskisthedude** [comment]
Another one

```
type: crash
osVersion: google/husky/husky:15/AP4A.241205.013/2024121200:user/release-keys
package: com.google.android.projection.gearhead:132644464, targetSdk 35
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:car
processUptime: 108828 + 215 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 152

java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@7bafb0a5: AdapterService getBondState
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3240)
	at android.os.Parcel.createException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3200)
	at android.os.Parcel.readException(Parcel.java:3142)
	at android.bluetooth.IBluetooth$Stub$Proxy.getBondState(IBluetooth.java:2691)
	at android.bluetooth.BluetoothDevice$2.apply(BluetoothDevice.java:1993)
	at android.bluetooth.BluetoothDevice$2.apply(BluetoothDevice.java:1978)
	at android.app.PropertyInvalidatedCache.recompute(PropertyInvalidatedCache.java:822)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:1046)
	at android.os.IpcDataCache.query(IpcDataCache.java:361)
	at android.bluetooth.BluetoothDevice.getBondState(BluetoothDevice.java:2036)
	at pwy.a(SourceFile:3)
	at pxq.h(SourceFile:44)
	at pxe.d(SourceFile:1452)
	at pxe.c(SourceFile:315)
	at swn.o(SourceFile:35)
	at pup.run(SourceFile:148)
	at pxi.onServiceConnected(SourceFile:122)
	at android.bluetooth.BluetoothAdapter$ProfileConnection.connect(BluetoothAdapter.java:903)
	at android.bluetooth.BluetoothAdapter.lambda$getProfileProxy$6(BluetoothAdapter.java:3699)
	at android.bluetooth.BluetoothAdapter.$r8$lambda$Loe3538lYg72NcoH44jZdACBXug(Unknown Source:0)
	at android.bluetooth.BluetoothAdapter$$ExternalSyntheticLambda7.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by routersecskisthedude** [comment]
I have 'Allow permissions for wired android auto' and  'allow to reroute audio from device to the car' enabled. However when connected, some apps do not play audio through the car, so I connect to the car  by Bluetooth as well to play sound from them. I am, in effect,  creating two separate interfaces to the car. If I connect Bluetooth first then AA, there is no problem. If I connect AA first then Bluetooth, AA crashes then restarts.
