### ISSUE TITLE
Error in Google Play services.

### ISSUE THREAD

**Issue by akeh-gh** [GrapheneOS/os-issue-tracker#4379]
Clicked the report button and here is what was copied to my clipboard:

type: crash
osVersion: google/shiba/shiba:15/AP3A.241105.007/2024111800:user/release-keys
userType: profile.private
flags: dev options enabled
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 41878880 + 422 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 22417, callerPackage: com.google.android.gms
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1947)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1894)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1881)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:763)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:763)
	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244433035@24.44.33 (260400-694629214):4)
	at brdu.a(:com.google.android.gms@244433035@24.44.33 (260400-694629214):2)
	at com.google.android.location.geofencer.service.GeofencerStateMachine.g(:com.google.android.gms@244433035@24.44.33 (260400-694629214):129)
	at epmf.accept(:com.google.android.gms@244433035@24.44.33 (260400-694629214):245)
	at buyx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):11)
	at anqt.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):50)
	at anqt.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at anwd.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: evzs: 
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)
```

**Comment by GOS6** [comment]
type: crash
osVersion: google/bluejay/bluejay:15/AP3A.241105.007/2024111800:user/release-keys
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 38609310 + 568 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 2962, callerPackage: com.google.android.gms
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1947)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1894)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at frw.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):45)
	at frw.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):7)
	at com.google.android.location.geofencer.service.GeofencerStateMachine.g(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at epmf.accept(:com.google.android.gms@244433035@24.44.33 (260400-694629214):245)
	at buyx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):11)
	at anqt.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):50)
	at anqt.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at anwd.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: evzs: 
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)

**Comment by muhomorr** [comment]
What was happening at the time of the crash? Does it crash regularly?

**Comment by GOS6** [comment]
When switching profiles

**Comment by akeh-gh** [comment]
Happened again.  Was not using my device when the crash occurred.  Before the crash I was browsing reddit on vanadium.  Set my phone down for about 20 minutes.  The notification of the crash was there when I unlocked my phone.

```
type: crash
osVersion: google/shiba/shiba:15/AP3A.241105.007/2024111800:user/release-keys
userType: profile.private
flags: dev options enabled
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 72265036 + 335 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.RuntimeException: Unable to create service com.google.android.gms.personalsafety.service.PSAService: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 22735, callerPackage: com.google.android.gms
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5012)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2453)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 22735, callerPackage: com.google.android.gms
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1947)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1894)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at frw.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):45)
	at com.google.android.gms.common.util.ScreenEventMonitor.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):45)
	at com.google.android.gms.personalsafety.service.PSAChimeraService.onCreate(:com.google.android.gms@244433035@24.44.33 (260400-694629214):22)
	at oia.onCreate(:com.google.android.gms@244433035@24.44.33 (260400-694629214):18)
	at ajeu.onCreate(:com.google.android.gms@244433035@24.44.33 (260400-694629214):16)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4999)
	... 11 more
```

**Comment by Barnminer** [comment]
I'm getting a crash too
```
type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241105.007/2024111800:user/release-keys
userType: full.secondary
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 30397704 + 331 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 5564, callerPackage: com.google.android.gms
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1947)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1894)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at frw.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):45)
	at frw.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):7)
	at com.google.android.location.geofencer.service.GmsActivityDetector.g(:com.google.android.gms@244433035@24.44.33 (260400-694629214):16)
	at epmf.accept(:com.google.android.gms@244433035@24.44.33 (260400-694629214):258)
	at buyx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):11)
	at anqt.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):50)
	at anqt.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at anwd.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: evzs: 
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)
```

**Comment by Barnminer** [comment]
I am having the same issue

```
type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241105.007/2024111800:user/release-keys
userType: full.secondary
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 31369815 + 411 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 22199, callerPackage: com.google.android.gms
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1947)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1894)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:776)
	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at frw.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):45)
	at frw.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):7)
	at com.google.android.location.geofencer.service.GmsActivityDetector.g(:com.google.android.gms@244433035@24.44.33 (260400-694629214):16)
	at epmf.accept(:com.google.android.gms@244433035@24.44.33 (260400-694629214):258)
	at buyx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):11)
	at anqt.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):50)
	at anqt.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at anwd.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: evzs: 
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)

description: crash while not using in second profile
```

**Comment by gitlacf** [comment]
Perhaps this is related? Just occurred.
````
type: crash
osVersion: google/husky/husky:15/AP4A.250105.002/2025010700:user/release-keys
package: com.android.vending:84411730, targetSdk 35
process: com.android.vending
processUptime: 2537006 + 263 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 152

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 540536 bytes
Bundle stats:
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=90744]
    androidx.lifecycle.internal.SavedStateHandlesProvider [size=3672]
      androidx.lifecycle.ViewModelProvider.DefaultKey:afyc [size=3544]
        savedState [size=3500]
          persistFilterIdsState [size=3436]
    fhb:2131427546 [size=85988]
      d5fpd0 [size=85692]
  nav_controller_state [size=447032]
    android-support-nav:controller:backStack [size=446928]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.TransactionTooLargeException: data parcel size 540536 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:598)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1498)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:100)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	... 10 more

**Comment by a-keh** [comment]
> Is it still happening?

I haven't had this issue occur in a while.
