### ISSUE TITLE
android auto crashes in latest build

### ISSUE THREAD

**Issue by readefries** [GrapheneOS/os-issue-tracker#4387]
When stopping the car, the app crashes:

```
type: crash
osVersion: google/akita/akita:15/AP3A.241105.007/2024111800:user/release-keys
package: com.google.android.projection.gearhead:129643854, targetSdk 35
sharedUid: com.google.android.projection.gearhead
process: com.google.android.projection.gearhead:car
processUptime: 80749 + 342 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 150

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } in qjt@2b1c35a
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1827)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.google.android.projection.gearhead/com.google.android.apps.auto.carservice.gmscorecompat.CarStartupServiceImpl
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5095)
	at android.os.Parcel.readParcelable(Parcel.java:5077)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3246)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7231)
	at android.app.Service.startForeground(Service.java:778)
	at qju.c(SourceFile:367)
	at qju.e(SourceFile:39)
	at qjt.a(SourceFile:585)
	at prj.onReceive(SourceFile:1)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1819)
	... 12 more
```

**Comment by readefries** [comment]
I'm running it on a Pixel 8a

**Comment by muhomorr** [comment]
Try updating to Android Auto 13.1, it's in alpha channel in App Store.

**Comment by readefries** [comment]
Aah, thanks. Installing it now. Will keep you posted

**Comment by readefries** [comment]
Hmmn, still getting these crashes when disconnecting the charging cable in the latest alpha build. Is there anything I can do to gather more information about this?
