### ISSUE TITLE
Crash during signal call

### ISSUE THREAD

**Issue by Neuromancer-1937** [GrapheneOS/os-issue-tracker#4394]
Graphene crashed right after a phone call. Not sure what happened. 

```
type: crash
flags: dev options enabled

SystemUptimeMs: 29745378
Process: system_server
Timestamp: 2024-11-26 19:10:18.066-0500
Build: google/akita/akita:15/AP3A.241105.007/2024111800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: Too late for abort.
	at com.android.server.wm.TransitionController.onAbort(TransitionController.java:1288)
	at com.android.server.wm.Transition.onTransactionReady(Transition.java:1712)
	at com.android.server.wm.BLASTSyncEngine$SyncGroup.finishNow(BLASTSyncEngine.java:274)
	at com.android.server.wm.BLASTSyncEngine$SyncGroup.-$$Nest$mfinishNow(BLASTSyncEngine.java:0)
	at com.android.server.wm.BLASTSyncEngine.abort(BLASTSyncEngine.java:532)
	at com.android.server.wm.Transition.abort(Transition.java:1619)
	at com.android.server.wm.ActivityTaskManagerService.lambda$enterPictureInPictureMode$10(ActivityTaskManagerService.java:3794)
	at com.android.server.wm.ActivityTaskManagerService.$r8$lambda$3nQTinSllhan__fYna_uMJMefPs(ActivityTaskManagerService.java:0)
	at com.android.server.wm.ActivityTaskManagerService$$ExternalSyntheticLambda17.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by empratyush** [comment]
how to reproduce this?

**Comment by Neuromancer-1937** [comment]
Not sure. I can try to do so and see what the conditions are


On February 11, 2025 4:26:48 AM PST, Pratyush ***@***.***> wrote:
>how to reproduce this?
>

Gibs
