### ISSUE TITLE
system_server crash

### ISSUE THREAD

**Issue by grillmaxwell** [GrapheneOS/os-issue-tracker#4398]
Hi.

It happens when switching to a second profile.

```
type: crash

SystemUptimeMs: 5318703
Process: system_server
Timestamp: 2024-11-27 08:18:23.231+0100
Build: google/cheetah/cheetah:15/AP3A.241105.007/2024111800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.OutOfMemoryError: Failed to allocate a 112 byte allocation with 1355136 free bytes and 1323KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.server.usage.UsageStatsProtoV2.parseEvent(UsageStatsProtoV2.java:241)
	at com.android.server.usage.UsageStatsProtoV2.read(UsageStatsProtoV2.java:522)
	at com.android.server.usage.UsageStatsDatabase.readLocked(UsageStatsDatabase.java:1172)
	at com.android.server.usage.UsageStatsDatabase.readLocked(UsageStatsDatabase.java:1126)
	at com.android.server.usage.UsageStatsDatabase.readLocked(UsageStatsDatabase.java:1108)
	at com.android.server.usage.UsageStatsDatabase.getLatestUsageStats(UsageStatsDatabase.java:762)
	at com.android.server.usage.UserUsageStatsService.loadActiveStats(UserUsageStatsService.java:923)
	at com.android.server.usage.UserUsageStatsService.rolloverStats(UserUsageStatsService.java:874)
	at com.android.server.usage.UserUsageStatsService.reportEvent(UserUsageStatsService.java:317)
	at com.android.server.usage.UsageStatsService.reportEvent(UsageStatsService.java:1260)
	at com.android.server.usage.UsageStatsService.onUserUnlocked(UsageStatsService.java:556)
	at com.android.server.usage.UsageStatsService.-$$Nest$monUserUnlocked(UsageStatsService.java:0)
	at com.android.server.usage.UsageStatsService$H.handleMessage(UsageStatsService.java:2119)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

description: crash
```

**Comment by stanlee786** [comment]
I've had it happen to me while not using my phone. See the log below.

```
type: crash
flags: dev options enabled

SystemUptimeMs: 96932013
Process: system_server
Timestamp: 2024-11-28 04:03:50.311+0100
Build: google/shiba/shiba:15/AP3A.241105.007/2024111800:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.util.SparseArray.valueAt(SparseArray.java:346)
	at com.android.server.power.stats.PowerComponentAggregatedPowerStats.addPowerStats(PowerComponentAggregatedPowerStats.java:204)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.flushPowerStats(BinaryStatePowerStatsProcessor.java:158)
	at com.android.server.power.stats.BinaryStatePowerStatsProcessor.start(BinaryStatePowerStatsProcessor.java:93)
	at com.android.server.power.stats.PowerStatsAggregator.start(PowerStatsAggregator.java:167)
	at com.android.server.power.stats.PowerStatsAggregator.aggregatePowerStats(PowerStatsAggregator.java:74)
	at com.android.server.power.stats.PowerStatsScheduler.aggregateAndStorePowerStats(PowerStatsScheduler.java:126)
	at com.android.server.power.stats.PowerStatsScheduler.$r8$lambda$GEaV9AQjfxC9uJ1Tfs7f2eF4_H0(PowerStatsScheduler.java:0)
	at com.android.server.power.stats.PowerStatsScheduler$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

**Comment by stanlee786** [comment]
@thestinger Alright I have developer options disabled.

**Comment by stanlee786** [comment]
@thestinger could you explain on how that would fix this bug, I'm interested

**Comment by stanlee786** [comment]
@thestinger No, but it happened randomly. I have had Developer settings enabled for a week without this happening.

**Comment by rookie-ger** [comment]
Same Situation here: 

`type: crash

SystemUptimeMs: 39476312
Process: system_server
Timestamp: 2025-02-19 17:30:39.899+0100
Build: google/oriole/oriole:15/AP4A.250205.002/2025021100:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:289)
	at android.app.ConfigurationController.handleConfigurationChangedInner(ConfigurationController.java:202)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:154)
	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:129)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6704)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:56)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2728)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at com.android.server.SystemServer.run(SystemServer.java:995)
	at com.android.server.SystemServer.main(SystemServer.java:673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)

description: When trying to switch to secondary user where Mullvad VPN, Whatsapp and Telegram should be running at the same time.  `
