### ISSUE TITLE
Google Play Dienste has crashed

### ISSUE THREAD

**Issue by Th3s3uss** [GrapheneOS/os-issue-tracker#4415]
```
type: crash
osVersion: google/raven/raven:15/AP3A.241105.007/2024112700:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms
processUptime: 8210225 + 311 ms
installer: com.android.vending
GmsCompatConfig version: 150

java.lang.SecurityException: DCL via storage, path: /data/user_de/0/com.google.android.gms/app_chimera/m/000000af/dl-VisionOcr.optional_244433100000.apk
	at android.ext.dcl.DynCodeLoading.checkDexFileOpen(DynCodeLoading.java:132)
	at dalvik.system.DexFile.openDexFileNative(Native Method)
	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
	at dalvik.system.DexFile.<init>(DexFile.java:128)
	at dalvik.system.DexFile.<init>(DexFile.java:101)
	at dalvik.system.DexPathList.loadDexFile(DexPathList.java:438)
	at dalvik.system.DexPathList.makeDexElements(DexPathList.java:397)
	at dalvik.system.DexPathList.<init>(DexPathList.java:166)
	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:160)
	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:105)
	at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:71)
	at dalvik.system.DelegateLastClassLoader.<init>(DelegateLastClassLoader.java:114)
	at ogr.f(:com.google.android.gms@244433035@24.44.33 (260400-694629214):60)
	at okm.b(:com.google.android.gms@244433035@24.44.33 (260400-694629214):36)
	at olf.a(:com.google.android.gms@244433035@24.44.33 (260400-694629214):325)
	at ogb.g(:com.google.android.gms@244433035@24.44.33 (260400-694629214):117)
	at com.google.android.gms.chimera.container.dynamite.GmsProcessDynamiteLoaderImpl.loadModule(:com.google.android.gms@244433035@24.44.33 (260400-694629214):149)
	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext3NoCrashUtils(:com.google.android.gms@244433035@24.44.33 (260400-694629214):55)
	at com.google.android.gms.dynamite.DynamiteModule.f(:com.google.android.gms@244433035@24.44.33 (260400-694629214):374)
	at dwkp.a(:com.google.android.gms@244433035@24.44.33 (260400-694629214):38)
	at dwkp.<init>(:com.google.android.gms@244433035@24.44.33 (260400-694629214):28)
	at dwky.a(:com.google.android.gms@244433035@24.44.33 (260400-694629214):3)
	at com.google.android.gms.ocr.service.OcrModelUpdateStateIntentOperation.onHandleIntent(:com.google.android.gms@244433035@24.44.33 (260400-694629214):95)
	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@244433035@24.44.33 (260400-694629214):2)
	at ajkn.onHandleIntent(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at ojx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):70)
	at ojw.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):152)
	at evzh.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Th3s3uss** [comment]
This crash happens about 20 times a day.
