### ISSUE TITLE
Error in Google Play Services

### ISSUE THREAD

**Issue by reyna-del-mar** [GrapheneOS/os-issue-tracker#4422]
```
type: crash
osVersion: google/coral/coral:13/TP1A.221005.002.B2/2024092100:user/release-keys
package: com.google.android.gms:244034029
process: com.google.android.gms
processUptime: 80842317 + 736 ms
installer: app.grapheneos.apps
GmsCompatConfig version: 150

fayg: rethrowing exception from lowpool[11]
	at anls.run(:com.google.android.gms@244034029@24.40.34 (190400-682300402):43)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at brnl.mz(:com.google.android.gms@244034029@24.40.34 (190400-682300402):1)
	at brnl.dispatchMessage(:com.google.android.gms@244034029@24.40.34 (190400-682300402):138)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: etin: 
		at tk_trace.ScheduledTaskImpl(Unknown Source:0)
		at tk_trace.networktransparency-NetworkDataUpdateTaskBoundService_onRunTaskAsync(Unknown Source:0)
Caused by: java.lang.SecurityException: Calling identity is not authorized
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.net.INetworkStatsService$Stub$Proxy.openSessionForUsageStats(INetworkStatsService.java:469)
	at android.app.usage.NetworkStats.<init>(NetworkStats.java:111)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTagState(NetworkStatsManager.java:661)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTagState(NetworkStatsManager.java:623)
	at android.app.usage.NetworkStatsManager.queryDetailsForUidTag(NetworkStatsManager.java:571)
	at cklx.a(:com.google.android.gms@244034029@24.40.34 (190400-682300402):28)
	at cklh.b(:com.google.android.gms@244034029@24.40.34 (190400-682300402):90)
	at glii.v(:com.google.android.gms@244034029@24.40.34 (190400-682300402):11)
	at glrp.run(:com.google.android.gms@244034029@24.40.34 (190400-682300402):112)
	at gmdl.run(:com.google.android.gms@244034029@24.40.34 (190400-682300402):4)
	at anmi.c(:com.google.android.gms@244034029@24.40.34 (190400-682300402):50)
	at anmi.run(:com.google.android.gms@244034029@24.40.34 (190400-682300402):76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at anrt.run(:com.google.android.gms@244034029@24.40.34 (190400-682300402):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkCallAuthorization(Preconditions.java:247)
	at com.android.server.devicepolicy.DevicePolicyManagerService.getProfileOwnerAsUser(DevicePolicyManagerService.java:9230)
	at android.app.admin.DevicePolicyManager.isProfileOwnerApp(DevicePolicyManager.java:9218)
	at android.net.NetworkStatsAccess.checkAccessLevel(NetworkStatsAccess.java:145)
	at com.android.server.net.NetworkStatsService.checkAccessLevel(NetworkStatsService.java:1523)

	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more
	Suppressed: java.lang.SecurityException: Calling identity is not authorized
		... 20 more

```

**Comment by reyna-del-mar** [comment]
Hello,This issue happens regularly.Every now and then I get the notice in my phone that it has crash. Its always the same message. It happens in the background without me doing anything with the phone.About the end of the support life of the pixel, which newer model do you consider the best one to replace this one?I fell in love with Graphine,Once you go Graphine you never want to go to any other system.Great job!Thank you for all your support.
-------- Original message --------From: Daniel Micay ***@***.***> Date: 12/2/24  12:39 AM  (GMT-06:00) To: GrapheneOS/os-issue-tracker ***@***.***> Cc: reyna-del-mar ***@***.***>, Author ***@***.***> Subject: Re: [GrapheneOS/os-issue-tracker] Error in Google Play Services (Issue #4422) 
Does this issue occur regularly or it only happened once such as when doing something specific?
You're on an end-of-life 4th generation Pixel which is no longer really supported beyond emergency legacy extended support releases.
