### ISSUE TITLE
Gmscompat crashing 

### ISSUE THREAD

**Issue by sprucemeerkat** [GrapheneOS/os-issue-tracker#4447]
```
type: crash
osVersion: google/akita/akita:15/AP3A.241105.007/2024120400:user/release-keys
package: com.google.android.gms:244433035, targetSdk 35
sharedUid: com.google.uid.shared
process: com.google.android.gms.persistent
processUptime: 58657867 + 281 ms
installer: com.android.vending
GmsCompatConfig version: 151

java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 3144, callerPackage: com.google.android.gms
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3259)
	at android.os.Parcel.createException(Parcel.java:3235)
	at android.os.Parcel.readException(Parcel.java:3211)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1947)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1894)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1881)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:763)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:763)
	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244433035@24.44.33 (260400-694629214):4)
	at brdu.a(:com.google.android.gms@244433035@24.44.33 (260400-694629214):2)
	at com.google.android.location.geofencer.service.GeofencerStateMachine.g(:com.google.android.gms@244433035@24.44.33 (260400-694629214):129)
	at epmf.accept(:com.google.android.gms@244433035@24.44.33 (260400-694629214):245)
	at buyx.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):11)
	at anqt.c(:com.google.android.gms@244433035@24.44.33 (260400-694629214):50)
	at anqt.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at anwd.run(:com.google.android.gms@244433035@24.44.33 (260400-694629214):8)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: evzs: 
		at tk_trace.location_base-GoogleLocationManagerChimeraService_onCreate(Unknown Source:0)
```

**Comment by sprucemeerkat** [comment]
Issue happens almost once a day. I don't notice any loss of functionality.

**Comment by sprucemeerkat** [comment]
>
