### ISSUE TITLE
System Crash after Update restart

### ISSUE THREAD

**Issue by Tealk** [GrapheneOS/os-issue-tracker#4477]
```
type: crash

SystemUptimeMs: 161455
Process: system_server
Timestamp: 2024-12-10 19:39:41.812+0100
Build: google/comet/comet:15/AP4A.241205.013/2024120900:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.telephony.TelephonyManager.isDataEnabledForReason(TelephonyManager.java:14431)
	at android.telephony.TelephonyManager.isDataEnabledForReason(TelephonyManager.java:14418)
	at android.telephony.TelephonyManager.isDataEnabled(TelephonyManager.java:11718)
	at android.telephony.TelephonyManager.getDataEnabled(TelephonyManager.java:11685)
	at com.android.server.location.gnss.GnssNetworkConnectivityHandler.handleUpdateNetworkState(GnssNetworkConnectivityHandler.java:468)
	at com.android.server.location.gnss.GnssNetworkConnectivityHandler.-$$Nest$mhandleUpdateNetworkState(GnssNetworkConnectivityHandler.java:0)
	at com.android.server.location.gnss.GnssNetworkConnectivityHandler$2.onCapabilitiesChanged(GnssNetworkConnectivityHandler.java:401)
	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:4287)
	at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:4252)
	at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:4705)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
Caused by: android.os.DeadSystemException
	... 15 more
```

**Comment by Tealk** [comment]
> Does it happen repeatedly or did it only happen once?

Only once so far, directly after the restart.

> If you haven't rebooted since then you can get it via the Log Viewer app and send it to [logs@grapheneos.org](mailto:logs@grapheneos.org).

No, I haven't yet, where can I find the log viewer?

**Comment by Tealk** [comment]
I have sent the mail.

**Comment by Tealk** [comment]
> Recommend doing a clean reboot

Is there any special instruction for this? 
Thanks for the support.
