### ISSUE TITLE
System_server crash after reboot

### ISSUE THREAD

**Issue by nick-van-h** [GrapheneOS/os-issue-tracker#4510]
Happened right after reboot after last night's system update, logged in on owner profile

```
type: crash
flags: dev options enabled

SystemUptimeMs: 164256
Process: system_server
Timestamp: 2024-12-14 13:05:55.035+0100
Build: google/lynx/lynx:15/AP4A.241205.013/2024121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.UserInfo com.android.server.pm.UserManagerInternal.getUserInfo(int)' on a null object reference
at com.android.server.SystemServiceManager.newTargetUser(SystemServiceManager.java:382)
at com.android.server.SystemServiceManager.onUserStarting(SystemServiceManager.java:391)
at com.android.server.am.UserController$Injector.onUserStarting(UserController.java:4127)
at com.android.server.am.UserController.handleMessage(UserController.java:3546)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.os.HandlerThread.run(HandlerThread.java:85)
at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by Jawshy** [comment]
I got the same issue but on a Pixel 6a (bluejay).

**Comment by Jawshy** [comment]
Here's the log [system_server crash 7714d57bd200.txt](https://github.com/user-attachments/files/18142505/system_server.crash.7714d57bd200.txt)

**Comment by Jawshy** [comment]
I'm using multiple users, but I wasn't switching between them when the crash occured. I rebooted to update then the crash occured after first unlock.

**Comment by Jawshy** [comment]
system_server crashed after rebooting to update OS. 
[system_server crash afb6d6a8ca06.txt](https://github.com/user-attachments/files/18304654/system_server.crash.afb6d6a8ca06.txt)
