### ISSUE TITLE
Random reboot

### ISSUE THREAD

**Issue by immunizedcarbon** [GrapheneOS/os-issue-tracker#4550]
Maybe it will be helpful.

`type: crash

SystemUptimeMs: 306265114
Process: system_server
Timestamp: 2024-12-21 03:39:27.882+0100
Build: google/bluejay/bluejay:15/AP4A.241205.013/2024121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
 at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
 at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:939)
 at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:791)
 at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:67)
 at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:2039)
 at com.android.server.accounts.AccountsDb.deleteGrantsByUid(AccountsDb.java:917)
 at com.android.server.accounts.AccountManagerService.purgeOldGrants(AccountManagerService.java:1456)
 at com.android.server.accounts.AccountManagerService.purgeOldGrantsAll(AccountManagerService.java:1434)
 at com.android.server.accounts.AccountManagerService.-$$Nest$mpurgeOldGrantsAll(AccountManagerService.java:0)
 at com.android.server.accounts.AccountManagerService$1$1.run(AccountManagerService.java:343)
 at android.os.Handler.handleCallback(Handler.java:991)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.os.HandlerThread.run(HandlerThread.java:85)
 at com.android.server.ServiceThread.run(ServiceThread.java:46)
`

**Comment by immunizedcarbon** [comment]
> Some kind of upstream bug, not much we can do.

I see. Thanks!
