### ISSUE TITLE
Google Play Services has crashed (while phone is not in use)

### ISSUE THREAD

**Issue by jasnn** [GrapheneOS/os-issue-tracker#4565]
Google Play Services has been periodically crashing on my main GOS/Pixel 8 Pro over the last week or so, primarily while not in use, (sitting in its charging cradle). I'll typically restart the phone and things will operate normally again for several hours.

FWIW, I have another GOS Pixel 8 Pro and Pixel Tablet, which are also exhibiting this same behavior.

Google Play Services Crash Log

```
type: logcat
osVersion: google/husky/husky:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
package: com.google.android.gms:244736036, targetSdk 35
sharedUid: com.google.uid.shared
buffers: crash
level: verbose

--------- beginning of crash
12-23 15:00:15.579  2913  2913 E AndroidRuntime: FATAL EXCEPTION: main
12-23 15:00:15.579  2913  2913 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 2913
12-23 15:00:15.579  2913  2913 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.google.android.gms.gcm.GcmService: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 2913, callerPackage: com.google.android.gms
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5093)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:109)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8826)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 2913, callerPackage: com.google.android.gms
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3248)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3224)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3200)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3142)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1994)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1937)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244736036@24.47.36 (260408-705155572):8)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at ftw.c(:com.google.android.gms@244736036@24.47.36 (260408-705155572):45)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at ftw.b(:com.google.android.gms@244736036@24.47.36 (260408-705155572):7)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at com.google.android.gms.gcm.GcmChimeraService.onCreate(:com.google.android.gms@244736036@24.47.36 (260408-705155572):229)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at pdm.onCreate(:com.google.android.gms@244736036@24.47.36 (260408-705155572):18)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at akgl.onCreate(:com.google.android.gms@244736036@24.47.36 (260408-705155572):16)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5080)
12-23 15:00:15.579  2913  2913 E AndroidRuntime: 	... 11 more
```

System Crash Log

```
type: logcat
osVersion: google/husky/husky:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
buffers: crash
level: verbose

--------- beginning of crash
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: FATAL EXCEPTION: main
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 2913
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.google.android.gms.gcm.GcmService: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 2913, callerPackage: com.google.android.gms
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5093)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:109)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8826)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 2913, callerPackage: com.google.android.gms
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3248)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3224)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3200)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3142)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6130)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1994)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1937)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at com.google.android.chimera.ModuleContext.registerReceiver(:com.google.android.gms@244736036@24.47.36 (260408-705155572):8)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:797)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at ftw.c(:com.google.android.gms@244736036@24.47.36 (260408-705155572):45)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at ftw.b(:com.google.android.gms@244736036@24.47.36 (260408-705155572):7)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at com.google.android.gms.gcm.GcmChimeraService.onCreate(:com.google.android.gms@244736036@24.47.36 (260408-705155572):229)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at pdm.onCreate(:com.google.android.gms@244736036@24.47.36 (260408-705155572):18)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at akgl.onCreate(:com.google.android.gms@244736036@24.47.36 (260408-705155572):16)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5080)
12-23 15:00:15.579 10145  2913  2913 E AndroidRuntime: 	... 11 more
```

**Comment by jasnn** [comment]
After subsequent Google Play Services updates, this is no longer occurring on any of my GOS Pixel devices.
