### ISSUE TITLE
Easy dialler constantly crashing

### ISSUE THREAD

**Issue by Maxduck** [GrapheneOS/os-issue-tracker#4567]
Pixel 8a. 
Build 2024121200
Easy dialler constantly crashing. Slows phone down to point needs hard restart.

````
type: crash
osVersion: google/akita/akita:15/AP4A.241205.013/2024121200:user/release-keys
package: com.simpler.dialer:1202, targetSdk 34
process: com.simpler.dialer
processUptime: 4321 + 352 ms
installer: com.android.vending

android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{8e7c7d5 14582:com.simpler.dialer/u0a146} targetSDK=34 has been prohibited
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:5084)
	at android.os.Parcel.readParcelable(Parcel.java:5066)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3235)
	at android.os.Parcel.createException(Parcel.java:3224)
	at android.os.Parcel.readException(Parcel.java:3200)
	at android.os.Parcel.readException(Parcel.java:3142)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7231)
	at android.app.Service.startForeground(Service.java:879)
	at m.a.a(SourceFile:1)
	at androidx.work.impl.foreground.SystemForegroundService$a.run(SourceFile:15)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```
`

**Comment by muhomorr** [comment]
This is an app bug.
