### ISSUE TITLE
Pixel 9 pro xl - system crached the system has failed after user switch

### ISSUE THREAD

**Issue by elmisiek24** [GrapheneOS/os-issue-tracker#4591]
```
type: crash

SystemUptimeMs: 69905399
Process: system_server
Timestamp: 2024-12-29 15:21:39.039+0100
Build: google/komodo/komodo:15/AP4A.241205.013/2024121200:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.RuntimeException: Keyguard is not shown in 20 seconds
	at com.android.server.am.UserController$Injector.lockDeviceNowAndWaitForKeyguardShown(UserController.java:4168)
	at com.android.server.am.UserController.startUserInternal(UserController.java:1993)
	at com.android.server.am.UserController.startUserNoChecks(UserController.java:1834)
	at com.android.server.am.UserController.startUser(UserController.java:1788)
	at com.android.server.am.UserController.startUser(UserController.java:1747)
	at com.android.server.am.UserController.startUserInForeground(UserController.java:2106)
	at com.android.server.am.UserController.handleMessage(UserController.java:3523)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by elmisiek24** [comment]
It is similarly. When I am on an additional user and logged on the main user, there is a temporary freeze of the screen and a restart of the phone. It's not the case every time, only sometimes. I'm trying to find whether it's a particular program or overall.

**Comment by elmisiek24** [comment]
I have the same method of pin and biometric.

**Comment by elmisiek24** [comment]
Hei, Can someone test this theory? The system may restart after logging in from another user to the main user because the automatic phone restart service is malfunctioning. My phone does not restart as I indicated every 2 hours, it does not restart at all, instead it restarts after changing the user. Emil.

**Comment by elmisiek24** [comment]
I understand, sorry if I misled you.
