### ISSUE TITLE
Experimental Play support: com.google.android.gms.persistent crashes

### ISSUE THREAD

**Issue by bobobo1618** [GrapheneOS/os-issue-tracker#608]
Steps to reproduce:
- Install Uber app
- Complete log-in flow
- See map screen with "Google Play services is updating"
- Terminate app (or reboot)
- Open app again

Full crash log: [ubercrashlog.txt](https://github.com/GrapheneOS/os-issue-tracker/files/6883378/ubercrashlog.txt)

It appears that Uber triggers Play Services `com.google.android.gms.persistent` to crash, which then causes Android to kill Uber:

`com.google.android.gms.persistent` crash:

```
07-27 10:05:06.754 21925 21973 E AndroidRuntime: FATAL EXCEPTION: FlpThread
07-27 10:05:06.754 21925 21973 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 21925
07-27 10:05:06.754 21925 21973 E AndroidRuntime: java.lang.SecurityException: uid 10225 does not have android.permission.UPDATE_APP_OPS_STATS.
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2357)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2340)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2282)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at com.android.internal.app.IAppOpsService$Stub$Proxy.startOperation(IAppOpsService.java:1148)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.app.AppOpsManager.startOpNoThrow(AppOpsManager.java:7980)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.app.AppOpsManager.startOpNoThrow(AppOpsManager.java:7945)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at udb.k(:com.google.android.gms@212418046@21.24.18 (150400-383468479):2)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at uds.p(:com.google.android.gms@212418046@21.24.18 (150400-383468479):20)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at uds.jj(:com.google.android.gms@212418046@21.24.18 (150400-383468479):3)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at bpev.s(:com.google.android.gms@212418046@21.24.18 (150400-383468479):22)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at bpep.run(:com.google.android.gms@212418046@21.24.18 (150400-383468479):5)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at aica.ja(:com.google.android.gms@212418046@21.24.18 (150400-383468479):0)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at aica.dispatchMessage(:com.google.android.gms@212418046@21.24.18 (150400-383468479):10)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at bqtt.ja(:com.google.android.gms@212418046@21.24.18 (150400-383468479):1)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at aica.dispatchMessage(:com.google.android.gms@212418046@21.24.18 (150400-383468479):10)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        Suppressed: bvgr: 
07-27 10:05:06.754 21925 21973 E AndroidRuntime:                at tk_trace.location_base-GoogleLocationManagerChimeraService-IGoogleLocationManagerService_58(Unknown Source:0)
07-27 10:05:06.754 21925 21973 E AndroidRuntime:        Suppressed: bvgr: 
07-27 10:05:06.754 21925 21973 E AndroidRuntime:                at tk_trace.location_base-GoogleLocationManagerChimeraService-IGoogleLocationManagerService_58(Unknown Source:0)
```

Android killing Uber:

`07-27 10:05:06.822  1390  1629 I ActivityManager: Killing 22564:com.ubercab/u0a228 (adj 0): depends on provider com.google.android.gms/.chimera.container.GmsModuleProvider in dying proc com.google.android.gms.persistent (adj 0)`

Since the error log indicates the problem is `android.permission.UPDATE_APP_OPS_STATS`, I tried to grant it, but it failed:

```
> adb shell pm grant com.google.android.gms android.permission.UPDATE_APP_OPS_STATS

Exception occurred while executing 'grant':
java.lang.SecurityException: Permission android.permission.UPDATE_APP_OPS_STATS requested by com.google.android.gms is not a changeable permission type
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:451)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1457)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1410)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2300)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:251)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21696)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4621)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4312)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by thestinger** [comment]
Some of this will be fixed by the next release but dynamite module support will be needed before anything using the modern Maps API will work. It's implemented but not merged yet. It needs careful review, some changes and testing first.

**Comment by thestinger** [comment]
This should be resolved now.

**Comment by 373252297** [comment]
@thestinger how do you fix this issue??

**Comment by thestinger** [comment]
Don't know what you mean.

**Comment by 373252297** [comment]
> 
happy to receive your reply：
issue:  Killing 22564:com.ubercab/u0a228 (adj 0): depends on provider com.google.android.gms/.chimera.container.GmsModuleProvider in dying proc com.google.android.gms.persistent (adj 0)
java.lang.SecurityException: uid 10225 does not have android.permission.UPDATE_APP_OPS_STATS.

We had the same problem with our project，so ,i want to know details of how you fixed this

**Comment by thestinger** [comment]
You'll need to clarify what you mean by "our project".

**Comment by 373252297** [comment]
> You'll need to clarify what you mean by "our project".

We are indie game developers，our game had the same problem on some android mobile device. so we hope get some help from you to fixed the problem

**Comment by thestinger** [comment]
This is only about sandboxed Google Play which is a GrapheneOS feature and isn't relevant to you.
