### ISSUE TITLE
Bunq app crashes when opening in-app QR code scanner

### ISSUE THREAD

**Issue by ellienieuwdorp** [GrapheneOS/os-issue-tracker#756]
App: bunq
Device: Pixel 5
Build no: SP1A.210812.015.2021102503

Everything about the app (except contactless payments) seems to be working fine, but as soon as I press the 'Camera' tab in the bottom right on the nav bar the app first asks for camera permission, and after granting it instantly crashes. Then the app opens again prompting me to send a bug report to the devs. 

I've sent an email to contact@grapheneos.org with a generated bug report.

EDIT: snippet of the bug report when the crash occurs

```
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: Process: com.android.statementservice, PID: 20444
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at androidx.work.Data.toByteArrayInternal(Data.java:417)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at androidx.work.Data$Builder.build(Data.java:846)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-26 15:02:50.721 10040 20444 20474 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
10-26 15:02:50.724  1000  1754 20478 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
10-26 15:02:50.772  1000  1754  2962 I ActivityManager: Process com.android.statementservice (pid 20444) has died: cch+5 CEM 
10-26 15:02:52.914  1000  1754  2561 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.bunq.android/.ui.activity.SplashScreenActivity bnds=[440,1515][641,1852]} from uid 10090
10-26 15:02:55.490  1000  1754  2118 W UsageStatsService: Unexpected activity event reported! (com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher event : 23 instanceId : 13046177)
10-26 15:02:55.519  1000  1754  4443 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.DEFAULT,android.intent.category.LAUNCHER] flg=0x10008000 pkg=com.bunq.android cmp=com.bunq.android/.ui.activity.SplashScreenActivity (has extras)} from uid 10125
10-26 15:02:55.520  1000  1754  4443 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=244 attached=false
10-26 15:02:55.533  1000  1754  4443 I ActivityTaskManager: START u0 {flg=0x10008000 cmp=com.bunq.android/.ui.activity.ProblemReportActivity (has extras)} from uid 10125
10-26 15:02:55.535  1000  1754  4443 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=245 attached=false
10-26 15:02:55.546  1000  1754  4443 I ActivityTaskManager: Add Task{67e82dd #244 type=standard A=10125:.ycxiupwiieysyreyxhebeufomymyayitaoutwdjxbjeucqtuoosfembhoaaqfgwfmhygxnlgppvprlrmwdprulbkxguvnwffaxjh U=0 visible=true mode=fullscreen translucent=true sz=1} to hidden list because adding Task{3ab3e52 #245 type=standard A=10125:.ycxiupwiieysyreyxhebeufomymyayitaoutwdjxbjeucqtuoosfembhoaaqfgwfmhygxnlgppvprlrmwdprulbkxguvnwffaxjh U=0 visible=true mode=fullscreen translucent=true sz=1}
10-26 15:02:55.672  1000  1754 21619 I WindowManager: WIN DEATH: Window{d39f402 u0 com.bunq.android/com.bunq.android.ui.activity.main.MainActivity}
10-26 15:02:55.674  1000  1754  4443 I ActivityManager: Process com.bunq.android (pid 19317) has died: fg  TOP 
10-26 15:02:55.676  1000  1754  4443 W ActivityManager: Scheduling restart of crashed service com.bunq.android/.hce.BunqHceService in 1000ms for connection
10-26 15:02:55.682  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10125; state: DISABLED
10-26 15:02:55.682  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10125; state: DISABLED
10-26 15:02:55.682  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10125; state: DISABLED
10-26 15:02:55.682  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10125; state: ENABLED
10-26 15:02:55.683  1000  1754  2120 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10125; state: ENABLED
10-26 15:02:55.685  1000  1754  2111 W ActivityManager: setHasOverlayUi called on unknown pid: 19317
10-26 15:02:55.687  1000  1754  2112 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=242 attached=false
10-26 15:02:55.687  1000  1754  2112 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=242 attached=false
10-26 15:02:55.701  1000  1754  2120 I ActivityManager: Start proc 20541:com.bunq.android/u0a125 for top-activity {com.bunq.android/com.bunq.android.ui.activity.ProblemReportActivity}
10-26 15:02:55.986 10125 20541 20541 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG5NZ6.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G5NZ6
10-26 15:02:55.988 10125 20541 20541 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayGD1YQ.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: GD1YQ
10-26 15:02:56.005  1000  1754  2111 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{f43d9aa u0 com.bunq.android/.ui.activity.main.MainActivity t-1 f} isExiting}
10-26 15:02:56.119 10125 20541 20589 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
10-26 15:02:57.428  1000  1754 21619 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=244 attached=false
10-26 15:02:57.428  1000  1754 21619 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=244 attached=false
10-26 15:02:57.434  1000  1754  1960 W WindowManager: Failed looking up window session=Session{86fbee0 2422:u0a10094} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5582 com.android.server.wm.WindowManagerService.relayoutWindow:2222 com.android.server.wm.Session.relayout:235 
10-26 15:02:57.438  1000  1754  1960 W WindowManager: Cannot find window which accessibility connection is added to
10-26 15:02:57.441  1000  1754  1960 W WindowManager: Failed looking up window session=Session{86fbee0 2422:u0a10094} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5582 com.android.server.wm.WindowManagerService.removeWindow:2026 com.android.server.wm.Session.remove:218 
10-26 15:02:57.445  1000  1754  2118 W UsageStatsService: Unexpected activity event reported! (com.bunq.android/com.bunq.android.ui.activity.SplashScreenActivity event : 23 instanceId : 30780833)
10-26 15:02:57.634  1000  1754  2112 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=245 attached=false
10-26 15:02:57.634  1000  1754  2112 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=245 attached=false
10-26 15:03:01.648  1000  1754  4354 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.bunq.android/.ui.activity.SplashScreenActivity bnds=[440,1515][641,1852]} from uid 10090
10-26 15:03:01.650  1000  1754  4354 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=246 attached=false
10-26 15:03:01.676  1000  1754  4354 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (4147542)
10-26 15:03:01.711  1000  1754  4354 I ActivityTaskManager: START u0 {flg=0x10000 cmp=com.bunq.android/.ui.activity.main.MainActivity} from uid 10125
10-26 15:03:01.726  1000  1754  4442 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (4153280)
10-26 15:03:02.771  1000  1754 10267 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.DEFAULT,android.intent.category.LAUNCHER] flg=0x10008000 pkg=com.bunq.android cmp=com.bunq.android/.ui.activity.SplashScreenActivity (has extras)} from uid 10125
10-26 15:03:02.772  1000  1754 10267 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=247 attached=false
10-26 15:03:02.783  1000  1754 10267 I ActivityTaskManager: START u0 {flg=0x10008000 cmp=com.bunq.android/.ui.activity.ProblemReportActivity (has extras)} from uid 10125
10-26 15:03:02.785  1000  1754 10267 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=248 attached=false
10-26 15:03:02.796  1000  1754 10267 I ActivityTaskManager: Add Task{fabc39e #247 type=standard A=10125:.ycxiupwiieysyreyxhebeufomymyayitaoutwdjxbjeucqtuoosfembhoaaqfgwfmhygxnlgppvprlrmwdprulbkxguvnwffaxjh U=0 visible=true mode=fullscreen translucent=true sz=1} to hidden list because adding Task{bf09e7f #248 type=standard A=10125:.ycxiupwiieysyreyxhebeufomymyayitaoutwdjxbjeucqtuoosfembhoaaqfgwfmhygxnlgppvprlrmwdprulbkxguvnwffaxjh U=0 visible=true mode=fullscreen translucent=true sz=1}
10-26 15:03:02.922  1000  1754 10267 I ActivityManager: Process com.bunq.android (pid 20541) has died: fg  TOP 
10-26 15:03:02.923  1000  1754  5153 I WindowManager: WIN DEATH: Window{e9db9cb u0 com.bunq.android/com.bunq.android.ui.activity.main.MainActivity}
10-26 15:03:02.926  1000  1754 10267 W ActivityManager: Scheduling restart of crashed service com.bunq.android/.hce.BunqHceService in 4000ms for connection
10-26 15:03:02.942  1000  1754  2112 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=246 attached=false
10-26 15:03:02.942  1000  1754  2112 W ActivityTaskManager: Can't find TaskDisplayArea to determine support for multi window. Task id=246 attached=false
10-26 15:03:02.946  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10125; state: DISABLED
10-26 15:03:02.946  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10125; state: DISABLED
10-26 15:03:02.946  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10125; state: DISABLED
10-26 15:03:02.946  1000  1754  2111 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10125; state: ENABLED
10-26 15:03:02.946  1000  1754  2111 W ActivityManager: setHasOverlayUi called on unknown pid: 20541
10-26 15:03:02.946  1000  1754  2120 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10125; state: ENABLED
10-26 15:03:02.956  1000  1754  2120 I ActivityManager: Start proc 20773:com.bunq.android/u0a125 for top-activity {com.bunq.android/com.bunq.android.ui.activity.ProblemReportActivity}
10-26 15:03:03.255  1000  1754  2111 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{da28951 u0 com.bunq.android/.ui.activity.main.MainActivity t-1 f} isExiting}
10-26 15:03:03.256 10125 20773 20773 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG5NZ6.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G5NZ6
10-26 15:03:03.258 10125 20773 20773 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayGD1YQ.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: GD1YQ
10-26 15:03:03.313 10125 20773 20802 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
10-26 15:03:04.045  1000  1754  4442 W WindowManager: Failed looking up window session=Session{86fbee0 2422:u0a10094} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5582 com.android.server.wm.WindowManagerService.relayoutWindow:2222 com.android.server.wm.Session.relayout:235 
10-26 15:03:04.054  1000  1754  4354 W WindowManager: Cannot find window which accessibility connection is added to
10-26 15:03:04.056  1000  1754  5247 W WindowManager: Failed looking up window session=Session{86fbee0 2422:u0a10094} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5582 com.android.server.wm.WindowManagerService.removeWindow:2026 com.android.server.wm.Session.remove:218 
10-26 15:03:04.062  1000  1754  2118 W UsageStatsService: Unexpected activity event reported! (com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher event : 23 instanceId : 13046177)
10-26 15:03:10.316  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10132, delta: -26
10-26 15:03:10.316  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10085, delta: -7
10-26 15:03:10.316  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10038, delta: -4
10-26 15:03:10.316  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10067, delta: -14
10-26 15:03:10.316  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10054, delta: -1
10-26 15:03:10.316  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10075, delta: -11
10-26 15:03:10.318  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10028, delta: -16
10-26 15:03:10.318  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10036, delta: -5
10-26 15:03:10.318  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10065, delta: -5
10-26 15:03:10.318  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10031, delta: -10
10-26 15:03:10.318  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10039, delta: -15
10-26 15:03:10.319  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10060, delta: -1
10-26 15:03:10.319  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10102, delta: -45
10-26 15:03:10.319  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10068, delta: -17
10-26 15:03:10.319  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10034, delta: -12
10-26 15:03:10.319  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10131, delta: -30
10-26 15:03:10.319  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10118, delta: -21
10-26 15:03:10.319  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10087, delta: -6
10-26 15:03:10.320  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 2000, delta: -15
10-26 15:03:10.321  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10103, delta: -3
10-26 15:03:10.321  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10069, delta: -9
10-26 15:03:10.322  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10035, delta: -15
10-26 15:03:10.322  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10132, delta: -42
10-26 15:03:10.322  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10085, delta: -11
10-26 15:03:10.322  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10038, delta: -16
10-26 15:03:10.322  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10025, delta: -6
10-26 15:03:10.322  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1053, delta: -19
10-26 15:03:10.322  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10067, delta: -24
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10088, delta: -9
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1027, delta: -1
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10054, delta: -11
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10075, delta: -15
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10041, delta: -8
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10028, delta: -18
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10036, delta: -21
10-26 15:03:10.323  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1017, delta: -1
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10133, delta: -15
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10044, delta: -17
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10065, delta: -10
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10120, delta: -4
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10031, delta: -13
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10141, delta: -10
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1080, delta: -10
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10039, delta: -20
10-26 15:03:10.324  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10102, delta: -47
10-26 15:03:10.325  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10068, delta: -20
10-26 15:03:10.325  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10034, delta: -12
10-26 15:03:10.325  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10076, delta: -49
10-26 15:03:10.325  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10131, delta: -26
10-26 15:03:10.325  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10063, delta: -15
10-26 15:03:10.326  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1002, delta: -18
10-26 15:03:10.326  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10118, delta: -20
10-26 15:03:10.326  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10113, delta: -227
10-26 15:03:10.326  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10079, delta: -8
10-26 15:03:10.326  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1073, delta: -1
10-26 15:03:10.326  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10087, delta: -1
10-26 15:03:10.326  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 2000, delta: -35
10-26 15:03:10.327  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1068, delta: -5
10-26 15:03:10.327  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10137, delta: -15
10-26 15:03:21.581  1000  1754  1754 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10040; state: DISABLED
10-26 15:03:21.581  1000  1754  1754 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10040; state: DISABLED
10-26 15:03:21.582  1000  1754  1754 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10040; state: DISABLED
10-26 15:03:21.583  1000  1754  1754 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10040; state: DISABLED
10-26 15:03:21.584  1000  1754  2120 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10040; state: DISABLED
10-26 15:03:21.596  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10132, delta: -26
10-26 15:03:21.596  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10085, delta: -7
10-26 15:03:21.596  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10038, delta: -4
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10067, delta: -14
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10054, delta: -1
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10075, delta: -11
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10028, delta: -16
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10036, delta: -5
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10065, delta: -5
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10031, delta: -10
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10039, delta: -15
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10060, delta: -1
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10102, delta: -45
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10068, delta: -17
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10034, delta: -12
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10131, delta: -30
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10118, delta: -21
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 10087, delta: -6
10-26 15:03:21.597  1000  1754  2126 E KernelCpuUidActiveTimeReader: Negative delta from active time for uid: 2000, delta: -15
10-26 15:03:21.598  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10103, delta: -3
10-26 15:03:21.598  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10069, delta: -9
10-26 15:03:21.598  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10035, delta: -15
10-26 15:03:21.598  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10132, delta: -42
10-26 15:03:21.598  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10085, delta: -11
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10038, delta: -16
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10025, delta: -6
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1053, delta: -19
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10067, delta: -24
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10088, delta: -9
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1027, delta: -1
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10054, delta: -11
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10075, delta: -15
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10041, delta: -8
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10028, delta: -18
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10036, delta: -21
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1017, delta: -1
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10133, delta: -15
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10044, delta: -17
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10065, delta: -10
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10120, delta: -4
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10031, delta: -13
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10141, delta: -10
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1080, delta: -10
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10039, delta: -20
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10102, delta: -47
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10068, delta: -20
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10034, delta: -12
10-26 15:03:21.599  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10076, delta: -49
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10131, delta: -26
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10063, delta: -15
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1002, delta: -18
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10118, delta: -20
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10113, delta: -227
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10079, delta: -8
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1073, delta: -1
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10087, delta: -1
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 2000, delta: -35
10-26 15:03:21.600  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 1068, delta: -5
10-26 15:03:21.601  1000  1754  2126 E KernelCpuUidClusterTimeReader: Negative delta from cluster time for uid: 10137, delta: -15
10-26 15:03:21.603  1000  1754  2120 I ActivityManager: Start proc 20971:com.android.statementservice/u0a40 for service {com.android.statementservice/androidx.work.impl.background.systemjob.SystemJobService}
10-26 15:03:22.048 10040 20971 20971 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG5NZ6.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G5NZ6
10-26 15:03:22.051 10040 20971 20971 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayGD1YQ.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: GD1YQ
```

**Comment by Lau1406** [comment]
What worked for me was to install the sandboxed play services; but only after installing bunq (when I installed the play services etc before bunq, bunq would crash on startup)

**Comment by thestinger** [comment]
Please try again with the latest release.

**Comment by Lau1406** [comment]
Still doesn't work for me. I know that doesn't give much information, but unfortunately I don't have anything more.

**Comment by Lau1406** [comment]
I just want to give an update that it does seem to fully work now. I'm not sure what changed, but I'm happy with it. Fyi, adding contacts, phone and sms permissions didn't help. It does now also work without at least contacts and phone permissions

**Comment by wrl** [comment]
Running into this on a freshly-installed Pixel 8.
Build no: UD1A.230803.041.2023102300

No play services installed.

**Comment by thestinger** [comment]
> No play services installed.

The app requires it.
